### PR TITLE
[CS] Dont wrap packexp in extra layer of expansion

### LINKED ISSUE #79392: Parameter packs that conform to a protocol hierarchy are ambiguous when one protocol refines another
### Description

When there are multiple overloads of a non-parameter-pack function where one overload is strictly a refinement of the other, the type checker correctly chooses the most specific one:

```swift
protocol BaseP {}
protocol RefinedP: BaseP {}
struct Concrete: RefinedP {}

func f<T: BaseP>(_ t: T) { print("T: BaseP") }
func f<T: RefinedP>(_ t: T) { print("T: RefinedP") }

func y() {
    f(Concrete())  // "T: RefinedP"
}
```

However, if the argument lists are parameter packs constrained to the same protocols, it becomes ambiguous (see repro below).

### Reproduction

Full repro example (also at https://godbolt.org/z/8Mnh5boWK):

```swift
protocol BaseP {}
protocol RefinedP: BaseP {}
struct Concrete: RefinedP {}

func f<T: BaseP>(_ t: T) { print("T: BaseP") }
func f<T: RefinedP>(_ t: T) { print("T: RefinedP") }

func y() {
    f(Concrete())  // "T: RefinedP"
}

func g<each T: BaseP>(_ t: repeat each T) { print("each T: BaseP") }
func g<each T: RefinedP>(_ t: repeat each T) { print("each T: RefinedP") }

func z() {
    g(Concrete())
    // ^ error: ambiguous use of 'g'
}

y()
z()
```

### Expected behavior

I would expect the most specific overload to be chosen when all of the concrete arguments passed to `g()` conform to `RefinedP`.

### Environment

Occurs on the current nightly, but also in versions before this.

```
Swift version 6.2-dev (LLVM 5805166b4c9eb06, Swift 57234f8034befac)
Target: x86_64-unknown-linux-gnu
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jameesbrown**
Arguments that were already pack expansions were being wrapped in a second layer--preventing some would-be unambiguous overloads from resolving. This adds a check to avoid doing that.

Resolves: [#79392](https://github.com/swiftlang/swift/issues/79392)

### CODE REVIEW

File: lib/Sema/CSRanking.cpp [hunk 1]
```diff
@@ -703,25 +703,43 @@ bool CompareDeclSpecializationRequest::evaluate(
...
         auto paramTy = param.getOldType();
+        const auto &argIndices = matching->parameterBindings[paramIdx];
+        if (argIndices.empty())
+          continue;
 
         if (paramListInfo.isVariadicGenericParameter(paramIdx) &&
             isPackExpansionType(paramTy)) {
           SmallVector<Type, 2> argTypes;
-          for (auto argIdx : matching->parameterBindings[paramIdx]) {
+          bool isPackExpansionArg = false;
```
Comment (xedin) [inline lib/Sema/CSRanking.cpp:713]: Let's fix this by tightening the condition instead, like so:

```
diff --git a/lib/Sema/CSRanking.cpp b/lib/Sema/CSRanking.cpp
index acd0dffa4b5..7c13843c59d 100644
--- a/lib/Sema/CSRanking.cpp
+++ b/lib/Sema/CSRanking.cpp
@@ -704,10 +704,16 @@ bool CompareDeclSpecializationRequest::evaluate(
         const auto &param = params2[paramIdx];
         auto paramTy = param.getOldType();

+        auto argIndices = matching->parameterBindings[paramIdx];
+        if (argIndices.empty())
+          continue;
+
         if (paramListInfo.isVariadicGenericParameter(paramIdx) &&
-            isPackExpansionType(paramTy)) {
+            isPackExpansionType(paramTy) &&
+            (argIndices.size() > 1 ||
+             !isPackExpansionType(args[argIndices.front()].getOldType()))) {
           SmallVector<Type, 2> argTypes;
-          for (auto argIdx : matching->parameterBindings[paramIdx]) {
+          for (auto argIdx : argIndices) {
             // Don't prefer `T...` over `repeat each T`.
             if (args[argIdx].isVariadic())
               return completeResult(false);
@@ -721,7 +727,7 @@ bool CompareDeclSpecializationRequest::evaluate(
           continue;
         }

-        for (auto argIdx : matching->parameterBindings[paramIdx]) {
+        for (auto argIdx : argIndices) {
           const auto &arg = args[argIdx];
           // Always prefer non-variadic version when possible.
           if (arg.isVariadic())
[
```

I think this is more understandable because we establish that wrapping happens only either for multiple arguments or if a single argument is not already a pack expansion.

**Review by xedin — CHANGES_REQUESTED** [review]
Thank you for looking into this, I left a implementation suggesting inline.

File: lib/Sema/CSRanking.cpp (hunk 1 above)
Comment (jameesbrown) [reply lib/Sema/CSRanking.cpp]: Yes, I like this a lot better, thanks for pointing it out! I missed the `argIndices.size() > 1` condition.

**Review by xedin — APPROVED** [review]
Thank you!

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Comment by xedin** [comment]
@swift-ci please test Windows platform
