### PR TITLE
[Parser] Check let/var context when fix-it moving attributes from type to decl

### LINKED ISSUE #65705: @discardableResult fix-it is wrong when placed on variable declaration
**Description**
When placing @discardableResult on a variable declaration, the suggested fix it results in another fix-it, because @discardableResult doesnt seem to work on property declarations:

```
struct Foo {
    // suggested fix-it: Attribute can only be applied to declarations, not types - Replace 'var foo: @discardableResult ' with '@discardableResult var foo: '
    var foo: @discardableResult () -> Int
}
```

Using the fix-it results in the following, which requires another fix-it:
```
struct Foo {
    // suggested fix-it: '@discardableResult' attribute cannot be applied to this declaration - Remove '@discardableResult '
    @discardableResult var foo: () -> Int
}
```

which finally results in code that compiles, albeit without the result that the developer desires:
```
struct Foo {
    var foo: () -> Int
}
```

**Steps to reproduce**
Place @discardableResult on variable declaration's type.

**Expected behavior**
Fix it to completely remove @discardableResult, until @discardableResult is supported on property decls.

**Screenshots**
Screenshot 2023-05-05 at 10 36 57 AM
Screenshot 2023-05-05 at 10 37 33 AM

**Environment**
- Swift compiler version info 5.9
- Xcode version info 14.3
- Deployment target: any

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Very small diagnostic QOI one
When in a declaration, the fix-it to move the attribute cannot be applied in all cases. So doing extra checks to be more conservative and add a couple of more test for this. 

Resolves https://github.com/apple/swift/issues/65705

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

**Review by xedin — COMMENTED** [review]
Seems reasonable to me but @rintaro and @ahoppen should take a look.

File: lib/Parse/ParseDecl.cpp [hunk 1]
```diff
@@ -4034,13 +4034,20 @@ ParserStatus Parser::parseTypeAttribute(TypeAttributes &Attributes,
...
+      // the location of the @ sign, or we don't have confidence that the fixit
+      // will be right.
       if (!Attributes.empty() || StructureMarkers.empty() ||
-          StructureMarkers.back().Kind != StructureMarkerKind::Declaration ||
           StructureMarkers.back().Loc.isInvalid() ||
           peekToken().is(tok::equal)) {
         diagnose(Tok, diag::decl_attribute_applied_to_type);
+      } else if (InBindingPattern != PatternBindingState::NotInBinding ||
+                 StructureMarkers.back().Kind !=
+                     StructureMarkerKind::Declaration) {
```
Comment (ahoppen) [inline lib/Parse/ParseDecl.cpp:4046]: What are the cases where the last structure marker is not a declaration? AFAICT in all of your test cases I think the last structure marker should be a declaration but I might be wrong.

---

Also: What diagnostic do we produce now if the attribute is used in a generic position, e.g. 

```swift
struct Foo<A> {}
let a: Foo<@discardableResult () -> Int>
```

Comment (LucianoPAlmeida) [reply lib/Parse/ParseDecl.cpp:4046]: > AFAICT in all of your test cases I think the last structure marker should be a declaration but I might be wrong.

The last two `if let _: @discardableResult Int = a { }` give me `(swift::Parser::StructureMarkerKind) $3 = Statement`

> Also: What diagnostic do we produce now if the attribute is used in a generic position, e.g.

Diagnostic keep the same, it is just be more conservative when offering the move it fix-it in such cases offer only to remove it makes more sense.

**Review by ahoppen — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test MacOS platform

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test Windows platform
