### PR TITLE
[cxx-interop] Fix crash trying to export read accesors

### LINKED ISSUE #77304: compiler crash involving Mutex
### Description

I added a few lines to my project and the compiler is crashing. Need to enable C++ interop. Concise repro attached.

### Reproduction

```swift
import Synchronization

public class SomeClass { }

public class Thing {
    public static let rc = Mutex(SomeClass())
}
```

### Stack dump

```text
1.	Apple Swift version 6.0.2 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
2.	Compiling with the current language version
3.	While generating Clang header
4.	While printing 'Thing' (at /Users/holliday/Sculptura/SculpturaBase/Sources/SculpturaBase/Thing.swift:7:8)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000105b0e9ac llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x0000000105b0cc00 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x0000000105b0ef78 SignalHandler(int) + 292
3  libsystem_platform.dylib 0x000000018b4d4184 _sigtramp + 56
4  swift-frontend           0x000000010065058c swift::DeclAndTypePrinter::Implementation::visitVarDecl(swift::VarDecl*) + 532
5  swift-frontend           0x000000010065058c swift::DeclAndTypePrinter::Implementation::visitVarDecl(swift::VarDecl*) + 532
6  swift-frontend           0x00000001006562cc void swift::DeclAndTypePrinter::Implementation::printMembers<false, llvm::iterator_range<swift::DeclIterator>>(llvm::iterator_range<swift::DeclIterator>&&) + 692
7  swift-frontend           0x000000010065a4e0 void llvm::function_ref<void ()>::callback_fn<swift::DeclAndTypePrinter::Implementation::visitClassDecl(swift::ClassDecl*)::'lambda'()>(long) + 56
8  swift-frontend           0x000000010067ac20 swift::ClangClassTypePrinter::printClassTypeDecl(swift::ClassDecl const*, llvm::function_ref<void ()>, swift::DeclAndTypePrinter&) + 2888
9  swift-frontend           0x000000010064e79c swift::ASTVisitor<swift::DeclAndTypePrinter::Implementation, void, void, void, void, void, void>::visit(swift::Decl*) + 1296
10 swift-frontend           0x000000010064b90c swift::DeclAndTypePrinter::print(swift::Decl const*) + 448
11 swift-frontend           0x0000000100666058 (anonymous namespace)::ModuleWriter::write() + 4712
12 swift-frontend           0x0000000100667234 swift::printModuleContentsAsCxx(llvm::raw_ostream&, swift::ModuleDecl&, swift::SwiftToClangInteropContext&, bool, llvm::StringSet<llvm::MallocAllocator>&) + 1192
13 swift-frontend           0x00000001006750a4 swift::printAsClangHeader(llvm::raw_ostream&, swift::ModuleDecl*, llvm::StringRef, swift::FrontendOptions const&, swift::IRGenOptions const&, clang::HeaderSearch&) + 8824
14 swift-frontend           0x0000000100469ae0 swift::withOutputPath(swift::DiagnosticEngine&, llvm::vfs::OutputBackend&, llvm::StringRef, llvm::function_ref<bool (llvm::raw_pwrite_stream&)>) + 128
15 swift-frontend           0x00000001004be934 performEndOfPipelineActions(swift::CompilerInstance&) + 5752
16 swift-frontend           0x00000001004baf30 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 5200
17 swift-frontend           0x00000001004b8ea0 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 3572
18 swift-frontend           0x000000010043ff64 swift::mainEntry(int, char const**) + 3680
19 dyld                     0x000000018b11c274 start + 2840
```

### Expected behavior

No crash

### Environment

swift-driver version: 1.115 Apple Swift version 6.0.2 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
Target: arm64-apple-macosx15.0

### Additional information

[CompilerCrash.zip](https://github.com/user-attachments/files/17578462/CompilerCrash.zip)

### PR DESCRIPTION
**Pull request by Xazax-hun**
This is not yet supported, so skip exporting those accessors for now.

Fixes #77304

rdar://138944832

### CODE REVIEW

**Comment by Xazax-hun** [comment]
@swift-ci please smoke test

File: lib/PrintAsClang/DeclAndTypePrinter.cpp [hunk 1]
```diff
@@ -1949,8 +1949,9 @@ class DeclAndTypePrinter::Implementation
 
     if (outputLang == OutputLanguageMode::Cxx) {
       // FIXME: Documentation.
-      auto *getter = VD->getOpaqueAccessor(AccessorKind::Get);
-      printAbstractFunctionAsMethod(getter, /*isStatic=*/VD->isStatic());
+      // TODO: support read/modify accessors.
+      if (auto *getter = VD->getOpaqueAccessor(AccessorKind::Get))
+        printAbstractFunctionAsMethod(getter, /*isStatic=*/VD->isStatic());
       if (auto *setter = VD->getOpaqueAccessor(AccessorKind::Set))
```
Comment (egorzhdan) [inline lib/PrintAsClang/DeclAndTypePrinter.cpp:1955]: What would happen if a Swift property has a `_read` accessor and a setter? Could you please add a test just to make sure we don't crash?

File: test/Interop/SwiftToCxx/stdlib/swift-synchronization-in-cxx.swift [hunk 2]
```diff
@@ -0,0 +1,17 @@
+// RUN: %empty-directory(%t)
+
+// RUN: %target-swift-frontend -typecheck %s -typecheck -module-name UseSynchronization -enable-experimental-cxx-interop -clang-header-expose-decls=all-public -emit-clang-header-path %t/UseSynchronization.h
+// RUN: %FileCheck %s < %t/UseSynchronization.h
+
+// REQUIRES: objc_interop
```
Comment (egorzhdan) [inline test/Interop/SwiftToCxx/stdlib/swift-synchronization-in-cxx.swift:6]: Do we rely on Obj-C runtime in this test? Should this be `// REQUIRES: synchronization` instead?

File: lib/PrintAsClang/DeclAndTypePrinter.cpp (hunk 1 above)
Comment (Xazax-hun) [reply lib/PrintAsClang/DeclAndTypePrinter.cpp:1955]: Could you help me come up with an example? In the code snippets I tried swift synthesized a getter. Seemingly the only way I could prevent that is to have a property with `~Copyable` type. But in that case, a setter would not compile, I need a `_modify` accessor. 

If there is any other way to prevent Swift from synthesizing a getter (despite me only spelling out a `_read` accessor) let me know.

Comment (egorzhdan) [reply lib/PrintAsClang/DeclAndTypePrinter.cpp:1955]: I was thinking of something like this:
```swift
struct Foo {
  private var x: Int = 123
  var computedVar: Int {
    _read { yield &x }
    set { x = newValue }
  }
}
```
Would Swift synthesize a getter in this case?

Comment (Xazax-hun) [reply lib/PrintAsClang/DeclAndTypePrinter.cpp:1955]: I got this error:
```
20 |     _read { yield &x }
   |                   `- error: '&' may only be used to pass an argument to inout parameter
```

After removing the `&`, I still see `Foo::getComputedVar()` in the generated interop header, so I think the getter is being synthesized in this case.

**Comment by Xazax-hun** [comment]
@swift-ci please smoke test

**Review by egorzhdan — APPROVED** [review]
