### PR TITLE
[Sema] Fix nonisolated(unsafe) fix-it to replace full attribute text

### LINKED ISSUE #87342: Fix-it about removing nonisolated(unsafe) does not actually work
### Description

This code produces the warning:

```
'nonisolated(unsafe)' has no effect on property 'value', consider using 'nonisolated'
```

However, the fix-it suggested does not work and is also confusing:

```
Replace 'nonisolated' with 'nonisolated'
```

### Reproduction

```swift
class MyClass2 {
  nonisolated(unsafe) var value: Int? {
    get { 0 }
  }
}
```

### Expected behavior

This should instead suggest:

```
Replace 'nonisolated(unsafe)' with 'nonisolated'
```

### Environment

Apple Swift version 6.3-dev (LLVM d402ab9729f318e, Swift 2de856568572fc0)
Target: arm64-apple-macosx26.0
Build config: +assertions

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tosh7**
## Summary

  Fix the fix-it for `nonisolated(unsafe)` on computed properties and methods to correctly replace the full attribute text.

### Problem

  When `nonisolated(unsafe)` has no effect (e.g., on computed properties or methods), the compiler suggests:

  Replace 'nonisolated' with 'nonisolated'

スクリーンショット 2026-03-25 10 53 24

  This is confusing and not actionable — the fix-it text is identical on both sides.

### Fix

  The `fixItReplace` call in `visitNonisolatedAttr()` was using `attr->getStartLoc()`,which only covers the `nonisolated` keyword. Changed to `attr->getRange()`, which covers the full `nonisolated(unsafe)` attribute. This is consistent with all other `fixItReplace` calls in the same file.

  **Before:**
  Replace 'nonisolated' with 'nonisolated'

  **After:**
  Replace 'nonisolated(unsafe)' with 'nonisolated'

  ### Changes

  - `lib/Sema/TypeCheckAttr.cpp`: Use `attr->getRange()` instead of `attr->getStartLoc()` (1-line change)
  - `test/FixCode/nonisolated_unsafe_fixit.swift`: Add regression tests for the fix-it

  Resolves https://github.com/swiftlang/swift/issues/87342

### CODE REVIEW

File: test/FixCode/nonisolated_unsafe_fixit.swift [hunk 1]
```diff
@@ -0,0 +1,13 @@
+// RUN: %target-typecheck-verify-swift -swift-version 6
+
+// https://github.com/swiftlang/swift/issues/87342
+
+class MyClass {
+  nonisolated(unsafe) var computedValue: Int? {
+  // expected-warning@-1 {{'nonisolated(unsafe)' has no effect on property 'computedValue', consider using 'nonisolated'}}{{3-22=nonisolated}}
```
Comment (jamieQ) [inline test/FixCode/nonisolated_unsafe_fixit.swift]: I believe both of these cases are already exercised in other tests within the Concurrency directory. I think it's typically preferred to update existing tests with the fixit expectation, so perhaps this file can be removed in favor of updating those existing ones.

Comment (tosh7) [reply test/FixCode/nonisolated_unsafe_fixit.swift]: @jamieQ 
Thanks for the feedback! I've removed the standalone test file and added fix-it expectations to the existing tests:
- `test/Concurrency/actor_isolation.swift` — covers the method case
- `test/Concurrency/transfernonsendable_nonisolatedunsafe.swift` — covers the computed property case

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
Thank you for the fix, @tosh7 !
