### PR TITLE
[Profiler] A couple of coverage fixes

### LINKED ISSUE #65964: Swift 5.8 bumps Coverage Mapping version from 5 to 6 without using the corresponding format
**Description**

Swift 5.8 bumps the coverage mapping version to 6 from version 5 without adding the CWD / compilation directory as the first item of the file list. The LLVM code coverage mapping format [documentation](https://llvm.org/docs/CoverageMappingFormat.html#llvm-ir-representation) explains the difference between versions 5 and 6:

> There is one difference between versions 6 and 5:
>- The first entry in the filename list is the compilation directory. When the filename is relative, the compilation directory is combined with the relative path to get an absolute path. This can reduce size by omitting the duplicate prefix in filenames.

We have confirmed this by parsing the `__LLVM_COV,__llvm_covmap` section of the binary compiled by the Swift 5.8 compiler shipped Xcode 14.3.

We can compare the [Swift IRGen that writes the coverage filenames](https://github.com/apple/swift/blob/release/5.8/lib/IRGen/GenCoverage.cpp#L86-L99) to similar [code in Apple's fork of llvm-project](https://github.com/apple/llvm-project/blob/swift/release/5.8/clang/lib/CodeGen/CoverageMappingGen.cpp#L1680-L1694). The latter code in llvm-project correctly inserts the CWD as the first item in the list (specifically see L1684).

The fact that the filenames are written in the format of version 5 with version 6 specified in the header breaks downstream tools like `llvm-cov` that [parse code coverage data](https://github.com/apple/llvm-project/blob/f0fb631dd1a3a2988b23ba5057cd9106713cd0b4/llvm/lib/ProfileData/Coverage/CoverageMappingReader.cpp#L151-L181), breaking the generation of coverage reports.

We have also confirmed that the Swift 5.7 compiler shipped in Xcode 14.2 encodes version 5, which correctly matches the format of the filenames.

**Steps to reproduce**

1. Download [code_coverage.zip](https://github.com/apple/swift/files/11492915/code_coverage.zip)
2. `cd` into the uncompressed `code_coverage/` directory
3. Run `./build_and_test.sh` and see the error message from `llvm-cov`

Screenshot 2023-05-16 at 4 52 27 PM

In the screenshot above we can see that the first filename (Test.swift) is being interpreted as the CWD and is being prefixed to the second filename (Lib.swift).

**Expected behavior**

`llvm-cov` generates the report with no error message. This can be seen by running the same steps as above with Xcode 14.2.

**Environment**

- Swift compiler version info
```
swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
```

- Xcode version info 
```
Xcode 14.3
Build version 14E222b
```

- Deployment target: n/a

cc: @qyang-nj who has been investigating with me

### PR DESCRIPTION
**Pull request by hamishknight**
Update for coverage mapping format version 6, and avoid mapping generated code for now (we may want to revisit this in the future, however).

rdar://109562235
Resolves #65964

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

File: lib/IRGen/GenCoverage.cpp [hunk 1]
```diff
@@ -112,13 +128,21 @@ void IRGenModule::emitCoverageMaps(ArrayRef<const SILCoverageMap *> Mappings) {
...
     std::string FuncRecordName = "__covrec_" + llvm::utohexstr(NameHash);
 
-    unsigned FileID =
-        std::find(Files.begin(), Files.end(), M->getFilename()) - Files.begin();
+    // The file ID needs to be bumped by 1 to account for the working directory
+    // as the first element.
+    unsigned FileID = 1 +
+                      std::find(Files.begin(), Files.end(), M->getFilename()) -
+                      Files.begin();
+    assert(FileID < FilenameStrs.size());
```
Comment (hamishknight) [inline lib/IRGen/GenCoverage.cpp:136]: Now that I think about it, it really doesn't seem great that we're using `std::find` here, it'll be fine for cases where we have N output files for N input files (since we shard the coverage maps, so `Files` will be max 1 element), but for WMO, this will be O(N^2) for the number of files....

File: test/Profiler/coverage_macros.swift [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+
+@addMembers
+struct S2 {
+  // CHECK: sil_coverage_map{{.*}}variable initialization expression of coverage_macros.S2.(_storage
+  private var _storage = S1()
+
+  @accessViaStorage
+  var x: Int
+
+  // No coverage map for the initializer, as it gets subsumed.
```
Comment (bnbarham) [inline test/Profiler/coverage_macros.swift:41]: Worth adding a `CHECK-NOT`?

File: test/Profiler/coverage_relative_path_exec.swift [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+
+// To make sure this test is resilient to directory changes, we create nested directories inside of the
+// temporary test directory and assert those exist, or don't exist, in the emitted ir
+//
+// RUN: %empty-directory(%t)
+// RUN: mkdir -p %t/root/nested
+// RUN: echo "func coverage() {}" > %t/root/nested/coverage_relative_path.swift
+// RUN: cd %t/root
+
+// RUN: %target-build-swift -profile-generate -profile-coverage-mapping -Xfrontend -coverage-prefix-map -Xfrontend %/t/root=. -Xfrontend -disable-incremental-llvm-codegen -o %t/main %/t/root/nested/coverage_relative_path.swift
```
Comment (bnbarham) [inline test/Profiler/coverage_relative_path_exec.swift:15]: `-Xfrontend %/t/root=.` should be `-Xfrontend %t/root=.`?

File: test/Profiler/coverage_relative_path_exec.swift [hunk 4]
```diff
@@ -0,0 +1,25 @@
+// REQUIRES: profile_runtime
+// REQUIRES: executable_test
+// REQUIRES: OS=macosx
+
+// This test is to make sure llvm-cov can deal with a coverage-prefix-map.
+
+// To make sure this test is resilient to directory changes, we create nested directories inside of the
+// temporary test directory and assert those exist, or don't exist, in the emitted ir
```
Comment (bnbarham) [inline test/Profiler/coverage_relative_path_exec.swift:8]: We're not actually checking for the directory are we? Just that the function exists in the output of `llvm-cov show`.

File: test/Profiler/coverage_relative_path_exec.swift (hunk 3 above)
Comment (hamishknight) [reply test/Profiler/coverage_relative_path_exec.swift:15]: Good catch! I copy and pasted this from the other file, seems we should fix it there too

File: test/Profiler/coverage_macros.swift (hunk 2 above)
Comment (hamishknight) [reply test/Profiler/coverage_macros.swift:41]: This test uses `--implicit-check-not`

File: test/Profiler/coverage_relative_path_exec.swift (hunk 4 above)
Comment (hamishknight) [reply test/Profiler/coverage_relative_path_exec.swift:8]: llvm-cov barfs if it can't find the file, but yeah probably worth adding a check for the file

Comment (hamishknight) [reply test/Profiler/coverage_relative_path_exec.swift:8]: Oh, I realize now you are talking about the comment, I'll update that

File: test/Profiler/coverage_macros.swift (hunk 2 above)
Comment (bnbarham) [reply test/Profiler/coverage_macros.swift:41]: Oh I missed that. I actually didn't even know that was an option, cool stuff!
