### PR TITLE
[CSSimplify] Account for tuple splat when resolving closure parameters

### LINKED ISSUE #62390: Compiler is extremely slow to compile simple closure
**Description**
While trying today's advent of code task as fast as possible (yes, I was slightly frustated), I encountered a weird bug in the compiler that causes it to compile extremely slowly. The simplest example that still exhibits this behaviour is a simple swift file of 11 lines that causes swiftc to run for over 2 minutes.

**Steps to reproduce**
Create a swift file with the following contents:

```swift
extension Sequence where Element: Numeric {
    public func sum() -> Element {
        self.reduce(0, +)
    }
}

let foo: [(Int, Int, Int, Int)] = []

print(foo.map { a, b, c, d in
    return ((a <= c && b >= d) || (c <= a && d >= b)) ? 1 : 0
}.sum())
```

Try to build it with swiftc.

**Expected behavior**
I expect the compiler to compile such a single file in a matter of a few milliseconds.

**Environment**
- **Swift version:**
  swift-driver version: 1.62.15 Apple Swift version 5.7.1 (swiftlang-5.7.1.135.2 clang-1400.0.29.51)
  Target: x86_64-apple-macosx13.0
- **Xcode version (Shouldn't really matter, as this happens on linux using Swift 5.7 as well)**
  Xcode 14.1
  Build version 14B47
- **Deployment Target**
  macOS Ventura 13.0

### PR DESCRIPTION
**Pull request by xedin**
SE-0110 allows tuple slat between function types. The solver needs to
account for that when trying to infer parameter types from context
while resolving a closure in order to propagate types and speed up
type-checking.

Resolves: https://github.com/apple/swift/issues/62390

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test source compatibility

File: validation-test/Sema/type_checker_perf/fast/issue-62390.swift [hunk 1]
```diff
@@ -0,0 +1,11 @@
...
+// REQUIRES: tools-release,no_asan
+
+// https://github.com/apple/swift/issues/62390
+// Compiler is extremely slow to compile simple closure
+
+func testFn<U>(_: ((Int, Int)) -> U) {}
+
+testFn { (a, _) in
+  return ((a <= a && a >= a) || (a <= a && a >= a)) // Ok
+}
```
Comment (AnthonyLatsis) [inline validation-test/Sema/type_checker_perf/fast/issue-62390.swift:11]: Is there any reason to turn this into a scale test over `||`?

**Review by AnthonyLatsis — COMMENTED** [review]
Huh, so it really did assume `a` was *the* tuple rather than an element?

File: validation-test/Sema/type_checker_perf/fast/issue-62390.swift (hunk 1 above)
Comment (AnthonyLatsis) [reply validation-test/Sema/type_checker_perf/fast/issue-62390.swift:11]: Probably not, the body of the closure was not to blame for the perf issue.

Comment (xedin) [reply validation-test/Sema/type_checker_perf/fast/issue-62390.swift:11]: Not really indeed, the issue is with how types are transferred into a closure.

**Review by hborla — APPROVED** [review]
