### PR TITLE
Change the definition of MALLOC_ALIGN_MASK so it should always be correct on all platforms.

### LINKED ISSUE #58486: `MALLOC_ALIGN_MASK` is incorrectly defined on some platforms
`MALLOC_ALIGN_MASK` is incorrectly defined on those platforms that take the fallback path in its definition. It is currently defined to be:

```c++
// Unknown alignment, but the standard requires alignment suitable for the largest
// standard types.
#  define MALLOC_ALIGN_MASK std::max(alignof(void *), alignof(double))
```

This definition is incorrect because it produces a power of two, _not_ a mask (because it needs to have `1` subtracted from it.) We can solve this problem for all platforms by redefining the macro to:

```c++
#define MALLOC_ALIGN_MASK (std::max(alignof(std::max_align_t), __STDCPP_DEFAULT_NEW_ALIGNMENT__) - 1)
```

### PR DESCRIPTION
**Pull request by grynspan**
Change the definition of `MALLOC_ALIGN_MASK` so it should always be correct on all platforms.

The default path that defines `MALLOC_ALIGN_MASK` does so incorrectly, producing a power-of-two value instead of a mask. This change resolves the issue by redefining `MALLOC_ALIGN_MASK` for all platforms in terms of the C/C++ standard `max_align_t` type (which exists for this purpose.)

Resolves #58486.

### CODE REVIEW

File: stdlib/public/runtime/Heap.cpp [hunk 1]
```diff
@@ -28,30 +28,12 @@
...
-// standard types.
-#  define MALLOC_ALIGN_MASK std::max(alignof(void *), alignof(double))
-
-#endif
+/// The guaranteed alignment mask for a pointer returned from \c malloc().
+///
+/// The C and C++ standards defined \c max_align_t as a type whose alignment is
+/// at least that of every scalar type. It is the lower bound for the alignment
+/// of any pointer returned from \c malloc().
+static constexpr size_t MALLOC_ALIGN_MASK = alignof(std::max_align_t) - 1;
```
Comment (mikeash) [inline stdlib/public/runtime/Heap.cpp:36]: Malloc is guaranteed to have at least this alignment, but some systems guarantee more. For example, `alignof(std::max_align_t)` is `8` on 32-bit Darwin, but malloc still gives us 16-byte alignment there. I'd suggest keeping the platform-specific constants and using this construct for the fallback.

**Review by mikeash — CHANGES_REQUESTED** [review]

**Review by mikeash — APPROVED** [review]
