### PR TITLE
[Concurrency] Remove _unsafeInheritExecutor from public APIs, use #isolation

### LINKED ISSUE #69659: `withUnsafeContinuation` doesn't inherit Actor executor during single await call
**Description**

Encountered a failure with `MainActor.shared.assertIsolated()` in the following code:

```swift
@MainActor
func doSomething() async {
    await withUnsafeContinuation { continuation in
        if #available(macOS 14.0, *) {
            MainActor.shared.assertIsolated()
        }

        continuation.resume(returning: ())
    }
}

await Task.detached {
    await doSomething()
}.value
```

**Expected behavior**

The `MainActor.shared.assertIsolated()` call should not fail.

**Environment**

- Swift compiler version info: swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
- Xcode version info: Xcode 15.0.1 Build version 15A507
- Deployment target: arm64-apple-macosx14.0

**Issue Details**

I suspect that the optimization which omits `hop_to_executor` during single await call does not account for `_unsafeInheritExecutor`.

This problem only appear when `doSomething` has single await call. The following code does work.

```swift
@MainActor
func doSomething() async {
    print("Hello") // write something
    await withUnsafeContinuation { continuation in
        if #available(macOS 14.0, *) {
            MainActor.shared.assertIsolated()
        }

        continuation.resume(returning: ())
    }
}

await Task.detached {
    await doSomething()
}.value
```

When the MainActor isolated async function (funcA) has only single await call (funcB),
we doesn't need hop to MainActor executor before calling funcB because hop to general executor when calling funcB.
However, when funcB has `_unsafeInheritExecutor`, we need hop to MainActor executor before calling it.

Inspecting the SIL, it seems that hop to MainActor has been erroneously removed by the optimization process.

SIL outputs here:
https://gist.github.com/kntkymt/3f8af33b98f238128a0eba638b74b81d

### PR DESCRIPTION
**Pull request by ktoso**
We should be using the `#isolation` macro in all APIs where `_unsafeInheritExecutor` was used before; 

This handles it just for the continuation APIs, more to follow soon.

resolves rdar://125307764
resolves #69659

--- 

It seems it runs into availability issues though? 

```
/Users/ktoso/code/swift-project/swift/stdlib/public/Concurrency/CheckedContinuation.swift:292:40: error: 'isolation()' is only available in macOS 10.15 or newer
╰─ /Users/ktoso/code/swift-project/swift/stdlib/public/Concurrency/CheckedContinuation.swift:292:39: note: expanded code originates here
//    @available(SwiftStdlib 5.1, *) <<<<<<< this is macOS 10.15 (SwiftStdlib 5.1:macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0)
//    @inlinable
//    @_unavailableInEmbedded
//    public func withCheckedContinuation<T>(
//      isolation: isolated (any Actor)? = #isolation,
//      function: String = #function,
290 │   _ body: (CheckedContinuation<T, Never>) -> Void
291 │ ) async -> T {
292 │   return await withUnsafeContinuation { <<<<<<< this now has #isolation
    ╭─── /Users/ktoso/code/swift-project/swift/stdlib/public/Concurrency/CheckedContinuation.swift
    │290 │
    │291 │
    │292 │                                       #isolation
    │    │                                        ╰─ error: 'isolation()' is only available in macOS 10.15 or newer
    ╰──────────────────────────────────────────────────────────────────────────────────────────────
293 │     body(CheckedContinuation(continuation: $0, function: function))
294 │   }
```

where the unsafe is:

```
@available(SwiftStdlib 5.1, *)
@_alwaysEmitIntoClient // removing this doesn't matter
public func withUnsafeContinuation<T>(
  isolation: isolated (any Actor)? = #isolation,
  _ fn: (UnsafeContinuation<T, Never>) -> Void
) async -> T {
  return await Builtin.withUnsafeContinuation {
    fn(UnsafeContinuation<T, Never>($0))
  }
}
```

### CODE REVIEW

File: stdlib/public/Concurrency/CheckedContinuation.swift [hunk 1]
```diff
@@ -282,18 +282,32 @@ extension CheckedContinuation {
...
   return await withUnsafeContinuation {
     body(CheckedContinuation(continuation: $0, function: function))
   }
 }
 
+@available(SwiftStdlib 5.1, *)
+@_unsafeInheritExecutor // ABI compatibility with Swift 5.1
+@inlinable
+@_unavailableInEmbedded
+public func __abi_withCheckedContinuation<T>(
```
Comment (ktoso) [inline stdlib/public/Concurrency/CheckedContinuation.swift:301]: TODO: add the appropriate sildeclname

File: stdlib/public/Concurrency/PartialAsyncTask.swift [hunk 2]
```diff
@@ -598,9 +598,20 @@ internal func _resumeUnsafeThrowingContinuationWithError<T>(
...
+) async -> T {
+  return await Builtin.withUnsafeContinuation {
+    fn(UnsafeContinuation<T, Never>($0))
+  }
+}
+
+@available(SwiftStdlib 5.1, *)
+@_unsafeInheritExecutor
+@_alwaysEmitIntoClient
+public func __abi_withUnsafeContinuation<T>(
```
Comment (ktoso) [inline stdlib/public/Concurrency/PartialAsyncTask.swift:614]: TODO: not strictly necessary since @_alwaysEmitIntoClient

**Comment by ktoso** [comment]
Unblocked by https://github.com/apple/swift/pull/72813

**Comment by ktoso** [comment]
Now this still needs some work about backdeployed + unavailable in embedded I think, otherwise it'd be good to go

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
So it turns out solving this issue took a few fixes in related language features and quite some time, but the hackathon is where we kicked off the diagnosis and fixes, so I'd like to thank you @kntkymt for collaborating on this back then!

**Comment by ktoso** [comment]
@swift-ci please smoke test
