### PR TITLE
[AutoDiff] Fix adjoints for loop-local active values

### LINKED ISSUE #78264: Adjoint for active values in loops are just wrong
### Description

Kudos to @kovdan01 for initial analysis of this issue.

It turns out that adjoints for active values in loops are just plain wrong. Consider the reproducer. As one case see, the gradient for `repeat_while_loop` is wrong, while gradient for `while_loop` is correct. Even more, if we'd replace the code in loop by `result *= x` then `repeat_while_loop` case will start working.

Why it is so?

The loop body for `repeat_while_loop` looks like as follows (removed loop condition calculation for brevity):

```llvm
  br bb1                                          // id: %10

bb1:                                              // Preds: bb2 bb0
  %11 = metatype $@thin Float.Type                // user: %16
  %12 = begin_access [read] [static] %2           // users: %14, %13
  %13 = load [trivial] %12                        // user: %16
  end_access %12                                  // id: %14
  // function_ref static Float.* infix(_:_:)
  %15 = function_ref @$sSf1moiyS2f_SftFZ : $@convention(method) (Float, Float, @thin Float.Type) -> Float // user: %16
  %16 = apply %15(%13, %0, %11) : $@convention(method) (Float, Float, @thin Float.Type) -> Float // user: %18
  %17 = begin_access [modify] [static] %2         // users: %18, %19
  store %16 to [trivial] %17                      // id: %18
  end_access %17                                  // id: %19
...
  cond_br %39, bb2, bb3                           // id: %40

bb2:                                              // Preds: bb1
  br bb1
bb3:                                              // Preds: bb1
...
```

The key thing here is active `%13` (which is essentially a `result` value), so we need to generate adjoint for it. AutoDiff code uses notion of "adjoint for value X in basic block Y`. This is fine for code without loops. And is just plain wrong for values inside loops as it should be "adjoint for value X in basic block Y on loop iteration Z`. The values are different at different loop iterations. Thus their adjoints should be distinct as well. Without this we're ending with artificial adjoint accumulations (since single adjoint value is shared between loop iterations) and wrong results.

So, when generating pullback for this loop body we need to ensure that initial value for adjoint of `%13` is zero on each iteration. And then perform the usual pullback cloning that involves adjoint value generation and accumulation. We don't do this, so essentially we're accumulating into adjoint from the previous loop iteration.

Sure, if things are so broken, why we have not noticed this before? I would say: coincidence.

For the code like `result *= x` we do not have these extra active values, `Float.*=` takes adjoint buffer as an inout argument and perform proper adjoint generation there.

`while / for` case is more interesting. Here the code looks like as follows:
```llvm
  br bb1                                          // id: %10

bb1:                                              // Preds: bb2 bb0
...
  cond_br %21, bb2, bb3                           // id: %22

bb2:                                              // Preds: bb1
  %23 = metatype $@thin Float.Type                // user: %28
  %24 = begin_access [read] [static] %2           // users: %26, %25
  %25 = load [trivial] %24                        // user: %28
  end_access %24                                  // id: %26
  // function_ref static Float.* infix(_:_:)
  %27 = function_ref @$sSf1moiyS2f_SftFZ : $@convention(method) (Float, Float, @thin Float.Type) -> Float // user: %28
  %28 = apply %27(%25, %0, %23) : $@convention(method) (Float, Float, @thin Float.Type) -> Float // user: %30
  %29 = begin_access [modify] [static] %2         // users: %30, %31
  store %28 to [trivial] %29                      // id: %30
  end_access %29                                  // id: %31
...
  br bb1                                          // id: %41

bb3:                                              // Preds: bb1
  %42 = begin_access [read] [static] %2           // users: %44, %43
  %43 = load [trivial] %42                        // user: %47
  end_access %42                                  // id: %44
```

So, we're having loop header (`bb1`) first, then loop body and finally the code after loop `bb3`. Now, we're having a code that propagates adjoints of active values into predecessor BBs while doing function traverse in reverse post-order. Here, we first visit `bb3`, then `bb1`. Inside `bb1` we're realizing that there are active values (`%25` and `%28`) in predecessor `bb2`, so we are taking their adjoints in `bb1` and propagating them into `bb2`. Since no adjoints were defined before, they will be zero initialized and further propagated. And since coincidentally it is a loop header, we're ending into zero-initializing them in each loop iteration in a pullback as pullback to loop header will be executed after loop body. Everything magically works.

The situation with repeat loop is in reverse, there is no "loop header" BB in the common sense, there is a "loop footer" instead fused into loop body. So, the adjoints for `%13` and `%16` will be first zero-initialized in pullback block corresponding to `bb3` and then further propagated to `bb1`. So, no zero-initialization on each loop iteration, adjoint values will be reused from previous loop iteration, and wrong results will be provided.

It seems to me that we need to perform explicit adjoint zeroing inside loop headers in pullback cloner

### Reproduction

```swift
import _Differentiation

func repeat_while_loop(_ x: Float) -> Float {
    var result = x
    var i = 0
    repeat {
      result = result * x
      i += 1
    } while i < 2
    return result
}

func while_loop(_ x: Float) -> Float {
    var result = x
    var i = 0
    while i < 2 {
      result = result * x
      i += 1
    }
    return result
}

print(valueWithGradient(at: 2, of: repeat_while_loop))
print(valueWithGradient(at: 2, of: while_loop))
```

### Expected behavior

Correct gradient calculation for both cases

### Environment

Swift version 6.2-dev (LLVM e404f8897f17aff, Swift 5a68861c9d0407a)
Target: arm64-apple-macosx15.0

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by kovdan01**
Fixes #78264

### CODE REVIEW

**Comment by kovdan01** [comment]
Tagging @asl @JaapWijnen @rxwei

**Comment by asl** [comment]
@swift-ci please test

**Comment by asl** [comment]
@swift-ci please test

**Comment by kovdan01** [comment]
Would be glad to see feedback from everyone interested

**Comment by asl** [comment]
@swift-ci please test

**Comment by kovdan01** [comment]
Would be glad to see feedback from everyone interested

**Comment by kovdan01** [comment]
Would be glad to see feedback from everyone interested

**Comment by kovdan01** [comment]
Would be glad to see feedback from everyone interested

**Comment by clackary** [comment]
@kovdan01 I cherrypicked this change onto `swift-DEVELOPMENT-SNAPSHOT-2025-02-20-a` and built a toolchain. I used this toolchain to build all our internal swift projects, and everything builds successfully on macOS.

**Comment by asl** [comment]
The change looks ok to me. The explanation of the problem is at https://github.com/swiftlang/swift/issues/78264

Long story short: SSA values in the loop body should be considered as "new values" at each loop iteration. We used to reuse the adjoints for them before this patch (though we should create distinct adjoints on each loop iteration).

This used to work before due to a particular CFG generated for for-style loops. As a result we've been lucky and simply zeroed the adjoints in the loop header on each iteration (loop header BB was the first BB we encountered the adjoint, so it was initialized there and this zero-initialization happened on each loop iteration effectively producing new adjoint value).

However, this stopped to work for while-style loops as the CFG is different and while we produced adjoint initialization, it happened outside the loop and therefore the adjoint values got reused from the previous loop iteration.

@rxwei will you please take a look as a second pair of eyes? :)

**Comment by kovdan01** [comment]
> However, this stopped to work for while-style loops

To bit a bit more precise: it not stopped working, it just never worked for repeat-while loops (if not never, at least, for several latest years). For regular while loops, we had the same situation that we observed with for loops, when the behavior looked correct because of a particular CFG.

**Comment by kovdan01** [comment]
> @kovdan01 I cherrypicked this change onto `swift-DEVELOPMENT-SNAPSHOT-2025-02-20-a` and built a toolchain. I used this toolchain to build all our internal swift projects, and everything builds successfully on macOS.

@clackary Great, thanks for letting me know! BTW, does "everything builds successfully on macOS" imply that your internal tests are also passing?

**Comment by clackary** [comment]
> your internal tests are also passing?

@kovdan01 No, just the compile-time checks for now. Further testing is more of a manual process at the moment, but I can get to testing a few projects this week.

**Comment by clackary** [comment]
@kovdan01 I was able to finish testing a bunch of our internal projects. The issue we discussed earlier was caused by a flaw in my invocation, so nothing to worry about there. This looks good from my end.

**Comment by kovdan01** [comment]
@rxwei Could you please take a look at this PR? Thanks!

**Comment by asl** [comment]
@swift-ci please smoke test

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 1]
```diff
@@ -2128,6 +2128,23 @@ PullbackCloner::PullbackCloner(VJPCloner &vjpCloner)
...
+static SILValue getArrayValue(ApplyInst *ai) {
+  SILValue arrayValue;
+  for (auto use : ai->getUses()) {
+    auto *dti = dyn_cast<DestructureTupleInst>(use->getUser());
+    if (!dti)
+      continue;
+    assert(!arrayValue && "Array value already found");
+    // The first `destructure_tuple` result is the `Array` value.
+    arrayValue = dti->getResult(0);
+#ifdef NDEBUG
```
Comment (asl) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp:2140]: Consider using `ASSERT` / `DEBUG_ASSERT` from swift/Basic/Assertions.h instead of conditional asserts, etc. Overall, the intention is to get rid of conditional asserts in new code (and avoid `#ifdef NDEBUG`).

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 2]
```diff
@@ -2472,6 +2489,137 @@ bool PullbackCloner::Implementation::run() {
...
+          //   %2 = apply %1<Float>(%0)
+          //   (%3, %4) = destructure_tuple %2
+          //   %5 = mark_dependence %4 on %3
+          //   %6 = pointer_to_address %6 to [strict] $*Float
+          // Since %6 is active, %3 (which is an array) must also be active.
+          // Thus, adjoint for %3 will be zeroed if needed. Ensure that expected
+          // invariants hold and then skip.
+          if (auto *ai = getAllocateUninitializedArrayIntrinsicElementAddress(
+                  bbActiveValue)) {
+#ifndef NDEBUG
```
Comment (asl) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp:2603]: ditto

**Review by asl — APPROVED** [review]
This LGTM module few asserts-related nits. Please fix them and I think we're good to go!

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp (hunk 1 above)
Comment (kovdan01) [reply lib/SILOptimizer/Differentiation/PullbackCloner.cpp]: I've put this `break;` under `DEBUG_ASSERT_enabled` condition since having the check present increases iterations count and this should probably not be done in non-debug builds. Please let me know if this looks reasonable for you.

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp (hunk 2 above)
Comment (kovdan01) [reply lib/SILOptimizer/Differentiation/PullbackCloner.cpp]: Deleted this preprocessor condition and switched to `ASSERT`. These checks should be OK in terms of negative performance impact, so `ASSERT` seems preferrable over `DEBUG_ASSERT`

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 3]
```diff
@@ -2439,6 +2456,134 @@ bool PullbackCloner::Implementation::run() {
...
+          LLVM_DEBUG(llvm::dbgs()
+                     << "zeroing its adjoint value in loop header: "
+                     << bbActiveValue);
+          setAdjointValue(bb, bbActiveValue,
+                          makeZeroAdjointValue(getRemappedTangentType(
+                              bbActiveValue->getType())));
+          continue;
+        }
+
+        assert(getTangentValueCategory(bbActiveValue) ==
```
Comment (kovdan01) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp:2510]: @asl As far as I understood, there is an intention to enable most checks in all builds including release ones. Given that, should I switch these and other remaining regular `assert` to `ASSERT`?

Comment (asl) [reply lib/SILOptimizer/Differentiation/PullbackCloner.cpp:2510]: Let's switch while here, yes

Comment (kovdan01) [reply lib/SILOptimizer/Differentiation/PullbackCloner.cpp]: Done, see ddfc5732b89d5ff60c339748512758c7d2a22010

**Comment by asl** [comment]
@swift-ci please test

**Comment by asl** [comment]
@swift-ci please test
