### PR TITLE
[Sema] Check for availability of result type of implicit literal initializer

### LINKED ISSUE #61890: Missing availability diagnostic on literal implicit init base type
**Describe the bug**
No diagnostic is being emitted when base type for implicit init from literal expression is unavailable.

```swift
@available(*, unavailable)
struct S: ExpressibleByIntegerLiteral {
  init(integerLiteral value: Int) {}
}
@available(*, unavailable)
typealias IntegerLiteralType = S

let i = 0 // implicit resolves to S(integerLiteral: 0) but S is unavailable so we should emit availability diagnostic
```
**Steps To Reproduce**
1. Try compile the snippet above
...

**Expected behavior**
Unavailable diagnostic should be emitted.

**Environment (please fill out the following information)**
 - Xcode Version/Tag/Branch: main at 66f67697577893a94ba4839e2abb18fd17550aa4

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
For literal expressions check availability of the resulting type of the implicit literal as well in addition to the initializer checking.

Resolves  https://github.com/apple/swift/issues/61890

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

File: test/Sema/availability_literals_inferred.swift [hunk 1]
```diff
@@ -0,0 +1,23 @@
+// RUN: %target-typecheck-verify-swift -swift-version 5
+
+// REQUIRES: OS=macosx
```
Comment (tshortli) [inline test/Sema/availability_literals_inferred.swift:3]: At first glance it doesn't seem like this test should require `macosx` since the availability annotations specify universal unavailability.

File: lib/Sema/TypeCheckAvailability.cpp [hunk 2]
```diff
@@ -3261,6 +3261,12 @@ class ExprAvailabilityWalker : public ASTWalker {
         // Regex literals require both the Regex<Output> type to be available,
         // as well as the initializer that is implicitly called.
         diagnoseDeclRefAvailability(Context.getRegexDecl(), Range);
+      } else if (auto literalType = LE->getType()) {
```
Comment (hamishknight) [inline lib/Sema/TypeCheckAvailability.cpp:3264]: Instead of making this an `else if`, I think we can just remove the regex case here as a regex literal is always typed as `Regex<Output>`.

**Review by hamishknight — COMMENTED** [review]
Thanks!

**Review by tshortli — APPROVED** [review]

**Review by hamishknight — APPROVED** [review]

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test MacOS platform
