### PR TITLE
[CS] Deep-equality match OpenedArchetypeTypes

### LINKED ISSUE #79623: Swift 6.1 regression creating `AnyHashable` from existential with parameter pack
### Description

Code involving `AnyHashable`, existentials, and parameter packs that used to compile in Swift 6.0.3 no longer compiles in 6.1.

### Reproduction

```swift
protocol Bar<T>: Hashable {
  associatedtype T
}
struct Foo<each T> {
  let x: any Bar<(repeat each T)>
  static func == (lhs: Foo, rhs: Foo) -> Bool {
    AnyHashable(lhs.x) == AnyHashable(rhs.x)     // 🛑
    /*
    // Workaround:

    let lhs = lhs.x
    let rhs = rhs.x
    return AnyHashable(lhs) == AnyHashable(rhs)  // ✅
     */
  }
}
```

### Expected behavior

I expect this code to still compile in 6.1.

### Environment

swift-driver version: 1.120.2 Apple Swift version 6.1 (swiftlang-6.1.0.106.4 clang-1700.0.9.2)
Target: arm64-apple-macosx15.0

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jameesbrown**
Resolves: [swiftlang/swift#79623](https://github.com/swiftlang/swift/issues/79623)

When comparing two distinct `OpenedArchetypeType`s, `matchTypes` currently does not check for deep equality. Because the types are not trivially equal, this results in incorrect mismatches.

This change resolves the issue by introducing a deep equality check when the two types have the same interface type and UUID.

### CODE REVIEW

**Comment by jameesbrown** [comment]
@hamishknight If you have a moment, I'd appreciate your thoughts on this!

File: lib/Sema/ConstraintSystem.cpp [hunk 1]
```diff
@@ -1087,6 +1087,14 @@ Type ConstraintSystem::getFixedTypeRecursive(Type type, TypeMatchOptions &flags,
     return getFixedTypeRecursive(simplified, flags, wantRValue);
   }
 
+  if (type->is<OpenedArchetypeType>()) {
```
Comment (jameesbrown) [inline lib/Sema/ConstraintSystem.cpp:1090]: Didn't `||` this with above because surrounding code suggests otherwise.

File: lib/Sema/ConstraintSystem.cpp [hunk 2]
```diff
@@ -1087,6 +1087,14 @@ Type ConstraintSystem::getFixedTypeRecursive(Type type, TypeMatchOptions &flags,
...
+    auto simplified = simplifyType(type);
+    if (simplified.getPointer() == type.getPointer())
+      return type;
+
+    return getFixedTypeRecursive(simplified, flags, wantRValue);
```
Comment (slavapestov) [inline lib/Sema/ConstraintSystem.cpp:1095]: Calling getFixedTypeRecursive() on the result of simplifyType() is unnecessary, because a type that is reduced wrt. simplifyType() is already reduced wrt. getFixedTypeRecursive().

However, it should also be unnecessary to special-case OpenedArchetypeType in this manner in the first place, and the `type->is<TupleType>()` special case above looks problematic for this reason as well. Perhaps the underlying problem is that somewhere we're calling `getFixedTypeRecursive()` and we should call `simplifyType()` instead?

**Review by slavapestov — CHANGES_REQUESTED** [review]

**Comment by slavapestov** [comment]
Oh, I wonder if the problem is that matchTypes() needs to implement support for matching opened existential types. If two opened existential types have the same interface type and UUID but different substitution maps, we need to generate Bind constraints between the corresponding replacement types in this substitution maps.

Compare this with how matchTypes() handles, BoundGenericNominalTypes. If you have, eg `G<Int>` vs `G<$T0>`, where both nominal types were instantiated from the same declaration `G`, but they have different generic arguments, and `$T0` is a type variable. We don't just fail the constraint; instead, we generate a `Bind` constraint `Int == $T0`, which may or may not succeed later.

A match between two distinct PrimaryArchetypeTypes can never succeed, because they correspond to distinct generic parameters. But two distinct OpenedArchetypeTypes may in fact match, if they have the same interface type and UUID.

File: lib/Sema/ConstraintSystem.cpp (hunk 2 above)
Comment (jameesbrown) [reply lib/Sema/ConstraintSystem.cpp:1095]: Thanks! I see how it's unnecessary now. My former reasoning: I saw that [at the top of matchTypes](https://github.com/swiftlang/swift/blob/737b5ec92433104ba975021f41e63da78723eff0/lib/Sema/CSSimplify.cpp#L6971), we already call `getFixedTypeRecursive()` for both types before proceeding. My initial thought was to add a `simplifyType()` call there, but I placed it here instead because I assumed the intent of calling `getFixedTypeRecursive()` was also to obtain the simplified type if needed. I like what you suggested in your other comment, will follow up there.

**Comment by jameesbrown** [comment]
@slavapestov Thanks for looking at this! I agree `matchTypes()` is lacking explicit support for opened existential types. I got as far as noticing they had same interface type and UUID but different substitution maps, but didn't think to generate Bind constraints there. That seems like a much more robust approach than what I have here. I’ll work on revising my solution accordingly.

**Comment by slavapestov** [comment]
It looks like support for matching substitution maps in this manner is already implemented, because we do something similar for opaque return types:

```
    // Opaque archetypes are globally bound, so we can match them for deep
    // equality.
    case TypeKind::OpaqueTypeArchetype: {
      auto opaque1 = cast<OpaqueTypeArchetypeType>(desugar1);
      auto opaque2 = cast<OpaqueTypeArchetypeType>(desugar2);
      
      if (opaque1->getDecl() == opaque2->getDecl()) {
        conversionsOrFixes.push_back(ConversionRestrictionKind::DeepEquality);
      }
      break;
    }
```

You just need a different check for opened existentials (they don't have a decl).

**Comment by jameesbrown** [comment]
Oh yes, I see it now — in `matchDeepEqualityTypes` we already compare substitution maps. So it sounds like (as you’re saying) we just need to ensure opened existentials don’t fall through here. Thanks!

File: lib/Sema/CSSimplify.cpp [hunk 3]
```diff
@@ -3946,6 +3946,23 @@ ConstraintSystem::matchDeepEqualityTypes(Type type1, Type type2,
                       locator.withPathElement(ConstraintLocator::ParentType));
   }
 
+  // Handle opened archetype types.
```
Comment (slavapestov) [inline lib/Sema/CSSimplify.cpp:3949]: Nitpick: Can you move this up to where the opaque archetype case also appears?

**Review by slavapestov — APPROVED** [review]

File: lib/Sema/CSSimplify.cpp (hunk 3 above)
Comment (jameesbrown) [reply lib/Sema/CSSimplify.cpp:3949]: Would it be useful to also move the switch case to where opaque archetype is as well?

Comment (jameesbrown) [reply lib/Sema/CSSimplify.cpp]: Fixed this, I also moved the switch case to beneath TypeKind::OpaqueArchetype so that they appear in the same order in both places (checked for fall through logic first).

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@jameesbrown Thank you for the fix!

**Comment by slavapestov** [comment]
This is also rdar://145694924

**Review by xedin — COMMENTED** [review]
I think it is good for valid code but might not be for diagnostics because other places here handle mismatches explicitly. Could you please add a few test-cases where opaque archetypes mismatch to make sure that the compiler would produce a reasonable diagnostic for it?

**Comment by jameesbrown** [comment]
@slavapestov Thanks for your help with it! I understood the problem a lot better afterward.

**Comment by slavapestov** [comment]
@xedin Maybe in a follow up PR though? This one fixes a regression.

**Comment by xedin** [comment]
Sure, no worries!

**Comment by slavapestov** [comment]
For completeness we should probably do the same thing with element archetypes as well, but I can’t think of a specific counterexample off the top of my head.

**Comment by jameesbrown** [comment]
@xedin I will add the additional test-cases as a follow up, sorry for not adding them initially though. Also @slavapestov there was a failure in the linux test, related to https://github.com/llvm/llvm-project/issues/85084.

**Comment by xedin** [comment]
https://github.com/llvm/llvm-project/issues/85084
@swift-ci please smoke test Linux platform

**Comment by jameesbrown** [comment]
@xedin I have been struggling to come up with a counter test-case for this. It _seems_ it is not possible to return a failure solution from `matchDeepEqualityTypes` when we have an opened existentials because prior to adding the deep equality restriction we already check that they are in the same generic environment -- which can only point to one set of outer substitutions. In the case we try to match two opened existentials with different generic environments it should result in `type_of_expression_is_ambiguous` but I haven't found a test case for this either yet.

**Comment by xedin** [comment]
There are two situations here - different opened existentials and different replacement types for the same existential.

>  In the case we try to match two opened existentials with different generic environments it should result in type_of_expression_is_ambiguous

This should never be the case because it's a fallback diagnostic when the solver couldn't produce a fix for the underlying issue.

The other one has to do with matching replacement types, currently they are equated, I'm not sure whether it's possible (in the language) to end up in the situation when one side has one set of substitutions and another has a different set. It seems like that's possible for opaque types so maybe here as well?

**Comment by jameesbrown** [comment]
Thanks @xedin! Yes it should be possible given it is for opaques. I'm going to look at our tests for opaques and see how to recreate the same situation for opened existentials. If I do find we get the bad diagnostic (in either of the two cases), I'll come up with a fix for that.
