### PR TITLE
[Parser] Eliminate 'CommentRetentionMode::None' in Lexer

### LINKED ISSUE #85922: Parse error when comment appears between variable declaration and #if
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [x] Confirmed reproduction steps with SwiftPM CLI. The description text _must_ include reproduction steps with either of command-line SwiftPM commands, `swift build`, `swift test`, `swift package` etc.

### Description

https://github.com/koher/swift-image.git

MacOS

The following package does not build using the 'swifbuild' backend but does with 'native'

```
swift build `--buildsystem=swiftbuild` fails to build package
```

```
info: Planning Swift module SwiftImageTests (arm64)
    cd /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8
    builtin-SwiftDriver -- /var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/swift-toolchains/latest.xctoolchain/usr/bin/swiftc -parse-as-library -module-name SwiftImageTests -Onone -enforce-exclusivity\=checked @/private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/Intermediates.noindex/SwiftImage.build/Debug/SwiftImageTests.build/Objects-normal/arm64/SwiftImageTests.SwiftFileList -DSWIFT_PACKAGE -DDEBUG -DSWIFT_MODULE_RESOURCE_BUNDLE_AVAILABLE -v -DXcode -I /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/swift-toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-12-01-a-osx/usr/lib/swift/macosx/testing -L /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/swift-toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-12-01-a-osx/usr/lib/swift/macosx/testing -plugin-path /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/swift-toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-12-01-a-osx/usr/lib/swift/host/plugins/testing -sdk /Applications/XcodeWonderXIP.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX16.0.sdk -F /Applications/XcodeWonderXIP.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -F /Applications/XcodeWonderXIP.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/PrivateFrameworks -I /Applications/XcodeWonderXIP.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -L /Applications/XcodeWonderXIP.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -g -external-plugin-path /var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/swift-toolchains/latest.xctoolchain/usr/lib/swift/host/plugins/testing\#/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/swift-toolchains/latest.xctoolchain/usr/bin/swift-plugin-server -enable-experimental-feature DebugDescriptionMacro -sdk /Applications/XcodeWonderXIP.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX16.0.sdk -target arm64-apple-macos14.0 -g -module-cache-path /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/ModuleCache.noindex -Xfrontend -serialize-debugging-options -enable-testing -index-store-path /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx -Xcc -D_LIBCPP_HARDENING_MODE\=_LIBCPP_HARDENING_MODE_DEBUG -swift-version 5 -I /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/Products/Debug -Isystem /Applications/XcodeWonderXIP.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -Isystem /var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/swift-toolchains/latest.xctoolchain/usr/lib/swift/macosx/testing -F /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/Products/Debug/PackageFrameworks -F /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/Products/Debug -F /Applications/XcodeWonderXIP.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -c -j24 -enable-batch-mode -incremental -output-file-map /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/Intermediates.noindex/SwiftImage.build/Debug/SwiftImageTests.build/Objects-normal/arm64/SwiftImageTests-OutputFileMap.json -use-frontend-parseable-output -save-temps -no-color-diagnostics -explicit-module-build -module-cache-path /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/Intermediates.noindex/SwiftExplicitPrecompiledModules -clang-scanner-module-cache-path /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/ModuleCache.noindex -sdk-module-cache-path /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/ModuleCache.noindex -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/Intermediates.noindex/SwiftImage.build/Debug/SwiftImageTests.build/Objects-normal/arm64/SwiftImageTests.swiftmodule -validate-clang-modules-once -clang-build-session-file /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/ModuleCache.noindex/Session.modulevalidation -package-name swift_image -emit-const-values -Xfrontend -const-gather-protocols-file -Xfrontend /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/Intermediates.noindex/SwiftImage.build/Debug/SwiftImageTests.build/Objects-normal/arm64/SwiftImageTests_const_extract_protocols.json -Xcc -I/private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/Products/Debug/include -Xcc -I/private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/Intermediates.noindex/SwiftImage.build/Debug/SwiftImageTests.build/DerivedSources-normal/arm64 -Xcc -I/private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/Intermediates.noindex/SwiftImage.build/Debug/SwiftImageTests.build/DerivedSources/arm64 -Xcc -I/private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/Intermediates.noindex/SwiftImage.build/Debug/SwiftImageTests.build/DerivedSources -Xcc -DSWIFT_PACKAGE -Xcc -DDEBUG\=1 -working-directory /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8 -experimental-emit-module-separately -disable-cmo
/private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/Tests/SwiftImageTests/SwiftImageTests.swift:17:23: error: consecutive statements on a line must be separated by ';'
        /**/ let y = 0
                      ^
                      ;
/private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/Tests/SwiftImageTests/SwiftImageTests.swift:40:66: error: consecutive statements on a line must be separated by ';'
        let binarized: Image<Bool> = image.map { $0.gray >= 127 }
                                                                 ^
                                                                 ;
Apple Swift version 6.3-dev (LLVM 35f48306184cd25, Swift a69dbb3366e64d8)
Target: arm64-apple-macos14.0
error: /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/Tests/SwiftImageTests/SwiftImageTests.swift:17:23 consecutive statements on a line must be separated by ';'
        /**/ let y = 0
                      ^
                      ;
error: /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/Tests/SwiftImageTests/SwiftImageTests.swift:40:66 consecutive statements on a line must be separated by ';'
        let binarized: Image<Bool> = image.map { $0.gray >= 127 }
                                                                 ^
                                                                 ;
error: SwiftDriver SwiftImageTests normal arm64 com.apple.xcode.tools.swift.compiler failed with a nonzero exit code. Command line:     cd /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8
    builtin-SwiftDriver -- /var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/swift-toolchains/latest.xctoolchain/usr/bin/swiftc -parse-as-library -module-name SwiftImageTests -Onone -enforce-exclusivity\=checked @/private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/Intermediates.noindex/SwiftImage.build/Debug/SwiftImageTests.build/Objects-normal/arm64/SwiftImageTests.SwiftFileList -DSWIFT_PACKAGE -DDEBUG -DSWIFT_MODULE_RESOURCE_BUNDLE_AVAILABLE -v -DXcode -I /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/swift-toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-12-01-a-osx/usr/lib/swift/macosx/testing -L /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/swift-toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-12-01-a-osx/usr/lib/swift/macosx/testing -plugin-path /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/swift-toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-12-01-a-osx/usr/lib/swift/host/plugins/testing -sdk /Applications/XcodeWonderXIP.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX16.0.sdk -F /Applications/XcodeWonderXIP.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -F /Applications/XcodeWonderXIP.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/PrivateFrameworks -I /Applications/XcodeWonderXIP.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -L /Applications/XcodeWonderXIP.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -g -external-plugin-path /var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/swift-toolchains/latest.xctoolchain/usr/lib/swift/host/plugins/testing\#/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/swift-toolchains/latest.xctoolchain/usr/bin/swift-plugin-server -enable-experimental-feature DebugDescriptionMacro -sdk /Applications/XcodeWonderXIP.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX16.0.sdk -target arm64-apple-macos14.0 -g -module-cache-path /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/ModuleCache.noindex -Xfrontend -serialize-debugging-options -enable-testing -index-store-path /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx -Xcc -D_LIBCPP_HARDENING_MODE\=_LIBCPP_HARDENING_MODE_DEBUG -swift-version 5 -I /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/Products/Debug -Isystem /Applications/XcodeWonderXIP.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -Isystem /var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/swift-toolchains/latest.xctoolchain/usr/lib/swift/macosx/testing -F /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/Products/Debug/PackageFrameworks -F /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/Products/Debug -F /Applications/XcodeWonderXIP.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -c -j24 -enable-batch-mode -incremental -output-file-map /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/Intermediates.noindex/SwiftImage.build/Debug/SwiftImageTests.build/Objects-normal/arm64/SwiftImageTests-OutputFileMap.json -use-frontend-parseable-output -save-temps -no-color-diagnostics -explicit-module-build -module-cache-path /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/Intermediates.noindex/SwiftExplicitPrecompiledModules -clang-scanner-module-cache-path /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/ModuleCache.noindex -sdk-module-cache-path /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/ModuleCache.noindex -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/Intermediates.noindex/SwiftImage.build/Debug/SwiftImageTests.build/Objects-normal/arm64/SwiftImageTests.swiftmodule -validate-clang-modules-once -clang-build-session-file /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/ModuleCache.noindex/Session.modulevalidation -package-name swift_image -emit-const-values -Xfrontend -const-gather-protocols-file -Xfrontend /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/Intermediates.noindex/SwiftImage.build/Debug/SwiftImageTests.build/Objects-normal/arm64/SwiftImageTests_const_extract_protocols.json -Xcc -I/private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/Products/Debug/include -Xcc -I/private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/Intermediates.noindex/SwiftImage.build/Debug/SwiftImageTests.build/DerivedSources-normal/arm64 -Xcc -I/private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/Intermediates.noindex/SwiftImage.build/Debug/SwiftImageTests.build/DerivedSources/arm64 -Xcc -I/private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8/swift-image/.build-swiftbuild/arm64-apple-macosx/Intermediates.noindex/SwiftImage.build/Debug/SwiftImageTests.build/DerivedSources -Xcc -DSWIFT_PACKAGE -Xcc -DDEBUG\=1 -working-directory /private/var/lib/jenkins/workspace/swift_oss/swift-package-index-metrics/spi-workdir/000DBA3D-CE2C-4681-A888-7417DF0087E8 -experimental-emit-module-separately -disable-cmo
error: Build failed

```

### Expected behaviour

Builds

### Actual behavior

Fails to build

### Steps to reproduce

```
git clone https://github.com/koher/swift-image.git
swift build --build-system=swiftbuild
```

### Swift Package Manager version/commit hash

_No response_

### Swift & OS version (output of `swift --version ; uname -a`)

_No response_

### PR DESCRIPTION
**Pull request by rintaro**
Fixes: https://github.com/swiftlang/swift/issues/85922

Lexer should always set `Token.CommentLength` correctly because it's necessary for restoring the token position with comments. Otherwise, `Token::isAtStartOfLine()` might not correctly set. (see: [`Lexer::getStateForBeginningOfToken()`](https://github.com/swiftlang/swift/blob/20bee09dc958bc18b8cb20ede7f702c1eb2eb2cf/include/swift/Parse/Lexer.h#L280-L283))

### CODE REVIEW

**Review by hamishknight — APPROVED** [review]

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test macOS

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux

File: unittests/Parse/LexerTests.cpp [hunk 1]
```diff
@@ -277,10 +277,10 @@ TEST_F(LexerTest, BOMNoCommentNoTrivia) {
   LangOptions LangOpts;
   SourceManager SourceMgr;
   unsigned BufferID = SourceMgr.addMemBufferCopy(StringRef(Source));
-  
+
   Lexer L(LangOpts, SourceMgr, BufferID, /*Diags=*/nullptr, LexerMode::Swift,
-          HashbangMode::Disallowed, CommentRetentionMode::None);
-  
+          HashbangMode::Disallowed, CommentRetentionMode::AttachToNextToken);
```
Comment (rintaro) [inline unittests/Parse/LexerTests.cpp]: This was specifically testing `CommentRetentionMode::None` behavior. Removing the case.
(`CommentRetentionMode::AttachToNextToken` behavior is tested in `BOMAttachCommentNoTrivia`)

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux

**Comment by rintaro** [comment]
@swift-ci Please smoke test Windows

**Comment by rintaro** [comment]
@swift-ci Please smoke test
