### PR TITLE
[CSApply] A couple of locator adjustments to support updated Double<->CGFloat conversion

### LINKED ISSUE #59932: Assert when typechecking with CALayer
**Describe the bug**
I'm seeing an assert in `swiftc` while typechecking the following source.

**Steps To Reproduce**
```swift
$ cat bug.swift
import UIKit

func foo(layer: CALayer) {
    let x = 2.0
    // Adding a type prevents the crash.
    // let x: CGFloat = 2.0
    layer.cornerRadius = x
}

$ swiftc -target arm64-apple-ios15.5 -sdk $(xcrun --show-sdk-path --sdk iphoneos) bug.swift
Assertion failed: (hasVal), function getValue, file Optional.h, line 96.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
Stack dump:
0.	Program arguments: swift-frontend -frontend -c -primary-file bug2.swift -target arm64-apple-ios15.5 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk xcode-13.4.0-iphoneos-sdk-15.5 -color-diagnostics -target-sdk-version 15.5 -module-name bug2 -o /var/folders/9r/0sls700961l6q076pb8_zj900000gn/T/bug2-86c73a.o
1.	Facebook Swift version 5.8-dev (LLVM 00d7112ac059491, Swift f13a5213c871c7e)
2.	Compiling with the current language version
3.	While evaluating request TypeCheckSourceFileRequest(source_file "bug2.swift")
4.	While evaluating request TypeCheckFunctionBodyRequest(bug2.(file).foo(layer:)@bug2.swift:3:6)
5.	While type-checking statement at [bug2.swift:3:26 - line:7:1] RangeText="{
    // let x: CGFloat = 2.0
    let x = 2.0
    layer.cornerRadius = x
"
6.	While type-checking expression at [bug2.swift:6:5 - line:6:26] RangeText="layer.cornerRadius = "
7.	While type-checking-target starting at bug2.swift:6:5
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x000000011423da8b llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 43
1  swift-frontend           0x000000011423cdf5 llvm::sys::RunSignalHandlers() + 85
2  swift-frontend           0x000000011423e0f0 SignalHandler(int) + 288
3  libsystem_platform.dylib 0x00007ff819a10dfd _sigtramp + 29
4  swift-frontend           0x000000010fb1857c std::__1::pair<llvm::StringMapIterator<swift::Identifier::Aligner>, bool> llvm::StringMap<swift::Identifier::Aligner, llvm::BumpPtrAllocatorImpl<llvm::MallocAllocator, 4096ul, 4096ul, 128ul>&>::try_emplace<swift::Identifier::Aligner>(llvm::StringRef, swift::Identifier::Aligner&&) + 28
5  libsystem_c.dylib        0x00007ff819946d24 abort + 123
6  libsystem_c.dylib        0x00007ff8199460cb err + 0
7  swift-frontend           0x000000010f4f2591 (anonymous namespace)::ExprRewriter::coerceToType(swift::Expr*, swift::Type, swift::constraints::ConstraintLocatorBuilder, llvm::Optional<swift::Pattern*>) (.cold.58) + 33
8  swift-frontend           0x000000010f4cb8f4 (anonymous namespace)::ExprRewriter::coerceToType(swift::Expr*, swift::Type, swift::constraints::ConstraintLocatorBuilder, llvm::Optional<swift::Pattern*>) + 8772
9  swift-frontend           0x000000010f4cf6d4 (anonymous namespace)::ExprWalker::walkToExprPost(swift::Expr*) + 9700
10 swift-frontend           0x000000010fbdfcd3 swift::Expr::walk(swift::ASTWalker&) + 99
11 swift-frontend           0x000000010f4c7ddb (anonymous namespace)::ExprWalker::rewriteTarget(swift::constraints::SolutionApplicationTarget) + 1819
12 swift-frontend           0x000000010f4c7274 swift::constraints::ConstraintSystem::applySolution(swift::constraints::Solution&, swift::constraints::SolutionApplicationTarget) + 788
13 swift-frontend           0x000000010f7483c9 swift::TypeChecker::typeCheckTarget(swift::constraints::SolutionApplicationTarget&, swift::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 409
14 swift-frontend           0x000000010f7481d7 swift::TypeChecker::typeCheckExpression(swift::constraints::SolutionApplicationTarget&, swift::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 183
15 swift-frontend           0x000000010f7480ae swift::TypeChecker::typeCheckExpression(swift::Expr*&, swift::DeclContext*, swift::constraints::ContextualTypeInfo, swift::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 78
16 swift-frontend           0x000000010f83ceff (anonymous namespace)::StmtChecker::typeCheckASTNode(swift::ASTNode&) + 239
17 swift-frontend           0x000000010f83f2ac swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) + 268
18 swift-frontend           0x000000010f83e4a3 bool (anonymous namespace)::StmtChecker::typeCheckStmt<swift::BraceStmt>(swift::BraceStmt*&) + 131
19 swift-frontend           0x000000010f83da3f swift::TypeCheckFunctionBodyRequest::evaluate(swift::Evaluator&, swift::AbstractFunctionDecl*) const + 911
20 swift-frontend           0x000000010fcdda10 llvm::Expected<swift::TypeCheckFunctionBodyRequest::OutputType> swift::Evaluator::getResultUncached<swift::TypeCheckFunctionBodyRequest>(swift::TypeCheckFunctionBodyRequest const&) + 400
21 swift-frontend           0x000000010fcdd7dc llvm::Expected<swift::TypeCheckFunctionBodyRequest::OutputType> swift::Evaluator::getResultCached<swift::TypeCheckFunctionBodyRequest, (void*)0>(swift::TypeCheckFunctionBodyRequest const&) + 92
22 swift-frontend           0x000000010fc4a833 swift::TypeCheckFunctionBodyRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckFunctionBodyRequest>(swift::Evaluator&, swift::TypeCheckFunctionBodyRequest, swift::TypeCheckFunctionBodyRequest::OutputType) + 35
23 swift-frontend           0x000000010f87ca46 swift::TypeCheckSourceFileRequest::evaluate(swift::Evaluator&, swift::SourceFile*) const + 326
24 swift-frontend           0x000000010f87e8f1 llvm::Expected<swift::TypeCheckSourceFileRequest::OutputType> swift::Evaluator::getResultUncached<swift::TypeCheckSourceFileRequest>(swift::TypeCheckSourceFileRequest const&) + 401
25 swift-frontend           0x000000010f87e697 llvm::Expected<swift::TypeCheckSourceFileRequest::OutputType> swift::Evaluator::getResultCached<swift::TypeCheckSourceFileRequest, (void*)0>(swift::TypeCheckSourceFileRequest const&) + 55
26 swift-frontend           0x000000010f87c82f swift::TypeCheckSourceFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckSourceFileRequest>(swift::Evaluator&, swift::TypeCheckSourceFileRequest, swift::TypeCheckSourceFileRequest::OutputType) + 31
27 swift-frontend           0x000000010e65c32c bool llvm::function_ref<bool (swift::SourceFile&)>::callback_fn<swift::CompilerInstance::performSema()::$_7>(long, swift::SourceFile&) + 12
28 swift-frontend           0x000000010e65709a swift::CompilerInstance::forEachFileToTypeCheck(llvm::function_ref<bool (swift::SourceFile&)>) + 90
29 swift-frontend           0x000000010e656f8a swift::CompilerInstance::performSema() + 74
30 swift-frontend           0x000000010e5f60c4 withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 52
31 swift-frontend           0x000000010e5e834d performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 701
32 swift-frontend           0x000000010e5e7843 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2451
33 swift-frontend           0x000000010e586ad8 swift::mainEntry(int, char const**) + 2552
34 dyld                     0x00000001286d051e start + 462
```

**Expected behavior**
The code should compile without crashing.

**Environment (please fill out the following information)**
 - OS: macOS 12.4
 - Xcode Version/Tag/Branch: Swift main (f13a5213c871c7ef683b1966b5118851e99138fc)

**Additional context**
I opened a very similar issue https://github.com/apple/swift/issues/59374 which was fixed by https://github.com/apple/swift/pull/59762 CC @xedin 
However, I believe those commits might have added this bug since we noticed it around that time.

### PR DESCRIPTION
**Pull request by xedin**
https://github.com/apple/swift/pull/59762 made it possible to use Double<->CGFloat conversions in different 
arguments positions of the same call, but it didn't account for the fact that 
some locators are constructed incorrectly by `ExprRewriter` during solution 
application. 

This PR adjusts locators for the following situations:

- Array/dictionary element coercions adjusted to use `<collection> -> tuple element #` locator;
- Assignment source -> destination type coercion is adjusted to use assignment expression 
   itself since this is where the conversion constraint is placed (which is also very helpful for diagnostics).

Resolves: rdar://96469597
Resolves: rdar://96477064 
Resolves: rdar://96477058
Resolves: https://github.com/apple/swift/issues/59932

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test source compatibility

File: lib/Sema/ConstraintSystem.cpp [hunk 1]
```diff
@@ -429,6 +429,11 @@ ConstraintLocator *ConstraintSystem::getImplicitValueConversionLocator(
   SmallVector<LocatorPathElt, 4> path;
   auto anchor = root.getLocatorParts(path);
   {
+    if (isExpr<DictionaryExpr>(anchor) && path.size() > 1) {
+      // Drop everything except to first `tuple element #`.
```
Comment (AnthonyLatsis) [inline lib/Sema/ConstraintSystem.cpp:433]: Except *for*?

File: test/Constraints/implicit_double_cgfloat_conversion.swift [hunk 2]
```diff
@@ -216,3 +216,49 @@ func test_multi_argument_conversion_with_optional(d: Double, cgf: CGFloat) {
...
+}
+
+func test_array_literal_as_call_argument() {
+  enum E {
+  case test_arr([CGFloat])
+  case test_dict_key([CGFloat: String])
+  case test_dict_value([String: CGFloat])
+  case test_arr_nested([String: [[CGFloat]: String]])
+  case test_dict_nested([String: [String: CGFloat]])
+  }
```
Comment (AnthonyLatsis) [inline test/Constraints/implicit_double_cgfloat_conversion.swift:231]: Spotted unindented cases. Disregard if this is a stylistic preference.

File: test/Constraints/implicit_double_cgfloat_conversion.swift [hunk 3]
```diff
@@ -216,3 +216,49 @@ func test_multi_argument_conversion_with_optional(d: Double, cgf: CGFloat) {
...
+    var y: Double
+  }
+
+  func test(cont: inout Container, point: Point) {
+    cont.prop = .test_arr([point.x]) // Ok
+    cont.prop = .test_dict_key([point.y: ""]) // Ok
+    cont.prop = .test_dict_value(["": point.y]) // Ok
+    cont.prop = .test_arr_nested(["": [[point.x]: ""]]) // Ok
+    cont.prop = .test_dict_nested(["": ["": point.x]]) // Ok
+  }
```
Comment (AnthonyLatsis) [inline test/Constraints/implicit_double_cgfloat_conversion.swift:248]: Maybe rename this function to `test_collection_literal_as_call_argument` since dictionary literals are tested as well?

**Review by AnthonyLatsis — COMMENTED** [review]
NFC remarks only (not worth relaunching already triggered tests).

File: test/Constraints/implicit_double_cgfloat_conversion.swift (hunk 2 above)
Comment (xedin) [reply test/Constraints/implicit_double_cgfloat_conversion.swift]: Fixed!

File: lib/Sema/ConstraintSystem.cpp (hunk 1 above)
Comment (xedin) [reply lib/Sema/ConstraintSystem.cpp]: Fixed!
