### PR TITLE
[AutoDiff] Implement cross-file lookup of derivatives

### LINKED ISSUE #55170: [SR-14235] [AutoDiff] Cross-file differentiation error: derivative configuration not registered for `@derivative` attribute
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14235      |
   |Radar             | None         |
   |Original Reporter | @dan-zheng      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, AutoDiff        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 1c36955f37f690185a211308ac4034a9

  </details>

**Issue Description:**

``` swift
// a.swift
@differentiable
func crossFileDerivativeAttr<T: DifferentiableTensorProtocol>(
  _ input: T
) -> T {
  return input.identityDerivativeAttr()
}
```

``` swift
import _Differentiation

protocol DifferentiableTensorProtocol: Differentiable {}

extension DifferentiableTensorProtocol {
  func identityDerivativeAttr() -> Self { self }

  // Test cross-file `@derivative` attribute.
  @derivative(of: identityDerivativeAttr)
  func vjpIdentityDerivativeAttr() -> (
    value: Self, pullback: (TangentVector) -> TangentVector
  ) {
    fatalError()
  }
}
```

The error occurs because `AbstractFunctionDecl::getDerivativeConfigurations` is not sufficiently requestified to type-check `@derivative` attributes in other files.

``` java
$ swiftc a.swift b.swift
a.swift:20:16: error: expression is not differentiable
  return input.identityDerivativeAttr()
               ^
a:20:16: note: cannot differentiate functions that have not been marked '@differentiable' and that are defined in other files
  return input.identityDerivativeAttr()
               ^
```

### PR DESCRIPTION
**Pull request by asl**
Look-up for functions with `@derivative` attributes defined in non-primary source files

Fixes #55170

### CODE REVIEW

**Comment by asl** [comment]
@swift-ci Please test

**Comment by asl** [comment]
Tagging @BradLarson

**Comment by asl** [comment]
Ok, look like the patch exposed the lookup cycle we're having here:

1. When we typecheck `@derivative(of:)` attribute we need to find the original function decl
2. This might trigger various requirement checks if the original function decl is generic
3. One of these checks is differentiability check that also checks what are the derivative function configurations out there
4. However, typechecking of `@derivative(of:)` also registers derivative function configuration

This was the cycle before, however it only caused correctness issue (e.g. we might miss the derivative configuration and produce an error). Now the cycle is explicitly exposed as we try to look for derivative configurations in no-primary files as well.

@rxwei Any preferences how to break the cycle? I'm thinking of removing the lookup logic from `getDerivativeFunctionConfigurations` and instead add "retry" logic into `findMinimalDerivativeConfiguration`. Alternatively we can to hack around and add a dedicated flag to `getDerivativeFunctionConfigurations` not to perform cross-module lookup during sema stage.

File: lib/AST/Decl.cpp [hunk 1]
```diff
@@ -8333,6 +8334,33 @@ AbstractFunctionDecl::getDerivativeFunctionConfigurations() {
     ctx.loadDerivativeFunctionConfigurations(this, previousGeneration,
                                              *DerivativeFunctionConfigs);
   }
+
+  class DerivativeFinder : public ASTWalker {
```
Comment (dan-zheng) [inline lib/AST/Decl.cpp:8338]: Drive-by question: does `@derivative` attribute finding have an impact on incremental compilation?

---

When a file is updated, it and all files that depend on it need to be recompiled. Incremental compilation is fast when there are few dependencies between files.

I wonder if `@derivative` finding can cause incremental compilation to become asymptotically worse. Thinking through an example:

1. `a.swift` defines `func foo`. `b.swift` exists in the same module, defining a `func vjpFoo` function with no attributes.
2. Many files in the same module ask for the derivative of `foo`, e.g. by calling `gradient(of: foo)`.

Initially, `foo` has no derivative functions registered via `@derivative`, so `gradient(of: foo)` triggers the compiler to automatically generate derivative functions.

3. `func vjpFoo` in`b.swift` is now marked with `@derivative(of: foo)`.

Since all files (`a.swift`, `b.swift`, `gradient(of: foo)` files) are in the same module, the addition of `@derivative(of: foo)` in `b.swift` means that `foo` now has a registered derivative, and all functions that call `gradient(of: foo)` need to be recompiled†.

Is the † recompilation behavior asymptotically worse than existing incremental compilation? It might not be, if the same amount of work (e.g. recompiling the entire module) was necessary previous to the implementation of correct `@derivative` attribute finding.

Comment (dan-zheng) [reply lib/AST/Decl.cpp:8338]: (It may be that the impact of `@derivative` attribute finding on incremental compilation was introduced prior to this PR.)

**Comment by asl** [comment]
@swift-ci please test

**Comment by rxwei** [comment]
Sorry I don't have the bandwidth in the near term to review this. Maybe @dan-zheng can help?

File: lib/Sema/TypeCheckAttr.cpp [hunk 2]
```diff
@@ -5365,13 +5366,18 @@ static bool typeCheckDerivativeAttr(ASTContext &Ctx, Decl *D,
...
 void AttributeChecker::visitDerivativeAttr(DerivativeAttr *attr) {
-  if (typeCheckDerivativeAttr(Ctx, D, attr))
+  if (typeCheckDerivativeAttr(attr))
     attr->setInvalid();
 }
 
 AbstractFunctionDecl *
 DerivativeAttrOriginalDeclRequest::evaluate(Evaluator &evaluator,
                                             DerivativeAttr *attr) const {
+  // Try to resolve the original function
```
Comment (dan-zheng) [inline lib/Sema/TypeCheckAttr.cpp:5376]: Minor:
```suggestion
  // Try to resolve the original function.
```

File: lib/Sema/TypeCheckProtocol.cpp [hunk 3]
```diff
@@ -379,7 +379,7 @@ matchWitnessDifferentiableAttr(DeclContext *dc, ValueDecl *req,
     bool foundExactConfig = false;
     Optional<AutoDiffConfig> supersetConfig = None;
     for (auto witnessConfig :
-         witnessAFD->getDerivativeFunctionConfigurations()) {
+           witnessAFD->getDerivativeFunctionConfigurations(/*NonLocal*/ false)) {
```
Comment (dan-zheng) [inline lib/Sema/TypeCheckProtocol.cpp:382]: Did you mean `NonPrimaryLookup`?
```suggestion
           witnessAFD->getDerivativeFunctionConfigurations(/*NonPrimaryLookup*/ false)) {
```

File: include/swift/AST/Decl.h [hunk 4]
```diff
@@ -6266,7 +6266,8 @@ class AbstractFunctionDecl : public GenericContext, public ValueDecl {
 
 public:
   /// Get all derivative function configurations.
-  ArrayRef<AutoDiffConfig> getDerivativeFunctionConfigurations();
+  ArrayRef<AutoDiffConfig>
```
Comment (dan-zheng) [inline include/swift/AST/Decl.h:6269]: Could you please document the `NonPrimaryLookup` parameter? That would be helpful as its meaning is not obvious.

How about renaming to something like `lookInNonPrimarySources`? I think that would be clearer and more fluent.

**Review by philipturner — CHANGES_REQUESTED** [review]

File: lib/AST/Decl.cpp (hunk 1 above)
Comment (CodaFi) [reply lib/AST/Decl.cpp:8338]: > The complete recompilation is certainly necessary when optimizations are enabled.

When optimizations are enabled you're building in whole-module mode anyways. Swift will refuse to perform the incremental build if you ask for -wmo as well.

An even simpler failure mode occurs here since this analysis is not going through name lookup. From the incremental build's perspective, there is no link between the derivative and the original.

File: lib/AST/Decl.cpp [hunk 5]
```diff
@@ -8333,6 +8334,36 @@ AbstractFunctionDecl::getDerivativeFunctionConfigurations() {
...
+          }
+        }
+      }
+
+      return true;
+    }
+  };
+
+  // Load derivative configurations from @derivative attributes defined in
+  // non-primary sources. Note that it might trigger lookup cycles if called
```
Comment (CodaFi) [inline lib/AST/Decl.cpp:8360]: This analysis needs to go through name lookup. If that's triggering cycles then we need to figure out why `getDerivativeFunctionConfigurations` is on the lookup path.

**Review by CodaFi — CHANGES_REQUESTED** [review]
Please refactor this code to go through name lookup. You'll get access control, shadowing, and incremental build metadata done for free as a result. If there are cycles that is evidence that autodiff has a layering problem. We should perform minimal validation on the lookup path.

**Comment by dan-zheng** [comment]
> Please refactor this code to go through name lookup. You'll get access control, shadowing, and incremental build metadata done for free as a result. If there are cycles that is evidence that autodiff has a layering problem. We should perform minimal validation on the lookup path.

This current approach for stateful derivative function configuration serialization (https://github.com/apple/swift/pull/30672) was adapted from prior work for serializing and loading extensions and Obj-C methods.

From current `main`:
* [`ASTContext::loadDerivativeFunctionConfigurations`](https://github.com/apple/swift/blob/760343f4782e87999e2d3dee9114fbdbe9fbadb4/lib/AST/ASTContext.cpp#L1938)
* [`ASTContext::loadExtensions`](https://github.com/apple/swift/blob/760343f4782e87999e2d3dee9114fbdbe9fbadb4/lib/AST/ASTContext.cpp#L1901)
* [`ASTContext::loadObjCMethods`](https://github.com/apple/swift/blob/760343f4782e87999e2d3dee9114fbdbe9fbadb4/lib/AST/ASTContext.cpp#L1909)

If there's a better approach for handling derivative function configuration lookup that avoids this statefulness, that would be great.

---

One design choice is that derivative registration is done ① "retroactively" from `@derivative` functions to the original function, not ② from the original function to `@derivative` functions – so I'm not sure how to straightforwardly implement "get all derivative function configurations of `foo`" using name lookup, since `foo` does not know which `@derivative` functions have been registered for it (potentially across modules) or what those derivative functions' names are.

```swift
// Previous approach ②: derivative registration is done from original function to derivative functions.
// This does not enable retroactive derivative registration, e.g. registering derivatives for tgmath functions.
@differentiable(vjp: vjpFoo)
func foo(_ x: Float) -> Float { x }
func vjpFoo(_ x: Float) -> (value: Float, pullback: (Float) -> Float) { (x, { $0 }) }
```

```swift
// Current approach ①: derivative registration is done from derivative functions to original function.
//
// This supports retroactive registration: derivatives can be registered for functions in other modules.
// For example, `vjpFoo` could be defined in module B, importing module A where `foo` is defined.
//
// However, determining "registered derivatives" for a function is less straightforward, hence the
// `ASTContext::loadDerivativeFunctionConfigurations` complications.
func foo(_ x: Float) -> Float { x }

@derivative(of: foo)
func vjpFoo(_ x: Float) -> (value: Float, pullback: (Float) -> Float) { (x, { $0 }) }
```

File: lib/AST/Decl.cpp (hunk 1 above)
Comment (asl) [reply lib/AST/Decl.cpp:8338]: > When optimizations are enabled you're building in whole-module mode anyways.

I'm confused. Will you please elaborate? The original testcase from https://github.com/apple/swift/issues/55170 fails regardless whether `-O` is provided to `swiftc`.

File: lib/AST/Decl.cpp (hunk 5 above)
Comment (asl) [reply lib/AST/Decl.cpp:8360]: It cannot by design. See the full description in https://github.com/apple/swift/pull/58644#issuecomment-1119158991 There is no way you could discover custom derivatives via name lookup as name is not known and the original function does not know anything about custom derivatives.

**Review by dan-zheng — APPROVED** [review]
This PR as an incremental fix/improvement looks good!

If tests pass, merging this sounds good to me unless others have concerns.

**Comment by asl** [comment]
@swift-ci please test
