### PR TITLE
[stdlib] Fix String.hasPrefix and String.hasSuffix when self and arg are in NFC form

### LINKED ISSUE #67427: [StdLib] Incorrect results from `String.hasPrefix` and `hasSuffix`
[As reported on the Swift forums](https://forums.swift.org/t/why-is-regex-slower-than-using-a-bunch-of-string-contains/66247/26), `String.hasPrefix` and `String.hasSuffix` sometimes have an incorrect result:

```swift
"\r\n".hasPrefix("\r")      // true
"\r\n".hasPrefix("\r"[...]) // false

"\r\n".hasSuffix("\n")      // true
"\r\n".hasSuffix("\n"[...]) // false
```

All four of these calls should return `false`, since those methods should be matching at the character level, not at the Unicode scalar level. The problem is in the `String`-specific overloads for `hasPrefix` and `hasSuffix` in [StringLegacy.swift](https://github.com/apple/swift/blob/main/stdlib/public/core/StringLegacy.swift#L123-L151), which don't validate that the string passed as a parameter ends on a character boundary (when both strings are known to be NFC). The calls that pass a substring go to the `StringProtocol`-based overload, instead, which calls through to the `Sequence` method `starts(with:)`.

**Environment**
- Swift `main` branch

### PR DESCRIPTION
**Pull request by nishithshah2211**
This commit resolves #67427. When the string and argument are both in NFC form, besides performing the prefix/suffix check, we also have to perform a grapheme boundary check to make sure that the prefix/suffix are not in between an extended grapheme cluster.

In addition, it also seems to pass a test that was previously marked as failing.

### CODE REVIEW

**Comment by nishithshah2211** [comment]
@LucianoPAlmeida Can you also add @natecook1000 as a reviewer too?

**Comment by natecook1000** [comment]
@swift-ci Please smoke test

**Comment by nishithshah2211** [comment]
What would be the next steps here?

File: test/stdlib/StringAPI.swift [hunk 1]
```diff
@@ -532,4 +517,14 @@ StringTests.test("_isIdentical(to:)") {
   expectTrue(g._isIdentical(to: g))
 }
 
+StringTests.test("GH-#67427") {
```
Comment (lorentey) [inline test/stdlib/StringAPI.swift:520]: Tiny nit: Let's use full URLs instead of such shorthand notation:

```suggestion
StringTests.test("hasPrefix/hasSuffix vs Character boundaries") { // https://github.com/apple/swift/issues/67427
```

**Review by lorentey — APPROVED** [review]

File: stdlib/public/core/StringLegacy.swift [hunk 2]
```diff
@@ -128,7 +128,7 @@ extension String {
         let prefixEnd = nfcPrefix.count
         return self._guts.withFastUTF8(range: 0..<prefixEnd) { nfcSlicedSelf in
           return _binaryCompare(nfcSlicedSelf, nfcPrefix) == 0
-        }
```
[the remark this answers is not in the document]
Comment (nishithshah2211) [reply stdlib/public/core/StringLegacy.swift:131]: I agree. Thanks for the suggestions. I made the changes in a new commit.

File: test/stdlib/StringAPI.swift (hunk 1 above)
Comment (nishithshah2211) [reply test/stdlib/StringAPI.swift]: Updated in the new commit

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

**Comment by natecook1000** [comment]
Thanks for the fix, @nishithshah2211!

**Comment by nishithshah2211** [comment]
Thanks for the guidance and merge! @natecook1000
