### PR TITLE
Remove linear map structs and use plain tuples instead.

### LINKED ISSUE #63207: Type reconstruction fails for some @differentiable functions when unit tests are built for Profiling.
**Description**
The compiler crashes with an error message indicating that it failed to reconstruct the type for what appears to be a differentiable function, in the case of the below code. 

**Steps to reproduce**
1. Use the code below in order to generate a library.
```swift
import _Differentiation
public struct F<I: Equatable, D> {public init() {}}
extension F: Equatable where D: Equatable {}
extension F: Differentiable where D: Differentiable, D.TangentVector == D {}
extension F: AdditiveArithmetic where D: AdditiveArithmetic {
    public static func + (lhs: F<I, D>, rhs: F<I, D>) -> F<I, D> {return lhs}
    public static func - (lhs: F<I, D>, rhs: F<I, D>) -> F<I, D> {return lhs}
    public static var zero: F<I, D> {return F<I, D>()}
}
public extension F where D: Differentiable, D == D.TangentVector {
    mutating func assign1(_ series: S<I, D>, at key: String?) {fatalError()}
    @differentiable(reverse)
    mutating func assign0(_ series: S<I, D>) {self.assign1(series, at: nil)}
    @inlinable
    @differentiable(reverse)
    mutating func assignMain(_ series: S<I, D>) {self.assign0(series)}
    @derivative(of: assign0)
    mutating func vjpAssign_(series: S<I, D>) -> (value: Void, pullback: (inout Self.TangentVector) -> S<I, D>.TangentVector)
    {
        return ((), {_ in S<I, D>.TangentVector.zero})
    }
//    @derivative(of: assignMain)
//    mutating func vjpAssignMain(series: S<I, D>) -> (value: Void, pullback: (inout Self.TangentVector) -> S<I, D>.TangentVector)
//    {
//        return ((), {_ in S<I, D>.TangentVector.zero})
//    }
    
}
public struct S<I, D> {public init(){}}
extension S: Equatable where D: Equatable {
    public static func == (lhs: S<I, D>, rhs: S<I, D>) -> Bool {fatalError()}
}
extension S: Differentiable where D: Differentiable, D.TangentVector == D{public typealias TangentVector = S<I, D>}
extension S: AdditiveArithmetic where D: AdditiveArithmetic {
    public static func + (_ lhs: Self, _ rhs: Self) -> Self {fatalError()}
    public static func - (_ lhs: Self, _ rhs: Self) -> Self {fatalError()}
    public static var zero: Self {fatalError()}
}
```
2. Specify the library generated by the code above as one of the imports to the unit test code below:
```swift
import _Differentiation
import PlayGround //Specify custom library name here.
import XCTest
class UnitTests: XCTestCase {
    func testA(){
        @differentiable(reverse)
        func a(input: S<Double, Double>) -> F<Double, Double> {
            var f = F<Double, Double>()
            f.assignMain(input)
            return f
        }
    }
}
```
3. In Xcode, right click and select `Profile "testA()"`.

The compiler will generate an error that looks like:
```
Failed to reconstruct type for $s10PlayGround09_AD__$s10a131Ground1FVAA16_Differentiation14DifferentiableR_13TangentVectorAdEPQy_Rs_rlE10assignMainyyAA1SVyxq_GF_bb0__PB__src_0_wrt_0_1_SQRz16_gh4R_13ij7AaBPQy_M5_r0_lVyS2dGD
Original type:
(bound_generic_struct_type decl=PlayGround.(file)._AD__$s10PlayGround1FVAA16_Differentiation14DifferentiableR_13TangentVectorAdEPQy_Rs_rlE10assignMainyyAA1SVyxq_GF_bb0__PB__src_0_wrt_0_1_SQRz16_Differentiation14DifferentiableR_13TangentVectorAaBPQy_Rs_r0_l
  (struct_type decl=Swift.(file).Double)
  (struct_type decl=Swift.(file).Double))
```

Additional stack information:
```
1.	Apple Swift version 5.9-dev (LLVM c48958355f7507c, Swift f26f810cc8406ef)
2.	Compiling with the current language version
3.	While emitting IR SIL function "@$s10PlayGround1FVAA16_Differentiation14DifferentiableR_13TangentVectorAdEPQy_Rs_rlE10assignMainyyAA1SVyxq_GFSQRzAdER_AHRs_r0_lTJpSSpSrSd_SdTg5".
 for <<debugloc at "<compiler-generated>":0:0>>Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x000000010948d5c8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x000000010948c84c llvm::sys::RunSignalHandlers() + 128
2  swift-frontend           0x000000010948dc08 SignalHandler(int) + 304
3  libsystem_platform.dylib 0x000000018d1314c4 _sigtramp + 56
4  libsystem_pthread.dylib  0x000000018d119ee0 pthread_kill + 288
5  libsystem_c.dylib        0x000000018d054340 abort + 168
6  swift-frontend           0x0000000109527c6c (anonymous namespace)::IRGenDebugInfoImpl::getOrCreateType(swift::irgen::DebugTypeInfo) (.cold.8) + 0
7  swift-frontend           0x0000000104f972f0 (anonymous namespace)::IRGenDebugInfoImpl::getOrCreateType(swift::irgen::DebugTypeInfo) + 3436
8  swift-frontend           0x0000000104f97aac (anonymous namespace)::IRGenDebugInfoImpl::createParameterType(llvm::SmallVectorImpl<llvm::Metadata*>&, swift::SILType) + 132
9  swift-frontend           0x0000000104f977c0 (anonymous namespace)::IRGenDebugInfoImpl::createParameterTypes(swift::CanTypeWrapper<swift::SILFunctionType>) + 404
10 swift-frontend           0x0000000104f90f3c (anonymous namespace)::IRGenDebugInfoImpl::emitFunction(swift::SILDebugScope const*, llvm::Function*, swift::SILFunctionTypeRepresentation, swift::SILType, swift::DeclContext*, llvm::StringRef) + 1720
11 swift-frontend           0x0000000104f917e8 (anonymous namespace)::IRGenDebugInfoImpl::emitFunction(swift::SILFunction&, llvm::Function*) + 160
12 swift-frontend           0x0000000104fcabdc (anonymous namespace)::IRGenSILFunction::emitSILFunction() + 880
13 swift-frontend           0x0000000104fca338 swift::irgen::IRGenModule::emitSILFunction(swift::SILFunction*) + 920
14 swift-frontend           0x0000000104e849a8 swift::irgen::IRGenerator::emitLazyDefinitions() + 1400
15 swift-frontend           0x0000000104f7bcc4 swift::performIRGeneration(swift::ModuleDecl*, swift::IRGenOptions const&, swift::TBDGenOptions const&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> >, llvm::StringRef, swift::PrimarySpecificPaths const&, llvm::ArrayRef<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, llvm::GlobalVariable**) + 1524
16 swift-frontend           0x0000000104bb2518 performCompileStepsPostSILGen(swift::CompilerInstance&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> >, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*) + 1608
17 swift-frontend           0x0000000104bb1b38 swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 1100
18 swift-frontend           0x0000000104bc063c withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 160
19 swift-frontend           0x0000000104bb361c swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 3204
20 swift-frontend           0x0000000104a09414 swift::mainEntry(int, char const**) + 3304
21 dyld                     0x00000001122e5088 start + 516
```

**Expected behavior**
The test should run successfully. Although many functions and computed properties are denoted as `fatalError()`, none of these are executed since the function `a` is not actually called. Namely, the type information should be able to be reconstructed without error.

**Environment**
- Swift compiler version info: 2023-01-19a. Fails with versions as far back as 2022-07-15a. The type reconstruction succeeds on 2022-05-23a, however.
- Xcode version info: 13.3 (13E113)
- Deployment target: iOS 12.3.1, ARM64.

**Additional context**
If the 5 lines in code block 1 are uncommented, then building `testA` for profiling succeeds. Namely, manual specification of `@derivative(of: assignMain)` causes the build to succeed.

### LINKED ISSUE #63234: AutoDiff produces SIL that cannot be read back
This is a spin-off from https://github.com/apple/swift/issues/63207 to track the underlying issue. Currently autodiff produces SIL that cannot be parsed back. The reason is internal types that are never serialized as they are created in the artificial module.

Example SIL file is attached. Trying to parse it yields:
```
playground.sil:108:17: error: cannot find type '_AD__$s10playground5testAyyF1aL_5input10PlayGround1FVyS2dGAE1SVyS2dG_tF_bb0__PB__src_0_wrt_0' in scope
  %14 = struct $_AD__$s10playground5testAyyF1aL_5input10PlayGround1FVyS2dGAE1SVyS2dG_tF_bb0__PB__src_0_wrt_0 (%10 : $@callee_guaranteed (@inout F<Double, Double>) -> S<Double, Double>) // user: %16
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
playground.sil:117:136: error: cannot find type '_AD__$s10playground5testAyyF1aL_5input10PlayGround1FVyS2dGAE1SVyS2dG_tF_bb0__PB__src_0_wrt_0' in scope
sil private @$s10playground5testAyyF1aL_5input10PlayGround1FVyS2dGAE1SVyS2dG_tFTJpSpSr : $@convention(thin) (F<Double, Double>, @owned _AD__$s10playground5testAyyF1aL_5input10PlayGround1FVyS2dGAE1SVyS2dG_tF_bb0__PB__src_0_wrt_0) -> S<Double, Double> {
                                                                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

[playground.sil.txt](https://github.com/apple/swift/files/10509937/playground.sil.txt)

Tagging @BradLarson @rxwei @dan-zheng

### PR DESCRIPTION
**Pull request by asl**
The changes are intentionally were made close to the original implementation w/o possible simplifications to ease the review

Fixes #63207, supersedes #63379 (and fixes #63234)

### CODE REVIEW

**Comment by asl** [comment]
Tagging @BradLarson @dan-zheng

**Comment by asl** [comment]
@swift-ci please test

**Comment by dan-zheng** [comment]
Nice approach! This seems to simplify things and avoids the struct complications.

I wonder if there are still complications from the branching trace enums, since those are still `NominalTypeDecl`s who go through various verifications – but that would be separate.

**Comment by asl** [comment]
@dan-zheng Yes. I'm afraid we can cook a testcase that would trigger an assertion similar to https://github.com/apple/swift/issues/63207 but due to lack of imported branch trace enum type. Though, I believe it ought to be more complicated.

File: lib/SILOptimizer/Differentiation/LinearMapInfo.cpp [hunk 1]
```diff
@@ -137,31 +92,58 @@ LinearMapInfo::createBranchingTraceDecl(SILBasicBlock *originalBB,
...
-  branchingTraceDecl->getAttrs().add(new (astCtx) FrozenAttr(/*implicit*/ true));
   if (genericSig)
     branchingTraceDecl->setGenericSignature(genericSig);
-  computeAccessLevel(branchingTraceDecl, original->getEffectiveSymbolLinkage());
+  switch (original->getEffectiveSymbolLinkage()) {
+  case swift::SILLinkage::Public:
+  case swift::SILLinkage::PublicNonABI:
+    // Branching trace enums shall not be resilient.
+    branchingTraceDecl->getAttrs().add(new (astCtx) FrozenAttr(/*implicit*/ true));
+    branchingTraceDecl->getAttrs().add(new (astCtx) UsableFromInlineAttr(/*Implicit*/ true));
```
Comment (rxwei) [inline lib/SILOptimizer/Differentiation/LinearMapInfo.cpp:102]: Can we fix this based on https://github.com/apple/swift/pull/63379#discussion_r1096651096?  Adding `@usableFromInline` is not the right fix, and could just be moving the problem somewhere else, as I think this would eventually fail in TBD verification.

Comment (rxwei) [reply lib/SILOptimizer/Differentiation/LinearMapInfo.cpp:102]: Oh, sorry please disregard this. I'm looking at the wrong PR 🤦‍♂️

File: lib/SILOptimizer/Differentiation/LinearMapInfo.cpp [hunk 2]
```diff
@@ -392,44 +323,52 @@ void LinearMapInfo::generateDifferentiationDataStructures(
...
-        if (ArraySemanticsCall(ai, semantics::ARRAY_FINALIZE_INTRINSIC))
-          continue;
-        LLVM_DEBUG(getADDebugStream()
-                   << "Adding linear map struct field for " << *ai);
-        addLinearMapToStruct(context, ai);
+    SmallVector<TupleTypeElt, 4> linearTupleTypes;
+    if (!origBB.isEntry()) {
+      CanType traceEnumType = getBranchingTraceEnumLoweredType(&origBB).getASTType();
+      linearTupleTypes.emplace_back(traceEnumType,
+                                    astCtx.getIdentifier(traceEnumFieldName));
```
Comment (rxwei) [inline lib/SILOptimizer/Differentiation/LinearMapInfo.cpp:339]: ... wait I don't think SIL tuples are allowed to have labels, as it's no longer a canonical type? Am I misremembering this?

File: lib/SIL/IR/SILPrinter.cpp [hunk 3]
```diff
@@ -3433,6 +3433,36 @@ static void printSILDifferentiabilityWitnesses(
     dw->print(Ctx.OS(), Ctx.printVerbose());
 }
 
+static void printSILLinearMapTypes(SILPrintContext &Ctx,
```
Comment (rxwei) [inline lib/SIL/IR/SILPrinter.cpp:3436]: Is this only for printing branching trace enums now?

**Review by rxwei — APPROVED** [review]
This is super exciting!  For branching trace enums, perhaps we should explore adding a SIL-level sum type construct. Then we may be able to remove `SynthesizedFileUnit` altogether because it was added just for AD-generated types.

File: lib/SIL/IR/SILPrinter.cpp (hunk 3 above)
Comment (asl) [reply lib/SIL/IR/SILPrinter.cpp:3436]: Yes

**Comment by asl** [comment]
> This is super exciting! For branching trace enums, perhaps we should explore adding a SIL-level sum type construct. Then we may be able to remove SynthesizedFileUnit altogether because it was added just for AD-generated types.

Yeah, right. But maybe as a next step? :)

File: lib/SILOptimizer/Differentiation/LinearMapInfo.cpp (hunk 2 above)
Comment (asl) [reply lib/SILOptimizer/Differentiation/LinearMapInfo.cpp:339]: Well, it seems it does not cause any problems anywhere, the identifier is just stored in the type and that's it. I double checked – the generated SIL parses as well.

On the other hand – having named field for branch trace enum helps debugging as we're having internal contract with indices :)

**Comment by rxwei** [comment]
Sure, this is already strictly an improvement.

File: lib/SILOptimizer/Differentiation/LinearMapInfo.cpp (hunk 2 above)
Comment (rxwei) [reply lib/SILOptimizer/Differentiation/LinearMapInfo.cpp:339]: Ok.  Something unrelated: would it be better if we made the branching trace enum be the _last_ element? Might help with alignment in the tuple.

Comment (asl) [reply lib/SILOptimizer/Differentiation/LinearMapInfo.cpp:339]: Frankly speaking, I do not know :) I wanted to replicate the struct layout to minimize possible unknown fallback. This is certainly worth exploring if e.g. this might improve the codegen, etc.

**Comment by asl** [comment]
@swift-ci please test

**Comment by asl** [comment]
@rxwei I'm feeling like opening a can of worms as many things require original AST types, while we'd need to operate mostly on lowered SIL ones. I thought that I fixed all such places, but apparently not. The last failure was caused by assertion inside generic cloner as `metatype` instruction (which is used when we'd need to allocate linear map context in loopy cases) essentially requires AST type...

**Comment by asl** [comment]
@swift-ci please test

**Comment by asl** [comment]
@swift-ci please test

**Comment by asl** [comment]
@swift-ci please test

**Comment by asl** [comment]
MacOS test is broken due to broken main

**Comment by asl** [comment]
@swift-ci please test macos

**Comment by asl** [comment]
@swift-ci please test macos platform

**Comment by asl** [comment]
@swift-ci please test

**Comment by asl** [comment]
@swift-ci please test macos platform

**Comment by asl** [comment]
@swift-ci please test macos platform
