### PR TITLE
[Parse] Diagnose missing 'in' after closure signature

### LINKED ISSUE #59928: Missing 'in' in closure leads to unhelpful error
Compiling the following code
```swift
func test<T>(make: () -> [T], consume: (T) -> Void) {
    consume(make()[0])
}

func main() {
    test(make: { () -> [Int] // in
        print("hi")
        return [3]
    }, consume: { _ in
        print("bye")
    })
}
```

leads to the following diagnostics:
```
<source>:6:18: warning: expression of type '(() -> [Int]).Type' is unused
    test(make: { () -> [Int] // in
                 ^~~~~~~~~~~
<source>:6:18: error: expected member name or constructor call after type name
    test(make: { () -> [Int] // in
                 ^
<source>:6:28: note: use '.self' to reference the type object
    test(make: { () -> [Int] // in
                           ^
                 (          ).self
```
(thanks, swift.godbolt.org)

This is not a great error message for several reasons:
1. "constructor" instead of "initializer"
2. Function types don't currently have members or initializers anyway
3. A function type as *the first statement in a closure without a signature* is probably intended to be a signature

With parameters, we get different poor errors:

<details>

<summary><code>x -> Int</code>, <code>(x) -> Int</code></summary>

```swift
func test<T>(make: (Int) -> [T], consume: (T) -> Void) {
    consume(make(1)[0])
}

func main() {
    test(make: { x -> [Int] // in
        print("hi")
        return [3]
    }, consume: { _ in
        print("bye")
    })
}
```
```
<source>:6:18: error: cannot find 'x' in scope
    test(make: { x -> [Int] // in
                 ^
<source>:6:18: error: expected type before '->'
    test(make: { x -> [Int] // in
                 ^
<source>:6:5: error: type of expression is ambiguous without more context
    test(make: { x -> [Int] // in
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

</details>

<details>

<summary><code>(x: Int) -> Int</code></summary>

```swift
func test<T>(make: (Int) -> [T], consume: (T) -> Void) {
    consume(make(1)[0])
}

func main() {
    test(make: { (x: Int) -> [Int] // in
        print("hi")
        return [3]
    }, consume: { _ in
        print("bye")
    })
}
```
```
<source>:6:16: error: contextual type for closure argument list expects 1 argument, which cannot be implicitly ignored
    test(make: { (x: Int) -> [Int] // in
               ^
                 _ in
```

</details>

<details>

<summary><code>x, y -> Int</code></summary>

```swift
func test<T>(make: (Int, Int) -> [T], consume: (T) -> Void) {
    consume(make(1, 2)[0])
}

func main() {
    test(make: { x, y -> [Int] // in
        print("hi")
        return [3]
    }, consume: { _ in
        print("bye")
    })
}
```
```
<source>:6:19: error: consecutive statements on a line must be separated by ';'
    test(make: { x, y -> [Int] // in
                  ^
                  ;
<source>:6:19: error: expected expression
    test(make: { x, y -> [Int] // in
                  ^
<source>:6:18: error: cannot find 'x' in scope
    test(make: { x, y -> [Int] // in
                 ^
```

</details>

<details>

<summary><code>(x, y) -> Int</code></summary>

```swift
func test<T>(make: (Int, Int) -> [T], consume: (T) -> Void) {
    consume(make(1, 2)[0])
}

func main() {
    test(make: { (x, y) -> [Int] // in
        print("hi")
        return [3]
    }, consume: { _ in
        print("bye")
    })
}
```
```
<source>:6:19: error: cannot find 'x' in scope
    test(make: { (x, y) -> [Int] // in
                  ^
<source>:6:22: error: cannot find 'y' in scope
    test(make: { (x, y) -> [Int] // in
                     ^
<source>:6:18: error: expected type before '->'
    test(make: { (x, y) -> [Int] // in
                 ^
<source>:6:5: error: type of expression is ambiguous without more context
    test(make: { (x, y) -> [Int] // in
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

</details>

<details>

<summary><code>(x: Int, y: Int) -> Int</code></summary>

```swift
func test<T>(make: (Int, Int) -> [T], consume: (T) -> Void) {
    consume(make(1, 2)[0])
}

func main() {
    test(make: { (x: Int, y: Int) -> [Int] // in
        print("hi")
        return [3]
    }, consume: { _ in
        print("bye")
    })
}
```
```
<source>:6:16: error: contextual type for closure argument list expects 2 arguments, which cannot be implicitly ignored
    test(make: { (x: Int, y: Int) -> [Int] // in
               ^
                 _,_ in
```

</details>

### PR DESCRIPTION
**Pull request by kwikysw**
Teach the parser to recognize a top-level '->' in a closure as a signature and
produce a targeted diagnostic ("expected 'in' after the closure signature")
instead of treating it as a type expression.

Adds a parser test:
- test/Parse/closure-missing-in.swift

Resolves swiftlang/swift#59928

### CODE REVIEW

**Comment by kwikysw** [comment]
Hi all. This is a small parser diagnostic change (+ test),
opened over a week ago. CI is pending but green locally. 
Happy to address any feedback. Thanks!

File: lib/Parse/ParseExpr.cpp [hunk 1]
```diff
@@ -2620,10 +2620,13 @@ ParserStatus Parser::parseClosureSignatureIfPresent(
...
 
     // Parse the 'in' at the end.
-    if (Tok.isNot(tok::kw_in))
-      return makeParserSuccess();
-
-    // Okay, we have a closure signature.
+    if (Tok.isNot(tok::kw_in)) {
+      // We saw a closure-signature shape but no 'in'. Do not return here.
+      // The real parse below produces 'expected_closure_in' and recovers.
+      // BacktrackingScope will restore the token stream for the real parse.
```
Comment (rintaro) [inline lib/Parse/ParseExpr.cpp]: Thank you for working on this!

Unfortunately this is source breaking. For example, consider `{ [x, y] }`, this is currently a valid closure returning an array of two elements. However with your change, it would be parsed as a closure with a capture list and a missing `in`.

As I mentioned in https://github.com/swiftlang/swift/issues/59928#issuecomment-1176788853 you could check whether `consumeIf(tok::arrow)` above returned true, so we know the skipped tokens actually look like a closure signature (because there's no valid expression that contain `->` at top-level). That won't resolve https://github.com/swiftlang/swift-syntax/issues/2204 case, but it would at least address the cases covered by your tests.

**Review by rintaro — COMMENTED** [review]
Also you'd need a corresponding fix (and test cases) for https://github.com/swiftlang/swift-syntax repo.
Specifically [`Parser.Lookahead.canParseClosureSignature()`](https://github.com/swiftlang/swift-syntax/blob/6673b05995983461eef015c4768f1483c245db22/Sources/SwiftParser/Expressions.swift#L2587-L2662)

File: lib/Parse/ParseExpr.cpp (hunk 1 above)
Comment (kwikysw) [reply lib/Parse/ParseExpr.cpp]: Thanks for the guidance, as well as the advice about needing the tests for swift-syntax too. I’ll gate the diagnostic on seeing a top-level -> as you said, during speculative scan (so if consumeIf(tok::arrow) succeeds at depth 0 and canParseType() accepts the following type). if no top-level ->, we treat it as an expression so the { [x, y] } remains an array literal. 

Could you please confirm if we should not use bare **async/throws** as a gate and that they're only considered when a top-level (not inside any nested (...)/[...]/{...}) -> is present. Also if -> is seen but canParseType() fails, we should bail out an expression to avoid false positives ?

Comment (rintaro) [reply lib/Parse/ParseExpr.cpp]: > Could you please confirm if we should not use bare async/throws as a gate and that they're only considered when a top-level (not inside any nested (...)/[...]/{...}) -> is present. 

I'd say no for `async` et al because `async` is a contextual keyword hence `var async = 1; _ = { async }` is valid. Although `throws` is a hard keyword, but handling differently between `async` and `throws` sounds weird.

> Also if -> is seen but canParseType() fails, we should bail out an expression to avoid false positives ?

Yes, that sounds good to me. That keeps the current behavior and safer.

**Comment by kwikysw** [comment]
Hi @rintaro. I updated the patch so that we only treat it as a closure signature in lookahead when we see a top-level ->. Bare async/throws are not used as gates and if we don't see a top-level arrow, we bail to expression (restoring the previous makeParserSucess() behavior). I had to gate the new diagnostic behind isSwiftVersionAtLeast(5) given some parser tests run in swift 4 mode. If this looks correct, I'll follow up with the corresponding change + tests in swift-syntax's Parser.Lookahead.canParseClosureSignature.

**Comment by bnbarham** [comment]
> I had to gate the new diagnostic behind isSwiftVersionAtLeast(5) given some parser tests run in swift 4 mode

What tests were failing here? And what was the failure? I wouldn't have expected needing to gate this at all 🤔

**Comment by kwikysw** [comment]
> > I had to gate the new diagnostic behind isSwiftVersionAtLeast(5) given some parser tests run in swift 4 mode
> 
> What tests were failing here? And what was the failure?

I misstated earlier, no parser tests broke semantically. The only failures were in a **swift 4 mode** verify test, not **swift 5+**. In [test/Parse/type_expr.swift](https://github.com/swiftlang/swift/blob/main/test/Parse/type_expr.swift), it runs with **RUN: %target-typecheck-verify-swift -swift-version 4 -module-name test** and in testInvalidArrowWithClosure, the line _ = { undefined -> undefined2 } has the parser take the type-expression path and expects the old diagnostics: 

- cannot find 'undefined' in scope
- cannot find 'undefined2' in scope
- expected type before '->'
- expected type after '->' but my change in lookahead sees a top-level '->' and treats this as a closure signature then emits "expected 'in' after closure signature".

**Comment by rintaro** [comment]
That sounds like expected changes. Please remove the `Context.LangOpts.isSwiftVersionAtLeast(5)` check and update the existing test cases as needed.

File: lib/Parse/ParseExpr.cpp [hunk 2]
```diff
@@ -2612,18 +2615,22 @@ ParserStatus Parser::parseClosureSignatureIfPresent(
...
     }
 
     // Parse the 'in' at the end.
-    if (Tok.isNot(tok::kw_in))
-      return makeParserSuccess();
-
-    // Okay, we have a closure signature.
+    if (Tok.isNot(tok::kw_in)) {
+      bool shouldTreatAsClosure = Context.LangOpts.isSwiftVersionAtLeast(5) && sawTopLevelArrowInLookahead;
+      if (!shouldTreatAsClosure)
```
Comment (rintaro) [inline lib/Parse/ParseExpr.cpp]: Could you add some comment like:
```
// Even if 'in' is missing, the presence of '->' makes this look like a closure signature.
// There’s no other valid syntax that could legally contain '->' at this position.
```
(Please add newlines as needed, C++ code in this repository have 80 columns limit)

Comment (kwikysw) [reply lib/Parse/ParseExpr.cpp]: I've just made the requested changes, let me know if anything else is needed.

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test

File: lib/Parse/ParseExpr.cpp [hunk 3]
```diff
@@ -2612,18 +2615,25 @@ ParserStatus Parser::parseClosureSignatureIfPresent(
...
     }
 
     // Parse the 'in' at the end.
-    if (Tok.isNot(tok::kw_in))
-      return makeParserSuccess();
+    if (Tok.isNot(tok::kw_in)) {
+      // Even if 'in' is missing, the presence of '->' makes this look
+      // like a closure signature. There's no other valid syntax that
+      // could legally contain '->' at this position.
+      bool shouldTreatAsClosure = sawTopLevelArrowInLookahead;
```
Comment (rintaro) [inline lib/Parse/ParseExpr.cpp]: I don't think `shouldTreatAsClosure` is needed here. Let's just use `sawTopLevelArrowInLookahead`.

**Review by rintaro — COMMENTED** [review]
The change looks fine to me, thank you!
Please go ahead and create corresponding swift-syntax PR.

File: lib/Parse/ParseExpr.cpp (hunk 3 above)
Comment (kwikysw) [reply lib/Parse/ParseExpr.cpp]: Yep, I've removed it. I'll create the swift-syntax PR.

File: lib/Parse/ParseExpr.cpp [hunk 4]
```diff
@@ -2612,18 +2615,24 @@ ParserStatus Parser::parseClosureSignatureIfPresent(
...
+    if (Tok.isNot(tok::kw_in)) {
+      // Even if 'in' is missing, the presence of '->' makes this look
+      // like a closure signature. There's no other valid syntax that
+      // could legally contain '->' at this position.
+      if (!sawTopLevelArrowInLookahead)
+        return makeParserSuccess();
 
-    // Okay, we have a closure signature.
+      // Okay, we have a closure signature.
+    }
```
Comment (rintaro) [inline lib/Parse/ParseExpr.cpp]: Nit-pick: 
```suggestion
    }
    // Okay, we have a closure signature.
```

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Comment by rintaro** [comment]
@swift-ci Please smoke test Windows

**Comment by rintaro** [comment]
@swift-ci Please smoke test Linux

**Comment by rintaro** [comment]
@swift-ci Please smoke test Windows

**Comment by rintaro** [comment]
@kwikysw This PR can be merged independently, but I'll hold off on merging it until the corresponding swift-syntax PR is up, to prevent divergence.

**Comment by kwikysw** [comment]
> @kwikysw This PR can be merged independently, but I'll hold off on merging it until the corresponding swift-syntax PR is up, to prevent divergence.

I'm working on it right now, sorry for the delay

**Comment by rintaro** [comment]
Nothing to sorry, thank you for working on this!

**Review by rintaro — APPROVED** [review]
