### PR TITLE
[Sema] Catch use-before-declarations in nested closures

### LINKED ISSUE #83628: Wrong compiler error "Closure captures variable before it is declared"
### Description

The compiler incorrectly reports an error "Closure captures variable before it is declared" when a closure captures a variable that is shadowed later.

### Reproduction

```swift
var array = [0]
let otherArray = [0]
if true {
    array.append(contentsOf: otherArray.filter({ !array.contains($0) }))
    let array = array
}
```

### Expected behavior

No compiler error.

### Environment

swift-driver version: 1.120.5 Apple Swift version 6.1.2 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
Target: arm64-apple-macosx15.0

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by hamishknight**
Previously we would allow these in Sema and diagnose them in SILGen, but allowing them in Sema is unsound because it means the constraint system ends up kicking interface type requests for declarations that should be type-checked as part of the closure itself. Adjust the name lookup logic to look through parent closures when detecting invalid forward references. This then allows us to have consistent shadowing behavior inside and outside of closures.

Forum post: https://forums.swift.org/t/ensuring-forward-references-to-local-variables-are-consistently-rejected/83265

rdar://74430478
rdar://163656720
Resolves #83628

### CODE REVIEW

File: test/Sema/diag_use_before_declaration.swift [hunk 1]
```diff
@@ -80,6 +80,141 @@ func nested_scope_3() {
...
+  lazy var hmm: () -> Any = { hmm }
+  // expected-error@-1 {{use of local variable 'hmm' before its declaration}}
+  // expected-note@-2 {{'hmm' declared here}}
+}
+
+func forward_declared_computed_locals() {
+  // In principle we could allow these, but it's simpler to just reject them.
+  let x = z // expected-error {{use of local variable 'z' before its declaration}}
+  let y = { z } // expected-error {{use of local variable 'z' before its declaration}}
+  var z: Int { 0 } // expected-note 2{{'z' declared here}}
```
Comment (hamishknight) [inline test/Sema/diag_use_before_declaration.swift:215]: `x` here was already illegal, this change also makes `y` illegal. In principle we could allow forward references for computed vars, but I think it's much better to have a consistent behavior for all variables.

**Comment by hamishknight** [comment]
@swift-ci please test macOS

File: CHANGELOG.md [hunk 2]
```diff
@@ -3,7 +3,61 @@
...
+  following previously illegal case to become legal:
+
+  ```swift
+  struct S {
+    var x: Int
+    func foo() {
+      let x = x // Already legal, refers to `self.x`.
+    }
+    func bar() {
+      let x = { x } // Previously illegal, now also refers to `self.x`.
```
Comment (jamieQ) [inline CHANGELOG.md]: in a reference type example, do we still get the existing 'implicit self' diagnostics?

Comment (hamishknight) [reply CHANGELOG.md]: Yup, added test case for that

**Comment by hamishknight** [comment]
@swift-ci please test Linux

File: test/Sema/diag_use_before_declaration.swift (hunk 1 above)
Comment (xedin) [reply test/Sema/diag_use_before_declaration.swift:215]: I think that makes sense as well!

**Review by xedin — APPROVED** [review]

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please smoke test

**Comment by hamishknight** [comment]
@swift-ci please smoke test
