### PR TITLE
[Diagnostics][Sema] Improving global actor function mismatch diagnostic

### LINKED ISSUE #62544: [Diagnostics] Global actor failure in function matching should produce tailored diagnostic
**Description**
Consider
```swift
@globalActor
struct GA {
  actor A {}
  static let shared: A = A()
}
let y: @GA () -> Void = {}
let x: @MainActor () -> Void  = y // error: cannot convert value of type 'GA' to specified type 'MainActor'
```

**Steps to reproduce**
The snippet above produces a diagnostic that states `value of type GA` which isn't correct in this case because the value is of a function type, and what is actually happening is a global actual mismatch between values of function type.

**Expected behavior**
We should produce a more specific diagnostic in this case to indicate that an global actor mismatch is the issue.

**Environment**
- Swift compiler version info main @45cd83d73e00230725849603d143ece95bc74467

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Just an improvement on global actor mismatch diagnostics. 
We could later on consider adding a tailored diagnostics(I've experimented with that but felt a bit overkill) for it or an additional note(also experimented with but the note there felt redundant since global actor is printed) mentioning global actor mismatch but that could be a further discussion since mismatch diagnostics already print global actor in function types this already a good improvement.
Also, strengthened a bit the test cases for different kinds of mismatches 

Resolves https://github.com/apple/swift/issues/62544

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

File: lib/Sema/CSSimplify.cpp [hunk 1]
```diff
@@ -3058,7 +3058,8 @@ ConstraintSystem::matchFunctionTypes(FunctionType *func1, FunctionType *func2,
       // If both have a global actor, match them.
       TypeMatchOptions subflags = getDefaultDecompositionOptions(flags);
       auto result = matchTypes(func1->getGlobalActor(), func2->getGlobalActor(),
-                               ConstraintKind::Equal, subflags, locator);
+                               ConstraintKind::Equal,
+                               subflags | TMF_ApplyingFix, locator);
```
Comment (xedin) [inline lib/Sema/CSSimplify.cpp:3062]: This is not technically correct because we not not matching to apply a fix in this case.

Comment (xedin) [reply lib/Sema/CSSimplify.cpp:3062]: Also it seems to be that the actual function type is not important here at all, a better failure would to something like - `cannot pass value isolated to <GlobalActorA> to parameter that expects a value isolated to <GlobalActorB>`

Comment (LucianoPAlmeida) [reply lib/Sema/CSSimplify.cpp:3062]: > Also it seems to be that the actual function type is not important here at all, a better failure would to something like - `cannot pass value isolated to <GlobalActorA> to parameter that expects a value isolated to <GlobalActorB>` and `cannot convert value isolated to <GlobalActorA> to value isolated to <GlobalActorB>`

Makes sense, I'll fix as soon as possible. Thanks @xedin =]

File: lib/Sema/CSSimplify.cpp [hunk 2]
```diff
@@ -3056,11 +3056,19 @@ ConstraintSystem::matchFunctionTypes(FunctionType *func1, FunctionType *func2,
...
       // If both have a global actor, match them.
-      TypeMatchOptions subflags = getDefaultDecompositionOptions(flags);
-      auto result = matchTypes(func1->getGlobalActor(), func2->getGlobalActor(),
-                               ConstraintKind::Equal, subflags, locator);
-      if (result == SolutionKind::Error)
-        return getTypeMatchFailure(locator);
+      const auto subflags = getDefaultDecompositionOptions(flags);
+      auto result = [&]() {
+        llvm::SaveAndRestore<ConstraintSystemOptions> options(
+            Options, Options - ConstraintSystemFlags::AllowFixes);
```
Comment (xedin) [inline lib/Sema/CSSimplify.cpp:3062]: This kind of seems like it's trying to workaround some problem and I think that problem is that `locator` passed to the `matchType` under this declaration should actually be different (with an extract element at the end) to identify for `repairFailures` that is going to be called by upcoming `matchTypes` that we are matching an attribute location.

**Review by xedin — COMMENTED** [review]
Looking much better now, left a few comments inline!

File: lib/Sema/CSSimplify.cpp (hunk 2 above)
Comment (LucianoPAlmeida) [reply lib/Sema/CSSimplify.cpp]: Yeah, I have actually considered this option before. Just fixed!

File: include/swift/Sema/CSFix.h [hunk 3]
```diff
@@ -421,6 +421,10 @@ enum class FixKind : uint8_t {
 
   /// Macro that has parameters but was not provided with any arguments.
   MacroMissingArguments,
+
+  /// Allow function type actor mismatch e.g. `@MainActor () -> Void`
+  /// vs.`@OtherActor () -> Void`
+  AllowFunctionTypeActorMismatch,
```
Comment (xedin) [inline include/swift/Sema/CSFix.h:427]: Maybe simply `AllowGlobalActorMismatch`?

**Review by xedin — APPROVED** [review]
LGTM!

**Comment by LucianoPAlmeida** [comment]
Thank you for the review @xedin!
@swift-ci Please test
