### PR TITLE
[ConstraintSystem] Set up keypath expressions typechecking

### LINKED ISSUE #65467: Failed to produce diagnostic when unable to choose correct initializer inside of result builder
**Description**
When you have (1) a key path to a value of type A, passed to (2) a struct initializer with two overloads which expect the key path to be either of type B or C, (3) inside of a result builder, Swift reports “failed to produce diagnostic for expression; please submit a bug report” instead of a useful error.

**Steps to reproduce**
```swift
struct Model {
    let member = ""
}

struct Wrapper {
    // produces correct error message if one of these is removed
    init(keyPath: KeyPath<Model, Int32>) {}
    init(keyPath: KeyPath<Model, Float>) {}
}

// can be any result builder
@resultBuilder struct MyResultBuilder {
    static func buildBlock(_ components: Void...) -> Void {}
}

// 🛑 Type of expression is ambiguous without more context
let baz = Wrapper(keyPath: \.member)

@MyResultBuilder
// 🛑 Failed to produce diagnostic for expression
var built: Void {
    let baz = Wrapper(keyPath: \.member)
}
```

**Expected behavior**

```
error: TypeConfusion.playground:18:15: error: no exact matches in call to initializer 
    let baz = Wrapper(keyPath: \.member)
              ^

TypeConfusion.playground:7:5: note: candidate expects value of type 'KeyPath<Model, Int32>' for parameter #1 (got 'KeyPath<Model, String>')
    init(keyPath: KeyPath<Model, Int32>) {}
    ^

TypeConfusion.playground:8:5: note: candidate expects value of type 'KeyPath<Model, Float>' for parameter #1 (got 'KeyPath<Model, String>')
    init(keyPath: KeyPath<Model, Float>) {}
```

**Environment**
- Both the integrated Swift toolchain and Swift Development Snapshot 2023-04-25 (a)
- Xcode 14.3, Build version 14E222b
- Deployment target: macOS 13.3

### PR DESCRIPTION
**Pull request by amritpan**
to use the contextual type determined by the solver along with the [key path root and value variables saved in `visitKeyPathExpr`](https://github.com/apple/swift/pull/67157) and delay key path value type checking until it is directly bound. This is an incremental step towards changing key path expression type checking to not prematurely generate constraints and type variables and instead wait until all other relevant parts of the source code have been resolved to determine a contextual type for the key path expression.

Resolves #65467

### CODE REVIEW

File: lib/Sema/CSSimplify.cpp [hunk 1]
```diff
@@ -4419,6 +4419,14 @@ ConstraintSystem::matchTypesBindTypeVar(
                : getTypeMatchFailure(locator);
   }
 
+  // If typeVar is key path value, leave unsolved until it is directly bound.
```
Comment (xedin) [inline lib/Sema/CSSimplify.cpp:4422]: - I think this needs to be wrapped in `if (shouldAttemptFixes())`
- For the comment, how about - `if type variable represents a key path value type, differ binding it to contextual type in diagnostic mode. We want it to be bound from the last key path component to help with diagnostics.`

**Review by xedin — CHANGES_REQUESTED** [review]
I left a few comments inline and please add a test-case which shows an improvement in diagnostics.

**Comment by xedin** [comment]
@amritpan I think code looks good now we just need a few test-cases to make sure it works properly.

File: lib/Sema/CSSimplify.cpp [hunk 2]
```diff
@@ -4621,6 +4628,13 @@ repairViaBridgingCast(ConstraintSystem &cs, Type fromType, Type toType,
   return true;
 }
 
+/// Return tuple of type and number of optionals on that type.
+static std::pair<Type, unsigned> repairViaOptionalInjection(Type type) {
```
Comment (xedin) [inline lib/Sema/CSSimplify.cpp:4632]: I think this should be named `getObjectTypeAndNumUnwraps` still.

File: test/Constraints/keypath.swift [hunk 3]
```diff
@@ -180,6 +180,20 @@ func key_path_root_mismatch<T>(_ base: KeyPathBase?, subBase: KeyPathBaseSubtype
 
 }
 
+func key_path_value_mismatch() {
+	struct S {
```
Comment (xedin) [inline test/Constraints/keypath.swift:184]: Nit: we use 2 space alignments in the tests.

File: test/Constraints/keypath.swift [hunk 4]
```diff
@@ -136,8 +136,8 @@ func test_mismatch_with_contextual_optional_result() {
     var arr: [Int] = []
   }
 
-  let _ = A(B(), keyPath: \.arr)
-  // expected-error@-1 {{key path value type '[Int]' cannot be converted to contextual type '[Int]?'}}
+  let _ = A(B(), keyPath: \.arr) // expected-error {{cannot convert value of type 'KeyPath<B, [Int]>' to expected argument type 'KeyPath<B, [Int]?>'}}
+	// expected-note@-1 {{arguments to generic parameter 'Value' ('[Int]' and '[Int]?') are expected to be equal}}
```
Comment (xedin) [inline test/Constraints/keypath.swift:140]: Nit: Please align // expected-note under `let`.

**Review by xedin — CHANGES_REQUESTED** [review]

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility debug
