### PR TITLE
[AutoDiff] Initial support for differentiation of throwing functions

### LINKED ISSUE #70819: [AutoDiff] Fatal error of "do not know how to handle this incoming bb argument" when using a throwing function inside a differentiable function
### Description

The use of a differentiable throwing function within an encapsulating differentiable function leads to a fatal error at compile time of `do not know how to handle this incoming bb argument`. This is similar to the case in #57523, but instead of the throwing function being used directly in `gradient(at:of:)` it is instead surrounded by a non-throwing differentiable function.

### Reproduction

The following simple program reproduces this in a regular `swiftc` build:

```swift
import _Differentiation

@differentiable(reverse)
func test1(input: Float) throws -> Float {
    return input
}

@differentiable(reverse)
func test2(input: Float) -> Float {
    do {
        return try test1(input: input)
    } catch {
        return 0.0
    }
}

let (value, gradient) = valueWithGradient(at: 1.0, of: test2)
print("Value: \(value), gradient: \(gradient)")
```

The trace produced looks something like the following:

```
error: compile command failed due to signal 6 (use -v to see invocation)
<unknown>:0: error: fatal error encountered during compilation; please submit a bug report (https://swift.org/contributing/#reporting-bugs)
<unknown>:0: note: do not know how to handle this incoming bb argument
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2023-12-07-a.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /Users/larson/Desktop/throwstest.swift -target arm64-apple-macosx13.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.sdk -color-diagnostics -new-driver-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2023-12-07-a.xctoolchain/usr/bin/swift-driver -empty-abi-descriptor -resource-dir /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2023-12-07-a.xctoolchain/usr/lib/swift -module-name throwstest -target-sdk-version 14.2 -target-sdk-name macosx14.2 -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.sdk/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.sdk/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -plugin-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2023-12-07-a.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2023-12-07-a.xctoolchain/usr/local/lib/swift/host/plugins -o /var/folders/6y/ghmhq_xj3xq100vsttqqn2lc0000gq/T/TemporaryDirectory.jYso3S/throwstest-1.o
1.	Apple Swift version 5.11-dev (LLVM 91cd37b9110872c, Swift 703a4719b0c6f3a)
2.	Compiling with the current language version
3.	While evaluating request ExecuteSILPipelineRequest(Run pipelines { Mandatory Diagnostic Passes + Enabling Optimization Passes } on SIL for throwstest)
4.	While running pass #70 SILModuleTransform "Differentiation".
5.	While processing // differentiability witness for test2(input:)
sil_differentiability_witness hidden [reverse] [parameters 0] [results 0] @$s10throwstest5test25inputS2f_tF : $@convention(thin) (Float) -> Float {
}

 on SIL function "@$s10throwstest5test25inputS2f_tF".
 for 'test2(input:)' (at /Users/larson/Desktop/throwstest.swift:9:1)
6.	While generating VJP for SIL function "@$s10throwstest5test25inputS2f_tF".
 for 'test2(input:)' (at /Users/larson/Desktop/throwstest.swift:9:1)
7.	While generating pullback for SIL function "@$s10throwstest5test25inputS2f_tF".
 for 'test2(input:)' (at /Users/larson/Desktop/throwstest.swift:9:1)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x00000001061db150 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x00000001061d98ac llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x00000001061db7a0 SignalHandler(int) + 304
3  libsystem_platform.dylib 0x000000019cd5ea24 _sigtramp + 56
4  libsystem_pthread.dylib  0x000000019cd2fc28 pthread_kill + 288
5  libsystem_c.dylib        0x000000019cc3dae8 abort + 180
6  swift-frontend           0x0000000100d8e848 PrettyStackTraceFrontend::~PrettyStackTraceFrontend() + 0
7  swift-frontend           0x0000000106154f84 llvm::report_fatal_error(llvm::Twine const&, bool) + 268
8  swift-frontend           0x0000000106154e78 llvm::report_fatal_error(llvm::Twine const&, bool) + 0
9  swift-frontend           0x000000010148e5dc swift::autodiff::PullbackCloner::Implementation::visitSILBasicBlock(swift::SILBasicBlock*) + 2680
10 swift-frontend           0x000000010148adcc swift::autodiff::PullbackCloner::Implementation::run() + 5276
11 swift-frontend           0x00000001014898f8 swift::autodiff::PullbackCloner::run() + 24
12 swift-frontend           0x00000001014a7670 swift::autodiff::VJPCloner::Implementation::run() + 1368
13 swift-frontend           0x00000001014a7da4 swift::autodiff::VJPCloner::run() + 24
14 swift-frontend           0x00000001015f05d4 (anonymous namespace)::DifferentiationTransformer::canonicalizeDifferentiabilityWitness(swift::SILDifferentiabilityWitness*, swift::autodiff::DifferentiationInvoker, swift::IsSerialized_t) + 6212
15 swift-frontend           0x00000001015ee460 (anonymous namespace)::Differentiation::run() + 1032
16 swift-frontend           0x00000001016a0a8c swift::SILPassManager::runModulePass(unsigned int) + 976
17 swift-frontend           0x00000001016a6b60 swift::SILPassManager::execute() + 624
18 swift-frontend           0x000000010169d950 swift::SILPassManager::executePassPipelinePlan(swift::SILPassPipelinePlan const&) + 68
19 swift-frontend           0x000000010169d8d8 swift::ExecuteSILPipelineRequest::evaluate(swift::Evaluator&, swift::SILPipelineExecutionDescriptor) const + 68
20 swift-frontend           0x00000001016e0794 swift::SimpleRequest<swift::ExecuteSILPipelineRequest, std::__1::tuple<> (swift::SILPipelineExecutionDescriptor), (swift::RequestFlags)1>::evaluateRequest(swift::ExecuteSILPipelineRequest const&, swift::Evaluator&) + 28
21 swift-frontend           0x00000001016c8510 llvm::Expected<swift::ExecuteSILPipelineRequest::OutputType> swift::Evaluator::getResultUncached<swift::ExecuteSILPipelineRequest>(swift::ExecuteSILPipelineRequest const&) + 268
22 swift-frontend           0x000000010169db40 swift::executePassPipelinePlan(swift::SILModule*, swift::SILPassPipelinePlan const&, bool, swift::irgen::IRGenModule*) + 84
23 swift-frontend           0x00000001016cb4f8 swift::runSILDiagnosticPasses(swift::SILModule&) + 192
24 swift-frontend           0x0000000100f77740 swift::CompilerInstance::performSILProcessing(swift::SILModule*) + 80
25 swift-frontend           0x0000000100d87b84 performCompileStepsPostSILGen(swift::CompilerInstance&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*) + 792
26 swift-frontend           0x0000000100d87284 swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 596
27 swift-frontend           0x0000000100d96ab8 withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 160
28 swift-frontend           0x0000000100d89e78 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 704
29 swift-frontend           0x0000000100d88e3c swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2632
30 swift-frontend           0x0000000100c30c6c swift::mainEntry(int, char const**) + 2192
31 dyld                     0x000000019c9d7f28 start + 2236
error: fatalError
```

### Expected behavior

The above should compile without error, and automatic differentiation should work correctly through the throwing function.

### Environment

This is not a new regression, and is present in nightly toolchain snapshots and releases on various platforms dating back through at least the last year.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by asl**
This adds initial support for differentiation of functions that may produce `Error` result. Essentially we wrap the pullback into `Optional` and emit a diamond-shape control flow pattern depending on whether the pullback value is available or not. VJP emission was modified to accommodate for this. In addition to this, some additional tricks are required as `try_apply` result is not available in the instruction parent block, it is available in normal successor basic block.

As a result we can now:
 - differentiate an active `try_apply` result (that would be produced from `do ... try .. catch` constructions)
 - `try_apply` when error result is unreachable (usually `try!` and similar source code constructs)
 - Support (some) throwing functions with builtin differentiation operators. stdlib change will follow. Though we cannot support typed throws here (yet)
 - Correctly propagate error types during currying around differentiable functions as well as type-checking for `@derivative(of:)` attribute, so we can register custom derivatives for functions producing error result
 - Added custom derivative for `Optional.??` operator (note that support here is not yet complete as we cannot differentiate through autoclosures, so `x ?? y` works only if `y` is not active, e.g. a constant value).

Some fixes here and there

### CODE REVIEW

**Comment by asl** [comment]
Tagging @JaapWijnen @kovdan01

**Comment by asl** [comment]
@swift-ci please test

**Comment by asl** [comment]
@swift-ci please test

**Comment by asl** [comment]
Windows fails in unrelated `IRGen/async/run-call-void-throws-to-int-throwing_call-sync-nothrow_call-async-throw.sil`

@swift-ci please test windows platform

File: test/AutoDiff/validation-test/throw.swift [hunk 1]
```diff
@@ -0,0 +1,83 @@
+// RUN: %target-run-simple-swift
+// REQUIRES: executable_test
+
+import StdlibUnittest
+import DifferentiationUnittest
+
+var ThrowingTests = TestSuite("Throwing")
+
+enum E: Error {
+    case error
```
Comment (kovdan01) [inline test/AutoDiff/validation-test/throw.swift]: Nit: it's probably worth using consistent indentation level across the file. In this file 2-spaces and 4-spaces indents are mixed.

File: test/AutoDiff/SILOptimizer/optional_error.swift [hunk 2]
```diff
@@ -8,12 +8,22 @@ import _Differentiation
 func o(ff: F) -> Double {
     var y = ff.i?.first { $0 >= 0.0 } ?? 0.0
     while 0.0 < y {
-        // expected-note @+1 {{expression is not differentiable}}
+        // This one is not differentiable since rhs of ?? is an autoclosure that we cannot differentiate wrt.
+        // The variant above has rhs as non-active and therefore everything works.
```
Comment (kovdan01) [inline test/AutoDiff/SILOptimizer/optional_error.swift]: > The variant above

Have you meant "The variant below" (in `o2` function)?

File: lib/SILOptimizer/Differentiation/VJPCloner.cpp [hunk 3]
```diff
@@ -989,16 +989,272 @@ class VJPCloner::Implementation final
...
+        if (pullbackFnType != pullbackUnsubstFnType) {
+          pullback = trampolineBuilder.createConvertFunction(
+            loc, pullback,
+            SILType::getPrimitiveObjectType(pullbackUnsubstFnType),
+            /*withoutActuallyEscaping*/ false);
+        }
+      }
+
+      // Store the original result to the value map.
+      //mapValue(ai, originalDirectResult);
```
Comment (kovdan01) [inline lib/SILOptimizer/Differentiation/VJPCloner.cpp]: Nit: it looks like some WIP code which is now not needed was left commented here

File: lib/SILOptimizer/Differentiation/LinearMapInfo.cpp [hunk 4]
```diff
@@ -311,10 +313,13 @@ Type LinearMapInfo::getLinearMapType(ADContext &context, FullApplySite fai) {
         params, silFnTy->getAllResultsInterfaceType().getASTType(), info);
   }
 
-  if (astFnTy->hasArchetype())
-    return astFnTy->mapTypeOutOfContext();
+  Type resultType = astFnTy->hasArchetype() ? astFnTy->mapTypeOutOfContext() : astFnTy;
+
+
```
Comment (kovdan01) [inline lib/SILOptimizer/Differentiation/LinearMapInfo.cpp]: Nit: probably one empty line is enough for readability :)

File: lib/AST/Builtins.cpp [hunk 5]
```diff
@@ -2892,6 +2892,7 @@ ValueDecl *swift::getBuiltinValueDecl(ASTContext &Context, Identifier Id) {
     if (!autodiff::getBuiltinApplyDerivativeConfig(
             OperationName, kind, arity, throws))
       return nullptr;
+    // TODO: Support somehow typed throws
```
Comment (kovdan01) [inline lib/AST/Builtins.cpp]: Do we have tests showing that this is unsupported?

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 6]
```diff
@@ -807,7 +814,8 @@ class PullbackCloner::Implementation final
   // CFG mapping
   //--------------------------------------------------------------------------//
 
-  SILBasicBlock *getPullbackBlock(SILBasicBlock *originalBlock) {
+  std::pair<SILBasicBlock *, SILBasicBlock *>
+  getPullbackBlock(SILBasicBlock *originalBlock) {
```
Comment (kovdan01) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp]: Nit
```suggestion
  getPullbackBlock(const SILBasicBlock *originalBlock) const {
```

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 7]
```diff
@@ -989,26 +1000,136 @@ class PullbackCloner::Implementation final
       return;
     }
 
-    buildPullbackCall(ai);
+    auto &nestedApplyInfo = getContext().getNestedApplyInfo();
```
Comment (kovdan01) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp]: Do I get it correct that you moved this piece of code out of `buildPullbackCall` because in `visitTryApplyInst` we need to perform the check long before calling `buildPullbackCall`? Could we somehow get rid of duplicating this check in 3 places by introducing some kind of helper for this?

File: lib/SILGen/SILGenBuiltin.cpp [hunk 8]
```diff
@@ -1324,7 +1326,7 @@ static ManagedValue emitBuiltinApplyDerivative(
       builtinName, kind, arity, throws);
   assert(successfullyParsed);
   return emitBuiltinAutoDiffApplyDerivativeFunction(
-      kind, arity, throws, SGF, loc, substitutions, args, C);
```
Comment (kovdan01) [inline lib/SILGen/SILGenBuiltin.cpp]: We also probably do not need `throws` declaration above and corresponding out parameter in `autodiff::getBuiltinApplyDerivativeConfig`

File: lib/Sema/TypeCheckAttr.cpp [hunk 9]
```diff
@@ -6271,15 +6277,19 @@ getTransposeOriginalFunctionType(AnyFunctionType *transposeFnType,
   // `(Self) -> (<original parameters>) -> <original result>`.
   if (isCurried) {
     assert(selfType && "`Self` type should be resolved");
-    originalType = makeFunctionType(originalParams, originalResult, nullptr);
+    originalType = makeFunctionType(originalParams, originalResult,
+                                    transposeFnType->isThrowing(), transposeFnType->getThrownError(),
+                                    nullptr);
     originalType =
         makeFunctionType(AnyFunctionType::Param(selfType), originalType,
+                         false, Type(),
```
Comment (kovdan01) [inline lib/Sema/TypeCheckAttr.cpp]: Nit
```suggestion
                         /*throws=*/false, Type(),
```

File: lib/Sema/TypeCheckAttr.cpp [hunk 10]
```diff
@@ -6271,15 +6277,19 @@ getTransposeOriginalFunctionType(AnyFunctionType *transposeFnType,
   // `(Self) -> (<original parameters>) -> <original result>`.
   if (isCurried) {
     assert(selfType && "`Self` type should be resolved");
-    originalType = makeFunctionType(originalParams, originalResult, nullptr);
+    originalType = makeFunctionType(originalParams, originalResult,
+                                    transposeFnType->isThrowing(), transposeFnType->getThrownError(),
+                                    nullptr);
```
Comment (kovdan01) [inline lib/Sema/TypeCheckAttr.cpp]: Nit
```suggestion
                                    /*genericSignature=*/nullptr);
```

File: lib/SILOptimizer/Differentiation/VJPCloner.cpp [hunk 11]
```diff
@@ -989,16 +989,272 @@ class VJPCloner::Implementation final
...
+    // this `apply`.
+    SmallVector<SILValue, 4> allResults;
+    SmallVector<unsigned, 8> activeParamIndices;
+    SmallVector<unsigned, 8> activeResultIndices;
+    collectMinimalIndicesForFunctionCall(tai, getConfig(), activityInfo,
+                                         allResults, activeParamIndices,
+                                         activeResultIndices);
+    assert(!activeParamIndices.empty() && "Parameter indices cannot be empty");
+    assert(!activeResultIndices.empty() && "Result indices cannot be empty");
+    LLVM_DEBUG(auto &s = getADDebugStream() << "Active indices: params=(";
```
Comment (kovdan01) [inline lib/SILOptimizer/Differentiation/VJPCloner.cpp]: It would be very nice to have tests against the logs (like in test/AutoDiff/SILOptimizer/pullback_generation_loop_adjoints.swift) so we can easier understand the logic by looking at these tests. While not strictly necessary, this would be a giant help for anyone who needs to touch this some time later.

I understand that this is a pretty time-consuming and monotonous task, and I would by happy to help with that if you wish.

File: include/swift/SILOptimizer/Differentiation/Common.h [hunk 12]
```diff
@@ -277,6 +277,12 @@ inline void createEntryArguments(SILFunction *f) {
       indResTy = indResTy.mapTypeOutOfContext();
     createFunctionArgument(f->mapTypeIntoContext(indResTy).getAddressType());
   }
+  if (auto indErrorResTy = conv.getIndirectErrorResultType(f->getTypeExpansionContext())) {
```
Comment (kovdan01) [inline include/swift/SILOptimizer/Differentiation/Common.h]: Could you please clarify why this is needed? Tests continue passing even if I delete this piece of code.

If this is really needed, it's worth adding a test case covering that.

File: test/AutoDiff/validation-test/throw.swift [hunk 13]
```diff
@@ -0,0 +1,83 @@
...
+}
+
+ThrowingTests.testWithLeakChecking("SimpleTry") {
+  @differentiable(reverse)
+  func f(x: Double) throws -> Double {
+    if x < 0 {
+        throw E.error
+    }
+    else {
```
Comment (kovdan01) [inline test/AutoDiff/validation-test/throw.swift]: Nit: probably, `} else {` is more preferable than `}` on one line and `else {` on the next one

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 14]
```diff
@@ -3125,6 +3255,36 @@ void PullbackCloner::Implementation::visitSILBasicBlock(SILBasicBlock *bb) {
         break;
       }
       }
+    } else if (auto *tai = dyn_cast<TryApplyInst>(bbArg->getSingleTerminator())) {
+      // try_apply does not provide result, so there is no value to propagate
+      // adjoint to.  Prepare adjoint and associate it "on side", so it will be
+      // used as seed during pullback call emission
+      if (!getPullbackInfo().shouldDifferentiateApplySite(tai))
```
Comment (kovdan01) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp]: It looks like that existing tests do not cover this condition and it always evaluates to false - inserting `assert(getPullbackInfo().shouldDifferentiateApplySite(tai);` does not break any tests.

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 15]
```diff
@@ -3125,6 +3255,36 @@ void PullbackCloner::Implementation::visitSILBasicBlock(SILBasicBlock *bb) {
...
+        auto concreteBBArgAdj = materializeAdjointDirect(bbArgAdj, pbLoc);
+        auto concreteBBArgAdjCopy =
+          builder.emitCopyValueOperation(pbLoc, concreteBBArgAdj);
+
+        blockTemporaries[getPullbackBlock(predBB).first].insert(concreteBBArgAdjCopy);
+        auto [_, inserted] = tryApplyAdjoints.try_emplace(tai, concreteBBArgAdjCopy);
+        assert(inserted && "should have unique adjoint for try_apply");
+        break;
+      }
+      case SILValueCategory::Address: {
```
Comment (kovdan01) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp]: With existing tests, we never fall into this case. It's probably worth covering it with tests.

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 16]
```diff
@@ -989,26 +1000,136 @@ class PullbackCloner::Implementation final
...
+                                   optPullback->getOwnershipKind());
+
+    SmallVector<SILValue, 2> adjArgs;
+    FullApplySite fai(tai);
+    auto *originalBB = tai->getParent();
     auto &applyInfo = applyInfoLookup->getSecond();
+    for (unsigned i : applyInfo.config.parameterIndices->getIndices()) {
+      unsigned argIdx = fai.getNumIndirectSILResults() + fai.getNumIndirectSILErrorResults() + i;
+      auto origArg = fai.getArgument(argIdx);
+        auto paramInfo = fai.getSubstCalleeConv().getParamInfoForSILArg(argIdx);
```
Comment (kovdan01) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp]: Nit: wrong indentation here and below. Maybe it's worth just running `git clang-format` on the changes.

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 17]
```diff
@@ -989,26 +1000,136 @@ class PullbackCloner::Implementation final
...
+        if (paramInfo.isAutoDiffSemanticResult())
```
Comment (kovdan01) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp]: This condition is not covered by existing tests - `paramInfo.isAutoDiffSemanticResult()` always evaluates to false. It's probably worth implementing a test covering that.

File: include/swift/SILOptimizer/Differentiation/Common.h (hunk 12 above)
Comment (asl) [reply include/swift/SILOptimizer/Differentiation/Common.h]: This is a bit non-trivial to trigger w/o support for differential operators and / or custom derivatives for throwing functions...

File: lib/AST/Builtins.cpp (hunk 5 above)
Comment (asl) [reply lib/AST/Builtins.cpp]: No, as I mentioned, the differential operators were removed from this PR as this is a stdlib change and I did not want to include it here. It is just a note for future work, see the `/*thrownType=*/Type()` below. But currently we just emit non-differentiable diagnostics and that's it.

File: lib/SILGen/SILGenBuiltin.cpp (hunk 8 above)
Comment (asl) [reply lib/SILGen/SILGenBuiltin.cpp]: I believe it was also used somewhere else... (the outparameter).

Comment (asl) [reply lib/SILGen/SILGenBuiltin.cpp]: It is used in `AST/Builtins.cpp`, so it is not quite possible to get rid of this.

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp (hunk 7 above)
Comment (asl) [reply lib/SILOptimizer/Differentiation/PullbackCloner.cpp]: Not quite. There are small differences here and there because we need to support multiple kinds of apply instructions

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp (hunk 15 above)
Comment (asl) [reply lib/SILOptimizer/Differentiation/PullbackCloner.cpp]: Yes, it seems we'd need something like object value with non-loadable tangent.

**Comment by asl** [comment]
@swift-ci please test

**Comment by asl** [comment]
@swift-ci please test

File: lib/AST/Builtins.cpp [hunk 18]
```diff
@@ -2912,6 +2912,7 @@ ValueDecl *swift::getBuiltinValueDecl(ASTContext &Context, Identifier Id) {
...
```
Comment (kovdan01) [inline lib/AST/Builtins.cpp:2923]: It's probably worth opening an issue and linking it here

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 19]
```diff
@@ -991,26 +1002,136 @@ class PullbackCloner::Implementation final
...
+    assert(getPullbackInfo().shouldDifferentiateApplySite(tai));
 
     // Replace a call to a function with a call to its pullback.
     auto &nestedApplyInfo = getContext().getNestedApplyInfo();
-    auto applyInfoLookup = nestedApplyInfo.find(fai);
+    auto applyInfoLookup = nestedApplyInfo.find(tai);
     // If no `NestedApplyInfo` was found, then this task doesn't need to be
     // differentiated.
     if (applyInfoLookup == nestedApplyInfo.end()) {
+      auto *normalBlock = tai->getNormalBB();
```
Comment (kovdan01) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp]: Nit
```suggestion
      const auto *normalBlock = tai->getNormalBB();
```

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 20]
```diff
@@ -991,26 +1002,136 @@ class PullbackCloner::Implementation final
...
+    auto *pbBB = builder.getInsertionBB();
+    auto *normalPbBB = pbBB->split(builder.getInsertionPoint());
+    auto *errorPbBB = getPullback().createBasicBlockAfter(normalPbBB);
+    auto *afterTryApplyPbBB = getPullback().createBasicBlockAfter(errorPbBB);
+
+    // Note that we cannot simply assign map value as DenseMap entry references
+    // could be invalidated on insertion, so map[a] = map[b] may trigger
+    // use-after-free
+    auto currentBT = blockTemporaries[pbBB];
+    blockTemporaries.insert({afterTryApplyPbBB, currentBT});
```
Comment (kovdan01) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp]: Nit: probably worth constructing in-place. Also, we might want to transfer ownership using `std::move` instead of doing copies. It would probably not be that beneficial in most cases because moving `llvm::SmallSetVector<SILValue, 32>` seems to be just a copy when we have less than 32 elements. But in rare cases we might see the difference.
```C++
    auto currentBT = std::move(blockTemporaries[pbBB]);
    blockTemporaries.try_emplace(afterTryApplyPbBB, std::move(currentBT));
    blockTemporaries[pbBB] = {};
```

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 21]
```diff
@@ -991,26 +1002,136 @@ class PullbackCloner::Implementation final
...
+      builder.createSwitchOptional(loc, optPullback,
+                                   normalPbBB, errorPbBB,
+                                   optPullback->getOwnershipKind());
+
+    SmallVector<SILValue, 2> adjArgs;
+    FullApplySite fai(tai);
+    auto *originalBB = tai->getParent();
     auto &applyInfo = applyInfoLookup->getSecond();
+    for (unsigned i : applyInfo.config.parameterIndices->getIndices()) {
+      unsigned argIdx = fai.getNumIndirectSILResults() + fai.getNumIndirectSILErrorResults() + i;
```
Comment (kovdan01) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp]: Nit: could you please run `git clang-format` to wrap such long lines at 80 characters?

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 22]
```diff
@@ -991,26 +1002,136 @@ class PullbackCloner::Implementation final
...
+      auto origArg = fai.getArgument(argIdx);
+      auto paramInfo = fai.getSubstCalleeConv().getParamInfoForSILArg(argIdx);
+      if (paramInfo.isAutoDiffSemanticResult())
+        continue;
+      if (getTangentValueCategory(origArg) != SILValueCategory::Object)
```
Comment (kovdan01) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp:1097]: Nit: it's probably worth adding a comment explaining why we need such a check. This part of logic is not very obvious IMHO

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 23]
```diff
@@ -991,26 +1002,136 @@ class PullbackCloner::Implementation final
...
+        auto argAdj = getAdjointValue(originalBB, arg);
+        outAdjArgs.push_back(materializeAdjointDirect(argAdj, loc));
+      }
+
+      cleanUpTemporariesForBlock(normalPbBB, loc);
+      builder.createBranch(loc, afterTryApplyPbBB, outAdjArgs);
+    }
+
+    builder.setInsertionPoint(afterTryApplyPbBB);
+    for (auto argAndIdx : llvm::enumerate(adjArgs)) {
```
Comment (kovdan01) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp]: Nit: probably worth using structured bindings and replacing `.value()` and `.index()` below with corresponding variables
```suggestion
    for (auto [index, arg] : llvm::enumerate(adjArgs)) {
```

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 24]
```diff
@@ -2280,7 +2407,7 @@ bool PullbackCloner::Implementation::run() {
 
   for (auto *origBB : originalBlocks) {
     auto *pullbackBB = pullback.createBasicBlock();
-    pullbackBBMap.insert({origBB, pullbackBB});
+    pullbackBBMap.insert({origBB, { pullbackBB, pullbackBB } });
```
Comment (kovdan01) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp]: Nit: probably worth constructing in-place
```suggestion
    pullbackBBMap.try_emplace(origBB, std::pair{ pullbackBB, pullbackBB });
```

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 25]
```diff
@@ -808,7 +815,8 @@ class PullbackCloner::Implementation final
   // CFG mapping
   //--------------------------------------------------------------------------//
 
-  SILBasicBlock *getPullbackBlock(SILBasicBlock *originalBlock) {
+  std::pair<SILBasicBlock *, SILBasicBlock *>
+  getPullbackBlock(const SILBasicBlock *originalBlock) {
```
Comment (kovdan01) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp]: Nit: maybe we should think of renaming the function to smth like `getPullbackBlocksRegion`.

File: lib/SILOptimizer/Differentiation/VJPCloner.cpp [hunk 26]
```diff
@@ -1009,16 +1009,269 @@ class VJPCloner::Implementation final
 
   void visitTryApplyInst(TryApplyInst *tai) {
```
Comment (kovdan01) [inline lib/SILOptimizer/Differentiation/VJPCloner.cpp:1010]: Completely optional, but it would be very nice if you could split the logic in this function into several helpers. Right now the function is quite big and it's a bit painful to dive into this w/o having full understanding of the context. You already have different pieces of logic wrapped into scopes `{/*...*/}`, so putting them into named helpers does not look too challenging. I'm sure we'll thank ourselves in future when we need to modify this :)

Feel free to ignore.

File: test/AutoDiff/SILOptimizer/optional_error.swift
Comment (kovdan01) [inline test/AutoDiff/SILOptimizer/optional_error.swift:1]: Do we want to also add tests which check actual generated SIL and not only valid executable behavior/compiler diagnostics? Of course, we do not need to match exact SIL, but it might be worth checking at least some key points.

**Review by kovdan01 — APPROVED** [review]
LGTM, thanks! Functionally this is totally OK, but please consider addressing minor suggestions I've left in comments before merging this. Feel free to ignore though.

File: lib/AST/Builtins.cpp (hunk 18 above)
Comment (asl) [reply lib/AST/Builtins.cpp:2923]: https://github.com/swiftlang/swift/issues/85343

File: lib/SILOptimizer/Differentiation/VJPCloner.cpp (hunk 26 above)
Comment (asl) [reply lib/SILOptimizer/Differentiation/VJPCloner.cpp:1010]: Believe me or not, I tried to to do this multiple times :) The reality is that they are like 50% of same and 50% of different (between `apply` and `tryApply` lowering) and these differences are intermixed. There are also lots of values here and there so factoring out looked very artificial.

**Comment by asl** [comment]
@swift-ci please test

**Comment by kovdan01** [comment]
@swift-ci please test Windows platform

**Review by kovdan01 — APPROVED** [review]

**Comment by asl** [comment]
@swift-ci please test Windows platform
