### PR TITLE
[Sema]: Fix data race safety hole with mutable statics within actors

### LINKED ISSUE #78435: Improve Diagnostics for Concurrent Access of Static Properties in Actors
### Motivation

Currently, when a static property is declared in an actor and accessed concurrently from multiple tasks, the Swift compiler does not provide any warnings or errors about potential race conditions. This lack of diagnostics can lead to subtle and hard-to-diagnose bugs, especially for developers who assume that all properties within an actor are isolated, including static ones.

In contrast, when a class is used instead of an actor, the compiler correctly identifies and prevents race conditions caused by concurrent access. This inconsistent behaviour between actors and classes can create confusion and lead to incorrect assumptions about the safety of static properties in actors.

### Proposed solution

Introduce compiler diagnostics for concurrent access to static properties in actors. Specifically:
1.	Warn developers when a static property in an actor is accessed in a concurrent context.
2.	Provide clear messaging that static properties are not actor-isolated and must be explicitly synchronised if accessed concurrently.
3.	Optionally, recommend alternative approaches.

```swift
actor MyActor {
    static var value = 0
}

nonisolated func a() async {
    await withTaskGroup(of: Void.self) { taskGroup in
        for _ in 0..<1000 {
            taskGroup.addTask {
                MyActor.value += 1 // This should trigger a compiler warning about potential race conditions.
            }
        }
    }
    print(MyActor.value)
}
```

Expected Diagnostic:
_Concurrent access to static property 'value' in actor 'MyActor' is not safe and may result in a race condition._

### Alternatives considered

1.	Status Quo: Continue without compiler diagnostics. This approach leaves developers vulnerable to race conditions when using static properties in actors without realising the lack of isolation.
2.	Documentation Update: Update the Swift documentation to clarify that static properties in actors are not isolated. While this would improve awareness, it relies on developers reading the documentation and may not be as effective as compiler diagnostics.
3.	Enhanced Actor Model: Extend the actor isolation model to include static properties. However, this would likely introduce significant complexity and break existing code, making it a less feasible option.

### Additional information

This feature would align with Swift’s focus on safety and concurrency. By making such race conditions explicit at compile time, it would prevent subtle bugs and reduce confusion for developers adopting the actor model.

This issue was discovered by the developers in this thread: https://forums.swift.org/t/why-does-the-compiler-allow-static-properties-in-actors-without-await/76973

### PR DESCRIPTION
**Pull request by jamieQ**
### Issue

the existing logic in `checkGlobalIsolation` ignored global variables nested within actor types when diagnosing global isolation during typechecking. this left open a data race safety hole, as described [here](https://forums.swift.org/t/why-does-the-compiler-allow-static-properties-in-actors-without-await/76973).

### Description

- removes the actor bypass logic from `checkGlobalIsolation`
- updates the existing tests
- reformat & add commentary to the `checkGlobalIsolation` implementation (separate commit)

i'd recommend using the 'hide whitespace' option if reviewing the full diff via GitHub as it makes it somewhat easier to parse.

resolves https://github.com/swiftlang/swift/issues/78435

### CODE REVIEW

File: lib/Sema/TypeCheckConcurrency.cpp [hunk 1]
```diff
@@ -6120,59 +6120,66 @@ void swift::checkOverrideActorIsolation(ValueDecl *value) {
...
-      !isolation.isGlobalActor() &&
-      (isolation != ActorIsolation::NonisolatedUnsafe)) {
-    auto *classDecl = var->getDeclContext()->getSelfClassDecl();
-    const bool isActorType = classDecl && classDecl->isAnyActor();
-    if (var->isGlobalStorage() && !isActorType) {
-      auto *diagVar = var;
-      if (auto *originalVar = var->getOriginalWrappedProperty()) {
-        diagVar = originalVar;
-      }
+  if (isolation.isGlobalActor() || isolation.isNonisolatedUnsafe())
```
Comment (jamieQ) [inline lib/Sema/TypeCheckConcurrency.cpp:6130]: minor change here to use the `isNonisolatedUnsafe()` accessor vs what was previously being done.

tangent: if someone cares to enlighten me as to whether these two formulations are actually the same i'd be curious to learn more about exactly why/how that is. the first case seems like a class is being compared to a 'Kind' which i don't entirely understand.

File: test/Concurrency/global_variables.swift [hunk 2]
```diff
@@ -8,7 +8,7 @@
 
 @globalActor
 actor TestGlobalActor {
-  static var shared = TestGlobalActor()
```
Comment (jamieQ) [inline test/Concurrency/global_variables.swift:11]: this code is now diagnosed as invalid since `shared` is global, mutable, non-isolated state. presumably this means this change could be a source-break – what is the stance on that when it comes to addressing bugs?

File: lib/Sema/TypeCheckConcurrency.cpp [hunk 3]
```diff
@@ -6120,59 +6120,66 @@ void swift::checkOverrideActorIsolation(ValueDecl *value) {
...
+
+  // Skip if the decl is global actor-isolated or is unsafely opted-out.
   const auto isolation = getActorIsolation(var);
-  if (var->getLoc() &&
-      var->getASTContext().LangOpts.hasFeature(Feature::GlobalConcurrency) &&
-      !isolation.isGlobalActor() &&
-      (isolation != ActorIsolation::NonisolatedUnsafe)) {
-    auto *classDecl = var->getDeclContext()->getSelfClassDecl();
-    const bool isActorType = classDecl && classDecl->isAnyActor();
-    if (var->isGlobalStorage() && !isActorType) {
```
[the remark this answers is not in the document]
Comment (hborla) [reply lib/Sema/TypeCheckConcurrency.cpp:6130]: I agree that there is no reason to check whether the enclosing type is an actor type in this code. If a variable is static, it doesn't matter whether or not it's inside an actor - as you've noted, actor instance isolation can't apply here.

File: lib/Sema/TypeCheckConcurrency.cpp (hunk 1 above)
Comment (hborla) [reply lib/Sema/TypeCheckConcurrency.cpp:6130]: I believe the reason the comparison between `ActorIsolation` and `ActorIsolation::Kind` works is because there's an operator `()` on `ActorIsolation` that returns its kind:

```cpp
operator Kind() const { return getKind(); }
```

I believe operator `()` was implicitly called on `ActorIsolation` when used as an operand to `==` or `!=`, so it was really just a comparison between two `ActorIsolation::Kind`s.

**Review by hborla — APPROVED** [review]
Thank you!

File: test/Concurrency/global_variables.swift (hunk 2 above)
Comment (hborla) [reply test/Concurrency/global_variables.swift:11]: It's okay to fix this as an error in Swift 6 mode - we can adjust if we find this causes wide spread source incompatibility amongst Swift 6 mode adopters through testing. These diagnostics are already warnings in strict concurrency checking / using the `GlobalConcurrency` upcoming feature prior to migrating to the Swift 6 language mode.

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by jamieQ** [comment]
hmm... seems my refactoring of some of the early exit conditions to occur before the `getActorIsolation()` call may have broken one of the other Concurrency tests (sorry, i thought i ran this stuff locally against that test dir and things passed, but maybe i missed something). i will try to address by preserving the prior execution order.

**Comment by jamieQ** [comment]
@hborla i pushed a fix (and rebased) for the failed CI test. would you mind kicking off another build when you have a moment please?

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
> hmm... seems my refactoring of some of the early exit conditions to occur before the getActorIsolation() call may have broken one of the other Concurrency tests

Huh, I'd love to investigate this to figure out why (separately from your fix here). I thought your refactoring to add the early exits was much easier to follow!

**Comment by jamieQ** [comment]
> Huh, I'd love to investigate this to figure out why (separately from your fix here). I thought your refactoring to add the early exits was much easier to follow!

i'll leave some notes based on the brief time i spent looking into it today. the refactoring commit that adjusted the early exit conditions caused the `global_actor_inference.swift` [test](https://github.com/swiftlang/swift/blob/34cc3e88b3d753465725c634e28aaa3a311fc92e/test/Concurrency/global_actor_inference.swift#L507) to fail with this error:

```
/swift-project/swift/test/Concurrency/global_actor_inference.swift:502:42: error: unexpected note produced: property declared here
  @SimplePropertyWrapper nonisolated var value 
                                         ^
/swift-project/swift/test/Concurrency/global_actor_inference.swift:507:9: error: unexpected error produced: main actor-isolated property 'value' can not be referenced from a nonisolated context
    _ = value
        ^
```

this seemed to be due to my original change which moved the call to compute actor isolation to only conditionally occur if there was a valid source loc & the global concurrency feature was enabled (it originally occurred unconditionally like [this](https://github.com/swiftlang/swift/blob/788d0f9f647ba29a5d68ace2cb4a06062ecf77f5/lib/Sema/TypeCheckConcurrency.cpp#L6199-L6204)). it seems there may be something load-bearing about the downstream `ActorIsolationRequest` that occurs from the `getActorIsolation()` here?

**Comment by jamieQ** [comment]
CI failures seemed unrelated to this change and might be resolved now that this merged? https://github.com/swiftlang/swift/pull/79415

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
https://github.com/swiftlang/sourcekit-lsp/pull/1985

@swift-ci please smoke test

**Comment by hborla** [comment]
@swift-ci please test source compatibility

**Comment by hborla** [comment]
@swift-ci please smoke test Linux

**Comment by hborla** [comment]
@swift-ci please smoke test Linux

**Comment by hborla** [comment]
@jamieQ Thank you for the contribution! Please feel free to ping me if you decide to pick up more in the concurrency area and have questions or need guidance 😄

**Comment by jamieQ** [comment]
@hborla thank you for helping get this through CI – much appreciated!
