### PR TITLE
[Concurrency] A few fixes for default isolation inference

### LINKED ISSUE #85564: .swiftinterface emits invalid @preconcurrency isolated deinit
### Description

If a view inherits from `UIView` and doesn't explicitly add `@MainActor` attribute while using `isolated deinit`, the generated `swiftinterface` file will contain invalid syntax of `@preconcurrency isolated deinit` that prevents use of the framework.

Image

### Reproduction

Create a framework with a simple view:

```swift
import UIKit

public class MyView: UIView {
    isolated deinit {
        print("test")
    }
}
```

Finally, try building the framework and using it in an application. The workaround is to annotate `MyView` with MainActor - then the `@preconcurrency` annotation disappears.

### Expected behavior

Invalid symbol shouldn't be emitted.

### Environment

6.2

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by xedin**
- Check whether `@preconcurrency` is supported before adding it

  Don't trasfer "preconcurrency" from isolation onto a declaration if
  the declaration doesn't support it. This is especially important for
  `MainActor` by default mode where each `@MainActor` injection site
  gets marked as `@preconcurrency` implicitly in pre-6 language modes.

- Add isolation attributes to declarations inferred as `@MainActor`

  When declaration gets inferred as `@MainActor` that needs to be
  reflected in its attributes as well because that's the only reliable
  way propagate isolation across modules.

Resolves: rdar://164077275
Resolves: https://github.com/swiftlang/swift/issues/85564

### CODE REVIEW

File: test/Concurrency/default_isolation_MainActor_cross_module.swift [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+// RUN: rm %t/A.swiftmodule
+
+// Re-build the client using interface
+// RUN: %target-swift-frontend -typecheck -verify -verify-ignore-unrelated -I %t -primary-file %t/src/Client.swift
+
+// REQUIRES: concurrency
+
+//--- A.swift
+
+// CHECK: @_Concurrency.MainActor @preconcurrency public protocol P
```
Comment (xedin) [inline test/Concurrency/default_isolation_MainActor_cross_module.swift:26]: @xymus I also noticed that we don't propagate `-default-isolation` to the swift interface flags. 

The interface file for `A.swift` ends up with the following flags:

```
// swift-module-flags: -target arm64-apple-macosx13.0 -swift-version 4 -module-name A -swift-version 5 -enable-library-evolution
// swift-module-flags-ignorable:  -formal-cxx-interoperability-mode=off -interface-compiler-version 6.3
```

Was this a deliberate choice? I think adding attributes is still the right way to go but wondering in general whether we are missing some concurrency flags in interfaces today...

**Comment by xedin** [comment]
@swift-ci please test

**Review by hborla — APPROVED** [review]

**Comment by drodriguez** [comment]
Should #86717 piece in the ASTPrinter be reverted now? /cc @sepy97

**Comment by xedin** [comment]
Yes, if this was done specifically for `@preconcurrency` on `isolated deinit` it should be reverted, this changes addresses the underlying problem.

**Comment by xedin** [comment]
I opened a PR to partially revert #86717 - https://github.com/swiftlang/swift/pull/87061
