### PR TITLE
[Concurrency] Fix too optimistic TaskGroup bail-out-when-empty, 

### LINKED ISSUE #63147: TaskGroups `waitForAll` changed behaviour in recent 5.8 toolchains
**Description**
With recent 5.8 toolchains `waitForAll` does not re throw the first observed error anymore it rather just silently returns.

**Steps to reproduce**
The following code behaves different in 5.7 and recent 5.8 snapshots

```swift
@main
struct Foo {
    static func main() async throws {
        do {
            try await withThrowingTaskGroup(of: Void.self) { group in
                group.addTask {
                    throw CancellationError()
                }

                group.addTask {}

                do {
                    try await group.waitForAll()
                } catch {
                    print("Got error", error)
                    throw error
                }
            }
        } catch {
            print(error)
        }
    }
}

// 5.7 prints
Got error CancellationError()
CancellationError()
Program ended with exit code: 0

// 5.8 Dev snapshot 2023-01-19 prints
Program ended with exit code: 0
```

**Expected behavior**
The behaviour shouldn't have changed.

**Environment**
- Swift compiler version: Dev snapshot 2023-01-19

rdar://104507347

### PR DESCRIPTION
**Pull request by ktoso**
discarding group may need to emit an error out of such waitAll attempt, if a previous error was already stored.

The exact dance is:
- we store an error from child task
- the pending task count is 0
- the code trying to waitAll would check status ONLY and bail out, noticing that pending count is zero -- returning the actual body value

Instead, it should:
- check again the readyQueue if we're in, if there was a stored value, because if so, it may be an RawError that the DiscardingTaskGroup should emit.

This also is now able to easily handle the "first error always wins" but we choose to implement the "error thrown by body wins" after discussions within the team.

Resolves rdar://104198700
Resolves https://github.com/apple/swift/issues/63147
Resolves rdar://104507347
Resolves rdar://104332560
Resolves rdar://104212282

### CODE REVIEW

**Comment by ktoso** [comment]
This resolves a flaky test (and an actual bug) that @shahmishal and @beccadax reported today.
Thank you for the ping, was a real omission in the code.

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
I'll have another look and add more tests about the retain/release correctness of the errors... I have a suspicion it might be wrong and over-retain the error a bit... 🤔

**Comment by ktoso** [comment]
Had another bug hiding, we must offerError WHILE holding the group locks ofc, otherwise we get interleaving between the offer and completions of other tasks and may end up returning a success while we intended to throw the body error.

Fix: https://github.com/apple/swift/pull/63016/commits/95628b1094eca626300a10b364963dd7f39968e7

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
@swift-ci please smoke test linux

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
@swift-ci please smoke test

File: stdlib/public/Concurrency/TaskGroup.cpp [hunk 1]
```diff
@@ -1641,8 +1652,9 @@ static void swift_taskGroup_waitAllImpl(
     ThrowingTaskFutureWaitContinuationFunction *resumeFunction,
     AsyncContext *rawContext) {
   auto waitingTask = swift_task_getCurrent();
-  waitingTask->ResumeTask = task_group_wait_resume_adapter;
-  waitingTask->ResumeContext = rawContext;
```
Comment (ktoso) [inline stdlib/public/Concurrency/TaskGroup.cpp:1645]: this was incorrect, we cannot do this without holding the lock, as otherwise an `offer` may pull the waiting task off the queue; but only one of the paths shall update and run the task.

File: stdlib/public/Concurrency/TaskGroup.cpp [hunk 2]
```diff
@@ -1739,21 +1739,52 @@ PollResult TaskGroupBase::tryEnqueueWaitingTask(AsyncTask *waitingTask) {
   bool haveRunOneChildTaskInline = false;
 
   reevaluate_if_TaskGroup_has_results:;
-  auto assumed = statusMarkWaitingAssumeAcquire();
```
Comment (ktoso) [inline stdlib/public/Concurrency/TaskGroup.cpp:1742]: The change here is that we don't mark and undo, but only mark when we indeed decide that we'll be waiting.

This is all still done with a lock, but the dance is more correct anyway.

File: test/Concurrency/Runtime/async_taskgroup_discarding.swift [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+  let l = "\(lhs)"
+  let r = "\(rhs)"
+  precondition(l.prefix("\(r)".count) == r, "'\(l)' did not start with '\(r)'")
+}
+
+// NOTE: Not as StdlibUnittest/TestSuite since these types of tests are unreasonably slow to load/debug.
+
+@main struct Main {
+  static func main() async {
+    for i in 0...1_000 {
```
Comment (ktoso) [inline test/Concurrency/Runtime/async_taskgroup_discarding.swift:44]: this is quick enough tbh, let's leave it like this

**Comment by ktoso** [comment]
@swift-ci please smoke test and merge

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
All passed but I want to make double-sure here, run again.

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
@swift-ci please smoke test
@swift-ci please smoke test

**Comment by ktoso** [comment]
@swift-ci please smoke test linux

**Comment by ktoso** [comment]
Heh, only remaining thing is a `pure virtual method called` happening only on linux that I can't explain :-( Getting a linux box to dig deeper.

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
Managed to reproduce with debug output:

```
[0x7f032a0a9640] [/home/ktoso/swift-project/swift/stdlib/public/Concurrency/TaskGroup.cpp:847][group(0x559fad1a15f0)] (swift_taskGroup_initializeWithFlagsImpl) create group; flags: isDiscardingResults=1
[0x7f032a0a9640] [/home/ktoso/swift-project/swift/stdlib/public/Concurrency/TaskGroup.cpp:631][group(0x559fad1a15f0,discardResults)] (statusAddPendingTaskRelaxed) addPending, after = TaskGroupStatus{ C:n W:n P:1 0000000000000000000000000000000000000000000000000000000000000001 }
[0x7f032a0a9640] [/home/ktoso/swift-project/swift/stdlib/public/Concurrency/TaskGroup.cpp:631][group(0x559fad1a15f0,discardResults)] (statusAddPendingTaskRelaxed) addPending, after = TaskGroupStatus{ C:n W:n P:2 0000000000000000000000000000000000000000000000000000000000000010 }
[0x7f032a0a9640] [/home/ktoso/swift-project/swift/stdlib/public/Concurrency/TaskGroup.cpp:1728][group(0x559fad1a15f0,discardResults)] (waitAll) waitAll, bodyError = (nil), status = TaskGroupStatus{ C:n W:n P:2 0000000000000000000000000000000000000000000000000000000000000010 }
[0x7f032a0a9640] [/home/ktoso/swift-project/swift/stdlib/public/Concurrency/TaskGroup.cpp:1743][group(0x559fad1a15f0,discardResults)] (waitAll) waitAll, status = TaskGroupStatus{ C:n W:n P:2 0000000000000000000000000000000000000000000000000000000000000010 }
[0x7f032a0a9640] [/home/ktoso/swift-project/swift/stdlib/public/Concurrency/TaskGroup.cpp:1792][group(0x559fad1a15f0,discardResults)] (waitAll) WATCH OUT, set waiter onto... waitQueue.head = (nil)
[0x7f032a0a9640] [/home/ktoso/swift-project/swift/stdlib/public/Concurrency/TaskGroup.cpp:1799][group(0x559fad1a15f0,discardResults)] (waitAll) waitAll, marked waiting status = TaskGroupStatus{ C:n W:y P:2 0100000000000000000000000000000000000000000000000000000000000010 }
[0x7f032b8ac640] [/home/ktoso/swift-project/swift/stdlib/public/Concurrency/TaskGroup.cpp:1159][group(0x559fad1a15f0,discardResults)] (offer) offer, completedTask:0x7f031c00ed00, error:0, status:TaskGroupStatus{ C:n W:y P:2 0100000000000000000000000000000000000000000000000000000000000010 }
[0x7f032b8ac640] [/home/ktoso/swift-project/swift/stdlib/public/Concurrency/TaskGroup.cpp:1167][group(0x559fad1a15f0,discardResults)] (offer) offer, complete, status afterComplete:TaskGroupStatus{ C:n W:y P:1 0100000000000000000000000000000000000000000000000000000000000001 }
[0x7f032a8aa640] [/home/ktoso/swift-project/swift/stdlib/public/Concurrency/TaskGroup.cpp:1159][group(0x559fad1a15f0,discardResults)] (offer) offer, completedTask:0x7f031c00e820, error:1, status:TaskGroupStatus{ C:n W:y P:1 0100000000000000000000000000000000000000000000000000000000000001 }
[0x7f032a8aa640] [/home/ktoso/swift-project/swift/stdlib/public/Concurrency/TaskGroup.cpp:1167][group(0x559fad1a15f0,discardResults)] (offer) offer, complete, status afterComplete:TaskGroupStatus{ C:n W:y P:0 0100000000000000000000000000000000000000000000000000000000000000 }
[0x7f032a8aa640] [/home/ktoso/swift-project/swift/stdlib/public/Concurrency/TaskGroup.cpp:1256][group(0x559fad1a15f0,discardResults)] (resumeWaitingTask) resume waiting task = 0x559fad1a1290, alreadyDecremented:1, error:1, complete with = 0x7f031c00e820
[0x7f032a8aa640] [/home/ktoso/swift-project/swift/stdlib/public/Concurrency/TaskGroup.cpp:1259][group(0x559fad1a15f0,discardResults)] (resumeWaitingTask) resumeWaitingTask, attempt CAS, waiting task = 0x559fad1a1290, waitQueue.head = 0x559fad1a1290, error:1, complete with = 0x7f031c00e820
[0x7f032a8aa640] [/home/ktoso/swift-project/swift/stdlib/public/Concurrency/TaskGroup.cpp:1296][group(0x559fad1a15f0,discardResults)] (resumeWaitingTask) resume waiting DONE, task = 0x559fad1a1290, backup = 0x559fad1a1290, complete with = 0x7f031c00e820, status = TaskGroupStatus{ C:y W:y P:0 1100000000000000000000000000000000000000000000000000000000000000 }
main/async_taskgroup_discarding.swift:56: Fatal error: (iteration:33) expected error to be re-thrown, got: 12
Current stack trace:
0    libswiftCore.so                    0x00007f032c5df890 _swift_stdlib_reportFatalErrorInFile + 112
1    libswiftCore.so                    0x00007f032c1d3892 <unavailable> + 1517714
2    libswiftCore.so                    0x00007f032c1d36e6 <unavailable> + 1517286
```

I can't understand how that's possible; we never hit any "store the result" codepath in the first offer, so how does the 12 end up in the result...

**Comment by ktoso** [comment]
preset=asan
@swift-ci Please test with preset macOS

**Comment by ktoso** [comment]
preset=asan
@swift-ci Please smoke test linux

**Comment by ktoso** [comment]
@swift-ci Please smoke macOS

**Comment by ktoso** [comment]
@swift-ci Please smoke test macOS

**Comment by ktoso** [comment]
Seems linux is passing with the latest rework of waitAll body -- avoiding a race on `context` mutation. Let's give it another spin though.

**Comment by ktoso** [comment]
@swift-ci Please smoke test linux

**Comment by ktoso** [comment]
@swift-ci Please smoke test linux

**Comment by ktoso** [comment]
@swift-ci Please smoke test

**Comment by ktoso** [comment]
Unlocking one more test

@swift-ci Please smoke test

**Comment by ktoso** [comment]
Also picked over the overflow protection we did way back then in https://github.com/apple/swift/pull/62271

I believe we're finally golden here, let's give it another test run and I'll pick forward.

**Comment by ktoso** [comment]
@swift-ci Please smoke test windows

**Comment by ktoso** [comment]
@swift-ci Please smoke test

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
ARM_ARCH_7K compilation fun, fixed now.

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please smoke test windows
