### PR TITLE
TypeCheckType: Fix some bugs in the `any` syntax checker

### LINKED ISSUE #65026: The suggested fix for the existential types with implicit unwrapping is incorrect when enable upcoming feature`ExistentialAny`
**Description**
In Swift 5.8, [SE-0335 "Introduce existential any"](https://github.com/apple/swift-evolution/blob/main/proposals/0335-existential-any.md) can be enabled by [SE-0362 "Piecemeal adoption of upcoming language improvements"](https://github.com/apple/swift-evolution/blob/main/proposals/0362-piecemeal-future-features.md). In that case, if the existential type is not given the `any` keyword, it causes a build error.

That build error contains a suggested fix, but it suggests a fix that seems incorrect when using implicitly unwrapped optionals.

**Steps to reproduce**
1. Create a Swift Package and open it Xcode 14.3.
```bash
% mkdir ExistentialAnySample

% cd ExistentialAnySample

% swift package init --type executable
Creating executable package: ExistentialAnySample
Creating Package.swift
Creating .gitignore
Creating Sources/
Creating Sources/main.swift

% xed .
```

2. Enable upcoming feature `ExistentialAny`.
```swift:Package.swift
// swift-tools-version: 5.8

import PackageDescription

let package = Package(
    name: "ExistentialAnySample",
    targets: [
        .executableTarget(
            name: "ExistentialAnySample",
            path: "Sources",
            swiftSettings: [
                .enableUpcomingFeature("ExistentialAny"),
            ]),
    ]
)
```

3. Write the following code in `main.swift` and build it (we will get an error).
```swift:main.swift
//
//  main.swift
//  ExistentialAnySample
//
//  Created by treastrain on 2023/04/08.
//

protocol SampleProtocol {}

let _: SampleProtocol! // ❌ Use of protocol 'SampleProtocol' as a type must be written 'any SampleProtocol'
```

4. Click "Fix" to accept the suggestion.

5. The error continues and the build fails.

**Expected behavior**
After clicking "Fix", `any SampleProtocol!` should be replaced with `(any SampleProtocol)!`.

**Environment**
- Swift compiler version info `swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100) Target: arm64-apple-macosx13.0`
- Xcode version info `Xcode 14.3 Build version 14E222b`
- Deployment target: iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4

### LINKED ISSUE #65027: The suggested fix for the protocol composition type is incorrect when enable upcoming feature`ExistentialAny`
**Description**
In Swift 5.8, [SE-0335 "Introduce existential any"](https://github.com/apple/swift-evolution/blob/main/proposals/0335-existential-any.md) can be enabled by [SE-0362 "Piecemeal adoption of upcoming language improvements"](https://github.com/apple/swift-evolution/blob/main/proposals/0362-piecemeal-future-features.md). In that case, if the existential type is not given the `any` keyword, it causes a build error.

That build error contains a suggested fix, but it suggests a fix that seems incorrect when using protocol composition types.

**Steps to reproduce**
1. Create a Swift Package and open it Xcode 14.3.
```bash
% mkdir ExistentialAnySample

% cd ExistentialAnySample

% swift package init --type executable
Creating executable package: ExistentialAnySample
Creating Package.swift
Creating .gitignore
Creating Sources/
Creating Sources/main.swift

% xed .
```

2. Enable upcoming feature `ExistentialAny`.
```swift:Package.swift
// swift-tools-version: 5.8

import PackageDescription

let package = Package(
    name: "ExistentialAnySample",
    targets: [
        .executableTarget(
            name: "ExistentialAnySample",
            path: "Sources",
            swiftSettings: [
                .enableUpcomingFeature("ExistentialAny"),
            ]),
    ]
)
```

3. Write the following code in `main.swift` and build it (we will get some errors).
```swift:main.swift
//
//  main.swift
//  ExistentialAnySample
//
//  Created by treastrain on 2023/04/08.
//

class C {}
protocol P {}
protocol Q {}

func f1(_ v: C & P) {} // ❌ Use of protocol 'P' as a type must be written 'any P'

func f2(_ v: P & Q) {} // ❌ Use of protocol 'P' as a type must be written 'any P'
                       // ❌ Use of protocol 'Q' as a type must be written 'any Q'
```

4. In the Xcode menu bar, "Editor" > "Fix all issues (Cmd + Ctrl + Option + F)".

5. The error continues and the build fails.

**Expected behavior**
After "Fix all issues (Cmd + Ctrl + Option + F)", `C & P` should be replaced with `any C & P`, and `P & Q` should be replaced with `any P & Q` in one shot.

**Environment**
- Swift compiler version info `swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100) Target: arm64-apple-macosx13.0`
- Xcode version info `Xcode 14.3 Build version 14E222b`
- Deployment target: iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4

### LINKED ISSUE #72588: Upcoming feature flag ExistentialAny ignores missing `any` keyword when constraining a protocol
### Description

_No response_

### Reproduction

Compiling the following program with `-enable-upcoming-feature ExistentialAny` succeeds, even though it should fail since the constraint on `f`'s parameter is written as `P2` instead of `any P2`.

```swift
protocol P1<T> {
    associatedtype T
}

protocol P2 {}

func f(_: some P1<P2>) {} // <---
```

### Expected behavior

The compiler should (when compiling with the ExistentialAny flag on) require that existential be explicitly spelled with `any`, as defined in [SE-0335](https://github.com/apple/swift-evolution/blob/main/proposals/0335-existential-any.md#proposed-solution).

### Environment

Apple Swift version 6.0-dev (LLVM 1ad249b55ef5cc0, Swift b10d97dd01fac82)
Target: arm64-apple-macosx14.0

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
Resolves #65026, resolves #65027, resolves #72588.

Diff counts are mostly due to tests.

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test macOS

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test macOS

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test macOS

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test macOS

**Comment by AnthonyLatsis** [comment]
@slavapestov @hborla ping

File: test/Parse/inverses.swift
Comment (AnthonyLatsis) [inline test/Parse/inverses.swift:1]: I have incorporated the tests I deleted here into `test/type/explicit_existential.swift` and `test/type/explicit_existential_swift6.swift`

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test Linux

File: test/decl/protocol/protocols.swift [hunk 1]
```diff
@@ -103,9 +103,9 @@ struct DoesNotConform : Up {
 // Circular protocols
 
 protocol CircleMiddle : CircleStart { func circle_middle() }
-// expected-note@-1 2 {{protocol 'CircleMiddle' declared here}}
-protocol CircleStart : CircleEnd { func circle_start() } // expected-error 2 {{protocol 'CircleStart' refines itself}}
-protocol CircleEnd : CircleMiddle { func circle_end()} // expected-note 2 {{protocol 'CircleEnd' declared here}}
+// expected-note@-1 3 {{protocol 'CircleMiddle' declared here}}
+protocol CircleStart : CircleEnd { func circle_start() } // expected-error 3 {{protocol 'CircleStart' refines itself}}
+protocol CircleEnd : CircleMiddle { func circle_end()} // expected-note 3 {{protocol 'CircleEnd' declared here}}
```
Comment (AnthonyLatsis) [inline test/decl/protocol/protocols.swift:108]: This is unfortunate although definitely not a `ExistentialTypeSyntaxChecker` problem.

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test Linux

**Comment by AnthonyLatsis** [comment]
@swift-ci please test source compatibility release

**Comment by AnthonyLatsis** [comment]
@slavapestov ping

File: test/type/explicit_existential.swift [hunk 2]
```diff
@@ -1,4 +1,4 @@
-// RUN: %target-typecheck-verify-swift
+// RUN: %target-typecheck-verify-swift -enable-experimental-feature NoncopyableGenerics
```
Comment (slavapestov) [inline test/type/explicit_existential.swift:1]: This shouldn't be needed anymore

File: lib/Sema/TypeCheckType.cpp [hunk 3]
```diff
@@ -6097,13 +6128,32 @@ class ExistentialTypeSyntaxChecker : public ASTWalker {
       return;
     }
 
+    // Backtrack the stack, looking just through parentheses and metatypes. If
+    // we find an inverse (which always requires `any`), diagnose it specially.
```
Comment (slavapestov) [inline lib/Sema/TypeCheckType.cpp:6132]: You might be able to just pass down the outermost location instead of "backtracking" here, but it's fine the way it is

**Review by slavapestov — APPROVED** [review]

File: lib/Sema/TypeCheckType.cpp (hunk 3 above)
Comment (AnthonyLatsis) [reply lib/Sema/TypeCheckType.cpp:6175]: Thanks for sharing your thoughts on this, Slava. 

> You might be able to just pass down the outermost location

Unless you mean something

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

File: lib/Sema/TypeCheckType.cpp (hunk 3 above)
Comment (AnthonyLatsis) [reply lib/Sema/TypeCheckType.cpp:6175]: Thanks for sharing your thoughts on this, Slava. 

> You might be able to just pass down the outermost location

Is this roughly what you meant (pass `tildeLoc` down such that if valid here, then the `~` necessarily pertains to the given identifier type)?

```c++
// walkToTypeReprPre

if (auto *inverse = isa<InverseTypeRepr>(T)) {
  this->tildeLoc = inverse->getTildeLoc();
} else if (this->tildeLoc.isValid()) {
  if (!T->isParenType() &&
      !isa<MetatypeTypeRepr>(T) &&
      !isa<DeclRefTypeRepr>(T)) {
    this->tildeLoc = SourceLoc();
  }
}

// ...
// checkDeclRefTypeRepr(declRefTR);

this->tildeLoc = SourceLoc();
```

Comment (AnthonyLatsis) [reply lib/Sema/TypeCheckType.cpp:6175]: I’m going to try to get this into the release as is before it’s too late, but I’m still very much willing to discuss this alternative.
