### PR TITLE
Loop on Win32 to satisfy large random byte requests (as is done on Linux)

### LINKED ISSUE #62130: `swift_stdlib_random()` crashes on Windows for large buffer sizes
`swift_stdlib_random()`, underlying `SystemRandomNumberGenerator`, sets a hard limit of `ULONG_MAX` bytes for its buffer size, and aborts if the requested buffer size is larger. On other platforms, it calls the underlying RNG multiple times to satisfy the request. The same should be done on Windows.

### PR DESCRIPTION
**Pull request by grynspan**
This change resolves a crash on Windows when using `SystemRandomNumberGenerator` and requesting a very large number (> `ULONG_MAX`) of random bytes.

In practice, it's unlikely anyone will be requesting more than 4GB of random bytes, but we don't abort on other platforms and nothing about the API suggests that a large buffer size is unsupported or disallowed.

I have not written a unit test because it would be impractical to request such a large amount of random data during a test run in CI.

Resolves #62130.

### CODE REVIEW

**Review by al45tair — APPROVED** [review]

**Review by mikeash — APPROVED** [review]

**Comment by grynspan** [comment]
@swift-ci please test

File: stdlib/public/stubs/Random.cpp [hunk 1]
```diff
@@ -65,16 +65,18 @@ void swift_stdlib_random(void *buf, __swift_size_t nbytes) {
 
 SWIFT_RUNTIME_STDLIB_API
 void swift_stdlib_random(void *buf, __swift_size_t nbytes) {
-  if (nbytes > ULONG_MAX) {
-    fatalError(0, "Fatal error: %zd exceeds ULONG_MAX\n", nbytes);
-  }
+  while (nbytes > 0) {
+    auto actual_nbytes = std::min(nbytes, (__swift_size_t)ULONG_MAX);
```
Comment (compnerd) [inline stdlib/public/stubs/Random.cpp:69]: It would be nice to use `static_cast` as this is C++.

```suggestion
    auto actual_nbytes = std::min(nbytes, static_cast<__swift_size_t>(ULONG_MAX));
```

**Review by compnerd — APPROVED** [review]
Thanks for fixing this!

File: stdlib/public/stubs/Random.cpp (hunk 1 above)
Comment (grynspan) [reply stdlib/public/stubs/Random.cpp:70]: Good question. AFAIK the unit tests for random number generation are not conditionalized by platform, are they?

**Comment by grynspan** [comment]
@swift-ci please test
