### PR TITLE
[AutoDiff] Support curry thunks differentiation in fragile funcs

### LINKED ISSUE #54819: [SR-14228] [AutoDiff] "Curry thunk" differentiation regression
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14228      |
   |Radar             | None         |
   |Original Reporter | @dan-zheng      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, AutoDiff        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 8635dba187654182d9292136d60a56fd

  </details>

**relates to**:  
* [TF-1030](https://bugs.swift.org/browse/TF-1030) allow serialized functions to reference implicit derivatives in some cases  

**Issue Description:**

Curry thunks were recently rewritten as implicit AST closures instead of SILGen'd thunks: <https://github.com/apple/swift/pull/28698.>

This caused regressions in curry thunk differentiation. Extracted from `test/AutoDiff/downstream/generics.swift`:

``` swift
// TF-688: Test generic curry thunk cloning.
public struct TF_688_Struct<Scalar> {
  var x: Scalar
}
extension TF_688_Struct: Differentiable where Scalar: Differentiable {
  @differentiable
  public static func id(x: Self) -> Self {
    return x
  }
}
@differentiable(wrt: x)
public func TF_688<Scalar: Differentiable>(
  _ x: TF_688_Struct<Scalar>,
  reduction: @differentiable (TF_688_Struct<Scalar>) -> TF_688_Struct<Scalar> = TF_688_Struct.id
) -> TF_688_Struct<Scalar> {
  reduction(x)
}
```

Before: no error.

``` java
// default argument 1 of TF_688<A>(_:reduction:)
sil non_abi [serialized] [ossa] @$s4main6TF_688_9reductionAA0B11_688_StructVyxGAF_A2FXFts14DifferentiableRzlFfA0_ : $@convention(thin) <Scalar where Scalar : Differentiable> () -> @owned @differentiable @callee_guaranteed (@in_guaranteed TF_688_Struct<Scalar>) -> @out TF_688_Struct<Scalar> {
bb0:
  %0 = metatype $@thin TF_688_Struct<Scalar>.Type // user: %2
  // function_ref curry thunk of static TF_688_Struct<A>.id(x:)
  %1 = function_ref @$s4main13TF_688_StructVAAs14DifferentiableRzlE2id1xACyxGAG_tFZTc : $@convention(thin) <τ_0_0 where τ_0_0 : Differentiable> (@thin TF_688_Struct<τ_0_0>.Type) -> @owned @callee_guaranteed (@in_guaranteed TF_688_Struct<τ_0_0>) -> @out TF_688_Struct<τ_0_0> // user: %2
  %2 = apply %1<Scalar>(%0) : $@convention(thin) <τ_0_0 where τ_0_0 : Differentiable> (@thin TF_688_Struct<τ_0_0>.Type) -> @owned @callee_guaranteed (@in_guaranteed TF_688_Struct<τ_0_0>) -> @out TF_688_Struct<τ_0_0> // user: %3
  %3 = differentiable_function [parameters 0] %2 : $@callee_guaranteed (@in_guaranteed TF_688_Struct<Scalar>) -> @out TF_688_Struct<Scalar> // user: %4
  return %3 : $@differentiable @callee_guaranteed (@in_guaranteed TF_688_Struct<Scalar>) -> @out TF_688_Struct<Scalar> // id: %4
} // end sil function '$s4main6TF_688_9reductionAA0B11_688_StructVyxGAF_A2FXFts14DifferentiableRzlFfA0_'
```

After: error regarding differentiating fragile function in serialized function.  
This error was introduced in <https://github.com/apple/swift/pull/28582.>

``` java
$ swiftc -Xllvm -debug-only=differentiation tf-688.swift
// AD__$s4main6TF_688_9reductionAA0B11_688_StructVyxGAF_A2FXFts14DifferentiableRzlFfA0_A2FcAFmcfu___differentiable_curry_thunk_src_0_wrt_0
sil shared [serialized] @AD__$s4main6TF_688_9reductionAA0B11_688_StructVyxGAF_A2FXFts14DifferentiableRzlFfA0_A2FcAFmcfu___differentiable_curry_thunk_src_0_wrt_0 : $@convention(thin) <τ_0_0 where τ_0_0 : Differentiable> (@thin TF_688_Struct<τ_0_0>.Type) -> @owned @differentiable @callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed TF_688_Struct<τ_0_0>) -> @out TF_688_Struct<τ_0_1> for <τ_0_0, τ_0_0> {
// %0                                             // users: %3, %1
bb0(%0 : $@thin TF_688_Struct<τ_0_0>.Type):
  debug_value %0 : $@thin TF_688_Struct<τ_0_0>.Type, let, name "self", argno 1 // id: %1
  // function_ref implicit closure #&#8203;2 in implicit closure #&#8203;1 in default argument 1 of TF_688<A>(_:reduction:)
  %2 = function_ref @$s4main6TF_688_9reductionAA0B11_688_StructVyxGAF_A2FXFts14DifferentiableRzlFfA0_A2FcAFmcfu_A2Fcfu0_ : $@convention(thin) <τ_0_0 where τ_0_0 : Differentiable> (@in_guaranteed TF_688_Struct<τ_0_0>, @thin TF_688_Struct<τ_0_0>.Type) -> @out TF_688_Struct<τ_0_0> // user: %3
  %3 = partial_apply [callee_guaranteed] %2<τ_0_0>(%0) : $@convention(thin) <τ_0_0 where τ_0_0 : Differentiable> (@in_guaranteed TF_688_Struct<τ_0_0>, @thin TF_688_Struct<τ_0_0>.Type) -> @out TF_688_Struct<τ_0_0> // user: %4
  %4 = convert_function %3 : $@callee_guaranteed (@in_guaranteed TF_688_Struct<τ_0_0>) -> @out TF_688_Struct<τ_0_0> to $@callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed TF_688_Struct<τ_0_0>) -> @out TF_688_Struct<τ_0_1> for <τ_0_0, τ_0_0> // user: %5
  %5 = differentiable_function [parameters 0] %4 : $@callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed TF_688_Struct<τ_0_0>) -> @out TF_688_Struct<τ_0_1> for <τ_0_0, τ_0_0> // user: %6
  return %5 : $@differentiable @callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed TF_688_Struct<τ_0_0>) -> @out TF_688_Struct<τ_0_1> for <τ_0_0, τ_0_0> // id: %6
} // end sil function 'AD__$s4main6TF_688_9reductionAA0B11_688_StructVyxGAF_A2FXFts14DifferentiableRzlFfA0_A2FcAFmcfu___differentiable_curry_thunk_src_0_wrt_0'

[AD] Diagnosing non-differentiability.
[AD] For value:
  %4 = convert_function %3 : $@callee_guaranteed (@in_guaranteed TF_688_Struct<τ_0_0>) -> @out TF_688_Struct<τ_0_0> to $@callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed TF_688_Struct<τ_0_0>) -> @out TF_688_Struct<τ_0_1> for <τ_0_0, τ_0_0> // user: %5
[AD] With invoker:
(differentiation_invoker differentiable_function_inst=(  %5 = differentiable_function [parameters 0] %4 : $@callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed TF_688_Struct<τ_0_0>) -> @out TF_688_Struct<τ_0_1> for <τ_0_0, τ_0_0> // user: %6
))
tf-688.swift:14:95: error: function is not differentiable
  reduction: @differentiable (TF_688_Struct<Scalar>) -> TF_688_Struct<Scalar> = TF_688_Struct.id
                                                                                ~~~~~~~~~~~~~~^~
tf-688.swift:14:95: note: differentiated functions in '@inlinable' functions must be marked '@differentiable' or have a public '@derivative'; this is not possible with a closure, make a top-level function instead
  reduction: @differentiable (TF_688_Struct<Scalar>) -> TF_688_Struct<Scalar> = TF_688_Struct.id
                                                                                              ^
```

### LINKED ISSUE #75776: Function incorrectly marked as not differentiable
### Description

The following code does not compile giving the following error diagnostic:
```
Function is not differentiable
Differentiated functions in '@inlinable' functions must be marked '@differentiable' or have a public '@derivative'; this is not possible with a closure, make a top-level function instead
```

This is incorrect however as the function itself is not a closure and is differentiable. 

### Reproduction

```swift
import _Differentiation

public struct Solution2<Thing: Differentiable & FloatingPoint>: Differentiable where Thing.TangentVector == Thing {
    @inlinable
    public static func optimization() -> Thing {
        var initial = Thing.zero
        
        let (_, delta) = valueWithGradient(at: initial, of: simulationWithLoss)
        
        initial.move(by: delta)
        
        return initial
    }
    
    @inlinable
    @differentiable(reverse)
    static func simulationWithLoss(input: Thing) -> Thing {
        return input // implementation
    }
}
```

### Expected behavior

Compile without error

### Environment

Apple Swift version 6.0-dev (LLVM 097782ee554d9fe, Swift 60bf038ce965551)
Target: arm64-apple-macosx14.0

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by kovdan01**
Inside fragile functions, we expect function derivatives to be public, which could be achieved by either explicitly marking the functions as differentiable or having a public explicit derivative defined for them. This is obviously not possible for single and double curry thunks which are a special case of `AutoClosureExpr`.

Instead of looking at the thunk itself, we unwrap it and look at the function being wrapped. While the thunk itself and its differentiability witness will not have public visibility, it's not an issue for the case where the function being wrapped (and its witness) have public visibility.

Fixes #54819
Fixes #75776

### CODE REVIEW

**Comment by kovdan01** [comment]
Tagging @asl

**Comment by asl** [comment]
Tagging @JaapWijnen

File: lib/AST/Expr.cpp [hunk 1]
```diff
@@ -2211,6 +2211,20 @@ Expr *AutoClosureExpr::getUnwrappedCurryThunkExpr() const {
   return nullptr;
 }
 
+Expr *AutoClosureExpr::getUnwrappedCurryThunkExpr() const {
```
[the remark this answers is not in the document]
Comment (kovdan01) [reply lib/AST/Expr.cpp:2214]: @slavapestov Do you mean that `getUnwrappedCurryThunkCalledValue()` might be used instead of `getUnwrappedCurryThunkExpr()`? I don't think so: I intentionally moved the actual implementation into a separate `getUnwrappedCurryThunkImpl()` function, so we can either get an `Expr` or a `ValueDecl` depending of what we need.

`getUnwrappedCurryThunkExpr()` seems to have a number of uses over the code base, and that uses seem to expect `Expr` and not `ValueDecl`, so it's probably still needed. Anyway, even if some refactoring might be done (while I do not see a room for it in this particular case), probably it would be better to keep it separate from functional changes.

If I got your question wrong and this does not answer it, it would be great if you can clarify your point a bit.

**Comment by kovdan01** [comment]
Would be glad to see feedback from everyone interested

**Comment by asl** [comment]
@swift-ci please test

**Comment by kovdan01** [comment]
Would be glad to see feedback from everyone interested

**Comment by kovdan01** [comment]
Would be glad to see feedback from everyone interested

**Comment by kovdan01** [comment]
Would be glad to see feedback from everyone interested

**Comment by kovdan01** [comment]
Would be glad to see feedback from everyone interested

**Comment by kovdan01** [comment]
Would be glad to see feedback from everyone interested

**Comment by kovdan01** [comment]
Would be glad to see feedback from everyone interested

**Comment by kovdan01** [comment]
Would be glad to see feedback from everyone interested

**Comment by kovdan01** [comment]
Would be glad to see feedback from everyone interested

**Comment by kovdan01** [comment]
Would be glad to see feedback from everyone interested

File: lib/SILOptimizer/Mandatory/Differentiation.cpp [hunk 2]
```diff
@@ -453,21 +476,55 @@ static SILValue reapplyFunctionConversion(
...
-    const AutoDiffConfig &desiredConfig, AutoDiffDerivativeFunctionKind kind,
-    SILValue original, DifferentiationInvoker invoker,
-    SmallVectorImpl<AllocStackInst *> &newBuffersToDealloc) {
-  ADContext &context = transformer.getContext();
+SILFunction *DifferentiationTransformer::getUnwrappedCurryThunkFunction(
+    SILFunction *originalFn) {
+  auto *abstractCE = originalFn->getDeclRef().getAbstractClosureExpr();
+  if (abstractCE == nullptr)
+    return nullptr;
+  auto *autoCE = dyn_cast<AutoClosureExpr>(abstractCE);
```
Comment (asl) [inline lib/SILOptimizer/Mandatory/Differentiation.cpp:484]: nit: could simplify a bit with `dyn_cast_or_null`

File: lib/SILOptimizer/Mandatory/Differentiation.cpp [hunk 3]
```diff
@@ -453,21 +476,55 @@ static SILValue reapplyFunctionConversion(
...
+        // ExprRewriter::buildDeclRef). If new use cases of curry thunks appear
+        // in future, the assertion after the loop will be a trigger for such
+        // cases being unhandled here.
+        //
+        // FIXME: References to functions having external property wrapper
+        // parameters are not handled since we can't now construct a test case
+        // for that due to the crash
+        // https://github.com/swiftlang/swift/issues/77613
+        if (currentAFD->hasCurriedSelf())
+          afdToSILFn.insert({currentAFD, &currentFunc});
```
Comment (asl) [inline lib/SILOptimizer/Mandatory/Differentiation.cpp:511]: `try_emplace` + assert on result?

**Comment by kovdan01** [comment]
I've limited scope of the changes only to AutoDiff code - see 2cadfa09d004a3b135f89ef0b03abf20d168770c

File: lib/SILOptimizer/Mandatory/Differentiation.cpp (hunk 3 above)
Comment (kovdan01) [reply lib/SILOptimizer/Mandatory/Differentiation.cpp]: Applied the suggestion, thanks, see c674f80962108686e5fecd557e040f449c64dcfa

File: lib/SILOptimizer/Mandatory/Differentiation.cpp (hunk 2 above)
Comment (kovdan01) [reply lib/SILOptimizer/Mandatory/Differentiation.cpp]: Applied the suggestion, thanks, see c674f80962108686e5fecd557e040f449c64dcfa

**Comment by asl** [comment]
@swift-ci please test

File: lib/SILOptimizer/Mandatory/Differentiation.cpp [hunk 4]
```diff
@@ -453,21 +476,66 @@ static SILValue reapplyFunctionConversion(
...
+        // cases being unhandled here.
+        //
+        // FIXME: References to functions having external property wrapper
+        // parameters are not handled since we can't now construct a test case
+        // for that due to the crash
+        // https://github.com/swiftlang/swift/issues/77613
+        if (currentAFD->hasCurriedSelf()) {
+          auto [_, wasEmplace] =
+              afdToSILFn.try_emplace(currentAFD, &currentFunc);
+          assert(wasEmplace);
```
Comment (asl) [inline lib/SILOptimizer/Mandatory/Differentiation.cpp:521]: see above

File: lib/SILOptimizer/Mandatory/Differentiation.cpp [hunk 5]
```diff
@@ -453,21 +476,66 @@ static SILValue reapplyFunctionConversion(
...
+  case AutoClosureExpr::Kind::DoubleCurryThunk:
+    afd = cast<AbstractFunctionDecl>(cast<ApplyExpr>(expr)->getCalledValue(
+        /*skipFunctionConversions=*/true));
+    break;
+  }
+  assert(afd);
+
+  auto silFnIt = afdToSILFn.find(afd);
+  if (silFnIt == afdToSILFn.end()) {
+    assert(afdToSILFn.empty());
```
Comment (asl) [inline lib/SILOptimizer/Mandatory/Differentiation.cpp:501]: see above

Comment (kovdan01) [reply lib/SILOptimizer/Mandatory/Differentiation.cpp]: Addressed in 4d74d349573bed30a0f64fbc90de89b1392e1830, thanks

File: lib/SILOptimizer/Mandatory/Differentiation.cpp (hunk 4 above)
Comment (kovdan01) [reply lib/SILOptimizer/Mandatory/Differentiation.cpp]: Addressed in 4d74d349573bed30a0f64fbc90de89b1392e1830, thanks

File: lib/SILOptimizer/Mandatory/Differentiation.cpp [hunk 6]
```diff
@@ -453,21 +476,66 @@ static SILValue reapplyFunctionConversion(
...
+  switch (autoCE->getThunkKind()) {
+  default:
+    llvm_unreachable("Only single and double curry thunks are expected");
+  case AutoClosureExpr::Kind::SingleCurryThunk:
+  case AutoClosureExpr::Kind::DoubleCurryThunk:
+    afd = cast<AbstractFunctionDecl>(cast<ApplyExpr>(expr)->getCalledValue(
+        /*skipFunctionConversions=*/true));
+    break;
+  }
+  assert(afd);
```
[the remark this answers is not in the document]
Comment (kovdan01) [reply lib/SILOptimizer/Mandatory/Differentiation.cpp]: I've changed the logic a bit in 4d74d349573bed30a0f64fbc90de89b1392e1830. It actually looks like that other thunk types (not single and double curry thunks) could go here, and this is valid, we just need to return `nullptr` (just as we do right above if we detect not `AutoClosureExpr`).

Since `getUnwrappedCurryThunkExpr` already has checks against single and double curry thunks and returns `nullptr` for other thunk types, using it in conjunction with `dyn_cast_or_null` with subsequent check against `nullptr` should be enough.

**Review by asl — APPROVED** [review]
All the changes were localized down to autodiff code (no code outside autodiff are to be changed) and looks good to me
