### PR TITLE
[interop][SwiftToCxx] move semantics for Swift classes; use of C++ move for unimplemented Swift value moves fails at link time now 

### LINKED ISSUE #64702: [interop] Assigning en expression with a constructor to a variable with a superclass type triggers a move
**Steps to reproduce**

Modify the lldb "TestSwiftBackwardInteropStepping" test's main.cpp file, line 40 from:
```c++
  auto swiftClass = SwiftSubclass::init();
```

To:
```c++
  SwiftSubclass swiftClass = SwiftSubclass::init();
```

Running the compiler program should trigger a move and assert.

### PR DESCRIPTION
**Pull request by hyp**
1) [interop][SwiftToCxx] moving a Swift class in C++ performs a copy
    C++ does not have a consuming move, so fallback to copy instead

    Fixes https://github.com/apple/swift/issues/64702

2) [interop][SwiftToCxx] the not yet implemented move constructor for Swift value types should lead to link error when a move is used in Swift, not runtime error

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test source compatibility

**Comment by hyp** [comment]
Fixes: https://github.com/apple/swift/issues/64702

File: lib/PrintAsClang/_SwiftCxxInteroperability.h [hunk 1]
```diff
@@ -159,18 +174,28 @@ class RefCountedClass {
...
     return *this;
   }
-#pragma clang diagnostic push
-#pragma clang diagnostic ignored "-Wmissing-noreturn"
-  // FIXME: implement 'move'?
-  SWIFT_INLINE_THUNK RefCountedClass(RefCountedClass &&) noexcept { abort(); }
-#pragma clang diagnostic pop
+  SWIFT_INLINE_THUNK RefCountedClass &
+  operator=(RefCountedClass &&other) noexcept {
+    swift_retain(other._opaquePointer);
```
Comment (zoecarver) [inline lib/PrintAsClang/_SwiftCxxInteroperability.h:194]: Sucks that we can't optimize away this retain.. I guess that's C++ for you :(

**Review by zoecarver — COMMENTED** [review]
LGTM!
