### PR TITLE
[Sema] SR-15940: Assert crash in TypeCheckStmt.cpp

### LINKED ISSUE #58201: [SR-15940] Assert crash in TypeCheckStmt.cpp
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15940      |
   |Radar             | None         |
   |Original Reporter | ellis (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   md5: c0318b50fadbb361c90032f67b6a66fb

  </details>

**Issue Description:**
Swift crashes when compiling the following source.

```swift
@propertyWrapper
public class Bar<Value> {
  public init(wrappedValue: @autoclosure () -> Value) {}
  public var wrappedValue: Value {}
}

class Foo {
  @Bar var a: Bool?
}
```

Here is the backtrace

```
error: compile command failed due to signal 6 (use -v to see invocation)
test.swift:4:35: error: computed property must have accessors specified
public var wrappedValue: Value {}
^
swift-frontend: swift/lib/Sema/TypeCheckStmt.cpp:86: virtual std::pair<bool, Expr *> (anonymous namespace)::ContextualizeClosures::walkToExprPre(swift::Expr *): Assertion `CE->getDiscriminator() == AutoClosureExpr::InvalidDiscriminator' failed.
Please submit a bug report (<https://swift.org/contributing/#reporting-bugs)> and include the project and the crash backtrace.
Stack dump:
0. Program arguments: swift-frontend -frontend -c -primary-file test.swift -target arm64-apple-ios11.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -color-diagnostics -new-driver-path /swift-driver -resource-dir swift -module-name EmojiPickerLayout -target-sdk-version 15.2 -o /tmp/TemporaryDirectory.qXz2A9/EmojiPickerLayout-1.o
1. Swift version 5.6-dev (LLVM a5fb80477a008fd, Swift c2abee2cb7c2471)
2. Compiling with the current language version
3. While evaluating request TypeCheckSourceFileRequest(source_file "test.swift")
4. While type-checking 'Foo' (at test.swift:7:1)
5. While type-checking declaration 0x8841d80 (in module 'EmojiPickerLayout')
#0 0x0000000007d136f3 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) llvm-project/llvm/lib/Support/Unix/Signals.inc:565:13
#1 0x0000000007d11a50 llvm::sys::RunSignalHandlers() llvm-project/llvm/lib/Support/Signals.cpp:98:18
#2 0x0000000007d13a7f SignalHandler(int) llvm-project/llvm/lib/Support/Unix/Signals.inc:407:1
#3 0x00007f72a1d3f130 __restore_rt (/usr/local/fbcode/platform009/lib/libpthread.so.0+0x15130)
#4 0x00007f72a17d2530 raise /home/engshare/third-party2/glibc/2.30/src/glibc-2.30/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
#5 0x00007f72a17b951d abort /home/engshare/third-party2/glibc/2.30/src/glibc-2.30/stdlib/abort.c:81:7
#6 0x00007f72a17c94c3 __assert_fail_base /home/engshare/third-party2/glibc/2.30/src/glibc-2.30/assert/assert.c:89:7
#7 0x00007f72a17c9533 (/usr/local/fbcode/platform009/lib/libc.so.6+0x35533)
#8 0x00000000040db1cf swift::AbstractClosureExpr::setDiscriminator(unsigned int) swift/include/swift/AST/Expr.h:3610:5
#9 0x00000000040db1cf (anonymous namespace)::ContextualizeClosures::walkToExprPre(swift::Expr*) swift/lib/Sema/TypeCheckStmt.cpp:87:13
#10 0x00000000043404af (anonymous namespace)::Traversal::doIt(swift::Expr*) swift/lib/AST/ASTWalker.cpp:1197:14
#11 0x00000000043404af (anonymous namespace)::Traversal::doIt(swift::ArgumentList*) swift/lib/AST/ASTWalker.cpp:1360:17
#12 0x00000000043432cd (anonymous namespace)::Traversal::visitApplyExpr(swift::ApplyExpr*) swift/lib/AST/ASTWalker.cpp:856:15
#13 0x000000000433f891 (anonymous namespace)::Traversal::SetParentRAII::~SetParentRAII() swift/lib/AST/ASTWalker.cpp:93:21
#14 0x000000000433f891 (anonymous namespace)::Traversal::visit(swift::Expr*) swift/lib/AST/ASTWalker.cpp:100:3
#15 0x000000000433f891 (anonymous namespace)::Traversal::doIt(swift::Expr*) swift/lib/AST/ASTWalker.cpp:1201:9
#16 0x000000000433f891 swift::Expr::walk(swift::ASTWalker&) swift/lib/AST/ASTWalker.cpp:1891:28
#17 0x00000000040d64ab swift::TypeChecker::contextualizeInitializer(swift::Initializer*, swift::Expr*) swift/lib/Sema/TypeCheckStmt.cpp:202:1
#18 0x0000000004024715 (anonymous namespace)::DeclChecker::visitPatternBindingDecl(swift::PatternBindingDecl*) swift/lib/Sema/TypeCheckDeclPrimary.cpp:2088:13
#19 0x0000000004024715 swift::ASTVisitor<(anonymous namespace)::DeclChecker, void, void, void, void, void, void>::visit(swift::Decl*) swift/include/swift/AST/DeclNodes.def:185:1
#20 0x0000000004024715 (anonymous namespace)::DeclChecker::visit(swift::Decl*) swift/lib/Sema/TypeCheckDeclPrimary.cpp:1697:31
#21 0x000000000402a1ac (anonymous namespace)::DeclChecker::visitClassDecl(swift::ClassDecl*) swift/lib/Sema/TypeCheckDeclPrimary.cpp:2478:23
#22 0x0000000004023aeb swift::ASTVisitor<(anonymous namespace)::DeclChecker, void, void, void, void, void, void>::visit(swift::Decl*) swift/include/swift/AST/DeclNodes.def:0:9
#23 0x0000000004023aeb (anonymous namespace)::DeclChecker::visit(swift::Decl*) swift/lib/Sema/TypeCheckDeclPrimary.cpp:1697:31
#24 0x000000000402383e swift::TypeChecker::typeCheckDecl(swift::Decl*, bool) swift/lib/Sema/TypeCheckDeclPrimary.cpp:3186:1
#25 0x000000000410e267 swift::TypeCheckSourceFileRequest::evaluate(swift::Evaluator&, swift::SourceFile*) const swift/lib/Sema/TypeChecker.cpp:336:17
#26 0x0000000004110258 llvm::Expected<swift::TypeCheckSourceFileRequest::OutputType> swift::Evaluator::getResultUncached<swift::TypeCheckSourceFileRequest>(swift::TypeCheckSourceFileRequest const&) swift/include/swift/AST/Evaluator.h:362:14
#27 0x000000000410ff72 llvm::Expected<std::tuple<> >::operator bool() llvm-project/llvm/include/llvm/Support/Error.h:564:17
#28 0x000000000410ff72 llvm::Expected<swift::TypeCheckSourceFileRequest::OutputType> swift::Evaluator::getResultCached<swift::TypeCheckSourceFileRequest, (void*)0>(swift::TypeCheckSourceFileRequest const&) swift/include/swift/AST/Evaluator.h:393:10
#29 0x000000000410e0c4 llvm::Expected<std::tuple<> >::takeError() llvm-project/llvm/include/llvm/Support/Error.h:592:15
#30 0x000000000410e0c4 swift::TypeCheckSourceFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckSourceFileRequest>(swift::Evaluator&, swift::TypeCheckSourceFileRequest, swift::TypeCheckSourceFileRequest::OutputType) swift/include/swift/AST/Evaluator.h:106:25
#31 0x000000000410e06e swift::performTypeChecking(swift::SourceFile&) swift/lib/Sema/TypeChecker.cpp:286:3
#32 0x000000000321ab3a swift::CompilerInstance::forEachFileToTypeCheck(llvm::function_ref<void (swift::SourceFile&)>) swift/lib/Frontend/Frontend.cpp:1138:19
#33 0x000000000321aa08 _*gnu_cxx::normal_iterator<unsigned int const*, std::vector<unsigned int, std::allocator<unsigned int> > >::*_normal_iterator(unsigned int const* const&) /mnt/gvfs/third-party2/libgcc/9ec50d4571ff7613c2a4dc750831a6d1cb86995f/9.x/platform009/9202ce7/include/c++/9.x/bits/stl_iterator.h:808:20
#34 0x000000000321aa08 std::vector<unsigned int, std::allocator<unsigned int> >::begin() const /mnt/gvfs/third-party2/libgcc/9ec50d4571ff7613c2a4dc750831a6d1cb86995f/9.x/platform009/9202ce7/include/c++/9.x/bits/stl_vector.h:818:16
#35 0x000000000321aa08 std::vector<unsigned int, std::allocator<unsigned int> >::empty() const /mnt/gvfs/third-party2/libgcc/9ec50d4571ff7613c2a4dc750831a6d1cb86995f/9.x/platform009/9202ce7/include/c++/9.x/bits/stl_vector.h:1005:16
#36 0x000000000321aa08 llvm::SetVector<unsigned int, std::vector<unsigned int, std::allocator<unsigned int> >, llvm::DenseSet<unsigned int, llvm::DenseMapInfo<unsigned int> > >::empty() const llvm-project/llvm/include/llvm/ADT/SetVector.h:73:20
#37 0x000000000321aa08 swift::CompilerInstance::isWholeModuleCompilation() const swift/include/swift/Frontend/Frontend.h:454:67
#38 0x000000000321aa08 swift::CompilerInstance::forEachFileToTypeCheck(llvm::function_ref<void (swift::SourceFile&)>) swift/lib/Frontend/Frontend.cpp:1129:7
#39 0x000000000321aa08 swift::CompilerInstance::finishTypeChecking() swift/lib/Frontend/Frontend.cpp:1145:3
#40 0x000000000321aa08 swift::CompilerInstance::performSema() swift/lib/Frontend/Frontend.cpp:1070:3
#41 0x000000000308123b withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>) swift/lib/FrontendTool/FrontendTool.cpp:1108:7
#42 0x000000000307838d performAction(swift::CompilerInstance&, int&, swift::FrontendObserver*) swift/lib/FrontendTool/FrontendTool.cpp:0:12
#43 0x000000000307838d performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) swift/lib/FrontendTool/FrontendTool.cpp:1306:19
#44 0x00000000030778f6 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) swift/lib/FrontendTool/FrontendTool.cpp:2080:46
#45 0x0000000003045f83 swift::mainEntry(int, char const**) swift/lib/DriverTool/driver.cpp:405:12
#46 0x00007f72a17b9dc5 __libc_start_main /home/engshare/third-party2/glibc/2.30/src/glibc-2.30/csu/../csu/libc-start.c:308:16
#47 0x000000000304590a _start /home/engshare/third-party2/glibc/2.30/src/glibc-2.30/csu/../sysdeps/x86_64/start.S:122:0
```

### PR DESCRIPTION
**Pull request by hank121314**
## Summary

This PR fixes: [SR-15940](https://github.com/apple/swift/issues/58201) #58201.

In [TypeCheckStorage.cpp](https://github.com/apple/swift/blob/bc43ced36a77806125b44a079f568bf149834552/lib/Sema/TypeCheckStorage.cpp#L2981-L2985), it will type-check default initializer and if there is a autoclosure in default initializer, its discriminator will also be set.
And In [TypeCheckDeclPrimary.cpp](https://github.com/apple/swift/blob/bc43ced36a77806125b44a079f568bf149834552/lib/Sema/TypeCheckDeclPrimary.cpp#L2164-L2168), when visiting `PatternBindingDecl` it will type-check the autoclosure in default initializer again which might cause the [assertion error](https://github.com/apple/swift/blob/bc43ced36a77806125b44a079f568bf149834552/lib/Sema/TypeCheckStmt.cpp#L86).

## Solution

This PR tries to stop the recursive check in `TypeCheckStmt.cpp` if the autoclosure is already checked in default initializer.

## Thanks

Please feel free to critique, and thanks for your code review 😄 .

### CODE REVIEW

File: lib/Sema/TypeCheckStmt.cpp [hunk 1]
```diff
@@ -82,7 +82,13 @@ namespace {
         if (CE->getParent() == ParentDC
             && CE->getDiscriminator() != AutoClosureExpr::InvalidDiscriminator)
           return { false, E };
-        
+        // Stop the recursion if the autoclosure is already checked in
+        // default initializer.
+        if (auto *initContext = dyn_cast<PatternBindingInitializer>(ParentDC))
+          if (initContext->getBinding()->isInitializerChecked(0) &&
```
Comment (xedin) [inline lib/Sema/TypeCheckStmt.cpp:88]: It is incorrect to use `0` here, instead `initContext->getBindingIndex()` should be used to find correct location.

**Review by xedin — CHANGES_REQUESTED** [review]

File: lib/Sema/TypeCheckStmt.cpp (hunk 1 above)
Comment (hank121314) [reply lib/Sema/TypeCheckStmt.cpp:88]: Many thanks for the quick review and explanation!
I will push the commit after local testing is passed!

Comment (xedin) [reply lib/Sema/TypeCheckStmt.cpp:88]: No worries!

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by hborla** [comment]
Hi @hank121314, thanks for digging into this!

> In [TypeCheckStorage.cpp](https://github.com/apple/swift/blob/bc43ced36a77806125b44a079f568bf149834552/lib/Sema/TypeCheckStorage.cpp#L2981-L2985), it will type-check default initializer and if there is a autoclosure in default initializer, its discriminator will also be set.

As you've discovered, this bit of code calls `typeCheckSynthesizedWrapperInitializer`, which will contextualize closures. What I'm curious about it your next point:

>And In [TypeCheckDeclPrimary.cpp](https://github.com/apple/swift/blob/bc43ced36a77806125b44a079f568bf149834552/lib/Sema/TypeCheckDeclPrimary.cpp#L2164-L2168), when visiting PatternBindingDecl it will type-check the autoclosure in default initializer again which might cause the [assertion error](https://github.com/apple/swift/blob/bc43ced36a77806125b44a079f568bf149834552/lib/Sema/TypeCheckStmt.cpp#L86).

Notice the comment above this bit of code that you linked:

```
        // Note that we don't contextualize the initializer for a property
        // with a wrapper, because the initializer will have been subsumed
        // by the backing storage property.
```

Why isn't the initializer skipped in this case based on the condition `!(PBD->getSingleVar() && PBD->getSingleVar()->hasAttachedPropertyWrapper()))`?

**Comment by hank121314** [comment]
Hi @hborla, Thanks for the review!

> Why isn't the initializer skipped in this case based on the condition `!(PBD->getSingleVar() && PBD->getSingleVar()->hasAttachedPropertyWrapper()))`?

For example:

```swift
@propertyWrapper
public class SR_15940Bar<Value> {
  public init(wrappedValue: @autoclosure () -> Value) {}
  public var wrappedValue: Value {}
}

class SR_15940 {
  @SR_15940Bar var a: Bool?
}
```

The property declaration `@SR_15940Bar var a: Bool?` will create another `PatternBindingDecl` which is `var _a: SR_15940Bar<Bool?>`(In [TypeCheckStorage.cpp](https://github.com/apple/swift/blob/bc43ced36a77806125b44a079f568bf149834552/lib/Sema/TypeCheckStorage.cpp#L2973)).

When visiting `var _a: SR_15940Bar<Bool?>`, it does not have any attached property wrapper. So `hasAttachedPropertyWrapper` will return `false`.

**Comment by xedin** [comment]
@hank121314 If I understand correctly `_a` initializer is synthesized while synthesizing one for `a`, so it would be great if you could figure out why exactly the initializer of `_a` gets checked twice, which is the underlying issue in this case. Your changes, albeit correct, fixed the symptom instead…

**Comment by hank121314** [comment]
For this test case, the initializer of `a` and the initializer of `_a`(its backing storage property) are the same.
In `TypeCheckStorage.cpp`, when the initializer of `a` gets checked,  initializer of `_a` will also get checked. 
And according to comments In `TypeCheckDeclPrimary.cpp`:

```swift
// Note that we don't contextualize the initializer for a property
// with a wrapper, because the initializer will have been subsumed
// by the backing storage property.
``` 

The initializer of `_a` will get checked again because it is a backing storage property.

IMHO, the fixes should be checking whether `_a` is a backing storage property and whether its initializer gets checked.
If `_a` is a backing storage property and it is already getting checked, skip the contextualize in `TypeCheckDeclPrimary.cpp`.

Thanks for pointing out if I have misunderstood anything!

**Comment by xedin** [comment]
@hank121314 That sounds like the right approach!

**Comment by hank121314** [comment]
Hi @xedin !

I am trying to add a property `isSynthesized` to `PatternBindingEntry` to check whether the initializer gets checked.
In `TypeCheckDeclPrimary.cpp`, It will check whether `_a` is a backing storage property. 
If it is a backing storage property, check whether its original `PatternBindingDecl` is synthesized.
If the original `PatternBindingDecl` is already synthesized skip it. 

Thanks for the review once again!

**Review by xedin — COMMENTED** [review]
I don't think you actually need `synthesized` flag since we already have `isInitializerChecked(unsigned)` and based on `PropertyWrapperInitializerInfoRequest::evaluate` - backing property always sets it, so really all you need to check is whether given variable is a backing property of some properly wrapper + assert that it's initializer is marked as checked and a `continue;`.

Does that make sense, @hborla?

**Comment by hank121314** [comment]
According to comments in `TypeCheckStorage.cpp`:

```
// Force the default initializer to come into existence, if there is one,
// and the wrapper doesn't provide its own.
```

`PropertyWrapperInitializerInfoRequest::evaluate` will only synthesize the initializer which does not have default initializer existence.
If the `PatternBindingDecl` have default initializer(ex. `@Lazy var foo = 17`, `@UnsafeMutablePointer(mutating: addressOfInt) var someInt`), its initiailizer will set as checked in `PropertyWrapperBackingPropertyTypeRequest::evaluate` by `TypeChecker::typeCheckPatternBinding`. But will not sythesize in `TypeCheckStorage.cpp`.

Thanks for pointing out if I have misunderstood anything!

**Comment by xedin** [comment]
So instead of an assert it would be a check?

**Comment by hank121314** [comment]
If the `PatternBindingDecl ` have a default initializer existence, even if `isInitializerChecked(unsigned)` returns true, It might not be synthesized yet.
So I think it might be unsafe to use `isInitializerChecked(unsigned)` instead of the `synthesized` flag.

**Comment by xedin** [comment]
If there is no initializer yet for a backing property `isInitializerChecked` should not return `true` unless it’s a bug though, isn’t?

**Comment by hank121314** [comment]
> If there is no initializer yet for a backing property `isInitializerChecked` should not return `true` unless it’s a bug though, isn’t?

Yes, In [PropertyWrapperInitializerInfoRequest::evaluate](https://github.com/apple/swift/blob/bc43ced36a77806125b44a079f568bf149834552/lib/Sema/TypeCheckStorage.cpp#L2992-L3002), it will set initializer for a backing property and `setInitializerChecked`. 
In [TypeCheckDeclPrimary.cpp](https://github.com/apple/swift/blob/bc43ced36a77806125b44a079f568bf149834552/lib/Sema/TypeCheckDeclPrimary.cpp#L2164-L2168), `isInitializerChecked` of a backing property will always return `true` , but it might not be synthesized yet. because `PropertyWrapperInitializerInfoRequest::evaluate` will only synthesize the initializer which does not have default initializer existence.

**Comment by xedin** [comment]
Sorry, you are making contradictory statements. When `PropertyWrapperInitializerInfoRequest::evaluate` sets initializer for a backing property its sets a completely type-checked initializer taken from the original property regardless whether it's a default one or not (non-default initializer should already be type-checked). The act of setting it on `pbd` in that method means that the initializer has been synthesized and we just want to skip that in `visitPatternBindingDecl`.

**Comment by xedin** [comment]
Also note that when it comes to `visitPatternBindingDecl` we don't really care about "synthesized" in a narrow sense as in "produced by the compiler", we only care that the initializer of a backed property has already been type-checked.

**Comment by hank121314** [comment]
> Also note that when it comes to `visitPatternBindingDecl` we don't really care about "synthesized" in a narrow sense as in "produced by the compiler", we only care that the initializer of a backed property has already been type-checked.

But if we skip the `TypeChecker::contextualizeInitializer` in `visitPatternBindingDecl` when `isInitializerChecked` return `true`,  some auto closure might not get contextualize.

Here is how I am trying to skip the `TypeChecker::contextualizeInitializer` in `visitPatternBindingDecl`:

```swift
if (!DC->isLocalContext() &&
    !(PBD->getSingleVar() &&
      PBD->getSingleVar()->hasAttachedPropertyWrapper())) {
  auto *initContext =
      cast_or_null<PatternBindingInitializer>(PBD->getInitContext(i));
  if (initContext) {
    // Check whether `var` is a backing storage property and its
    // initializer is already checked.
    bool shouldSynthesized = true;
    if (auto var = PBD->getSingleVar()) {
      if (auto kind =
              var->getPropertyWrapperSynthesizedPropertyKind()) {
        if (kind == PropertyWrapperSynthesizedPropertyKind::Backing) {
          assert(PBD->isInitializerChecked(i));
          shouldSynthesized = false;
        }
      }
    }
    if (shouldSynthesized) {
      TypeChecker::contextualizeInitializer(initContext, init);
    }
    checkInitializerActorIsolation(initContext, init);
    TypeChecker::checkInitializerEffects(initContext, init);
  }
}
```

And the failed test example when auto closure is not getting contextualize:

```swift
// RUN: %target-swift-frontend -emit-ir %s

@propertyWrapper
public class SR_15940Bar<Value> {
    private var _value: Value

    public var wrappedValue: Value {
        get { _value }
        set {
            _value = newValue
        }
    }
    public init(wrappedValue value: @autoclosure @escaping () -> Value) {
        self._value = value()
    }
}

// SR-15940
class SR_15940_A {
    @SR_15940Bar var a: Bool = false
}
```

Thank you for all your assistance ❤️ !

**Comment by xedin** [comment]
Then the question is why an initializer that is marked as type-checked is not getting contextualized although it should be.

**Comment by xedin** [comment]
Meaning `typeCheckSynthesizedWrapperInitializer` does contextualization but why it’s not happening when there is explicit initializer like in your example with `@SR_15940Bar var a: Bool = false`?…

**Comment by hank121314** [comment]
> Meaning `typeCheckSynthesizedWrapperInitializer` does contextualization but why it’s not happening when there is explicit initializer like in your example with `@SR_15940Bar var a: Bool = false`?…

If there is no explicit initializer(ex. `@SR_15940Bar var a: Bool?`), it will satisfy these conditions in [TypeCheckStorage.cpp](https://github.com/apple/swift/blob/bc43ced36a77806125b44a079f568bf149834552/lib/Sema/TypeCheckStorage.cpp#L2977-L2979) and do the contextualization  with `typeCheckSynthesizedWrapperInitializer`.
But if there is explicit initializer, it will not satisfy `!parentPBD->isInitialized(patternNumber)`, because it already has an initializer which is set by `ParseDecl`.

**Comment by xedin** [comment]
The question I am asking is why isn’t explicit initializer contextualized before `PropertyWrapperInitializerInfoRequest::evaluate` if it is considered to be fully type-checked…

**Comment by hank121314** [comment]
> The question I am asking is why isn’t explicit initializer contextualized before `PropertyWrapperInitializerInfoRequest::evaluate` if it is considered to be fully type-checked…

In this test case, the initializer is set as fully type-checked in [TypeCheckConstraints.cpp](https://github.com/apple/swift/blob/main/lib/Sema/TypeCheckConstraints.cpp#L814) when doing `visitClassDecl`. But it is not contextualized yet.

**Comment by xedin** [comment]
It seems reasonable to contextualize explicit initializers in `PropertyWrapperInitializerInfoRequest::evaluate` then too? 
Alternatively, `typeCheckSynthesizedWrapperInitializer` can get a flag to indicate whether it should run the checks or not and it would only be turned on [in case where backed property gets independent initializer](https://github.com/apple/swift/blob/main/lib/Sema/TypeCheckStorage.cpp#L3070). This way the behavior of relying on backed property to run contextualization in `visitPatternBindingDecl` would be made consistent between default and non-default initializers.

**Comment by hank121314** [comment]
> Alternatively, `typeCheckSynthesizedWrapperInitializer` can get a flag to indicate whether it should run the checks or not and it would only be turned on [in case where backed property gets independent initializer](https://github.com/apple/swift/blob/main/lib/Sema/TypeCheckStorage.cpp?rgh-link-date=2022-06-04T16%3A41%3A02Z#L3070). This way the behavior of relying on backed property to run contextualization in `visitPatternBindingDecl` would be made consistent between default and non-default initializers.

This solution sounds great!
Many thanks for your assistance and detailed explanation!
I will update the PR after the local testing is passed!

**Comment by hank121314** [comment]
Hi @xedin !

I have updated the PR!

> typeCheckSynthesizedWrapperInitializer can get a flag to indicate whether it should run the checks or not and it would only be turned on [in case where backed property gets independent initializer](https://github.com/apple/swift/blob/main/lib/Sema/TypeCheckStorage.cpp?rgh-link-date=2022-06-04T16%3A41%3A02Z#L3070).

For this test case:

```swift
@propertyWrapper
struct SR_15940Bar {
  var wrappedValue: Int { 0 }
}
struct SR_15940_B {
  func a() {
    @SR_15940Bar var b: Int
  }
}
```

I also notice that the flag should be turned on [in case where property wrapper has defaultInit and it is a local variable](https://github.com/apple/swift/blob/efc66c7af6c394a9fd297a0edf11630775e66039/lib/Sema/TypeCheckStorage.cpp#L3000). ([visitingPatternBindingDecl will filter out local variables](https://github.com/apple/swift/blob/efc66c7af6c394a9fd297a0edf11630775e66039/lib/Sema/TypeCheckDeclPrimary.cpp#L2174)).

Many thanks for the review once again!

**Comment by xedin** [comment]
Thank you! I'll take a look tomorrow.

File: lib/Sema/TypeCheckStorage.cpp [hunk 2]
```diff
@@ -2689,7 +2689,8 @@ static VarDecl *synthesizePropertyWrapperProjectionVar(
 }
 
 static void typeCheckSynthesizedWrapperInitializer(VarDecl *wrappedVar,
-                                                   Expr *&initializer) {
+                                                   Expr *&initializer,
+                                                   bool contextualize = false) {
```
Comment (xedin) [inline lib/Sema/TypeCheckStorage.cpp:2693]: Let's not default this new parameter, instead specify this directly in every use.

File: lib/Sema/TypeCheckStorage.cpp [hunk 3]
```diff
@@ -2997,7 +3003,7 @@ PropertyWrapperInitializerInfoRequest::evaluate(Evaluator &evaluator,
         // FIXME: Record this expression somewhere so that DI can perform the
         // initialization itself.
         Expr *defaultInit = nullptr;
-        typeCheckSynthesizedWrapperInitializer(var, defaultInit);
+        typeCheckSynthesizedWrapperInitializer(var, defaultInit, dc->isLocalContext());
```
Comment (xedin) [inline lib/Sema/TypeCheckStorage.cpp:3006]: Why is `dc->isLocalContext()` important here?

File: lib/Sema/TypeCheckStorage.cpp [hunk 4]
```diff
@@ -3067,7 +3073,7 @@ PropertyWrapperInitializerInfoRequest::evaluate(Evaluator &evaluator,
              !var->getName().hasDollarPrefix()) {
     wrappedValueInit = PropertyWrapperValuePlaceholderExpr::create(
         ctx, var->getSourceRange(), var->getType(), /*wrappedValue=*/nullptr);
-    typeCheckSynthesizedWrapperInitializer(var, wrappedValueInit);
+    typeCheckSynthesizedWrapperInitializer(var, wrappedValueInit, true);
```
Comment (xedin) [inline lib/Sema/TypeCheckStorage.cpp:3076]: Nit: please use `/*contextualize=*/true`, that's the style for literals we use.

File: test/Sema/property_wrappers.swift [hunk 5]
```diff
@@ -47,3 +47,37 @@ struct TestInitSubscript {
...
+  @SR_15940Bar var a: Bool?
+}
+
+// CHECK-LABEL: struct_decl{{.*}}SR_15940_B
+struct SR_15940_B {
+  // CHECK:      argument_list implicit labels=wrappedValue:
+  // CHECK-NEXT:   argument label=wrappedValue
+  // CHECK-NEXT:     autoclosure_expr implicit type='() -> Bool' location={{.*}}.swift:[[@LINE+2]]:30 range=[{{.+}}] discriminator=0 captures=(<opaque_value> ) escaping
+  // CHECK:            autoclosure_expr implicit type='() -> Bool' location={{.*}}.swift:[[@LINE+1]]:30 range=[{{.+}}] discriminator=1 escaping
+  @SR_15940Bar var b: Bool = false
```
Comment (xedin) [inline test/Sema/property_wrappers.swift:82]: Could you please also add the last example you mentioned that requires contextualization?

File: lib/Sema/TypeCheckStorage.cpp (hunk 3 above)
Comment (hank121314) [reply lib/Sema/TypeCheckStorage.cpp:3006]: Because visitPatternBindingDecl [will filter out local variables](https://github.com/apple/swift/blob/efc66c7af6c394a9fd297a0edf11630775e66039/lib/Sema/TypeCheckDeclPrimary.cpp#L2174), there is a need to contextualize backed property here.

File: test/Sema/property_wrappers.swift (hunk 5 above)
Comment (hank121314) [reply test/Sema/property_wrappers.swift:82]: The last example will only affect `SILGen`, I have added a test in `SILGen/property_wappers.swift`.

File: lib/Sema/TypeCheckStorage.cpp (hunk 3 above)
Comment (xedin) [reply lib/Sema/TypeCheckStorage.cpp:3009]: Ah sure!

File: test/Sema/property_wrappers.swift (hunk 5 above)
Comment (xedin) [reply test/Sema/property_wrappers.swift:82]: Thank you!

File: lib/Sema/TypeCheckStorage.cpp [hunk 6]
```diff
@@ -2705,6 +2706,11 @@ static void typeCheckSynthesizedWrapperInitializer(VarDecl *wrappedVar,
 
   initializer = result->getAsExpr();
 
+  // Contextualize the initializer which is a local variable with defaultInit or
+  // gets an independent initializer. The rest of initializer contextualizing
+  // will be done in visitPatternBindingDecl.
```
Comment (hborla) [inline lib/Sema/TypeCheckStorage.cpp:2711]: After this return statement, the function also checks actor isolation and initializer effects. Do we have tests to make sure the cases where `contextualize` is `false` still perform actor isolation and effects checking? We might also want to call the parameter something else since it skips more than contextualizing closures.

Comment (hborla) [inline lib/Sema/TypeCheckStorage.cpp:2711]: After this return statement, the function also checks actor isolation and initializer effects. Do we have tests to make sure the cases where `contextualize` is `false` still perform actor isolation and effects checking? We might also want to call the parameter something else since it skips more than contextualizing closures.

Comment (xedin) [reply lib/Sema/TypeCheckStorage.cpp:2711]: That's a good question. @hank121314 You can comment out the logic in `visitPatternBinding` and see if we get any test failures from that related to property wrappers.

**Comment by hank121314** [comment]
> We might also want to call the parameter something else since it skips more than contextualizing closures.

Agree! Is there any recommendation about the parameter name?

> Do we have tests to make sure the cases where `contextualize` is false still perform actor isolation and effects checking?

There are two kinds of situations that make `contextualize` false.

1. [Forcing the default initializer to come into existence.](https://github.com/hank121314/swift/blob/d0ef4d2718687ef0fae8833b498942b44910c148/lib/Sema/TypeCheckStorage.cpp#L2988-L2989) In this situation, actor isolation and effects checking will be perform in `visitPatternBinding`, if `dc->isLocalContext` returns `false`. If `dc->isLocalContext` returns `true`, actor isolation and effects checking will be perform in `TypeCheckFunctionBodyRequest`.

Test example:

```swift
@propertyWrapper
public class SR_15940Bar<Value> {
  private var _value: Value

  public var wrappedValue: Value {
    get { _value }
    set {
      _value = newValue
    }
  }

  public init(wrappedValue value: @autoclosure @escaping () -> Value) {
    self._value = value()
  }
}

struct SR_15940_A {
  // If `dc->isLocalContext` returns `false`, actor isolation and effects checking will be perform in `visitPatternBinding`.
  @SR_15940Bar var a: Bool?
  func b() {
    // If `dc->isLocalContext` returns `true`, actor isolation and effects checking will be perform in `TypeCheckFunctionBodyRequest`.
    @SR_15940Bar var c: Bool?
  }
}
```

2. [`PatternBindingDecl` is not initialized, wrapper has defaultInit and `dc->isLocalContext` is false.](https://github.com/hank121314/swift/blob/d0ef4d2718687ef0fae8833b498942b44910c148/lib/Sema/TypeCheckStorage.cpp#L3009) In this situation, actor isolation and effects checking will be perform in `visitPatternBinding`.

Test example:

```swift
@propertyWrapper
struct SR_15940Foo {
  var wrappedValue: Int { 0 }
}
struct SR_15940 {
  @SR_15940Foo var a: Int
}
```

**Comment by hank121314** [comment]
I have added a test to [Concurrency/global_actor_inference.swift](https://github.com/apple/swift/pull/58956/commits/c05afe20f0dc40e3aa0ed7ed1566a8a58993488d#diff-3d48dcdcfe534d9c5bd0f631b0a3ca016cd023e67ff8db66b9d93338d43b5a66) to make sure actor isolation and effects checking is performed in the second situation as mentioned above. 
As for the first situation, tests are added in [Sema/property_wrappers.swift](https://github.com/hank121314/swift/blob/c05afe20f0dc40e3aa0ed7ed1566a8a58993488d/test/Sema/property_wrappers.swift#L51-L83) and [SILGen/property_wrappers.swift](https://github.com/hank121314/swift/blob/c05afe20f0dc40e3aa0ed7ed1566a8a58993488d/test/SILGen/property_wrappers.swift#L960-L986).
Please let me know if anything is missing.

Thanks for the review!

**Review by hborla — APPROVED** [review]
Thank you!

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
@swift-ci please test source compatibility

**Review by xedin — APPROVED** [review]
