### PR TITLE
[cxx-interop] Disable debug info in synthesized C++ methods

### LINKED ISSUE #79670: Compiler crash passing a C++ class with inline destructor to pure virtual method
### Description

swiftc crashes when trying to pass a C++ class with an inline destructor to a virtual C++ class method, when compiling with -g.

Originally found with Qt's QString which also has an inline destructor.

```
error: compile command failed due to signal 6 (use -v to see invocation)
inlinable function call in a function with debug info must have a !dbg location
  call void @_ZN6PassedD2Ev(ptr noundef nonnull align 1 dereferenceable(1) %5) #8
inlinable function call in a function with debug info must have a !dbg location
  call void @_ZN6PassedD2Ev(ptr noundef nonnull align 1 dereferenceable(1) %5) #8
```

### Reproduction

Compile with
```
% swiftc -g -swift-version 6 -cxx-interoperability-mode=default -import-objc-header header.h main.swift
```

main.swift
```swift
func f(d: CppReceiver, s: Passed) {
  d.callMe(s)
}
```

header.h
```cpp
#define IMMORTAL_REF                               \
    __attribute__((swift_attr("import_as_ref")))   \
    __attribute__((swift_attr("retain:immortal"))) \
    __attribute__((swift_attr("release:immortal")))

struct Passed {
    inline ~Passed() {}
};

struct IMMORTAL_REF CppReceiver {
    virtual void callMe(Passed str) = 0;
};
```

### Stack dump

```text
Stack dump:
0.      Program arguments: /usr/lib64/swift-6.0.3/usr/bin/swift-frontend -frontend -c -primary-file test.swift -target x86_64-unknown-linux-gnu -disable-objc-interop -cxx-interoperability-mode=default -color-diagnostics -g -debug-info-format=dwarf -dwarf-version=4 -swift-version 6 -empty-abi-descriptor -resource-dir /usr/lib64/swift-6.0.3/usr/lib/swift -enable-anonymous-context-mangled-names -file-compilation-dir /Users/saiko -import-objc-header /tmp/TemporaryDirectory.KX2QMZ/header.pch -module-name test -plugin-path /usr/lib64/swift-6.0.3/usr/lib/swift/host/plugins -plugin-path /usr/lib64/swift-6.0.3/usr/local/lib/swift/host/plugins -o /tmp/TemporaryDirectory.KX2QMZ/test-2.o
1.      Swift version 6.0.3 (swift-6.0.3-RELEASE)
2.      Compiling with the current language version
 #0 0x0000557ff20eb538 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib64/swift-6.0.3/usr/bin/swift-frontend+0x629d538)
 #1 0x0000557ff20e94ee llvm::sys::RunSignalHandlers() (/usr/lib64/swift-6.0.3/usr/bin/swift-frontend+0x629b4ee)
 #2 0x0000557ff20ebbb8 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007f63df868cb0 (/usr/lib64/libc.so.6+0x3ccb0)
 #4 0x00007f63df8bf07c (/usr/lib64/libc.so.6+0x9307c)
 #5 0x00007f63df868b86 raise (/usr/lib64/libc.so.6+0x3cb86)
 #6 0x00007f63df85128b abort (/usr/lib64/libc.so.6+0x2528b)
 #7 0x0000557fecf786b3 (/usr/lib64/swift-6.0.3/usr/bin/swift-frontend+0x112a6b3)
 #8 0x0000557ff20486f2 llvm::report_fatal_error(llvm::Twine const&, bool) (/usr/lib64/swift-6.0.3/usr/bin/swift-frontend+0x61fa6f2)
 #9 0x0000557ff20485d6 (/usr/lib64/swift-6.0.3/usr/bin/swift-frontend+0x61fa5d6)
#10 0x0000557ff1e16d4c (/usr/lib64/swift-6.0.3/usr/bin/swift-frontend+0x5fc8d4c)
#11 0x0000557fed21f23d llvm::detail::PassModel<llvm::Module, llvm::VerifierPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) IRGen.cpp:0:0
#12 0x0000557ff1deb2c2 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/lib64/swift-6.0.3/usr/bin/swift-frontend+0x5f9d2c2)
#13 0x0000557fed215281 swift::performLLVMOptimizations(swift::IRGenOptions const&, llvm::Module*, llvm::TargetMachine*, llvm::raw_pwrite_stream*) (/usr/lib64/swift-6.0.3/usr/bin/swift-frontend+0x13c7281)
#14 0x0000557fed216668 swift::performLLVM(swift::IRGenOptions const&, swift::DiagnosticEngine&, llvm::sys::SmartMutex<false>*, llvm::GlobalVariable*, llvm::Module*, llvm::TargetMachine*, llvm::StringRef, llvm::vfs::OutputBackend&, swift::UnifiedStatsReporter*) (/usr/lib64/swift-6.0.3/usr/bin/swift-frontend+0x13c8668)
#15 0x0000557feccf7010 generateCode(swift::CompilerInstance&, llvm::StringRef, llvm::Module*, llvm::GlobalVariable*) FrontendTool.cpp:0:0
#16 0x0000557feccf2f04 performCompileStepsPostSILGen(swift::CompilerInstance&, std::unique_ptr<swift::SILModule, std::default_delete<swift::SILModule>>, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*) FrontendTool.cpp:0:0
#17 0x0000557feccf1c07 swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) (/usr/lib64/swift-6.0.3/usr/bin/swift-frontend+0xea3c07)
#18 0x0000557feccf43c8 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) FrontendTool.cpp:0:0
#19 0x0000557feccf38b5 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) (/usr/lib64/swift-6.0.3/usr/bin/swift-frontend+0xea58b5)
#20 0x0000557fecaa34ca swift::mainEntry(int, char const**) (/usr/lib64/swift-6.0.3/usr/bin/swift-frontend+0xc554ca)
#21 0x00007f63df8531ae (/usr/lib64/libc.so.6+0x271ae)
#22 0x00007f63df853269 __libc_start_main (/usr/lib64/libc.so.6+0x27269)
#23 0x0000557fecaa29a5 _start (/usr/lib64/swift-6.0.3/usr/bin/swift-frontend+0xc549a5)
```

### Expected behavior

It compiles

### Environment

Swift version 6.0.3 (swift-6.0.3-RELEASE)
Target: x86_64-unknown-linux-gnu

### Additional information

Possible workaround includes making the virtual method take the parameter by reference, i.e. const Passed &.

### PR DESCRIPTION
**Pull request by susmonteiro**
Generating debug info for synthesized C++ methods was resulting in a crash due to missing `!dbg` on a call to destructors inside the synthesized body of these methods. 
We disable debug info for these synthesized C++ methods because `!dbg` wouldn't point to real source locations anyways.

Fixes #79670

rdar://141167229

### CODE REVIEW

**Review by egorzhdan — COMMENTED** [review]
Thanks! Could you please describe the problem that this is fixing in the commit message?

**Comment by j-hui** [comment]
Does this fix https://github.com/swiftlang/swift/issues/79670 ?

File: lib/ClangImporter/SwiftDeclSynthesizer.cpp [hunk 1]
```diff
@@ -2106,6 +2106,7 @@ clang::CXXMethodDecl *SwiftDeclSynthesizer::synthesizeCXXForwardingMethod(
   newMethod->setImplicit();
   newMethod->setImplicitlyInline();
   newMethod->setAccess(clang::AccessSpecifier::AS_public);
+  newMethod->addAttr(clang::NoDebugAttr::CreateImplicit(clangCtx));
```
Comment (Xazax-hun) [inline lib/ClangImporter/SwiftDeclSynthesizer.cpp:2109]: I am a bit curious what is going on here. We are specifying the source range for the created method here, so I would suspect codegen to generate the right debug info based on that. Or is this due to missing source locations in the body of the function? Should we add this attribute to other synthesized functions as well?

File: test/Interop/Cxx/class/inheritance/virtual-methods.swift [hunk 2]
```diff
@@ -1,5 +1,6 @@
 // RUN: %target-run-simple-swift(-I %S/Inputs -cxx-interoperability-mode=swift-5.9)
 // RUN: %target-run-simple-swift(-I %S/Inputs -cxx-interoperability-mode=swift-6)
+// RUN: %target-run-simple-swift(-g -I %S/Inputs -cxx-interoperability-mode=swift-6)
```
Comment (j-hui) [inline test/Interop/Cxx/class/inheritance/virtual-methods.swift:3]: Why not test `-cxx-interoperability-mode=default` here? Not that there's anything wrong with testing `swift-6` (all the interop modes are equivalent as far as I can tell), but `default` seems to be the default recommendation.

File: lib/ClangImporter/SwiftDeclSynthesizer.cpp (hunk 1 above)
Comment (egorzhdan) [reply lib/ClangImporter/SwiftDeclSynthesizer.cpp:2109]: > Should we add this attribute to other synthesized functions as well?

Yeah I think so, but let's make it a separate change to make this diff smaller and easier to cherry-pick.

File: test/Interop/Cxx/class/inheritance/virtual-methods.swift (hunk 2 above)
Comment (susmonteiro) [reply test/Interop/Cxx/class/inheritance/virtual-methods.swift:3]: You're right, that probably makes more sense. I'm testing with `-cxx-interoperability-mode=swift-6` because https://github.com/swiftlang/swift/issues/79670 explicitly says to reproduce on this version. I'll check if this succeeds in both versions and, if so, will make the change you suggest

**Comment by susmonteiro** [comment]
@swift-ci please smoke test

File: lib/ClangImporter/SwiftDeclSynthesizer.cpp (hunk 1 above)
Comment (susmonteiro) [reply lib/ClangImporter/SwiftDeclSynthesizer.cpp:2109]: > Or is this due to missing source locations in the body of the function?

Yes, exactly - particularly on calls to destructors in the body of the synthesized function. I've updated the PR description.

**Review by egorzhdan — APPROVED** [review]
LGTM, thanks!

**Review by Xazax-hun — APPROVED** [review]

**Comment by susmonteiro** [comment]
@swift-ci please smoke test

**Review by j-hui — APPROVED** [review]
LGTM!

**Comment by compnerd** [comment]
@susmonteiro can you please ensure that there is a filed issue that tracks the unsupported case for Windows?
