### PR TITLE
[SymbolGraphGen] Refactor export-import logic

### LINKED ISSUE #60771: "Symbol with identifier 's:So9NSDecimala10FoundationE11FormatStyleV8CurrencyV' couldn't be found" error
### Description

Since Xcode 14 beta 4, I haven't been able to build the documentation for the following project:

https://github.com/pointfreeco/combine-schedulers

I get the following errors:

> error build: Symbol with identifier 's:So9NSDecimala10FoundationE11FormatStyleV8CurrencyV' couldn't be found
> error build: Symbol with identifier 's:So9NSDecimala10FoundationE11FormatStyleV7PercentV' couldn't be found

In case this is an Xcode issue I filed feedback FB11088354.

Is there a workaround that I can take advantage of to get documentation building in Xcode?

### Checklist

- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected Behavior

I expect the documentation to compile.

### Actual behavior

It fails to compile.

### Steps To Reproduce

1. Clone `https://github.com/pointfreeco/combine-schedulers`
2. Open in Xcode 14 beta 4, 5, or 6
3. Build documentation

### Swift-DocC Version Information

Version bundled in Xcode 14

### Swift Compiler Version Information

```shell
swift-driver version: 1.62.3 Apple Swift version 5.7 (swiftlang-5.7.0.123.8 clang-1400.0.29.50)
Target: arm64-apple-macosx12.0
```

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
Resolves rdar://98808363, fixes #60771

This PR fixes a handful of rough edges surrounding re-exported modules, extensions, and Clang symbols:

1. Re-exporting a module doesn't include that module's Clang symbols.
2. If a module renames a Clang symbol in Swift via API notes, children of that symbol can be incorrectly sorted into an extension graph.
3. Tertiary chains of extensions and module re-exports can incorrectly sort the third- and lower-level symbols into the main graph instead of an extension.

These issues primarily occur when a module re-exports Foundation, but the patterns can be recreated outside of Foundation.

### CODE REVIEW

File: test/SymbolGraph/ClangImporter/ExportedImport.swift [hunk 1]
```diff
@@ -0,0 +1,12 @@
+// RUN: %empty-directory(%t)
+// RUN: cp -r %S/Inputs/ExportedImport/ObjcProperty.framework %t
+// RUN: %target-swift-frontend(mock-sdk: %clang-importer-sdk) -enable-objc-interop -emit-module -o %t/ObjcProperty.framework/Modules/ObjcProperty.swiftmodule/%target-swiftmodule-name -import-underlying-module -F %t -module-name ObjcProperty %S/Inputs/ExportedImport/A.swift
```
Comment (franklinsch) [inline test/SymbolGraph/ClangImporter/ExportedImport.swift:3]: Is it worth also having a separate test for `swift-symbolgraph-extract`?

**Review by franklinsch — APPROVED** [review]

File: test/SymbolGraph/ClangImporter/ExportedImport.swift (hunk 1 above)
Comment (QuietMisdreavus) [reply test/SymbolGraph/ClangImporter/ExportedImport.swift:3]: `swift-symbolgraph-extract` doesn't have support for processing re-exports (https://github.com/apple/swift/issues/59920) so any tests i add for that will just confirm that the symbols don't exist.
