### PR TITLE
[Sema]: fix @discardableResult interaction with implicit @Sendable conversions

### LINKED ISSUE #83463: @discardableResult on global actor-isolated function is ignored
### Description

`@discardableResult` stops working when function is isolated to a global actor.

Reproducible in Swift 5 and Swift 6 modes. Does not reproduce when functions are isolated to an actor instance.

### Reproduction

```swift
// Order of attributes does not matter
// Removing isolation attribute fixes the error
@discardableResult @MainActor
func foo() -> () -> Void {
    return {}
}

@MainActor
func test() {
    foo() // error: function is unused
}
```

### Expected behavior

Code should compiler without error

### Environment

```
swift-driver version: 1.120.5 Apple Swift version 6.1.2 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
Target: arm64-apple-macosx15.0
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jamieQ**
Updates existing diagnostic handling to look through function conversions when suppressing diagnostics for unused functions that are return values from callees marked with `@discardableResult`.

Resolves https://github.com/swiftlang/swift/issues/83463

### CODE REVIEW

**Comment by jamieQ** [comment]
@swift-ci please smoke test

**Comment by jamieQ** [comment]
cc @xedin – lmk what you think if/when you have a chance please!

File: lib/Sema/TypeCheckStmt.cpp [hunk 1]
```diff
@@ -1886,7 +1886,25 @@ void TypeChecker::checkIgnoredExpr(Expr *E) {
...
+      ///
+      /// @MainActor
+      /// func test() {
+      ///   foo() // implicitly converted to `@MainActor @Sendable () -> () ->
+      ///   Void`
+      /// }
+      /// ```
+      /// So we look through such things when trying to locate the called value.
+      if (auto *calledValue =
+              Fn->getCalledValue(/*skipFunctionConversions*/ true)) {
```
Comment (ktoso) [inline lib/Sema/TypeCheckStmt.cpp]: nitpick on the formatting that we usually do 
```suggestion
              Fn->getCalledValue(/*skipFunctionConversions=*/true)) {
```

**Review by ktoso — APPROVED** [review]
Looks good to me -- unless @xedin has some better approach in mind for the fix

**Review by xedin — APPROVED** [review]
Makes sense to me!

**Comment by jamieQ** [comment]
@swift-ci please smoke test

**Comment by jamieQ** [comment]
@ktoso @xedin thanks for the reviews! Would one of you please merge when you are able?

**Comment by ktoso** [comment]
Merged, thanks for the fix and ping!
