### PR TITLE
[AutoDiff] Lookup for custom derivatives in non-primary source files

### LINKED ISSUE #55170: [SR-14235] [AutoDiff] Cross-file differentiation error: derivative configuration not registered for `@derivative` attribute
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14235      |
   |Radar             | None         |
   |Original Reporter | @dan-zheng      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, AutoDiff        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 1c36955f37f690185a211308ac4034a9

  </details>

**Issue Description:**

``` swift
// a.swift
@differentiable
func crossFileDerivativeAttr<T: DifferentiableTensorProtocol>(
  _ input: T
) -> T {
  return input.identityDerivativeAttr()
}
```

``` swift
import _Differentiation

protocol DifferentiableTensorProtocol: Differentiable {}

extension DifferentiableTensorProtocol {
  func identityDerivativeAttr() -> Self { self }

  // Test cross-file `@derivative` attribute.
  @derivative(of: identityDerivativeAttr)
  func vjpIdentityDerivativeAttr() -> (
    value: Self, pullback: (TangentVector) -> TangentVector
  ) {
    fatalError()
  }
}
```

The error occurs because `AbstractFunctionDecl::getDerivativeConfigurations` is not sufficiently requestified to type-check `@derivative` attributes in other files.

``` java
$ swiftc a.swift b.swift
a.swift:20:16: error: expression is not differentiable
  return input.identityDerivativeAttr()
               ^
a:20:16: note: cannot differentiate functions that have not been marked '@differentiable' and that are defined in other files
  return input.identityDerivativeAttr()
               ^
```

### PR DESCRIPTION
**Pull request by asl**
This is done after typecheck is finished for the primary source.

This registers all custom derivatives before autodiff transformations and makes them available to them.

Fully resolves #55170

### CODE REVIEW

**Comment by asl** [comment]
Note that this PR effectively makes large part of https://github.com/apple/swift/commit/a1e138b2af332baa8941b676a7626392feebce25 obsolete and, more importantly, removes cycle-breaking hacks as they are not needed anymore

**Comment by asl** [comment]
@swift-ci please test

File: test/AutoDiff/Sema/DerivativeRegistrationCrossFile/main.swift [hunk 1]
```diff
@@ -0,0 +1,9 @@
+// RUN: %target-swift-frontend -emit-sil -verify -primary-file %s %S/Inputs/derivatives.swift -module-name main -o /dev/null
+
+import _Differentiation
+
+@differentiable(reverse)
+func clamp(_ value: Double, _ lowerBound: Double, _ upperBound: Double) -> Double {
+    // No error expected
+    return max(min(value, upperBound), lowerBound)
+}
```
Comment (philipturner) [inline test/AutoDiff/Sema/DerivativeRegistrationCrossFile/main.swift:9]:
```suggestion
}

```

**Review by philipturner — CHANGES_REQUESTED** [review]

File: test/AutoDiff/Sema/DerivativeRegistrationCrossFile/main.swift (hunk 1 above)
Comment (philipturner) [reply test/AutoDiff/Sema/DerivativeRegistrationCrossFile/main.swift:9]: Add newline to end of file

**Comment by asl** [comment]
@swift-ci please test

File: test/AutoDiff/Sema/DerivativeRegistrationCrossFile/main.swift [hunk 2]
```diff
@@ -0,0 +1,9 @@
+// RUN: %target-swift-frontend -emit-sil -verify -primary-file %s %S/Inputs/derivatives.swift -module-name main -o /dev/null
+
+import _Differentiation
+
+@differentiable(reverse)
+func clamp(_ value: Double, _ lowerBound: Double, _ upperBound: Double) -> Double {
+    // No error expected
+    return max(min(value, upperBound), lowerBound)
```
Comment (dan-zheng) [inline test/AutoDiff/Sema/DerivativeRegistrationCrossFile/main.swift:8]: Could you please clarify the functionality added by this PR on top of https://github.com/apple/swift/pull/58644?

My understanding:
- https://github.com/apple/swift/pull/58644 adds an option for non-primary-file derivative resolution to `AbstractFunctionDecl::getDerivativeFunctionConfigurations`, as well as original declaration serialization for `@derivative` attribute.
- This PR moves the non-primary-file derivative resolution logic to `CompilerInstance::finishTypeChecking` instead, visiting each source file.
  - This resolves the "cross-file derivative not found" issue in https://github.com/apple/swift/issues/55170.
  - Does this also avoid circular requests?
  - Are there other implications to this new resolution-triggering condition? Ostensibly, to fix https://github.com/apple/swift/issues/55170, this PR is causing derivative resolution to happen in more cases than previously in https://github.com/apple/swift/pull/58644.

**Review by dan-zheng — APPROVED** [review]
Looks good, thanks!

File: lib/Frontend/Frontend.cpp [hunk 3]
```diff
@@ -1186,11 +1186,31 @@ bool CompilerInstance::forEachFileToTypeCheck(
...
 void CompilerInstance::finishTypeChecking() {
   forEachFileToTypeCheck([](SourceFile &SF) {
     performWholeModuleTypeChecking(SF);
     return false;
   });
+
+  forEachSourceFile([](SourceFile &SF) {
+    loadDerivativeConfigurations(SF);
+    return false;
+  });
```
[the remark this answers is not in the document]
Comment (asl) [reply lib/Frontend/Frontend.cpp:1213]: Right. And any custom derivative declaration is typechecked. Regardless whether the derivative is used or not. This is quite a big hammer, but for now I do not see other way to "expose" them.

Old approach had its own pros and cons:
 - Pros: other source files were visited only when derivative was needed. And only those required were typechecked
 - Cons: other source files were visited on every derivative lookup. And we had typechecking cycles.

File: test/AutoDiff/Sema/DerivativeRegistrationCrossFile/main.swift (hunk 2 above)
Comment (asl) [reply test/AutoDiff/Sema/DerivativeRegistrationCrossFile/main.swift:8]: 1. Yes, as I mentioned, this avoids circular requests. As custom derivative resolution is decoupled from obtaining derivatives configurations. Also, after this PR the differentiation will not trigger typechecking
2. After this PR indeed, we lookup and register all explicit derivates regardless of their original function and regardless whether this function is used. The nice side effect is that we will error out in case of `@derivative(of: foo)` with `foo` not defined anywhere.
3. Effectively this resolves the following cross-file derivate requests:
   *  File A.swift is using (wants a derivative of) function from B.swift with derivatives defined in C.swift
   * The important special case is when B.swift is effectively a part of stdlib (like in the testcase). Here C.swift is a non-primary source but we have no way to resolve the derivative in other way as there is no mechanism to "pull" anything from C.swift – there are simply no forward dependency edges in the dependency graph, only backward.

File: lib/Sema/TypeChecker.cpp [hunk 4]
```diff
@@ -375,6 +375,44 @@ void swift::performWholeModuleTypeChecking(SourceFile &SF) {
   }
 }
 
+void swift::loadDerivativeConfigurations(SourceFile &SF) {
+  if (!isDifferentiableProgrammingEnabled(SF))
```
Comment (slavapestov) [inline lib/Sema/TypeChecker.cpp:379]: When is this true? The recursive walk over the AST in secondary files is going to trigger delayed parsing in all nominal types and extensions, which will impact performance in non-WMO builds.

**Review by slavapestov — CHANGES_REQUESTED** [review]

File: lib/Sema/TypeChecker.cpp (hunk 4 above)
Comment (dan-zheng) [reply lib/Sema/TypeChecker.cpp:379]: `isDifferentiableProgrammingEnabled` returns true only for files that have `import _Differentiation`, so I hope there would be negligible impact for other files.

Comment (asl) [reply lib/Sema/TypeChecker.cpp:379]: @slavapestov This is true when there is an `import _Differentiation` in the given SourceFile (so, corresponding ImportDecl).

What is the viable alternative? Essentially the task is: for function `f` find all functions that has `@derivative(of : f)` attribute specified. Both in primary and secondary sources.

Comment (slavapestov) [reply lib/Sema/TypeChecker.cpp:379]: > What is the viable alternative? Essentially the task is: for function f find all functions that has @derivative(of : f) attribute specified. Both in primary and secondary sources.

The only real alternative would be to change the design of this attribute so that this kind of search does not have to be performed. By definition, it requires parsing all source files ahead of time which is incompatible with our strategy of skipping bodies of nominal types and extensions in secondary files.

Comment (asl) [reply lib/Sema/TypeChecker.cpp:379]: Yeah. Though the alternative design would not easily allow "pluggable" derivatives.... (see https://github.com/apple/swift/pull/58644#issuecomment-1119158991 for the design explanation, etc. by @dan-zheng )

**Comment by philipturner** [comment]
I wanted to make the #59467 regression test as a "suggestion" in a GitHub review, but it's too large to merge a contribution that way. Please check out https://github.com/asl/swift/pull/1, which will put the test into `asl:55170-fix`.

File: lib/Sema/TypeChecker.cpp (hunk 4 above)
Comment (slavapestov) [reply lib/Sema/TypeChecker.cpp:379]: One alternative is to handle this like we do operators and AnyObject lookup. When skipping over the body of a nominal type or extension, make a note if the lexer sees '@_derivative', then eagerly parse only those delayed bodies when performing this global lookup. That's still not great but better than disabling delayed parsing entirely when 'import _Differentiation' appears in the program.

**Comment by asl** [comment]
@rxwei Do you happen to have any further comments on this? Or we can land this PR?

Thanks!

File: lib/Sema/TypeChecker.cpp (hunk 4 above)
Comment (asl) [reply lib/Sema/TypeChecker.cpp:379]: @slavapestov Yes, I though about this as well, thanks! Though I was a bit hesitant to introduce such derivative-specific logic into lexer and parser :) But if you're thinking it's acceptable, I can try to do something around this in the subsequent PRs.

**Review by rxwei — APPROVED** [review]
LGTM but I would also get a ✅ from @slavapestov

**Comment by philipturner** [comment]
Could we get this merged? The longer we wait, the more nightly snapshots are produced that are unusable with my AutoDiff client library. If general consensus is that it’s acceptable, let’s merge it (and the uncommitted regression test) sooner rather than later.

**Comment by asl** [comment]
We are currently waiting for @slavapestov's opinion per @rxwei request

**Comment by philipturner** [comment]
> We are currently waiting for slavapestov's opinion per rxwei request

Would it be possible to temporarily revert https://github.com/apple/swift/pull/58644 until https://github.com/apple/swift/pull/58965 is approved? That would remove the crash it introduced, letting other modifications to the compiler (such as RQM, SIL patches) be tested against AutoDiff. Furthermore, #58644 is like an incomplete version of #58965. We should wait to incorporate cross-file lookup the Swift compiler until its implementation is complete. This solution would also provide reviewers with as much time as necessary to decide whether to merge this PR.

There is also a precedent for this, as it is how the merging of https://github.com/apple/swift/pull/42189 played out. The initial version caused a [regression on Windows](https://github.com/apple/swift/pull/42466#issuecomment-1103413951), much like the how #58644 introduced https://github.com/apple/swift/issues/59467. After being temporarily reverted, the PR was reapplied with fixes for Windows.

**Comment by asl** [comment]
@slavapestov gently ping :)

**Review by slavapestov — APPROVED** [review]

File: lib/Frontend/Frontend.cpp [hunk 5]
```diff
@@ -1186,11 +1186,31 @@ bool CompilerInstance::forEachFileToTypeCheck(
...
+  return false;
+}
+
 void CompilerInstance::finishTypeChecking() {
   forEachFileToTypeCheck([](SourceFile &SF) {
     performWholeModuleTypeChecking(SF);
     return false;
   });
+
+  forEachSourceFile([](SourceFile &SF) {
```
Comment (slavapestov) [inline lib/Frontend/Frontend.cpp:1210]: Is there a way to avoid the walk over all source files in the case where none of them have differentiable programming enabled?

**Comment by asl** [comment]
@slavapestov Thanks! I created https://github.com/apple/swift/pull/58965 to track it. Will post follow-up patch

**Comment by philipturner** [comment]
Thanks! But what happened to the regression test from https://github.com/asl/swift/pull/1? Should I make a new PR to merge it into apple/swift, or did you decide that it's not a good idea?
