### PR TITLE
[AutoDiff] Fix return type of subset parameters thunk function

### LINKED ISSUE #55703: [SR-13263] Invalid Debug Information Generation
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13263      |
   |Radar             | None         |
   |Original Reporter | @compnerd      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963900-471558bd-8a5b-48c6-9c51-3a16a7f09fde.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 3         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | @adrian-prantl      |
   |Priority          | Medium      |

   

   md5: 1cf1abd3137f286141ea88df6a315030

  </details>

**Issue Description:**

lit test reproducer:

``` swift
// RUN: %empty-directory(%t)
// RUN: %target-swiftc_driver -DM -emit-module -emit-module-path %t/M.swiftmodule %s -module-name M
// RUN: not --crash %target-swiftc_driver -O -g -I %t -c %s -o /dev/null

#if M
import _Differentiation

public struct S<T> {
  class C {}
  let c: C
  internal var b: Bool
}

extension S: AdditiveArithmetic {
  public static var zero: S { fatalError() }

  public static func == (_ lhs: S, _ rhs: S) -> Bool { fatalError() }
  public static func + (_ lhs: S, _ rhs: S) -> S { fatalError() }
  public static func - (_ lhs: S, _ rhs: S) -> S { fatalError() }
}

extension S: Differentiable {
  public typealias TangentVector = S
}

#else
import _Differentiation
import M

struct T: Differentiable {
  var u1: U
  var u2: U
}

struct U: Differentiable {
  var s: S<Float>
  var v: V
}

struct V: Differentiable {
  var s: S<Float>
}
#endif
```

Crash:

```
swift-frontend: swift-dev/llvm-project/llvm/lib/CodeGen/AsmPrinter/DwarfExpression.cpp:572: void llvm::DwarfExpression::addFragmentOffset(const llvm::DIExpression *): Assertion `FragmentOffset >= OffsetInBits && "overlapping or duplicate fragments"' failed.
Stack dump:
1.  Swift version 5.3-dev (LLVM 6d510c802af0d59, Swift 3e090b483352b3c)
2.  Running pass 'Function Pass Manager' on module '/dev/null'.
3.  Running pass 'X86 Assembly Printer' on function '@"$s4null1TV4move5alongyAC13TangentVectorV_tF"'
```

### PR DESCRIPTION
**Pull request by asavonic**
The patch resolves #67402.

When the original function has a tuple result type, we should append thunkedLinearMap as the last element of the tuple to match the function declaration. Before this patch, the compiler used to wrap the original result tuple and thunkedLinearMap into another tuple, and caused the verifier error.

Before the patch:

```
  return %{{.*}} : $((Float, Double), @callee_guaranteed (Float) -> X.TangentVector)
```
After the patch:
```
  return %{{.*}} : $(Float, Double, @callee_guaranteed (Float) -> X.TangentVector)
```

### CODE REVIEW

File: test/AutoDiff/SILOptimizer/param_thunk_tuple.swift [hunk 1]
```diff
@@ -0,0 +1,33 @@
+// RUN: %target-swift-frontend -emit-sil %s | %FileCheck %s
+
+// Verify the result type of a subset parameters thunk matches the declaration:
+//
+// CHECK: // autodiff subset parameters thunk for forward-mode derivative from f(x:)
```
Comment (asavonic) [inline test/AutoDiff/SILOptimizer/param_thunk_tuple.swift:5]: I'm not sure if demangled names are printed in all build configurations. Please let me know if it is not the case.
Mangled names are a bit too long and unreadable, but we can check them instead if we have to.

**Comment by jkshtj** [comment]
> Before the patch:
> 
> ```
>   return %{{.*}} : $((Float, Double), @callee_guaranteed (X.TangentVector) -> Float)
> ```
> 
> After the patch:
> 
> ```
>   return %{{.*}} : $(Float, Double, @callee_guaranteed (Float) -> X.TangentVector)
> ```

Is there a typo in the signature of the linear map in the after section?

**Comment by jkshtj** [comment]
Looks good otherwise. Thanks Andrew!

**Comment by asavonic** [comment]
> Is there a typo in the signature of the linear map in the after section?

Good catch, thank you.
I've updated the PR description, but not the commit message to avoid re-running CI. We can update it before landing.
