### PR TITLE
[embedded] Don't produce PerfDiags when in non-WMO mode (e.g. when building during indexing)

### LINKED ISSUE #48: SourceKit error: Cannot use metatype of type 'RCC.AHB1ENR.ReadWrite' in embedded Swift
While the stm32-uart-echo builds successfully, there are errors from SourceKit. Here's one of them 
Screenshot 2024-08-10 at 11 54 13

### PR DESCRIPTION
**Pull request by kubamracek**
This silences false positives coming from the fact that in non-WMO builds, we don't currently see function bodies of other translation units, and therefore we can't specialize+inline them.

Fixes https://github.com/apple/swift-embedded-examples/issues/48

rdar://125437187

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by ahoppen — APPROVED** [review]

**Comment by kubamracek** [comment]
@swift-ci please test

File: lib/SILOptimizer/Mandatory/PerformanceDiagnostics.cpp [hunk 1]
```diff
@@ -755,6 +755,10 @@ class PerformanceDiagnosticsPass : public SILModuleTransform {
   void run() override {
     SILModule *module = getModule();
 
+    // Skip all performance/embedded diagnostics if not in WMO mode. Building in
+    // non-WMO mode currently results in false positives.
```
Comment (eeckstein) [inline lib/SILOptimizer/Mandatory/PerformanceDiagnostics.cpp:759]: I think we should do this only for SourceKit but not in a regular build. In embedded non-wmo builds can only happen in SourceKit, anyway. But for performance annotations (in non-wmo, non-embedded mode) such errors are not false alarms.

**Comment by kubamracek** [comment]
@swift-ci please test macOS platform

File: lib/SILOptimizer/Mandatory/PerformanceDiagnostics.cpp (hunk 1 above)
Comment (kubamracek) [reply lib/SILOptimizer/Mandatory/PerformanceDiagnostics.cpp:759]: @bnbarham do you know a way to detect here that we're doing a SourceKit build?

Comment (bnbarham) [reply lib/SILOptimizer/Mandatory/PerformanceDiagnostics.cpp:759]: > But for performance annotations (in non-wmo, non-embedded mode) such errors are not false alarms.

I'm confused, why should they be disabled for SourceKit then?

Comment (eeckstein) [reply lib/SILOptimizer/Mandatory/PerformanceDiagnostics.cpp:759]: Because SourceKit does not compile with wmo, regardless of the build settings

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test macOS platform

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
```
******************** TEST 'Swift(macosx-x86_64) :: SourceKit/Diagnostics/embedded_non_wmo.swift' FAILED ********************
Script:
--
: 'RUN: at line 3';   rm -rf "/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/SourceKit/Diagnostics/Output/embedded_non_wmo.swift.tmp" && mkdir -p "/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/SourceKit/Diagnostics/Output/embedded_non_wmo.swift.tmp"
: 'RUN: at line 4';   split-file /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/test/SourceKit/Diagnostics/embedded_non_wmo.swift /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/SourceKit/Diagnostics/Output/embedded_non_wmo.swift.tmp
: 'RUN: at line 6';   /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/bin/sourcekitd-test -module-cache-path '/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/swift-test-results/x86_64-apple-macosx10.13/clang-module-cache' -req=diags /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/SourceKit/Diagnostics/Output/embedded_non_wmo.swift.tmp/file1.swift -- /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/SourceKit/Diagnostics/Output/embedded_non_wmo.swift.tmp/file1.swift /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/SourceKit/Diagnostics/Output/embedded_non_wmo.swift.tmp/file2.swift -enable-experimental-feature Embedded | /Applications/Xcode-beta.app/Contents/Developer/usr/bin/python3 /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/utils/PathSanitizingFileCheck --allow-unused-prefixes --sanitize BUILD_DIR=/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64 --sanitize SOURCE_DIR=/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift --use-filecheck /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/llvm-macosx-x86_64/bin/FileCheck   /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/test/SourceKit/Diagnostics/embedded_non_wmo.swift
--
Exit Code: 2

Command Output (stderr):
--
{
  key.request: source.request.diagnostics,
  key.sourcefile: "/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/SourceKit/Diagnostics/Output/embedded_non_wmo.swift.tmp/file1.swift",
  key.primary_file: "/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/SourceKit/Diagnostics/Output/embedded_non_wmo.swift.tmp/file1.swift",
  key.compilerargs: [
    "-module-cache-path",
    "/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/swift-test-results/x86_64-apple-macosx10.13/clang-module-cache",
    "/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/SourceKit/Diagnostics/Output/embedded_non_wmo.swift.tmp/file1.swift",
    "/Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/swift-macosx-x86_64/test-macosx-x86_64/SourceKit/Diagnostics/Output/embedded_non_wmo.swift.tmp/file2.swift",
    "-enable-experimental-feature",
    "Embedded"
  ]
}
error response (Request Failed): Internal error: no response was provided for the request
FileCheck error: '<stdin>' is empty.
FileCheck command line:  /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/build/buildbot_incremental/llvm-macosx-x86_64/bin/FileCheck --allow-unused-prefixes /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/test/SourceKit/Diagnostics/embedded_non_wmo.swift

--
```

**Comment by kubamracek** [comment]
@swift-ci please test macOS platform

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test
