### PR TITLE
Fix runtime crash due to miscompile when using result builder via synthesized initializer in non-generic struct

### LINKED ISSUE #86205: Runtime crash when using result builder via synthesized initializer
### Description

The following code compiles successfully but crashes at runtime. The `value.array` is unexpectedly `<uninitialized>`.

### Reproduction

```swift
@resultBuilder
struct StringArrayBuilder {
  static func buildBlock(_ elements: String...) -> [String] {
    elements
  }
}

struct MyValue {
  @StringArrayBuilder let array: [String]
}

let value = MyValue(array: {
  "foo"
  "bar"
})

print("Value?")
print(value.array.count) // Crashes because value.array is uninitialized
```

### Stack dump

```text
#0	0x00000001959fd178 in swift::RefCounts<swift::RefCountBitsT<(swift::RefCountInlinedness)1>>::incrementSlow ()
#1	(access of value.array)
```

### Expected behavior

It should not crash, and the array should be initialized to `["foo", "bar"]`. This works correctly if you change `@StringArrayBuilder let array: [String]` to `@StringArrayBuilder let array: () -> [String]`, but that changes the semantics of the type.

### Environment

Swift version 6.2.3 (swift-6.2.3-RELEASE)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by calda**
This PR fixes https://github.com/swiftlang/swift/issues/86205.

In this sample code, the synthesized memberwise initializer does not properly initialize `value.array`, causing a runtime crash when it is later accessed.

```swift
@resultBuilder
struct StringArrayBuilder {
  static func buildBlock(_ elements: String...) -> [String] {
    elements
  }
}

struct MyValue {
  @StringArrayBuilder let array: [String]
}

let value = MyValue(array: {
  "foo"
  "bar"
})

print("Value?")
print(value.array.count) // Crashes because value.array is uninitialized
```

The result-builder specific logic in `emitImplicitValueConstructor` was missing in the `if (resultSlot) {`'s `else` codepath. In this case generic structs (so, all SwiftUI / `@ViewBuilder` use cases) used the first code path, and non-generic structs use the `else` codepath.

### CODE REVIEW

File: lib/SILGen/SILGenConstructor.cpp [hunk 1]
```diff
@@ -558,6 +558,20 @@ static void emitImplicitValueConstructor(SILGenFunction &SGF,
       (void)eltEnd;
       value = std::move(*elti);
       ++elti;
+
+      // If the stored property has an attached result builder and its
+      // type is not a function type, the argument is a noescape closure
+      // that needs to be called.
+      if (field->getResultBuilderType()) {
```
Comment (calda) [inline lib/SILGen/SILGenConstructor.cpp]: This check is used in the above `if (resultSlot) {` code path, but was missing from this `else {` codepath.

**Comment by calda** [comment]
Hey @xedin, would you mind reviewing this fix?

File: lib/SILGen/SILGenConstructor.cpp (hunk 1 above)
Comment (xedin) [reply lib/SILGen/SILGenConstructor.cpp]: Looks like it's also missing a property wrapper application. Let's package that into a closure and call from both places before `++elti;` is called, does that make sense?

Comment (calda) [reply lib/SILGen/SILGenConstructor.cpp]: Sounds good, updated!

For the property wrapper application, I think both branches already have the correct `maybeEmitPropertyWrapperInitFromValue` call:
 - https://github.com/calda/swift/blob/1126b71195757935045b99bcf8fd8b4385e17a37/lib/SILGen/SILGenConstructor.cpp#L491
 - https://github.com/calda/swift/blob/1126b71195757935045b99bcf8fd8b4385e17a37/lib/SILGen/SILGenConstructor.cpp#L592C18-L592C55

File: lib/SILGen/SILGenConstructor.cpp [hunk 2]
```diff
@@ -557,6 +561,7 @@ static void emitImplicitValueConstructor(SILGenFunction &SGF,
       assert(elti != eltEnd && "number of args does not match number of fields");
       (void)eltEnd;
       value = std::move(*elti);
+      value = emitResultBuilderCallIfNeeded(field, std::move(value));
```
Comment (xedin) [inline lib/SILGen/SILGenConstructor.cpp:584]: Shouldn't `maybeEmitPropertyWrapperInitFromValue` be included on both sides as well?

Comment (calda) [reply lib/SILGen/SILGenConstructor.cpp:584]: The newly updated codepath calls `maybeEmitPropertyWrapperInitFromValue` 20-30 lines later, so I don't think we need to make any changes there. wdyt? https://github.com/calda/swift/blob/1126b71195757935045b99bcf8fd8b4385e17a37/lib/SILGen/SILGenConstructor.cpp#L592

Comment (xedin) [reply lib/SILGen/SILGenConstructor.cpp:584]: Ah, I missed it, thanks! Looks good to me then!

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

File: lib/SILGen/SILGenConstructor.cpp (hunk 2 above)
Comment (calda) [reply lib/SILGen/SILGenConstructor.cpp:584]: 😄

**Comment by calda** [comment]
@xedin, could you trigger CI again? I think the failure was a flake.

**Comment by calda** [comment]
Hey @xedin, could you trigger CI again? Thanks :)

**Comment by xedin** [comment]
Oh, I thought we landed this, I am sorry!

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by calda** [comment]
np!

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please test arm64

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please test arm64

**Comment by calda** [comment]
@xedin, I rebased the PR on top of a more recent development snapshot, maybe that will help resolve some of these CI flakes

**Comment by xedin** [comment]
@swift-ci please test

**Comment by calda** [comment]
Thanks @xedin!
