### PR TITLE
[SE-0286] Fix issue where forward scanning default value heuristic wouldn't be applied in Swift 6 mode

### LINKED ISSUE #65921: ForwardTrailingClosures is not source compatible with calls to `View.sheet(isPresented:onDismiss:content:)`
**Description**
The Swift proposal "[Forward-scan matching for trailing closures](https://github.com/apple/swift-evolution/blob/main/proposals/0286-forward-scan-trailing-closures.md)" explicitly states that its implementation includes a heuristic that will allow for calls to SwiftUI's `View.sheet` method to continue to compile. 

> For the `View.sheet(isPresented:onDismiss:content:)` API, this means that onDismiss, which has a default argument, will be skipped in the forward match so that the unlabeled trailing closure will match content:, allowing this code to continue to compile correctly.

However, when I enable ForwardTrailingClosures in Swift 5.8, the example call does not continue to compile correctly. 

**Steps to reproduce**
Using Xcode 14.3, I've created a new iOS App project with SwiftUI. [ForwardScanCompatibilityRepro.zip](https://github.com/apple/swift/files/11480742/ForwardScanCompatibilityRepro.zip)
 I modified the `ContentView` to look like this:

```Swift
import SwiftUI

struct ContentView: View {
  @State private var isShowingSheet = false

  var body: some View {
    VStack {
      showButton
        .sheet(isPresented: $isShowingSheet) {
          Text("Hello")
        }
    }.padding()
  }

  var showButton: some View {
    Button("Show Sheet") {
      isShowingSheet.toggle()
    }
  }
}
```

This code compiles and runs just fine, but when I add `-enable-upcoming-feature ForwardTrailingClosures` to "Other Swift Flags" it no longer compiles. The error message states `Missing argument for parameter 'content' in call`. 

If you modify the call to include the `content:` parameter then the code compiles. 

```Swift
        .sheet(isPresented: $isShowingSheet, content: {
          Text("Hello")
        })
```

**Expected behavior**

`sheet(isPresented: $isPresented) { Text("Hello") }` should compile with Swift 5.8 and `-enable-upcoming-feature ForwardTrailingClosures`. 

**Environment**
- Swift version info swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
- Xcode version info Xcode 14.3 Build version 14E222b
- Deployment target: iOS 16.4

### PR DESCRIPTION
**Pull request by calda**
This PR fixes https://github.com/apple/swift/issues/65921, which is a bug related to [SE-0286](https://github.com/apple/swift-evolution/blob/master/proposals/0286-forward-scan-trailing-closures.md).

The following examples compile successfully in Swift 5 mode, but currently fail to compile in Swift 6 mode, or in Swift 5 mode with the `ForwardTrailingClosures` upcoming feature enabled:

```swift
func sheet(
  isPresented: Bool,
  onDismiss: (() -> Void)? = nil,
  content: () -> String
) -> String { content() }

// error: missing argument for parameter 'content' in call
_ = sheet(isPresented: true) {
  "Hello world"
}

func issue_65921(onStart: ((String) -> Void)? = nil, onEnd: (String) -> Void) { }

// error: missing argument for parameter 'onEnd' in call
issue_65921 { end in
  _ = end
}
```

I believe these examples are expected to compile in Swift 6 based on this section of SE-0286, which says it applies to all language versions and not just Swift 5:

> ## Mitigating the source compatibility impact (all language versions)
> ... We can turn this into an heuristic to accept more existing code, reducing the source breaking impact of the proposal. Specifically, if
>  - the parameter that would match the unlabeled trailing closure argument does not require an argument (because it is variadic or has a default argument), and
>  - there are parameters after that parameter that require an argument, up until the first parameter whose label matches that of the next trailing closure (if any)
>
> then do not match the unlabeled trailing closure to that parameter. Instead, skip it and examine the next parameter to see if that should be matched against the unlabeled trailing closure. For the `View.sheet(isPresented:onDismiss:content:`) API, this means that `onDismiss`, which has a default argument, will be skipped in the forward match so that the unlabeled trailing closure will match `content:`, allowing this code to continue to compile correctly.

This issue appears to be that the code implementing the heuristic described above is disabled in Swift 6 mode. Updating the code to apply to all language modes makes it so these examples compile successfully.

Please review: @DougGregor

### CODE REVIEW

File: test/expr/postfix/call/forward_trailing_closure_errors.swift [hunk 1]
```diff
@@ -17,14 +17,98 @@ func testUnlabeledParamMatching(i: Int, fn: ((Int) -> Int) -> Void) {
...
-func forwardMatchFailure( // expected-note{{declared here}}
+func forwardMatchFailure(
   onError: ((any Error) -> Void)? = nil,
   onCompletion: (Int) -> Void
 ) { }
 
 func testForwardMatchFailure() {
   forwardMatchFailure { x in
     print(x)
-  } // expected-error{{missing argument for parameter 'onCompletion' in call}}{{4-4= onCompletion: <#(Int) -> Void#>}}
```
Comment (calda) [inline test/expr/postfix/call/forward_trailing_closure_errors.swift:29]: I believe this example is actually expected to compile successfully in Swift 6 mode based on the behavior described in SE-0286

**Review by xedin — APPROVED** [review]
Thank you, the heuristic is described in https://github.com/apple/swift-evolution/blob/main/proposals/0286-forward-scan-trailing-closures.md#mitigating-the-source-compatibility-impact-all-language-versions and should be applied to all language versions.

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Comment by xedin** [comment]
Source compatibility failures are unrelated.

**Comment by calda** [comment]
Thank you @xedin and @hborla! 🙇🏻
