### PR TITLE
[Concurrency] Fix `stripConcurrency` to strip only global actor isola…

### LINKED ISSUE #86332: "Approachable concurrency" miscompilation involving function conversions
### Description

the combination of `NonisolatedNonsendingByDefault`, default `MainActor` isolation, and the swift 5 language mode seems like it can lead to function conversion miscompilation in which the implicit `nonisolated(nonsending)` isolation parameter is incorrectly passed as an explicit parameter.

### Reproduction

```swift
/*
built with:
xcrun swiftc \
-enable-upcoming-feature NonisolatedNonsendingByDefault \
-default-isolation MainActor \
-swift-version 5 \
-parse-as-library
*/

struct S {
    var action: (AnyObject) async -> Void

	init(action: @escaping (AnyObject) -> Void) {
		self.action = action
	}
}

func test() async {
    let s = S { print($0) }
    await s.action(42 as AnyObject) // prints: 'Swift.MainActor'
}

@main
enum App {
    static func main() async {
        await test()
    }
}
```

changing the param from `AnyObject` to other types typically results in runtime crashes.

### Expected behavior

the code should correctly perform the necessary function conversions without mixing up the parameters.

### Environment

Apple Swift version 6.2 (swiftlang-6.2.0.19.9 clang-1700.3.19.1)
Target: arm64-apple-macosx26.0

### Additional information

issue was originally reported and discussed here: https://forums.swift.org/t/exc-bad-access-with-escaping-closure-and-task/83989

### PR DESCRIPTION
**Pull request by xedin**
…tion

The original condition was removing not just global actor isolation but any isolation set on the function type. This leads to incorrect conversions in AST and miscompiles.

Resolves: https://github.com/swiftlang/swift/issues/86332
Resolves: rdar://167712422

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Review by hborla — APPROVED** [review]

File: test/Interpreter/issue86332.swift [hunk 1]
```diff
@@ -0,0 +1,29 @@
+// RUN: %empty-directory(%t)
+// RUN: %target-build-swift -target %target-swift-5.1-abi-triple %s -default-isolation MainActor -enable-upcoming-feature NonisolatedNonsendingByDefault -parse-as-library -module-name main -swift-version 6 -o %t/main
```
Comment (jamieQ) [inline test/Interpreter/issue86332.swift]: FYI @xedin when i tested this, it did not repro in swift 6 mode, but needed swift 5 mode

Comment (xedin) [reply test/Interpreter/issue86332.swift]: Yeah, I switched to `-swift-version 5` to make everything 1-1.

**Comment by xedin** [comment]
@swift-ci please test

**Review by ktoso — APPROVED** [review]
nice catch!

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform
