### PR TITLE
[Diagnostics] Improving diagnostics for function type coerce with different number of args

### LINKED ISSUE #63926: [Sema] Not actionable diagnostic for function conversion failure in coercion context
**Description**
Consider this example:
```swift
func fn(_: Int) {}
func fn(_: Bool) {}
let i: Int = 0
(fn as (Int, Int) -> Void)(i, i) // type of expression is ambiguous without more context
```
`MissingArgumentsFailure` doesn't handle the diagnose it correctly.

**Steps to reproduce**
Run the sample code above.

**Expected behavior**

A diagnostic that mentions that `fn` has an number of arguments mismatch with coerce function type.

**Environment**
- Swift compiler version info: main at @9d9e015a9f616391c9af8c992286ffa53aa1d438

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
For a function match failure on the number of args, record a contextual failure to diagnose as a type mismatch since is not a function application. Except for closures because missing/extraneous argument fix can handle closure mismatch and provide fix-its to closure expr arguments.

Resolves https://github.com/apple/swift/issues/63926

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

File: lib/Sema/CSSimplify.cpp [hunk 1]
```diff
@@ -3425,18 +3425,36 @@ ConstraintSystem::matchFunctionTypes(FunctionType *func1, FunctionType *func2,
...
-      if (diff < 0) {
-        if (fixMissingArguments(*this, anchor, func1Params, func2Params,
-                                abs(diff), loc))
+      // The param diff is in a function type coercion context
+      //
+      // func fn(_: Int) {}
+      // let i: Int = 0
+      // (fn as (Int, Int) -> Void)(i, i)
+      //
+      // Since we are not in a function argument application, so simply record
```
Comment (xedin) [inline lib/Sema/CSSimplify.cpp:3434]: Extra-nit: so is unnecessary here.

File: lib/Sema/CSSimplify.cpp [hunk 2]
```diff
@@ -3425,18 +3425,36 @@ ConstraintSystem::matchFunctionTypes(FunctionType *func1, FunctionType *func2,
...
+      // a function type mismatch instead of an argument fix.
+      // Except for when a closure is a subexpr because missing and extraneous
+      // arg fix can properly handle closure diagnostic.
```
Comment (xedin) [inline lib/Sema/CSSimplify.cpp:3437]: Nit: I think we should rework this section a bit to explain the reason why the closure is special - because it's possible to suggest source code changes for closures to remove or add arguments (which is handled by missing/extraneous arguments fix) unlike function references.

File: test/expr/cast/as_coerce.swift [hunk 3]
```diff
@@ -163,3 +163,28 @@ let _: Int = any as Int // expected-error {{'Any' is not convertible to 'Int'}}
 // expected-note@-1 {{did you mean to use 'as!' to force downcast?}} {{18-20=as!}}
 let _: Int? = any as Int // expected-error {{'Any' is not convertible to 'Int'}}
 // expected-note@-1 {{did you mean to use 'as?' to conditionally downcast?}} {{19-21=as?}}
+
+// https://github.com/apple/swift/issues/63926
+
+func fn63926(_: Int) {} // expected-note {{found candidate with type '(Int) -> ()'}}
```
Comment (xedin) [inline test/expr/cast/as_coerce.swift:169]: Since all we check here are functions, let's wrap all the new tests in a `do { ... }` and drop `63926` from the names.

**Review by xedin — APPROVED** [review]
Looks good, thank you! I left a new small comments which would be good to address before merging.

File: lib/Sema/CSSimplify.cpp (hunk 2 above)
Comment (LucianoPAlmeida) [reply lib/Sema/CSSimplify.cpp]: Yes, just updated =]

File: test/expr/cast/as_coerce.swift (hunk 3 above)
Comment (LucianoPAlmeida) [reply test/expr/cast/as_coerce.swift]: Fixed!

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

**Comment by xedin** [comment]
Looks great, thank you again!
