### PR TITLE
[Sema] Fix crash when diagnosing ambiguous trailing closure inits

### LINKED ISSUE #85364: [Typechecker]: Crash involving trailing closures, callAsFunction, and duplicate declarations
### Description

_No response_

### Reproduction

```swift
struct S {
  var c: () -> Void
}

S {}

struct S {
  func callAsFunction(_: () -> Void) {}
}
```

an additional variant that looks like it hits the same assertion occurs when overloading initializers (as @YOCKOW noted in https://github.com/swiftlang/swift/issues/85378):

```swift
struct S {
  init() {
    print("`init` without block is called.")
  }

  init(_ block: () -> Void) {
    print("`init` with block is called.")
    block()
  }

  func callAsFunction(_ block: () -> Void) {
    print("`callAsFunction` is called.")
    block()
  }
}

S {}
```

### Stack dump

```text
swift-frontend: /home/build-user/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:157: const T &llvm::ArrayRef<swift::ParamDecl *>::back() const [T = swift::ParamDecl *]: Assertion `!empty()' failed.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /cefs/fe/fe478d39bbcfde13719a3634_swift-nightly/usr/bin/swift-frontend -frontend -S -primary-file <source> -target x86_64-unknown-linux-gnu -disable-objc-interop -no-color-diagnostics -Xcc -fno-color-diagnostics -g -debug-info-format=dwarf -dwarf-version=4 -empty-abi-descriptor -enable-anonymous-context-mangled-names -file-compilation-dir /app -Xllvm --x86-asm-syntax=intel -no-auto-bridging-header-chaining -module-name output -in-process-plugin-server-path /cefs/fe/fe478d39bbcfde13719a3634_swift-nightly/usr/lib/swift/host/libSwiftInProcPluginServer.so -plugin-path /cefs/fe/fe478d39bbcfde13719a3634_swift-nightly/usr/lib/swift/host/plugins -plugin-path /cefs/fe/fe478d39bbcfde13719a3634_swift-nightly/usr/local/lib/swift/host/plugins -o /app/output.s
1.	Swift version 6.3-dev (LLVM bff1370bd79c983, Swift 57cf4ce563f700b)
2.	Compiling with effective version 5.10
3.	While evaluating request TypeCheckPrimaryFileRequest(source_file "<source>")
4.	While type-checking statement at [<source>:5:1 - line:5:4] RangeText="S {"
5.	While type-checking expression at [<source>:5:1 - line:5:4] RangeText="S {"
6.	While type-checking-target starting at <source>:5:1
 #0 0x000064fffeb0c418 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/cefs/fe/fe478d39bbcfde13719a3634_swift-nightly/usr/bin/swift-frontend+0x8958418)
 #1 0x000064fffeb09c05 llvm::sys::RunSignalHandlers() (/cefs/fe/fe478d39bbcfde13719a3634_swift-nightly/usr/bin/swift-frontend+0x8955c05)
 #2 0x000064fffeb0d1c1 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #3 0x00007343a3e42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007343a3e969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007343a3e42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007343a3e287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00007343a3e2871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x00007343a3e39e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x000064fff8101175 swift::constraints::TrailingClosureAmbiguityFailure::diagnoseAsNote() (/cefs/fe/fe478d39bbcfde13719a3634_swift-nightly/usr/bin/swift-frontend+0x1f4d175)
#10 0x000064fff815b8bf swift::constraints::ConstraintSystem::diagnoseAmbiguity(llvm::ArrayRef<swift::constraints::Solution>) (/cefs/fe/fe478d39bbcfde13719a3634_swift-nightly/usr/bin/swift-frontend+0x1fa78bf)
#11 0x000064fff81569bb swift::constraints::ConstraintSystem::salvage() (/cefs/fe/fe478d39bbcfde13719a3634_swift-nightly/usr/bin/swift-frontend+0x1fa29bb)
#12 0x000064fff80a76d6 swift::constraints::ConstraintSystem::solve(swift::constraints::SyntacticElementTarget&, swift::FreeTypeVariableBinding) (/cefs/fe/fe478d39bbcfde13719a3634_swift-nightly/usr/bin/swift-frontend+0x1ef36d6)
#13 0x000064fff82602ee swift::TypeChecker::typeCheckTarget(swift::constraints::SyntacticElementTarget&, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>, swift::DiagnosticTransaction*) (/cefs/fe/fe478d39bbcfde13719a3634_swift-nightly/usr/bin/swift-frontend+0x20ac2ee)
#14 0x000064fff8260131 swift::TypeChecker::typeCheckExpression(swift::constraints::SyntacticElementTarget&, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>, swift::DiagnosticTransaction*) (/cefs/fe/fe478d39bbcfde13719a3634_swift-nightly/usr/bin/swift-frontend+0x20ac131)
#15 0x000064fff8260006 swift::TypeChecker::typeCheckExpression(swift::Expr*&, swift::DeclContext*, swift::constraints::ContextualTypeInfo, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>) (/cefs/fe/fe478d39bbcfde13719a3634_swift-nightly/usr/bin/swift-frontend+0x20ac006)
#16 0x000064fff836714b (anonymous namespace)::StmtChecker::typeCheckASTNode(swift::ASTNode&) TypeCheckStmt.cpp:0:0
#17 0x000064fff836afbd swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) TypeCheckStmt.cpp:0:0
#18 0x000064fff8368fec bool (anonymous namespace)::StmtChecker::typeCheckStmt<swift::BraceStmt>(swift::BraceStmt*&) TypeCheckStmt.cpp:0:0
#19 0x000064fff8369083 swift::TypeChecker::typeCheckTopLevelCodeDecl(swift::TopLevelCodeDecl*) (/cefs/fe/fe478d39bbcfde13719a3634_swift-nightly/usr/bin/swift-frontend+0x21b5083)
#20 0x000064fff83d969a swift::TypeCheckPrimaryFileRequest::evaluate(swift::Evaluator&, swift::SourceFile*) const (/cefs/fe/fe478d39bbcfde13719a3634_swift-nightly/usr/bin/swift-frontend+0x222569a)
#21 0x000064fff83dda4b swift::TypeCheckPrimaryFileRequest::OutputType swift::Evaluator::getResultUncached<swift::TypeCheckPrimaryFileRequest, swift::TypeCheckPrimaryFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckPrimaryFileRequest>(swift::Evaluator&, swift::TypeCheckPrimaryFileRequest, swift::TypeCheckPrimaryFileRequest::OutputType)::'lambda'()>(swift::TypeCheckPrimaryFileRequest const&, swift::TypeCheckPrimaryFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckPrimaryFileRequest>(swift::Evaluator&, swift::TypeCheckPrimaryFileRequest, swift::TypeCheckPrimaryFileRequest::OutputType)::'lambda'()) crtstuff.c:0:0
#22 0x000064fff83d95a5 swift::performTypeChecking(swift::SourceFile&) (/cefs/fe/fe478d39bbcfde13719a3634_swift-nightly/usr/bin/swift-frontend+0x22255a5)
#23 0x000064fff6f16e59 bool llvm::function_ref<bool (swift::SourceFile&)>::callback_fn<swift::CompilerInstance::performSema()::$_10>(long, swift::SourceFile&) Frontend.cpp:0:0
#24 0x000064fff6f0dada swift::CompilerInstance::forEachFileToTypeCheck(llvm::function_ref<bool (swift::SourceFile&)>) (/cefs/fe/fe478d39bbcfde13719a3634_swift-nightly/usr/bin/swift-frontend+0xd59ada)
#25 0x000064fff6f0d8cb swift::CompilerInstance::performSema() (/cefs/fe/fe478d39bbcfde13719a3634_swift-nightly/usr/bin/swift-frontend+0xd598cb)
#26 0x000064fff6b87372 withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) FrontendTool.cpp:0:0
#27 0x000064fff6b75f99 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*, llvm::ArrayRef<char const*>) FrontendTool.cpp:0:0
#28 0x000064fff6b72bfe swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) (/cefs/fe/fe478d39bbcfde13719a3634_swift-nightly/usr/bin/swift-frontend+0x9bebfe)
#29 0x000064fff68c2aec swift::mainEntry(int, char const**) (/cefs/fe/fe478d39bbcfde13719a3634_swift-nightly/usr/bin/swift-frontend+0x70eaec)
#30 0x00007343a3e29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#31 0x00007343a3e29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#32 0x000064fff68c19d5 _start (/cefs/fe/fe478d39bbcfde13719a3634_swift-nightly/usr/bin/swift-frontend+0x70d9d5)

*** Signal 6: Backtracing from 0x7343a3f1e88d... done ***

*** Program crashed: Aborted at 0x0000280000000001 ***

Platform: x86_64 Linux (Ubuntu 22.04.5 LTS)
```

### Expected behavior

No crash

### Environment

Swift version 6.3-dev (LLVM bff1370bd79c983, Swift 57cf4ce563f700b)
Target: x86_64-unknown-linux-gnu

### Additional information

forum post: https://forums.swift.org/t/why-can-initializer-parentheses-be-omitted-with-callasfunction-trailing-closure/83061
godbolt: https://swift.godbolt.org/z/97d3ex586

### LINKED ISSUE #85378: Compiler crashes if a type has specific `init` overload + `callAsFunction`.
### Description

This is probably related to:
- https://github.com/swiftlang/swift/issues/85364
- https://github.com/swiftlang/swift/issues/85376

The compiler crashes when it tries to compile the following code.

### Reproduction

```swift
struct S {
  init() {
    print("`init` without block is called.")
  }

  init(_ block: () -> Void) {
    print("`init` with block is called.")
    block()
  }

  func callAsFunction(_ block: () -> Void) {
    print("`callAsFunction` is called.")
    block()
  }
}

S {}

```

### Stack dump

```text
Assertion failed: (!empty()), function back, file ArrayRef.h, line 157.
Stack dump:
0.	Program arguments: /Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend -frontend -interpret forums-83061.swift -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -color-diagnostics -Xcc -fcolor-diagnostics -empty-abi-descriptor -no-auto-bridging-header-chaining -module-name main -in-process-plugin-server-path /Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/lib/swift/host/libSwiftInProcPluginServer.dylib -plugin-path /Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/local/lib/swift/host/plugins -target-sdk-version 26.0 -target-sdk-name macosx26.0 -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server
1.	Apple Swift version 6.3-dev (LLVM bff1370bd79c983, Swift 57cf4ce563f700b)
2.	Compiling with effective version 5.10
3.	While evaluating request TypeCheckPrimaryFileRequest(source_file "forums-83061.swift")
4.	While type-checking statement at [forums-83061.swift:17:1 - line:17:4] RangeText="S {"
5.	While type-checking expression at [forums-83061.swift:17:1 - line:17:4] RangeText="S {"
6.	While type-checking-target starting at forums-83061.swift:17:1
 #0 0x000000010a2ffb80 (/Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend+0x105c9fb80)
 #1 0x000000010a2fde9c (/Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend+0x105c9de9c)
 #2 0x000000010a300610 (/Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend+0x105ca0610)
 #3 0x000000019e1ea744 (/usr/lib/system/libsystem_platform.dylib+0x1804d6744)
 #4 0x000000019e1e0888 (/usr/lib/system/libsystem_pthread.dylib+0x1804cc888)
 #5 0x000000019e0e6808 (/usr/lib/system/libsystem_c.dylib+0x1803d2808)
 #6 0x000000019e0e5a3c (/usr/lib/system/libsystem_c.dylib+0x1803d1a3c)
 #7 0x000000010a3102b4 (/Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend+0x105cb02b4)
 #8 0x0000000105987638 (/Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend+0x101327638)
 #9 0x00000001059e1e64 (/Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend+0x101381e64)
#10 0x00000001059defb0 (/Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend+0x10137efb0)
#11 0x00000001059474cc (/Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend+0x1012e74cc)
#12 0x0000000105af4928 (/Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend+0x101494928)
#13 0x0000000105af4768 (/Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend+0x101494768)
#14 0x0000000105af4630 (/Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend+0x101494630)
#15 0x0000000105bcb350 (/Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend+0x10156b350)
#16 0x0000000105bce538 (/Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend+0x10156e538)
#17 0x0000000105bccd64 (/Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend+0x10156cd64)
#18 0x0000000105bccdfc (/Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend+0x10156cdfc)
#19 0x0000000105c182e8 (/Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend+0x1015b82e8)
#20 0x0000000105c1b868 (/Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend+0x1015bb868)
#21 0x0000000105c181f4 (/Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend+0x1015b81f4)
#22 0x0000000104b9f67c (/Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend+0x10053f67c)
#23 0x0000000104b97088 (/Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend+0x100537088)
#24 0x0000000104b96fc4 (/Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend+0x100536fc4)
#25 0x000000010493f88c (/Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend+0x1002df88c)
#26 0x0000000104932d30 (/Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend+0x1002d2d30)
#27 0x000000010493048c (/Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend+0x1002d048c)
#28 0x0000000104698dec (/Users/yockow/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-11-03-a.xctoolchain/usr/bin/swift-frontend+0x100038dec)
#29 0x000000019de21d54
```

### Expected behavior

The compiler emits an error (or compiles successfully).

### Environment

```console
Apple Swift version 6.3-dev (LLVM bff1370bd79c983, Swift 57cf4ce563f700b)
Target: arm64-apple-macosx26.0
Build config: +assertions
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by naveen-seth**
This fixes a compiler crash that occurred when diagnosing an ambiguous call using trailing closure syntax, where one of the candidates was a function or initializer with no parameters.

The crash was caused by calling `.back()` on the candidate's empty parameter list, which is now guarded against.

Resolves #85364, resolves #85378.

### CODE REVIEW

**Comment by xedin** [comment]
Thank you @naveen-seth! I will take a look tomorrow!

File: lib/Sema/CSDiagnostics.cpp [hunk 1]
```diff
@@ -2142,6 +2142,8 @@ bool TrailingClosureAmbiguityFailure::diagnoseAsNote() {
       return false;
 
     const ParameterList *paramList = callee->getParameters();
+    if (paramList->getArray().empty())
```
Comment (xedin) [inline lib/Sema/CSDiagnostics.cpp]: Let's change this condition to `(!paramList || paramList->size() == 0)` and `paramList->getArray().back()` could be changed to `paramList->back()` while we are here.

**Review by xedin — CHANGES_REQUESTED** [review]

File: lib/Sema/CSDiagnostics.cpp (hunk 1 above)
Comment (naveen-seth) [reply lib/Sema/CSDiagnostics.cpp]: Done. Thank you for reviewing!

**Review by xedin — APPROVED** [review]
Thank you!

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@naveen-seth Looks like you need to mark `validation-test/compiler_crashers/TrailingClosureAmbiguityFailure-diagnoseAsNote-d62041.swift` as fixed as well.

**Comment by xedin** [comment]
@swift-ci please smoke test

**Comment by naveen-seth** [comment]
> @naveen-seth Looks like you need to mark `validation-test/compiler_crashers/TrailingClosureAmbiguityFailure-diagnoseAsNote-d62041.swift` as fixed as well.

Ah, I see! For future reference, should I have just extended the test in `validation-test/...` instead? (I can still do that.)

And in general, should all regression checks that guard against crashes be added under `validation-test/compiler-crashers(-fixed)`? I wasn’t entirely sure about that from the docs.

**Comment by xedin** [comment]
@naveen-seth Yes, you can move your test case to the same place and use `issue-<number>.swift` for the name.

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test Windows platform

File: validation-test/compiler_crashers_fixed/issue-85364.swift
Comment (AnthonyLatsis) [inline validation-test/compiler_crashers_fixed/issue-85364.swift:1]: @naveen-seth Hello Naveen, thank you for resolving this. If I may, here is an undocumented convention for next time. If you are writing contrived tests like these for diagnostics, place them somewhere in the primary test suite, even if that code used to crash. `compiler_crashers_fixed` is for real-world examples that:
* are too complex or specialised to serve as a targeted test that exercises a select code path.
* we feel are valuable to add or keep as is _in addition_ to a reduced and focused test, for example, because they represent common programming patterns or use a variety of features together (unlike the reduction).
