### PR TITLE
[CS] Avoid binding unwrapped type for SingleValueStmtExpr

### LINKED ISSUE #79474: [Diagnostics] Bogus diagnostic with implicit returns
### Description

_No response_

### Reproduction

```swift
enum E {
  struct S {
    let a: [Int]
  }

  case a(S)
  case b([String])
}

func f(_ e: E) -> [Int]? {
  switch e {
  case .b:
    // Cannot convert value of type 'ExpressibleByNilLiteral' to specified type '[Int]'
    nil

  case .a(let a):
    if a.count > 1 { // The error should be here
      a.a
    } else {
      nil
    }
  }
}
```

### Expected behavior

Points out that `a.count` is not defined (this works if the `case .a` is first!)

### Environment

```
swift-driver version: 1.115.1 Apple Swift version 6.0.3 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
Target: arm64-apple-macosx15.0
```

### Additional information

Yet another example of Swift diagnostics being broken, leading to hours of wasted time by developers trying to understand what's wrong with the code because the compiler points to a completely wrong line.

### PR DESCRIPTION
**Pull request by hamishknight**
Like closure results, we want the conversion to happen within the individual branches of the expression. This avoids unhelpful diagnostics around `nil` literals.

Resolves #79474
rdar://118813324

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Review by NachoSoto — COMMENTED** [review]
Awesome thank you!

File: lib/Sema/BindingProducer.cpp [hunk 1]
```diff
@@ -336,8 +336,14 @@ bool TypeVarBindingProducer::computeNext() {
...
-        if (!TypeVar->getImpl().isClosureResultType() || objTy->isVoid() ||
-            objTy->isTypeVariableOrMember()) {
+        //
+        // The same applies to the result of a SingleValueStmtExpr, we want to
+        // attempt conversions as part of the join between results rather than
+        // between the expression and its context.
+        auto *loc = TypeVar->getImpl().getLocator();
+        if (!(TypeVar->getImpl().isClosureResultType() && !objTy->isVoid() &&
+              !objTy->isTypeVariableOrMember()) &&
+            !loc->directlyAt<SingleValueStmtExpr>()) {
```
Comment (xedin) [inline lib/Sema/BindingProducer.cpp:346]: I think this is okay for time being but we really need to remove this condition since it's a generic problem and we keep piling up the conditions here...

**Review by xedin — APPROVED** [review]

File: lib/Sema/BindingProducer.cpp (hunk 1 above)
Comment (hamishknight) [reply lib/Sema/BindingProducer.cpp:346]: Yeah @slavapestov mentioned he was planning on getting rid of this logic entirely

**Comment by hamishknight** [comment]
@swift-ci please test macOS

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility Release
