### PR TITLE
SILGen: Don't try to project static stored properties as addressable from their base.

### LINKED ISSUE #82368: Compiler crash when using InlineArray span in static func
### Description

This crash was found during the development of a Swift Embedded application.

### Reproduction

```swift
struct A {
  static let a: InlineArray = [1]

  static func foo() {
    a.span.withUnsafeBufferPointer({ buffer in
      print("\(buffer.baseAddress)")
    })
  }
}

```

### Stack dump

```text
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.      Program arguments: /Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin/swift-frontend -frontend -c /Users/felix/DEV/Swift/swift-quadro-package/Sources/ApusFC/AHRS.swift /Users/felix/DEV/Swift/swift-quadro-package/Sources/ApusFC/Bluetooth.swift /Users/felix/DEV/Swift/swift-quadro-package/Sources/ApusFC/Button.swift /Users/felix/DEV/Swift/swift-quadro-package/Sources/ApusFC/CRSF.swift /Users/felix/DEV/Swift/swift-quadro-package/Sources/ApusFC/DShot.swift /Users/felix/DEV/Swift/swift-quadro-package/Sources/ApusFC/DroneController.swift /Users/felix/DEV/Swift/swift-quadro-package/Sources/ApusFC/ESPIDFUtils.swift /Users/felix/DEV/Swift/swift-quadro-package/Sources/ApusFC/Kalman.swift /Users/felix/DEV/Swift/swift-quadro-package/Sources/ApusFC/LED.swift /Users/felix/DEV/Swift/swift-quadro-package/Sources/ApusFC/LT1Filter.swift /Users/felix/DEV/Swift/swift-quadro-package/Sources/ApusFC/Logger.swift /Users/felix/DEV/Swift/swift-quadro-package/Sources/ApusFC/MCPWM.swift /Users/felix/DEV/Swift/swift-quadro-package/Sources/ApusFC/MSP.swift /Users/felix/DEV/Swift/swift-quadro-package/Sources/ApusFC/Matek.swift /Users/felix/DEV/Swift/swift-quadro-package/Sources/ApusFC/MotorController.swift /Users/felix/DEV/Swift/swift-quadro-package/Sources/ApusFC/NVS.swift /Users/felix/DEV/Swift/swift-quadro-package/Sources/ApusFC/PID.swift /Users/felix/DEV/Swift/swift-quadro-package/Sources/ApusFC/Receiver.swift /Users/felix/DEV/Swift/swift-quadro-package/Sources/ApusFC/SPI.swift /Users/felix/DEV/Swift/swift-quadro-package/Sources/ApusFC/System.swift /Users/felix/DEV/Swift/swift-quadro-package/Sources/ApusFC/Telemetry.swift /Users/felix/DEV/Swift/swift-quadro-package/Sources/ApusFC/ToF.swift -supplementary-output-file-map /var/folders/b7/c4_n2dh94k148lnrcmfpkxsw0000gn/T/TemporaryDirectory.2S5sDY/supplementaryOutputs-1 -target riscv32-none-none-eabi -disable-objc-interop -cxx-interoperability-mode=default -I ../Sources/ESPIDF -I ../Sources/Fusion -I ../Sources/VL53L1 -I /Users/felix/DEV/Swift/swift-quadro-package/build/config -I /Users/felix/DEV/Swift/swift-quadro-package/Sources/ESPIDF/include -I /Users/felix/DEV/Swift/swift-quadro-package/main -I /Users/felix/DEV/esp/esp-idf/components/newlib/platform_include -I /Users/felix/DEV/esp/esp-idf/components/freertos/config/include -I /Users/felix/DEV/esp/esp-idf/components/freertos/config/include/freertos -I /Users/felix/DEV/esp/esp-idf/components/freertos/config/riscv/include -I /Users/felix/DEV/esp/esp-idf/components/freertos/FreeRTOS-Kernel/include -I /Users/felix/DEV/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/include -I /Users/felix/DEV/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/include/freertos -I /Users/felix/DEV/esp/esp-idf/components/freertos/esp_additions/include -I /Users/felix/DEV/esp/esp-idf/components/esp_hw_support/include -I /Users/felix/DEV/esp/esp-idf/components/esp_hw_support/include/soc -I /Users/felix/DEV/esp/esp-idf/components/esp_hw_support/include/soc/esp32c6 -I /Users/felix/DEV/esp/esp-idf/components/esp_hw_support/dma/include -I /Users/felix/DEV/esp/esp-idf/components/esp_hw_support/ldo/include -I /Users/felix/DEV/esp/esp-idf/components/esp_hw_support/debug_probe/include -I /Users/felix/DEV/esp/esp-idf/components/esp_hw_support/port/esp32c6 -I /Users/felix/DEV/esp/esp-idf/components/esp_hw_support/port/esp32c6/include -I /Users/felix/DEV/esp/esp-idf/components/esp_hw_support/port/esp32c6/private_include -I /Users/felix/DEV/esp/esp-idf/components/heap/include -I /Users/felix/DEV/esp/esp-idf/components/heap/tlsf -I /Users/felix/DEV/esp/esp-idf/components/log/include -I /Users/felix/DEV/esp/esp-idf/components/soc/include -I /Users/felix/DEV/esp/esp-idf/components/soc/esp32c6 -I /Users/felix/DEV/esp/esp-idf/components/soc/esp32c6/include -I /Users/felix/DEV/esp/esp-idf/components/soc/esp32c6/register -I /Users/felix/DEV/esp/esp-idf/components/hal/platform_port/include -I /Users/felix/DEV/esp/esp-idf/components/hal/esp32c6/include -I /Users/felix/DEV/esp/esp-idf/components/hal/include -I /Users/felix/DEV/esp/esp-idf/components/esp_rom/include -I /Users/felix/DEV/esp/esp-idf/components/esp_rom/esp32c6/include -I /Users/felix/DEV/esp/esp-idf/components/esp_rom/esp32c6/include/esp32c6 -I /Users/felix/DEV/esp/esp-idf/components/esp_rom/esp32c6 -I /Users/felix/DEV/esp/esp-idf/components/esp_common/include -I /Users/felix/DEV/esp/esp-idf/components/esp_system/include -I /Users/felix/DEV/esp/esp-idf/components/esp_system/port/soc -I /Users/felix/DEV/esp/esp-idf/components/esp_system/port/include/riscv -I /Users/felix/DEV/esp/esp-idf/components/esp_system/port/include/private -I /Users/felix/DEV/esp/esp-idf/components/riscv/include -I /Users/felix/DEV/esp/esp-idf/components/lwip/include -I /Users/felix/DEV/esp/esp-idf/components/lwip/include/apps -I /Users/felix/DEV/esp/esp-idf/components/lwip/include/apps/sntp -I /Users/felix/DEV/esp/esp-idf/components/lwip/lwip/src/include -I /Users/felix/DEV/esp/esp-idf/components/lwip/port/include -I /Users/felix/DEV/esp/esp-idf/components/lwip/port/freertos/include -I /Users/felix/DEV/esp/esp-idf/components/lwip/port/esp32xx/include -I /Users/felix/DEV/esp/esp-idf/components/lwip/port/esp32xx/include/arch -I /Users/felix/DEV/esp/esp-idf/components/lwip/port/esp32xx/include/sys -I /Users/felix/DEV/esp/esp-idf/components/esp_driver_gpio/include -I /Users/felix/DEV/esp/esp-idf/components/esp_driver_spi/include -I /Users/felix/DEV/esp/esp-idf/components/esp_pm/include -I /Users/felix/DEV/esp/esp-idf/components/esp_driver_mcpwm/include -I /Users/felix/DEV/esp/esp-idf/components/esp_driver_rmt/include -I /Users/felix/DEV/esp/esp-idf/components/esp_driver_i2c/include -I /Users/felix/DEV/esp/esp-idf/components/esp_driver_uart/include -I /Users/felix/DEV/esp/esp-idf/components/vfs/include -I /Users/felix/DEV/esp/esp-idf/components/esp_timer/include -I /Users/felix/DEV/Swift/swift-quadro-package/components/Fusion/include -I /Users/felix/DEV/Swift/swift-quadro-package/components/VL53L1/core -I /Users/felix/DEV/Swift/swift-quadro-package/components/VL53L1/platform -I /Users/felix/DEV/esp/esp-idf/components/mbedtls/port/include -I /Users/felix/DEV/esp/esp-idf/components/mbedtls/mbedtls/include -I /Users/felix/DEV/esp/esp-idf/components/mbedtls/mbedtls/library -I /Users/felix/DEV/esp/esp-idf/components/mbedtls/esp_crt_bundle/include -I /Users/felix/DEV/esp/esp-idf/components/mbedtls/mbedtls/3rdparty/everest/include -I /Users/felix/DEV/esp/esp-idf/components/mbedtls/mbedtls/3rdparty/p256-m -I /Users/felix/DEV/esp/esp-idf/components/mbedtls/mbedtls/3rdparty/p256-m/p256-m -I /Users/felix/DEV/esp/esp-idf/components/driver/deprecated -I /Users/felix/DEV/esp/esp-idf/components/driver/i2c/include -I /Users/felix/DEV/esp/esp-idf/components/driver/touch_sensor/include -I /Users/felix/DEV/esp/esp-idf/components/driver/twai/include -I /Users/felix/DEV/esp/esp-idf/components/esp_ringbuf/include -I /Users/felix/DEV/esp/esp-idf/components/esp_driver_pcnt/include -I /Users/felix/DEV/esp/esp-idf/components/esp_driver_gptimer/include -I /Users/felix/DEV/esp/esp-idf/components/esp_driver_ana_cmpr/include -I /Users/felix/DEV/esp/esp-idf/components/esp_driver_i2s/include -I /Users/felix/DEV/esp/esp-idf/components/esp_driver_sdmmc/include -I /Users/felix/DEV/esp/esp-idf/components/sdmmc/include -I /Users/felix/DEV/esp/esp-idf/components/esp_driver_sdspi/include -I /Users/felix/DEV/esp/esp-idf/components/esp_driver_sdio/include -I /Users/felix/DEV/esp/esp-idf/components/esp_driver_dac/include -I /Users/felix/DEV/esp/esp-idf/components/esp_driver_tsens/include -I /Users/felix/DEV/esp/esp-idf/components/esp_driver_sdm/include -I /Users/felix/DEV/esp/esp-idf/components/esp_driver_ledc/include -I /Users/felix/DEV/esp/esp-idf/components/esp_driver_parlio/include -I /Users/felix/DEV/esp/esp-idf/components/esp_driver_usb_serial_jtag/include -I /Users/felix/DEV/esp/esp-idf/components/nvs_flash/include -I /Users/felix/DEV/esp/esp-idf/components/esp_partition/include -I /Users/felix/DEV/esp/esp-idf/components/bt/include/esp32c6/include -I /Users/felix/DEV/esp/esp-idf/components/bt/common/osi/include -I /Users/felix/DEV/esp/esp-idf/components/bt/common/api/include/api -I /Users/felix/DEV/esp/esp-idf/components/bt/common/btc/profile/esp/blufi/include -I /Users/felix/DEV/esp/esp-idf/components/bt/common/btc/profile/esp/include -I /Users/felix/DEV/esp/esp-idf/components/bt/common/hci_log/include -I /Users/felix/DEV/esp/esp-idf/components/bt/porting/include -I /Users/felix/DEV/esp/esp-idf/components/bt/porting/npl/freertos/include -I /Users/felix/DEV/esp/esp-idf/components/bt/porting/transport/include -I /Users/felix/DEV/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/include -I /Users/felix/DEV/esp/esp-idf/components/bt/host/nimble/nimble/nimble/include -I /Users/felix/DEV/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/ans/include -I /Users/felix/DEV/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/bas/include -I /Users/felix/DEV/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/dis/include -I /Users/felix/DEV/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/gap/include -I /Users/felix/DEV/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/gatt/include -I /Users/felix/DEV/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/hr/include -I /Users/felix/DEV/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/htp/include -I /Users/felix/DEV/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/ias/include -I /Users/felix/DEV/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/ipss/include -I /Users/felix/DEV/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/lls/include -I /Users/felix/DEV/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/prox/include -I /Users/felix/DEV/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/cts/include -I /Users/felix/DEV/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/tps/include -I /Users/felix/DEV/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/hid/include -I /Users/felix/DEV/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/sps/include -I /Users/felix/DEV/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/cte/include -I /Users/felix/DEV/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/util/include -I /Users/felix/DEV/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/store/ram/include -I /Users/felix/DEV/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/store/config/include -I /Users/felix/DEV/esp/esp-idf/components/bt/host/nimble/nimble/porting/nimble/include -I /Users/felix/DEV/esp/esp-idf/components/bt/host/nimble/port/include -I /Users/felix/DEV/esp/esp-idf/components/bt/host/nimble/nimble/nimble/transport/include -I /Users/felix/DEV/esp/esp-idf/components/esp_wifi/include -I /Users/felix/DEV/esp/esp-idf/components/esp_wifi/include/local -I /Users/felix/DEV/esp/esp-idf/components/esp_wifi/wifi_apps/include -I /Users/felix/DEV/esp/esp-idf/components/esp_wifi/wifi_apps/nan_app/include -I /Users/felix/DEV/esp/esp-idf/components/esp_event/include -I /Users/felix/DEV/esp/esp-idf/components/esp_phy/include -I /Users/felix/DEV/esp/esp-idf/components/esp_phy/esp32c6/include -I /Users/felix/DEV/esp/esp-idf/components/esp_netif/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/dotprod/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/support/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/support/mem/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/windows/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/windows/hann/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/windows/blackman/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/windows/blackman_harris/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/windows/blackman_nuttall/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/windows/nuttall/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/windows/flat_top/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/iir/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/fir/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/math/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/math/add/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/math/sub/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/math/mul/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/math/addc/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/math/mulc/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/math/sqrt/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/matrix/mul/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/matrix/add/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/matrix/addc/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/matrix/mulc/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/matrix/sub/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/matrix/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/fft/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/dct/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/conv/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/common/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/matrix/mul/test/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/kalman/ekf/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__esp-dsp/modules/kalman/ekf_imu13states/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__led_strip/include -I /Users/felix/DEV/Swift/swift-quadro-package/managed_components/espressif__led_strip/interface -color-diagnostics -Xcc -fcolor-diagnostics -module-link-name main -static -Osize -D ESP_PLATFORM -D IDF_VER=\"v5.4-dirty\" -D MBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -D SOC_MMU_PAGE_SIZE=CONFIG_MMU_PAGE_SIZE -D SOC_XTAL_FREQ_MHZ=CONFIG_XTAL_FREQ -D _GLIBCXX_HAVE_POSIX_SEMAPHORE -D _GLIBCXX_USE_POSIX_SEMAPHORE -D _GNU_SOURCE -D _POSIX_READER_WRITER_LOCKS -D CHIP_HAVE_CONFIG_H -function-sections -disable-availability-checking -enable-single-module-llvm-emission -enable-experimental-feature Embedded -empty-abi-descriptor -Xcc -fno-exceptions -Xcc -fno-rtti -Xcc -DCHIP_HAVE_CONFIG_H -Xcc -DESP_PLATFORM -Xcc -DIDF_VER=v5.3-dev-2815-gbe06a6f5ff-dirty -Xcc -DLV_CONF_INCLUDE_SIMPLE -Xcc -DMBEDTLS_CONFIG_FILE=mbedtls/esp_config.h -Xcc -DMD5_ENABLED=1 -Xcc -DSERIAL_FLASHER_BOOT_HOLD_TIME_MS=50 -Xcc -DSERIAL_FLASHER_RESET_HOLD_TIME_MS=100 -Xcc -DSOC_MMU_PAGE_SIZE=CONFIG_MMU_PAGE_SIZE -Xcc -DSOC_XTAL_FREQ_MHZ=CONFIG_XTAL_FREQ -Xcc -DUNITY_INCLUDE_CONFIG_H -Xcc -D_GLIBCXX_HAVE_POSIX_SEMAPHORE -Xcc -D_GLIBCXX_USE_POSIX_SEMAPHORE -Xcc -D_POSIX_READER_WRITER_LOCKS -Xcc -I/Users/felix/.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/lib/gcc/riscv32-esp-elf/14.2.0/include -Xcc -I/Users/felix/.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/lib/gcc/riscv32-esp-elf/14.2.0/include-fixed -Xcc -I/Users/felix/.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/riscv32-esp-elf/include -Xcc -I/Users/felix/.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/riscv32-esp-elf/include/c++/14.2.0 -Xcc -I/Users/felix/.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/riscv32-esp-elf/include/c++/14.2.0/riscv32-esp-elf/rv32imac_zicsr_zifencei/ilp32 -Xcc -I/Users/felix/.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/riscv32-esp-elf/include/c++/14.2.0/backward -Xcc -I/Users/felix/.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/lib/gcc/riscv32-esp-elf/14.2.0/include -Xcc -I/Users/felix/.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/lib/gcc/riscv32-esp-elf/14.2.0/include-fixed -Xcc -I/Users/felix/.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/riscv32-esp-elf/include -no-auto-bridging-header-chaining -module-name __idf_main -in-process-plugin-server-path /Library/Developer/Toolchains/swift-latest.xctoolchain/usr/lib/swift/host/libSwiftInProcPluginServer.dylib -plugin-path /Library/Developer/Toolchains/swift-latest.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Library/Developer/Toolchains/swift-latest.xctoolchain/usr/local/lib/swift/host/plugins -enable-default-cmo -parse-as-library -num-threads 10 -o esp-idf/main/CMakeFiles/__idf_main.dir/__/Sources/ApusFC/AHRS.swift.obj -o esp-idf/main/CMakeFiles/__idf_main.dir/__/Sources/ApusFC/Bluetooth.swift.obj -o esp-idf/main/CMakeFiles/__idf_main.dir/__/Sources/ApusFC/Button.swift.obj -o esp-idf/main/CMakeFiles/__idf_main.dir/__/Sources/ApusFC/CRSF.swift.obj -o esp-idf/main/CMakeFiles/__idf_main.dir/__/Sources/ApusFC/DShot.swift.obj -o esp-idf/main/CMakeFiles/__idf_main.dir/__/Sources/ApusFC/DroneController.swift.obj -o esp-idf/main/CMakeFiles/__idf_main.dir/__/Sources/ApusFC/ESPIDFUtils.swift.obj -o esp-idf/main/CMakeFiles/__idf_main.dir/__/Sources/ApusFC/Kalman.swift.obj -o esp-idf/main/CMakeFiles/__idf_main.dir/__/Sources/ApusFC/LED.swift.obj -o esp-idf/main/CMakeFiles/__idf_main.dir/__/Sources/ApusFC/LT1Filter.swift.obj -o esp-idf/main/CMakeFiles/__idf_main.dir/__/Sources/ApusFC/Logger.swift.obj -o esp-idf/main/CMakeFiles/__idf_main.dir/__/Sources/ApusFC/MCPWM.swift.obj -o esp-idf/main/CMakeFiles/__idf_main.dir/__/Sources/ApusFC/MSP.swift.obj -o esp-idf/main/CMakeFiles/__idf_main.dir/__/Sources/ApusFC/Matek.swift.obj -o esp-idf/main/CMakeFiles/__idf_main.dir/__/Sources/ApusFC/MotorController.swift.obj -o esp-idf/main/CMakeFiles/__idf_main.dir/__/Sources/ApusFC/NVS.swift.obj -o esp-idf/main/CMakeFiles/__idf_main.dir/__/Sources/ApusFC/PID.swift.obj -o esp-idf/main/CMakeFiles/__idf_main.dir/__/Sources/ApusFC/Receiver.swift.obj -o esp-idf/main/CMakeFiles/__idf_main.dir/__/Sources/ApusFC/SPI.swift.obj -o esp-idf/main/CMakeFiles/__idf_main.dir/__/Sources/ApusFC/System.swift.obj -o esp-idf/main/CMakeFiles/__idf_main.dir/__/Sources/ApusFC/Telemetry.swift.obj -o esp-idf/main/CMakeFiles/__idf_main.dir/__/Sources/ApusFC/ToF.swift.obj
1.      Apple Swift version 6.2-dev (LLVM 54efc8c61424404, Swift 2f920ceb5abcb13)
2.      Compiling with effective version 5.10
3.      While evaluating request ASTLoweringRequest(Lowering AST to SIL for module __idf_main)
4.      While silgen emitFunction SIL function "@$e10__idf_main1AV3fooyyFZ".
 for 'foo()' (at /Users/felix/DEV/Swift/swift-quadro-package/Sources/ApusFC/System.swift:8:3)
5.      Assertion failed: (!operand->getType().isTrivial(getFunction()) && "Should not be passing trivial values to this api. Use instead " "emitDestroyValueOperation"), function createDestroyValue at SILBuilder.h:1456.
|       (to display assertion configuration options: -Xllvm -assert-help)
 #0 0x000000010a83d030 (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x1059fd030)
 #1 0x000000010a83b75c (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x1059fb75c)
 #2 0x000000010a83d678 (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x1059fd678)
 #3 0x0000000192c94624 (/usr/lib/system/libsystem_platform.dylib+0x1804ac624)
 #4 0x0000000192c5a88c (/usr/lib/system/libsystem_pthread.dylib+0x18047288c)
 #5 0x0000000192b63c60 (/usr/lib/system/libsystem_c.dylib+0x18037bc60)
 #6 0x00000001069a5218 (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x101b65218)
 #7 0x00000001069a51d4 (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x101b651d4)
 #8 0x00000001056417a0 (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x1008017a0)
 #9 0x000000010569ade4 (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x10085ade4)
#10 0x000000010571d8c4 (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x1008dd8c4)
#11 0x000000010571e5f8 (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x1008de5f8)
#12 0x0000000105748bb4 (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x100908bb4)
#13 0x00000001056b113c (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x10087113c)
#14 0x00000001056b2118 (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x100872118)
#15 0x00000001056af950 (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x10086f950)
#16 0x00000001057ca014 (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x10098a014)
#17 0x00000001057c66cc (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x1009866cc)
#18 0x00000001057c65ac (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x1009865ac)
#19 0x00000001056b498c (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x10087498c)
#20 0x00000001056b4ea8 (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x100874ea8)
#21 0x00000001057b3ac8 (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x100973ac8)
#22 0x00000001056b8f1c (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x100878f1c)
#23 0x00000001056b5214 (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x100875214)
#24 0x00000001050e8580 (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x1002a8580)
#25 0x00000001050f4948 (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x1002b4948)
#26 0x00000001050ea044 (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x1002aa044)
#27 0x00000001050e9800 (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x1002a9800)
#28 0x0000000104e76f84 (/Users/felix/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend+0x100036f84)
#29 0x00000001928bab98
```

### Expected behavior

Compiles without crashing.

### Environment

Apple Swift version 6.2-dev (LLVM 54efc8c61424404, Swift 2f920ceb5abcb13)

Build Target: riscv32-none-none-eabi

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jckarter**
An oversight from https://github.com/swiftlang/swift/pull/82288. Fixes #82368 / rdar://153837014.

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci Please test

File: lib/SILGen/SILGenApply.cpp [hunk 1]
```diff
@@ -3622,8 +3622,9 @@ SILGenFunction::tryEmitAddressableParameterAsAddress(ArgumentSource &&arg,
     auto vd = cast<VarDecl>(memberStorage);
     // TODO: Is it possible and/or useful for class storage to be
     // addressable?
-    if (!vd->getDeclContext()->getInnermostTypeContext()
-         ->getDeclaredTypeInContext()->getStructOrBoundGenericStruct()) {
+    if (!vd->isInstanceMember()
+        || !vd->getDeclContext()->getInnermostTypeContext()
+             ->getDeclaredTypeInContext()->getStructOrBoundGenericStruct()) {
```
Comment (slavapestov) [inline lib/SILGen/SILGenApply.cpp]: is getInnermostTypeContext() correct to check here at all? This is not an instance property for instance:

```
struct S {
  func f() {
    var x = ... // innermost type context of `x` is a struct; why does that matter at all?
  }
}
```

I think you can just do `isa<StructDecl>(vd->getDeclContext())`?

**Comment by jckarter** [comment]
@swift-ci Please test
