### PR TITLE
[Sema] Don't force interface type of VarDecl in getIUOReferenceKind

### LINKED ISSUE #88530: Sema: "Cannot type-check PatternBindingDecl without closure context" — IUO binding with unbound generic type inside a closure
### Description

Swift main crashes with `Cannot type-check PatternBindingDecl without closure context` (in `swift::TypeChecker::typeCheckBinding`, `lib/Sema/TypeCheckConstraints.cpp`) when, inside a closure, a pattern binding is declared with an implicitly-unwrapped-optional type whose type spelling is an unbound generic member (outer generic parameters elided).

Regression from #85141 (commit `c8fd93e`, merged 2026-03-04), which enabled a previously commented-out `ABORT(\"Cannot type-check PatternBindingDecl without closure context\")` that had been guarded by a FIXME. The `InterfaceTypeRequest → NamingPatternRequest → PatternBindingEntryRequest` chain fires for the inner binding before the enclosing closure has been type-checked, tripping the new assertion.

### Minimal reproduction

```swift
struct G<T> { struct I {} }
let f = { var x: G.I! = G<Int>.I(); _ = x }
```

```
\$ swiftc -typecheck repro.swift
Abort: function typeCheckBinding at TypeCheckConstraints.cpp:677
Cannot type-check PatternBindingDecl without closure context
```

Required ingredients (removing any one avoids the crash):
1. IUO (`!`) type annotation.
2. Annotation is an unbound generic member (`G.I`, not `G<Int>.I`).
3. Binding is inside a closure (top-level or plain `func` is fine).

No `consume`, no `~Copyable`, no concurrency, no Swift 6 mode, no optimization required. Reproduces with bare `swiftc -typecheck`.

### Stack (abridged)

```
PatternBindingEntryRequest
  TypeChecker::typeCheckBinding   ← ABORT here
    ConstraintSystem::solve
      ConstraintSystem::bindOverloadType
        OverloadChoice::getIUOReferenceKind
          InterfaceTypeRequest
            NamingPatternRequest
              PatternBindingEntryRequest   ← re-entered for the inner binding
```

(`OverloadChoice::getIUOReferenceKind` demands the interface type of the inner IUO binding during constraint solving of the outer closure; the subsequent `NamingPatternRequest` forces the inner `PatternBindingEntryRequest` outside the closure's type-check context.)

### Environment

- Swift 6.4-dev, commit `cf7481b28905381` / LLVM `b8889af02f47cf7`
- Reproduced on both Linux (aarch64/x86_64, `swiftlang/swift:nightly-jammy`) and macOS.
- Originally hit in swift-async-algorithms CI:
  - Linux: https://ci.swift.org/job/pr-swift-async-algorithms-linux/51/consoleText
  - macOS: https://ci.swift.org/job/pr-swift-async-algorithms-macos/56/console

### Workaround

Spell the generic arguments:
```swift
let x: G<Int>.I! = G<Int>.I()
```
or split the declaration:
```swift
var x: G.I!
x = G<Int>.I()
```

### Note

PR #85141 also enabled a sister `ASSERT(...)` in `lib/Sema/TypeCheckDecl.cpp`'s `NamingPatternRequest::evaluate`; other IUO-in-closure shapes may trip that one instead.

cc @hamishknight

### PR DESCRIPTION
**Pull request by azarovalex**
- Explanation: Fixes an assertion failure that could occur when using an implicitly-unwrapped optional with an unbound generic type for a local variable within a closure.
- Scope: Affects the use of implicitly-wrapped optional local vars in closures
- Issue: #88530
- Risk: Low, the existing logic would never permit a VarDecl to be anything other than `IUOReferenceKind::Value` since the compiler rejects any IUO VarDecl that isn't a top-level optional, this change just bypasses the need to query the interface type
- Testing: Added test to test suite

---

Fixes #88530.

## The crash

```swift
struct G<T> { struct I {} }
let f = { var x: G.I! = G<Int>.I(); _ = x }
```

```
Abort: function typeCheckBinding at TypeCheckConstraints.cpp:677
Cannot type-check PatternBindingDecl without closure context
```

Regression from #85141 (the tightened `ABORT` in `typeCheckBinding`).

## Root cause

While the solver is mid-closure and encounters the reference to `x`, `OverloadChoice::getIUOReferenceKind` calls `decl->getInterfaceType()` on the inner `VarDecl` (at `ConstraintSystem.cpp:1985`) to distinguish `var x: T!` from `var x: () -> T!`. For this `VarDecl`:

- `InterfaceTypeRequest::evaluate` (`TypeCheckDecl.cpp:2476`) calls `VD->getNamingPattern()`
- `NamingPatternRequest::evaluate` (`TypeCheckDecl.cpp:2722`) calls `PBD->getCheckedPatternBindingEntry(i)`
- which re-enters `TypeChecker::typeCheckPatternBinding` on the inner binding from **outside** the closure's own type-check context — exactly what #85141 forbids.

**Why only with unbound generic.** When the annotation is spelled fully (`G<Int>.I!`), the pattern type is resolvable syntactically, so during the closure's own pass `coercePatternToType` calls `setNamingPattern` on `x` (`TypeCheckPattern.cpp:1223`); later `getInterfaceType()` finds the naming pattern cached and never re-invokes `PatternBindingEntryRequest`. With an unbound generic annotation (`G.I!`), the pattern can't be resolved without initializer inference, so `setNamingPattern` isn't called on that path, and the deferred `getInterfaceType()` re-enters the pattern-binding type-check.

## Fix

`VarDecl` (and its subclass `ParamDecl`) can never have an IUO on a function return — that spelling is only valid for `FuncDecl` and `SubscriptDecl`. So the answer is already known: `IUOReferenceKind::Value`. Short-circuit before forcing the interface type.

```cpp
if (isa<VarDecl>(decl))
  return IUOReferenceKind::Value;
```

This targets the crash narrowly and avoids cutting across the invariant #85141 is trying to enforce. It's consistent with the preference to not eagerly force interface types during constraint solving.

## Test

Added a regression case to `test/Constraints/iuo.swift`.

## Notes

- PR #85141 also enabled a sister `ASSERT(...)` in `NamingPatternRequest::evaluate` (`TypeCheckDecl.cpp:2749`). This fix doesn't touch that path; if other IUO-in-closure shapes trip the sister assertion, they'd be a separate issue.
- I haven't been able to run the full test suite locally (no stage2 build); relying on CI here.

cc @hamishknight

### CODE REVIEW

File: lib/Sema/ConstraintSystem.cpp [hunk 1]
```diff
@@ -1981,6 +1981,16 @@ OverloadChoice::getIUOReferenceKind(ConstraintSystem &cs,
...
 
+  // A variable or parameter spelled with an IUO type (`x: T!`) is always an
+  // IUO value; only functions and subscripts can carry an IUO on the return.
+  // Short-circuit here so we don't force the declaration's interface type.
+  // Doing so while the solver is mid-closure can re-enter
+  // `typeCheckPatternBinding` from outside the closure's own type-check
+  // context and trip the assertion in `TypeChecker::typeCheckBinding` (see
+  // https://github.com/swiftlang/swift/issues/88530).
+  if (isa<VarDecl>(decl))
+    return IUOReferenceKind::Value;
```
Comment (xedin) [inline lib/Sema/ConstraintSystem.cpp:1992]: Hm, what about `var x: () -> T!` then?

Comment (xedin) [reply lib/Sema/ConstraintSystem.cpp:1992]: Oh, we do reject this early so nevermind.

**Review by hamishknight — APPROVED** [review]
Thank you! This looks good to me

**Review by xedin — APPROVED** [review]

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
Going to mark this ready to review unless there's a reason you want to keep it a draft @azarovalex?

**Comment by azarovalex** [comment]
Oops, CI flagged an unexpected "never mutated" warning in the test, pushed a fix

**Comment by DougGregor** [comment]
@swift-ci please test source compatibility

**Comment by DougGregor** [comment]
@swift-ci please smoke test
