### PR TITLE
[SILOptimizer]: fix some missing use after consume diagnostics

### LINKED ISSUE #83277: Compiler fails to prevent accessing protocol extension members on consumed values
### Description

After a value is consumed, it's still possible to access protocol extension members on it. This happens for both protocol required members and non-required members, as long as they are not shadowed by struct's own implemenations.

### Reproduction

My original example:

```swift
func test() {
    let values = [1, 2, 3]
    var newValues = consume values
    newValues.append(4)
    
    //print(values.count) // this doesn't compile (as expected)
    //print(values[0]) // this doesn't compile (as expected)
    print(values.first!) // output: 1
    print(values.last!) // output: 3
}
```

User CrystDragon in Swift forums identified the general pattern to reproduce it:

```swift
protocol P {
    func bar() 
}
extension P {
    func bar() {}
    func baz() {}
}

struct A: P {
    let x: String = ""

    func foo() {}
}

func test() {
    let a = A()
    _ = consume a

    a.foo() // error, as expected
    a.bar() // no error, not as expected
    a.baz() // no error, not as expected
}
``` 

### Expected behavior

Compile should produce error

### Environment

$ swift --version
Swift version 6.2-dev (LLVM 5fbc818cf26c90b, Swift 2e1897356956e43)
Target: x86_64-unknown-linux-gnu
Build config: +assertions

### Additional information

Just in case some people might think `P.bar()` works because `P` has no data requirement, compiler fails to generate diagnostic for the following code too.

```swift
protocol P {
    var x: String { get }
    func bar()
}

extension P {
    func bar() { print(x) }
}

struct A: P {
    let x: String = ""
}

func test() {
    let a = A()
    _ = consume a

    a.bar() // no error, not as expected
}
```

### PR DESCRIPTION
**Pull request by jamieQ**
Updates ConsumeOperatorCopyableValuesChecker to identify store_borrow instructions as a liveness-affecting use so that patterns that would previously slip through undiagnosed are correctly identified. e.g.

```swift
func use<V>(_ v: borrowing V) {}

func f() {
  let a = A()
  _ = consume a
  use(a) // previously would not be diagnosed
}
```

Resolves https://github.com/swiftlang/swift/issues/83277

### CODE REVIEW

**Comment by jamieQ** [comment]
@swift-ci please smoke test

File: lib/SILOptimizer/Mandatory/ConsumeOperatorCopyableValuesChecker.cpp [hunk 1]
```diff
@@ -157,6 +157,8 @@ bool CheckerLivenessInfo::compute() {
               return false;
             }
           }
+        } else if (isa<StoreBorrowInst>(user)) {
+          liveness->updateForUse(user, /*lifetimeEnding*/ false);
```
Comment (jamieQ) [inline lib/SILOptimizer/Mandatory/ConsumeOperatorCopyableValuesChecker.cpp]: i copied the logic for the lexical borrow above, but it's not entirely clear to me if this is a conceptually correct solution (tests seem to pass, but they also passed before this change so 🤷 – well, the existing ones did, not the added cases). feedback appreciated if/when you have time – cc @nate-chandler @eeckstein

Comment (nate-chandler) [reply lib/SILOptimizer/Mandatory/ConsumeOperatorCopyableValuesChecker.cpp]: The comment `we are going to check its uses separately and emit diagnostics for it` doesn't apply here, we need to add the whole range in which the value is borrowed to liveness as in the non-lexical case above:
```
if (liveness->updateForBorrowingOperand(use) !=
                InnerBorrowKind::Contained) {
               return false;
             }
```

Comment (jamieQ) [reply lib/SILOptimizer/Mandatory/ConsumeOperatorCopyableValuesChecker.cpp]: @nate-chandler slightly tangential, but do you happen to know if the implementation of `updateForBorrowingOperand()` is robust enough that the handling of this case could (or should) be refactored to only special case the lexical `begin_borrow`s, and have everything else take the alternate path? i.e. could the 'FIXME' below be resolved with such an approach? or should this just special case `store_borrow`?

Comment (nate-chandler) [reply lib/SILOptimizer/Mandatory/ConsumeOperatorCopyableValuesChecker.cpp]: I suggest landing the store_borrow fix first and then investigating more involved changes separately, ideally together with Swift source test cases that aren't handled properly.  

At that point, yes, this would be a good starting point:
```
      case OperandOwnership::Borrow: {
        auto *bbi = dyn_cast<BeginBorrowInst>(user);
        if (bbi && bbi->isFromVarDecl()) {
          // If we have a begin_borrow [var_decl], we are going to check its
          // uses separately and emit diagnostics for it. So we just need to
          // the begin_borrow to liveness.
          //
          // NOTE: We know that semantically the use VarDecl must have a
          // separate lifetime from the base VarDecl that we are processing. We
          // do not want to include those uses as transitive uses of our base
          // VarDecl lifetime. We just want to treat the formation of the new
          // variable as a use. Thus we only include the begin_borrow itself as
          // the use.
          liveness->updateForUse(bbi, false /*lifetime ending*/);
          break;
        }
        // Otherwise, try to update liveness for a borrowing operand
        // use. This will make it so that we add the end_borrows of the
        // liveness use. If we have a reborrow here, we will bail.
        if (liveness->updateForBorrowingOperand(use) !=
            InnerBorrowKind::Contained) {
          return false;
        }
        break;
      }
```
Note in particular this changes to `[var_decl]` which is the flag that's actually looked for in the begin_borrow instructions added to the worklist.

**Comment by jamieQ** [comment]
@swift-ci please smoke test

**Review by nate-chandler — APPROVED** [review]
Looks good--thanks!

**Comment by xwu** [comment]
@nate-chandler Worthwhile cherrypicking for 6.2?

**Comment by nate-chandler** [comment]
@jamieQ Please raise a PR to cherry-pick this to 6.2 to give the branch managers the option of taking this patch .
