### PR TITLE
[Sema]: improve noasync diagnostics in defer statement bodies

### LINKED ISSUE #73614: Calling `noasync` function inside a `defer`
### Description

When annotating a function as `noasync`, the compiler should produce a warning when calling that function from an async context - such as an async function. When calling a `noasync` function from a `defer` block inside an async function, the warning is not produced which can lead to unexpected behaviour.

### Reproduction

```swift
@available(*, noasync, message: "Don't call async contexts")
func somethingSync() {
  print("Sync")
}

func asyncFunc() async {
  somethingSync() // This produces a warning

  defer {
    somethingSync() // This does not produce a warning but should
  }

  print("Async")
}
```

### Expected behavior

The compiler should produce 2 warnings, for each call of `somethingSync()` inside `asyncFunc`. It currently only produces a warning for the call outside the defer block

### Environment

swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jamieQ**
updates noasync diagnostics in TypeCheckAvailability.cpp to diagnose defer bodies as if they had the same `isAsyncContext()` value as their nearest non-defer parent scope.

resolves: https://github.com/apple/swift/issues/73614 and rdar://128102432

### CODE REVIEW

File: lib/Sema/TypeCheckAvailability.cpp [hunk 1]
```diff
@@ -397,6 +397,26 @@ static bool shouldAllowReferenceToUnavailableInSwiftDeclaration(
...
+      return shouldTreatDeclContextAsAsyncForDiagnostics(DC->getParent());
+    } else {
+      return DC->isAsyncContext();
+    }
+  }
+
+  default:
+    return DC->isAsyncContext();
+  }
+}
```
Comment (tshortli) [inline lib/Sema/TypeCheckAvailability.cpp:418]: This is a matter of style and up to you as the author, but I'd prefer a more compact implementation since we only care about function decl contexts:
```suggestion
static bool shouldTreatDeclContextAsAsyncForDiagnostics(const DeclContext *DC) {
  if (auto *FD = dyn_cast<FuncDecl>(DC->getAsDecl())) {
    // If this is a defer body, we should delegate the determination
    // to its parent.
    if (FD->isDeferBody())
      return shouldTreatDeclContextAsAsyncForDiagnostics(DC->getParent());
  }
  return DC->isAsyncContext();
}
```

File: test/attr/attr_availability_noasync.swift [hunk 2]
```diff
@@ -27,6 +27,15 @@ actor IOActor {
...
 @available(SwiftStdlib 5.5, *)
 func asyncFunc() async {
+    defer {
+        defer {
+            // expected-warning@+1 {{global function 'basicNoAsync' is unavailable from asynchronous contexts; this is an error in the Swift 6 language mode}}
+            basicNoAsync()
+        }
+        // expected-warning@+1 {{global function 'basicNoAsync' is unavailable from asynchronous contexts; this is an error in the Swift 6 language mode}}
+        basicNoAsync()
+    }
```
Comment (tshortli) [inline test/attr/attr_availability_noasync.swift:37]: Some additional test cases that would be useful to have to ensure the walk up the context hierarchy remains correct would be to test a `defer` inside:
- either a sync or an async closure or local function
- inside either a sync or an async function.
I think there are 8 total combinations there, though it may be that some of them are redundant.

**Review by tshortli — COMMENTED** [review]
Thanks for fixing this! I'll dig up the radar to associate with it, I think there's one.

**Comment by tshortli** [comment]
@swift-ci please smoke test

File: lib/Sema/TypeCheckAvailability.cpp (hunk 1 above)
Comment (jamieQ) [reply lib/Sema/TypeCheckAvailability.cpp:418]: thanks for the suggestion, that seems like a nicer formulation to me. i ran into some issues with things crashing using a similar approach b/c i _think_ `DC->getAsDecl()` may return null in some circumstances (function decl in top level code?) and `dyn_cast` doesn't like null arguments. will rework to something like this with an additional null check.

**Review by tshortli — APPROVED** [review]

**Comment by tshortli** [comment]
@swift-ci please test

**Comment by tshortli** [comment]
@jamieQ we'd like to take this on `release/6.0`, could you cherry pick it to a PR based on that branch?
