### PR TITLE
Ensure we check for thrown error types when resolving custom derivatives

### LINKED ISSUE #86998: [AutoDiff] Lacking diagnostics for invalid custom derivative having incompatible throwing error type
### Description

Consider the following code. It leads to assertion in emitApplyWithRethrow() as inner and outer error types do not match. Instead we need to reject this code

### Reproduction

```swift
import _Differentiation

extension Array where Element: Differentiable {
    @differentiable(reverse, wrt: self)
    public func differentiableThrowingMap<Result: Differentiable, E: Error>(
        _ body: @differentiable(reverse) (Element) throws(E) -> Result
    ) throws(E) -> [Result] {
        try map(body)
    }

    @derivative(of: differentiableThrowingMap)
    public func _vjpDifferentiableThrowingMap<Result: Differentiable, E: Error>(
        _ body: @differentiable(reverse) (Element) throws(E) -> Result
    ) throws -> ( // succeeds when turned into throws(E)
        value: [Result],
        pullback: (Array<Result>.TangentVector) -> Array.TangentVector
    ) {
        let count = self.count
        var values: [Result] = []
        var pullbacks: [(Result.TangentVector) -> Element.TangentVector] = []
        values.reserveCapacity(count)
        pullbacks.reserveCapacity(count)
        for x in self {
            let (y, pb) = try valueWithPullback(at: x, of: body)
            values.append(y)
            pullbacks.append(pb)
        }
        func pullback(_ tans: Array<Result>.TangentVector) -> Array.TangentVector {
            .init(zip(tans.base, pullbacks).map { tan, pb in pb(tan) })
        }
        return (value: values, pullback: pullback)
    }
}
```

### Stack dump

```text
swift-frontend: /home/build-user/swift/lib/SILGen/SILGenApply.cpp:6437: SILValue swift::Lowering::SILGenFunction::emitApplyWithRethrow(SILLocation, SILValue, SILType, SubstitutionMap, ArrayRef<SILValue>): Assertion `outerErrorType == SILType::getExceptionType(getASTContext())' failed.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /cefs/f8/f8129916841d04cc8c4b5bfc_swift-nightly/usr/bin/swift-frontend -frontend -S -primary-file <source> -target x86_64-unknown-linux-gnu -disable-objc-interop -no-color-diagnostics -Xcc -fno-color-diagnostics -g -debug-info-format=dwarf -dwarf-version=4 -empty-abi-descriptor -enable-anonymous-context-mangled-names -file-compilation-dir /app -Xllvm --x86-asm-syntax=intel -no-auto-bridging-header-chaining -module-name output -in-process-plugin-server-path /cefs/f8/f8129916841d04cc8c4b5bfc_swift-nightly/usr/lib/swift/host/libSwiftInProcPluginServer.so -plugin-path /cefs/f8/f8129916841d04cc8c4b5bfc_swift-nightly/usr/lib/swift/host/plugins -plugin-path /cefs/f8/f8129916841d04cc8c4b5bfc_swift-nightly/usr/local/lib/swift/host/plugins -o /app/output.s
1.	Swift version 6.3-dev (LLVM c480caf3dc1c3ea, Swift 1e00daa140adf86)
2.	Compiling with effective version 5.10
3.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for file "<source>")
 #0 0x0000647751933e98 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/cefs/f8/f8129916841d04cc8c4b5bfc_swift-nightly/usr/bin/swift-frontend+0x8b02e98)
 #1 0x0000647751931685 llvm::sys::RunSignalHandlers() (/cefs/f8/f8129916841d04cc8c4b5bfc_swift-nightly/usr/bin/swift-frontend+0x8b00685)
 #2 0x0000647751934c41 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #3 0x000076e8e9242520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x000076e8e92969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x000076e8e9242476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x000076e8e92287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x000076e8e922871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x000076e8e9239e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x000064774a2146be swift::Lowering::SILGenFunction::emitApplyWithRethrow(swift::SILLocation, swift::SILValue, swift::SILType, swift::SubstitutionMap, llvm::ArrayRef<swift::SILValue>) crtstuff.c:0:0
#10 0x000064774a19c28c swift::Lowering::SILGenModule::getOrCreateCustomDerivativeThunk(swift::AbstractFunctionDecl*, swift::SILFunction*, swift::SILFunction*, swift::AutoDiffConfig const&, swift::AutoDiffDerivativeFunctionKind) crtstuff.c:0:0
#11 0x000064774a0b0b32 swift::Lowering::SILGenModule::emitDifferentiabilityWitness(swift::AbstractFunctionDecl*, swift::SILFunction*, swift::DifferentiabilityKind, swift::AutoDiffConfig const&, swift::SILFunction*, swift::SILFunction*, swift::DeclAttribute const*) crtstuff.c:0:0
#12 0x000064774a0b1406 swift::Lowering::SILGenModule::emitAbstractFuncDecl(swift::AbstractFunctionDecl*) crtstuff.c:0:0
#13 0x000064774a0ad094 swift::Lowering::SILGenModule::emitFunction(swift::FuncDecl*) crtstuff.c:0:0
#14 0x000064774a1eebba SILGenExtension::visitFuncDecl(swift::FuncDecl*) crtstuff.c:0:0
#15 0x000064774a1e9478 SILGenExtension::emitExtension(swift::ExtensionDecl*) crtstuff.c:0:0
#16 0x000064774a1e93cd swift::Lowering::SILGenModule::visitExtensionDecl(swift::ExtensionDecl*) crtstuff.c:0:0
#17 0x000064774a0b3a33 swift::Lowering::SILGenModule::emitSourceFile(swift::SourceFile*) crtstuff.c:0:0
#18 0x000064774a0b41a4 swift::ASTLoweringRequest::evaluate(swift::Evaluator&, swift::ASTLoweringDescriptor) const (/cefs/f8/f8129916841d04cc8c4b5bfc_swift-nightly/usr/bin/swift-frontend+0x12831a4)
#19 0x000064774a1cdac6 swift::SimpleRequest<swift::ASTLoweringRequest, std::unique_ptr<swift::SILModule, std::default_delete<swift::SILModule>> (swift::ASTLoweringDescriptor), (swift::RequestFlags)17>::evaluateRequest(swift::ASTLoweringRequest const&, swift::Evaluator&) crtstuff.c:0:0
#20 0x000064774a0b8f65 swift::ASTLoweringRequest::OutputType swift::Evaluator::getResultUncached<swift::ASTLoweringRequest, swift::ASTLoweringRequest::OutputType swift::evaluateOrFatal<swift::ASTLoweringRequest>(swift::Evaluator&, swift::ASTLoweringRequest)::'lambda'()>(swift::ASTLoweringRequest const&, swift::ASTLoweringRequest::OutputType swift::evaluateOrFatal<swift::ASTLoweringRequest>(swift::Evaluator&, swift::ASTLoweringRequest)::'lambda'()) crtstuff.c:0:0
#21 0x000064774a0b4a7f swift::performASTLowering(swift::FileUnit&, swift::Lowering::TypeConverter&, swift::SILOptions const&, swift::IRGenOptions const*) (/cefs/f8/f8129916841d04cc8c4b5bfc_swift-nightly/usr/bin/swift-frontend+0x1283a7f)
#22 0x000064774982e362 swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*, llvm::ArrayRef<char const*>) (/cefs/f8/f8129916841d04cc8c4b5bfc_swift-nightly/usr/bin/swift-frontend+0x9fd362)
#23 0x0000647749845c3a withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) FrontendTool.cpp:0:0
#24 0x00006477498340b9 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*, llvm::ArrayRef<char const*>) FrontendTool.cpp:0:0
#25 0x0000647749830d1e swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) (/cefs/f8/f8129916841d04cc8c4b5bfc_swift-nightly/usr/bin/swift-frontend+0x9ffd1e)
#26 0x000064774955b7fc swift::mainEntry(int, char const**) (/cefs/f8/f8129916841d04cc8c4b5bfc_swift-nightly/usr/bin/swift-frontend+0x72a7fc)
#27 0x000076e8e9229d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#28 0x000076e8e9229e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#29 0x000064774955a6e5 _start (/cefs/f8/f8129916841d04cc8c4b5bfc_swift-nightly/usr/bin/swift-frontend+0x7296e5)

*** Signal 6: Backtracing from 0x76e8e931e8fd... done ***

*** Program crashed: Aborted at 0x0000280000000001 ***

Platform: x86_64 Linux (Ubuntu 22.04.5 LTS)

Thread 0 "swift-frontend" crashed:

  0  0x000076e8e931e8fd <unknown> in libc.so.6
...


Registers:

rax 0x0000000000000000  0
rdx 0x0000000000000006  6
rcx 0x000076e8e931e8fd  48 3d 01 f0 ff ff 73 01 c3 48 8b 0d 03 b5 0f 00  H=·ðÿÿs·ÃH···µ··
rbx 0x0000000000000006  6
rsi 0x0000000000000001  1
rdi 0x0000000000000001  1
rbp 0x0000000000000001  1
rsp 0x000064776ab1f5e8  6b 4c 93 51 77 64 00 00 70 f8 b1 6a 77 64 00 00  kL·Qwd··pø±jwd··
 r8 0x000064776ab1f870  06 00 00 00 00 00 00 00 fa ff ff ff 00 00 00 00  ········úÿÿÿ····
 r9 0x000064776ab1f870  06 00 00 00 00 00 00 00 fa ff ff ff 00 00 00 00  ········úÿÿÿ····
r10 0x000064776ab1f870  06 00 00 00 00 00 00 00 fa ff ff ff 00 00 00 00  ········úÿÿÿ····
r11 0x0000000000000246  582
r12 0x0000000000000000  0
r13 0x0000000000000000  0
r14 0x0000000000000000  0
r15 0x000064776ab1f5f8  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ················
rip 0x000076e8e931e8fd  48 3d 01 f0 ff ff 73 01 c3 48 8b 0d 03 b5 0f 00  H=·ðÿÿs·ÃH···µ··

rflags 0x0000000000000246  ZF PF

cs 0x0033  fs 0x0000  gs 0x0000


Images (27 omitted):

0x000076e8e9200000–0x000076e8e93bc3c1 4f7b0c955c3d81d7cac1501a2498b69d1d82bfe7 libc.so.6 /lib/x86_64-linux-gnu/libc.so.6

Backtrace took 0.00s

Program terminated with signal: SIGSEGV
Compiler returned: 139
```

### Expected behavior

Proper diagnostics

### Environment

Swift version 6.3-dev (LLVM c480caf3dc1c3ea, Swift 1e00daa140adf86)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by asl**
Fixes #86998

### CODE REVIEW

**Comment by asl** [comment]
Tagging @JaapWijnen

**Comment by asl** [comment]
@swift-ci please test

File: test/AutoDiff/compiler_crashers_fixed/issue-86998-incompatible-thrown-types.swift [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+      _ body: @differentiable(reverse) (Element) throws(E) -> Result
+    ) throws -> [Result] {
+        try map(body)
+    }
+
+  // expected-error @+1 {{referenced declaration 'differentiableThrowingMap' could not be resolved}}
+    @derivative(of: differentiableThrowingMap)
+    public func _vjpDifferentiableThrowingMap<Result: Differentiable, E: Error>(
+        _ body: @differentiable(reverse) (Element) throws(E) -> Result
+  ) throws(E) -> ( // succeeds when turned into throws(E)
```
Comment (kovdan01) [inline test/AutoDiff/compiler_crashers_fixed/issue-86998-incompatible-thrown-types.swift]: Have you meant to have just `throws` here instead of `throws(E)` (just as in your reproducer in #86998)?

As far as I understood, there was no issue when we had `throws(E)` here, so that's not the case which is fixed by this patch. But I might have misunderstood your point - I would be glad if you could explain it so things become clearer.

Comment (asl) [reply test/AutoDiff/compiler_crashers_fixed/issue-86998-incompatible-thrown-types.swift]: Oh, indeed, I tested other combinations and committed the opposite version :)

**Comment by asl** [comment]
@swift-ci please test

File: test/AutoDiff/compiler_crashers_fixed/issue-86998-incompatible-thrown-types.swift (hunk 1 above)
Comment (asl) [reply test/AutoDiff/compiler_crashers_fixed/issue-86998-incompatible-thrown-types.swift]: Updated

**Comment by asl** [comment]
@swift-ci please test macos platform

**Comment by asl** [comment]
@swift-ci please test macos platform

**Review by kovdan01 — APPROVED** [review]

**Comment by asl** [comment]
@swift-ci smoke check

**Comment by asl** [comment]
@swift-ci smoke test

**Comment by hnrklssn** [comment]
https://github.com/swiftlang/swift-llbuild/pull/1023
please smoke test linux

**Comment by asl** [comment]
@swift-ci please smoke test linux
