### PR TITLE
[Profiler] Improve if statement coverage

### LINKED ISSUE #62943: Incorrect else if condition coverage
For e.g:

```swift
func foo() {
  if .random() {
    ()
  } else if .random() {
    ()
  } else {
    ()
  }
}
```

the condition `else if .random()` is given the region 0, which is incorrect, it should be (0 - 1), i.e it's hit anytime the first if condition isn't true.

rdar://104078910

### LINKED ISSUE #62944: Incorrect coverage for blocks following else ifs
For e.g:

```swift
func foo() {
  if .random() {
    ()
  } else if .random() {
    ()
  } else {
    ()
  }
}
```

The `else` block is given the counter `(0 - 2)`, but it should be `((0 - 1) - 2)`, to take account of the else if block.

rdar://104079242

### PR DESCRIPTION
**Pull request by hamishknight**
Fix counters for regions following `else if`s, fix the counters for `else if` conditions, and fix handling of `break` statements. Also while here, clean up the handling of branch exit regions such that we don't generate multiple overlapping regions for each branch, but a single region at the end of the entire `if` statement that accounts for all exiting control flow.

rdar://104078910
rdar://104079242
Resolves #62943
Resolves #62944

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
@swift-ci please test

File: test/Profiler/coverage_optimized_report.swift [hunk 1]
```diff
@@ -14,7 +14,7 @@
 // REQUIRES: executable_test
 // REQUIRES: OS=macosx
 
-// CHECK: "lines":{"count":9,"covered":6{{.*}}"functions":{"count":5,"covered":3
+// CHECK: "lines":{"count":9,"covered":5{{.*}}"functions":{"count":5,"covered":3
```
Comment (bnbarham) [inline test/Profiler/coverage_optimized_report.swift:17]: What line isn't covered now?

**Review by bnbarham — APPROVED** [review]

File: test/Profiler/coverage_optimized_report.swift (hunk 1 above)
Comment (hamishknight) [reply test/Profiler/coverage_optimized_report.swift:17]: It's the closing `}` of `if bar()`, previously we emitted a region for after the `if`, but we no longer do so if the counter hasn't changed from the parent. That means in this case that we'll no longer consider that line to be covered since it will now use the counter for the body of the `if`, but I think that's reasonable enough.
