### PR TITLE
[SILOptimizer] Fix wrong Integer overflow diagnostic type

### LINKED ISSUE #83877: Builtin.Int leaking in diagnostics when matching UInt with negative integer literal
### Description

The diagnostic is confusing when matching UInt with negative integer literal

### Reproduction

```swift
func test(val: UInt) {
  switch val { // error: integer literal '-24' overflows when stored into unsigned 'Builtin.Int64'
  case 12: break
  case -24: break
  default: break
  }
}
```

### Expected behavior

Message should be at least `integer literal '-24' overflows when stored into unsigned 'UInt'`, but preferably more like `Integer literal '-24' is invalid for unsigned type 'UInt'`.
The diagnostic location is also off, it should be on the `-24` literal.

### Environment

6.2

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by AbdAlRahmanGad**
When an integer literal overflows its target type, the diagnostic could incorrectly display a Builtin type (e.g. 'Builtin.Int64') instead of the user-facing type (e.g. 'UInt').

Resolves https://github.com/swiftlang/swift/issues/83877

### CODE REVIEW

**Comment by AbdAlRahmanGad** [comment]
Hi @rintaro, Could you please review this change?

File: lib/SILOptimizer/Utils/ConstantFolding.cpp [hunk 1]
```diff
@@ -864,6 +864,8 @@ constantFoldAndCheckIntegerConversions(BuiltinInst *BI,
       }
     } else if (auto *ILE = Loc.getAsASTNode<IntegerLiteralExpr>()) {
       UserDstTy = ILE->getType();
+    } else if (auto *E = Loc.getAsASTNode<Expr>()) {
+      UserDstTy = E->getType();
```
Comment (rintaro) [inline lib/SILOptimizer/Utils/ConstantFolding.cpp]: `IntegerLiteralExpr` is also a `Expr` so if `Expr` here is fine, you can remove `IntegerLiteralExpr` branch.
But I'm not really a person to review this area, so I'm not certain we can use arbitrary `Expr` here. So I'll defer to @eeckstein for the review.

**Review by rintaro — COMMENTED** [review]
Please add test cases 🙏

**Comment by finagolfin** [comment]
See [the test cases that were added for the previous `IntegerLiteralExpr` check](https://github.com/swiftlang/swift/commit/b12fcb50db554f10524976fb3ffd6d80d84377c1#diff-5ff12d80d1dc4a5465f9f3b17a816e457f8b4700709d528c0ea86eef09324800), I think you'll want to add something like that.

File: lib/SILOptimizer/Utils/ConstantFolding.cpp (hunk 1 above)
Comment (AbdAlRahmanGad) [reply lib/SILOptimizer/Utils/ConstantFolding.cpp]: Thanks for the review!
Done (added a unit test also)

**Comment by finagolfin** [comment]
Were you able to run these changes through the compiler validation suite locally, to make sure nothing broke? You can [follow these instructions](https://github.com/swiftlang/swift/blob/main/docs/HowToGuides/GettingStarted.md#the-actual-build) and add the `-T` flag to `build-script` to run all the compiler tests.

**Comment by AbdAlRahmanGad** [comment]
> Were you able to run these changes through the compiler validation suite locally, to make sure nothing broke? You can [follow these instructions](https://github.com/swiftlang/swift/blob/main/docs/HowToGuides/GettingStarted.md#the-actual-build) and add the `-T` flag to `build-script` to run all the compiler tests.

Yes, I built the compiler, ran the new build on the reproduction file, and ran the tests with `--filter="SILOptimizer*"` successfully!

Additionally I ran the full test suite and there a few unrelated failing tests that are already failing when I am in the main branch (without any new changes), so I think it's fine?

Here is the output if it's going to be helpful:

```
********************
********************
Failed Tests (10):
  Swift(linux-x86_64) :: CAS/dependency_file.swift
  Swift(linux-x86_64) :: CAS/path_remap.swift
  Swift(linux-x86_64) :: CAS/swift-scan-diagnostics-batch.swift
  Swift(linux-x86_64) :: CAS/swift-scan-diagnostics.swift
  Swift(linux-x86_64) :: CAS/swift-scan-response-file.swift
  Swift(linux-x86_64) :: CAS/swift-scan-test-llvm-args.swift
  Swift(linux-x86_64) :: CAS/swift-scan-test.swift
  Swift(linux-x86_64) :: CAS/symbol-graph.swift
  Swift(linux-x86_64) :: Interop/Cxx/stdlib/use-std-set.swift
  Swift(linux-x86_64) :: SourceKit/Misc/match-module-cache-with-compiler.swift

********************
Flaky Tests (1):
  Swift(linux-x86_64) :: SourceKit/Misc/no-change-working-dir.swift


Testing Time: 702.99s

Total Discovered Tests: 12453
  Unsupported      : 2550 (20.48%)
  Passed           : 9859 (79.17%)
  Expectedly Failed:   33 (0.26%)
  Failed           :   10 (0.08%)
  Flaky            :    1 (0.01%)
```

**Comment by finagolfin** [comment]
Great, let's let Erik review your small pull, maybe sometime this week, then he will run it through the full CI if he's okay with it. 👍

**Review by eeckstein — APPROVED** [review]
lgtm

**Comment by AbdAlRahmanGad** [comment]
Thanks! Could you please run the CI?

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by AbdAlRahmanGad** [comment]
Is the failing test related to the change? Is it a problem in the CI?
It doesn't fail locally

Could you please have a look when you have time?
```
13:20:30  Failed Tests (1):
13:20:30    Swift(macosx-x86_64) :: IRGen/async_frame_entry_return_metadata.swift
```

**Comment by finagolfin** [comment]
[Single IRGen/async_frame_entry_return_metadata test failure on macOS](https://ci.swift.org/job/swift-PR-macos-smoke-test/26465/console) is completely unrelated

@swift-ci smoke test macOS

**Comment by AbdAlRahmanGad** [comment]
Could you please merge this?

**Comment by finagolfin** [comment]
Thanks for the diagnostic fix, @AbdAlRahmanGad. 😺
