### PR TITLE
[SourceKit] Don’t provide incorrect semantic highlighting of `nil` in case statements as enum decl element

### LINKED ISSUE #599: nil should still be highlighted as a keyword in a case pattern
`nil` is highlighted as a keyword everywhere except when it is being pattern-matched in a case pattern (`switch`, `if case`, etc.)

Screenshot from 2022-07-29 14-08-01

this is *technically* correct, but makes for some strange highlighting in a text editor. it would be better if `nil` was the same color everywhere.

### PR DESCRIPTION
**Pull request by ahoppen**
If a 'nil' literal occurs in a swift-case statement, it gets replaced by a reference to 'Optional.none' in the AST. We want to continue highlighting 'nil' as a keyword and not as an enum element. Detect this case if 'none' was spelled with 3 characters, which indicates that it was rewritten from 'nil'.

Resolves apple/sourcekit-lsp#599
rdar://97961865

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

File: tools/SourceKit/lib/SwiftLang/SwiftEditor.cpp [hunk 1]
```diff
@@ -982,6 +982,14 @@ class SemanticAnnotator : public SourceEntityWalker {
 
     unsigned ByteOffset = SM.getLocOffsetInBuffer(Range.getStart(), BufferID);
     unsigned Length = Range.getByteLength();
+    if (D == D->getASTContext().getOptionalNoneDecl() && Length == 3) {
+      // If a 'nil' literal occurs in a swift-case statement, it gets replaced
+      // by a reference to 'Optional.none' in the AST. We want to continue
+      // highlighting 'nil' as a keyword and not as an enum element.
+      // Detect this case if 'none' was spelled with 3 characters, which
+      // indicates that it was rewritten from 'nil'.
```
Comment (rintaro) [inline tools/SourceKit/lib/SwiftLang/SwiftEditor.cpp:990]: `Length == 3` might be enough in real world, but `SM.extractText(Range) == "nil"` is more explicit, safe, and not so heavy. If we don't have strong reason not to, could you check the actual spelling?

Comment (rintaro) [reply tools/SourceKit/lib/SwiftLang/SwiftEditor.cpp:990]: Also, other "deciding annotate or not" checks are in `visitDeclReference()` instead of `annote()`. Could you move this logic to it?

Comment (ahoppen) [reply tools/SourceKit/lib/SwiftLang/SwiftEditor.cpp:990]: Good suggestions, thanks. I though I would have needed to go to the lexer to get the original source text but of course I don’t.

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

File: tools/SourceKit/lib/SwiftLang/SwiftEditor.cpp [hunk 2]
```diff
@@ -963,6 +963,17 @@ class SemanticAnnotator : public SourceEntityWalker {
...
       return true;
 
+    auto &SM = D->getASTContext().SourceMgr;
+    if (D == D->getASTContext().getOptionalNoneDecl() &&
+        SM.extractText(Range) == "nil") {
+      // If a 'nil' literal occurs in a swift-case statement, it gets replaced
+      // by a reference to 'Optional.none' in the AST. We want to continue
+      // highlighting 'nil' as a keyword and not as an enum element.
+      // Detect this case if 'none' was spelled with 3 characters, which
+      // indicates that it was rewritten from 'nil'.
```
Comment (rintaro) [inline tools/SourceKit/lib/SwiftLang/SwiftEditor.cpp:973]: This description is not correct anymore :)

File: tools/SourceKit/lib/SwiftLang/SwiftEditor.cpp [hunk 3]
```diff
@@ -963,6 +963,17 @@ class SemanticAnnotator : public SourceEntityWalker {
     if (AvailableAttr::isUnavailable(D))
       return true;
 
+    auto &SM = D->getASTContext().SourceMgr;
+    if (D == D->getASTContext().getOptionalNoneDecl() &&
+        SM.extractText(Range) == "nil") {
```
Comment (rintaro) [inline tools/SourceKit/lib/SwiftLang/SwiftEditor.cpp:968]:
```suggestion
        SM.extractText(Range, BufferID) == "nil") {
```
So it skips `findBufferContainingLoc()` operation

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

File: tools/SourceKit/lib/SwiftLang/SwiftEditor.cpp (hunk 2 above)
Comment (ahoppen) [reply tools/SourceKit/lib/SwiftLang/SwiftEditor.cpp]: Thanks for catching it. I removed the last sentence.

File: tools/SourceKit/lib/SwiftLang/SwiftEditor.cpp (hunk 3 above)
Comment (ahoppen) [reply tools/SourceKit/lib/SwiftLang/SwiftEditor.cpp]: Good catch. Thanks 👍

**Review by rintaro — APPROVED** [review]
