### PR TITLE
[Sema] Diagnose function coercion ambiguity 

### LINKED ISSUE #63834: Disambiguation of function ref using coercion to non-matching type produces unhelpful error
```swift
func foo(int: Int, string: String) {}
func foo(int: Int, string: Bool) {}

let a = foo(int:string:) as (Int, Int) -> Void // error: type of expression is ambiguous without more context
```

We ought to point out the mismatch and show the candidates, similar to how the ambiguity is handled in the absence of a coercion.

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
In previous PR was handling only failures located in argument mismatch, but ambiguity of overload in coerce subexpr can come from other fixes as well e.g. contextual mismatch, not only located in `FunctionArgument`. So is a more general approach look for the overload subexpr. 

Resolves https://github.com/apple/swift/issues/63834

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

File: test/Constraints/overload.swift [hunk 1]
```diff
@@ -287,7 +287,15 @@ func rdar97396399() {
...
+// expected-note@-2{{found this candidate}}
+func f63834(int: Int, string: Bool) {} // expected-note 3{{found candidate with type '(Int, Bool) -> ()'}}
+// expected-note@-1{{candidate '(Int) -> Void' requires 1 argument, but 2 were provided}}
+// expected-note@-2{{found this candidate}}
+
+let _ = f63834(int:string:) as (Int, Int) -> Void // expected-error{{no exact matches in reference to global function 'f63834'}}
+let _ = f63834(int:string:) as (Int) -> Void // expected-error{{no exact matches in reference to global function 'f63834'}}
+let _ = f63834(int:string:) as Int // expected-error{{no exact matches in reference to global function 'f63834'}}
+let _ = (f63834(int:string:)) as Int // expected-error{{no exact matches in reference to global function 'f63834'}}
+let _ = f63834(int:string:) as (Double, Double) -> Void // expected-error{{no exact matches in reference to global function 'f63834'}}
```
Comment (AnthonyLatsis) [inline test/Constraints/overload.swift:301]: Could you decouple these test cases by the kind of note they produce to make them more robust and clarify which ones produce which notes?

**Review by AnthonyLatsis — COMMENTED** [review]
Thank you!

File: test/Constraints/overload.swift (hunk 1 above)
Comment (LucianoPAlmeida) [reply test/Constraints/overload.swift]: Done :)

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

File: test/Constraints/overload.swift [hunk 2]
```diff
@@ -287,7 +287,22 @@ func rdar97396399() {
 }
 
 // https://github.com/apple/swift/issues/63834
-func f63834(int: Int, string: String) {} // expected-note{{found candidate with type '(Int, String) -> ()'}}
-func f63834(int: Int, string: Bool) {} // expected-note{{found candidate with type '(Int, Bool) -> ()'}}
+func f63834(int: Int, string: String) {} // expected-note 3{{found candidate with type '(Int, String) -> ()'}}
+func f63834(int: Int, string: Bool) {} // expected-note 3{{found candidate with type '(Int, Bool) -> ()'}}
 
-let a = f63834(int:string:) as (Int, Int) -> Void // expected-error{{no exact matches in reference to global function 'f63834'}}
+func f63834_1(int: Int, string: Bool) {} // expected-note{{candidate '(Int) -> Void' requires 1 argument, but 2 were provided}}
```
Comment (AnthonyLatsis) [inline test/Constraints/overload.swift:293]: Sorry to only notice this now when you pushed and re-triggered the tests. I think this warrants a FIXME. This is better than a generic error, but the message is still far from optimal. We are diagnosing the function reference instead of the coercion type. It ought to be the other way around, e.g. `coercion type '(Int) -> Void' requires 1 argument, but candidate requires 2`.

File: test/Constraints/overload.swift [hunk 3]
```diff
@@ -287,7 +287,22 @@ func rdar97396399() {
...
+func f63834_1(int: Int, string: String) {} // expected-note{{candidate '(Int) -> Void' requires 1 argument, but 2 were provided}}
+
+func f63834_2(int: Int, string: Bool) {} // expected-note {{found this candidate}}
+func f63834_2(int: Int, string: String) {} // expected-note {{found this candidate}}
```
Comment (AnthonyLatsis) [inline test/Constraints/overload.swift:297]: This too. I think we should mention the type of the candidate in the note, as in the first case.

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

File: include/swift/AST/DiagnosticsSema.def [hunk 4]
```diff
@@ -1404,9 +1404,9 @@ NOTE(decl_multiple_defaulted_closure_parameters,none,
      "%0 contains defaulted closure parameters %1 and %2",
      (DeclName, Identifier, Identifier))
 NOTE(candidate_with_extraneous_args,none,
-      "candidate %0 requires %1 argument%s1, "
-      "but %2 %select{were|was}3 %select{provided|used in closure body}4",
-      (Type, unsigned, unsigned, bool, bool))
+      "contextual type %0 requires %1 argument%s1, "
+      "but %2 %select{were|was}3 %select{provided by candidate of type %5|used in closure body}4",
+      (Type, unsigned, unsigned, bool, bool, Type))
```
Comment (AnthonyLatsis) [inline include/swift/AST/DiagnosticsSema.def:1409]: Huh, apparently this diagnostic isn’t even tested anywhere.

File: test/Constraints/overload.swift [hunk 5]
```diff
@@ -290,9 +290,8 @@ func rdar97396399() {
 func f63834(int: Int, string: String) {} // expected-note 3{{found candidate with type '(Int, String) -> ()'}}
 func f63834(int: Int, string: Bool) {} // expected-note 3{{found candidate with type '(Int, Bool) -> ()'}}
 
-// FIXME: Note should state that candidate has 2 arguments but 1 is expected.
-func f63834_1(int: Int, string: Bool) {} // expected-note{{candidate '(Int) -> Void' requires 1 argument, but 2 were provided}}
-func f63834_1(int: Int, string: String) {} // expected-note{{candidate '(Int) -> Void' requires 1 argument, but 2 were provided}}
+func f63834_1(int: Int, string: Bool) {} // expected-note{{contextual type '(Int) -> Void' requires 1 argument, but 2 were provided by candidate of type '(Int, Bool) -> ()'}}
+func f63834_1(int: Int, string: String) {} // expected-note{{contextual type '(Int) -> Void' requires 1 argument, but 2 were provided by candidate of type '(Int, String) -> ()'}}
```
Comment (AnthonyLatsis) [inline test/Constraints/overload.swift:294]: * IMO the note should start with a description of the candidate, because that is what it point to.
* The candidate "requires" rather than "provides".

But I’m not sure if it’s safe to modify this diagnostic any further without the test coverage.

File: include/swift/AST/DiagnosticsSema.def (hunk 4 above)
Comment (LucianoPAlmeida) [reply include/swift/AST/DiagnosticsSema.def:1409]: Yes, that was why it may had be overlooked. But we are adding at least on case now. Still couldn't figure out a closure repro tho.

File: test/Constraints/overload.swift (hunk 5 above)
Comment (LucianoPAlmeida) [reply test/Constraints/overload.swift:294]: > * The candidate "requires" rather than "provides".

My understanding is that since there is a candidate is trying to match a contextual type, I read as `context requires one thing but candidate provides another`. I think candidate "requires" makes sense in a call situation.

> But I’m not sure if it’s safe to modify this diagnostic any further without the test coverage.

I think is fine to change at some extent since we are adding a test case. Although I wouldn't like to touch closure one given I still have no idea on how to repro this note with this scenario.

Comment (LucianoPAlmeida) [reply test/Constraints/overload.swift:294]: > * IMO the note should start with a description of the candidate, because that is what it point to.

What about `candidate '(Int, String) -> ()' has 2 arguments but context '(Int) -> Void' requires 1`

Comment (LucianoPAlmeida) [reply test/Constraints/overload.swift]: > But I’m not sure if it’s safe to modify this diagnostic any further without the test coverage.

Separated the closure one to leave it untouched for now.

File: lib/Sema/ConstraintSystem.cpp [hunk 6]
```diff
@@ -622,9 +622,10 @@ ConstraintLocator *ConstraintSystem::getCalleeLocator(
   if (isExpr<ObjectLiteralExpr>(anchor))
     return getConstraintLocator(anchor, ConstraintLocator::ConstructorMember);
 
-  if (locator->isLastElement<LocatorPathElt::FunctionArgument>()) {
-    if (auto *CE = getAsExpr<CoerceExpr>(anchor)) {
-      return getConstraintLocator(CE->getSubExpr());
+  if (auto *CE = getAsExpr<CoerceExpr>(anchor)) {
+    if (auto *ODRE = getAsExpr<OverloadedDeclRefExpr>(
+            CE->getSubExpr()->getValueProvidingExpr())) {
+      return getConstraintLocator(ODRE);
```
[the remark this answers is not in the document]
Comment (hamishknight) [reply lib/Sema/ConstraintSystem.cpp:628]: For example, here's some code that shouldn't compile, but I believe will compile with this change:

```swift
typealias Magic<T> = T

func foo(_ x: Int = 0) {}
func foo(_ x: String) {}

(foo as Magic)()
```

Would you mind adding this as a test case to make sure we don't accept it?

[the remark this answers is not in the document]
Comment (LucianoPAlmeida) [reply lib/Sema/ConstraintSystem.cpp:628]: Yes, sure it makes sense to move this logic to diagnoseAmbiguityWithFixes. I'll fix it today after work :)

[the remark this answers is not in the document]
Comment (LucianoPAlmeida) [reply lib/Sema/ConstraintSystem.cpp]: Fixed and test added!

File: test/Constraints/overload.swift (hunk 5 above)
Comment (hamishknight) [reply test/Constraints/overload.swift]: > What about `candidate '(Int, String) -> ()' has 2 arguments, but context '(Int) -> Void' requires 1`?

To be nitpicky, candidates don't have arguments, they have parameters. Maybe it would be better worded as something like `candidate '(Int, String) -> ()' has 2 parameters, but context '(Int) -> Void' has 1`?

File: lib/Sema/CSDiagnostics.cpp [hunk 7]
```diff
@@ -5573,6 +5573,15 @@ SourceLoc ExtraneousArgumentsFailure::getLoc() const {
   return FailureDiagnostic::getLoc();
 }
 
+ASTNode ExtraneousArgumentsFailure::getAnchor() const {
+  auto anchor = FailureDiagnostic::getAnchor();
+
+  if (auto *CE = getAsExpr<CoerceExpr>(anchor))
+    return CE->getSubExpr();
```
Comment (hamishknight) [inline lib/Sema/CSDiagnostics.cpp:5580]: I kind of wonder whether `CoerceExpr` should generate its conversion constraint with a locator element that points into the sub-expression, that way `simplifyLocator` would automatically handle this. That being said, I'm not sure what other impact that might have, so I'm happy to leave that for future work.

**Review by hamishknight — COMMENTED** [review]
Looking good! Just one more comment, and a suggestion for potential future work that could be done here

File: lib/Sema/ConstraintSystem.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (hamishknight) [reply lib/Sema/ConstraintSystem.cpp]: Thanks!

File: include/swift/Sema/ConstraintSystem.h [hunk 8]
```diff
@@ -1653,6 +1653,9 @@ class Solution {
     return None;
   }
 
+  ConstraintLocator *getLocatorForAmbiguity(ConstraintLocator *locator,
+                                            bool lookThroughApply = true) const;
+
```
[the remark this answers is not in the document]
Comment (LucianoPAlmeida) [reply include/swift/Sema/ConstraintSystem.h:1662]: Added!

**Review by hamishknight — APPROVED** [review]
LGTM! I'll let @xedin have the final say though

**Review by xedin — COMMENTED** [review]
This feels like a workaround for the fact that fixes don't have correct locators for some specific situations where the problem is with structure of the types being coerced, should be adjust locator at the point of fix instead?

**Comment by LucianoPAlmeida** [comment]
You mean record the fix anchored on the coerce subexpr in those cases?
Or maybe still record fix on the coerce expr but with additional path elt that we can use to simplify down to the subexpr?

**Comment by xedin** [comment]
It seems like in these cases coercion expression itself plays no role because the issue is with the type structure of the coerced expression, locator should probably be simplified down to sub-expression + path for the fix.

**Comment by LucianoPAlmeida** [comment]
Sounds good, thank you! I'll try update later today :)

**Comment by xedin** [comment]
Sounds good, thank you!

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test MacOS platform

**Comment by LucianoPAlmeida** [comment]
> It seems like in these cases coercion expression itself plays no role because the issue is with the type structure of the coerced expression, locator should probably be simplified down to sub-expression + path for the fix.

@xedin, Let me know whether this aligns with what you have in mind. It is likely I have miss something either on approach or implementation detail.

File: lib/Sema/CSSimplify.cpp [hunk 9]
```diff
@@ -3408,6 +3435,8 @@ ConstraintSystem::matchFunctionTypes(FunctionType *func1, FunctionType *func2,
       if (!anchor)
         return getTypeMatchFailure(argumentLocator);
 
+      loc = adjustFunctionCoercionFixLocator(*this, loc, loc->getPath());
```
Comment (xedin) [inline lib/Sema/CSSimplify.cpp:3438]: I'm afraid that we'd end up with this adjustment all over the place. Have you tried a slightly different approach where `CoerceExpr` stays as an anchor but instead of `FunctionCoercion` we add a `CoercionOperand` element and that forces `simplifyLocator` to always produce underlying expression? This way it should be possible to add that element to conversion locator during CSGen and that would do the trick since ambiguity and other diagnostics try to simply?

Comment (LucianoPAlmeida) [reply lib/Sema/CSSimplify.cpp:3438]: Yeah, that is kind of what I had in mind initially but haven't tried because somehow interpreted from the last comment we want to adjust only before recording the fix, but let me give this a try. And sorry for all the back and forth

Comment (xedin) [reply lib/Sema/CSSimplify.cpp:3438]: No need to apologize! I though that we could do the switch to the underlying element in one place i.e. in matchTypes somewhere but having looked at your changes it seems like it might be easier to just do it during constraint generation...

Comment (LucianoPAlmeida) [reply lib/Sema/CSSimplify.cpp:3438]: Just an update, working on this is just slowly... a bit swamped with work stuff this past/next few weeks. Hopefully will make some progress soon :)

Comment (xedin) [reply lib/Sema/CSSimplify.cpp:3438]: Sounds great, thank you!

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test MacOS

File: lib/Sema/CSSimplify.cpp (hunk 9 above)
Comment (LucianoPAlmeida) [reply lib/Sema/CSSimplify.cpp]: Just updated, let me know what you think and if I missed something along the way. This didn't make things as simple as I imagined it would be, but felt a little bit better than previous "fix adjustment approach".

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test MacOS Platform

File: include/swift/Sema/ConstraintSystem.h [hunk 10]
```diff
@@ -3249,6 +3249,12 @@ class ConstraintSystem {
   ConstraintLocator *
   getConstraintLocator(const ConstraintLocatorBuilder &builder);
 
+  /// Retrieves a locator that identifies where an overload ambiguity may be
+  /// present. In most cases this is a no-op, but may simplify locator e.g
+  /// coercions for ambiguities in the expression operand.
+  ConstraintLocator *
+  getConstraintLocatorForAmbiguity(ConstraintLocator *locator);
```
Comment (xedin) [inline include/swift/Sema/ConstraintSystem.h:3256]: Have you tried adjusting `getCalleeLocator` to detect presence of `CoercionOperand` and produce a version that is anchored on the operand?

Comment (hamishknight) [reply include/swift/Sema/ConstraintSystem.h:3256]: @xedin Most clients of `getCalleeLocator` don't want it to look through coercions, e.g for things like handling IUOs, default arguments, argument labels. We could add another `bool` parameter to handle that, but IMO it's clearer as a separate function.

Comment (xedin) [reply include/swift/Sema/ConstraintSystem.h:3256]: @hamishknight We added that element to indicate that the locator points to the coerced expression.

Comment (hamishknight) [reply include/swift/Sema/ConstraintSystem.h:3256]: @xedin Ah right I see, feels a little odd to call it a callee, but I guess that's fine to simplify things :)

Comment (LucianoPAlmeida) [reply include/swift/Sema/ConstraintSystem.h]: Just adjusted!
I was worried about this case: 
```
func fn63834_3() -> String {} // expected-note {{found candidate with type 'String'}}
func fn63834_3() -> Double {} // expected-note {{found candidate with type 'Double'}}

fn63834_3() as Int // expected-error {{no exact matches in call to global function 'fn63834_3'}}
```
I thought we had to consider adjusting the locator before `Solution::getCalleeLocator`. But we can just look recursively in that.

File: lib/Sema/CSApply.cpp [hunk 11]
```diff
@@ -4275,8 +4275,15 @@ namespace {
     bool hasForcedOptionalResult(ExplicitCastExpr *expr) {
       const auto *const TR = expr->getCastTypeRepr();
       if (TR && TR->getKind() == TypeReprKind::ImplicitlyUnwrappedOptional) {
-        auto *locator = cs.getConstraintLocator(
-            expr, ConstraintLocator::ImplicitlyUnwrappedDisjunctionChoice);
+        ConstraintLocator *locator;
+        if (isExpr<CoerceExpr>(expr)) {
+          locator = cs.getConstraintLocator(
+              expr, {LocatorPathElt::CoercionOperand(),
```
Comment (xedin) [inline lib/Sema/CSApply.cpp:4281]: Do we actually need `CoercionOperand` here? Isn't the result of coercion being considered here instead?

File: lib/Sema/CSApply.cpp [hunk 12]
```diff
@@ -4349,7 +4356,8 @@ namespace {
       // If we weren't explicitly told by the caller which disjunction choice,
       // get it from the solution to determine whether we've picked a coercion
       // or a bridging conversion.
-      auto *locator = cs.getConstraintLocator(expr);
+      auto *locator =
+          cs.getConstraintLocator(expr, LocatorPathElt::CoercionOperand());
```
Comment (xedin) [inline lib/Sema/CSApply.cpp:4360]: Nit: you can use `ConstraintLocator::CoercionOperand` if path element doesn't have any parameters.

File: lib/Sema/ConstraintSystem.cpp [hunk 13]
```diff
@@ -622,10 +622,10 @@ ConstraintLocator *ConstraintSystem::getCalleeLocator(
   if (isExpr<ObjectLiteralExpr>(anchor))
     return getConstraintLocator(anchor, ConstraintLocator::ConstructorMember);
 
-  if (locator->isLastElement<LocatorPathElt::FunctionArgument>()) {
-    if (auto *CE = getAsExpr<CoerceExpr>(anchor)) {
-      return getConstraintLocator(CE->getSubExpr());
-    }
+  if (locator->findFirst<LocatorPathElt::CoercionOperand>()) {
+    locator = getConstraintLocator(simplifyLocatorToAnchor(locator));
```
Comment (xedin) [inline lib/Sema/ConstraintSystem.cpp:626]: This doesn't seem correct... I think should simplify only anchor + CoercionOperand into the underlying operand expression and let the recursive call to `getCalleeLocator` handle the rest of the chain (if there is anything).

Comment (LucianoPAlmeida) [reply lib/Sema/ConstraintSystem.cpp]: Fixed =]

File: lib/Sema/CSApply.cpp (hunk 11 above)
Comment (LucianoPAlmeida) [reply lib/Sema/CSApply.cpp:4281]: Yeah, otherwise it asserts because in `getDisjunctionChoice` for because that is the locator path expected for the disjunction. I thought it was expected since we  both call `addDisjunctionConstraint` and `createTypeVariableAndDisjunctionForIUOCoercion` at that locator in `CSGen`.

Comment (xedin) [reply lib/Sema/CSApply.cpp:4281]: So maybe we should just use `CoerceExpr` directly for call to `createTypeVariableAndDisjunctionForIUOCoercion`? It seems more reasonable considering that we are unwrapping the cast type.

File: lib/Sema/CSDiagnostics.cpp [hunk 14]
```diff
@@ -1222,17 +1228,18 @@ ASTNode InvalidCoercionFailure::getAnchor() const {
...
   auto fromType = getFromType();
   auto toType = getToType();
+  auto *CE = getAsExpr<CoerceExpr>(getRawAnchor());
 
   emitDiagnostic(diag::cannot_coerce_to_type, fromType, toType);
 
   if (UseConditionalCast) {
     emitDiagnostic(diag::missing_optional_downcast)
-        .highlight(getSourceRange())
-        .fixItReplace(getLoc(), "as?");
```
Comment (xedin) [inline lib/Sema/CSDiagnostics.cpp:1231]: Sorry, didn't notice this initially... Should `getLoc()` of `InvalidCoercionFailure` be re-defined instead?

File: lib/Sema/CSApply.cpp (hunk 11 above)
Comment (LucianoPAlmeida) [reply lib/Sema/CSApply.cpp:4281]: Wouldn't that require to have handle both(CoercionOperand and directlyAt<CoerceExpr>) on diagnostics? Let me try that and see

File: lib/Sema/CSDiagnostics.cpp (hunk 14 above)
Comment (LucianoPAlmeida) [reply lib/Sema/CSDiagnostics.cpp]: Fixed!

File: lib/Sema/CSApply.cpp (hunk 11 above)
Comment (LucianoPAlmeida) [reply lib/Sema/CSApply.cpp:4281]: It seems that there was no problem, but I'm relying on that to be covered by the tests. If that is ok, I can commit the changes =]

Comment (xedin) [reply lib/Sema/CSApply.cpp:4281]: We can always fix it if some cases come up in the future :)

File: lib/Sema/ConstraintSystem.cpp (hunk 13 above)
Comment (LucianoPAlmeida) [reply lib/Sema/ConstraintSystem.cpp]: This seems to cause regressions in two cases, it seems like not all subexpr should be returned as calleeLocator.

File: lib/Sema/CSApply.cpp (hunk 11 above)
Comment (LucianoPAlmeida) [reply lib/Sema/CSApply.cpp]: Fixed!

File: lib/Sema/ConstraintSystem.cpp (hunk 13 above)
Comment (xedin) [reply lib/Sema/ConstraintSystem.cpp]: I think it be simplified to the argument expression only if there are more elements after CoercionOperand?…

Comment (LucianoPAlmeida) [reply lib/Sema/ConstraintSystem.cpp]: The regression was in a very specific case where a requirement failure specific logic relies on callee locator to get information about context. Fixed in the last commit

**Review by xedin — APPROVED** [review]
Looks great, thank you!

File: lib/Sema/CSGen.cpp [hunk 15]
```diff
@@ -3326,8 +3327,12 @@ namespace {
 
       // If the result type was declared IUO, add a disjunction for
       // bindings for the result of the coercion.
-      if (repr && repr->getKind() == TypeReprKind::ImplicitlyUnwrappedOptional)
-        return createTypeVariableAndDisjunctionForIUOCoercion(toType, locator);
+      if (repr &&
+          repr->getKind() == TypeReprKind::ImplicitlyUnwrappedOptional) {
+        auto *locatorIUO = CS.getConstraintLocator(expr);
```
Comment (xedin) [inline lib/Sema/CSGen.cpp:3332]: Nit: let's just inline this locator into the `createTypeVariableAndDisjunctionForIUOCoercion` call.

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test MacOS Platform
