### PR TITLE
Fixed issue #72085 where BinaryExpr fix-it suggested missing operator.

### LINKED ISSUE #72085: Non-sensical fix-it (and weird error message) when trying to multiply a Duration by an integer
### Description

_No response_

### Reproduction

```swift
let origin = SuspendingClock.now
let duration = Duration.seconds(1)

let overallOffset = .now - origin
let loopIndex = overallOffset / duration
let durationOfCompletedLoops = loopIndex * duration // 🤨 Operator argument #2 must precede operator argument #1
                                                    // ❌ Replace 'loopIndex * duration' with 'durationloopIndex'
```

### Expected behavior

1. It shouldn't care what order the operands are for the multiplication, it's a commutative operation.
2. The fix-it is just bizarre.  It makes no sense; it synthesises a non-existent variable reference out of basically nothing.

### Environment

swift-driver version: 1.90.10.1 Apple Swift version 5.10 (swiftlang-5.10.0.12.7 clang-1500.3.9.3)
Target: x86_64-apple-macosx14.0

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by CrazyFanFan**
Add missing  operator to BinaryExpr fix-it suggestions.

Resolves #72085.

### CODE REVIEW

File: lib/Sema/CSDiagnostics.cpp [hunk 1]
```diff
@@ -5862,12 +5862,18 @@ bool OutOfOrderArgumentFailure::diagnoseAsError() {
...
-        !isExpr<BinaryExpr>(anchor) && PrevArgIdx != args->size() - 1;
+    auto sign = "";
+    if (isExpr<BinaryExpr>(anchor)) {
+      auto BinExpr = castToExpr<BinaryExpr>(anchor);
+      auto Func = BinExpr->getFn();
+      auto operatorName = std::string(*getOperatorName(Func));
+      sign = (" " + operatorName + " ").c_str();
+    } else if (PrevArgIdx != args->size() - 1) {
+      sign = ", ";
+    }
```
Comment (LucianoPAlmeida) [inline lib/Sema/CSDiagnostics.cpp:5873]: Nit: A small simplification suggestion
```suggestion
    std::string sign;
    if (auto *BE = getAsExpr<BinaryExpr>(anchor)) {
      auto operatorName = std::string(*getOperatorName(BE->getFn()));
      sign = " " + operatorName + " ";
    } else if (PrevArgIdx != args->size() - 1) {
      sign = ", ";
    }
```

Comment (CrazyFanFan) [reply lib/Sema/CSDiagnostics.cpp]: Thanks for your code review and suggestions.  I've made the changes and unit tests have passed in my local.

**Review by LucianoPAlmeida — APPROVED** [review]

File: lib/Sema/CSDiagnostics.cpp [hunk 2]
```diff
@@ -5863,12 +5863,16 @@ bool OutOfOrderArgumentFailure::diagnoseAsError() {
 
     // Move requires postfix comma only if argument is moved in-between
     // other arguments.
-    bool requiresComma =
-        !isExpr<BinaryExpr>(anchor) && PrevArgIdx != args->size() - 1;
+    std::string sign;
```
Comment (ahoppen) [inline lib/Sema/CSDiagnostics.cpp:5866]: Nitpick: I would call this `argumentSeparator` or something. But otherwise LGTM.

Comment (CrazyFanFan) [reply lib/Sema/CSDiagnostics.cpp]: Sure, it's all set to `argumentSeparator`.  Thanks

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test
