### PR TITLE
[Sema] Improve diagnostics for duplicate global actor attributes

### LINKED ISSUE #82702: Missing note for duplicate global actor annotations
### Description

There should be a note indicating where the other annotations are in source.

### Reproduction

```swift
@MainActor // func uhoh-commented-out() {
//   print("oops")
// }
@MainActor func myFunction() {}
```

```shell
➜  Desktop (main 6/9/25) swiftc -c test.swift
test.swift:4:17: error: declaration can not have multiple global actor attributes ('MainActor' and 'MainActor')
2 | //   print("oops")
3 | // }
4 | @MainActor func myFunction() {}
  |                 `- error: declaration can not have multiple global actor attributes ('MainActor' and 'MainActor')
5 |
6 |
```

### Expected behavior

a note referring to source location 1:1.

### Environment

```shell
$ swiftc --version
Apple Swift version 6.2-dev (LLVM 3c4a54b02dd62b7, Swift a40a7be6945a895)
Target: arm64-apple-macosx16.0
Build config: +assertions
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by AbdAlRahmanGad**
Add a note diagnostic that points to the source location of each conflicting global actor attribute when a declaration has more than one.

Resolves https://github.com/swiftlang/swift/issues/82702.

### CODE REVIEW

File: lib/Sema/TypeCheckConcurrency.cpp [hunk 1]
```diff
@@ -340,6 +340,10 @@ swift::checkGlobalActorAttributes(SourceLoc loc, ArrayRef<CustomAttr *> attrs) {
       ctx.Diags.diagnose(
           loc, diag::multiple_global_actors, globalActorNominal->getName(),
           nominal->getName());
+
+      ctx.Diags.diagnose(attr->getLocation(), diag::multiple_global_actors_note,
+                         nominal->getName());
```
Comment (xedin) [inline lib/Sema/TypeCheckConcurrency.cpp]: A small suggestion - instead of `getName()` let's use `nominal` and use `%kindonly0` just like the diagnostic below the one you added does.

Comment (AbdAlRahmanGad) [reply lib/Sema/TypeCheckConcurrency.cpp]: Done

File: include/swift/AST/DiagnosticsSema.def [hunk 2]
```diff
@@ -6228,6 +6228,8 @@ ERROR(no_concurrency_module,none,
 ERROR(multiple_global_actors,none,
       "declaration can not have multiple global actor attributes (%0 and %1)",
       (Identifier, Identifier))
+NOTE(multiple_global_actors_note,none,
+      "%kindonly0 attribute previously declared here", (const Decl *))
```
Comment (xedin) [inline include/swift/AST/DiagnosticsSema.def]: Sorry I meant `%0` here, the "generic struct" doesn't really help us here, what we want is the name :)

Comment (AbdAlRahmanGad) [reply include/swift/AST/DiagnosticsSema.def]: No problem!
Done, let me know if there are any other changes.

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Comment by xedin** [comment]
@swift-ci please test Windows platform
