### PR TITLE
[cxx-interop] Import constexpr globals in a namespace

### LINKED ISSUE #81327: [cxx-interop] constexpr from within a namespace is not available in Swift
### Description

When a `constexpr` is declared inside a namespace, it won't be visible from Swift; but declaring it in the global namespace will make it visible in Swift.

### Reproduction

In a cpp target:

```cpp
namespace namespace_test{
constexpr int TEST1 = 44;
static constexpr char TEST2 = 't';
}
constexpr int TEST1 = 44;
static constexpr char TEST2= 't';

```

And then in swift

```swift
import cxx_target

let i = TEST1
let i2 - namespace_test.TEST1

let c = TEST2
let c2 = namespace_test.TEST2
```
which will result in "error: type 'namespace_test' has no member 'TEST1'" and "error: type 'namespace_test' has no member 'TEST2'"

### Expected behavior

The `constexpr`s are available in Swift.

### Environment

swift-driver version: 1.120.5 Apple Swift version 6.1 (swiftlang-6.1.0.110.21 clang-1700.0.13.3)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by egorzhdan**
rdar://150756970 / resolves https://github.com/swiftlang/swift/issues/81327

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please test

**Review by Xazax-hun — APPROVED** [review]

File: lib/ClangImporter/ImportDecl.cpp [hunk 1]
```diff
@@ -4599,7 +4599,7 @@ namespace {
         isStatic = true;
 
       // For now we don't import static constexpr. TODO: Lift this restriction.
```
Comment (j-hui) [inline lib/ClangImporter/ImportDecl.cpp:4601]: Out of curiosity: what's the reason behind this restriction?

**Review by j-hui — APPROVED** [review]
LGTM

File: lib/ClangImporter/ImportDecl.cpp (hunk 1 above)
Comment (egorzhdan) [reply lib/ClangImporter/ImportDecl.cpp:4601]: My understanding is that we need to synthesize thunks for `static constexpr` fields of C++ classes because those might be eliminated from the binary (6bc2696e243a916f4bec61fa1353ffe32cbb4d1d). That logic had issues so it was removed at some point (0f83b65f9b4f49a91ac66e7952cd56e3dac35782).
