### PR TITLE
[TypeChecker] Avoid checking lazy property accessors if they haven't …

### LINKED ISSUE #84041: Repeated SIGSEGV using VSCode with Swift PM project
### Swift version

Apple Swift version 6.2-dev (LLVM 84f765b899f6671, Swift 6713168abd85e22)

### Platform

macOS 26 25A5349a

### Editor

Visual Studio Code Version: 1.103.2 (Universal) with Swift extension v2.11.20250806, LLDB DAP 0.2.16

### Description

VSCode is in an endless SourceKit-LSP restart loop. Logs seem to show a segfault. 

### Steps to Reproduce

_No response_

### Logging

[sourcekit-lsp-diagnose-2025-08-29T11-52-25-07-00.zip](https://github.com/user-attachments/files/22051883/sourcekit-lsp-diagnose-2025-08-29T11-52-25-07-00.zip)

### PR DESCRIPTION
**Pull request by xedin**
…been synthesized yet

Ttheir availability is going to match the property itself. This is a workaround for lazy type-checking because synthesis of accessors for such properties requires a reference to `self` which won't be available because pattern binding for the variable was skipped.

Resolves: rdar://129359362
Resolves: rdar://159463230
Resolves: https://github.com/swiftlang/swift/issues/84041

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Review by tshortli — APPROVED** [review]

File: test/Sema/rdar129359362.swift [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+
+public class MyClass {
+  public lazy var lazyVar: Int = { 2 }()
+}
+
+//--- Client.swift
+
+import Lib
+
+func test(foo: MyClass) {
```
Comment (tshortli) [inline test/Sema/rdar129359362.swift]: Rather than having a dedicated test-case for this, you might consider extending `Serialization/lazy-typecheck` (which is based on `/Inputs/lazy_typecheck.swift` and `/Inputs/lazy_typecheck_client.swift`). The benefit would be that it will get exercised in a number of different ways.

Comment (xedin) [reply test/Sema/rdar129359362.swift]: Thanks, I'll do that!

Comment (xedin) [reply test/Sema/rdar129359362.swift]: ✅

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform
