### PR TITLE
Fix 82618 (casting of collection types)

### LINKED ISSUE #82618: App crashes on the boundary between Swift 5 and Swift 6 code
### Description

Examples consists of two targets, one compiled with Swift 6 mode (or Swift 5 with strict isolation checking), and another with Swift 5 mode with minimal isolation checking. Swift 5 target calls a function from Swift 6 target. At the call site `Dictionary<String, () -> ()>` is casted to `Dictionary<String, @MainActor @Sendable () -> ()>`, which fails.

Issue does not reproduce when importing target is compiled with strict isolation checking or `-warn-concurrency` flag.

### Reproduction

```swift
// MyLib: Swift 6

@preconcurrency public typealias Action = @MainActor () -> Void

@preconcurrency @MainActor
public func useIt(_ actions: [String: Action]) {
    actions["xyz"]?()
}

// MyApp: Swift 5, minimal checking
import MyLib

func getActions() -> [String: Action] {
    return [
        "abc": { print("abc") },
        "xyz": { print("xyz") }
    ]
}

// CRASH: Could not cast value of type '() -> ()' (0x104818518) to '@Swift.MainActor @Sendable () -> ()' (0x10487ebf8).
//
// #0 __pthread_kill ()
// #1 pthread_kill ()
// #2 abort ()
// #3 swift::fatalErrorv ()
// #4 swift::fatalError ()
// #5 swift::swift_dynamicCastFailure ()
// #6 swift::swift_dynamicCastFailure ()
// #7 swift_dynamicCast ()
// #8 Swift._dictionaryUpCast<τ_0_0, τ_0_1, τ_0_2, τ_0_3 where τ_0_0: Swift.Hashable, τ_0_2: Swift.Hashable>(Swift.Dictionary<// τ_0_0, τ_0_1>) -> Swift.Dictionary<τ_0_2, τ_0_3> ()
// 
useIt(getActions())
```

### Expected behavior

App should run without crashing, or compiler should emit an error preventing app from building.

### Environment

Xcode 16.4 (Apple Swift version 6.1.2).
Nightly toolchain (2025-06-22).

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by nickolas-pohilets**
This MR adds missing functionality to generate code for `KeyConversion` and `ValueConversion` in `CollectionUpcastConversionExpr`. New built-ins have been added to the standard library as `@_alwaysEmitIntoClient` for backwards compatibility.

Resolves #82618

### CODE REVIEW

File: lib/SILGen/SILGenExpr.cpp [hunk 1]
```diff
@@ -1547,18 +1636,187 @@ visitCollectionUpcastConversionExpr(CollectionUpcastConversionExpr *E,
...
-  return SGF.emitCollectionConversion(loc, fn, fromCollection, toCollection,
-                                      mv, C);
+  return SGF.emitCollectionConversion(loc, fn, fromCollection, toCollection, mv,
+                                      keyConversion, valueConversion, C);
+}
+
+namespace {
+class ConversionClosureEmitter: public Lowering::ExprVisitor<ConversionClosureEmitter, Expr*> {
+  ASTContext &Context;
+  OpaqueValueExpr *OrigValue;
```
Comment (kavon) [inline lib/SILGen/SILGenExpr.cpp]: AST transformations and non-trivial expression synthesis should happen in Sema, not SILGen. One of the main reasons why is that SILGen happens after the ASTVerifier has run.

One way to do this is to define an `ASTWalker` and have it run during `TypeCheckPrimaryFileRequest::evaluate`.

Comment (nickolas-pohilets) [reply lib/SILGen/SILGenExpr.cpp]: If  `CollectionUpcastConversionExpr` is replaced by `ApplyExpr` in Sema. then Sema will know about details of lowering into a function call, which is `SILGen`'s job.

Note that synthesised closures are disconnected from the AST, and could be deleted if they were not AST-allocated. It's not much of a syntheses, more of a conversion from `ConversionPair` into a format understandable by the rest of the `SILGen`.

I think the best approach would be to use `ClosureExpr` instead of `ConversionPair` in the first place. I'll give it a try.

**Comment by nickolas-pohilets** [comment]
@swift-ci please smoke test

File: lib/SILGen/SILGenExpr.cpp (hunk 1 above)
Comment (kavon) [reply lib/SILGen/SILGenExpr.cpp]: >If  CollectionUpcastConversionExpr is replaced by ApplyExpr in Sema. then Sema will know about details of lowering into a function call, which is SILGen's job.

Sema should know about those details and AST expression synthesis should happen there, even if it is "lowering" one expression into some other expressions. There should not be expression synthesis in SILGen.

**Review by kavon — CHANGES_REQUESTED** [review]

**Comment by nickolas-pohilets** [comment]
@swift-ci Please test

**Comment by glessard** [comment]
@swift-ci please test

File: lib/SILGen/SILGenExpr.cpp [hunk 2]
```diff
@@ -1571,18 +1674,193 @@ visitCollectionUpcastConversionExpr(CollectionUpcastConversionExpr *E,
 
   // Get the intrinsic function.
   FuncDecl *fn = nullptr;
+  ClosureExpr *keyConversion = nullptr;
+  ClosureExpr *valueConversion = nullptr;
   if (fromCollection->isArray()) {
-    fn = SGF.SGM.getArrayForceCast(loc);
+    if (needsCustomConversion(E->getValueConversion())) {
+      fn = SGF.SGM.getArrayWitnessCast(loc);
+      valueConversion = synthesizeConversionClosure(E->getValueConversion());
```
Comment (kavon) [inline lib/SILGen/SILGenExpr.cpp]: This AST generation is bypassing the AST verifier and needs to happen in Sema, not SILGen. This is the same feedback I've given before that hasn't been addressed.

**Review by kavon — CHANGES_REQUESTED** [review]

File: lib/SILGen/SILGenExpr.cpp (hunk 2 above)
Comment (nickolas-pohilets) [reply lib/SILGen/SILGenExpr.cpp]: I'm looking into this right now. Ive pushed some changes to stabilise the current version before starting refactoring.

**Comment by nickolas-pohilets** [comment]
@swift-ci please test

**Comment by nickolas-pohilets** [comment]
@swift-ci please test

File: lib/SILGen/SILGenExpr.cpp (hunk 1 above)
Comment (nickolas-pohilets) [reply lib/SILGen/SILGenExpr.cpp]: I've pushed an update where, element conversion is modelled using `ClosureExpr`, constructed in Sema before AST validation. Please take a look.

File: include/swift/AST/Expr.h [hunk 3]
```diff
@@ -3415,52 +3418,45 @@ class MetatypeConversionExpr : public ImplicitConversionExpr {
...
+  ClosureExpr *getValueConversion() const { return ValueConversion; }
+  void setValueConversion(ClosureExpr *pair) { ValueConversion = pair; }
 
   static bool classof(const Expr *E) {
     return E->getKind() == ExprKind::CollectionUpcastConversion;
   }
 };
-  
+
+struct ConversionPair {
```
Comment (kavon) [inline include/swift/AST/Expr.h:3453]: minor: Perhaps this should live under ErasureExpr now? Feels weird to have this hanging around at the top level in this namespace while not being an Expr, and ErasureExpr seems to be the only user now.

File: lib/AST/ASTVerifier.cpp [hunk 4]
```diff
@@ -967,24 +967,6 @@ class Verifier : public ASTWalker {
       OptionalEvaluations.pop_back();
     }
 
-    // Register the OVEs in a collection upcast.
-    bool shouldVerify(CollectionUpcastConversionExpr *expr) {
```
Comment (kavon) [inline lib/AST/ASTVerifier.cpp:971]: First, this removal is makes sense.

Elsewhere in `void verifyChecked(CollectionUpcastConversionExpr *E)` it would be good to call verifyChecked on the key and value version ClosureExpr's to ensure they're well-formed.

It doesn't look like we were checking the expressions in the ConversionPair's beforehand, either, so this is a nice-to-have suggestion.

File: lib/Sema/MiscDiagnostics.cpp [hunk 5]
```diff
@@ -6495,7 +6502,7 @@ void swift::performSyntacticExprDiagnostics(const Expr *E,
   if (!ctx.isLanguageModeAtLeast(5))
     diagnoseDeprecatedWritableKeyPath(E, DC);
   if (!ctx.LangOpts.DisableAvailabilityChecking)
-    diagnoseExprAvailability(E, const_cast<DeclContext*>(DC));
+    diagnoseExprAvailability(E, const_cast<DeclContext *>(DC), false);
```
Comment (kavon) [inline lib/Sema/MiscDiagnostics.cpp]: minor: this spot was missing the helpful argument name
```suggestion
    diagnoseExprAvailability(E, const_cast<DeclContext *>(DC), /*preconcurrency=*/false);
```

File: lib/SILGen/SILGenDynamicCast.cpp [hunk 6]
```diff
@@ -394,7 +394,7 @@ static RValue emitCollectionDowncastExpr(SILGenFunction &SGF,
   }
 
   return SGF.emitCollectionConversion(loc, fn, fromCollection, toCollection,
-                                      source, C);
+                                      source, nullptr, nullptr, C);
```
Comment (kavon) [inline lib/SILGen/SILGenDynamicCast.cpp]: minor:
```suggestion
                                      source, /*keyConversion*/nullptr, /*valueConversion*/nullptr, C);
```

File: lib/SILGen/SILGenPoly.cpp [hunk 7]
```diff
@@ -647,9 +647,10 @@ ManagedValue Transform::transform(ManagedValue v,
         llvm::report_fatal_error("unsupported collection upcast kind");
       }
 
-      return SGF.emitCollectionConversion(Loc, fn, inputSubstType,
-                                          outputSubstType, v, ctxt)
-                .getScalarValue();
+      return SGF
+          .emitCollectionConversion(Loc, fn, inputSubstType, outputSubstType, v,
+                                    nullptr, nullptr, ctxt)
```
Comment (kavon) [inline lib/SILGen/SILGenPoly.cpp]: minor:
```suggestion
                                    /*keyConversion*/nullptr, /*valueConversion*/nullptr, ctxt)
```

**Review by kavon — APPROVED** [review]
Overall this looks great! Thank you for doing this! I haven't had a chance to review every cast being tested in your test, but the ones I checked look OK.

Regarding the scenarios that are marked as currently failing and excluded with `#if false` due to the issue you describe [here](https://forums.swift.org/t/casting-closure-collections/82100/10)... I assume they're casts that always have been broken and you've just now discovered? Is it possible to have those parts included and running in the test, by using `expectFailure { }` to wrap the parts where the cast is failing/succeeding when it shouldn't? It would help us know if some other PR fixes it in the future, but I don't know if `expectFailure` can handle it if the bug traps at runtime.

If the source compat suite looks OK with these changes, I think it's ready to merge.

**Comment by kavon** [comment]
@swift-ci Please Test Source Compatibility

**Comment by kavon** [comment]
@swift-ci Please Test Source Compatibility Debug

**Comment by nickolas-pohilets** [comment]
@swift-ci Please Test Source Compatibility Debug

File: include/swift/AST/Expr.h (hunk 3 above)
Comment (nickolas-pohilets) [reply include/swift/AST/Expr.h:3453]: IIRC, I've tried it, and then C++ compiler could not see `ErasureExpr::ConversionPair` in `class ErasureExpr: ... llvm::TrailingObjects<ErasureExpr, ProtocolConformanceRef, ErasureExpr::ConversionPair>`. To my best knowledge it is not possible to forward declare a nested class in C++. 

As an alternative, I could place it inside `ImplicitConversionExpr`.

Comment (nickolas-pohilets) [reply include/swift/AST/Expr.h:3453]: Do you think it is feasible to get rid of `OpaqueValueExpr` completely (in follow up MRs)? At least one use case (`OpenExistentialExpr`) would require `ClosureExpr` of `GenericFunctionType`. Is it possible?

**Comment by nickolas-pohilets** [comment]
> Regarding the scenarios that are marked as currently failing and excluded with `#if false` due to the issue you describe [here](https://forums.swift.org/t/casting-closure-collections/82100/10)... I assume they're casts that always have been broken and you've just now discovered? Is it possible to have those parts included and running in the test, by using `expectFailure { }` to wrap the parts where the cast is failing/succeeding when it shouldn't? It would help us know if some other PR fixes it in the future, but I don't know if `expectFailure` can handle it if the bug traps at runtime.

`expectFailure()` does not help here, but `expectCrashLater()` does the job.

File: lib/AST/ASTVerifier.cpp (hunk 4 above)
Comment (nickolas-pohilets) [reply lib/AST/ASTVerifier.cpp:971]: Tried it, verification fails. I'm looking into it.

Comment (nickolas-pohilets) [reply lib/AST/ASTVerifier.cpp:971]: `verifyParsed(AbstractClosureExpr *E)` and `void verifyChecked(AbstractClosureExpr *E)` are called on key and value conversion with the code being as is. This is handled in `ASTWalker`.  `Verifier` is not responsible for recursive traversal, so I'm not sure why `verifyChecked(E->getSubExpr());` is there. I've got an impression that entire `verifyChecked(CollectionUpcastConversionExpr *E)` could be removed after https://github.com/swiftlang/swift/commit/0390e7f034b7754e173390960a867bcdbba12a79, but I don't fully understand the code. I'll keep it as is for now.

**Comment by nickolas-pohilets** [comment]
@swift-ci Please Test Source Compatibility Debug

**Comment by nickolas-pohilets** [comment]
@swift-ci please smoke test

File: include/swift/AST/Expr.h (hunk 3 above)
Comment (kavon) [reply include/swift/AST/Expr.h:3453]: > As an alternative, I could place it inside ImplicitConversionExpr.

That sounds like a good alternative.

> Do you think it is feasible to get rid of OpaqueValueExpr completely (in follow up MRs)?

That might be a difficult task. I believe it serves as a sort of "variable reference" to an instance of an opened existential value, to ensure we're referring to the same opened existential within expressions that can also mutate the real variable that holds the existential.

**Comment by nickolas-pohilets** [comment]
Source compatibility suite has 4 failures, all failing at link time unable to find `SwiftUI.Binding.init(get: @isolated(any) () -> A, set: @isolated(any) (A) -> ()) -> SwiftUI.Binding<A>`. I'm not sure how this can be related to my changes.

**Comment by nickolas-pohilets** [comment]
@swift-ci please smoke test

**Comment by nickolas-pohilets** [comment]
@swift-ci Please Test Source Compatibility Debug

**Comment by kavon** [comment]
> Source compatibility suite has 4 failures [...] I'm not sure how this can be related to my changes.

Yeah they seem unrelated. If it fails again for unrelated things we can just go ahead and merge.

**Comment by kavon** [comment]
@swift-ci smoke test windows
