### PR TITLE
[Sema] Avoid folding sequences multiple times

### LINKED ISSUE #75845: Assertion failed: (hasType(node) && "Expected type to have been set!") when assigning `self` from implicit `error` variable
The following new test case causes an assertion failure

```swift
// RUN: %batch-code-completion

struct Foo {
  init() {
    do {
    } catch {
      self = error#^COMPLETE^#
    }
  }
}
```

Stack trace:

```
Assertion failed: (hasType(node) && "Expected type to have been set!"), function getType, file ConstraintSystem.h, line 3283.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
(decl_context: )Stack dump:
0.	Program arguments: /Users/alex/sbin/swift-ide-test -code-completion -source-filename /private/var/folders/9_/vrdblnzs0m762wbv2hsryrkr0000gn/T/reduced.swift -code-completion-token COMPLETE
1.	While performing new IDE inspection
2.	While evaluating request IDEInspectionSecondPassRequest(source_file "/private/var/folders/9_/vrdblnzs0m762wbv2hsryrkr0000gn/T/reduced.swift", )
3.	While evaluating request TypeCheckASTNodeAtLocRequest(0x14d0a6218 AbstractFunctionDecl name=init() : (no type set), )
4.	While type-checking expression at [/private/var/folders/9_/vrdblnzs0m762wbv2hsryrkr0000gn/T/reduced.swift:7:7 - line:7:19] RangeText="self = error"
5.	While type-checking-target starting at /private/var/folders/9_/vrdblnzs0m762wbv2hsryrkr0000gn/T/reduced.swift:7:7
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-ide-test           0x000000010a6a1f4c llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-ide-test           0x000000010a6a0314 llvm::sys::RunSignalHandlers() + 112
2  swift-ide-test           0x000000010a6a25e0 SignalHandler(int) + 352
3  libsystem_platform.dylib 0x000000019a47d184 _sigtramp + 56
4  libsystem_pthread.dylib  0x000000019a445f70 pthread_kill + 288
5  libsystem_c.dylib        0x000000019a352908 abort + 128
6  libsystem_c.dylib        0x000000019a351c1c err + 0
7  swift-ide-test           0x000000010a7baa00 swift::constraints::ConstraintSystem::getType(swift::ASTNode) const (.cold.3) + 0
8  swift-ide-test           0x00000001052f93c0 swift::constraints::ConstraintSystem::getType(swift::ASTNode) const + 228
9  swift-ide-test           0x00000001060e8738 (anonymous namespace)::ConstraintGenerator::genAssignDestType(swift::Expr*, swift::constraints::ConstraintSystem&) + 148
10 swift-ide-test           0x00000001060e32c0 (anonymous namespace)::ConstraintGenerator::visitAssignExpr(swift::AssignExpr*) + 56
11 swift-ide-test           0x00000001060db3a8 (anonymous namespace)::ConstraintWalker::walkToExprPost(swift::Expr*) + 1192
12 swift-ide-test           0x0000000104ece454 (anonymous namespace)::Traversal::doIt(swift::Expr*) + 988
13 swift-ide-test           0x0000000104ece06c swift::Expr::walk(swift::ASTWalker&) + 32
14 swift-ide-test           0x00000001060d6fcc swift::constraints::ConstraintSystem::generateConstraints(swift::Expr*, swift::DeclContext*) + 104
15 swift-ide-test           0x00000001060d62d8 swift::constraints::ConstraintSystem::generateConstraints(swift::constraints::SyntacticElementTarget&, swift::FreeTypeVariableBinding) + 432
16 swift-ide-test           0x0000000106139094 swift::constraints::ConstraintSystem::solveForCodeCompletion(swift::constraints::SyntacticElementTarget&, llvm::SmallVectorImpl<swift::constraints::Solution>&) + 176
17 swift-ide-test           0x000000010629e8dc swift::TypeChecker::typeCheckForCodeCompletion(swift::constraints::SyntacticElementTarget&, bool, llvm::function_ref<void (swift::constraints::Solution const&)>)::$_3::operator()(swift::constraints::SyntacticElementTarget&) const + 348
18 swift-ide-test           0x000000010629e688 swift::TypeChecker::typeCheckForCodeCompletion(swift::constraints::SyntacticElementTarget&, bool, llvm::function_ref<void (swift::constraints::Solution const&)>) + 200
19 swift-ide-test           0x00000001062c1fac swift::TypeChecker::typeCheckTarget(swift::constraints::SyntacticElementTarget&, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 192
20 swift-ide-test           0x00000001062c1e94 swift::TypeChecker::typeCheckExpression(swift::constraints::SyntacticElementTarget&, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 184
21 swift-ide-test           0x00000001062c1d68 swift::TypeChecker::typeCheckExpression(swift::Expr*&, swift::DeclContext*, swift::constraints::ContextualTypeInfo, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 92
22 swift-ide-test           0x000000010637a904 (anonymous namespace)::StmtChecker::typeCheckASTNode(swift::ASTNode&) + 248
23 swift-ide-test           0x000000010637b098 swift::TypeCheckASTNodeAtLocRequest::evaluate(swift::Evaluator&, swift::TypeCheckASTNodeAtLocContext, swift::SourceLoc) const + 900
24 swift-ide-test           0x00000001063c2cb8 swift::TypeCheckASTNodeAtLocRequest::OutputType swift::Evaluator::getResultUncached<swift::TypeCheckASTNodeAtLocRequest, swift::TypeCheckASTNodeAtLocRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckASTNodeAtLocRequest>(swift::Evaluator&, swift::TypeCheckASTNodeAtLocRequest, swift::TypeCheckASTNodeAtLocRequest::OutputType)::'lambda'()>(swift::TypeCheckASTNodeAtLocRequest const&, swift::TypeCheckASTNodeAtLocRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckASTNodeAtLocRequest>(swift::Evaluator&, swift::TypeCheckASTNodeAtLocRequest, swift::TypeCheckASTNodeAtLocRequest::OutputType)::'lambda'()) + 208
25 swift-ide-test           0x00000001063b6924 swift::typeCheckASTNodeAtLoc(swift::TypeCheckASTNodeAtLocContext, swift::SourceLoc) + 76
26 swift-ide-test           0x00000001052ca478 swift::ide::typeCheckContextAt(swift::TypeCheckASTNodeAtLocContext, swift::SourceLoc) + 316
27 swift-ide-test           0x000000010529a5c0 (anonymous namespace)::CodeCompletionCallbacksImpl::typeCheckWithLookup(swift::ide::TypeCheckCompletionCallback&, swift::SourceLoc) + 188
28 swift-ide-test           0x0000000105296214 (anonymous namespace)::CodeCompletionCallbacksImpl::doneParsing(swift::SourceFile*) + 716
29 swift-ide-test           0x00000001065f170c swift::Parser::performIDEInspectionSecondPassImpl(swift::IDEInspectionDelayedDeclState&) + 600
30 swift-ide-test           0x00000001065f13c4 swift::IDEInspectionSecondPassRequest::evaluate(swift::Evaluator&, swift::SourceFile*, swift::IDEInspectionCallbacksFactory*) const + 168
31 swift-ide-test           0x00000001065f76c0 swift::IDEInspectionSecondPassRequest::OutputType swift::Evaluator::getResultUncached<swift::IDEInspectionSecondPassRequest, swift::IDEInspectionSecondPassRequest::OutputType swift::evaluateOrDefault<swift::IDEInspectionSecondPassRequest>(swift::Evaluator&, swift::IDEInspectionSecondPassRequest, swift::IDEInspectionSecondPassRequest::OutputType)::'lambda'()>(swift::IDEInspectionSecondPassRequest const&, swift::IDEInspectionSecondPassRequest::OutputType swift::evaluateOrDefault<swift::IDEInspectionSecondPassRequest>(swift::Evaluator&, swift::IDEInspectionSecondPassRequest, swift::IDEInspectionSecondPassRequest::OutputType)::'lambda'()) + 232
32 swift-ide-test           0x00000001065f130c swift::performIDEInspectionSecondPass(swift::SourceFile&, swift::IDEInspectionCallbacksFactory&) + 52
33 swift-ide-test           0x000000010531c5f4 void llvm::function_ref<void (swift::ide::IDEInspectionInstanceResult const&, llvm::function_ref<void (swift::ide::CancellableResult<swift::ide::CodeCompleteResult>)>)>::callback_fn<swift::ide::IDEInspectionInstance::codeComplete(swift::CompilerInvocation&, llvm::ArrayRef<char const*>, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, llvm::MemoryBuffer*, unsigned int, swift::DiagnosticConsumer*, swift::ide::CodeCompletionContext&, std::__1::shared_ptr<std::__1::atomic<bool>>, llvm::function_ref<void (swift::ide::CancellableResult<swift::ide::CodeCompleteResult>)>)::$_1::operator()(swift::ide::CancellableResult<swift::ide::IDEInspectionInstanceResult>) const::'lambda'(auto&, auto)>(long, swift::ide::IDEInspectionInstanceResult const&, llvm::function_ref<void (swift::ide::CancellableResult<swift::ide::CodeCompleteResult>)>) + 896
34 swift-ide-test           0x000000010531bc88 void swift::ide::CancellableResult<swift::ide::IDEInspectionInstanceResult>::mapAsync<swift::ide::CodeCompleteResult>(llvm::function_ref<void (swift::ide::IDEInspectionInstanceResult const&, llvm::function_ref<void (swift::ide::CancellableResult<swift::ide::CodeCompleteResult>)>)>, llvm::function_ref<void (swift::ide::CancellableResult<swift::ide::CodeCompleteResult>)>) + 84
35 swift-ide-test           0x000000010531bbd0 void llvm::function_ref<void (swift::ide::CancellableResult<swift::ide::IDEInspectionInstanceResult>)>::callback_fn<swift::ide::IDEInspectionInstance::codeComplete(swift::CompilerInvocation&, llvm::ArrayRef<char const*>, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, llvm::MemoryBuffer*, unsigned int, swift::DiagnosticConsumer*, swift::ide::CodeCompletionContext&, std::__1::shared_ptr<std::__1::atomic<bool>>, llvm::function_ref<void (swift::ide::CancellableResult<swift::ide::CodeCompleteResult>)>)::$_1>(long, swift::ide::CancellableResult<swift::ide::IDEInspectionInstanceResult>) + 128
36 swift-ide-test           0x000000010531aeac swift::ide::IDEInspectionInstance::performNewOperation(std::__1::optional<llvm::hash_code>, swift::CompilerInvocation&, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, llvm::MemoryBuffer*, unsigned int, swift::DiagnosticConsumer*, std::__1::shared_ptr<std::__1::atomic<bool>>, llvm::function_ref<void (swift::ide::CancellableResult<swift::ide::IDEInspectionInstanceResult>)>) + 928
37 swift-ide-test           0x000000010531b650 swift::ide::IDEInspectionInstance::performOperation(swift::CompilerInvocation&, llvm::ArrayRef<char const*>, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, llvm::MemoryBuffer*, unsigned int, swift::DiagnosticConsumer*, std::__1::shared_ptr<std::__1::atomic<bool>>, llvm::function_ref<void (swift::ide::CancellableResult<swift::ide::IDEInspectionInstanceResult>)>) + 552
38 swift-ide-test           0x000000010531b890 swift::ide::IDEInspectionInstance::codeComplete(swift::CompilerInvocation&, llvm::ArrayRef<char const*>, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, llvm::MemoryBuffer*, unsigned int, swift::DiagnosticConsumer*, swift::ide::CodeCompletionContext&, std::__1::shared_ptr<std::__1::atomic<bool>>, llvm::function_ref<void (swift::ide::CancellableResult<swift::ide::CodeCompleteResult>)>) + 216
39 swift-ide-test           0x0000000104dbf70c bool llvm::function_ref<bool (CompletionLikeOperationParams)>::callback_fn<doCodeCompletion(swift::CompilerInvocation const&, llvm::StringRef, llvm::StringRef, llvm::StringRef, bool, bool, bool, bool, bool, bool, bool)::$_8>(long, CompletionLikeOperationParams) + 344
40 swift-ide-test           0x0000000104dbf3a4 performWithCompletionLikeOperationParams(swift::CompilerInvocation const&, llvm::StringRef, llvm::StringRef, llvm::StringRef, bool, llvm::function_ref<bool (CompletionLikeOperationParams)>) + 1220
41 swift-ide-test           0x0000000104dad208 doCodeCompletion(swift::CompilerInvocation const&, llvm::StringRef, llvm::StringRef, llvm::StringRef, bool, bool, bool, bool, bool, bool, bool) + 444
42 swift-ide-test           0x0000000104da8e8c main + 10072
43 dyld                     0x000000019a0c3274 start + 2840

```

### PR DESCRIPTION
**Pull request by hamishknight**
Completion can end up calling into pre-checking multiple times in certain cases, make sure we don't attempt to fold a SequenceExpr multiple times since its original AST is in a broken state post-folding. Instead, just return the already-folded expression.

rdar://133717866
Resolves #75845

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

File: validation-test/compiler_crashers_2_fixed/1f6ae695bebb359b.swift [hunk 1]
```diff
@@ -1,3 +1,3 @@
 // {"signature":"makeBinOp(swift::ASTContext&, swift::Expr*, swift::Expr*, swift::Expr*, swift::PrecedenceGroupDecl*, bool)"}
-// RUN: not --crash %target-swift-frontend -typecheck %s
+// RUN: not %target-swift-frontend -typecheck %s
```
Comment (hamishknight) [inline validation-test/compiler_crashers_2_fixed/1f6ae695bebb359b.swift:2]: Turns out this also affects pattern type-checking, I'll look into that in a follow-up

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Review by xedin — APPROVED** [review]
