### PR TITLE
[CSApply] Key path dynamic member lookup argument is Sendable only if its captures are

### LINKED ISSUE #77105: Dynamic member lookup does not honor sendability of key paths
### Description

If a dynamic member subscript is limited to sendable key paths, this check is only performed when invoking the dynamic member directly.

### Reproduction

```swift
@dynamicMemberLookup
struct S<T> {
  subscript<U>(dynamicMember keyPath: KeyPath<T, U> & Sendable) -> U {
    fatalError()
  }
}

public struct Foo {
  subscript<T>(bar bar: T) -> Int { 42 }
}

public struct NonSendable: Hashable {}

func f() {
  let s = S<Foo>()
  s[dynamicMember: \.[bar: NonSendable()]]  // ❌ Fails to compile
  s[bar: NonSendable()]                     // ✅ Compiles when it shouldn't
}
```

### Expected behavior

I expect both lines to fail to compiles.

### Environment

swift-driver version: 1.115 Apple Swift version 6.0.2 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
Target: arm64-apple-macosx15.0

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by xedin**
Previously dynamic member subscript wasn't allowed to use `& Sendable`,
since this restriction was lifted the argument cannot simply assume
the parameter type any longer, the key path captures have to be checked
to determine whether it could be marked as Sendable or not.

Resolves: https://github.com/swiftlang/swift/issues/77105
Resolves: rdar://138227393

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

File: lib/Sema/CSApply.cpp [hunk 1]
```diff
@@ -2556,18 +2556,39 @@ namespace {
...
       using Component = KeyPathExpr::Component;
       auto *anchor = getAsExpr(memberLoc->getAnchor());
 
       auto makeKeyPath = [&](ArrayRef<Component> components) -> Expr * {
+        Type keyPathTy = paramType;
+
+        // If parameter of a dynamic member lookup is `& Sendable` type
+        // we need to check key path captures to determine whether the
+        // argument could be `& Sendable` as well or not.
+        if (paramType->isExistentialType() && paramType->isSendableType()) {
```
Comment (hamishknight) [inline lib/Sema/CSApply.cpp:2574]: Could this be `paramType->isSendableExistential()` instead?

**Review by hamishknight — APPROVED** [review]

File: lib/Sema/CSApply.cpp (hunk 1 above)
Comment (xedin) [reply lib/Sema/CSApply.cpp:2574]: I think that’s only for `any Sendable` and doesn’t handle compositions but I will double-check.

Comment (hamishknight) [reply lib/Sema/CSApply.cpp:2574]: Oh sorry yes you're right, I misread the code

**Comment by xedin** [comment]
@swift-ci please smoke test
