### PR TITLE
[Serialization] Drop overriding relationship in constructors when safe

### LINKED ISSUE #63242: [Source compatibility suite] RXSwift failing to build with release config - error: generic parameter 'Element' could not be inferred
**Describe the bug**
The RXSwift project is failing to build certain configurations as of Jan 25th, 2023 

From the build logs you can see 
```
/Users/ec2-user/jenkins/workspace/swift-main-source-compat-suite/swift-source-compat-suite/project_cache/RxSwift/RxRelay/PublishRelay.swift:24:24: error: 'PublishSubject<Element>' cannot be constructed because it has no accessible initializers
        self.subject = PublishSubject()
                       ^~~~~~~~~~~~~~
/Users/ec2-user/jenkins/workspace/swift-main-source-compat-suite/swift-source-compat-suite/project_cache/RxSwift/RxRelay/PublishRelay.swift:24:24: error: generic parameter 'Element' could not be inferred
        self.subject = PublishSubject()
                       ^
/Users/ec2-user/jenkins/workspace/swift-main-source-compat-suite/swift-source-compat-suite/project_cache/RxSwift/RxRelay/PublishRelay.swift:24:24: note: explicitly specify the generic arguments to fix this issue
        self.subject = PublishSubject()
                       ^
```

You can see all the failing configurations here:
http://ci.swift.org/job/swift-main-source-compat-suite/312/artifact/swift-source-compat-suite/

**Expected behavior**
Expecting the project to build correctly

**Environment**
```
Apple Swift version 5.9-dev (LLVM 9c08d218ae741f4, Swift 8eee0fff5ef0841)
```

https://ci.swift.org/job/swift-main-source-compat-suite/286

This appears to only affect the release config of the project build

### PR DESCRIPTION
**Pull request by xymus**
Deserialization recovery lead the compiler to drop public constructors overriding internal constructors. This PR limits the logic to dropping only the overriding relationship instead of the whole constructor. This applies when the overriden constructor fails to deserialize and only when the overriding relationship was marked as not affecting ABI. This should realign the behavior between swiftmodules and swiftinterfaces.

rdar://104704832

Fixes: https://github.com/apple/swift/issues/63242

This is the equivalent of https://github.com/apple/swift/pull/63068 for constructors.

### CODE REVIEW

**Comment by xymus** [comment]
@swift-ci Please smoke test

File: lib/Serialization/Deserialization.cpp [hunk 1]
```diff
@@ -3130,15 +3131,23 @@ class DeclDeserializer {
...
     }
 
-    auto overridden = MF.getDeclChecked(overriddenID);
-    if (!overridden) {
+    Expected<Decl *> overriddenOrError = MF.getDeclChecked(overriddenID);
+    Decl *overridden;
+    if (overriddenOrError) {
+      overridden = overriddenOrError.get();
+    } else {
+      if (overriddenAffectsABI || !ctx.LangOpts.EnableDeserializationRecovery) {
```
Comment (bnbarham) [inline lib/Serialization/Deserialization.cpp:3139]: Could we set `overridden = nullptr` if we're allowing compiler errors in this case (ie. `MF.allowCompilerErrors`)?

File: lib/Serialization/Serialization.cpp [hunk 2]
```diff
@@ -4494,9 +4494,12 @@ class Serializer::DeclSerializer : public DeclVisitor<DeclSerializer> {
     uint8_t rawAccessLevel = getRawStableAccessLevel(ctor->getFormalAccess());
 
     bool firstTimeRequired = ctor->isRequired();
-    if (auto *overridden = ctor->getOverriddenDecl())
+    auto *overridden = ctor->getOverriddenDecl();
+    if (overridden) {
       if (firstTimeRequired && overridden->isRequired())
         firstTimeRequired = false;
+    }
+    bool overriddenAffectsABI = overriddenDeclAffectsABI(ctor, overridden);
```
Comment (bnbarham) [inline lib/Serialization/Serialization.cpp:4502]: Is the relationship actually useful if it doesn't?

**Review by bnbarham — APPROVED** [review]

File: lib/Serialization/Serialization.cpp (hunk 2 above)
Comment (xymus) [reply lib/Serialization/Serialization.cpp:4510]: That's a good question. For non-resilient modules it could be used by optimizations. For resilient modules in most cases it should now be dropped by deserialization safety for the public-override-internal case, and the clang case is there more as tolerance for poor modularization and such I believe. I think we could try always dropping it when reading from a resilient module.

File: lib/Serialization/Deserialization.cpp (hunk 1 above)
Comment (xymus) [reply lib/Serialization/Deserialization.cpp]: Sure 👍

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Review by xedin — APPROVED** [review]

**Comment by xymus** [comment]
@swift-ci Please smoke test

**Comment by xymus** [comment]
@swift-ci Please smoke test macOS

**Comment by xymus** [comment]
@swift-ci Please smoke test macOS

**Comment by xymus** [comment]
https://github.com/apple/swift-driver/pull/1281

@swift-ci please smoke test macOS
