### PR TITLE
[Index] Fix incorrect setter references for subscript keys

### LINKED ISSUE #56541: [SR-14162] Index store does not relate static property getter used as subscript key.
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14162      |
   |Radar             | rdar://problem/74102056         |
   |Original Reporter | Leitch (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift 5.3 & 5.4 beta (Xcode 12.5 beta 1)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Source Tooling    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 7c96ce342087142383568e877034f2d5

  </details>

**Issue Description:**

Given the following code:

``` swift
enum FixtureEnum128 {
    static let someVar = ""
}

class FixtureClass128 {
    func someFunc() {
        var s: [String: Int] = [:]
        s[FixtureEnum128.someVar] = 0
    }
}
```

The index store does not relate the `someVar` getter when used as a subscript key. It does however relate the setter, which is also incorrect.

``` java
1:6 | enum/Swift | FixtureEnum128 | s:14swift_ide_test14FixtureEnum128O | Def | rel: 0
2:16 | static-property/Swift | someVar | s:14swift_ide_test14FixtureEnum128O7someVarSSvpZ | Def,RelChild | rel: 1
  RelChild | enum/Swift | FixtureEnum128 | s:14swift_ide_test14FixtureEnum128O
2:16 | static-method/acc-get/Swift | getter:someVar | s:14swift_ide_test14FixtureEnum128O7someVarSSvgZ | Def,Impl,RelChild,RelAcc | rel: 1
  RelChild,RelAcc | static-property/Swift | someVar | s:14swift_ide_test14FixtureEnum128O7someVarSSvpZ
2:16 | static-method/acc-set/Swift | setter:someVar | s:14swift_ide_test14FixtureEnum128O7someVarSSvsZ | Def,Impl,RelChild,RelAcc | rel: 1
  RelChild,RelAcc | static-property/Swift | someVar | s:14swift_ide_test14FixtureEnum128O7someVarSSvpZ
5:7 | class/Swift | FixtureClass128 | s:14swift_ide_test15FixtureClass128C | Def | rel: 0
6:10 | instance-method/Swift | someFunc() | s:14swift_ide_test15FixtureClass128C8someFuncyyF | Def,Dyn,RelChild | rel: 1
  RelChild | class/Swift | FixtureClass128 | s:14swift_ide_test15FixtureClass128C
7:17 | struct/Swift | String | s:SS | Ref,RelCont | rel: 1
  RelCont | instance-method/Swift | someFunc() | s:14swift_ide_test15FixtureClass128C8someFuncyyF
7:25 | struct/Swift | Int | s:Si | Ref,RelCont | rel: 1
  RelCont | instance-method/Swift | someFunc() | s:14swift_ide_test15FixtureClass128C8someFuncyyF
8:10 | instance-property/subscript/Swift | subscript(_:) | s:SDyq_Sgxcip | Ref,Writ,RelCont | rel: 1
  RelCont | instance-method/Swift | someFunc() | s:14swift_ide_test15FixtureClass128C8someFuncyyF
8:10 | instance-method/acc-set/Swift | setter:subscript(_:) | s:SDyq_Sgxcis | Ref,Call,Impl,RelCall,RelCont | rel: 1
  RelCall,RelCont | instance-method/Swift | someFunc() | s:14swift_ide_test15FixtureClass128C8someFuncyyF
8:11 | enum/Swift | FixtureEnum128 | s:14swift_ide_test14FixtureEnum128O | Ref,RelCont | rel: 1
  RelCont | instance-method/Swift | someFunc() | s:14swift_ide_test15FixtureClass128C8someFuncyyF
8:26 | static-property/Swift | someVar | s:14swift_ide_test14FixtureEnum128O7someVarSSvpZ | Ref,Writ,RelCont | rel: 1
  RelCont | instance-method/Swift | someFunc() | s:14swift_ide_test15FixtureClass128C8someFuncyyF
8:26 | static-method/acc-set/Swift | setter:someVar | s:14swift_ide_test14FixtureEnum128O7someVarSSvsZ | Ref,Call,Impl,RelRec,RelCall,RelCont | rel: 2
  RelCall,RelCont | instance-method/Swift | someFunc() | s:14swift_ide_test15FixtureClass128C8someFuncyyF
  RelRec | enum/Swift | FixtureEnum128 | s:14swift_ide_test14FixtureEnum128O
5:7 | constructor/Swift | init() | s:14swift_ide_test15FixtureClass128CACycfc | Def,Impl,RelChild | rel: 1
  RelChild | class/Swift | FixtureClass128 | s:14swift_ide_test15FixtureClass128C
```

### PR DESCRIPTION
**Pull request by ileitch**
Properties used as subscript keys (e.g., `dictionary[key] = 42`) were incorrectly indexed as writes, referencing setters instead of getters. Fix by forcing subscript arguments to be treated as reads, except for dynamic member lookup subscripts where the argument represents the member being accessed.

Resolves #56541

### CODE REVIEW

**Comment by ileitch** [comment]
@swift-ci please test

**Comment by ileitch** [comment]
@hamishknight @rintaro Can I please get a review on this?

File: lib/IDE/SourceEntityWalker.cpp [hunk 1]
```diff
@@ -451,8 +451,31 @@ ASTWalker::PreWalkResult<Expr *> SemaAnnotator::walkToExprPre(Expr *E) {
...
+        if (args->isUnary() &&
+            args->getLabel(0) == ctx.Id_dynamicMember) {
+          isDynamicMemberLookup = true;
+        }
+      }
+    }
+
+    if (!isDynamicMemberLookup) {
+      llvm::SaveAndRestore<std::optional<AccessKind>>
+          C(this->OpAccess, AccessKind::Read);
```
Comment (hamishknight) [inline lib/IDE/SourceEntityWalker.cpp]: I don't think it matters much in practice, but I think for consistency I think this should reset back to `nullopt` rather than `Read`


```suggestion
          C(this->OpAccess, std::nullopt);
```

File: lib/IDE/SourceEntityWalker.cpp [hunk 2]
```diff
@@ -451,8 +451,31 @@ ASTWalker::PreWalkResult<Expr *> SemaAnnotator::walkToExprPre(Expr *E) {
...
+    // are always read, regardless of how the subscript is being used (read or write).
+    // Do not propagate a write access kind into the subscript arguments.
+    // However, for dynamic member lookup subscripts, the argument represents
+    // a member being accessed, so it should reflect the access kind.
+    bool isDynamicMemberLookup = false;
+    if (SubscrD) {
+      if (auto *args = SE->getArgs()) {
+        auto &ctx = SubscrD->getASTContext();
+        if (args->isUnary() &&
+            args->getLabel(0) == ctx.Id_dynamicMember) {
```
Comment (hamishknight) [inline lib/IDE/SourceEntityWalker.cpp]: Rather than checking the arg label I think it would be better to check the base type for `hasDynamicMemberLookupAttribute`, then check `isValidKeyPathDynamicMemberLookup` on the decl.

**Review by hamishknight — COMMENTED** [review]
Thanks!

File: lib/IDE/SourceEntityWalker.cpp [hunk 3]
```diff
@@ -451,8 +451,27 @@ ASTWalker::PreWalkResult<Expr *> SemaAnnotator::walkToExprPre(Expr *E) {
...
     }
 
-    if (!SE->getArgs()->walk(*this))
-      return Action::Stop();
+    // For regular subscripts (not dynamic member lookups), the index expressions
+    // are always read, regardless of how the subscript is being used (read or write).
+    // Do not propagate a write access kind into the subscript arguments.
+    // However, for dynamic member lookup subscripts, the argument represents
+    // a member being accessed, so it should reflect the access kind.
+    bool isKeyPathDynamicMemberLookup = false;
```
Comment (hamishknight) [inline lib/IDE/SourceEntityWalker.cpp:459]: Can you also check that the base `hasDynamicMemberLookupAttribute`?

Comment (ileitch) [reply lib/IDE/SourceEntityWalker.cpp:459]: Do you mean the `SE->getBase()->getType()`? Because `hasDynamicMemberLookupAttribute` always return `false` in this context. Alternatively, we could use `SD->getDeclContext()->getSelfNominalTypeDecl()->getDeclaredInterfaceType()`?

Comment (hamishknight) [reply lib/IDE/SourceEntityWalker.cpp:459]: I mean the former yeah, I think the issue you're running into is you have an lvalue type, try using `getWithoutSpecifierType()` first

Comment (ileitch) [reply lib/IDE/SourceEntityWalker.cpp:459]: Yep, that was it!

**Review by hamishknight — APPROVED** [review]
Thanks!

**Comment by hamishknight** [comment]
@swift-ci please test
