### PR TITLE
[AST] Avoid flattening type variable tuple singletons

### LINKED ISSUE #86628: Accessing `first` on opaque result containing pack expansion result crashes the compiler
This crashes the compiler:

```swift
func foo<each T>(_ x: repeat each T) -> some Collection<(repeat each T)> {
  [(repeat each x)]
}
let _ = foo(0, 0).first
```

```
Stack dump:
0.      Program arguments: /Users/hamish/src/swift-dev/build/Release/swift-macosx-arm64/bin/swift-frontend -typecheck /Users/hamish/src/swift-test-arena/main.swift -sdk /Users/hamish/src/MacOSX.sdk -debug-diagnostic-names -diagnostic-style=llvm
1.      Swift version 6.3-dev (LLVM 019fde48d9dc241, Swift 03e6809782526cd)
2.      Compiling with effective version 5.10
3.      While evaluating request TypeCheckPrimaryFileRequest(source_file "/Users/hamish/src/swift-test-arena/main.swift")
4.      While type-checking statement at [/Users/hamish/src/swift-test-arena/main.swift:2977:1 - line:2977:19] RangeText="let _ = foo(0, 0)."
5.      While type-checking declaration 0xc28f8c658 (at /Users/hamish/src/swift-test-arena/main.swift:2977:1)
6.      While evaluating request PatternBindingEntryRequest((unknown decl)@/Users/hamish/src/swift-test-arena/main.swift:2977:1, 0)
7.      While type-checking expression at [/Users/hamish/src/swift-test-arena/main.swift:2977:9 - line:2977:19] RangeText="foo(0, 0)."
8.      While type-checking-target starting at /Users/hamish/src/swift-test-arena/main.swift:2977:19
9.      Abort: function coerceToType at CSApply.cpp:7961
|       Unhandled coercion:
|       (tuple_type num_elements=2
|         (tuple_type_elt
|           (struct_type decl="Swift.(file).Int"))
|         (tuple_type_elt
|           (struct_type decl="Swift.(file).Int")))
|       (pack_type num_elements=2
|         (struct_type decl="Swift.(file).Int")
|         (struct_type decl="Swift.(file).Int"))
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x000000010ac3c5e8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x000000010ac3a398 llvm::sys::RunSignalHandlers() + 164
2  swift-frontend           0x000000010ac3d114 SignalHandler(int, __siginfo*, void*) + 340
3  libsystem_platform.dylib 0x00000001855f0764 _sigtramp + 56
4  libsystem_pthread.dylib  0x00000001855e6888 pthread_kill + 296
5  libsystem_c.dylib        0x00000001854eb850 abort + 124
6  swift-frontend           0x000000010aec9db8 _ABORT(char const*, int, char const*, llvm::function_ref<void (llvm::raw_ostream&)>) + 0
7  swift-frontend           0x000000010aec9e6c _ABORT(char const*, int, char const*, llvm::StringRef) + 0
8  swift-frontend           0x00000001055c77c8 (anonymous namespace)::ExprRewriter::coerceToType(swift::Expr*, swift::Type, swift::constraints::ConstraintLocatorBuilder) + 8852
9  swift-frontend           0x00000001055e767c (anonymous namespace)::ExprRewriter::coerceOptionalToOptional(swift::Expr*, swift::Type, swift::constraints::ConstraintLocatorBuilder) + 536
10 swift-frontend           0x00000001055c6d30 (anonymous namespace)::ExprRewriter::coerceToType(swift::Expr*, swift::Type, swift::constraints::ConstraintLocatorBuilder) + 6140
11 swift-frontend           0x00000001055c54dc swift::constraints::Solution::coerceToType(swift::Expr*, swift::Type, swift::constraints::ConstraintLocator*) + 236
12 swift-frontend           0x00000001055e4d70 applySolutionToInitialization(swift::constraints::SyntacticElementTarget, swift::Expr*, swift::constraints::SyntacticElementTargetRewriter&) + 556
13 swift-frontend           0x00000001055c4988 (anonymous namespace)::ExprWalker::rewriteTarget(swift::constraints::SyntacticElementTarget) + 2936
14 swift-frontend           0x00000001055c3c30 swift::constraints::ConstraintSystem::applySolution(swift::constraints::Solution&, swift::constraints::SyntacticElementTarget) + 1192
15 swift-frontend           0x0000000105842704 swift::TypeChecker::typeCheckTarget(swift::constraints::SyntacticElementTarget&, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>, swift::DiagnosticTransaction*) + 412
16 swift-frontend           0x000000010584250c swift::TypeChecker::typeCheckExpression(swift::constraints::SyntacticElementTarget&, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>, swift::DiagnosticTransaction*) + 196
17 swift-frontend           0x0000000105843a0c swift::TypeChecker::typeCheckBinding(swift::Pattern*&, swift::Expr*&, swift::DeclContext*, swift::Type, swift::PatternBindingDecl*, unsigned int, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 112
18 swift-frontend           0x0000000105843bf4 swift::TypeChecker::typeCheckPatternBinding(swift::PatternBindingDecl*, unsigned int, swift::Type, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 268
19 swift-frontend           0x00000001059318b0 swift::PatternBindingEntryRequest::evaluate(swift::Evaluator&, swift::PatternBindingDecl*, unsigned int) const + 1492
20 swift-frontend           0x0000000105d2fb68 swift::PatternBindingEntryRequest::OutputType swift::Evaluator::getResultUncached<swift::PatternBindingEntryRequest, swift::PatternBindingEntryRequest::OutputType swift::evaluateOrDefault<swift::PatternBindingEntryRequest>(swift::Evaluator&, swift::PatternBindingEntryRequest, swift::PatternBindingEntryRequest::OutputType)::'lambda'()>(swift::PatternBindingEntryRequest const&, swift::PatternBindingEntryRequest::OutputType swift::evaluateOrDefault<swift::PatternBindingEntryRequest>(swift::Evaluator&, swift::PatternBindingEntryRequest, swift::PatternBindingEntryRequest::OutputType)::'lambda'())::'lambda'()::operator()() const + 76
21 swift-frontend           0x0000000105d2f558 swift::PatternBindingEntryRequest::OutputType swift::Evaluator::getResultUncached<swift::PatternBindingEntryRequest, swift::PatternBindingEntryRequest::OutputType swift::evaluateOrDefault<swift::PatternBindingEntryRequest>(swift::Evaluator&, swift::PatternBindingEntryRequest, swift::PatternBindingEntryRequest::OutputType)::'lambda'()>(swift::PatternBindingEntryRequest const&, swift::PatternBindingEntryRequest::OutputType swift::evaluateOrDefault<swift::PatternBindingEntryRequest>(swift::Evaluator&, swift::PatternBindingEntryRequest, swift::PatternBindingEntryRequest::OutputType)::'lambda'()) + 204
22 swift-frontend           0x0000000105cf9f44 swift::PatternBindingDecl::getCheckedPatternBindingEntry(unsigned int) const + 124
23 swift-frontend           0x000000010588fdb4 (anonymous namespace)::DeclChecker::visit(swift::Decl*) + 1844
24 swift-frontend           0x000000010588f664 swift::TypeChecker::typeCheckDecl(swift::Decl*) + 128
25 swift-frontend           0x00000001059287dc swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) + 288
26 swift-frontend           0x0000000105926f1c bool (anonymous namespace)::StmtChecker::typeCheckStmt<swift::BraceStmt>(swift::BraceStmt*&) + 136
27 swift-frontend           0x0000000105926fa4 swift::TypeChecker::typeCheckTopLevelCodeDecl(swift::TopLevelCodeDecl*) + 52
28 swift-frontend           0x0000000105978878 swift::TypeCheckPrimaryFileRequest::evaluate(swift::Evaluator&, swift::SourceFile*) const + 184
29 swift-frontend           0x000000010597c3a4 swift::TypeCheckPrimaryFileRequest::OutputType swift::Evaluator::getResultUncached<swift::TypeCheckPrimaryFileRequest, swift::TypeCheckPrimaryFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckPrimaryFileRequest>(swift::Evaluator&, swift::TypeCheckPrimaryFileRequest, swift::TypeCheckPrimaryFileRequest::OutputType)::'lambda'()>(swift::TypeCheckPrimaryFileRequest const&, swift::TypeCheckPrimaryFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckPrimaryFileRequest>(swift::Evaluator&, swift::TypeCheckPrimaryFileRequest, swift::TypeCheckPrimaryFileRequest::OutputType)::'lambda'())::'lambda'()::operator()() const + 72
30 swift-frontend           0x000000010597bcb8 swift::TypeCheckPrimaryFileRequest::OutputType swift::Evaluator::getResultUncached<swift::TypeCheckPrimaryFileRequest, swift::TypeCheckPrimaryFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckPrimaryFileRequest>(swift::Evaluator&, swift::TypeCheckPrimaryFileRequest, swift::TypeCheckPrimaryFileRequest::OutputType)::'lambda'()>(swift::TypeCheckPrimaryFileRequest const&, swift::TypeCheckPrimaryFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckPrimaryFileRequest>(swift::Evaluator&, swift::TypeCheckPrimaryFileRequest, swift::TypeCheckPrimaryFileRequest::OutputType)::'lambda'()) + 204
31 swift-frontend           0x0000000105978798 swift::performTypeChecking(swift::SourceFile&) + 76
32 swift-frontend           0x0000000104740e68 bool llvm::function_ref<bool (swift::SourceFile&)>::callback_fn<swift::CompilerInstance::performSema()::$_0>(long, swift::SourceFile&) + 16
33 swift-frontend           0x0000000104737f74 swift::CompilerInstance::forEachFileToTypeCheck(llvm::function_ref<bool (swift::SourceFile&)>) + 156
34 swift-frontend           0x0000000104737eb8 swift::CompilerInstance::performSema() + 144
35 swift-frontend           0x000000010449c53c withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 60
36 swift-frontend           0x000000010448f910 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*, llvm::ArrayRef<char const*>) + 560
37 swift-frontend           0x000000010448d324 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2180
38 swift-frontend           0x0000000104200940 swift::mainEntry(int, char const**) + 3164
39 dyld                     0x000000018521dd54 start + 7184
```

### LINKED ISSUE #86629: Cannot use opaque result type containing pack expansion in for-loop
The following fails to compile, but should:

```swift
func foo<each T>(_ x: repeat each T) -> some Collection<(repeat each T)> {
  [(repeat each x)]
}
for _ in foo(0, 0) {} // error: value pack expansion can only appear inside a function argument list, tuple element, or as the expression of a for-in loop
```

If you do `foo(0)` instead of `foo(0, 0)` it works.

### PR DESCRIPTION
**Pull request by hamishknight**
If we have `(_: $T0)`, avoid flattening to `$T0` since for a pack expansion type variable that would result in a bare pack type instead of a tuple. Instead, leave the flattening for TypeSimplifier.

Resolves #86629
Resolves #86628
rdar://168407842&168407626

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

File: include/swift/AST/TypeTransform.h [hunk 1]
```diff
@@ -761,16 +761,17 @@ case TypeKind::Id:
...
-          return elements[0].getType();
-        }
+      // Handle vanishing tuples -- If the transform would yield a singleton
+      // tuple, and we didn't start with one, flatten to produce the
+      // element type. Avoid flattening if we have a type variable singeton,
+      // since it could be subtituted with a pack, TypeSimplifier handles the
+      // flattening in this case.
+      if (elements.size() == 1 &&
+          !elements[0].getType()->is<PackExpansionType>() &&
+          !elements[0].getType()->is<TypeVariableType>() &&
```
Comment (xedin) [inline include/swift/AST/TypeTransform.h:771]: Probably if it’s a type variable and can bind to a pack?

Comment (hamishknight) [reply include/swift/AST/TypeTransform.h:771]: We can't check that here since this in libAST, my preference is to leave that handling up to `matchTypes`/`TypeSimplifier`

**Comment by hamishknight** [comment]
@swift-ci please smoke test

File: include/swift/AST/TypeTransform.h (hunk 1 above)
Comment (xedin) [reply include/swift/AST/TypeTransform.h:771]: Ah right, okay, let's keep it that way for now.

**Review by xedin — APPROVED** [review]
