### PR TITLE
Sema: Allow collection downcast in cast pattern and remove the diagnostic that it is not implemented

### LINKED ISSUE #56139: [SR-13742] Allow "case let value as [Int]" and remove the diagnostic that it is not implemented
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13742      |
   |Radar             | rdar://problem/70336498         |
   |Original Reporter | @ktoso      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, StarterBug        |
   |Assignee          | @ktoso      |
   |Priority          | Medium      |

   

   md5: d4a4c363d3b5f5288974990ee8ab9dfc

  </details>

**Issue Description:**

The following code:

``` swift
extension Array {
    func lol() -> String {
        switch self {
            case let value as [Int]: return "int"
            default: return "no"
        }
    }
}
```

yields:

``` java
// Swift version 5.3-dev (LLVM 2ea629d94ab01c3, Swift d3108db2429b29b)
// Target: x86_64-apple-darwin20.1.0
$SWIFT_EXEC Hello.swift
Hello.swift:5:28: error: collection downcast in cast pattern is not implemented; use an explicit downcast to '[Int]' instead
            case let value as [Int]: return "int"
                           ^
```

@jckarter suggests that implementation wise this isn't true anymore, just that the diagnostic is outdated.

### PR DESCRIPTION
**Pull request by simanerush**
Resolves #56139.

### CODE REVIEW

File: test/Parse/matching_patterns.swift [hunk 1]
```diff
@@ -289,16 +289,16 @@ case (let (_, _, _)) + 1:
...
-// FIXME: We don't currently allow subpatterns for "isa" patterns that
-// require interesting conditional downcasts.
+// "isa" patterns.
 class Base { }
 class Derived : Base { }
 
 
 switch [Derived(), Derived(), Base()] {
-case let ds as [Derived]: // expected-error{{collection downcast in cast pattern is not implemented; use an explicit downcast to '[Derived]' instead}}
+case let ds as [Derived]:
```
Comment (xedin) [inline test/Parse/matching_patterns.swift:298]: Could you please add a test-case that uses `switch` + `case let ... as ...` inside of a closure and SILGen test-case for that as well?

Comment (simanerush) [reply test/Parse/matching_patterns.swift:298]: Yes, I will address this

Comment (simanerush) [reply test/Parse/matching_patterns.swift]: @xedin I just pushed new changes. It has more tests!

File: test/Parse/matching_patterns.swift [hunk 2]
```diff
@@ -289,22 +289,44 @@ case (let (_, _, _)) + 1:
...
 
-default:
-  ()
-}
+  if case let _ as [Derived] = arr {}
+
+  guard case let _ as [Derived] = arr else {}
+
+  while case let _ as [Derived] = arr {}
+
```
Comment (AnthonyLatsis) [inline test/Parse/matching_patterns.swift:308]: Please add analogous tests for the `is` pattern, and one more test featuring a for-in loop for each pattern. Example: `for case _ as [Derived] in [arr]` (note that we are casting the *element* here, and it must be a collection downcast).

File: test/SILGen/statements.swift [hunk 3]
```diff
@@ -657,6 +657,113 @@ func test_as_pattern(_ y : BaseClass) -> DerivedClass {
...
+  guard case is [DerivedClass] = arr else {}
+  // CHECK: [[ARR_CAST_FN:%[0-9]+]] = function_ref @$ss21_arrayConditionalCastySayq_GSgSayxGr0_lF : $@convention(thin) <τ_0_0, τ_0_1> (@guaranteed Array<τ_0_0>) -> @owned Optional<Array<τ_0_1>>
+  // CHECK-NEXT: [[RESULT:%[0-9]+]] = apply [[ARR_CAST_FN]]<BaseClass, DerivedClass>
+  // CHECK-NEXT: switch_enum [[RESULT]]
+  while case is [DerivedClass] = arr {}
+}
+// CHECK: } // end sil function '$s10statements35test_is_pattern_collection_downcastyySayAA9BaseClassCGF'
+
+// CHECK-LABEL: sil hidden [ossa] @$s10statements35test_is_pattern_dictionary_downcastyySDySSAA9BaseClassCGF : $@convention(thin) (@guaranteed Dictionary<String, BaseClass>) -> () {
+func test_is_pattern_dictionary_downcast(_ dict: Dictionary<String, BaseClass>) {
```
Comment (AnthonyLatsis) [inline test/SILGen/statements.swift:734]: All these tests are really similar so I suggest we group them by collection kind 3 functions named `test_isa_pattern_*_downcast`.

Comment (AnthonyLatsis) [inline test/SILGen/statements.swift:734]: All these tests are really similar, so I suggest we group them by collection kind into 3 functions named `test_isa_pattern_*_downcast`.

File: test/Parse/matching_patterns.swift [hunk 4]
```diff
@@ -289,22 +289,44 @@ case (let (_, _, _)) + 1:
...
+  switch arr {
+  case let ds as [Derived]:
+    // expected-warning@-1 {{immutable value 'ds' was never used; consider replacing with '_' or removing it}}
+    ()
+  case is [Derived]:
+    ()
```
Comment (AnthonyLatsis) [inline test/Parse/matching_patterns.swift:314]: Optional: These case elements could be compact one-liners. Also, how about a conventional `break` instead of a paren expression?

File: test/Parse/matching_patterns.swift [hunk 5]
```diff
@@ -289,22 +289,44 @@ case (let (_, _, _)) + 1:
...
-}
+  if case let _ as [Derived] = arr {}
+
+  guard case let _ as [Derived] = arr else {}
+
+  while case let _ as [Derived] = arr {}
+
+  switch arr {
+  case let ds as [Derived]:
+    // expected-warning@-1 {{immutable value 'ds' was never used; consider replacing with '_' or removing it}}
```
Comment (AnthonyLatsis) [inline test/Parse/matching_patterns.swift:311]: ds → _ to rid us of this extraneous warning.

File: test/Parse/matching_patterns.swift [hunk 6]
```diff
@@ -289,22 +289,44 @@ case (let (_, _, _)) + 1:
...
+    ()
 
+  default:
+    ()
+  }
+
+  let _ = { (arr: [Base]) -> Void in
+    switch arr {
+    case let ds as [Derived]:
+      // expected-warning@-1 {{immutable value 'ds' was never used; consider replacing with '_' or removing it}}
```
Comment (AnthonyLatsis) [inline test/Parse/matching_patterns.swift:323]: ds → _

**Review by AnthonyLatsis — COMMENTED** [review]
Nice!

File: test/Parse/matching_patterns.swift (hunk 5 above)
Comment (simanerush) [reply test/Parse/matching_patterns.swift:311]: But in this case there's still going to be a warning: unexpected warning produced: 'let' pattern has no effect; sub-pattern didn't bind any variables

File: test/Parse/matching_patterns.swift (hunk 6 above)
Comment (simanerush) [reply test/Parse/matching_patterns.swift:323]: But in this case, there's still going to be a warning: unexpected warning produced: 'let' pattern has no effect; sub-pattern didn't bind any variables

File: test/Parse/matching_patterns.swift (hunk 5 above)
Comment (AnthonyLatsis) [reply test/Parse/matching_patterns.swift:311]: Huh. Your choice then! I wonder if we had any reasoning behind warning on `case let _`, but not `let _ =`; I do not see it playing well as long as `let _` is what the current warning suggests to silence itself.

File: test/SILGen/statements.swift [hunk 7]
```diff
@@ -657,6 +657,113 @@ func test_as_pattern(_ y : BaseClass) -> DerivedClass {
   // CHECK-NEXT: return [[RESULT]] : $DerivedClass
   return result
 }
+
+// CHECK-LABEL: sil hidden [ossa] @$s10statements30test_as_pattern_array_downcastyySayAA9BaseClassCGF : $@convention(thin) (@guaranteed Array<BaseClass>) -> () {
+func test_as_pattern_array_downcast(_ arr: [BaseClass]) {
```
Comment (AnthonyLatsis) [inline test/SILGen/statements.swift:662]: We forgot to add a link to the issue here.

File: test/Parse/matching_patterns.swift [hunk 8]
```diff
@@ -289,22 +289,59 @@ case (let (_, _, _)) + 1:
...
+  }
 
+  for case _ as [Derived] in [arr] {
+    ()
+  }
+
+  for case is [Derived] in [arr] {
+    ()
+  }
+}
```
Comment (AnthonyLatsis) [inline test/Parse/matching_patterns.swift:344]: Thanks! Could you group these with the `if`/`guard`/`while` tests? The `()` is redundant, by the way.

File: test/SILGen/switch.swift [hunk 9]
```diff
@@ -635,6 +635,133 @@ func test_isa_class_2(x: B) -> AnyObject {
 }
 // CHECK: } // end sil function '$s6switch16test_isa_class_21xyXlAA1BC_tF'
 
+// https://github.com/apple/swift/issues/56139
+
+// CHECK-LABEL: sil hidden [ossa] @$s6switch14test_isa_array2psySayAA1P_pG_tF : $@convention(thin) (@guaranteed Array<P>) -> () {
+func test_isa_array(ps: Array<P>) {
```
[the remark this answers is not in the document]
Comment (AnthonyLatsis) [reply test/SILGen/switch.swift]: It appears you only renamed this one; what about the other functions?

File: test/SILGen/statements.swift (hunk 3 above)
Comment (AnthonyLatsis) [reply test/SILGen/statements.swift]: Seems like you resolved the conversation, but forgot to address the suggestion?

Comment (simanerush) [reply test/SILGen/statements.swift]: fixed that!

File: test/SILGen/switch.swift (hunk 9 above)
[the remark this answers is not in the document]
Comment (simanerush) [reply test/SILGen/switch.swift]: Fixed that!

File: test/SILGen/statements.swift (hunk 3 above)
Comment (simanerush) [reply test/SILGen/statements.swift]: I did change the name of these functions. Did you mean something else?

Comment (AnthonyLatsis) [reply test/SILGen/statements.swift]: Ah, right, what I meant is to group these tests by collection kind into 3 functions rather than 6. Each function then tests both `is` and `as` patterns for a given collection kind.

**Comment by AnthonyLatsis** [comment]
Requesting Slava to review SIL tests.

File: test/SILGen/switch.swift [hunk 10]
```diff
@@ -635,6 +635,133 @@ func test_isa_class_2(x: B) -> AnyObject {
...
+    // CHECK: br [[CONT]]
+  }
+  // CHECK: [[CONT]]:
+  // CHECK: function_ref @$s6switch1dyyF
+  d()
+}
+// CHECK-LABEL: } // end sil function '$s6switch30test_isa_pattern_dict_downcast2psySDySSAA1P_pG_tF'
+
+// CHECK-LABEL: sil hidden [ossa] @$s6switch30test_isa_pattern_set_downcastt2psyShyxG_tSHRzlF : $@convention(thin) <T where T : Hashable> (@guaranteed Set<T>) -> () {
+func test_isa_pattern_set_downcastt<T: Hashable>(ps: Set<T>) {
```
Comment (AnthonyLatsis) [inline test/SILGen/switch.swift:734]: Not to commit directly:
```suggestion
// CHECK-LABEL: sil hidden [ossa] @$s6switch29test_isa_pattern_set_downcast2psyShyxG_tSHRzlF : $@convention(thin) <T where T : Hashable> (@guaranteed Set<T>) -> () {
func test_isa_pattern_set_downcast<T: Hashable>(ps: Set<T>) {
```

Comment (simanerush) [reply test/SILGen/switch.swift:734]: fixed that, thanks!

**Review by xedin — APPROVED** [review]

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
@simanerush That is a false positive, a single-element array literal cannot possibly be heterogeneous. Looks like we need another issue report. The warning will have to be verified in the meantime.

**Comment by simanerush** [comment]
@slavapestov could you take a look?

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test macOS

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
@swift-ci please clean smoke test macOS

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test macOS

**Review by AnthonyLatsis — APPROVED** [review]
Great! There are no functional changes to SIL generation anyway, so let’s land this. We can open a new PR shall Slava have any comments on test matter later on.

**Comment by AnthonyLatsis** [comment]
@xedin Do you reckon this needs a changelog entry?
