### PR TITLE
[CSBindings] Limit `BindingSet::isViable` binding skipping to stdlib …

### LINKED ISSUE #77003: Regression: `ambiguous use of 'Task.init(priority:operation:)'
### Description

A recent regression. 

At a glace, based on `-debug-constraints` output, it looks like the very first difference is - `receiveCompletion: { _ in }` gets disconnected from the rest of the constraint system early because one of the dependent member types gets eagerly simplified down to a concrete type:

```
$T10 := (@escaping ((Subscribers.Completion<$T23.Failure>) -> Void), @escaping (($T23.Output) -> Void)) -> AnyCancellable
($T11, $T14) -> $T17 applicable fn $T10
$T23 := Publishers.CompactMap<Publishers.FlatMap<$T20, PassthroughSubject<Set<Value>, any Error>>, $T22>
$T11 arg conv ((Subscribers.Completion<any Error>) -> Void) 💥 
```

The type of `$T11` used to be `((Subscribers.Completion<Publishers.CompactMap<Publishers.FlatMap<$T20, PassthroughSubject<Set<Value>, any Error>>, $T22>.Failure>) -> Void)` which kept the closure connected to the rest of the constraint system.

This is the initial difference which causes solver to produce more solutions than before because order of binding selection changes.

### Reproduction

```swift
import Combine

struct Value : Hashable {
}

protocol Item: Actor {
}

class Test {
    var subject: PassthroughSubject<Set<Value>, Error>

    init(subject: PassthroughSubject<Set<Value>, Error>) {
        self.subject = subject
    }

    func test() {
        subject
          .flatMap { (values: Set<Value>) -> AnyPublisher<[any Item]?, Error> in
              fatalError()
          }
          .compactMap { $0 }
          .sink(
            receiveCompletion: { _ in },
            receiveValue: { _ in
              Task { [weak self] in
              }
           })

    }
}
```

### Expected behavior

The expression should produce a single valid solution that uses non-throwing async overload of `Task.init`.

### Environment

Swift main branch @ 4afc2d4d6d358dca2c87310b7d9c7e5f9160ff13

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by xedin**
…collection types

This is follow-up to https://github.com/swiftlang/swift/pull/76487

It's reasonable to coalesce bindings of different kind if they don't allow implicit conversions like stdlib collection types do.

Resolves: https://github.com/swiftlang/swift/issues/77003

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

File: lib/Sema/CSBindings.cpp [hunk 1]
```diff
@@ -1215,8 +1215,12 @@ bool BindingSet::isViable(PotentialBinding &binding, bool isTransitive) {
     // as a binding because `$T0` could be inferred to
     // `(key: String, value: Int)` and binding `$T1` to `Array<(String, Int)>`
     // eagerly would be incorrect.
-    if (existing->Kind != binding.Kind)
-      continue;
+    if (existing->Kind != binding.Kind) {
+      // Array, Set and Dictionary allow conversions, everything else
+      // requires their generic arguments to match exactly.
+      if (existingType->isKnownStdlibCollectionType())
```
Comment (slavapestov) [inline lib/Sema/CSBindings.cpp:1221]: What about Optional?

Comment (slavapestov) [reply lib/Sema/CSBindings.cpp:1221]: Maybe this check should also call `hasConversions()`?

Comment (xedin) [reply lib/Sema/CSBindings.cpp:1221]: We allow injections to optional but not conversions of its generic arguments, this only covers situations like `Int? conv $T` and `$T conv $U?`.

Comment (xedin) [reply lib/Sema/CSBindings.cpp:1221]: This spot a lot narrower so I don't think we can use `hasConversions` here.

Comment (slavapestov) [reply lib/Sema/CSBindings.cpp:1221]: > We allow injections into optional but not conversions of its generic arguments,

The optional-to-optional conversion is a lot like `Array` upcast isn't it?

Comment (xedin) [reply lib/Sema/CSBindings.cpp:1221]: Somewhat but it wasn’t allowed previously but the logic here so we are not changing the behavior.

Comment (xedin) [reply lib/Sema/CSBindings.cpp:1221]: Expressions like:

```
func test<T>(_: T, _: () -> T?) {}

class A {
}

class B : A {}

test(A()) {
    Optional(B())
}
```

Still work fine because optional conversion differ from collection upcast in that solver doesn't introduce a separate type variable when they are bound so even if we infer result type to be `B?` it would still much fine against `A?` from context, unlike what happens for collections where we'd infer the element and match it directly.

Comment (xedin) [reply lib/Sema/CSBindings.cpp:1221]: Also allowing both `Int?` and `$T?` bindings results in the same solution multiple times, something that CSRanking doesn't properly handle today because we don't expect that to happen without score or binding differences, that's most likely the logic didn't have change check, I'd rather we revisit this whole method in the future than try to fix it now...

**Comment by xedin** [comment]
@swift-ci please test source compatibility
