### PR TITLE
[ConstraintSystem] Adjust the way pack parameters are opened

### LINKED ISSUE #66095: Compiler crash when forwarding variadic type parameter pack to initializer
**Description**
The following code causes a compiler crash related to same shape constraint simplification. Crash logs are included near the bottom of the issue.

If the `A` initializer is instead just `init() {}` (and the culprit line is updated accordingly), no crash occurs. It also doesn't crash the compiler if instead of forwarding the pack to `A.init` it's forwarded to another function `bar` that does nothing.

As far as I can see, 'simplifying' the same shape requirement of the type of `repeat each v` and the type `repeat each V` (explicitly given as the type parameter pack of the `A` being initialized), should be trivial, so the `simplifySameShapeRequirement` may be able to short circuit pretty early if it doesn't already? (I'm not a compiler wizz so I'm probably wrong, I haven't looked at the implementation yet)

```swift
// repro.swift

@available(macOS 99.99.0, *)
struct A<each V> {
    init(_ vs: repeat each V) {}
}

@available(macOS 99.99.0, *)
func foo<each V>(_ v: repeat each V) -> A<repeat each V> {
    return A<repeat each V>(repeat each v) // CULPRIT
}
```

**Steps to reproduce**
1. `swiftc repro.swift`
2. Compiler crashes

**Expected behavior**
I'm pretty sure the code snippet is valid use of variadic generics, so it should compile just fine, but even if it is malformed due to a gap in my understanding, it still shouldn't crash the compiler.

**Environment**
- Swift compiler version info `Apple Swift version 5.9-dev (LLVM 3653146fb31d979, Swift 889f813e44d8d04) (Target: arm64-apple-macosx13.0)`
- Xcode version info `Xcode 14.3 Build version 14E222b`
- Deployment target: `macOS 13`

**Crash log**

```
error: compile command failed due to signal 6 (use -v to see invocation)
Assertion failed: (isa<To>(Val) && "cast<Ty>() argument of incompatible type!"), function cast, file Casting.h, line 578.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.      Program arguments: /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2023-05-22-a.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file main.swift -target arm64-apple-macosx13.0 -Xllvm -a
arch64-use-tbi -enable-objc-interop -color-diagnostics -new-driver-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2023-05-22-a.xctoolchain/usr/bin/swift-driver -empty-abi-descriptor -plugin-path
/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2023-05-22-a.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2023-05-22-a.xctoolchain/usr/lo
cal/lib/swift/host/plugins -resource-dir /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2023-05-22-a.xctoolchain/usr/lib/swift -module-name main -o /var/folders/rg/rbnmrj9s25906hk5f1v8zv8r0000gn/T/Tem
poraryDirectory.HVy9f6/main-1.o
1.      Apple Swift version 5.9-dev (LLVM 3653146fb31d979, Swift 889f813e44d8d04)
2.      Compiling with the current language version
3.      While evaluating request TypeCheckSourceFileRequest(source_file "main.swift")
4.      While evaluating request TypeCheckFunctionBodyRequest(main.(file).foo@main.swift:7:6)
5.      While type-checking statement at [main.swift:7:58 - line:9:1] RangeText="{
    return A<repeat each V>(repeat each v)
"
6.      While type-checking statement at [main.swift:8:5 - line:8:42] RangeText="return A<repeat each V>(repeat each v"
7.      While type-checking expression at [main.swift:8:12 - line:8:42] RangeText="A<repeat each V>(repeat each v"
8.      While type-checking-target starting at main.swift:8:13
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x00000001073e4a40 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x00000001073e3de4 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x00000001073e5080 SignalHandler(int) + 304
3  libsystem_platform.dylib 0x00000001a99bc2a4 _sigtramp + 56
4  libsystem_pthread.dylib  0x00000001a998dcec pthread_kill + 288
5  libsystem_c.dylib        0x00000001a98c72c8 abort + 180
6  libsystem_c.dylib        0x00000001a98c6620 err + 0
7  swift-frontend           0x0000000107764ad8 swift::constraints::ConstraintSystem::simplifySameShapeConstraint(swift::Type, swift::Type, swift::OptionSet<swift::constraints::ConstraintSystem::TypeMatchFlags,
unsigned int>, swift::constraints::ConstraintLocatorBuilder) (.cold.30) + 0
8  swift-frontend           0x000000010359ac84 swift::constraints::ConstraintSystem::simplifySameShapeConstraint(swift::Type, swift::Type, swift::OptionSet<swift::constraints::ConstraintSystem::TypeMatchFlags,
unsigned int>, swift::constraints::ConstraintLocatorBuilder) + 2152
9  swift-frontend           0x000000010359e600 swift::constraints::ConstraintSystem::addConstraintImpl(swift::constraints::ConstraintKind, swift::Type, swift::Type, swift::constraints::ConstraintLocatorBuilder,
 bool) + 1068
10 swift-frontend           0x0000000103577f48 swift::constraints::ConstraintSystem::addConstraint(swift::constraints::ConstraintKind, swift::Type, swift::Type, swift::constraints::ConstraintLocatorBuilder, boo
l) + 76
11 swift-frontend           0x0000000103577be8 swift::constraints::ConstraintSystem::matchPackExpansionTypes(swift::PackExpansionType*, swift::PackExpansionType*, swift::constraints::ConstraintKind, swift::Opti
onSet<swift::constraints::ConstraintSystem::TypeMatchFlags, unsigned int>, swift::constraints::ConstraintLocatorBuilder) + 172
12 swift-frontend           0x0000000103574138 swift::constraints::ConstraintSystem::matchTypes(swift::Type, swift::Type, swift::constraints::ConstraintKind, swift::OptionSet<swift::constraints::ConstraintSyste
m::TypeMatchFlags, unsigned int>, swift::constraints::ConstraintLocatorBuilder) + 4588
13 swift-frontend           0x000000010359f2b4 swift::constraints::ConstraintSystem::simplifyConstraint(swift::constraints::Constraint const&) + 304
14 swift-frontend           0x00000001035af67c swift::constraints::ConstraintSystem::simplify() + 412
15 swift-frontend           0x00000001035440a4 swift::constraints::TypeVariableBinding::attempt(swift::constraints::ConstraintSystem&) const + 1032
16 swift-frontend           0x00000001035c77dc swift::constraints::BindingStep<swift::constraints::TypeVarBindingProducer>::take(bool) + 548
17 swift-frontend           0x00000001035b17bc swift::constraints::ConstraintSystem::solveImpl(llvm::SmallVectorImpl<swift::constraints::Solution>&) + 464
18 swift-frontend           0x0000000103648e34 swift::constraints::ConstraintSystem::salvage() + 252
19 swift-frontend           0x00000001035b2f9c swift::constraints::ConstraintSystem::solve(swift::constraints::SyntacticElementTarget&, swift::FreeTypeVariableBinding) + 704
20 swift-frontend           0x000000010371c5dc swift::TypeChecker::typeCheckTarget(swift::constraints::SyntacticElementTarget&, swift::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 320
21 swift-frontend           0x000000010371c444 swift::TypeChecker::typeCheckExpression(swift::constraints::SyntacticElementTarget&, swift::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 184
22 swift-frontend           0x000000010371c304 swift::TypeChecker::typeCheckExpression(swift::Expr*&, swift::DeclContext*, swift::constraints::ContextualTypeInfo, swift::OptionSet<swift::TypeCheckExprFlags, uns
igned int>) + 84
23 swift-frontend           0x00000001037f8aa0 swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) + 3472
24 swift-frontend           0x00000001037f7cdc bool (anonymous namespace)::StmtChecker::typeCheckStmt<swift::Stmt>(swift::Stmt*&) + 136
25 swift-frontend           0x00000001037f4fcc (anonymous namespace)::StmtChecker::typeCheckASTNode(swift::ASTNode&) + 156
26 swift-frontend           0x00000001037f7e58 swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) + 328
27 swift-frontend           0x00000001037f6514 bool (anonymous namespace)::StmtChecker::typeCheckStmt<swift::BraceStmt>(swift::BraceStmt*&) + 136
28 swift-frontend           0x00000001037f5ba0 swift::TypeCheckFunctionBodyRequest::evaluate(swift::Evaluator&, swift::AbstractFunctionDecl*) const + 1028
29 swift-frontend           0x0000000103b90b04 llvm::Expected<swift::TypeCheckFunctionBodyRequest::OutputType> swift::Evaluator::getResultUncached<swift::TypeCheckFunctionBodyRequest>(swift::TypeCheckFunctionBo
dyRequest const&) + 392
30 swift-frontend           0x0000000103b908a0 llvm::Expected<swift::TypeCheckFunctionBodyRequest::OutputType> swift::Evaluator::getResultCached<swift::TypeCheckFunctionBodyRequest, (void*)0>(swift::TypeCheckFu
nctionBodyRequest const&) + 120
31 swift-frontend           0x0000000103adf3c0 swift::TypeCheckFunctionBodyRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckFunctionBodyRequest>(swift::Evaluator&, swift::TypeCheckFunctionBodyReques
t, swift::TypeCheckFunctionBodyRequest::OutputType) + 52
32 swift-frontend           0x000000010382dc2c swift::TypeCheckSourceFileRequest::evaluate(swift::Evaluator&, swift::SourceFile*) const + 312
33 swift-frontend           0x000000010382ff0c llvm::Expected<swift::TypeCheckSourceFileRequest::OutputType> swift::Evaluator::getResultUncached<swift::TypeCheckSourceFileRequest>(swift::TypeCheckSourceFileRequ
est const&) + 388
34 swift-frontend           0x000000010382fc9c llvm::Expected<swift::TypeCheckSourceFileRequest::OutputType> swift::Evaluator::getResultCached<swift::TypeCheckSourceFileRequest, (void*)0>(swift::TypeCheckSource
FileRequest const&) + 84
35 swift-frontend           0x000000010382da0c swift::TypeCheckSourceFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckSourceFileRequest>(swift::Evaluator&, swift::TypeCheckSourceFileRequest, swi
ft::TypeCheckSourceFileRequest::OutputType) + 44
36 swift-frontend           0x00000001028dd114 bool llvm::function_ref<bool (swift::SourceFile&)>::callback_fn<swift::CompilerInstance::performSema()::$_9>(long, swift::SourceFile&) + 16
37 swift-frontend           0x00000001028d7588 swift::CompilerInstance::forEachFileToTypeCheck(llvm::function_ref<bool (swift::SourceFile&)>) + 76
38 swift-frontend           0x00000001028d751c swift::CompilerInstance::performSema() + 76
39 swift-frontend           0x000000010274c6bc withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 60
40 swift-frontend           0x0000000102740058 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 620
41 swift-frontend           0x000000010273f064 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2428
42 swift-frontend           0x000000010259232c swift::mainEntry(int, char const**) + 2144
43 dyld                     0x00000001a9663e50 start + 2544
error: fatalError
```

**Reducing repro further with creduce for fun**
I tried using `creduce` to reduce the repro case even further and ended up with this abomination, but it technically does seem to cause the same crash 😅

```swift
struct a < each b {
  init(repeat each b) {             a(
```

### PR DESCRIPTION
**Pull request by xedin**
Although variadic type is declared without `repeat` each of its generic arguments is
supposed to be a PackType which is modeled in the interface type as `Pack{repeat ...}`.
When reference to such a type is opened by the constraint solver we need to drop the
Pack{repeat ...} structure because the type variable would represent a pack type so 
`S<each T>` is opened as `S<$T0>` instead of `S<Pack{repeat $T0}>`.

Resolves: https://github.com/apple/swift/issues/66095

### CODE REVIEW

File: test/Constraints/variadic_generic_types.swift [hunk 1]
```diff
@@ -29,3 +29,18 @@ struct MissingMemberError<each T> {
...
+do {
+  struct Test<each S> {
+    init(_ s: repeat each S) {}
+  }
+
+  func test1<each T>(_ v: repeat each T) -> Test<repeat each T> {
+    return Test(repeat each v) // Ok
+  }
+
+  func test2<each T>(_ v: repeat each T) -> Test<repeat each T> {
```
Comment (hborla) [inline test/Constraints/variadic_generic_types.swift:43]: Could you please also add a few tests that append concrete pack elements onto either side of the forwarded pack, e.g. `Test<repeat each T, Int, String>` and `Test<Int, String, repeat each T>`?

Comment (xedin) [reply test/Constraints/variadic_generic_types.swift:43]: Sure!

Comment (xedin) [reply test/Constraints/variadic_generic_types.swift:43]: ✅

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by stackotter** [comment]
Thanks for the fix 🙏
