### PR TITLE
[Sema] Warn about dictionary literal of dictionary type about duplicated keys

### LINKED ISSUE #43258: [SR-641] [QOI] Missing diagnostic for static dictionary literal w/ duplicate keys
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-641      |
   |Radar             | rdar://problem/29658494         |
   |Original Reporter | @ddunbar      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: f77ddc4df78320549e3e087d1765eb3e

  </details>

**Issue Description:**

This code leads to a runtime, not compile time, error:

``` java
$ cat z.swift
let a = ["A": "A", "A": "B"]
$ swiftc z.swift 
$ 
```

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
This simply warns about dictionary literal with duplicated keys only when they are inferred as `Dictionary` where we know duplicated keys are not stored, but we cannot diagnose the same for other custom `ExpressibleByDictionaryLiteral` type because rules are unknown.

Resolves https://github.com/apple/swift/issues/43258.

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test macOS platform

File: lib/Sema/MiscDiagnostics.cpp [hunk 1]
```diff
@@ -4987,6 +4987,168 @@ static void diagUnqualifiedAccessToMethodNamedSelf(const Expr *E,
...
+        keyExpr->printConstExprValue(&OS, /*additionalCheck=*/nullptr);
+        return out;
+      }
+      default:
+        break;
+      }
+      return None;
+    }
+
+    std::string getKeyLiteralDescription(const Expr *keyExpr) {
```
Comment (xedin) [inline lib/Sema/MiscDiagnostics.cpp:5015]: There are a couple of places in the Sema where this exact operation is needed i.e. for binding printing and for diagnostics (search for `ExprKind::IntegerLiteral`). Looks like it's time to move it to a hear and start using it from all the places where this is needed...

File: lib/Sema/MiscDiagnostics.cpp [hunk 2]
```diff
@@ -4987,6 +4987,168 @@ static void diagUnqualifiedAccessToMethodNamedSelf(const Expr *E,
...
+          continue;
+        }
+
+        auto *DRE = dyn_cast<DeclRefExpr>(keyExpr);
+        if (DRE && DRE->getDecl()) {
+          auto name = DRE->getDecl()->getBaseName();
+          if (name.isSpecial())
+            continue;
+
+          groupedDeclKeys[DRE->getDecl()].push_back({tupleElt, i});
```
Comment (xedin) [inline lib/Sema/MiscDiagnostics.cpp:5079]: Here is a problem with how you have it setup right now:

```
func test() {
  var rand: Int { get { return Int.random(in: 0...10000) } }

  let arr = [rand: "a", rand: "b"]
  print(arr)
}
```

Referencing computed property `rand` could produce different results. I'm torn between suggesting to not attempt this at all and adding more checking to this which could potentially miss some valid cases (which would result in an error in `warnings-as-errors` mode).

**Review by xedin — COMMENTED** [review]
Overall looks great, thank you! I left a couple comments inline.

File: lib/Sema/MiscDiagnostics.cpp (hunk 2 above)
Comment (xedin) [reply lib/Sema/MiscDiagnostics.cpp:5079]: Another example here would be use of property wrappers on parameters e.g. `(@Wrapper x: Int)` or declarations which control access to `wrappedValue` and `projectedValue` unbeknownst to the declaration, so we shouldn't do this probably.

Comment (LucianoPAlmeida) [reply lib/Sema/MiscDiagnostics.cpp:5079]: Those were a nice catch! Really didn't thought about that. Thanks

>  Referencing computed property rand could produce different results. I'm torn between suggesting to not attempt this at all and adding more checking to this which could potentially miss some valid cases (which would result in an error in warnings-as-errors mode).

Yeah, I guess we should be conservative here and do this only for literals which are really the most common case.

File: include/swift/AST/DiagnosticsSema.def [hunk 3]
```diff
@@ -3768,7 +3768,11 @@ ERROR(should_use_empty_dictionary_literal,none,
 // Dictionary literals
 ERROR(type_is_not_dictionary,none,
       "contextual type %0 cannot be used with dictionary literal", (Type))
-
+WARNING(duplicated_literal_keys_in_dictionary_literal, none,
+        "dictionary literal of type %0 has duplicated entries for %1 literal key%select{ %3|}2",
```
Comment (xedin) [inline include/swift/AST/DiagnosticsSema.def:3772]: Nit: "duplicate"

File: lib/Sema/MiscDiagnostics.cpp [hunk 4]
```diff
@@ -5011,6 +5011,149 @@ static void diagUnqualifiedAccessToMethodNamedSelf(const Expr *E,
   const_cast<Expr *>(E)->walk(Walker);
 }
 
+static void
+diagnoseDictionaryLiteralDuplicatedKeyEntries(const Expr *E,
+                                              const DeclContext *DC) {
```
Comment (xedin) [inline lib/Sema/MiscDiagnostics.cpp:5016]: Same here: "Duplicate"

File: lib/Sema/MiscDiagnostics.cpp [hunk 5]
```diff
@@ -5011,6 +5011,149 @@ static void diagUnqualifiedAccessToMethodNamedSelf(const Expr *E,
...
+            tupleElt->getElement(0)->getSemanticsProvidingExpr();
+        auto *LE = dyn_cast<LiteralExpr>(keyExpr);
+        if (!LE)
+          continue;
+
+        // Skip interpolated literals because they
+        // can contain expressions that although equal
+        // maybe be evaluated to different values. e.g.
+        // "\(a) \(a)" where 'a' is a computed variable.
+        if (isa<InterpolatedStringLiteralExpr>(LE))
```
Comment (xedin) [inline lib/Sema/MiscDiagnostics.cpp:5089]: Could you please aggregate this checks into an exhaustive switch statement over literal expression kind? That would be a much safer approach since compilation would fail when somebody adds a new literal kind and they'd have to consider how to handle it here.

File: lib/Sema/MiscDiagnostics.cpp [hunk 6]
```diff
@@ -5011,6 +5011,149 @@ static void diagUnqualifiedAccessToMethodNamedSelf(const Expr *E,
...
+            elt.first->getElement(0)->getSemanticsProvidingExpr());
+        const auto value = getKeyStringValueForDiagnostic(keyExpr);
+        DE.diagnose(elt.first->getLoc(),
+                    diag::duplicated_literal_keys_in_dictionary_literal, type,
+                    keyExpr->getLiteralKindDescription(), value.empty(), value);
+        for (auto &duplicated : keyValuePairs) {
+          emitNoteWithFixit(duplicated);
+        }
+
+        return {false, E};
```
Comment (xedin) [inline lib/Sema/MiscDiagnostics.cpp:5147]: Since this is just a warning let's just keep going and diagnose any nested collections as well? You even have a test for that which should warn but doesn't :)

**Review by xedin — APPROVED** [review]
Looks great! I have left a couple of comments inline, no need for re-review.

File: lib/Sema/MiscDiagnostics.cpp (hunk 6 above)
Comment (LucianoPAlmeida) [reply lib/Sema/MiscDiagnostics.cpp]: Fixed! It was originally on purpose test and behavior, I thought in only diagnose one at a time but as you said since is a warning is better just to diagnose all.

File: lib/Sema/MiscDiagnostics.cpp (hunk 5 above)
Comment (LucianoPAlmeida) [reply lib/Sema/MiscDiagnostics.cpp]: Fixed, thank you =]

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test
