### PR TITLE
[cxx-interop] Do not crash when an operator returns an internal type as `auto`

### LINKED ISSUE #83942: Assertion failure when importing C++ struct defined within an overloaded operator
(This issue report talks about Windows, but the bug isn't Windows-specific)

Seeing this assertion when trying to import WinRT headers into Swift with C++ interop:

~~~
Assertion failed: Name.isIdentifier() && "Name is not a simple identifier", file C:\Sources\swift\llvm-project\clang\include\clang/AST/Decl.h, line 277
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: C:\\Builds.noindex\\swift\\swift\\bin\\swift-ide-test.exe -print-module -module-to-print=WinRT -source-filename=x -target aarch64-unknown-windows-msvc -disable-implicit-string-processing-module-import -disable-implicit-concurrency-module-import -cxx-interoperability-mode=upcoming-swift -resource-dir C:\\Builds.noindex\\swift\\swift\\lib\\swift -swift-version 6 -Xcc -D_SILENCE_CLANG_COROUTINE_MESSAGE
1.	C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\cppwinrt\WinRT\base.h:8305:12: importing 'winrt::access_token'
2.	C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\cppwinrt\WinRT\base.h:8373:14: importing 'winrt::access_token::operator()'
3.	While importing a clang type AutoType 0x1b6af236e30 'guard' sugar imported
`-ElaboratedType 0x1b6af236e00 'guard' sugar imported
  `-RecordType 0x1b6af236de0 'guard' imported
    `-CXXRecord 0x1b6af236cb8 'guard'
4.	While importing a clang type ElaboratedType 0x1b6af236e00 'guard' sugar imported
`-RecordType 0x1b6af236de0 'guard' imported
  `-CXXRecord 0x1b6af236cb8 'guard'
5.	While importing a clang type RecordType 0x1b6af236de0 'guard' imported
`-CXXRecord 0x1b6af236cb8 'guard'
6.	C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\cppwinrt\WinRT\base.h:8375:20: importing 'guard'
Exception Code: 0x80000003
 #0 0x00007ff754e24798 HandleAbort C:\Sources\swift\llvm-project\llvm\lib\Support\Windows\Signals.inc:429:0
 #1 0x00007ffc20eb0ef8 (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0xa0ef8)
 #2 0x00007ffc20eb2a50 (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0xa2a50)
 #3 0x00007ffc20eb7668 (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0xa7668)
 #4 0x00007ffc20eb5ac8 (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0xa5ac8)
 #5 0x00007ffc20eb7be4 (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0xa7be4)
 #6 0x00007ff741d14a78 clang::NamedDecl::getName(void) const C:\Sources\swift\llvm-project\clang\include\clang\AST\Decl.h:277:0
 #7 0x00007ff747aa1e24 swift::ClangImporter::Implementation::importDeclContextImpl(class clang::Decl const *, class clang::DeclContext const *) C:\Sources\swift\swift\lib\ClangImporter\ImportDecl.cpp:10433:0
 #8 0x00007ff747aa2250 swift::ClangImporter::Implementation::importDeclContextOf(class clang::Decl const *, class swift::EffectiveClangContext, bool) C:\Sources\swift\swift\lib\ClangImporter\ImportDecl.cpp:10591:0
 #9 0x00007ff747a34e18 `anonymous namespace'::SwiftDeclConverter::VisitRecordDecl C:\Sources\swift\swift\lib\ClangImporter\ImportDecl.cpp:2211:0
#10 0x00007ff747a144dc `anonymous namespace'::SwiftDeclConverter::VisitCXXRecordDecl C:\Sources\swift\swift\lib\ClangImporter\ImportDecl.cpp:3154:0
...
~~~

The problematic type looks like this:
```
struct access_token {
  auto operator()() const {
    struct guard {}; // <-- oops
    return guard();
  }
};
```

### PR DESCRIPTION
**Pull request by egorzhdan**
If an overloaded operator returns `auto`, and the implementation of it returns an instance of a type declared within the operator, Swift was crashing when trying to import the internal type. Instead of crashing, let's not import those overloads.

rdar://159271202 / resolves https://github.com/swiftlang/swift/issues/83942

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please test

**Comment by egorzhdan** [comment]
@swift-ci please test Linux

File: lib/ClangImporter/ImportDecl.cpp [hunk 1]
```diff
@@ -10165,7 +10165,7 @@ DeclContext *ClangImporter::Implementation::importDeclContextImpl(
   assert(!dc->isTranslationUnit());
 
   auto decl = dyn_cast<clang::NamedDecl>(dc);
-  if (!decl)
+  if (!decl || !decl->getDeclName().isIdentifier())
```
Comment (Xazax-hun) [inline lib/ClangImporter/ImportDecl.cpp:10168]: Would this also prevent us importing types from unnamed structs like:
```
struct S {
  struct {
    struct Inner {
      int a, b;
    } c;
    auto f() {
        return Inner{1, 2};
    }
  } d;
};
```
?

And if it would, is that intentional?

Comment (egorzhdan) [reply lib/ClangImporter/ImportDecl.cpp:10168]: This case is tested in `test/Interop/C/struct/struct-decl-context-module-interface.swift`, it works because the struct still has a declaration name (which consists of an empty string).

**Review by Xazax-hun — APPROVED** [review]

File: test/Interop/Cxx/operators/Inputs/member-inline.h [hunk 2]
```diff
@@ -590,4 +590,13 @@ struct ClassWithDefaultTemplatedOperatorStar {
   template <typename T = int> T operator*() const { return 42; }
 };
 
+struct HasOperatorReturningAuto {
+  auto operator*() const {
```
Comment (hnrklssn) [inline test/Interop/Cxx/operators/Inputs/member-inline.h:594]: What happens if this is not an `operator*`, but instead something like `auto foo() const {`?
The way I read the patch, we don't import `struct Inner` because the decl context (`operator*()`) has a special name. But do we want to import it even when it does have a name?

Comment (egorzhdan) [reply test/Interop/Cxx/operators/Inputs/member-inline.h:594]: That wouldn't be imported at the moment – I have a PR open to support methods that return `auto`: https://github.com/swiftlang/swift/pull/83949

Comment (hnrklssn) [reply test/Interop/Cxx/operators/Inputs/member-inline.h:594]: Makes sense!
