### PR TITLE
Diagnose member type access on opaque types

### LINKED ISSUE #87039: Compiler crash when explicitly annotating variable with type (some P).T
### Description

_No response_

### Reproduction

```swift
protocol P {
	associatedtype T
	var t: T { get }
}

struct S: P {
	var t: Int { 23 }
}

// This explicit type annotation crashes the compiler
let spt: (some P).T = S().t
```

### Stack dump

```text
0.	Program arguments: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file Sources/main.swift -target arm64-apple-macosx26.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -stack-check -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.2.sdk -color-diagnostics -Xcc -fcolor-diagnostics -new-driver-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-driver -empty-abi-descriptor -no-auto-bridging-header-chaining -module-name main -disable-clang-spi -target-sdk-version 26.2 -target-sdk-name macosx26.2 -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -in-process-plugin-server-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/libSwiftInProcPluginServer.dylib -plugin-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/lib/swift/host/plugins -o /var/folders/_9/w_01hfx97ld0wtqbd7jnt4800000gn/T/TemporaryDirectory.lEqrbb/main-1.o
1.	Apple Swift version 6.2.3 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
2.	Compiling with effective version 5.10
3.	While evaluating request TypeCheckPrimaryFileRequest(source_file "Sources/main.swift")
4.	While type-checking statement at [Sources/main.swift:11:1 - line:11:27] RangeText="let spt: (some P).T = S()."
5.	While type-checking declaration 0x9b53e6448 (at Sources/main.swift:11:1)
6.	While type-checking expression at [Sources/main.swift:11:23 - line:11:27] RangeText="S()."
7.	While type-checking-target starting at Sources/main.swift:11:27
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000107462b60 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x00000001074604f0 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x000000010746318c SignalHandler(int, __siginfo*, void*) + 344
3  libsystem_platform.dylib 0x00000001969d3744 _sigtramp + 56
4  swift-frontend           0x00000001024b8538 std::__1::optional<swift::Type> llvm::function_ref<std::__1::optional<swift::Type> (swift::TypeBase*)>::callback_fn<swift::constraints::ConstraintSystem::openOpaqueType(swift::Type, swift::ContextualTypePurpose, swift::constraints::ConstraintLocatorBuilder, swift::Decl*)::$_1>(long, swift::TypeBase*) + 1208
5  swift-frontend           0x0000000102ce26bc swift::TypeTransform<swift::Type::transformRec(llvm::function_ref<std::__1::optional<swift::Type> (swift::TypeBase*)>) const::Transform>::doIt(swift::Type, swift::TypePosition) + 56
6  swift-frontend           0x00000001022e3a7c (anonymous namespace)::ConstraintGenerator::getTypeForPattern(swift::Pattern*, swift::constraints::ConstraintLocatorBuilder, bool, swift::PatternBindingDecl*, unsigned int) + 3544
7  swift-frontend           0x00000001022e28a0 swift::constraints::ConstraintSystem::generateConstraints(swift::Pattern*, swift::constraints::ConstraintLocatorBuilder, bool, swift::PatternBindingDecl*, unsigned int) + 116
8  swift-frontend           0x00000001022e16d4 swift::constraints::ConstraintSystem::generateConstraints(swift::constraints::SyntacticElementTarget&, swift::FreeTypeVariableBinding) + 2712
9  swift-frontend           0x000000010235dbc8 swift::constraints::ConstraintSystem::solve(swift::constraints::SyntacticElementTarget&, swift::FreeTypeVariableBinding) + 660
10 swift-frontend           0x000000010257b1ac swift::TypeChecker::typeCheckTarget(swift::constraints::SyntacticElementTarget&, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>, swift::DiagnosticTransaction*) + 704
11 swift-frontend           0x000000010257adc8 swift::TypeChecker::typeCheckExpression(swift::constraints::SyntacticElementTarget&, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>, swift::DiagnosticTransaction*) + 420
12 swift-frontend           0x000000010257c620 swift::TypeChecker::typeCheckBinding(swift::Pattern*&, swift::Expr*&, swift::DeclContext*, swift::Type, swift::PatternBindingDecl*, unsigned int, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 200
13 swift-frontend           0x000000010257c83c swift::TypeChecker::typeCheckPatternBinding(swift::PatternBindingDecl*, unsigned int, swift::Type, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 292
14 swift-frontend           0x00000001025dc278 (anonymous namespace)::DeclChecker::visit(swift::Decl*) + 5560
15 swift-frontend           0x0000000102693488 (anonymous namespace)::StmtChecker::typeCheckASTNode(swift::ASTNode&) + 1024
16 swift-frontend           0x00000001026990ac swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) + 288
17 swift-frontend           0x000000010269670c bool (anonymous namespace)::StmtChecker::typeCheckStmt<swift::BraceStmt>(swift::BraceStmt*&) + 312
18 swift-frontend           0x00000001026968cc swift::TypeChecker::typeCheckTopLevelCodeDecl(swift::TopLevelCodeDecl*) + 120
19 swift-frontend           0x00000001026ecc18 swift::TypeCheckPrimaryFileRequest::evaluate(swift::Evaluator&, swift::SourceFile*) const + 696
20 swift-frontend           0x00000001026f3bf8 swift::TypeCheckPrimaryFileRequest::OutputType swift::Evaluator::getResultUncached<swift::TypeCheckPrimaryFileRequest, swift::TypeCheckPrimaryFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckPrimaryFileRequest>(swift::Evaluator&, swift::TypeCheckPrimaryFileRequest, swift::TypeCheckPrimaryFileRequest::OutputType)::'lambda'()>(swift::TypeCheckPrimaryFileRequest const&, swift::TypeCheckPrimaryFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckPrimaryFileRequest>(swift::Evaluator&, swift::TypeCheckPrimaryFileRequest, swift::TypeCheckPrimaryFileRequest::OutputType)::'lambda'()) + 672
21 swift-frontend           0x00000001014962b8 bool llvm::function_ref<bool (swift::SourceFile&)>::callback_fn<swift::CompilerInstance::performSema()::$_0>(long, swift::SourceFile&) + 156
22 swift-frontend           0x000000010148f8e8 swift::CompilerInstance::forEachFileToTypeCheck(llvm::function_ref<bool (swift::SourceFile&)>) + 176
23 swift-frontend           0x000000010148f77c swift::CompilerInstance::performSema() + 120
24 swift-frontend           0x0000000101093fd8 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 772
25 swift-frontend           0x0000000101092fc8 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 3580
26 swift-frontend           0x0000000101010408 swift::mainEntry(int, char const**) + 5412
27 dyld                     0x0000000196601d54 start + 7184
```

### Expected behavior

The code should either compile successfully or produce a compiler error.

### Environment

swift-driver version: 1.127.14.1 Apple Swift version 6.2.3 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
Target: arm64-apple-macosx26.0

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jairajput**
This fixes a compiler crash when explicitly annotating a value with (someP).T. Opaque types intentionally hide associated types, so this should be a clean diagnostic. The change adds a targeted check in type resolution and a regression test. Fixes #87039

### CODE REVIEW

**Comment by jairajput** [comment]
@xedin @slavapestov @hborla @AnthonyLatsis Can you please Review this 🙇🏻

**Comment by jairajput** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test macOS

**Comment by jairajput** [comment]
@swift-ci please smoke test macOS

**Comment by xedin** [comment]
Thank you for the contribution! I will take a look on Monday.

**Comment by jairajput** [comment]
> Thank you for the contribution! I will take a look on Monday.

Sure Thanks 🙏🏻

**Comment by jairajput** [comment]
@xedin Have you looked at this

File: lib/Sema/TypeCheckType.cpp [hunk 1]
```diff
@@ -2052,6 +2052,17 @@ static Type resolveQualifiedIdentTypeRepr(const TypeResolution &resolution,
 
   // Short-circuiting.
   if (repr->isInvalid()) return ErrorType::get(ctx);
+  // Reject explicit syntax like `(some P).T`, but allow member type lookup on
+  // opaque archetypes introduced by generic requirements.
+  if (repr->getBase()->hasOpaque()) {
```
Comment (xedin) [inline lib/Sema/TypeCheckType.cpp]: Should this be `isa<NamedOpaqueReturnTypeRepr>` instead? I'm assuming that at some point `S<some P>` is going to be allowed and this check shouldn't diagnose the problem here.

Comment (jairajput) [reply lib/Sema/TypeCheckType.cpp]: Thanks For pointing this out I missed it, I Updated  this to check only the immediate base type repr , and diagnose only when that base is explicitly opaque 🙇🏻

Comment (xedin) [reply lib/Sema/TypeCheckType.cpp]: Great, thank you!

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Comment by xedin** [comment]
@swift-ci please test macOS platform
