### PR TITLE
[Concurrency] Allow default arguments to require actor isolation.

### LINKED ISSUE #58177: [SR-15916] @MainActor-isolated default arguments for @MainActor-isolated functions
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15916      |
   |Radar             | None         |
   |Original Reporter | @groue      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Xcode 13.3 beta 3 (13E5104i)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 2         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 618b69843e92ff0edf9587c87894767b

  </details>

**Issue Description:**

Hello,

The following snippet does not compile:

``` java
@MainActor class Foo { }

// error: call to main actor-isolated initializer 'init()' in a synchronous nonisolated context
// @MainActor func f(foo: Foo = Foo()) { }
//                               ^
// note: calls to initializer 'init()' from outside of its actor context are implicitly asynchronous
// @MainActor class Foo {
//                  ^
@MainActor func f(foo: Foo = Foo()) { }
```

It should compile, since everything in the declaration of the `f` function is MainActor-isolated.

### PR DESCRIPTION
**Pull request by hborla**
Type checking a default argument expression will compute the required actor isolation for evaluating that argument value synchronously. Actor isolation checking is deferred to the caller; it is an error to use a default argument from across isolation domains.

This change enables code like the following:

```swift
@MainActor
func requiresMainActor() -> Int { 0 }

@MainActor
func useMainActorDefault(value: Int = requiresMainActor()) { ... }

@MainActor
func mainActorCaller() {
  useMainActorDefault() // okay
}

func nonisolatedCaller() {
  useMainActorDefault() // error
}
```

Currently gated behind `-enable-experimental-feature IsolatedDefaultArguments`.

Resolves https://github.com/apple/swift/issues/58177

### CODE REVIEW

File: lib/Sema/TypeCheckConcurrency.cpp [hunk 1]
```diff
@@ -2123,6 +2129,94 @@ namespace {
       }
     }
 
+    bool refineRequiredIsolation(ActorIsolation refinedIsolation) {
+      if (requiredIsolationLoc.isInvalid())
+        return false;
```
Comment (ktoso) [inline lib/Sema/TypeCheckConcurrency.cpp:2134]: For my education, because I've been bitten by checking Loc validity for logic before... Why are we returning early if that happens here? I think this can happen across modules, but the isolation is expected to be always in the same module here so that's why? Wanted to understand that bit to avoid missing handling similar cases 🤔

File: test/Concurrency/isolated_default_arguments.swift [hunk 2]
```diff
@@ -0,0 +1,182 @@
...
+    // expected-error@+1 {{call to main actor-isolated local function 'f()' in a synchronous global actor 'SomeGlobalActor'-isolated context}}
+    f()
+  }
+) {}
+
+func conflictingClosureIsolation(
+  // expected-error@+1 {{default argument cannot be both main actor-isolated and global actor 'SomeGlobalActor'-isolated}}
+  closure: () -> Void = {
+    _ = requiresMainActor()
+    _ = requiresSomeGlobalActor()
```
Comment (ktoso) [inline test/Concurrency/isolated_default_arguments.swift:106]: that's a pretty nice diagnostic for these, how it falls out of the inference here... nice

File: test/Concurrency/isolated_default_arguments.swift [hunk 3]
```diff
@@ -0,0 +1,182 @@
...
+) {}
+
+actor A {}
+
+func closureWithIsolatedParam(
+  closure: (isolated A) -> Void = { _ in
+    // expected-error@+1 {{call to main actor-isolated global function 'requiresMainActor()' in a synchronous actor-isolated context}}
+    _ = requiresMainActor()
+  }
+) {}
```
Comment (ktoso) [inline test/Concurrency/isolated_default_arguments.swift:126]: I guess it is covered implicitly, but maybe worth adding test for 

```
extension A { 
func closureWithIsolatedParam(
   closure: () -> Void = { _ in
     _ = requiresMainActor()
   }
 ) {}
}
```

that's somewhat interesting... that would fail when called inside actor, but across could actually work...? Hop to main for param, then hop to invoke method...? I'm not sure what would happen today tbh, so may be worth the test-case

**Review by ktoso — APPROVED** [review]
Nice! Had a question inline and maybe one additional case to cover with a test?

**Comment by hborla** [comment]
@swift-ci please smoke test

File: lib/Sema/TypeCheckConcurrency.cpp (hunk 1 above)
Comment (hborla) [reply lib/Sema/TypeCheckConcurrency.cpp:2134]: We'll never compute the required isolation of a default argument or initializer expression across modules because we don't serialize expressions; we compute the required isolation in the original module and we need to serialize the required isolation to be checked at call-sites in other modules, so we should always have a source location here. However, I have not implemented nor tested the cross-module case yet 🙂

The reason I'm returning early here is because I'm using the validity of this source location to turn on the "required isolation" computation, so there's nothing to do here if the location isn't valid.

File: test/Concurrency/isolated_default_arguments.swift (hunk 3 above)
Comment (hborla) [reply test/Concurrency/isolated_default_arguments.swift:126]: Default arguments are always evaluated in the caller's isolation domain, so using a MainActor-isolated default argument to an actor-isolated method is conceptually "fine" - it only has implications on where you can use the default argument from. However, I'm considering an (artificial) restriction that the required isolation has to be either `nonisolated` or the same isolation as the function itself because I'm not sure why you would want a default argument that has any other isolation.

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
@swift-ci please build toolchain

File: lib/Sema/TypeCheckDeclPrimary.cpp [hunk 4]
```diff
@@ -2466,7 +2507,11 @@ class DeclChecker : public DeclVisitor<DeclChecker> {
               PBD->getInitContext(i));
           if (initContext) {
             TypeChecker::contextualizeInitializer(initContext, init);
-            checkInitializerActorIsolation(initContext, init);
+            if (auto *singleVar = PBD->getSingleVar()) {
+              (void)singleVar->getInitializerIsolation();
+            } else {
+              computeRequiredIsolation(initContext, init);
+            }
```
Comment (xedin) [inline lib/Sema/TypeCheckDeclPrimary.cpp:2514]: Why not simplify `computeRequiredIsolation` because this is already happening in the loop that goes over the entries in the pattern binding?

File: lib/Sema/TypeCheckStorage.cpp [hunk 5]
```diff
@@ -3225,7 +3225,7 @@ PropertyWrapperInitializerInfoRequest::evaluate(Evaluator &evaluator,
       // Check initializer effects.
       auto *initContext = new (ctx) PropertyWrapperInitializer(
           dc, param, PropertyWrapperInitializer::Kind::ProjectedValue);
-      checkInitializerActorIsolation(initContext, projectedValueInit);
+      (void)projection->getInitializerIsolation();
```
Comment (xedin) [inline lib/Sema/TypeCheckStorage.cpp:3228]: Just like in the other case I mentioned - might be worth replacing this direct call with a top-level `computeRequiredIsolation`

File: test/Concurrency/isolated_default_property_inits.swift [hunk 6]
```diff
@@ -0,0 +1,57 @@
...
+  @MainActor init(b: Int) {}
+
+  // expected-error@+1 {{return from initializer without initializing all stored properties}}
+  @SomeGlobalActor init(c: Int) {}
+}
+
+struct S2 {
+  var x = requiresMainActor()
+  var y = requiresSomeGlobalActor()
+  var z = 10
```
Comment (xedin) [inline test/Concurrency/isolated_default_property_inits.swift:42]: Might be good to add a test for multi-variable patterns as well make sure that all the variables are handled correctly.

**Review by xedin — APPROVED** [review]

File: lib/Sema/TypeCheckDeclPrimary.cpp (hunk 4 above)
Comment (xedin) [reply lib/Sema/TypeCheckDeclPrimary.cpp:2514]: Oh my got a wrote a giant comment and forgot to add it :/

Comment (xedin) [reply lib/Sema/TypeCheckDeclPrimary.cpp:2514]: This means that a single-variable pattern is going to be cached but multi-variable one is not going to. I want to suggest adding `Pattern *` as a parameter to `computeRequiredIsolation` so that after isolation is computed it could collect all of the variables involved and cache the result for each, this way we can simply use `computeRequiredIsolation` here and in other places without this re-computation caveat.

Another way might be to compute required isolation one for anchoring var decl after the loop is done.

File: lib/Sema/TypeCheckConcurrency.cpp (hunk 1 above)
Comment (ktoso) [reply lib/Sema/TypeCheckConcurrency.cpp:2134]: I see, so really detecting cross module here kindof... Thanks for explaining

File: test/Concurrency/isolated_default_arguments.swift (hunk 3 above)
Comment (ktoso) [reply test/Concurrency/isolated_default_arguments.swift:126]: Gotcha that makes sense; I'm not sure about the artificial restriction, I guess things fall into place and can work without it 🤔

File: lib/Sema/TypeCheckDeclPrimary.cpp (hunk 4 above)
Comment (hborla) [reply lib/Sema/TypeCheckDeclPrimary.cpp]: Fixed this to always go through the request and added a `PatternBindingDecl::getInitializerIsolation(unsigned i)` convenience to get the initializer isolation for each pattern binding entry.

File: lib/Sema/TypeCheckStorage.cpp (hunk 5 above)
Comment (hborla) [reply lib/Sema/TypeCheckStorage.cpp:3228]: I removed `swift::computeRequiredIsolation` in favor of always going through the request via `getInitializerIsolation`

File: test/Concurrency/isolated_default_property_inits.swift (hunk 6 above)
Comment (hborla) [reply test/Concurrency/isolated_default_property_inits.swift:42]: The only way that you can write an initial value for multiple variables is with a tuple pattern, but I've added that test case

**Comment by hborla** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
@swift-ci please smoke test

File: test/Concurrency/isolated_default_property_inits.swift (hunk 6 above)
Comment (xedin) [reply test/Concurrency/isolated_default_property_inits.swift:42]: Thank you!

File: lib/Sema/TypeCheckStorage.cpp (hunk 5 above)
Comment (xedin) [reply lib/Sema/TypeCheckStorage.cpp:3228]: Sounds good!

**Comment by hborla** [comment]
@swift-ci please smoke test
