### PR TITLE
[Sema] Do not emit cast to unrelated warning from existential to Anyhashable

### LINKED ISSUE #59405: Incorrect warning when casting `any Error` to `AnyHashable`
**Describe the bug**

Swift warns of casting `any Error` to `AnyHashable` when it shouldn't.

**To Reproduce**

Try compiling the following code:

```swift
func isHashable(_ error: Error) -> Bool {
  (error as? AnyHashable) != nil
}
```

Or the following code:

```swift
func isHashable(_ error: Error) -> Bool {
  error is AnyHashable
}
```

Both are given the following warning:

> ⚠️ Cast from 'any Error' to unrelated type 'AnyHashable' always fails

Despite not actually failing:

```swift
struct E: Error, Hashable {}
isHashable(E())  // `true` in either implementation
```

**Expected behavior**

The warning shouldn't appear, as it is incorrect.

**Environment (please complete the following information):**
 - OS: macOS 11
 - Xcode 14 beta 1

**Additional context**

While `any Hashable` may be the way forward here, the existing compiler magic around `AnyHashable` should still work.

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Checked cast an existential type to `Anyhashable` can be successful at runtime if underlying type conforms to hashable. But at compile time is not possible to know the conformances, so we cannot emit the cast to unrelated warning in this case.

Fixes https://github.com/apple/swift/issues/59405

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

File: lib/Sema/TypeCheckConstraints.cpp [hunk 1]
```diff
@@ -1942,7 +1942,14 @@ TypeChecker::typeCheckCheckedCast(Type fromType, Type toType,
         !toExistentialMetatype &&
         (toType->isAnyObject() || fromType->isAnyObject()))
       return CheckedCastKind::ValueCast;
-
+    
+    // Runtime can successfully cast a concrete value that conforms
+    // with hashable to `AnyHashable`. So if we have an existential
+    // is not possible to statically know the underlying conformances.
+    if (fromExistential && toType->isAnyHashable()) {
```
Comment (xedin) [inline lib/Sema/TypeCheckConstraints.cpp:1949]: Should this check be part of `couldDynamicallyConformToProtocol` instead?

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

**Review by xedin — APPROVED** [review]
Thank you!
