### PR TITLE
[AutoDiff] Refine debug info emitted for adjoint buffers

### LINKED ISSUE #62608: [AutoDiff] Conflicting debug info for argument with custom valueWithPullback
**Description**

A specific configuration of a wrapper function around `valueWithPullback()` built with both optimization and debug symbol generation leads to an assertion failure of `conflicting debug info for argument`.

**Steps to reproduce**

Place the following in a file:

```swift
import _Differentiation

public extension Array {
    @inlinable
    @differentiable(reverse)
    mutating func update(at index: Int, byCalling closure: @differentiable(reverse) (inout Element) -> Void) where Element: Differentiable {
        closure(&self[index])
    }
}

public func valueWithPullback<T>(
    at x: T, of f: @differentiable(reverse) (inout T) -> Void
) -> (value: Void, pullback: (inout T.TangentVector) -> Void) {
    @differentiable(reverse)
    func nonInoutWrappingFunction(_ t: T) -> T {
        var t = t
        f(&t)
        return t
    }
    let nonInoutPullback = pullback(at: x, of: nonInoutWrappingFunction)
    return ((), { $0 = nonInoutPullback($0) })
}

@inlinable
public func pullback<T>(
    at x: T, of f: @differentiable(reverse) (inout T) -> Void
) -> (inout T.TangentVector) -> Void {
    return valueWithPullback(at: x, of: f).pullback
}

public extension Array where Element: Differentiable {
    @inlinable
    @derivative(of: update(at:byCalling:))
    mutating func vjpUpdate(
        at index: Int,
        byCalling closure: @differentiable(reverse) (inout Element) -> Void
    )
    ->
    (value: Void, pullback: (inout Self.TangentVector) -> Void)
    {
        let closurePullback = pullback(at: self[index], of: closure)
        return (value: (), pullback: { closurePullback(&$0.base[index]) })
    }
}

func testUpdateByCalling() throws {
    @differentiable(reverse)
    func fOfArray(array: [Double]) -> Double {
        var array = array
        var result = 0.0
        for i in withoutDerivative(at: 0 ..< array.count) {
            array.update(at: i, byCalling: { (element: inout Double) in
                let initialElement = element
                for _ in withoutDerivative(at: 0 ..< i) {
                    element *= initialElement
                }
            })
            result += array[i]
        }
        return result
    }
    
    let array = [Double](repeating: 1.0, count: 3)
    let expectedGradientOfFOfArray = [1.0, 2.0, 3.0]
    let obtainedGradientOfFOfArray = gradient(at: array, of: fOfArray).base
}
```

And build it via `swiftc -O -g file.swift`. Note that both optimization and debug symbol generation must be used for this assertion failure to happen.

The assertion failure looks something like the following:

```
conflicting debug info for argument
  call void @llvm.dbg.value(metadata double %14, metadata !797, metadata !DIExpression()), !dbg !807
!796 = !DILocalVariable(name: "element", arg: 1, scope: !792, file: !18, line: 53, type: !201)
!797 = !DILocalVariable(name: "element", arg: 1, scope: !792, file: !18, line: 53, type: !201, flags: DIFlagArtificial)
<unknown>:0: error: fatal error encountered during compilation; please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project
<unknown>:0: note: Broken module found, compilation aborted!
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
Stack dump:
0.	Program arguments: /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2022-10-09-a.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file ConflictingDebugInfo.swift -target arm64-apple-macosx12.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -color-diagnostics -g -O -new-driver-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2022-10-09-a.xctoolchain/usr/bin/swift-driver -empty-abi-descriptor -resource-dir /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2022-10-09-a.xctoolchain/usr/lib/swift -module-name ConflictingDebugInfo -target-sdk-version 13.0 -target-sdk-name macosx13.0 -enable-default-cmo -o /var/folders/6y/ghmhq_xj3xq100vsttqqn2lc0000gq/T/TemporaryDirectory.3eixJp/ConflictingDebugInfo-2.o
1.	Apple Swift version 5.8-dev (LLVM b9ce35da9a19288, Swift 7335d60c50dc6af)
2.	Compiling with the current language version
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000107224840 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x0000000107223ac4 llvm::sys::RunSignalHandlers() + 128
2  swift-frontend           0x0000000107224e80 SignalHandler(int) + 304
3  libsystem_platform.dylib 0x00000001b77c74a4 _sigtramp + 56
4  libsystem_pthread.dylib  0x00000001b77afee0 pthread_kill + 288
5  libsystem_c.dylib        0x00000001b76ea340 abort + 168
6  swift-frontend           0x000000010295a924 PrettyStackTraceFrontend::~PrettyStackTraceFrontend() + 0
7  swift-frontend           0x0000000107188204 llvm::report_fatal_error(llvm::Twine const&, bool) + 268
8  swift-frontend           0x00000001071880f8 llvm::report_fatal_error(llvm::Twine const&, bool) + 0
9  swift-frontend           0x0000000106fcfaa8 llvm::VerifierPass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) + 0
10 swift-frontend           0x0000000106fad380 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) + 396
11 swift-frontend           0x0000000102d09ecc swift::performLLVMOptimizations(swift::IRGenOptions const&, llvm::Module*, llvm::TargetMachine*) + 4012
12 swift-frontend           0x0000000102d0b0c4 swift::performLLVM(swift::IRGenOptions const&, swift::DiagnosticEngine&, llvm::sys::SmartMutex<false>*, llvm::GlobalVariable*, llvm::Module*, llvm::TargetMachine*, llvm::StringRef, swift::UnifiedStatsReporter*) + 3092
13 swift-frontend           0x0000000102954a74 performCompileStepsPostSILGen(swift::CompilerInstance&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> >, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*) + 2512
14 swift-frontend           0x0000000102953afc swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 576
15 swift-frontend           0x00000001029628b0 withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 160
16 swift-frontend           0x0000000102955824 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 3256
17 swift-frontend           0x00000001027b014c swift::mainEntry(int, char const**) + 3288
18 dyld                     0x000000011075908c start + 520
```

**Expected behavior**

The file should build cleanly.

**Environment**
- Swift compiler version: present in current main, and extending back in nightly snapshots for as far as I've tried
- Deployment target: tested on macOS 12.5.1

### PR DESCRIPTION
**Pull request by asl**
Single input variable might yield multiple adjoint buffers if control flow is involved. Therefore we cannot simply transfer debug info from the input variable: it will be invalid as we will end with multiple locations for a single "source" variable, and, even worse, might end with conflicting debug info as different buffers might be optimized differently.

We do:
  - Drop input argument number. This must be unique and we're not
  - Correct variable name

Fixes #62608

### CODE REVIEW

**Comment by asl** [comment]
Tagging @BradLarson

**Comment by asl** [comment]
@swift-ci please test

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 1]
```diff
@@ -559,9 +559,18 @@ class PullbackCloner::Implementation final
...
+    llvm::SmallString<32> adjName;
     auto *newBuf = createFunctionLocalAllocation(
         bufType, loc, /*zeroInitialize*/ true,
-        debugInfo.transform([](AdjointValue::DebugInfo di) { return di.second; }));
+        debugInfo.transform(
+          [&](AdjointValue::DebugInfo di) {
+            SILDebugVariable &dv = di.second;
+            dv.ArgNo = 0;
+            llvm::raw_svector_ostream(adjName) << "adjoint of '" << dv.Name
+                                               << "' in bb" << origBB->getDebugID();
```
Comment (rxwei) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp:570]: Since the variable name shows up in the debugger, it might be better to use the user-facing language to describe these variables: "derivative of" instead of "adjoint of".  I'm not sure the " in bb..." part is useful as the user won't make sense of basic blocks.

File: test/AutoDiff/compiler_crashers_fixed/issue-62608-conflicting-debug-info.swift [hunk 2]
```diff
@@ -0,0 +1,79 @@
+// RUN: %target-swift-frontend -emit-sil -O -g %s | %FileCheck %s
+
+// REQUIRES: swift_in_compiler
```
Comment (rxwei) [inline test/AutoDiff/compiler_crashers_fixed/issue-62608-conflicting-debug-info.swift:3]: Why does this require `swift_in_compiler`?

Comment (asl) [reply test/AutoDiff/compiler_crashers_fixed/issue-62608-conflicting-debug-info.swift:3]: The code is optimized on Windows differently due to lack of optimization passes written in Swift....

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp (hunk 1 above)
Comment (asl) [reply lib/SILOptimizer/Differentiation/PullbackCloner.cpp:570]: The `in bbN` part is actually what is making this unique. We need to have separate variable names and there is a dedicated variable per basic block.

I'm not sure if 'derivative' is a correct term here. After all, it's adjoint :) Things are produced only in compiler-generated code (pullback), so we're already exposing the special terms.

**Comment by asl** [comment]
@swift-ci please test

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp (hunk 1 above)
Comment (rxwei) [reply lib/SILOptimizer/Differentiation/PullbackCloner.cpp:570]: ### Re. "in bbN"

I'm interested in finding a user-digestible name here.  Otherwise it seems to be nothing but confusion, as we can't expect users know what a "bb0" or "basic block 0" is.

For adjoint values coming from the current basic block, can we drop "in bbN" completely? This information is not useful to debug derivatives in the same scope.

For other derivatives, can we instead use source location information, e.g. "in the scope at 123:23", where "123:23" is the source location of the first instruction in its parent basic block.

### Re. "adjoint of"

> Things are produced only in compiler-generated code (pullback), so we're already exposing the special terms.

I disagree. "pullback" is an intentionally user-facing term and is used extensively in documentation and API, e.g. `pullback(at:of:)`, `valueWithPullback(at:of:)`. Thus we are **not** already exposing compiler-internal terms.

> I'm not sure if 'derivative' is a correct term here. After all, it's adjoint :)

I don't intend to debate about "correctness" here as the design already has already made a bunch of tradeoffs (e.g. "tangent" instead of the more correct "cotangent"). However, "adjoint" refers to the adjoint (transpose) of the differential linear map, which is really the pullback function itself, not a value. Thus "adjoint" wouldn't be the correct term to use on a vector in the pullback.

Additionally, "adjoint", exactly like "transpose", is relative. The adjoint of the adjoint of a linear map is the linear map itself. Using "adjoint" without mentioning what it's applied to adds confusion. An adjoint in the context of AD is the adjoint of the differential, which we already have a user-facing term for, which is "pullback".

As such, calling those values "v in the pullback" would be much much more correct and significantly less confusing than "adjoint of v".  However it can be argued that a nominal phrase would be better than the prepositional phrase "in the pullback", to name a variable in the debugger.

More on "adjoint": We chose to use "adjoint" in the implementation because most AD implementations did so, but in hindsight we really should've called it "tangent" or "cotangent" to align with the user model, i.e. the tangent vector at a certain point in the program. `JVPCloner`, the forward-mode implementation, already does so by referring to all values in the differential as "tangent".

Unlike "adjoint" which really refers to a function instead of a value, the word "derivative" on the other hand already has the duality of referring to both derivative functions and the results thereof. Also because it matches what's taught in introductory calculus, the word is the most approachable.  [The proposal](https://github.com/rxwei/swift-evolution/blob/autodiff/proposals/0000-differentiable-programming.md#the-differentiable-protocol-1) explicitly refers to values in the pullback as _derivative values_.

> [...] a derivative value is a vector in the [tangent bundle](https://en.wikipedia.org/wiki/Tangent_bundle) of this manifold and has type `TangentVector`.

That's why I'm suggesting "derivative of". "Partial derivative of" or "tangent vector" would be fine too. But shorter is better here for a debug variable.

**Comment by asl** [comment]
@rxwei Thanks for the comments!

> For other derivatives, can we instead use source location information, e.g. "in the scope at 123:23", where "123:23" is the source location of the first instruction in its parent basic block.

So, the problem here is that we need to have unique locations. Are we sure that scopes for different basic blocks will be different even after optimizations?

**Comment by rxwei** [comment]
> @rxwei Thanks for the comments!
> 
> > For other derivatives, can we instead use source location information, e.g. "in the scope at 123:23", where "123:23" is the source location of the first instruction in its parent basic block.
> 
> So, the problem here is that we need to have unique locations. Are we sure that scopes for different basic blocks will be different even after optimizations?

We could use something vague but non-confusing, e.g. `derivative of v in scope at 123:23 (scope #1)` where `#1` is the BB number.

**Comment by rxwei** [comment]
@adrian-prantl for input on this approach

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp (hunk 1 above)
Comment (CodaFi) [reply lib/SILOptimizer/Differentiation/PullbackCloner.cpp:570]: +1, please don't surface the notion of basic blocks to users. Statements do not map one-to-one between basic blocks and vice versa.

**Review by rxwei — APPROVED** [review]
Thanks for iterating on it!

I do wonder what this will look like when the body is expanded from a macro...

**Comment by asl** [comment]
@swift-ci please test

**Comment by asl** [comment]
@swift-ci please test
