### PR TITLE
[Sema] Perform availability checks in literals initializers

### LINKED ISSUE #61564: `@available` doesn’t affect literal initialization
**Describe the bug**
When a literal initializer is marked with an availability annotation, it's seemingly ignored by the compiler at the point of use, unless the initializer is used explicitly.

**Steps To Reproduce**

```swift
struct Foo {
    let bar: String
}

@available(*, deprecated)
extension Foo: ExpressibleByStringLiteral {
    init(stringLiteral value: StringLiteralType) {
        self.bar = value
    }
}

let a: Foo = Foo(stringLiteral: "") // warning: 'init(stringLiteral:)' is deprecated
let b: Foo = "" // no warning
```

**Expected behavior**
Both assignments should cause a deprecation warning.

Note: every other availability status (e.g. `unavailable`) is also ignored.

**Screenshots**

Screenshot 2022-10-13 at 11 29 21

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Some literal initializers were not being handled in `ExprAvailabilityWalker` which make then being left undiagnosed in cases like:
```swift
struct Foo {}

@available(*, deprecated)
extension Foo: ExpressibleByStringLiteral {
    init(stringLiteral value: StringLiteralType) { }
}

let a: Foo = Foo(stringLiteral: "") // warning: 'init(stringLiteral:)' is deprecated
let b: Foo = "" // no warning
```
So this adds check for all literals that have an associated implicit initializer and collection literal as well.

Fixes https://github.com/apple/swift/issues/61564

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

File: lib/Sema/TypeCheckAvailability.cpp [hunk 1]
```diff
@@ -3254,13 +3254,22 @@ class ExprAvailabilityWalker : public ASTWalker {
...
-      auto Range = RLE->getSourceRange();
-      diagnoseDeclRefAvailability(Context.getRegexDecl(), Range);
-      diagnoseDeclRefAvailability(RLE->getInitializer(), Range);
+
+    if (auto *LE = dyn_cast<LiteralExpr>(E)) {
+      auto Range = LE->getSourceRange();
+      if (auto *RLE = dyn_cast<RegexLiteralExpr>(LE)) {
+        // Regex literals require both the Regex<Output> type to be available,
+        // as well as the initializer that is implicitly called.
+        diagnoseDeclRefAvailability(Context.getRegexDecl(), Range);
```
Comment (hamishknight) [inline lib/Sema/TypeCheckAvailability.cpp:3263]: I wonder if this is something that ought to be applied to the result type of a literal in general. e.g for:

```swift
@available(*, unavailable)
struct S: ExpressibleByIntegerLiteral {
  init(integerLiteral value: Int) {}
}
@available(*, unavailable)
typealias IntegerLiteralType = S

let i = 0
```

We're implicitly forming a call to `S(integerLiteral: 0)`, but aren't erroring that it's unavailable.

File: test/Sema/availability_literals.swift [hunk 2]
```diff
@@ -0,0 +1,169 @@
+// RUN: %target-typecheck-verify-swift -swift-version 5
```
Comment (hamishknight) [inline test/Sema/availability_literals.swift:1]: I love the thoroughness of this test, thanks!

**Review by hamishknight — APPROVED** [review]
Thanks! I think we probably ought to apply this logic to the result type of the literal too, but I'm happy for that to be done in a follow up if you want. cc @tshortli in case he has any other comments.

**Review by tshortli — APPROVED** [review]

File: lib/Sema/TypeCheckAvailability.cpp (hunk 1 above)
Comment (tshortli) [reply lib/Sema/TypeCheckAvailability.cpp:3263]: A long term goal of mine is to run availability checks on the transformed AST so that we can catch these issues in a more generalized way. Not sure if that applies directly here but it seems like it might.

Comment (hamishknight) [reply lib/Sema/TypeCheckAvailability.cpp:3263]: Yeah these literal cases are tricky because we don't actually form the call in the AST, we emit them directly in SILGen

Comment (LucianoPAlmeida) [reply lib/Sema/TypeCheckAvailability.cpp:3263]: > I wonder if this is something that ought to be applied to the result type of a literal in general.

I'll create an issue to track that case and look at it separately =]

Comment (LucianoPAlmeida) [reply lib/Sema/TypeCheckAvailability.cpp:3263]: @hamishknight @tshortli Issue created #61890
