### PR TITLE
[cxx-interop] Support rvalue-ref qualified methods

### LINKED ISSUE #83801: [cxx-interop] Passing an `std::optional<std::string>` from C++ to Swift causes a compiler crash only in Release builds
### Description

When passing a `std::optional<std::string>` from C++ to Swift, the compiler crashes - but only in Release/Archive builds.

In debug it works fine.

### Reproduction

Common C++ header
```cpp
struct Params {
  std::optional<std::string> value;
};
```

Swift implementation;
```swift
func someFunc(params: MyCppLib.Params) {
  print("Called!")
}
```

C++ implementation;
```cpp
Params p { "Hello world!" }; 
MySwiftLib.someFunc(p);
```

### Stack dump

```text
Showing Recent Errors Only
SwiftCompile normal arm64 Compiling\ AsyncImageLoadOptions.swift,\ AsyncImageLoadOptions+toSDWebImageOptions.swift,\ AsyncImagePriority.swift,\ Func_void_std__exception_ptr.swift,\ Func_void_std__shared_ptr_margelo__nitro__image__HybridImageSpec_.swift,\ HybridWebImageFactory.swift,\ HybridWebImageFactorySpec.swift,\ HybridWebImageFactorySpec_cxx.swift,\ HybridWebImageLoader.swift,\ NitroWebImageAutolinking.swift,\ SDWebImageManager+loadImage.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/nitrogen/generated/ios/swift/AsyncImageLoadOptions.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/ios/AsyncImageLoadOptions+toSDWebImageOptions.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/nitrogen/generated/ios/swift/AsyncImagePriority.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/nitrogen/generated/ios/swift/Func_void_std__exception_ptr.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/nitrogen/generated/ios/swift/Func_void_std__shared_ptr_margelo__nitro__image__HybridImageSpec_.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/ios/HybridWebImageFactory.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/nitrogen/generated/ios/swift/HybridWebImageFactorySpec.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/nitrogen/generated/ios/swift/HybridWebImageFactorySpec_cxx.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/ios/HybridWebImageLoader.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/nitrogen/generated/ios/NitroWebImageAutolinking.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/ios/SDWebImageManager+loadImage.swift (in target 'NitroWebImage' from project 'Pods')

Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /Volumes/External/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -c /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/nitrogen/generated/ios/swift/AsyncImageLoadOptions.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/ios/AsyncImageLoadOptions+toSDWebImageOptions.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/nitrogen/generated/ios/swift/AsyncImagePriority.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/nitrogen/generated/ios/swift/Func_void_std__exception_ptr.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/nitrogen/generated/ios/swift/Func_void_std__shared_ptr_margelo__nitro__image__HybridImageSpec_.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/ios/HybridWebImageFactory.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/nitrogen/generated/ios/swift/HybridWebImageFactorySpec.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/nitrogen/generated/ios/swift/HybridWebImageFactorySpec_cxx.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/ios/HybridWebImageLoader.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/nitrogen/generated/ios/NitroWebImageAutolinking.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/ios/SDWebImageManager+loadImage.swift -supplementary-output-file-map "/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/supplementaryOutputs-128" -target arm64-apple-ios15.5 -Xllvm -aarch64-use-tbi -enable-objc-interop -stack-check -cxx-interoperability-mode=default -sdk /Volumes/External/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.5.sdk -I "/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/BuildProductsPath/Release-iphoneos/NitroWebImage" -I "/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/BuildProductsPath/Release-iphoneos/NitroImage" -I "/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/BuildProductsPath/Release-iphoneos/NitroModules" -F "/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/BuildProductsPath/Release-iphoneos/NitroWebImage" -F /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/hermes-engine/destroot/Library/Frameworks/universal -F "/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/hermes-engine/Pre-built" -no-color-diagnostics -g -debug-info-format=dwarf -dwarf-version=4 -import-underlying-module -module-cache-path /Volumes/External/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -O -D COCOAPODS -D RCT_NEW_ARCH_ENABLED -serialize-debugging-options -const-gather-protocols-file "/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/NitroWebImage_const_extract_protocols.json" -enable-experimental-feature DebugDescriptionMacro -enable-bare-slash-regex -empty-abi-descriptor -validate-clang-modules-once -clang-build-session-file /Volumes/External/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -Xcc -working-directory -Xcc /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods -resource-dir /Volumes/External/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -file-compilation-dir /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods -Xcc "-fmodule-map-file=/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/BuildProductsPath/Release-iphoneos/NitroImage/NitroImage.modulemap" -Xcc "-fmodule-map-file=/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/BuildProductsPath/Release-iphoneos/NitroModules/NitroModules.modulemap" -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/DoubleConversion/DoubleConversion.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/RCTDeprecation/RCTDeprecation.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/RCTFabric/React-RCTFabric.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/RCTRuntime/React-RCTRuntime.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/RCTTypeSafety/RCTTypeSafety.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React/React-Core.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/ReactCodegen/ReactCodegen.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/ReactCommon/ReactCommon.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React_Fabric/React-Fabric.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React_FabricComponents/React-FabricComponents.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React_NativeModulesApple/React-NativeModulesApple.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React_RCTAppDelegate/React-RCTAppDelegate.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/SDWebImage/SDWebImage.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/SocketRocket/SocketRocket.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/fmt/fmt.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/folly/RCT-Folly.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/glog/glog.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/jsi/React-jsi.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/jsinspector_modern/React-jsinspector.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/jsinspector_modern_cdp/React-jsinspectorcdp.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/jsinspector_modern_network/React-jsinspectornetwork.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/jsinspector_modern_tracing/React-jsinspectortracing.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_debug/React-debug.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_featureflags/React-featureflags.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_nativemodule_defaults/React-defaultsnativemodule.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_nativemodule_dom/React-domnativemodule.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_nativemodule_featureflags/React-featureflagsnativemodule.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_nativemodule_idlecallbacks/React-idlecallbacksnativemodule.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_nativemodule_microtasks/React-microtasksnativemodule.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_renderer_css/React-renderercss.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_renderer_debug/React-rendererdebug.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_renderer_graphics/React-graphics.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_renderer_imagemanager/React-ImageManager.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_runtime/React-jsitooling.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_utils/React-utils.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/reacthermes/React-hermes.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/yoga/Yoga.modulemap -Xcc -fmodule-map-file=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/NitroWebImage/NitroWebImage.modulemap -Xcc -std=c++20 -Xcc -ivfsstatcache -Xcc /Volumes/External/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphoneos18.5-22F76-e8e9afe82149fbaaa193ba75a8d26675.sdkstatcache -Xcc "-I/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/swift-overrides.hmap" -Xcc -iquote -Xcc "/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/NitroWebImage-generated-files.hmap" -Xcc "-I/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/NitroWebImage-own-target-headers.hmap" -Xcc "-I/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/NitroWebImage-all-non-framework-target-headers.hmap" -Xcc -ivfsoverlay -Xcc "/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/Pods-8699adb1dd336b26511df848a716bd42-VFS-iphoneos/all-product-headers.yaml" -Xcc -iquote -Xcc "/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/NitroWebImage-project-headers.hmap" -Xcc "-I/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/BuildProductsPath/Release-iphoneos/NitroWebImage/include" -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Private -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Private/NitroWebImage -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/DoubleConversion -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/FBLazyVector -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/RCT-Folly -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/RCTRequired -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/RCTTypeSafety -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-Core -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-Fabric -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-FabricComponents -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-FabricImage -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-ImageManager -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-Mapbuffer -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-NativeModulesApple -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-RCTAnimation -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-RCTBlob -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-RCTFBReactNativeSpec -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-RCTFabric -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-RCTRuntime -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-RCTText -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-RuntimeApple -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-RuntimeCore -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-RuntimeHermes -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-callinvoker -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-cxxreact -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-debug -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-defaultsnativemodule -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-domnativemodule -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-featureflags -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-featureflagsnativemodule -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-graphics -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-hermes -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-idlecallbacksnativemodule -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-jserrorhandler -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-jsi -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-jsiexecutor -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-jsinspector -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-jsinspectorcdp -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-jsinspectornetwork -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-jsinspectortracing -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-jsitooling -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-logger -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-microtasksnativemodule -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-oscompat -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-perflogger -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-performancetimeline -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-rendererconsistency -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-renderercss -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-rendererdebug -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-runtimeexecutor -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-runtimescheduler -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-timing -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-utils -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/ReactCodegen -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/ReactCommon -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/Yoga -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/boost -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/fast_float -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/fmt -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/glog -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/hermes-engine -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Private/Yoga -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/glog -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/boost -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/DoubleConversion -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/fast_float/include -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/fmt/include -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/SocketRocket -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/RCT-Folly -Xcc "-I/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/DerivedSources-normal/arm64" -Xcc "-I/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/DerivedSources/arm64" -Xcc "-I/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/DerivedSources" -Xcc -DPOD_CONFIGURATION_RELEASE=1 -Xcc -DCOCOAPODS=1 -module-name NitroWebImage -frontend-parseable-output -disable-clang-spi -target-sdk-version 18.5 -target-sdk-name iphoneos18.5 -external-plugin-path /Volumes/External/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/lib/swift/host/plugins#/Volumes/External/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Volumes/External/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/local/lib/swift/host/plugins#/Volumes/External/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/swift-plugin-server -in-process-plugin-server-path /Volumes/External/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/libSwiftInProcPluginServer.dylib -plugin-path /Volumes/External/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Volumes/External/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/lib/swift/host/plugins -enable-default-cmo -num-threads 10 -o "/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/AsyncImageLoadOptions.o" -o "/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/AsyncImageLoadOptions+toSDWebImageOptions.o" -o "/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/AsyncImagePriority.o" -o "/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/Func_void_std__exception_ptr.o" -o "/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/Func_void_std__shared_ptr_margelo__nitro__image__HybridImageSpec_.o" -o "/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/HybridWebImageFactory.o" -o "/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/HybridWebImageFactorySpec-a0bcb7c348b280bc8fd837a65d28019f.o" -o "/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/HybridWebImageFactorySpec_cxx.o" -o "/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/HybridWebImageLoader.o" -o "/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/NitroWebImageAutolinking-eb0136c4d43d7063abc775fa809f3589.o" -o "/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/SDWebImageManager+loadImage.o" -index-unit-output-path /Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/AsyncImageLoadOptions.o -index-unit-output-path /Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/AsyncImageLoadOptions+toSDWebImageOptions.o -index-unit-output-path /Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/AsyncImagePriority.o -index-unit-output-path /Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/Func_void_std__exception_ptr.o -index-unit-output-path /Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/Func_void_std__shared_ptr_margelo__nitro__image__HybridImageSpec_.o -index-unit-output-path /Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/HybridWebImageFactory.o -index-unit-output-path /Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/HybridWebImageFactorySpec-a0bcb7c348b280bc8fd837a65d28019f.o -index-unit-output-path /Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/HybridWebImageFactorySpec_cxx.o -index-unit-output-path /Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/HybridWebImageLoader.o -index-unit-output-path /Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/NitroWebImageAutolinking-eb0136c4d43d7063abc775fa809f3589.o -index-unit-output-path /Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/SDWebImageManager+loadImage.o
1.	Apple Swift version 6.1.2 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
2.	Compiling with effective version 5.10
3.	While evaluating request ExecuteSILPipelineRequest(Run pipelines { Mandatory Diagnostic Passes + Enabling Optimization Passes } on SIL for NitroWebImage)
4.	While running pass #5068 SILModuleTransform "MandatorySILLinker".
5.	While deserializing SIL function "_ZNKOSt3__18optionalINS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEEdeB8ne190102Ev"
6.	*** DESERIALIZATION FAILURE ***
*** If any module named here was modified in the SDK, please delete the ***
*** new swiftmodule files from the SDK and keep only swiftinterfaces.   ***
module 'NitroImage', builder version '6.1.2(5.10)/Apple Swift version 6.1.2 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)', built from source against SDK 22F76, non-resilient, loaded from '/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup prod/BuildProductsPath/Release-iphoneos/NitroImage/NitroImage.swiftmodule/arm64-apple-ios.swiftmodule'
result is ambiguous (_)
Cross-reference to module '__ObjC'
... std
... __1
... optional
... (in c:@N@std@N@__1@S@optional>#$@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C)
... __operatorStar
... with type (std.__1.optional<std.__1.basic_string<CChar, std.__1.char_traits<CChar>, std.__1.allocator<CChar>>>) -> () -> UnsafePointer<std.__1.basic_string<CChar, std.__1.char_traits<CChar>, std.__1.allocator<CChar>>>


Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x000000010a7d6e24 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x000000010a7d4c5c llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x000000010a7d7460 SignalHandler(int) + 360
3  libsystem_platform.dylib 0x0000000194f156a4 _sigtramp + 56
4  libsystem_pthread.dylib  0x0000000194edb88c pthread_kill + 296
5  libsystem_c.dylib        0x0000000194de4a3c abort + 124
6  swift-frontend           0x0000000104de21a4 swift::ModuleFileSharedCore::outputDiagnosticInfo(llvm::raw_ostream&) const + 0
7  swift-frontend           0x0000000104d75a50 swift::ModuleFile::getSourceLoc() const + 0
8  swift-frontend           0x0000000104d755d0 swift::ModuleFile::fatal(llvm::Error) const + 44
9  swift-frontend           0x0000000104d7b9b8 swift::ModuleFile::getModule(llvm::PointerEmbeddedInt<unsigned int, 31>) + 0
10 swift-frontend           0x0000000104db88cc swift::SILDeserializer::readSILFunctionChecked(llvm::PointerEmbeddedInt<unsigned int, 31>, swift::SILFunction*, llvm::StringRef, bool, bool, bool) + 1920
11 swift-frontend           0x0000000104dcc9b8 swift::SILDeserializer::lookupSILFunction(swift::SILFunction*, bool) + 456
12 swift-frontend           0x0000000104e957b8 swift::SILLinkerVisitor::maybeAddFunctionToWorklist(swift::SILFunction*, swift::SerializedKind_t) + 464
13 swift-frontend           0x0000000104e95a70 swift::SILLinkerVisitor::process() + 372
14 swift-frontend           0x0000000104e95888 swift::SILLinkerVisitor::processFunction(swift::SILFunction*) + 152
15 swift-frontend           0x0000000105601940 (anonymous namespace)::SILLinker::run() + 192
16 swift-frontend           0x00000001054c447c swift::SILPassManager::executePassPipelinePlan(swift::SILPassPipelinePlan const&) + 13536
17 swift-frontend           0x00000001054feedc swift::SimpleRequest<swift::ExecuteSILPipelineRequest, std::__1::tuple<> (swift::SILPipelineExecutionDescriptor), (swift::RequestFlags)1>::evaluateRequest(swift::ExecuteSILPipelineRequest const&, swift::Evaluator&) + 52
18 swift-frontend           0x00000001054e296c swift::ExecuteSILPipelineRequest::OutputType swift::Evaluator::getResultUncached<swift::ExecuteSILPipelineRequest, swift::ExecuteSILPipelineRequest::OutputType swift::evaluateOrFatal<swift::ExecuteSILPipelineRequest>(swift::Evaluator&, swift::ExecuteSILPipelineRequest)::'lambda'()>(swift::ExecuteSILPipelineRequest const&, swift::ExecuteSILPipelineRequest::OutputType swift::evaluateOrFatal<swift::ExecuteSILPipelineRequest>(swift::Evaluator&, swift::ExecuteSILPipelineRequest)::'lambda'()) + 412
19 swift-frontend           0x00000001054e5c6c swift::runSILDiagnosticPasses(swift::SILModule&) + 416
20 swift-frontend           0x00000001049e88b0 swift::CompilerInstance::performSILProcessing(swift::SILModule*) + 656
21 swift-frontend           0x0000000104628d90 performCompileStepsPostSILGen(swift::CompilerInstance&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*) + 1360
22 swift-frontend           0x000000010462871c swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 2688
23 swift-frontend           0x000000010462b654 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 1764
24 swift-frontend           0x0000000104629fd8 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 3716
25 swift-frontend           0x00000001045ae0bc swift::mainEntry(int, char const**) + 5428
26 dyld                     0x0000000194b3ab98 start + 6076
Failed frontend command:
/Volumes/External/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -c /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/nitrogen/generated/ios/swift/AsyncImageLoadOptions.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/ios/AsyncImageLoadOptions+toSDWebImageOptions.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/nitrogen/generated/ios/swift/AsyncImagePriority.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/nitrogen/generated/ios/swift/Func_void_std__exception_ptr.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/nitrogen/generated/ios/swift/Func_void_std__shared_ptr_margelo__nitro__image__HybridImageSpec_.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/ios/HybridWebImageFactory.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/nitrogen/generated/ios/swift/HybridWebImageFactorySpec.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/nitrogen/generated/ios/swift/HybridWebImageFactorySpec_cxx.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/ios/HybridWebImageLoader.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/nitrogen/generated/ios/NitroWebImageAutolinking.swift /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/node_modules/react-native-nitro-web-image/ios/SDWebImageManager+loadImage.swift -supplementary-output-file-map /Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/supplementaryOutputs-128 -target arm64-apple-ios15.5 -Xllvm -aarch64-use-tbi -enable-objc-interop -stack-check -cxx-interoperability-mode\=default -sdk /Volumes/External/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.5.sdk -I /Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/BuildProductsPath/Release-iphoneos/NitroWebImage -I /Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/BuildProductsPath/Release-iphoneos/NitroImage -I /Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/BuildProductsPath/Release-iphoneos/NitroModules -F /Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/BuildProductsPath/Release-iphoneos/NitroWebImage -F /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/hermes-engine/destroot/Library/Frameworks/universal -F /Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/hermes-engine/Pre-built -no-color-diagnostics -g -debug-info-format\=dwarf -dwarf-version\=4 -import-underlying-module -module-cache-path /Volumes/External/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity\=checked -O -D COCOAPODS -D RCT_NEW_ARCH_ENABLED -serialize-debugging-options -const-gather-protocols-file /Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/NitroWebImage_const_extract_protocols.json -enable-experimental-feature DebugDescriptionMacro -enable-bare-slash-regex -empty-abi-descriptor -validate-clang-modules-once -clang-build-session-file /Volumes/External/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -Xcc -working-directory -Xcc /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods -resource-dir /Volumes/External/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -file-compilation-dir /Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods -Xcc -fmodule-map-file\=/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/BuildProductsPath/Release-iphoneos/NitroImage/NitroImage.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/BuildProductsPath/Release-iphoneos/NitroModules/NitroModules.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/DoubleConversion/DoubleConversion.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/RCTDeprecation/RCTDeprecation.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/RCTFabric/React-RCTFabric.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/RCTRuntime/React-RCTRuntime.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/RCTTypeSafety/RCTTypeSafety.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React/React-Core.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/ReactCodegen/ReactCodegen.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/ReactCommon/ReactCommon.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React_Fabric/React-Fabric.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React_FabricComponents/React-FabricComponents.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React_NativeModulesApple/React-NativeModulesApple.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React_RCTAppDelegate/React-RCTAppDelegate.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/SDWebImage/SDWebImage.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/SocketRocket/SocketRocket.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/fmt/fmt.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/folly/RCT-Folly.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/glog/glog.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/jsi/React-jsi.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/jsinspector_modern/React-jsinspector.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/jsinspector_modern_cdp/React-jsinspectorcdp.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/jsinspector_modern_network/React-jsinspectornetwork.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/jsinspector_modern_tracing/React-jsinspectortracing.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_debug/React-debug.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_featureflags/React-featureflags.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_nativemodule_defaults/React-defaultsnativemodule.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_nativemodule_dom/React-domnativemodule.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_nativemodule_featureflags/React-featureflagsnativemodule.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_nativemodule_idlecallbacks/React-idlecallbacksnativemodule.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_nativemodule_microtasks/React-microtasksnativemodule.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_renderer_css/React-renderercss.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_renderer_debug/React-rendererdebug.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_renderer_graphics/React-graphics.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_renderer_imagemanager/React-ImageManager.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_runtime/React-jsitooling.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/react_utils/React-utils.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/reacthermes/React-hermes.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/yoga/Yoga.modulemap -Xcc -fmodule-map-file\=/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/NitroWebImage/NitroWebImage.modulemap -Xcc -std\=c++20 -Xcc -ivfsstatcache -Xcc /Volumes/External/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphoneos18.5-22F76-e8e9afe82149fbaaa193ba75a8d26675.sdkstatcache -Xcc -I/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/swift-overrides.hmap -Xcc -iquote -Xcc /Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/NitroWebImage-generated-files.hmap -Xcc -I/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/NitroWebImage-own-target-headers.hmap -Xcc -I/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/NitroWebImage-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/Pods-8699adb1dd336b26511df848a716bd42-VFS-iphoneos/all-product-headers.yaml -Xcc -iquote -Xcc /Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/NitroWebImage-project-headers.hmap -Xcc -I/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/BuildProductsPath/Release-iphoneos/NitroWebImage/include -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Private -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Private/NitroWebImage -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/DoubleConversion -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/FBLazyVector -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/RCT-Folly -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/RCTRequired -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/RCTTypeSafety -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-Core -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-Fabric -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-FabricComponents -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-FabricImage -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-ImageManager -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-Mapbuffer -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-NativeModulesApple -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-RCTAnimation -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-RCTBlob -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-RCTFBReactNativeSpec -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-RCTFabric -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-RCTRuntime -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-RCTText -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-RuntimeApple -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-RuntimeCore -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-RuntimeHermes -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-callinvoker -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-cxxreact -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-debug -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-defaultsnativemodule -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-domnativemodule -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-featureflags -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-featureflagsnativemodule -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-graphics -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-hermes -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-idlecallbacksnativemodule -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-jserrorhandler -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-jsi -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-jsiexecutor -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-jsinspector -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-jsinspectorcdp -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-jsinspectornetwork -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-jsinspectortracing -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-jsitooling -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-logger -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-microtasksnativemodule -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-oscompat -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-perflogger -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-performancetimeline -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-rendererconsistency -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-renderercss -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-rendererdebug -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-runtimeexecutor -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-runtimescheduler -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-timing -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/React-utils -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/ReactCodegen -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/ReactCommon -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/Yoga -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/boost -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/fast_float -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/fmt -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/glog -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Public/hermes-engine -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/Headers/Private/Yoga -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/glog -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/boost -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/DoubleConversion -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/fast_float/include -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/fmt/include -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/SocketRocket -Xcc -I/Volumes/External/Workspace/klassapp/source/edular/edular-mobile/ios/Pods/RCT-Folly -Xcc -I/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/DerivedSources-normal/arm64 -Xcc -I/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/DerivedSources/arm64 -Xcc -I/Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/DerivedSources -Xcc -DPOD_CONFIGURATION_RELEASE\=1 -Xcc -DCOCOAPODS\=1 -module-name NitroWebImage -frontend-parseable-output -disable-clang-spi -target-sdk-version 18.5 -target-sdk-name iphoneos18.5 -external-plugin-path /Volumes/External/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/lib/swift/host/plugins\#/Volumes/External/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Volumes/External/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/local/lib/swift/host/plugins\#/Volumes/External/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/swift-plugin-server -in-process-plugin-server-path /Volumes/External/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/libSwiftInProcPluginServer.dylib -plugin-path /Volumes/External/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Volumes/External/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/lib/swift/host/plugins -enable-default-cmo -num-threads 10 -o /Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/AsyncImageLoadOptions.o -o /Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/AsyncImageLoadOptions+toSDWebImageOptions.o -o /Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/AsyncImagePriority.o -o /Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/Func_void_std__exception_ptr.o -o /Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/Func_void_std__shared_ptr_margelo__nitro__image__HybridImageSpec_.o -o /Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/HybridWebImageFactory.o -o /Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/HybridWebImageFactorySpec-a0bcb7c348b280bc8fd837a65d28019f.o -o /Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/HybridWebImageFactorySpec_cxx.o -o /Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/HybridWebImageLoader.o -o /Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/NitroWebImageAutolinking-eb0136c4d43d7063abc775fa809f3589.o -o /Volumes/External/Library/Developer/Xcode/DerivedData/edular-eevtswfydvhtpeenncuahazijzcn/Build/Intermediates.noindex/ArchiveIntermediates/turnagegroup\ prod/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/SDWebImageManager+loadImage.o -index-unit-output-path /Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/AsyncImageLoadOptions.o -index-unit-output-path /Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/AsyncImageLoadOptions+toSDWebImageOptions.o -index-unit-output-path /Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/AsyncImagePriority.o -index-unit-output-path /Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/Func_void_std__exception_ptr.o -index-unit-output-path /Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/Func_void_std__shared_ptr_margelo__nitro__image__HybridImageSpec_.o -index-unit-output-path /Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/HybridWebImageFactory.o -index-unit-output-path /Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/HybridWebImageFactorySpec-a0bcb7c348b280bc8fd837a65d28019f.o -index-unit-output-path /Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/HybridWebImageFactorySpec_cxx.o -index-unit-output-path /Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/HybridWebImageLoader.o -index-unit-output-path /Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/NitroWebImageAutolinking-eb0136c4d43d7063abc775fa809f3589.o -index-unit-output-path /Pods.build/Release-iphoneos/NitroWebImage.build/Objects-normal/arm64/SDWebImageManager+loadImage.o
Command SwiftCompile failed with a nonzero exit code

Command SwiftCompile failed with a nonzero exit code
```

### Expected behavior

I expect it to build fine in both debug and release.

### Environment

swift-driver version: 1.120.5 Apple Swift version 6.1.2 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
Target: arm64-apple-macosx15.0

### Additional information

[One of my library's users](https://github.com/mrousavy/react-native-nitro-image/issues/56) temporarily fixed the issue by disabling some of the runtime performance optimizations;

```rb
config.build_settings['SWIFT_COMPILATION_MODE'] = 'incremental'
config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Osize'
```

So I assume it has something to do with the `-O` flags. Maybe `std::string`'s optimizations (like small-string-buffer-optimizations) cause it to crash?

### PR DESCRIPTION
**Pull request by Xazax-hun**
We already imported methods that have && as qualifiers but did not support them properly. When in the C++ code there is overloading based on the reference qualifiers the imported Swift functions are ambiguous. This patch append "Consuming" to the && qualified methods' names to avoid the ambiguity. It also makes sure these methods are actually imported as consuming.

In case of operators, however, Swift does not have a way to distinguish between the consuming and non-consuming self. This patch prevents importing the consuming variants. This fixes some compiler crashes during deserialization that we hit due to the ambiguities.

Fixes #83801

rdar://158675235

### CODE REVIEW

**Comment by Xazax-hun** [comment]
@swift-ci please smoke test

File: lib/ClangImporter/ImportName.cpp [hunk 1]
```diff
@@ -1955,6 +1952,12 @@ ImportedName NameImporter::importNameImpl(const clang::NamedDecl *D,
     if (!functionDecl)
       return ImportedName();
 
+    // We do not import && qualified operators yet.
+    if (const auto *method = dyn_cast<clang::CXXMethodDecl>(functionDecl)) {
+      if (method->getRefQualifier() == clang::RefQualifierKind::RQ_RValue)
+        return ImportedName();
+    }
```
Comment (hnrklssn) [inline lib/ClangImporter/ImportName.cpp:1959]: Is it possible to import it as unavailable, with an explanation why? Silently dropping it seems like a possible source of confusion.

File: lib/ClangImporter/ImportName.cpp [hunk 2]
```diff
@@ -2298,29 +2301,49 @@ ImportedName NameImporter::importNameImpl(const clang::NamedDecl *D,
...
       }
     }
+    if (shouldAddMutable || shouldAddConsuming) {
+      newName = baseName;
+      if (shouldAddMutable)
+        newName += "Mutating";
+      if (shouldAddConsuming)
+        newName += "Mutating";
+      baseName = newName;
+    }
```
Comment (hnrklssn) [inline lib/ClangImporter/ImportName.cpp:2346]: What happens if one overload is non-const, and one is (non-const and) rvalue ref?

File: lib/ClangImporter/ImportName.cpp (hunk 1 above)
Comment (Xazax-hun) [reply lib/ClangImporter/ImportName.cpp:1959]: I don't think the availability feature was planned to cover scenarios like this. If we have two functions in Swift that are considered redeclarations, making one of them unavailable does not seem to make the compiler happy:

```
test.swift:4:20: error: invalid redeclaration of 'f()'
1 | struct S {
2 |     func f() {}
  |          `- note: 'f()' previously declared here
3 |     @available(*, unavailable)
4 |     consuming func f() {}
  |                    `- error: invalid redeclaration of 'f()'
5 | }
```

Unless I am missing something. So I think we would run into the same issues with ambiguity. 

Also, many of these operators would be imported as unavailable anyways with a message to use the corresponding generated Swift property. So one would never call `__operatorStar` but the synthesized `value` or `pointee` property and we already have a message on these operators what to use instead. Having two of these might not work and/or might make things a bit confusing even if the redeclaration part was working as expected.

File: lib/ClangImporter/ImportName.cpp (hunk 2 above)
Comment (Xazax-hun) [reply lib/ClangImporter/ImportName.cpp:2346]: I have a typo here, the second one supposed to add "Consuming". Oops.

File: test/Interop/Cxx/class/inheritance/functions-module-interface.swift [hunk 3]
```diff
@@ -15,7 +15,7 @@
 // CHECK-NEXT:   @discardableResult
 // CHECK-NEXT:   public func constInBase() -> UnsafePointer<CChar>!
 // CHECK-NEXT:   @discardableResult
-// CHECK-NEXT:   public func rvalueThisInBase() -> UnsafePointer<CChar>!
+// CHECK-NEXT:   public consuming func rvalueThisInBase() -> UnsafePointer<CChar>!
```
Comment (egorzhdan) [inline test/Interop/Cxx/class/inheritance/functions-module-interface.swift:18]: Could you please add a test for the method renaming part?

File: lib/ClangImporter/ImportName.cpp (hunk 1 above)
Comment (hnrklssn) [reply lib/ClangImporter/ImportName.cpp:1959]: Right this would be an issue for operators since we don't rename those. But for the case where a non-consuming overload doesn't exist there wouldn't be any trace of any `__operatorStar` (etc) existing. I would presume that the synthesized property wouldn't exist either, then?

File: lib/ClangImporter/ImportName.cpp [hunk 4]
```diff
@@ -59,10 +60,6 @@ STATISTIC(ImportNameNumCacheMisses, "# of times the import name cache was missed
 using namespace swift;
 using namespace importer;
 
-// Commonly-used Clang classes.
-using clang::CompilerInstance;
-using clang::CompilerInvocation;
```
Comment (egorzhdan) [inline lib/ClangImporter/ImportName.cpp:64]: Minor: accidental change?

File: lib/ClangImporter/ClangImporter.cpp [hunk 5]
```diff
@@ -5735,7 +5735,8 @@ MemberRefExpr *getSelfInteropStaticCast(FuncDecl *funcDecl,
 // The base C++ method is either the original C++ method that corresponds
 // to the imported base member, or it's the synthesized C++ method thunk
 // used in another synthesized derived thunk that acts as a base member here.
-const clang::CXXMethodDecl *getCalledBaseCxxMethod(FuncDecl *baseMember) {
+static const clang::CXXMethodDecl *
+getCalledBaseCxxMethod(FuncDecl *baseMember) {
```
Comment (egorzhdan) [inline lib/ClangImporter/ClangImporter.cpp:5702]: Minor: accidental change?

File: lib/ClangImporter/ImportName.cpp (hunk 4 above)
Comment (Xazax-hun) [reply lib/ClangImporter/ImportName.cpp:64]: This is an intentional cleanup, this was unused but was lazy to open a separate PR just for this. Same for the change below. But I can move this to an independent PR.

File: lib/ClangImporter/ClangImporter.cpp (hunk 5 above)
Comment (Xazax-hun) [reply lib/ClangImporter/ClangImporter.cpp:5702]: Same as above.

File: lib/ClangImporter/ImportName.cpp (hunk 1 above)
Comment (Xazax-hun) [reply lib/ClangImporter/ImportName.cpp:1959]: > I would presume that the synthesized property wouldn't exist either, then?

Yeah, if there is no operator, we will not have a synthesized property. Moreover, we cannot synthesize the correct code for operators with rvalue ref qualifiers.

**Comment by Xazax-hun** [comment]
@swift-ci please smoke test

**Comment by Xazax-hun** [comment]
@swift-ci please smoke test

**Review by egorzhdan — APPROVED** [review]
