### PR TITLE
[SourceKit] Don't report type for `InjectIntoOptionalExpr`

### LINKED ISSUE #66882: SourceKit expression type request returns optional type for expression that is not optional
**Description**
When requesting expression types for the following Swift snippet, I would expect the type of `foo` to be `String`, not `String?`:

```
let foo: String = "Hey"

let bar: String? = foo // `foo` should be of type `String` not `String?`
```

I looked into why this might be happening and found that SourceKit is taking the type of the `InjectIntoOptionalExpr` that surrounds the actual expression in the assignment. It could be that this is the expected behaviour, but since SourceKit is used in an IDE context, I would not expect the type of the injected expression.

If this is not the expected behaviour, I'm willing to implement a fix. 

**Steps to reproduce**
Running `source.request.expression.type` on the above code snippet produces the following output: 

```
<ExpressionTypes>
(16, 21): String
(40, 41): String?
</ExpressionTypes>

```
**Environment**
- Swift compiler version info:
    swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
- Xcode version info: Version 14.2 (14C18)
- Deployment target: arm64-apple-macosx13.0

### PR DESCRIPTION
**Pull request by skrtks**
Fixes incorrectly reporting an optional type for an expression when the contextual type is optional.

fixes #66882
rdar://111462279

### CODE REVIEW

File: lib/IDE/IDETypeChecking.cpp [hunk 1]
```diff
@@ -667,6 +667,10 @@ class ExpressionTypeCollector: public SourceEntityWalker {
     if (E->getType().isNull())
       return false;
 
+    // We should not report a type for InjectIntoOptionalExpr
+    if (isa<InjectIntoOptionalExpr>(E))
+      return false;
```
Comment (rintaro) [inline lib/IDE/IDETypeChecking.cpp:672]: [Cursor-info ignores all `isImplicit()` expressions](https://github.com/apple/swift/blob/c50263c7301dd47b2982041d44ca8eb46504e7cb/lib/IDE/IDERequests.cpp#L301-L302). Could you try:
```suggestion
    if (E->isImplict())
      return false;
```

File: test/SourceKit/ExpressionType/basic.swift [hunk 2]
```diff
@@ -31,3 +38,6 @@ func DictS(_ a: [Int: S]) {
 // CHECK: (291, 292): Int?
 // CHECK: (295, 332): Int?
 // CHECK: (295, 320): Int
+// CHECK: (395, 398): String?
+// CHECK: (418, 423): String
+// CHECK: (457, 458): String
```
Comment (bnbarham) [inline test/SourceKit/ExpressionType/basic.swift:43]: Would you mind adding the other type here? Not sure if it's the `"Hey"`, `"Bye"` or `c` 😅

File: lib/IDE/IDETypeChecking.cpp (hunk 1 above)
Comment (skrtks) [reply lib/IDE/IDETypeChecking.cpp:672]: Yes, that works, but I think we should add an exception for `OptionalEvaluationExpr`, right?

Comment (skrtks) [reply lib/IDE/IDETypeChecking.cpp:672]: Also, currently, in case of an implicit `DotSyntaxCallExpr` like in `let a = 1 + 2`, we expect the type of `+` to be `(Int, Int) -> Int`. With your suggested change that becomes `(Int.Type) -> (Int, Int) -> Int`. Is that correct, or do you think we should also opt in for reporting types of implicit `DotSyntaxCallExpr`?

File: test/SourceKit/ExpressionType/basic.swift (hunk 2 above)
Comment (skrtks) [reply test/SourceKit/ExpressionType/basic.swift]: No problem :)

**Comment by bnbarham** [comment]
@swift-ci please test

**Review by bnbarham — APPROVED** [review]

**Review by hamishknight — APPROVED** [review]
Thanks! LGTM

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test Windows

**Comment by hamishknight** [comment]
@swift-ci please test Windows
