### PR TITLE
[Concurrency] `memberAccessHasSpecialPermissionInSwift5` should treat…

### LINKED ISSUE #70550: "init accessors" don't work with actors
### Description

`init` accessors don't seem to be usable from `actor` initializers (I expected that `accesses:` might not work, but `initializes:` doesn't either, which seems like a bug)

### Reproduction

The example from the "init accessors" SE, with `struct` changed to `actor`,

```swift
final actor Angle {
  var degrees: Double
  var radians: Double {
    @storageRestrictions(initializes: degrees)
    init(initialValue)  {
      degrees = initialValue * 180 / .pi
    }

    get { degrees * .pi / 180 }
    set { degrees = newValue * 180 / .pi }
  }

  init(degrees: Double) {
    self.degrees = degrees // initializes 'self.degrees' directly
  }

  init(radians: Double) {
    self.radians = radians // calls init accessor for 'self.radians', passing 'radians' as the argument
  }
}
```

produces

```
ActorInitAccessor.swift:18:10: warning: actor-isolated property 'radians' can not be mutated from a non-isolated context; this is an error in Swift 6
    self.radians = radians // calls init accessor for 'self.radians', passing 'radians' as the argument
         ^
ActorInitAccessor.swift:3:7: note: mutation of this property is only permitted within the actor
  var radians: Double {
      ^
ActorInitAccessor.swift:18:18: warning: cannot access property 'degrees' here in non-isolated initializer; this is an error in Swift 6
    self.radians = radians // calls init accessor for 'self.radians', passing 'radians' as the argument
    ~~~~~~~~~~~~~^~~~~~~~~
ActorInitAccessor.swift:18:18: note: after making a copy of 'self', only non-isolated properties of 'self' can be accessed from this init
    self.radians = radians // calls init accessor for 'self.radians', passing 'radians' as the argument
    ~~~~~~~~~~~~~^~~~~~~~~
```

### Expected behavior

I think this should compile.

### Environment

(Xcode 15.1)

swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx13.0

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by xedin**
… init accessors as stored properties

Init accessor properties cannot escape self and are only 
allowed to initialized and access a set of properties declared
in their `@storageRestrictions(...)` attribute.

Resolves: https://github.com/apple/swift/issues/70550

### CODE REVIEW

**Comment by xedin** [comment]
@kavon I'd appreciate if you could help me come up with an example that should warn. I looked at the FlowIsolation path and it's ran after `assign_or_init` is expanded into individual accesses to underlying stored properties and/or setter/getter calls.

**Comment by xedin** [comment]
Based on my read of FlowIsolation it doesn't matter what kind of access is performed inside, it tracks references.

File: test/Concurrency/flow_isolation.swift [hunk 1]
```diff
@@ -729,3 +729,28 @@ actor CheckDeinitFromActor {
...
+      set { degrees = newValue * 180 / .pi }
+    }
+
+    init(degrees: Double) {
+      self.degrees = degrees // Ok
+    }
+
+    init(radians: Double) {
+      self.radians = radians // Ok
+    }
```
Comment (kavon) [inline test/Concurrency/flow_isolation.swift:754]: Some suggestions for other things to test for:

1. What happens if you init `radians`, escape `self` from the initializer, and then try to access `radians` again?
2.  Same as above but if `radians` is a nonisolated property.
3. What happens if you try to escape `self` prior to `radians` being initialized?

I assume that for all of these, they _should_ work the same as a computed property (which is hopefully already tested).  Only (3) is one that is really to ensure FlowIsolation doesn't crash, since it should already get flagged as an error by DI prior.

Comment (kavon) [reply test/Concurrency/flow_isolation.swift:754]: Otherwise if those are working, then this PR LGTM.

Comment (xedin) [reply test/Concurrency/flow_isolation.swift:759]: @kavon I had to make some changes to FlowIsolation pass to recognize `setter` use of init accessor properties. That cannot be done earlier because only DI knows when to use init accessor and when to use a setter for a particular property.

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

File: test/Concurrency/flow_isolation.swift [hunk 2]
```diff
@@ -734,3 +734,86 @@ actor CheckDeinitFromActor {
...
+
+    init(value: Double) {
+      let escapingSelf: (Angle) -> Void = { _ in }
+
+      // degrees are initialized here via default value associated with radians
+
+      escapingSelf(self)
+
+      self.radians = 0
+      // expected-warning@-1 {{actor-isolated property 'radians' can not be mutated from a non-isolated context; this is an error in Swift 6}}
```
Comment (kavon) [inline test/Concurrency/flow_isolation.swift:769]: 👍🏼

**Review by kavon — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform
