### PR TITLE
[TypeChecker] Simplify ExprPattern from Bool literals in Bool? switch

### LINKED ISSUE #61817: Optional boolean doesn't satisfy switch exhaustivity with literal case statements
**Describe the bug**

When `switch`ing over an optional boolean with `true` and `false` literals, an error diagnostic is produced claiming that the switch statement is not exhaustive. This is inconsistent with other pattern matchable value types which unwraps the optional to perform a match.

**Steps To Reproduce**

```swift
func over(bool: Bool?) {
  switch bool { // Switch must be exhaustive
  case true:
    break
  case false:
    break
  case .none:
    break
  }
}
```

**Expected behavior**

No diagnostic should be produced, as the switch is exhaustive. For example if we redefine a `Bool`-like `enum`, the exhaustivity checker works correctly and no diagnostic is produced:

```swift
enum BoolEnum {
  case truthy
  case falsy
}

func over(boolEnum: BoolEnum?) {
  switch boolEnum {
  case .truthy:
    break
  case .falsy:
    break
  case .none:
    break
  }
}
```

**Screenshots**

image

**Environment (please fill out the following information)**
 - OS: [e.g. macOS 11.0] macOS 13.0 (22A380)
 - Xcode Version/Tag/Branch: Xcode 14.0 (14A309), Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)

### PR DESCRIPTION
**Pull request by jameesbrown**
Resolves: [swiftlang/swift#61817](https://github.com/swiftlang/swift/issues/61817).

Boolean literals are treated as `ExprPattern`s when switching over `Bool?` because they require implicit conversion to Optionals, resulting in them being wrapped in `InjectIntoOptionalExpr`s. Consequently, they do not contribute to exhausting the switch cases.

In this special case, we can instead treat them as `true?`/`false?`.

### CODE REVIEW

**Review by xedin — APPROVED** [review]
We need equivalent change in CSGen I think and a test-case where a switch is used inside of a closure. 

@hamishknight could you please take a look at the changes?

**Comment by xedin** [comment]
Approved by mistake, meant only to comment.

**Comment by jameesbrown** [comment]
@xedin Thanks for looking at it. I will investigate a CSGen change and add that test case.

**Comment by xedin** [comment]
It should be pretty similar to what you already did, look at `getTypeForPattern`.

**Comment by hamishknight** [comment]
I'm not actually sure this needs a CSGen change, `trySimplifyExprPattern` is called for both `coercePatternToType` and CSApply, and this is something that needs to operate on the type-checked pattern (since `ExpressibleByBooleanLiteral` means you can't always turn a top-level `BooleanLiteralExpr` into a `BoolPattern`). But yes, please add a test case in a closure :)

File: lib/Sema/TypeCheckPattern.cpp [hunk 1]
```diff
@@ -1015,21 +1015,30 @@ NullablePtr<Pattern> TypeChecker::trySimplifyExprPattern(ExprPattern *EP,
                                                          Type patternTy) {
   auto *subExpr = EP->getSubExpr();
   auto &ctx = EP->getDeclContext()->getASTContext();
+  const auto optType = patternTy->getOptionalObjectType();
 
-  if (patternTy->isBool()) {
-    // The type is Bool.
+  if (patternTy->isBool() || (optType && optType->isBool())) {
+    // The type is Bool or Optional<Bool>.
```
Comment (hamishknight) [inline lib/Sema/TypeCheckPattern.cpp:1021]: IMO this ought to be able to handle any level of optionality, you can either use `lookThroughAllOptionalTypes` and re-apply the same level of wrapping after, or you could refactor this function to be recursive and have it try unwrapping a single level as one of the checks(you'd want to handle the `nil` case before that though)

**Comment by jameesbrown** [comment]
@hamishknight Thanks! I took your suggestion and rewrote it recursively to handle any level of optionality. I also included the test case inside a closure.

@xedin I explored possible changes in `getTypeForPattern`, but without already knowing the type of `ExprPattern`, I couldn’t find a clear solution. It doesn’t seem like a necessary change, though it might be an optimization—potentially solving the constraints earlier?

File: lib/Sema/TypeCheckPattern.cpp [hunk 2]
```diff
@@ -1045,7 +1060,13 @@ NullablePtr<Pattern> TypeChecker::trySimplifyExprPattern(ExprPattern *EP,
         return nullptr;
     }
   }
-  return nullptr;
+
+  const auto *BLE = dyn_cast_or_null<BooleanLiteralExpr>(
+      subExpr->getSemanticsProvidingExpr());
```
Comment (hamishknight) [inline lib/Sema/TypeCheckPattern.cpp:1065]: Tiny nit: `getSemanticsProvidingExpr` never returns null, so `dyn_cast` should be sufficient here

**Review by hamishknight — APPROVED** [review]
Thanks!

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Review by xedin — APPROVED** [review]
LGTM! I originally thought that this needs to happen earlier.

**Comment by hamishknight** [comment]
Those are the [same failures as on main](https://ci.swift.org/job/swift-main-source-compat-suite/1053/), so yeah they're unrelated

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility Debug
