### PR TITLE
[ConstraintSystem] A few improvements to key path handling and diagnostics

### LINKED ISSUE #55436: [SR-12991] Type checker doesn't take context from "<key path expr> as <function type>" - Examples in Key Path Expressions as Functions proposal don't compile
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12991      |
   |Radar             | rdar://problem/64304000         |
   |Original Reporter | @beccadax      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: c64fc41feeb4a1205ee0f1de49f07037

  </details>

**cloned from**:  
* [SR-12897](https://bugs.swift.org/browse/SR-12897) "\.self" not working with keypath-as-function - Examples in Key Path Expressions as Functions proposal don't compile  

**is duplicated by**:  
* [SR-13392](https://bugs.swift.org/browse/SR-13392) Can't use `as` to coerce KeyPath to function  

**Issue Description:**

The proposal which was Implemented in Swift 5.2 for Key Path Expressions as Functions has examples which do not compile. <https://github.com/apple/swift-evolution/blob/master/proposals/0249-key-path-literal-function-expressions.md>

When run in a playground:

``` swift
struct User {
    let email: String
}

let users = [User]()
let f3 = \User.email as (User) -> String
users.map(f3) // Error: Expression type '(User) -> String' is ambiguous without more context
 
```

\[Edited to remove symptoms of a separate bug tracked as SR-12897.\]

### PR DESCRIPTION
**Pull request by xedin**
- Makes sure that key path types are not assigned eagerly when the literal is passed as an argument to a call or coerced
- Fixes locators used for root and value type matching
- Fixes diagnostics related to missing optional unwraps of the key path root and members
- Prevents inference from using type-erased superclasses as bindings for a key path type
- Avoids propagating contextual placeholders into key paths

Resolves: rdar://116376651
Resolves: https://github.com/apple/swift/issues/55436

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

File: lib/Sema/CSSimplify.cpp [hunk 1]
```diff
@@ -12364,21 +12397,58 @@ ConstraintSystem::simplifyKeyPathConstraint(
...
+                         return match->getKind() ==
+                                    ConstraintKind::ApplicableFunction ||
+                                match->getKind() == ConstraintKind::Disjunction;
+                       })) {
+      formUnsolved();
+    } else {
+      auto resolvedKPTy =
+          BoundGenericType::get(kpDecl, nullptr, {rootTy, valueTy});
+      return matchTypes(resolvedKPTy, keyPathTy, ConstraintKind::Bind,
+                        subflags, loc);
```
Comment (Jumhyn) [inline lib/Sema/CSSimplify.cpp:12448]: In the little digging I did on this issue, it struck me that it seems like in this path we're basically using the simplification step to infer a `KeyPath`-type binding for the literal (by simplifying to a `Bind` constraint). Do you know why we wouldn't want to use the usual `PotentialBindings::infer` machinery to do that? It seems like we could then use `BindingSet::favoredOverDisjunction` to ensure we don't attempt the binding until we've resolved disjunctions rather than searching for the constraints here?

File: lib/Sema/CSSimplify.cpp [hunk 2]
```diff
@@ -12364,21 +12397,58 @@ ConstraintSystem::simplifyKeyPathConstraint(
...
+    // an overload of `test` is selected, we'd end up with no solutions
+    // because the type of the key path expression is actually: '(Data) -> Int'
+    // and not 'WritableKeyPath<Data, Int>`.
+    auto *typeVar = keyPathTy->getAs<TypeVariableType>();
+    if (typeVar && findConstraintThroughOptionals(
+                       typeVar, OptionalWrappingDirection::Unwrap,
+                       [&](Constraint *match, TypeVariableType *) {
+                         return match->getKind() ==
+                                    ConstraintKind::ApplicableFunction ||
+                                match->getKind() == ConstraintKind::Disjunction;
```
Comment (Jumhyn) [inline lib/Sema/CSSimplify.cpp:12441]: If we're just looking for function/disjunction constraints, how does this handle the `let fn = \User.email as (User) -> String`?

File: lib/Sema/CSSimplify.cpp (hunk 1 above)
Comment (xedin) [reply lib/Sema/CSSimplify.cpp:12448]: We cannot use binding inference for this because constraint gets re-activated when adjacent types are bound.

File: lib/Sema/CSSimplify.cpp (hunk 2 above)
Comment (xedin) [reply lib/Sema/CSSimplify.cpp:12441]: Coercions form disjunctions

File: lib/Sema/CSSimplify.cpp (hunk 1 above)
Comment (xedin) [reply lib/Sema/CSSimplify.cpp:12448]: I put a branch into resolveKeyPath to handle contextual placeholder but here I think we actually want to have it bound to propagate “unknown type” information out.

**Comment by xedin** [comment]
@swift-ci please test windows platform

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Comment by xedin** [comment]
@swift-ci please test source compatibility
