### PR TITLE
[SILOptimizer] Fix ConstantCapturePropagation ODR violation with generic closures

### LINKED ISSUE #87917: ConstantCapturePropagation creates ODR violation for generic closures with different type substitutions
### Description

We found a can miscompile where generic closures with different concrete types and different callers can be instantiated to the same generic function. This miscompile led to an incorrect function being called at runtime and eventually a SIGTRAP because of it.

### Reproduction

Two tests added in https://github.com/swiftlang/swift/pull/87916
- A SIL test shows the SILVerifier failure
- An executable test to show the runtime misbehavior 

```swift
// Build with: swiftc -Osize -Xllvm -sil-disable-pass=GenericSpecializer
// GenericSpecializer is disabled to isolate the bug — in practice this manifests in multi-module builds where GenericSpecializer doesn't run on the @_alwaysEmitIntoClient stdlib closure before CCP does.

  @inline(never)
  func parseU8(_ s: String) -> UInt8? { UInt8(s, radix: 10) }

  @inline(never)
  func parseInt(_ s: String) -> Int? { Int(s, radix: 10) }

  @inline(never)
  func parseInt32(_ s: String) -> Int32? { Int32(s, radix: 10) }

  print("UInt8: \(parseU8("42") as Any)")   // Optional(42) ✓
  print("Int: \(parseInt("42") as Any)")     // garbage ✗
  print("Int32: \(parseInt32("42") as Any)") // garbage ✗
```

If we enable SILVerifier, we'd get "SIL verification failed: entry point argument types do not match function type: matched While verifying SIL function "@$s15generic_closureSiTf3nnpSi10_n""
If we build the executable, the later two function calls will produce garbage

### Expected behavior

- Tests ought to pass
- The executable should print three "42"

### Environment

main branch, 6.3 branch

### Additional information

https://github.com/swiftlang/swift/pull/84071 rewrite surrounding code:

In `specializeClosure()`

https://github.com/swiftlang/swift/blob/6e29396edec5e55d4171883a9c0bc90abbedebfb/SwiftCompilerSources/Sources/Optimizer/FunctionPasses/ConstantCapturePropagation.swift#L148-L184

  - The mangled name encodes only constant-propagated arguments, not the generic substitution map
  - The function declaration correctly preserves the generic signature with preserveGenericSignature: isGeneric
  - The body cloning contradicts this by calling `cloneAndSpecializeFunction(substitutions: partialApply.substitutionMap)`, which applies concrete type substitutions via `TypeSubstitutionCloner`

Result: `{radix=10, T=UInt8}` and `{radix=10, T=Int}` produce the same shared symbol with different bodies — an ODR violation.

Proposed fix:

When specializeClosure determines the specialized closure remains generic (`isGeneric == true`), clone the body without applying type substitutions, and use `partial_apply` with the substitution map at the call site instead of `thin_to_thick_function`. The body stays generic with type parameters like `$*Optional<Self>`, which is correct since all callers share the same shared symbol and apply their own concrete types through the substitution map on the `partial_apply`.

cc @kyulee-com @drodriguez @eeckstein

### PR DESCRIPTION
**Pull request by DataCorrupted**
## Summary
This PR fixes the ODR violation detailed in https://github.com/swiftlang/swift/issues/87917

## Impl

When specializeClosure determines the specialized closure remains generic (`isGeneric == true`), clone the body without applying type substitutions, and use `partial_apply` with the substitution map at the call site instead of `thin_to_thick_function`. The body stays generic with type parameters like `$*Optional<Self>`, which is correct since all callers share the same shared symbol and apply their own concrete types through the substitution map on the `partial_apply`.

## Tests
Add SIL and executable tests demonstrating that ConstantCapturePropagation produces an ODR violation when specializing generic closures with different concrete type substitutions but the same constant captures.

The SIL test provides a minimal reproducer: two callers instantiate the same generic closure with UInt8 and Int respectively, both capturing constant `radix=10`. With `-enable-sil-verify-all`, the verifier catches the type mismatch in the specialized function body.

The executable test exercises the real-world scenario through `FixedWidthInteger.init?(_:radix:)`, where the miscompile causes Int and `Int32` parsing to return garbage values because the closure body was baked with `UInt8` type metadata.

Fixes: https://github.com/swiftlang/swift/issues/87917

[Assisted-by](https://t.ly/Dkjjk): [Claude Opus 4.6](https://www.anthropic.com/news/claude-opus-4-6)

cc @drodriguez @kyulee-com

### CODE REVIEW

**Comment by DataCorrupted** [comment]
@swift-ci  Please test

File: test/SILOptimizer/constant_capture_propagation_odr.swift [hunk 1]
```diff
@@ -0,0 +1,30 @@
+// RUN: %empty-directory(%t)
+// RUN: %target-build-swift -Osize -Xllvm -sil-disable-pass=GenericSpecializer -Xfrontend -sil-verify-none -module-name=test %s -o %t/a.out
```
Comment (eeckstein) [inline test/SILOptimizer/constant_capture_propagation_odr.swift]: Why do we need `-sil-verify-none`?

**Review by eeckstein — APPROVED** [review]
Thanks!
lgtm

File: test/SILOptimizer/constant_capture_propagation_odr.swift (hunk 1 above)
Comment (DataCorrupted) [reply test/SILOptimizer/constant_capture_propagation_odr.swift]: So the executable can build successfully without the fix

Comment (DataCorrupted) [reply test/SILOptimizer/constant_capture_propagation_odr.swift]: Added the verifier back

**Comment by DataCorrupted** [comment]
@swift-ci Please test

**Comment by DataCorrupted** [comment]
@swift-ci  Please test

**Comment by DataCorrupted** [comment]
@swift-ci Please test

**Comment by eeckstein** [comment]
I merged another fix for ConstantCapturePropagation right now: https://github.com/swiftlang/swift/pull/87977.
This was blocking CI, so I decided to merge it before your PR.
The merge conflict should be easily resolvable.

**Comment by DataCorrupted** [comment]
@swift-ci Please test

**Comment by DataCorrupted** [comment]
@eeckstein  @drodriguez The test passed! Nice, can you help me merge it pls?

**Comment by drodriguez** [comment]
@eeckstein since this affects the 6.3 branch and Xcode 26.4 beta 3, should a cherry-pick be requested to that branch?

File: test/SILOptimizer/constant_capture_propagation_odr.sil [hunk 2]
```diff
@@ -0,0 +1,66 @@
+// RUN: %target-sil-opt -sil-print-types -enable-sil-verify-all %s -constant-capture-propagation | %FileCheck %s
```
Comment (finagolfin) [inline test/SILOptimizer/constant_capture_propagation_odr.sil:1]: This new test [crashes `sil-opt` when run for 32-bit Android armv7](https://ci.swift.org/job/swift-PR-swift-sdk-for-android/18/consoleText), can you take a look?

Comment (DataCorrupted) [reply test/SILOptimizer/constant_capture_propagation_odr.sil:1]: I'll take a look and ping you when I send a fixing PR, `%3 = struct $Int (%2 : $Builtin.Int64)` probably won't work on 32-bit

Comment (DataCorrupted) [reply test/SILOptimizer/constant_capture_propagation_odr.sil:1]: https://github.com/swiftlang/swift/pull/88076

**Comment by eeckstein** [comment]
> @eeckstein since this affects the 6.3 branch and Xcode 26.4 beta 3, should a cherry-pick be requested to that branch?

yes, let's put up a cherry-pick PR for `release/6.3`. Though I don't know if this gets accepted or in which Xcode release the fix might land.

**Comment by eeckstein** [comment]
> yes, let's put up a cherry-pick PR for release/6.3.

@DataCorrupted could you do that? Please not that release cherry-pick PRs need a template in the description (see existing PRs for examples)

**Comment by DataCorrupted** [comment]
@eeckstein  I can try to cherry-pick, I've not done that before. 

IIUC there are three PRs that needs to be cherry-picked, correct?

- https://github.com/swiftlang/swift/pull/87977 : (Your PR) Fix SIL Verifier
- https://github.com/swiftlang/swift/pull/87916 : (This PR) Fix ODR violation
- https://github.com/swiftlang/swift/pull/88076 : Fixing test
