### PR TITLE
Sema: Emit diagnostics when walking into collection literals with defaulted types

### LINKED ISSUE #60011: `collection literal could only be inferred to` diagnostic not shown in the presence of a contextual type
When a heterogeneous array literal could only be inferred to have type `[Any]`, the compiler humbly states that this may not match our expectation:

```swift
let array = [1, "Swift"] // error: heterogeneous collection literal could only be inferred to '[Any]'; add explicit type annotation if this is intentional
```

However, this never seems to happen in the presence of a contextual type:

```swift
let array: any Sequence = [1, "Swift"] // OK?
```

**Expected behavior**
The compiler should not assume that a contextual type other than `[Any]` or, perhaps, `[Any?]` makes the inferred element type any more intentional. In this case, the error should be downgraded to a warning for source compatibility.

**Environment**
Swift version 5.8-dev (LLVM 116acf4edcf4f06, Swift d565ba5084a169d)

### PR DESCRIPTION
**Pull request by simanerush**
Resolves #60011

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test macOS

File: test/Constraints/array_literal.swift [hunk 1]
```diff
@@ -155,6 +155,13 @@ func defaultToAny(i: Int, s: String) {
 
   let a6 = [B(), C()]
   let _: Int = a6 // expected-error{{value of type '[A]'}}
+  
+  let a7: some Collection = [1, "Swift"]
+  // expected-warning@-1{{heterogeneous collection literal could only be inferred to '[Any]'; add explicit type annotation if this is intentional}}
```
Comment (LucianoPAlmeida) [inline test/Constraints/array_literal.swift:160]: We are emitting the fix-it, so we need to verify them as well :)

Comment (simanerush) [reply test/Constraints/array_literal.swift:160]: Oh, you're right! Will fix that :)

Comment (simanerush) [reply test/Constraints/array_literal.swift:160]: Sure, I will add a check for fixit emission

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test macOS

File: lib/Sema/MiscDiagnostics.cpp [hunk 2]
```diff
@@ -1313,11 +1323,26 @@ static void diagSyntacticUseRestrictions(const Expr *E, const DeclContext *DC,
...
+    }
+
+    E = conversion->getSubExpr();
+  }
+
+  if (auto collection = dyn_cast<CollectionExpr>(E)) {
     if (collection->isTypeDefaulted()) {
-      Walker.checkTypeDefaultedCollectionExpr(
-        const_cast<CollectionExpr *>(collection));
+      Walker.diagnoseTypeDefaultedCollectionExpr(
```
Comment (xedin) [inline lib/Sema/MiscDiagnostics.cpp:1344]: I think we should go one step farther with this and lift the check to somewhere around https://github.com/apple/swift/blob/main/lib/Sema/MiscDiagnostics.cpp#L133 which would mean that inner defaulted collections are going to be diagnosed as well ad we don't have to look through `ImplicitConversionExpr` explicitly since that would already be handled by the walker.

Here are a couple of examples of what needs to warn but doesn't at the moment:

```
func test<T>(_: [T]) {}

test([]) // should warn because T is defaulted to Any 
test([1, nil, ""]) // same issue
```

and

```
func test<T>() -> [T]? {
  []
}

_ = test() ?? [] // same here T is defaulted to Any from literal collection
```

**Review by xedin — CHANGES_REQUESTED** [review]

File: lib/Sema/MiscDiagnostics.cpp (hunk 2 above)
Comment (LucianoPAlmeida) [reply lib/Sema/MiscDiagnostics.cpp:1344]: @xedin 
Would this be another example as well?
```swift
func f(_ b: Bool) {
  let _ = b ? [] : []
}
```

Comment (xedin) [reply lib/Sema/MiscDiagnostics.cpp:1344]: Yes!

Comment (simanerush) [reply lib/Sema/MiscDiagnostics.cpp:1344]: Thank you for the review! Once I moved the functionality to the upper-level, I ran into a problem where inner arrays in expressions like `let a: [Any]  = [1, nil, [2, "Swift"]]` are diagnosed, even though they shouldn't. I'm working on restricting emission of any diagnostics in this case, since I can't think of any better solution.

Comment (simanerush) [reply lib/Sema/MiscDiagnostics.cpp:1344]: That happens because we're walking into the first array and then we see that nested array, which is inferred as `[Any]` and diagnostics gets emitted.

Comment (xedin) [reply lib/Sema/MiscDiagnostics.cpp:1344]: That is actually correct, the second array is heterogeneous as well.

Comment (simanerush) [reply lib/Sema/MiscDiagnostics.cpp:1344]: Okay, but I thought we can't emit diagnostics for nested stuff in arrays (at least my mentor told me so)

Comment (xedin) [reply lib/Sema/MiscDiagnostics.cpp:1344]: I don’t see why not in this case but you could just check whether `Parent` is a collection expression and if so - skip this diagnostic.

Comment (xedin) [reply lib/Sema/MiscDiagnostics.cpp:1344]: Maybe only ASTVisitor tracks Parent so you might need to write some code it track it in here.

Comment (simanerush) [reply lib/Sema/MiscDiagnostics.cpp:1344]: Yea, this makes sense!

Comment (xedin) [reply lib/Sema/MiscDiagnostics.cpp:1344]: Ok, I was got it right - `ASTWalker` has `Parent` it should be easy. If you are curious about the direct tracking good example of such pattern could be found in PreCheckExpr which needs to track current declaration context because it walks into closures. 

So before walking into the closure body it would switch `DC` to a closure - https://github.com/apple/swift/blob/main/lib/Sema/PreCheckExpr.cpp#L1469 

and then when walking out back to its parent -  https://github.com/apple/swift/blob/main/lib/Sema/PreCheckExpr.cpp#L1310-L1313

Comment (AnthonyLatsis) [reply lib/Sema/MiscDiagnostics.cpp:1344]: > I thought we can't emit diagnostics for nested stuff in arrays (at least my mentor told me so)

For context, this was me trying to make sense of [this](https://github.com/apple/swift/blob/6c7e8c4c5bdc3c0086a4f149b39efe526a8744c5/lib/Sema/MiscDiagnostics.cpp#L425) comment. It seems like we do not want to diagnose a nested collection literal if we already diagnosed the outer literal, but I am not certain.

Comment (xedin) [reply lib/Sema/MiscDiagnostics.cpp:1344]: IMHO it just states what implementation does which doesn’t account for the fact that the types flow both ways and erasure/defaulting might happen in the inner collection without outer being defaulted or erased…

Comment (simanerush) [reply lib/Sema/MiscDiagnostics.cpp]: @xedin I just pushed new version of the changes. The check had been lifted to Walker

Comment (AnthonyLatsis) [reply lib/Sema/MiscDiagnostics.cpp]: I don't see why we shouldn't diagnose nested literals either, even when both the outer and inner literals are defaulted.

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test macOS

File: lib/Sema/MiscDiagnostics.cpp [hunk 3]
```diff
@@ -420,23 +460,34 @@ static void diagSyntacticUseRestrictions(const Expr *E, const DeclContext *DC,
...
-      // produce an error with a fixit to add the type as an explicit
-      // annotation.
-      if (c->getNumElements() == 0)
-        Ctx.Diags.diagnose(c->getLoc(), diag::collection_literal_empty)
-          .highlight(c->getSourceRange());
-      else {
+    /// Diagnose a collection literal with a defaulted type such as \c [Any].
+    static void diagnoseTypeDefaultedCollectionExpr(CollectionExpr *c,
+                                                    ASTContext &ctx,
+                                                    bool diagnoseAsWarning) {
```
Comment (xedin) [inline lib/Sema/MiscDiagnostics.cpp:466]: Nit: let's call this `downgradeToWarning`.

File: lib/Sema/MiscDiagnostics.cpp [hunk 4]
```diff
@@ -105,13 +105,35 @@ static void diagSyntacticUseRestrictions(const Expr *E, const DeclContext *DC,
     SmallPtrSet<DeclRefExpr*, 4> AlreadyDiagnosedBitCasts;
 
     bool IsExprStmt;
+    bool ShouldDiagnoseTypeDefaultedCollectionAsWarning;
```
Comment (xedin) [inline lib/Sema/MiscDiagnostics.cpp:108]: I don't think this is necessary because `ASTWalker` has a `Parent` which could be used to determine this when `CollectionExpr` is found - if there is no parent or it's semantically meaningless - diagnose as an error, otherwise diagnose as a warning.

**Review by xedin — CHANGES_REQUESTED** [review]

File: lib/Sema/MiscDiagnostics.cpp (hunk 4 above)
Comment (AnthonyLatsis) [reply lib/Sema/MiscDiagnostics.cpp:108]: What if there's sth semantically meaningful surrounding a semantically meaningless parent, like
 ```swift
let _ = (true, ([1, "Swift"]))
```
? That would have to be a warning.

Comment (xedin) [reply lib/Sema/MiscDiagnostics.cpp:108]: Too bad ASTWalker doesn't carry a depth but it should be easy to add that and increase for each semantically significant expression...

Comment (AnthonyLatsis) [reply lib/Sema/MiscDiagnostics.cpp:108]: Right, I was thinking about a `hasReachedValueProvidingExpr` flag.

Comment (xedin) [reply lib/Sema/MiscDiagnostics.cpp:108]: Something like that sounds good to me!

Comment (simanerush) [reply lib/Sema/MiscDiagnostics.cpp]: @xedin I just pushed new changes. Could you take a look?

Comment (xedin) [reply lib/Sema/MiscDiagnostics.cpp]: Absolutely!

File: lib/Sema/MiscDiagnostics.cpp [hunk 5]
```diff
@@ -124,6 +126,17 @@ static void diagSyntacticUseRestrictions(const Expr *E, const DeclContext *DC,
     bool shouldWalkIntoTapExpression() override { return false; }
 
     std::pair<bool, Expr *> walkToExprPre(Expr *E) override {
+
+      if (auto collection = dyn_cast<CollectionExpr>(E)) {
+        if (collection->isTypeDefaulted()) {
+          // Diagnose type defaulted collection literals in subexpressions as
+          // warnings to preserve source compatibility.
+          diagnoseTypeDefaultedCollectionExpr(
+              const_cast<CollectionExpr *>(collection), Ctx,
```
Comment (xedin) [inline lib/Sema/MiscDiagnostics.cpp:135]: Why do we need a `const_cast<>` here the original `E` is not `const` right?

File: test/Constraints/array_literal.swift [hunk 6]
```diff
@@ -145,16 +145,48 @@ func defaultToAny(i: Int, s: String) {
...
   let _: [Any] = [1, [2, [3]]]
+  // expected-warning@-1{{heterogeneous collection literal could only be inferred to '[Any]'; add explicit type annotation if this is intentional}}
   
   let _: [Any?] = [1, "a", nil, 3.5]
   let _: [Any?] = [1, "a", nil, [3.5, 3.7, 3.9]]
   let _: [Any?] = [1, "a", nil, [3.5, "b", nil]]
+  // expected-warning@-1{{heterogeneous collection literal could only be inferred to '[Any?]'; add explicit type annotation if this is intentional}}
   let _: [Any?] = [1, [2, [3]]]
+  // expected-warning@-1{{heterogeneous collection literal could only be inferred to '[Any]'; add explicit type annotation if this is intentional}}
```
Comment (xedin) [inline test/Constraints/array_literal.swift:157]: @simanerush @AnthonyLatsis I think we don't want to diagnose cases like this one (note that it's different from the following one where inner collection literal is heterogeneous) and the ones where `[]` is used in `return` i.e. https://github.com/apple/swift/pull/60323/files#diff-55b6c1da2887f7323cf5ddb64f0a2add1f0b6a1392a51113d20bbbd04f8ccfc7R12 because there is a contextual type in this case so it's equivalent to `as [Any]` or `as [Any?]` which we suggest to silence the warning.

File: test/expr/cast/objc_coerce_array.swift [hunk 7]
```diff
@@ -7,9 +7,13 @@ var x = 1
 _ = [x] as [NSNumber]
 
 _ = ["x":["y":"z","a":1]] as [String : [String : AnyObject]]
+// expected-warning@-1{{heterogeneous collection literal could only be inferred to '[String : AnyObject]'; add explicit type annotation if this is intentiona}}
```
Comment (xedin) [inline test/expr/cast/objc_coerce_array.swift:10]: This is another instance of `let _: [Any?] = [1, [2, [3]]]` - we shouldn't diagnose it because there is an explicit coercion here.

**Review by xedin — CHANGES_REQUESTED** [review]

File: test/expr/cast/objc_coerce_array.swift (hunk 7 above)
Comment (AnthonyLatsis) [reply test/expr/cast/objc_coerce_array.swift:10]: This one is interesting. Is the inner literal being marked as defaulted by mistake?

File: test/Constraints/array_literal.swift (hunk 6 above)
Comment (AnthonyLatsis) [reply test/Constraints/array_literal.swift:157]: I think the compiler is correct in this particular case because there is no explicit element type specified for `[2, [3]]`, which is defaulted to `[Any]` and coerced to `Any?` as an element of the outer `[Any?]` literal.

Comment (simanerush) [reply test/Constraints/array_literal.swift:157]: Agree. This change originated from @xedin's point earlier on about nested collection literals with a defaulted type.

Comment (xedin) [reply test/Constraints/array_literal.swift:157]: Ah yes, I missed that, sorry, this one is indeed correct

Comment (AnthonyLatsis) [reply test/Constraints/array_literal.swift:157]: IMO we are also correct to warn on `return []` for the same reason. `func f() -> some Collection { return [] }` is analogous to `let _: some Collection = []`.

File: test/expr/cast/objc_coerce_array.swift (hunk 7 above)
Comment (xedin) [reply test/expr/cast/objc_coerce_array.swift:10]: Would we warn about `let _: [Any] = []`?

File: test/Constraints/array_literal.swift (hunk 6 above)
Comment (xedin) [reply test/Constraints/array_literal.swift:157]: Would we warn about `let _: [Any] = []`?

Comment (xedin) [reply test/Constraints/array_literal.swift:157]: `some Collection` case is different really because the underlying type of opaque has to be inferred from the result expression, so it's reasonable to warn there but in case where result is a concrete type I don't think so.

Comment (simanerush) [reply test/Constraints/array_literal.swift:157]: @xedin I can't find an example of emission of warning diagnostics in a case of a function with a concrete type -- all tests have an opaque type. Could you maybe point to a case where we emit diagnostics with a concrete type function?

Comment (AnthonyLatsis) [reply test/Constraints/array_literal.swift:157]: > Would we warn about `let _: [Any] = []`?

We should not.

Comment (xedin) [reply test/Constraints/array_literal.swift:157]: @simanerush It must have been an older commit or something but I could swear I saw a test-case that got updated with the warning that returned `[Any]` similar to this one:

```
func test() -> [Any] {
  []
}
```

Comment (xedin) [reply test/Constraints/array_literal.swift:157]: Since it's not in the changes anymore I think we can land this with a `// FIXME` comment for all the test-cases mentioned in https://github.com/apple/swift/pull/60323/files#r942866744. That could be addressed separately.

**Review by xedin — APPROVED** [review]

File: lib/Sema/MiscDiagnostics.cpp [hunk 8]
```diff
@@ -420,23 +438,34 @@ static void diagSyntacticUseRestrictions(const Expr *E, const DeclContext *DC,
...
+                                                    ASTContext &ctx,
+                                                    bool downgradeToWarning) {
+      // Produce a diagnostic with a fixit to add the defaulted type as an
+      // explicit annotation.
+      auto &diags = ctx.Diags;
+
+      if (c->getNumElements() == 0) {
+        InFlightDiagnostic inFlight =
+            diags.diagnose(c->getLoc(), diag::collection_literal_empty);
+        inFlight.highlight(c->getSourceRange());
```
Comment (LucianoPAlmeida) [inline lib/Sema/MiscDiagnostics.cpp:452]: I see we produce a fix-it in the non-empty case. Should a fix-it be produced here as well?

File: test/Constraints/array_literal.swift [hunk 9]
```diff
@@ -145,16 +145,48 @@ func defaultToAny(i: Int, s: String) {
...
   let _: [Any?] = [1, nil, [2, nil, [3]]]
+  // expected-warning@-1{{heterogeneous collection literal could only be inferred to '[Any?]'; add explicit type annotation if this is intentional}}
 
   let a6 = [B(), C()]
   let _: Int = a6 // expected-error{{value of type '[A]'}}
+  
+  let a7: some Collection = [1, "Swift"]
+  // expected-warning@-1{{heterogeneous collection literal could only be inferred to '[Any]'; add explicit type annotation if this is intentional}} {{41-41= as [Any]}}
+  let _: (any Sequence)? = [1, "Swift"]
+  // expected-warning@-1{{heterogeneous collection literal could only be inferred to '[Any]'; add explicit type annotation if this is intentional}}
```
Comment (LucianoPAlmeida) [inline test/Constraints/array_literal.swift:167]: Should we verify the fix-it's for all test cases? I would look a bit redundant in that case, so maybe that was intentional?

File: test/Constraints/array_literal.swift (hunk 6 above)
Comment (AnthonyLatsis) [reply test/Constraints/array_literal.swift:157]: > ```swift
> func test() -> [Any] {
>   []
> }
> ```
@simanerush Could you add test cases for this and `let _: [Any] = []` as you fix the conflict?

File: test/Constraints/array_literal.swift (hunk 9 above)
Comment (AnthonyLatsis) [reply test/Constraints/array_literal.swift:167]: I believe already added fix-it verifications suffice. These changes do not affect the emission of the fix-it, which in itself is just a trivial insertion.

Comment (LucianoPAlmeida) [reply test/Constraints/array_literal.swift:167]: Makes sense! Thanks @AnthonyLatsis =]

File: lib/Sema/MiscDiagnostics.cpp (hunk 8 above)
Comment (LucianoPAlmeida) [reply lib/Sema/MiscDiagnostics.cpp:452]: I guess it makes sense, I just asked because to me we were suggesting explicit type but missing something actionable as the other case. Maybe could offer a fix-it with an element IDE placeholder e.g. `as [<#Element#>]`? But I agree is ok not emitting, that is just something to think about.

File: test/Constraints/array_literal.swift (hunk 6 above)
Comment (simanerush) [reply test/Constraints/array_literal.swift:157]: @AnthonyLatsis sure!

File: lib/Sema/MiscDiagnostics.cpp (hunk 8 above)
Comment (AnthonyLatsis) [reply lib/Sema/MiscDiagnostics.cpp:452]: > Maybe could offer a fix-it with an element IDE placeholder e.g. `as [<#Element#>]`?

Yeah, something along the lines of `; did you mean this to be an instance of 'Swift.Array'?` plus this fix-it would probably be helpful.

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test
