### PR TITLE
[Diagnostics] Add fix-it to `@main` struct without main static function.

### LINKED ISSUE #58518: No Fix-It for `@main` struct without main static function
When compiling the following code, you get an error message: `'Foo' is annotated with @main and must provide a main static function of type () -> Void, () throws -> Void, () async -> Void, or () async throws -> Void`

```swift
@main struct Foo {
}
```

We should offer a fix-it to add

```swift
static func main() {
  <#code#>
}
```

I’m open to whether we should also suggest the `async` and `throws` variations but IMHO just offering the base variation without any modifiers would be a good starting point.

rdar://92511524

### PR DESCRIPTION
**Pull request by CrazyFanFan**
Resolves https://github.com/swiftlang/swift/issues/58518

It will create four different fix-its:

```swift
    static func main() {
        <#code#>
    }
 
    static func main() throws {
        <#code#>
    }
 
    static func main() async {
        <#code#>
    }
 
    static func main() async throws {
        <#code#>
    }
```

### CODE REVIEW

File: lib/Sema/TypeCheckAttr.cpp [hunk 1]
```diff
@@ -3081,6 +3082,37 @@ synthesizeMainBody(AbstractFunctionDecl *fn, void *arg) {
   return std::make_pair(body, /*typechecked=*/false);
 }
 
+llvm::SmallString<128> generateMainFunctionText(ASTContext &C, Decl *decl,
```
Comment (AnthonyLatsis) [inline lib/Sema/TypeCheckAttr.cpp]:
```suggestion
static llvm::SmallString<128> generateMainFunctionText(ASTContext &C, Decl *decl,
```

File: lib/Sema/TypeCheckAttr.cpp [hunk 2]
```diff
@@ -3210,9 +3242,33 @@ SynthesizeMainFunctionRequest::evaluate(Evaluator &evaluator,
...
+    auto location = attr->getLocation();
+    auto fixLocation = braces.Start;
+
+    context.Diags.diagnose(location, diag::attr_MainType_without_main, nominal,
+                           hasAsyncSupport);
+
+    context.Diags.diagnose(location, diag::note_add_main_sync)
+        .fixItInsertAfter(
+            fixLocation,
+            generateMainFunctionText(context, nominal, false, false).str());
```
Comment (AnthonyLatsis) [inline lib/Sema/TypeCheckAttr.cpp]:
```suggestion
            generateMainFunctionText(context, nominal, /* isThrows=*/false, /*isAsync=*/false).str());
```

Let’s do this for all `generateMainFunctionText` calls for clarity.

File: lib/Sema/TypeCheckAttr.cpp (hunk 1 above)
Comment (AnthonyLatsis) [inline lib/Sema/TypeCheckAttr.cpp]:
```suggestion
llvm::SmallString<128> generateMainFunctionText(ASTContext &C, NominalTypeDecl *parentDecl,
```

File: lib/Sema/TypeCheckAttr.cpp [hunk 3]
```diff
@@ -3081,6 +3082,37 @@ synthesizeMainBody(AbstractFunctionDecl *fn, void *arg) {
   return std::make_pair(body, /*typechecked=*/false);
 }
 
+llvm::SmallString<128> generateMainFunctionText(ASTContext &C, Decl *decl,
+                                                bool isThrows, bool isAsync) {
+  // Prepare the indent (same as `printRequirementStub`)
+  StringRef ExtraIndent;
+  StringRef CurrentIndent = Lexer::getIndentationForLine(
+      C.SourceMgr, decl->getStartLoc(), &ExtraIndent);
```
Comment (AnthonyLatsis) [inline lib/Sema/TypeCheckAttr.cpp]: We should pass the sum indent to the printer instead.
```
std::string MethodIndent = (CurrentIndent + ExtraIndent).str();
```

Then you won’t have to explicitly print any indents except for the placeholder’s extra indent.

File: lib/Sema/TypeCheckAttr.cpp [hunk 4]
```diff
@@ -3210,9 +3242,33 @@ SynthesizeMainFunctionRequest::evaluate(Evaluator &evaluator,
...
-                           diag::attr_MainType_without_main,
-                           nominal, hasAsyncSupport);
+
+    auto location = attr->getLocation();
+    auto fixLocation = braces.Start;
+
+    context.Diags.diagnose(location, diag::attr_MainType_without_main, nominal,
+                           hasAsyncSupport);
+
+    context.Diags.diagnose(location, diag::note_add_main_sync)
```
Comment (AnthonyLatsis) [inline lib/Sema/TypeCheckAttr.cpp:3254]: Could you add a comment for what we’re doing here after emitting the primary diagnostic?

File: lib/Sema/TypeCheckAttr.cpp [hunk 5]
```diff
@@ -3081,6 +3082,37 @@ synthesizeMainBody(AbstractFunctionDecl *fn, void *arg) {
...
+  StringRef ExtraIndent;
+  StringRef CurrentIndent = Lexer::getIndentationForLine(
+      C.SourceMgr, decl->getStartLoc(), &ExtraIndent);
+
+  llvm::SmallString<128> Text;
+  llvm::raw_svector_ostream OS(Text);
+  ExtraIndentStreamPrinter Printer(OS, CurrentIndent);
+
+  Printer.printNewline();
+  Printer.printIndent();
```
Comment (AnthonyLatsis) [inline lib/Sema/TypeCheckAttr.cpp]: `printNewline()` already prints the given indent.

**Review by AnthonyLatsis — COMMENTED** [review]
Nice!

Please add a test case with a nested `@main struct` to make sure we got the indents right.

**Comment by CrazyFanFan** [comment]
@AnthonyLatsis  Thanks for the review! All issues have been addressed based on your feedback.

File: test/attr/ApplicationMain/attr_main_instance_nested.swift [hunk 6]
```diff
@@ -0,0 +1,13 @@
+// RUN: %target-swift-frontend -typecheck -parse-as-library -verify %s
+
+enum Nested {
```
Comment (AnthonyLatsis) [inline test/attr/ApplicationMain/attr_main_instance_nested.swift]: I would prefer it to be in the same file. It’s harder to miss that we’re already testing something this way, as long as the file is kept tidy and below a reasonable size bound.

File: lib/Sema/TypeCheckAttr.cpp [hunk 7]
```diff
@@ -3210,9 +3241,48 @@ SynthesizeMainFunctionRequest::evaluate(Evaluator &evaluator,
...
+
+    // Add `static func main() throws`
+    context.Diags.diagnose(location, diag::note_add_main_sync_throws)
+        .fixItInsertAfter(fixLocation, generateMainFunctionText(
+                                           context, nominal, /*isThrows*/ true,
+                                           /*isAsync*/ false)
+                                           .str());
+
+    // if async support, there are two addtional fix-it
+    if (hasAsyncSupport) {
```
Comment (AnthonyLatsis) [inline lib/Sema/TypeCheckAttr.cpp]: This one is a bit superfluous IMO.

File: lib/Sema/TypeCheckAttr.cpp [hunk 8]
```diff
@@ -3210,9 +3241,48 @@ SynthesizeMainFunctionRequest::evaluate(Evaluator &evaluator,
...
+
+    auto location = attr->getLocation();
+    auto fixLocation = braces.Start;
+
+    context.Diags.diagnose(location, diag::attr_MainType_without_main, nominal,
+                           hasAsyncSupport);
+
+    // Add some fix-it to help generate the static main function.
+
+    // Add `static func main()`
```
Comment (AnthonyLatsis) [inline lib/Sema/TypeCheckAttr.cpp]: How about 
```suggestion
    // Offer fix-its to add the `main` function for different combinations of
    // effects, starting with no effects.
```

File: lib/Sema/TypeCheckAttr.cpp [hunk 9]
```diff
@@ -3081,6 +3082,36 @@ synthesizeMainBody(AbstractFunctionDecl *fn, void *arg) {
...
+
+  Printer.printNewline();
+
+  Printer << "static func main() ";
+  if (isAsync)
+    Printer << "async ";
+  if (isThrows)
+    Printer << "throws ";
+
+  /// Print the "{ <#code#> }" placeholder body
```
Comment (AnthonyLatsis) [inline lib/Sema/TypeCheckAttr.cpp]:
```suggestion
  // Print the "{ <#code#> }" placeholder body.
```

**Review by AnthonyLatsis — COMMENTED** [review]
One more round. Are you using `clang-format`?

**Comment by CrazyFanFan** [comment]
> One more round. Are you using `clang-format`?
 
@AnthonyLatsis  Yes, I ran `clang-format` before submitting:

```shell
git-clang-format HEAD~2
git add .
git commit --amend --no-edit
```
All other review feedback has been addressed as well.

File: lib/Sema/TypeCheckAttr.cpp [hunk 10]
```diff
@@ -3081,6 +3082,36 @@ synthesizeMainBody(AbstractFunctionDecl *fn, void *arg) {
...
+    Printer << "async ";
+  if (isThrows)
+    Printer << "throws ";
+
+  // Print the "{ <#code#> }" placeholder body
+  Printer << "{\n";
+  Printer.printIndent();
+  Printer << ExtraIndent << getCodePlaceholder();
+  Printer.printNewline();
+  Printer << "}\n";
```
Comment (ahoppen) [inline lib/Sema/TypeCheckAttr.cpp:3110]: Nitpick: Should we add two newlines here to separate the generated `main` function from the remaining body using a newline?

**Review by ahoppen — APPROVED** [review]
Very nice. Looking forward to using this 🤩

File: lib/Sema/TypeCheckAttr.cpp (hunk 10 above)
Comment (AnthonyLatsis) [reply lib/Sema/TypeCheckAttr.cpp:3110]: I don’t have a clear preference. Ideally (not in this PR!), I imagine a `formatCodeForInsertion` function that parses a given string into a SwiftSyntax tree and formats it using SwiftBasicFormat (indentation, separation) for insertion at a given location.

File: lib/Sema/TypeCheckAttr.cpp (hunk 7 above)
Comment (AnthonyLatsis) [reply lib/Sema/TypeCheckAttr.cpp]: Sorry, I meant the comment is superfluous, not the `if`. The `if` is correct!

File: lib/Sema/TypeCheckAttr.cpp (hunk 9 above)
Comment (AnthonyLatsis) [reply lib/Sema/TypeCheckAttr.cpp]: Forgot the full stop.

File: lib/Sema/TypeCheckAttr.cpp (hunk 10 above)
Comment (ahoppen) [reply lib/Sema/TypeCheckAttr.cpp:3110]: The way that Fix-Its and refactorings are designed to work is that the editor applies its own indentation after applying the Fix-It refactoring because it can really know about the user’s preferences (the compiler can only guess based on existing lines). But whether to add a newline is currently an opinionated decision by the compiler.

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test Linux

**Comment by AnthonyLatsis** [comment]
```
01:57:17  Failed Tests (6):
01:57:17    Swift(linux-x86_64) :: attr/ApplicationMain/attr_main_arguments.swift
01:57:17    Swift(linux-x86_64) :: attr/ApplicationMain/attr_main_dynamicCallable.swift
01:57:17    Swift(linux-x86_64) :: attr/ApplicationMain/attr_main_dynamicMemberLookup.swift
01:57:17    Swift(linux-x86_64) :: attr/ApplicationMain/attr_main_extension_nofunc.swift
01:57:17    Swift(linux-x86_64) :: attr/ApplicationMain/attr_main_return.swift
01:57:17    Swift(linux-x86_64) :: attr/ApplicationMain/attr_main_struct_from_two_protocols_one_missing.swift
```

Let me know if you need help running the tests locally.

File: lib/Sema/TypeCheckAttr.cpp (hunk 10 above)
Comment (CrazyFanFan) [reply lib/Sema/TypeCheckAttr.cpp:3110]: Thank you for the discussion.

I've looked at other **fix-it** instances in **[TypeCheckProtocol.cpp](https://github.com/swiftlang/swift/blob/4b9ef8c53c988ce91e57b1e03dbb00c774fbf56d/lib/Sema/TypeCheckProtocol.cpp#L3787)** and **[TypeCheckDistributed.cpp](https://github.com/swiftlang/swift/blob/4b9ef8c53c988ce91e57b1e03dbb00c774fbf56d/lib/Sema/TypeCheckDistributed.cpp#L298)**, and found that they only add a single `\n` at the end of inserted code, without additional blank lines.

Considering this, and editors applying indentation based on user preferences, I'm inclined to stay consistent with existing practices and not insert extra blank lines.

Of course, if you have any other thoughts, I'm open to further discussion.

**Comment by CrazyFanFan** [comment]
> ```
> 01:57:17  Failed Tests (6):
> 01:57:17    Swift(linux-x86_64) :: attr/ApplicationMain/attr_main_arguments.swift
> 01:57:17    Swift(linux-x86_64) :: attr/ApplicationMain/attr_main_dynamicCallable.swift
> 01:57:17    Swift(linux-x86_64) :: attr/ApplicationMain/attr_main_dynamicMemberLookup.swift
> 01:57:17    Swift(linux-x86_64) :: attr/ApplicationMain/attr_main_extension_nofunc.swift
> 01:57:17    Swift(linux-x86_64) :: attr/ApplicationMain/attr_main_return.swift
> 01:57:17    Swift(linux-x86_64) :: attr/ApplicationMain/attr_main_struct_from_two_protocols_one_missing.swift
> ```
> 
> Let me know if you need help running the tests locally.

@AnthonyLatsis  Thank you for the detailed test failure information.​

All issues you mentioned have been fixed. Additionally, all tests in **test/attr/ApplicationMain/** have been run in my local before this update, addressing the previously overlooked cases.​

Please let me know if you spot anything else or have further suggestions.​

File: lib/Sema/TypeCheckAttr.cpp (hunk 10 above)
Comment (ahoppen) [reply lib/Sema/TypeCheckAttr.cpp:3110]: Thanks for finding those examples. In that case let’s stick with the existing practice of only adding one newline. 👍🏽

**Review by AnthonyLatsis — APPROVED** [review]
Thanks! Please tidy up your history before we go for merge.

P.S. You are welcome to add a test for `if (hasAsyncSupport) {` in a follow-up.

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test Linux

**Comment by CrazyFanFan** [comment]
@AnthonyLatsis Hi,

Just to confirm: by tidying up history, do you mean amending/combining commits?
I’d like to add the test for `if (hasAsyncSupport)` but am unsure how to set up an Async-unsupported environment. Any tips?

Thanks!

**Comment by AnthonyLatsis** [comment]
> Just to confirm: by tidying up history, do you mean amending/combining commits?

In this case I mean squashing the "review feedback" commit into the original.

> I’d like to add the test for if (hasAsyncSupport) but am unsure how to set up an Async-unsupported environment. Any tips?

Try this (async is supported or can be deployed to platform versions aligned with 5.1 and onward):
```
// RUN: %target-typecheck-verify-swift -parse-as-library -target %target-swift-5.0-abi-triple

// REQUIRES: OS=macosx && CPU=x86_64

@main struct S {}
```

**Comment by CrazyFanFan** [comment]
I've squashed the "review feedback" commit into the original as suggested. I've also added the test for `if (hasAsyncSupport)`. Let me know if anything needs adjusting. 

Thanks！

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test macOS

**Comment by AnthonyLatsis** [comment]
FYI if you build the project without `--swift-darwin-supported-archs=arm64` you will also get a x86_64 stdlib and a `test-macosx-x86_64` directory that you can use to run these kinds of tests. You don’t need a x86_64 machine in this case.

**Review by AnthonyLatsis — APPROVED** [review]

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test Linux

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test Windows
