### PR TITLE
[Sema] Correct 'await' insertion fixIt

### LINKED ISSUE #65913: Compiler suggests a wrong insertion point for 'await' in `if let ...`.
**Description**
As you can see in the following code, the compiler suggests to write 'await' at the right of `let`, which is syntactically invalid.

**Steps to reproduce**

Try to compile the following code:

```swift
func f() async -> Int? { return 0 }
async let result = f()
if let result { print(result) }

/* COMPILER SAYS:

if-let-await.swift:3:8: error: expression is 'async' but is not marked with 'await'
if let result { print(result) }
      ^~~~~~
      await
if-let-await.swift:3:8: note: reference to async let 'result' is 'async'
if let result { print(result) }
      ^

 */

// FIX as above...
if let await result { print(result) } // ⛔️ Invalid Syntax

// Correct answer is...
if let result = await result { print(result) } // ✅

```

**Expected behavior**

Compiler suggests the correct answer described above.

**Environment**
- swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
- Xcode 14.3 / Build version 14E222b

### PR DESCRIPTION
**Pull request by jameesbrown**
Note this is a duplicate of a previously open pull request I'd closed accidentally: https://github.com/apple/swift/pull/71716
Resolves https://github.com/apple/swift/issues/65913

use fixItInsertAfter with the specialized fixIt given it is an implicit `DeclRefExpr`.

My reasoning is that I saw in ParseStmt.cpp, where we parse a shorthand optional binding we have:
```swift
else if (!ThePattern.getPtrOrNull()->getBoundName().empty()) {
    auto bindingName = DeclNameRef(ThePattern.getPtrOrNull()->getBoundName());
    auto loc = DeclNameLoc(ThePattern.getPtrOrNull()->getEndLoc());
    auto declRefExpr = new (Context) UnresolvedDeclRefExpr(bindingName,
                                                           DeclRefKind::Ordinary,
                                                           loc);
    
     declRefExpr->setImplicit();
     Init = makeParserResult(declRefExpr);
```.

### CODE REVIEW

File: lib/Sema/TypeCheckEffects.cpp [hunk 1]
```diff
@@ -3570,16 +3570,40 @@ class CheckEffectsCoverage : public EffectsHandlingWalker<CheckEffectsCoverage>
...
+        .warnUntilSwiftVersionIf(downgradeToWarning, 6)
+        .fixItInsertAfter(anchor->getStartLoc(),
+                          (" = await " + varDecl->getName().str()).str())
+        .highlight(anchor->getSourceRange());
+    } else {
+      Ctx.Diags.diagnose(anchor->getStartLoc(), diag::async_expr_without_await)
+        .warnUntilSwiftVersionIf(downgradeToWarning, 6)
+        .fixItInsert(awaitInsertLoc, "await ")
+        .highlight(anchor->getSourceRange());
+    }
```
Comment (LucianoPAlmeida) [inline lib/Sema/TypeCheckEffects.cpp:3606]: Nit: Can this be simplified? 
```suggestion
    auto diag = Ctx.Diags.diagnose(anchor->getStartLoc(), diag::async_expr_without_await)
        .warnUntilSwiftVersionIf(downgradeToWarning, 6)
        .highlight(anchor->getSourceRange());
    if (auto varDecl = findShorthandOptionalBinding(anchor)) {
        diag.fixItInsertAfter(anchor->getStartLoc(),
                          (" = await " + varDecl->getName().str()).str());
    } else {
        diag.fixItInsert(awaitInsertLoc, "await ");
    }
```

File: lib/Sema/TypeCheckEffects.cpp [hunk 2]
```diff
@@ -3570,16 +3570,40 @@ class CheckEffectsCoverage : public EffectsHandlingWalker<CheckEffectsCoverage>
...
         awaitInsertLoc = tryExpr->getSubExpr()->getStartLoc();
     }
+    
+    auto findShorthandOptionalBinding = [&](Expr *anchor) -> VarDecl * {
+      VarDecl *varDecl = nullptr;
+      if (!anchor->getType()->isOptional())
+        return nullptr;
+      anchor->forEachChildExpr([&](Expr *expr) -> Expr * {
+        if (auto *declRef = dyn_cast<DeclRefExpr>(expr)) {
+          if (declRef && declRef->isImplicit()) {
```
Comment (LucianoPAlmeida) [inline lib/Sema/TypeCheckEffects.cpp:3580]: Did all the tests passed? I am just curious to see if this can indeed detect narrowly the case we want for diagnostic and will not return unwanted cases such as `let a = anAsyncFuncThatReturnsOptional(value)` where the `CallExpr` returns optional and value is a optional variable. Although maybe `declRef->isImplicit()` may cover that, I wonder if we can be more specific on the context where we look for a `OptionalEvaluationExpr` for example instead of `anchor->getType()->isOptional()`. But that is just a guess for my side, maybe worth looking into it.

File: lib/Sema/TypeCheckEffects.cpp (hunk 1 above)
Comment (Jamezzzb) [reply lib/Sema/TypeCheckEffects.cpp:3606]: I like this idea but I tried it and I get the build error: `call to deleted constructor of 'InFlightDiagnostic'`

File: lib/Sema/TypeCheckEffects.cpp (hunk 2 above)
Comment (Jamezzzb) [reply lib/Sema/TypeCheckEffects.cpp:3603]: The tests do pass, I added another test case based off of `let a = anAsyncFuncThatReturnsOptional(value)` it passes as well. I see what you're saying but I'm not sure if `OptionalEvaluationExpr` applies here. For example, running `swift -dump-ast -O` on the following:
```swift
func test() async {
  async let result: String? = nil
  if let result {}
}
```
we get (not including all output here btw): 
```
(if_stmt range=[tmp.swift:3:3 - line:3:18]
        (pattern
          (pattern_optional_some implicit type='String?'
            (pattern_let implicit type='String'
              (pattern_named type='String' 'result')))
          (declref_expr implicit type='String?' location=tmp.swift:3:10 range=[tmp.swift:3:10 - line:3:10] decl=tmp.(file).test().result@tmp.swift:2:13 function_ref=unapplied))
        (brace_stmt range=[tmp.swift:3:17 - line:3:18])))))
```

You would get `OptionalEvaluationExpr` if you wrote something like:
```swift
struct S { let x: String }
func foo() {
  let s: S? = nil
  // the optional chaining here
  if let x = s?.x {
    print(x)
  }
}
```

File: lib/Sema/TypeCheckEffects.cpp (hunk 1 above)
Comment (Jamezzzb) [reply lib/Sema/TypeCheckEffects.cpp]: I was able to still simplify it _slightly_ by using `varDecl->getNameStr()`

File: lib/Sema/TypeCheckEffects.cpp (hunk 2 above)
Comment (LucianoPAlmeida) [reply lib/Sema/TypeCheckEffects.cpp:3603]: Yeah, it doesn't matter whether is an optiona_evaluation_expr or pattern_optional_some, I just remember wrong AST node, but point is we can be more explicit in the check to avoid false positives, checking only for "type is optional" would not guarantee we are in a let optional binding, so narrowing down to `pattern_optional_some` seems to be safer to the kind of pattern we want to detect here.

File: lib/Sema/TypeCheckEffects.cpp (hunk 1 above)
Comment (LucianoPAlmeida) [reply lib/Sema/TypeCheckEffects.cpp]: It should be possible to do something like this IIRC ...

Comment (Jamezzzb) [reply lib/Sema/TypeCheckEffects.cpp]: I managed to find a place in the codebase that does it like in your example, so will try this again.

File: lib/Sema/TypeCheckEffects.cpp (hunk 2 above)
Comment (Jamezzzb) [reply lib/Sema/TypeCheckEffects.cpp]: I was looking into this today, seems like we should be able to check for the pattern, but from this part of the code I haven't figured it out yet. Was trying `varDecl->getParentPattern()` but that doesn't seem to be what we want. Will continue trying of course, just wanted to give an update.

File: lib/Sema/TypeCheckEffects.cpp (hunk 1 above)
Comment (AnthonyLatsis) [reply lib/Sema/TypeCheckEffects.cpp]: > I like this idea but I tried it and I get the build error: `call to deleted constructor of 'InFlightDiagnostic'`

Because `highlight`, unlike `diagnose`, returns a reference, and the `auto` in `auto diag` gets deduced as a non-reference, which implies a copy or a call to the deleted copy constructor. `auto &diag` should work.

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test macOS

File: lib/Sema/TypeCheckEffects.cpp (hunk 1 above)
Comment (Jamezzzb) [reply lib/Sema/TypeCheckEffects.cpp]: Ah I see, thanks!

File: lib/Sema/TypeCheckEffects.cpp [hunk 3]
```diff
@@ -3593,16 +3593,38 @@ class CheckEffectsCoverage : public EffectsHandlingWalker<CheckEffectsCoverage>
...
+        return nullptr;
+      anchor->forEachChildExpr([&](Expr *expr) -> Expr * {
+        if (isa<DeclRefExpr>(expr) && expr->isImplicit()) {
+          varDecl = dyn_cast<VarDecl>(expr->getReferencedDecl().getDecl());
+          return nullptr;
+        }
+        return expr;
+      });
+      return varDecl;
+    };
```
Comment (AnthonyLatsis) [inline lib/Sema/TypeCheckEffects.cpp:3609]: I would tighten up this logic to look through all `ImplicitConversionExpr` layers instead of walking all children. I think even just the existence of an implicit `DeclRefExpr` is acceptable to conclude a shorthand optional binding. If not, the additional optional type condition would only get in the way of us knowing about it because there definitely is no case where an implicit `DeclRefExpr` cannot have optional type. Alternatively, a robust solution would be to implement `ASTWalker::walkToStmtConditionElementPre/Post`, and use that to store the condition element in the context object before descending into the implicit initializer expression ([`Context::InterpolatedString`](https://github.com/apple/swift/blob/5a546ed6b0c60ef522ec1898b63b8ec489a24542/lib/Sema/TypeCheckEffects.cpp#L2112) serves a similar purpose). `StmtConditionElement` has all the info needed to outline this case.

**Comment by AnthonyLatsis** [comment]
The failure is not related.

File: lib/Sema/TypeCheckEffects.cpp (hunk 3 above)
Comment (LucianoPAlmeida) [reply lib/Sema/TypeCheckEffects.cpp:3609]: I agree, that was somewhat the point on the previous comment, be more specific and robust on the check :)

**Comment by Jamezzzb** [comment]
@AnthonyLatsis @LucianoPAlmeida I've made some updates based off your suggestions. I first tried implementing a traversal through `StmtConditionElement`s by following `ArgumentList` as an example but somehow `free` was being called twice on my `Walker` and I was getting exceptions in my `walkToStmtConditionElementPost`. I didn't figure that part out but it did lead me to understand the code a bit more. I realized that what was making this more complicated  than it should be was that we were walking too far in the case of a shorthand optional binding. What I did was make a small change in `walkToAnchor`  so that we stop if we see an implicit `DeclRefExpr`. I then cleaned up the code a little by moving the creation of the fixit to its own function.

File: lib/Sema/TypeCheckEffects.cpp [hunk 4]
```diff
@@ -3581,27 +3583,43 @@ class CheckEffectsCoverage : public EffectsHandlingWalker<CheckEffectsCoverage>
...
+        }
     }
+    return std::make_pair(awaitInsertLoc, insertion);
+  }
 
+  void diagnoseUncoveredAsyncSite(const Expr *anchor) const {
+    auto asyncPointIter = uncoveredAsync.find(anchor);
+    if (asyncPointIter == uncoveredAsync.end())
+      return;
+    const std::vector<DiagnosticInfo> &errors = asyncPointIter->getSecond();
```
Comment (LucianoPAlmeida) [inline lib/Sema/TypeCheckEffects.cpp:3613]:
```suggestion
    const auto &errors = asyncPointIter->getSecond();
```

File: lib/Sema/TypeCheckEffects.cpp [hunk 5]
```diff
@@ -3581,27 +3583,43 @@ class CheckEffectsCoverage : public EffectsHandlingWalker<CheckEffectsCoverage>
...
+    const auto fixIt = getFixItForUncoveredAsyncSite(anchor);
```
Comment (LucianoPAlmeida) [inline lib/Sema/TypeCheckEffects.cpp:3614]: Nit: would this syntax work
```suggestion
    const auto &[loc, insertText] = getFixItForUncoveredAsyncSite(anchor);
```

Comment (Jamezzzb) [reply lib/Sema/TypeCheckEffects.cpp:3614]: I will try it thanks!

Comment (Jamezzzb) [reply lib/Sema/TypeCheckEffects.cpp:3614]: It works, much cleaner, thanks for showing.

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

**Review by LucianoPAlmeida — APPROVED** [review]

**Comment by LucianoPAlmeida** [comment]
It seems good to me, but wait for code owners review before merging :)
cc @xedin

**Comment by Jamezzzb** [comment]
@xedin When you have some time - Could you take a look at this please?

**Comment by xedin** [comment]
Sorry I missed this, will add it to the queue for Monday!

**Comment by xedin** [comment]
I didn’t forget about this, will take a look tomorrow!

**Review by xedin — APPROVED** [review]
Thank you!

**Comment by xedin** [comment]
@swift-ci please smoke test

File: test/Sema/diag_async_expr_without_await.swift [hunk 6]
```diff
@@ -0,0 +1,44 @@
...
+  // expected-note@-2 {{reference to async let 'result' is 'async'}}
+  if let result {} // expected-error {{expression is 'async' but is not marked with 'await'}} {{16-16= = await result}}
+  // expected-warning@-1 {{value 'result' was defined but never used; consider replacing with boolean test}}
+  // expected-note@-2 {{reference to async let 'result' is 'async'}}
+  if let person: Foo = person {} // expected-error {{expression is 'async' but is not marked with 'await'}} {{24-24=await }}
+  // expected-warning@-1 {{immutable value 'person' was never used; consider replacing with '_' or removing it}}
+  // expected-note@-2 {{reference to async let 'person' is 'async'}}
+  if let person: Foo {} // expected-error {{expression is 'async' but is not marked with 'await'}} {{21-21= = await person}}
+  // expected-warning@-1 {{immutable value 'person' was never used; consider replacing with '_' or removing it}}
+  // expected-note@-2 {{reference to async let 'person' is 'async'}}
```
Comment (AnthonyLatsis) [inline test/Sema/diag_async_expr_without_await.swift:28]: These seem superfluous when we have `if let result: A`.

File: test/Sema/diag_async_expr_without_await.swift [hunk 7]
```diff
@@ -0,0 +1,44 @@
...
+  if let person: (String, Int) {} // expected-error {{expression is 'async' but is not marked with 'await'}} {{31-31= = await person}}
+  // expected-warning@-1 {{immutable value 'person' was never used; consider replacing with '_' or removing it}}
+  // expected-note@-2 {{reference to async let 'person' is 'async'}}
+  if let person = person {} // expected-error {{expression is 'async' but is not marked with 'await'}} {{19-19=await }}
+  // expected-warning@-1 {{value 'person' was defined but never used; consider replacing with boolean test}}
+  // expected-note@-2 {{reference to async let 'person' is 'async'}}
+  if let person {} // expected-error {{expression is 'async' but is not marked with 'await'}} {{16-16= = await person}}
+  // expected-warning@-1 {{value 'person' was defined but never used; consider replacing with boolean test}}
+  // expected-note@-2 {{reference to async let 'person' is 'async'}}
```
Comment (AnthonyLatsis) [inline test/Sema/diag_async_expr_without_await.swift:40]: Ditto.

File: test/Sema/diag_async_expr_without_await.swift
Comment (AnthonyLatsis) [inline test/Sema/diag_async_expr_without_await.swift:1]: I suggest either moving this file to `test/expr/unary` or accommodating its contents in `test/expr/unary/async_await.swift` — at least that is the original place for this sort of material.

**Review by AnthonyLatsis — APPROVED** [review]
Good job!

**Comment by AnthonyLatsis** [comment]
Please consider [tidying up](https://www.swift.org/contributing/#commit-messages) the commit message. NB: I do not recommend including a link to the issue because it spawns permanent commit activity items in the issue every time you force-push, but if you wish to, please place the link in the body rather than the title.

**Comment by Jamezzzb** [comment]
@AnthonyLatsis I will do this (tidy up commit message) and I see your point about linking the issue; I'll avoid doing that in the future.

File: test/Sema/diag_async_expr_without_await.swift (hunk 6 above)
Comment (Jamezzzb) [reply test/Sema/diag_async_expr_without_await.swift]: Thank you, yes I got a little carried away maybe. Removed these

File: test/Sema/diag_async_expr_without_await.swift
Comment (Jamezzzb) [reply test/Sema/diag_async_expr_without_await.swift:1]: Fixed this

**Comment by Jamezzzb** [comment]
@AnthonyLatsis Following the guidelines I cleaned up the commit message, I also have removed some of the not needed test functions you had pointed out. Thank you for all your reviewing! It is much appreciated.

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test
