### PR TITLE
Fix the new diagnostic formatter adding extra whitespace on Windows

### LINKED ISSUE #64413: New diagnostic formatter adds extra whitespace on Windows
### Description

The new formatter on Windows seems to add extra whitespace between each line:
```
=== .../swift/stdlib/public/core/Macros.swift:32:11 ===

31 | public macro fileID<T: ExpressibleByStringLiteral>() -> T =

32 |   Builtin.FileIDMacro

   |           ^ warning: ignoring definition of unknown builtin macro 'FileIDMacro'

33 |
```

Possibly some mishandling of \r\n?

### Steps to Reproduce

Run a swift build on Windows now that it uses the new formatter by default for the compiler compilation. CC @compn

### PR DESCRIPTION
**Pull request by hjyamauchi**
The swift driver emits extra newlines because it applies the LF -> CRLF conversions again on the outpt from the child processes. Fix it by using the binary mode when outputting the output from the child processes.

Fixes: #64413

### CODE REVIEW

File: lib/Driver/Compilation.cpp [hunk 1]
```diff
@@ -727,6 +731,15 @@ namespace driver {
                  : TaskFinishedResponse::StopExecution;
     }
 
+#if defined(_WIN32)
+    struct ChangeStderrToBinaryMode {
```
Comment (compnerd) [inline lib/Driver/Compilation.cpp:735]: WDYT of `FileBinaryModeRAII` as a name and taking a `FILE *` as a ctor parameter instead of hardcoding this?  That would make this more re-usable and name it more in-line with the LLVM scheme as well.

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

File: lib/Driver/Compilation.cpp (hunk 1 above)
Comment (hjyamauchi) [reply lib/Driver/Compilation.cpp]: SGTM and done.

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test

File: lib/Driver/Compilation.cpp [hunk 2]
```diff
@@ -727,6 +731,16 @@ namespace driver {
...
     }
 
+#if defined(_WIN32)
+    struct FileBinaryModeRAII {
+      FileBinaryModeRAII(FILE *F) : F(F) { _setmode(_fileno(F), _O_BINARY); }
+      ~FileBinaryModeRAII() { _setmode(_fileno(F), _O_TEXT);}
+      FILE *F;
+    };
+#else
+    struct ChangeStderrToBinaryMode {};
```
Comment (LucianoPAlmeida) [inline lib/Driver/Compilation.cpp:741]: This is defined but not used, is intentional?

Comment (tristanlabelle) [reply lib/Driver/Compilation.cpp:741]: Looks like this is meant to be:
```c++
struct FileBinaryModeRAII {
  FileBinaryModeRAII(FILE *) {}
};
```
So the code compile as a no-op on non-Windows?

File: lib/Driver/Compilation.cpp [hunk 3]
```diff
@@ -727,6 +731,16 @@ namespace driver {
                  : TaskFinishedResponse::StopExecution;
     }
 
+#if defined(_WIN32)
+    struct FileBinaryModeRAII {
+      FileBinaryModeRAII(FILE *F) : F(F) { _setmode(_fileno(F), _O_BINARY); }
+      ~FileBinaryModeRAII() { _setmode(_fileno(F), _O_TEXT);}
```
[the remark this answers is not in the document]
Comment (hjyamauchi) [reply lib/Driver/Compilation.cpp]: Done

File: lib/Driver/Compilation.cpp (hunk 2 above)
Comment (hjyamauchi) [reply lib/Driver/Compilation.cpp]: Good catch. Done.

**Comment by hjyamauchi** [comment]
Please rerun the CI

**Comment by hjyamauchi** [comment]
Disabled the test for the `swift_swift_parser` case.

Please kick off another test run.

**Comment by compnerd** [comment]
@swift-ci please test
