### PR TITLE
[stdlib] Fix assertionFailure() not respecting -assert-config Release at -Onone

### LINKED ISSUE #85382: `assertionFailure()` Not Removed at `-Onone -assert-config Release`
### Description

`assertionFailure()` crashes when compiled with `-Onone -assert-config Release`. In contrast, `assert()` correctly respects `-assert-config Release` at all optimization levels.

### Reproduction

```swift
// test.swift
assertionFailure("Should not crash")
print("SURVIVED")
```

```bash
# Crashes (unexpected)
$ swiftc test.swift -Onone -assert-config Release -o test && ./test
Fatal error: Should not crash

# Works correctly
$ swiftc test.swift -O -assert-config Release -o test && ./test
SURVIVED
```

Compare with `assert()`:

```swift
// test_assert.swift
assert(false, "Should not crash")
print("SURVIVED")
```

```bash
# Works correctly at -Onone
$ swiftc test_assert.swift -Onone -assert-config Release -o test && ./test
SURVIVED

# Works correctly at -O
$ swiftc test_assert.swift -O -assert-config Release -o test && ./test
SURVIVED
```

### Expected behavior

Both `assert()` and `assertionFailure()` are debug-only assertions. When compiled with `-assert-config Release`, both should be disabled regardless of optimization level. The `-assert-config` flag should control assertion behavior consistently across all assertion types.

### Environment

Apple Swift version 6.2 (swiftlang-6.2.0.19.9 clang-1700.3.19.1)
Target: arm64-apple-macosx15.0

### Additional information

Looking at Assert.swift, the two functions use different attributes:

`assert()` uses `@_transparent`:
- Appears to inline at SIL level into user code
- Seems to evaluate `_isDebugAssertConfiguration()` with user's compilation flags
- Works as expected at `-Onone`

`assertionFailure()` uses `@inlinable` + `@inline(__always)`:
- At `-Onone`, the generated assembly shows a function call rather than inlined code
- Might be calling into pre-compiled stdlib where `_isDebugAssertConfiguration()` was evaluated differently
- This could explain why it doesn't respect the user's `-assert-config Release` flag

### PR DESCRIPTION
**Pull request by realrajaryan**
Fixes #85382.

Currently, `assertionFailure()` crashes at `-Onone -assert-config Release` because it used `@inlinable @inline(__always)` instead of `@_transparent`. At `-Onone`, this caused a call to the pre-compiled stdlib (built in Debug mode) instead of inlining.

To address this, we change it to `@_transparent` for mandatory inlining at all optimization levels, consistent with `assert()`, `precondition()`, and `preconditionFailure()`.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by meg-gupta** [comment]
@swift-ci test

**Comment by glessard** [comment]
@swift-ci Please test source compatibility

**Review by glessard — APPROVED** [review]

**Comment by meg-gupta** [comment]
The source compatibility failures are unrelated.

**Comment by meg-gupta** [comment]
@swift-ci test

File: validation-test/stdlib/AssertDiagnosticsSIL.swift [hunk 1]
```diff
@@ -1,7 +1,10 @@
...
 
-func assertionFailure_isNotNoreturn() -> Int {
-  _ = 0 // Don't implicitly return the assertionFailure call.
+// assertionFailure() is now @_transparent (previously @inlinable), so the
+// compiler can see that it never returns, eliminating the "missing return" error.
+func assertionFailure_isNoreturn() -> Int {
+  _ = 0
   assertionFailure("")
-} // expected-error {{missing return in global function expected to return 'Int'}}
+  // No error expected - assertionFailure() is recognized as Never-returning
```
Comment (DmT021) [inline validation-test/stdlib/AssertDiagnosticsSIL.swift:8]: Are we sure this is correct behavior? It doesn't seem right `assertionFailure` is now recognized as never-returning depending on compilation settings as it'll lead to descrepancies between build types - builds fine in debug, but fails in release when a return is missing after the assertion.

Comment (DmT021) [reply validation-test/stdlib/AssertDiagnosticsSIL.swift:8]: @realrajaryan @slavapestov @meg-gupta @glessard 
I've just tested this on `main` and indeed the diagnostics are different depending on `-assert-config`.
```swift
func assertionFailure_isNoreturn() -> Int {
  _ = 0
  assertionFailure("")
}
```
With `-assert-config Debug` it builds with no diagnostics, but with `-assert-config Release` it fails with `missing return in global function expected to return 'Int'`

But what's even more interesting is that this code
```swift
func codeAfterAssertionFailure() -> Int {
  _ = 0
  assertionFailure("")
  return 42
}
```
doesn't report `warning: will never be executed` even with `-assert-config Debug` (when `assertionFailure` is recognized as never-returning). IMO it shouldn't, but now it's inconsistent with the test.

Comment (glessard) [reply validation-test/stdlib/AssertDiagnosticsSIL.swift:8]: @DmT021 thanks for noticing this. Fixed by https://github.com/swiftlang/swift/pull/91276.
