### PR TITLE
[SourceKit] Format macro decl without crashing

### LINKED ISSUE #70002: SourceKit crash for `source.request.editor.formattext` request
**Description**

Sending a request to SourceKit to format the following Swift code crashes SourceKit:

```swift
@available(iOS 17, *)
#Preview("") {
  UIView()
}
```

**Steps to reproduce**

The easiest way to reproduce this is using the [SourceKitten](https://github.com/jpsim/SourceKitten) tool to send SourceKit requests, but SourceKitten isn't necessary to reproduce this crash:

```console
$ brew install sourcekitten
$ cat file.swift 
@available(iOS 17, *)
#Preview("") {
  UIView()
}
$ SOURCEKIT_LOGGING=3 sourcekitten format --file file.swift
sourcekit: [2:sourcekitd_initialize:6403: 0.0000] initializing
sourcekit: [2:handleRequest-before:6403: 0.0155] {
  key.request: source.request.editor.open,
  key.name: "/path/to/file.swift",
  key.sourcefile: "/path/to/file.swift"
}
sourcekit: [2:handleRequest-after:6403: 0.0175] {
  key.offset: 0,
  key.length: 50,
  key.diagnostic_stage: source.diagnostic.stage.swift.parse,
  key.syntaxmap: [
    {
      key.kind: source.lang.swift.syntaxtype.attribute.builtin,
      key.offset: 0,
      key.length: 10
    },
    {
      key.kind: source.lang.swift.syntaxtype.keyword,
      key.offset: 11,
      key.length: 3
    },
    {
      key.kind: source.lang.swift.syntaxtype.number,
      key.offset: 15,
      key.length: 2
    },
    {
      key.kind: source.lang.swift.syntaxtype.operator,
      key.offset: 19,
      key.length: 1
    },
    {
      key.kind: source.lang.swift.syntaxtype.identifier,
      key.offset: 23,
      key.length: 7
    },
    {
      key.kind: source.lang.swift.syntaxtype.string,
      key.offset: 31,
      key.length: 2
    },
    {
      key.kind: source.lang.swift.syntaxtype.identifier,
      key.offset: 39,
      key.length: 6
    }
  ],
  key.substructure: [
    {
      key.kind: source.lang.swift.expr.closure,
      key.offset: 35,
      key.length: 14,
      key.bodyoffset: 36,
      key.bodylength: 12,
      key.substructure: [
        {
          key.kind: source.lang.swift.stmt.brace,
          key.offset: 35,
          key.length: 14,
          key.bodyoffset: 36,
          key.bodylength: 12,
          key.substructure: [
            {
              key.kind: source.lang.swift.expr.call,
              key.name: "UIView",
              key.offset: 39,
              key.length: 8,
              key.nameoffset: 39,
              key.namelength: 6,
              key.bodyoffset: 46,
              key.bodylength: 0
            }
          ]
        }
      ]
    }
  ]
}
sourcekit: [2:handleRequest-before:6403: 0.0178] {
  key.request: source.request.editor.formattext,
  key.name: "/path/to/file.swift",
  key.line: 1,
  key.editor.format.options: {
    key.editor.format.indentwidth: 4,
    key.editor.format.tabwidth: 4,
    key.editor.format.usetabs: 0
  }
}
sourcekit: [2:handleRequest-after:6403: 0.0178] {
  key.line: 1,
  key.length: 1,
  key.sourcetext: "@available(iOS 17, *)"
}
sourcekit: [2:handleRequest-before:6403: 0.0178] {
  key.request: source.request.editor.formattext,
  key.name: "/path/to/file.swift",
  key.line: 2,
  key.editor.format.options: {
    key.editor.format.indentwidth: 4,
    key.editor.format.tabwidth: 4,
    key.editor.format.usetabs: 0
  }
}
sourcekit: [2:handleRequest-after:6403: 0.0178] {
  key.line: 2,
  key.length: 1,
  key.sourcetext: "#Preview(\"\") {"
}
sourcekit: [2:handleRequest-before:6403: 0.0179] {
  key.request: source.request.editor.formattext,
  key.name: "/path/to/file.swift",
  key.line: 3,
  key.editor.format.options: {
    key.editor.format.indentwidth: 4,
    key.editor.format.tabwidth: 4,
    key.editor.format.usetabs: 0
  }
}
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
[1]    64119 segmentation fault  SOURCEKIT_LOGGING=3 sourcekitten format --file file.swift
```

**Expected behavior**

The file should be formatted without crashing SourceKit.

**Environment**
- Swift compiler version info: 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
- Xcode version info: 15.0 (15A240d)
- Deployment target: macOS 14.1.1 (23B81)

```console
$ swiftc --version
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx14.0
$ xcodebuild -version
Xcode 15.0
Build version 15A240d
```

Originally reported here: https://github.com/realm/SwiftLint/issues/5365

### PR DESCRIPTION
**Pull request by vincentisambart**
Resolves #70002

Fix SourceKit crash occurring when formatting a macro with both an available attribute and a trailing closure.
SourceKit's formatting code was expecting trailing closures to only be present on expressions (`Expr`), but an available attribute on a macro makes it a declaration (`Decl`).

I don't have much knowledge of how SourceKit's formatting works so I wouldn't be surprised if this was incomplete.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

File: test/SourceKit/CodeFormat/indent-available-macro.swift [hunk 1]
```diff
@@ -0,0 +1,6 @@
+@available(iOS 17, *)
+#Preview("") {
+  UIView()
+}
+
+// RUN: %sourcekitd-test -req=format -line=3 -length=1 %s >%t.response
```
Comment (ahoppen) [inline test/SourceKit/CodeFormat/indent-available-macro.swift:6]: If you write the response into `%t.response` you should also check its contents.

Comment (vincentisambart) [reply test/SourceKit/CodeFormat/indent-available-macro.swift:6]: Without the fix this test crashes, and `indent-crashes.swift` which seems to have a goal similar to this did write into `%t.response` without checking its content I thought it would be fine like this.
What do you think I should do?
- Do not write into `%t.response`?
- Write into `%t.response` and check the content? In that case should I change the test to be badly indented on purpose checking it properly gets into the expected shape?

Thanks

Comment (vincentisambart) [reply test/SourceKit/CodeFormat/indent-available-macro.swift:6]: @ahoppen Thanks for the help! I just made the modifications you asked.
I also checked that running this test without my SourceKit changes still makes SourceKit crash and the test fail.

**Review by ahoppen — APPROVED** [review]
Great. Thank you for the fix. Looks good to me 👍🏽
