### PR TITLE
[SourceKit] Merge local refactoring implementations

### LINKED ISSUE #64264: Local rename fails if refactoring `if let file` when `file` is not declared
The following new test case fails with `error: value decl ''file'' has no declaration location`. If the variable is renamed to anything but `file`, it works. The same issue happens if the variable is named `line` so I believe the problem here is that `file` is resolving to the `file` macro.

```swift
func test() {
    // RUN: %sourcekitd-test -req=refactoring.rename.local -pos=%(line + 1):12 %s -- %s
    if let file {}
}

```

### PR DESCRIPTION
**Pull request by bnbarham**
Retrieving local rename ranges and the local rename refactoring both had almost identical methods, except for the addition of retrieving the outermost shadowed decl that was added a couple months back. Merge them.

Resolves rdar://106529370.
Resolves #64264

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

File: lib/Refactoring/Refactoring.cpp [hunk 1]
```diff
@@ -9084,29 +9094,11 @@ int swift::ide::findLocalRenameRanges(
...
-  Optional<RenameRefInfo> RefInfo;
-  if (ValueRefCursorInfo->isRef())
-    RefInfo = {CursorInfo->getSourceFile(), CursorInfo->getLoc(),
-               ValueRefCursorInfo->isKeywordArgument()};
-
-  llvm::SmallVector<DeclContext *, 8> Scopes;
-  analyzeRenameScope(VD, RefInfo, Diags, Scopes);
-  if (Scopes.empty())
+  Optional<RenameRangeCollector> RangeCollector =
+      localRenames(SF, StartLoc, StringRef(), Diags);
```
Comment (bnbarham) [inline lib/Refactoring/Refactoring.cpp:9098]: `findLocalRenameRanges` and the rename refactoring itself were both doing this. Back when I added shorthand shadow handling, I updated one and not the other (didn't see this one).

The two refactorings here are just merging those + changing `collectRenameAvailabilityInfo` to just give back the availability info since it was always just a single value, never both.

File: test/refactoring/rename/shorthand_shadow.swift [hunk 2]
```diff
@@ -1,16 +1,11 @@
...
-  _ = { (toRename: Int?) in
-    // RUN: %refactor -rename -dump-text -source-filename %s -pos=%(line+2):12 -new-name=renamed | %FileCheck %s
-    // CHECK: shorthand_shadow.swift [[# @LINE+1]]:12 -> [[# @LINE+1]]:20
-    if let toRename {
-      // RUN: %refactor -rename -dump-text -source-filename %s -pos=%(line+2):11 -new-name=renamed | %FileCheck %s
-      // CHECK: shorthand_shadow.swift [[# @LINE+1]]:11 -> [[# @LINE+1]]:19
-      _ = toRename
-    }
+// RUN: %refactor -rename -dump-text -source-filename %s -pos=%(line+2):29 -new-name=renamed | %FileCheck %s --check-prefix=OPTIONAL
+// OPTIONAL: shorthand_shadow.swift [[# @LINE+1]]:29 -> [[# @LINE+1]]:32
```
Comment (ahoppen) [inline test/refactoring/rename/shorthand_shadow.swift:2]: I think it might be worth keeping a version of this test that is inside a closure. At least in solver-based land they still behave differently than top-level code.

**Review by ahoppen — APPROVED** [review]

File: test/refactoring/rename/shorthand_shadow.swift (hunk 2 above)
Comment (bnbarham) [reply test/refactoring/rename/shorthand_shadow.swift:2]: I just moved that to the sourcekitd-test. This one now just checks we handle shorthand shadow correctly from refactor as well.

Comment (bnbarham) [reply test/refactoring/rename/shorthand_shadow.swift:2]: ...oh I forgot to add that file :)

**Comment by bnbarham** [comment]
@swift-ci please test

**Review by hamishknight — APPROVED** [review]

**Comment by bnbarham** [comment]
@swift-ci please test
