### PR TITLE
[Runtime] Fix subscript key path printing when arguments can't be resolved.

### LINKED ISSUE #64865: Runtime crash in AnyKeyPath.debugDescription when using @dynamicMemberLookup
**Description**

The following code defines a wrapper struct around a value and uses `@dynamicMemberLookup` to expose access to the underlying value:

```swift
@dynamicMemberLookup
struct Wrapper<Value> {
  let value: Value
  subscript<OtherValue>(dynamicMember keyPath: KeyPath<Value, OtherValue>) -> OtherValue {
    self.value[keyPath: keyPath]
  }
}
```

In Swift 5.8, if we try to access a key path's `debugDescription` on `Wrapper` that goes through the dynamic member, we get a runtime crash:

```swift
let kp = \Wrapper<String>.count
print(kp.debugDescription)  // 🛑 Bad access
```

**Steps to reproduce**

Run the above code in any Swift environment.

**Expected behavior**

It should print out something like `"\Wrapper<String>.count"`.

**Environment**
- swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
- Xcode 14.3, Build version 14E222b
- Deployment target: iOS 16.4

### PR DESCRIPTION
**Pull request by mikeash**
If there's a mismatch between the arguments we match and the arguments we actually have, we can end up indexing off the end of the argumentTypeNames vector. This can happen when an argument has a dependent generic type. Add a bounds check and print <unknown> when we're out of bounds to avoid crashing.

For correctness, we should match generic dependent types and add them to the arguments array, but we'll fix the crashes first.

rdar://104438524
Fixes #64865

### CODE REVIEW

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test

**Comment by mikeash** [comment]
@swift-ci please test linux platform

File: lib/Demangling/NodePrinter.cpp [hunk 1]
```diff
@@ -3315,6 +3315,11 @@ std::string Demangle::keyPathSourceString(const char *MangledName,
       case Node::Kind::Subscript: {
         std::string subscriptText = "subscript(";
         std::vector<std::string> argumentTypeNames;
+        auto getArgumentTypeName = [&argumentTypeNames](size_t i) {
+          if (i < argumentTypeNames.size())
+            return argumentTypeNames[i];
+          return std::string("<unknown>");
+        };
```
Comment (al45tair) [inline lib/Demangling/NodePrinter.cpp:3322]: :-) Neat fix.

**Review by al45tair — APPROVED** [review]

**Comment by mikeash** [comment]
@swift-ci please test linux platform

**Comment by mikeash** [comment]
@swift-ci please test linux platform

**Comment by mikeash** [comment]
@swift-ci please test linux platform

**Comment by mikeash** [comment]
@swift-ci please test and merge
