### PR TITLE
[Concurrency] Skip `Sendable` checking for `nonisolated(nonsending)` …

### LINKED ISSUE #86203: @Sendable function conversions seem unnecessarily restrictive
### Description

I cannot see a scenario where these conversions could actually introduce races. My guess would have been that you could never *form* these functions in an unsafe way in the first place. Maybe I don't see it, but I thought it was at least worth a bug report.

Could it be that the `@Sendable`-ness is not being taken into account?

### Reproduction

```swift
class NonSendable {}

let a: @Sendable (NonSendable) -> Void = { _ in }
// warning: Cannot convert '@Sendable (NonSendable) -> Void' to '@Sendable (NonSendable) async -> Void' because crossing of an isolation boundary requires parameter and result types to conform to 'Sendable' protocol
let b: @Sendable (NonSendable) async -> Void = a

let c: @Sendable () -> NonSendable = { fatalError() }
// warning: Cannot convert '@Sendable () -> NonSendable' to '@Sendable () async -> NonSendable' because crossing of an isolation boundary requires parameter and result types to conform to 'Sendable' protocol
let d: @Sendable () async -> NonSendable = c
```

### Expected behavior

I think both of these should build warning-free.

### Environment

Apple Swift version 6.3-dev (LLVM f6e8f31819e2e67, Swift cecebdd863d2f71)

### Additional information

_No response_

### LINKED ISSUE #87235: A `nonisolated(nonsending)` function with non-`Sendable` parameter can witness `@concurrent` requirement but converting it to the latter produces warning
### Description

SE-0461 has the following:

> Function conversions that cross an isolation boundary require `Sendable` argument and result types,
> and the destination function type must be `async`.

It also gives a list of cross-isolation convention, which includes conversion from `nonisolated(nonsending)` to `@concurrent`.

On the other hand, my experiment shows that a `nonisolated(nonsending)` function with non-Sendable parameter can witness `@concurrent` function requirement in protocol:  

```
class NS {}

protocol P1 {
    @concurrent nonisolated func fn(_ ns: NS) async    
}

struct S1: P1 {
    nonisolated(nonsending) func fn(_ ns: NS) async {}  // OK
}
```

IMO this means it's OK to use a `nonisolated(nonsending)` function as a `@concurrent` function in term of isolation check. If so, I wonder why it's not OK to convert the former to the latter?

The actual result is neither the same as what SE-0461 said nor what I thought. Compiler produces warning:

```
class NS {}

func foo(_ fn: @concurrent (NS) async -> Void) {}

nonisolated(nonsending)
func fn(_ ns: NS) async -> Void {}

func test() {
    foo(fn) // warning: cannot convert 'nonisolated(nonsending) @Sendable (NS) async -> Void' to '(NS) async -> Void' because crossing of an isolation boundary requires parameter and result types to conform to 'Sendable' protocol; this will be an error in a future Swift language mode
}
```

I'm submitting the report because I'm not sure if the warning is intended. IMO protocol conformance and function conversion should have the same behavior. 

### Reproduction

See above

### Expected behavior

I'm not 100% sure, but I think the two examples in my report should have the same behavior. 

### Environment

swiftc x86-64 nightly on godbolt.org

### Additional information

I also noticed that this didn't compile. I suspect the behavior is similar to that in example 2? Is it by design? I can't see why example 1 is OK, but this isn't.

```
protocol P5 {
    func foo(_ fn: @concurrent (NS) async -> Void) async
}

struct S5: P5 {
    func foo(_ fn: nonisolated(nonsending) (NS) async -> Void) async {
    }
}
```

### PR DESCRIPTION
**Pull request by xedin**
…-> `@concurrent` conversions

Converting a `nonisolated(nonsending)` function type to a `@concurrent` one is the same as converting it to an actor-isolated function type. `nonisolated(nonsending)` functions run on the caller's actor without crossing an isolation boundary and so no Sendable checking is necessary.

Resolves: https://github.com/swiftlang/swift/issues/86203
Resolves: https://github.com/swiftlang/swift/issues/87235
Resolves: rdar://170380869

### CODE REVIEW

**Review by ktoso — APPROVED** [review]
Makes sense, we're not crossing anywhere new here AFAICS

**Comment by xedin** [comment]
@swift-ci please test

File: lib/Sema/TypeCheckConcurrency.cpp [hunk 1]
```diff
@@ -2780,12 +2779,13 @@ namespace {
               break;
             }
 
-            case FunctionTypeIsolation::Kind::NonIsolated: {
-              // nonisolated synchronous <-> @concurrent
-              if (fromFnType->isAsync() != toFnType->isAsync()) {
-                diagnoseNonSendableParametersAndResult(toFnType,
-                                                       LanguageMode::future);
-              }
+            case FunctionTypeIsolation::Kind::NonIsolated:
```
Comment (jamieQ) [inline lib/Sema/TypeCheckConcurrency.cpp:2782]: I had done something similar [here](https://github.com/swiftlang/swift/pull/86210) for one of the conversion cases and we discussed somewhat in https://github.com/swiftlang/swift/issues/86203. Will this resolve https://github.com/swiftlang/swift/issues/86203 then as well？

Also just double checking that this is intentionally changing behavior of nonisolated function conversions as well.

Comment (xedin) [reply lib/Sema/TypeCheckConcurrency.cpp:2782]: Yeah, we have it wrong in the proposal as well. Both nonisolated sync and `nonisolated(nonsending)` async function types should behave the same way when converted to `@concurrent` (and we don't allow async -> sync conversions) because they don't leave the isolation of the `@concurrent` function when called. I'll update the proposal text for this as well. The change does indeed resolve https://github.com/swiftlang/swift/issues/86203 as well.

**Review by hborla — APPROVED** [review]
