### PR TITLE
Sema: Implement missing part of SE-0346

### LINKED ISSUE #62906: Can't inherit from a protocol with primary associated types using the "generic" notation
It doesn't seem possible for a struct to inherit a protocol with primary associated type using this primary associated type in the declaration. In other words, the following doesn't compile:
```swift
protocol P<A> {
  associatedtype A
}
struct B {}

struct T: P<B> {} // Error: Cannot inherit from protocol type with generic argument 'P<B>'
```
This configuration was however explicitly mentioned in [SE-0346](https://github.com/apple/swift-evolution/blob/main/proposals/0346-light-weight-same-type-syntax.md#other-positions), so I don't know if this is a bug, a regression, or feature that was not implemented at the end.

**Environment**
- Swift compiler version info: swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
- Xcode version info: Version 14.2 (14C18)
- Deployment target: macOS 13.1

### PR DESCRIPTION
**Pull request by slavapestov**
[The proposal](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0346-light-weight-same-type-syntax.md) states that this should work, but this was never implemented:

    protocol P<A> {
      associatedtype A
    }

    struct S: P<Int> {}

- Fixes https://github.com/swiftlang/swift/issues/62906.
- Fixes rdar://91842338.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Review by xedin — APPROVED** [review]

File: lib/Sema/TypeCheckDeclPrimary.cpp [hunk 1]
```diff
@@ -1777,6 +1777,33 @@ static TypeRepr *unwrapAttributedRepr(TypeRepr *repr) {
...
+    if (isModuleQualified(repr, proto->getParentModule())) {
+      protocolsWithRetroactiveAttr.insert(proto);
+    }
+
+    protos.push_back(proto);
+  } else if (auto *pct = inheritedTy->getAs<ProtocolCompositionType>()) {
+    for (auto member : pct->getMembers()) {
+      collectProtocolsFromInheritedEntry(entry, member,
+                                         protocolsWithRetroactiveAttr, protos);
+    }
```
Comment (AnthonyLatsis) [inline lib/Sema/TypeCheckDeclPrimary.cpp:1801]: Do we have a test case for a nested composition?

**Review by AnthonyLatsis — APPROVED** [review]
Will we be fine (error) if there’s another kind of explicit type witness?

File: lib/Sema/TypeCheckDeclPrimary.cpp (hunk 1 above)
Comment (slavapestov) [reply lib/Sema/TypeCheckDeclPrimary.cpp:1801]: I'll add one

**Comment by slavapestov** [comment]
@AnthonyLatsis it would crash on ambiguity. I added a little bit of logic that makes us now diagnose an ambiguity error.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility
