### PR TITLE
Sema: Fix soundness hole with variable initializers and opaque return types

### LINKED ISSUE #73245: Opaque types as inferred associated types violate type safety
### Description / Reproduction

The following ought to generate a type-error where `whoops` is declared, but instead it complies and violates type safety, interpreting memory as incorrect type.
```swift
protocol ExampleProtocol {}
extension Int: ExampleProtocol {}
extension String: ExampleProtocol {}

struct ExampleFactory {
    func makeExample() -> some ExampleProtocol { 0 }
}

protocol MakeExampleProtocol {
    associatedtype Example
    func makeExample() -> Example
}
extension ExampleFactory: MakeExampleProtocol {}

let whoops: ExampleFactory.Example = "hi"
print(whoops) // -> 26984
```

In the example above, the `String` `"hi"` was reinterpreted as an `Int` since `ExampleFactor.Example` is `Int`.

If we were to `unsafeBitCast` a `String` to `Int`, it would trap since the sizes don't match. Instead, we can run the following:
```swift
print(unsafeBitCast("hi", to: (Int, Int).self)) // (26984, -2161727821137838080)
```
As you can see, the first component matches the value of `whoops`, confirming that Swift in the first example silently reinterpreted `whoops`'s initializing value as a conflicting type. 

### Expected behavior

> Cannot convert value of type 'String' to specified type 'some ExampleProtocol' (result of 'ExampleFactory.makeExample()')

### Environment

swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by slavapestov**
Just because the type of the initializer expression is an opaque return type, does not mean it is the opaque return type *for the variable being initialized*.

It looks like there is a bit of duplicated logic and layering violations going on so I only fixed one caller of openOpaqueType(). This addresses the test case in the issue. For the remaining calls I added FIXMEs to investigate what is going on.

Fixes https://github.com/swiftlang/swift/issues/73245.
Fixes rdar://127180656.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

File: lib/Sema/TypeOfReference.cpp [hunk 1]
```diff
@@ -359,23 +359,31 @@ Type ConstraintSystem::openOpaqueType(OpaqueTypeArchetypeType *opaque,
...
+  // FIXME: Require non-null ownerDecl and fix remaining callers
+  // ASSERT(ownerDecl);
+
   // Early return if `type` is `NULL` or if there are no opaque archetypes (in
   // which case there is certainly nothing for us to do).
   if (!type || !type->hasOpaqueArchetype())
     return type;
 
-  if (!(context == CTP_Initialization || context == CTP_ReturnStmt))
+  if (context != CTP_Initialization && context != CTP_ReturnStmt)
```
Comment (xedin) [inline lib/Sema/TypeOfReference.cpp:372]: This are equivalent, just a matter of preference which one to use.

**Review by xedin — APPROVED** [review]

**Comment by slavapestov** [comment]
https://github.com/swiftlang/swift-docc/pull/1116/
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test
