### PR TITLE
[cxx-interop] Improve interface of `std::optional`

### LINKED ISSUE #74090: Assigning to .pointee of a nil std.optional does not update the .value
### Description

When a qualified `std::optional` is created using a constructor in swift, assigning a value to `.pointee` does not affect the `.value`, it stays as nil. Furthermore it doesn't update the values of `.pointee`, as long as it's treated as nil.

From my testing, a primitive value (like `int64_t` or `bool`) do change the `.pointee` but the whole optional is still treated as nil. Once an optional is non-nil modifying the `.pointee` does work as expected (as far as I've noticed, at least) 

### Reproduction

https://github.com/Drejzer/swift-std.optional-minimal

```cpp
using MyOptionalString = std::optional<std::string>;
```

in a cpp target, then in a swift one

```swift
var opt = MyOptionalString()// creates a std::optional<std::string>

opt.pointee = "test"

print(opt, opt.hasValue, opt.value, opt.pointee) 
```
and analogous for int64_t and a simple struct

### Expected behavior

assigning to `.pointee` updates `.value` (and `.hasValue`), or at the very least updates `.pointee`

### Environment

1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)

### Additional information

The workaround for this is to create a function that returns an optional and call it from Swift. It's cumbersome and awkward, especially if the goal is to call a cpp method that takes some optional (which probably is the only reason someone would want to create a cpp optional in Swift, I suppose).

I've posted about it [on the forum](https://forums.swift.org/t/no-way-to-create-a-non-nil-std-optional-in-swift) and was directed to make a bug report.

### PR DESCRIPTION
**Pull request by egorzhdan**
We've seen multiple reports of `std::optional`'s behavior in Swift being confusing. In particular, creating an instance of `std::optional` without a value, and then assigning a value to it via `myOpt.pointee = ...` does not actually persist the non-nil value inside of the `std::optional`.

This behavior was consistent with the design: the setter for `var pointee` in Swift is synthesized from `operator*()` imported from C++. In C++, if `std::optional` does not contain a value, the behavior of its `operator*()` is undefined.

https://en.cppreference.com/w/cpp/utility/optional/operator%252A.html

Swift already conforms instantiations of `std::optional` to `protocol CxxOptional`, which declares `var value` property that provides UB-safe access to the wrapped element. That property was immutable. This change makes it mutable by adding a setter, and introduces a deprecation annotation to direct users to use `value` instead of `pointee`.

Note that currently `CxxOptional` does not support non-copyable types.

rdar://129159672 / resolves https://github.com/swiftlang/swift/issues/74090

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Comment by egorzhdan** [comment]
@swift-ci please clean smoke test macOS

**Review by Xazax-hun — APPROVED** [review]

File: test/Interop/Cxx/stdlib/use-std-optional.swift [hunk 1]
```diff
@@ -53,6 +47,20 @@ StdOptionalTestSuite.test("std::optional hasValue/value") {
...
+  var nonNilOpt = getNonNilOptional()
+  nonNilOpt.value = 321
+  expectEqual(321, nonNilOpt.value!)
+  nonNilOpt.value = 456
+  expectEqual(456, nonNilOpt.value!)
+  nonNilOpt.value = nil
+  expectNil(nonNilOpt.value)
+
+  var nilOpt = getNilOptional()
+  nilOpt.value = 321
```
Comment (hnrklssn) [inline test/Interop/Cxx/stdlib/use-std-optional.swift:60]: Could we have a check that setting Swift nil results in the object comparing equal to a C++ nullopt?
```suggestion
  nonNilOpt.value = nil
  expectNil(nonNilOpt.value)

  var nilOpt = getNilOptional()
  expectEqual(nonNilOpt, nilOpt)
  nilOpt.value = 321
```

**Review by hnrklssn — COMMENTED** [review]
This also resolves https://github.com/swiftlang/swift/issues/75834, right?

**Comment by egorzhdan** [comment]
@hnrklssn good observation, https://github.com/swiftlang/swift/issues/75834 was actually resolved awhile ago in https://github.com/swiftlang/swift/pull/74146, so I've closed that issue.

File: test/Interop/Cxx/stdlib/use-std-optional.swift (hunk 1 above)
Comment (egorzhdan) [reply test/Interop/Cxx/stdlib/use-std-optional.swift:60]: I don't think we currently instantiate `std::optional<T>::operator==` since it's a non-member templated function (and also uses SFINAE).

Comment (hnrklssn) [reply test/Interop/Cxx/stdlib/use-std-optional.swift:60]: ah I see
