### PR TITLE
[6.3] StackNesting: don't mark pending allocations [non_nested]

### LINKED ISSUE #81771: Crash in Swift 6.1 when using async let inside a do {} block (Xcode 16.3+)
### Description

In Swift 6.1 (Xcode 16.3 and 16.4), placing `async let` bindings inside a do block causes a runtime crash—even when those values are properly awaited and the code is enclosed in do-catch. The crash does not occur in Xcode 16.2 or earlier.

This behavior seems to be related to how task deallocation is handled for `async let` when declared inside lexical scopes.

### Reproduction

```swift
func crashingAsyncLetUsage() async {
  do {
    async let value1 = fetchValue1()
    async let value2 = fetchValue2()

    let result1 = try await value1()
    let result2 = try await value2()

    let model = buildModel(result1, result2)
    await consume(model)
  } catch {
    print("Caught error: \(error)")
  }
}

func safeAsyncLetUsage() async {
  async let value1 = fetchValue1()
  async let value2 = fetchValue2()

  do {
    let result1 = try await value1()
    let result2 = try await value2()

    let model = buildModel(result1, result2)
    await consume(model)
  } catch {
    print("Caught error: \(error)")
  }
}
```

### Stack dump

```text
Thread 12 Crashed:
0   libsystem_kernel.dylib        	       0x102628874 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x1015be2ec pthread_kill + 264
2   libsystem_c.dylib             	       0x180170568 __abort + 112
3   libsystem_c.dylib             	       0x1801704f8 abort + 116
4   libswift_Concurrency.dylib    	       0x2493a346c swift::swift_Concurrency_fatalErrorv(unsigned int, char const*, char*) + 28
5   libswift_Concurrency.dylib    	       0x2493a3488 swift::swift_Concurrency_fatalError(unsigned int, char const*, ...) + 28
6   libswift_Concurrency.dylib    	       0x2493a6718 swift_task_dealloc + 124
7   libswift_Concurrency.dylib    	       0x2493a27a4 asyncLet_finish_after_task_completion(swift::AsyncContext*, swift::AsyncLet*, void (swift::AsyncContext* swift_async_context) swiftasynccall*, swift::AsyncContext*, void*) + 72
8   Dev.debug.dylib               	       0x113f12529 implicit closure #6 in implicit closure #5 in implicit closure #4 in FooViewModel.sendAction<A>(_:) + 1
9   Dev.debug.dylib               	       0x113f1cddd partial apply for implicit closure #6 in implicit closure #5 in implicit closure #4 in FooViewModel.sendAction<A>(_:) + 1
10  Dev.debug.dylib               	       0x113ec8d6d thunk for @escaping @callee_guaranteed @async () -> () + 1
11  Dev.debug.dylib               	       0x113f1ccf9 partial apply for thunk for @escaping @callee_guaranteed @async () -> () + 1
12  Dev.debug.dylib               	       0x113f0f959 FooViewModel.sendAction<A>(_:) + 1 (FooViewModel.swift:)
13  Dev.debug.dylib               	       0x113f1b5c1 protocol witness for ActionCaster.sendAction<A>(_:) in conformance FooViewModel + 1
14  Dev.debug.dylib               	       0x113f0b10d closure #1 in FooViewModel.viewWillAppear(_:) + 1 (FooViewModel.swift:)
15  Dev.debug.dylib               	       0x113f0b2c5 partial apply for closure #1 in FooViewController.viewWillAppear(_:) + 1
16  Dev.debug.dylib               	       0x113e74cbd thunk for @escaping @isolated(any) @callee_guaranteed @async () -> (@out A) + 1
17  Dev.debug.dylib               	       0x113e74e29 partial apply for thunk for @escaping @isolated(any) @callee_guaranteed @async () -> (@out A) + 1
18  libswift_Concurrency.dylib    	       0x2493a5829 completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*) + 1
```

### Expected behavior

`async let` declared inside a do block should behave the same as when declared outside it, as long as all values are awaited. It should not result in a crash.

### Environment

swift-driver version: 1.120.5 Apple Swift version 6.1.2 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
Target: arm64-apple-macosx15.0

### Additional information

This may be a regression introduced by recent changes to task deallocation logic in Swift 6.1. The crash appears related to how async let scopes are finalized when declared in lexical blocks like do {}.

### PR DESCRIPTION
**Pull request by rjmccall**
Instead, just emit them immediately when we encounter a non-reorderable deallocation. Credit for this idea goes to Michael Gottesman.

This is a nice optimization; it avoids marking a lot of allocations as [non_nested] unnecessarily. But by not marking allocations that are well-nested w.r.t the non-reorderable deallocation, it also means we never need to mark allocations that were emitted well-ordered and never fell out of order. That should actually achieve the intuition I had with the earlier work that it was okay to not support marking certain stack allocations that are never introduced directly by the SIL optimizer.

6.3 version of #88225.

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test

File: lib/SILOptimizer/Utils/StackNesting.cpp [hunk 1]
```diff
@@ -550,6 +535,69 @@ static void emitPendingDeallocations(State &state,
...
+  // to insert prior to the out-of-order deallocation.
+  std::optional<SILBuilderWithScope> builder;
+
+  // Iterate from the top of the stack down to the paired allocation. We
+  // can't pop anything yet because we might still see deallocations later
+  // for the allocations that are still live, but we do need to transition
+  // literally everything in the suffix.
+  auto i = state.allocations.end();
+  while (true) {
+    assert(i != state.allocations.begin() && "allocEntry not in stack!");
```
Comment (eeckstein) [inline lib/SILOptimizer/Utils/StackNesting.cpp:611]: Please use `ASSERT` instead of `assert` in new code so that we catch errors also in non-assert compiler builds.

File: lib/SILOptimizer/Utils/StackNesting.cpp [hunk 2]
```diff
@@ -267,6 +268,16 @@ static bool isAllocatedOrUndeallocatable(AllocationStatus status) {
...
 }
 
+static StringRef getNameForStatus(AllocationStatus status) {
+  switch (status) {
+  case AllocationStatus::Allocated: return "allocated";
+  case AllocationStatus::Pending: return "pending";
+  case AllocationStatus::Deallocated: return "deallocated";
+  case AllocationStatus::Undeallocatable: return "undeallocatable";
+  }
+  llvm_unreachable("bad kind");
```
Comment (eeckstein) [inline lib/SILOptimizer/Utils/StackNesting.cpp:285]: also: `llvm_unreachable` -> `ABORT`

**Review by eeckstein — CHANGES_REQUESTED** [review]
Unfortunately this does not work in some multi-block scenarios:

```
sil [ossa] @test_async_let_non_nested : $@convention(thin) @async (Builtin.Int1) -> () {
bb0(%cond: $Builtin.Int1):
  specify_test "stack_nesting_fixup"
  %al = builtin "startAsyncLetWithLocalBuffer"<Int>(undef: $Optional<Builtin.RawPointer>, undef: $@convention(thick) @Sendable @async () -> (@out Int, @error any Error), undef: $Builtin.RawPointer) : $Builtin.RawPointer
  %b = alloc_stack $Int16
  %c = alloc_stack $Int32
  cond_br undef, bb1, bb2

bb1:
  dealloc_stack %b
  %out = builtin "finishAsyncLet"(%al, undef: $Builtin.RawPointer) : $()
  br bb3

bb2:
  %out2 = builtin "finishAsyncLet"(%al, undef: $Builtin.RawPointer) : $()
  dealloc_stack %b
  br bb3

bb3:
  dealloc_stack %c
  %ret = tuple ()
  return %ret : $()
}
```

->

```
SIL verification failed: return with operations still active: state.ActiveOps.empty()
```

File: lib/SILOptimizer/Utils/StackNesting.cpp (hunk 1 above)
Comment (rjmccall) [reply lib/SILOptimizer/Utils/StackNesting.cpp:611]: I understand that we have a large number of assertions that are actually missing verifier checks, but this really is a traditional use of `assert` for checking that we didn't locally break a precondition that the caller already established.

File: lib/SILOptimizer/Utils/StackNesting.cpp (hunk 2 above)
Comment (rjmccall) [reply lib/SILOptimizer/Utils/StackNesting.cpp:285]: And this is the exhaustive enum switch pattern where an unreachable is actually appropriate.

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
> Unfortunately this does not work in some multi-block scenarios:

Very nice catch! The fact that we're immediately emitting a deallocation for something that's not at the top of the stack can leave us in an inconsistent state when we defer deallocation on other paths. I believe it's sufficient to just force deallocation to be eager for any outstanding allocations above a non-nested, non-reorderable deallocation — in other words, give them a new state that causes deallocations to trigger an allocated=>deallocated transition (preserving the deallocation) instead of an allocated=>pending transition (removing the deallocation). Consistency seems pretty obvious for join points that follow a dealloc of both allocations on both paths, and any other possibility should force a conservative merger that makes both allocations undeallocatable.

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
@swift-ci Please test macOS

**Review by eeckstein — APPROVED** [review]
lgtm

**Review by hborla — APPROVED** [review]
