### PR TITLE
[Diagnostics] Fix a few issues with existential type mismatches

### LINKED ISSUE #83991: Failed to produce diagnostic for invalid metatype to existential metatype conversion
The following fails to produce a diagnostic:

```swift
protocol P {}

func bar<T>(_ x: T) -> T.Type {}
func foo(_ x: P.Type) { }
foo(bar(0)) // error: failed to produce diagnostic for expression; please submit a bug report
```

It ought to produce the same diagnostic as:

```swift
foo(Int.self) // error: cannot convert value of type 'Int.Type' to expected argument type 'any P.Type'
```

### PR DESCRIPTION
**Pull request by xedin**
- Look through `InstanceType` while attempting to diagnose conformance failures

    Matching existential types could introduce `InstanceType` element
    at the end of the locator path, it's okay to look through them to
    diagnose the underlying issue.

- Diagnose an attempt to match non-existential type to an existential one

Resolves: https://github.com/swiftlang/swift/issues/83991
Resolves: rdar://159401910

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please smoke test

File: lib/Sema/CSSimplify.cpp [hunk 1]
```diff
@@ -8750,7 +8750,27 @@ ConstraintSystem::SolutionKind ConstraintSystem::simplifyConformsToConstraint(
...
   }
 
-  return matchExistentialTypes(type, protocol, kind, flags, locator);
+  auto result = matchExistentialTypes(type, protocol, kind, flags, locator);
+
+  if (shouldAttemptFixes() && result.isFailure()) {
+    auto *loc = getConstraintLocator(locator);
+
+    if (loc->isLastElement<LocatorPathElt::InstanceType>())
+      loc = getConstraintLocator(loc->getAnchor(), loc->getPath().drop_back());
```
Comment (hamishknight) [inline lib/Sema/CSSimplify.cpp]: Should we also handle nested cases? e.g

```swift
  func bar<T>(_ x: T) -> T.Type.Type { }
  func foo2(_ x: P.Type.Type.Type) { }
  foo2(bar(0))
```

**Review by hamishknight — APPROVED** [review]

File: lib/Sema/CSSimplify.cpp (hunk 1 above)
Comment (xedin) [reply lib/Sema/CSSimplify.cpp]: Eh, it just needs to unwrap `InstanceType` in a loop, I'll fix that here.

**Review by hamishknight — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please smoke test
