### PR TITLE
[ClangImporter] Fix NS_CLOSED_ENUM to validate raw values

### LINKED ISSUE #85701: Imported enum from NS_CLOSED_ENUM shouldn't allow arbitrary raw value
### Description

I could understand that

> Enumerations imported using the NS_ENUM macro won’t fail when you initialize one with a raw value that does not correspond to an enumeration case. This characteristic facilitates compatibility with C, which allows any value to be stored in an enumeration, including values used internally but not exposed in headers.

However, we should not allow that for `NS_CLOSED_ENUM` because it is unsafe and causes unexpected  crashes.

For example:

```objc
typedef NS_ENUM(NSInteger, IntEnum) {
    IntEnumZero,
    IntEnumOne,
};
```

Since it is imported as non-frozen enum so I have to handle `@unknown default` anyway.

```swift
if let ie = IntEnum(rawValue: 100) {
    switch ie {
    case .zero:
        print("zero")
    case .one:
        print("one")
    @unknown default:
        print("unknown")
    }
}
```

However, if I define it as `NS_CLOSED_ENUM`:

```objc
typedef NS_CLOSED_ENUM(NSInteger, IntEnum) {
    IntEnumZero,
    IntEnumOne,
};
```

It should be imported as frozen enum and only those raw values declared in the enum definition should convert successfully to the enum. Unfortunately, that’s not the case and it causes crash:

```swift
if let ie = IntEnum(rawValue: 100) {
    switch ie {
    case .zero:
        print("zero")
    case .one: // Thread 1: Fatal error: unexpected enum case 'IntEnum(rawValue: 100)'
        print("one")
    }
}
```

### Reproduction

```objc
typedef NS_CLOSED_ENUM(NSInteger, IntEnum) {
    IntEnumZero,
    IntEnumOne,
};
```

```swift
if let ie = IntEnum(rawValue: 100) {
    switch ie {
    case .zero:
        print("zero")
    case .one: // Thread 1: Fatal error: unexpected enum case 'IntEnum(rawValue: 100)'
        print("one")
    }
}
```

### Stack dump

```text
#0	0x0000000193dab0dc in _swift_runtime_on_report ()
#1	0x0000000193e91d08 in _swift_stdlib_reportFatalError ()
#2	0x0000000193ec398c in closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> () in Swift._assertionFailure(_: Swift.StaticString, _: Swift.String, flags: Swift.UInt32) -> Swift.Never ()
#3	0x0000000193e9f378 in _assertionFailure ()
#4	0x0000000193ec4734 in _diagnoseUnexpectedEnumCaseValue ()
```

### Expected behavior

`IntEnum(rawValue: 100)` returns `nil`

### Environment

swift-driver version: 1.127.14.1 Apple Swift version 6.2.1 (swiftlang-6.2.1.4.8 clang-1700.4.4.1)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by an0**
## Summary

Fixes #85701 - `NS_CLOSED_ENUM` now properly validates raw values in `init?(rawValue:)`, returning `nil` for invalid values instead of creating invalid enum instances that crash later.

## Problem

When importing C enums marked with `NS_CLOSED_ENUM` (which map to `@frozen` Swift enums), the synthesized `init?(rawValue:)` used `Builtin.reinterpretCast` without validation. This allowed creating enum instances with invalid raw values that would crash with "Fatal error: unexpected enum case" when used in switch statements.

## Solution

- **For `@frozen` enums (`NS_CLOSED_ENUM`):** Generate a switch statement that validates the raw value against all declared cases, returning `nil` for invalid values
- **For non-frozen enums (`NS_ENUM`):** Preserve existing `reinterpretCast` behavior for C compatibility

## Implementation

Modified `synthesizeEnumRawValueConstructorBody()` in `lib/ClangImporter/SwiftDeclSynthesizer.cpp` to detect frozen enums and generate switch-based validation, following the same pattern used for native Swift enums in `DerivedConformanceRawRepresentable.cpp`.

## Testing

Added comprehensive execution tests that verify:
- Valid raw values correctly initialize enum instances
- Invalid raw values return `nil` (not crash)
- Non-contiguous and negative raw values handled correctly
- Open enums still accept arbitrary values for C compatibility

## Performance

Matches native Swift enums.

### CODE REVIEW

File: test/ClangImporter/enum-closed-raw-value.swift [hunk 1]
```diff
@@ -0,0 +1,84 @@
+// RUN: %empty-directory(%t)
+// RUN: %target-build-swift %s -import-objc-header %S/Inputs/enum-closed-raw-value.h -o %t/a.out
+// RUN: %target-codesign %t/a.out
+// RUN: %target-run %t/a.out | %FileCheck %s
```
Comment (j-hui) [inline test/ClangImporter/enum-closed-raw-value.swift]: Can you please use `StdlibUnittest` and its `expectEqual()` functions, rather than pipe the output to `FileCheck`? See `test/Interop/Cxx/enum/hashable-enums.swift` for an example.

File: test/ClangImporter/enum-closed-raw-value.swift [hunk 2]
```diff
@@ -0,0 +1,84 @@
+// RUN: %empty-directory(%t)
+// RUN: %target-build-swift %s -import-objc-header %S/Inputs/enum-closed-raw-value.h -o %t/a.out
```
Comment (j-hui) [inline test/ClangImporter/enum-closed-raw-value.swift]: Can you please test this both with and without C++ interop?

File: lib/ClangImporter/SwiftDeclSynthesizer.cpp [hunk 3]
```diff
@@ -1290,11 +1335,92 @@ synthesizeEnumRawValueConstructorBody(AbstractFunctionDecl *afd,
...
+                                                  /*implicit*/ true);
+    switchParamRef->setType(param->getTypeInContext());
+
+    auto *switchStmt = SwitchStmt::create(LabeledStmtInfo(), SourceLoc(),
+                                          switchParamRef, SourceLoc(),
+                                          cases, SourceLoc(), SourceLoc(), ctx);
+
+    auto body = BraceStmt::create(ctx, SourceLoc(), {switchStmt}, SourceLoc(),
+                                  /*implicit*/ true);
+    return {body, /*isTypeChecked=*/false};
```
Comment (j-hui) [inline lib/ClangImporter/SwiftDeclSynthesizer.cpp:1389]: Can you please elaborate on why `isTypeChecked` is returned as `false` here?

File: lib/ClangImporter/SwiftDeclSynthesizer.cpp [hunk 4]
```diff
@@ -1290,11 +1335,92 @@ synthesizeEnumRawValueConstructorBody(AbstractFunctionDecl *afd,
...
+  } else {
```
Comment (j-hui) [inline lib/ClangImporter/SwiftDeclSynthesizer.cpp]: nit: no need for `else` branch, since the "then" branch returns at the end. This also minimizes the diff.

**Review by j-hui — COMMENTED** [review]
Thank you for your contribution! The compiler changes look good to me, aside from a question and a nit. I would like the test to be migrated to use `StdlibUnittest` though.

**Comment by j-hui** [comment]
@swift-ci please test

**Comment by an0** [comment]
@j-hui I've addressed all the review feedback:
  - ✅ Converted tests to StdlibUnittest framework with `expectEqual()`, `expectNil()`, etc.
  - ✅ Added C++ interop test variant (two RUN lines)
  - ✅ Removed unnecessary else branch in SwiftDeclSynthesizer.cpp
  - ✅ Added comments explaining `isTypeChecked` reasoning for both code paths

File: lib/ClangImporter/SwiftDeclSynthesizer.cpp [hunk 5]
```diff
@@ -1290,10 +1335,95 @@ synthesizeEnumRawValueConstructorBody(AbstractFunctionDecl *afd,
...
+      caseReinterpreted->setThrows(nullptr);
+
+      auto *caseAssign = new (ctx) AssignExpr(caseBodySelfRef, SourceLoc(),
+                                               caseReinterpreted, /*implicit*/ true);
+      caseAssign->setType(TupleType::getEmpty(ctx));
+
+      auto *caseBody = BraceStmt::create(ctx, SourceLoc(), {caseAssign},
+                                         SourceLoc(), /*implicit*/ true);
+
+      auto *caseStmt = CaseStmt::createImplicit(ctx, CaseParentKind::Switch,
```
Comment (AdamCmiel) [inline lib/ClangImporter/SwiftDeclSynthesizer.cpp]: Great contribution! You could save a few bytes by generating one case statement with each known case as a series of labels, as their bodies are the same (reinterpret cast)

equivalent to the source:
```
switch rawValue {
case .first, .second, third:
  reinterpretCast
default:
  return nil
}
```

function merging may consolidate these blocks on the back end but better not to emit them in the first place

Comment (an0) [reply lib/ClangImporter/SwiftDeclSynthesizer.cpp]: Good suggestion! I've consolidated all the case labels into a single `CaseStmt` to reduce code duplication. The switch now generates a combined case instead of separate cases with identical bodies.

**Comment by an0** [comment]
@j-hui could you take another look?

**Comment by j-hui** [comment]
@swift-ci please test

File: lib/ClangImporter/SwiftDeclSynthesizer.cpp [hunk 6]
```diff
@@ -1247,7 +1247,52 @@ SwiftDeclSynthesizer::makeIndirectFieldAccessors(
...
+/// For frozen (closed) enums, this generates:
+///   init?(rawValue: RawType) {
+///     switch rawValue {
+///     case <value1>:
+///       self = Builtin.reinterpretCast(rawValue)
+///     case <value2>:
+///       self = Builtin.reinterpretCast(rawValue)
+///     ...
+///     default:
+///       return nil
```
Comment (j-hui) [inline lib/ClangImporter/SwiftDeclSynthesizer.cpp:1289]: nit: this comment should be updated to reflect the most recent change:

```suggestion
///   init?(rawValue: RawType) {
///     switch rawValue {
///     case <value1>, <value2>, ...:
///       self = Builtin.reinterpretCast(rawValue)
///     default:
///       return nil
```

File: lib/ClangImporter/SwiftDeclSynthesizer.cpp [hunk 7]
```diff
@@ -1290,10 +1335,73 @@ synthesizeEnumRawValueConstructorBody(AbstractFunctionDecl *afd,
                                      /*implicit*/ true);
   assign->setType(TupleType::getEmpty(ctx));
 
+  // Check if the enum is frozen (closed). If so, we need to validate
+  // that the raw value is one of the declared cases.
+  bool isFrozen = enumDecl->getAttrs().hasAttribute<FrozenAttr>();
+
+  if (isFrozen) {
+    // For frozen enums, generate a switch statement to validate the raw value
+    SmallVector<CaseStmt *, 8> cases;
```
Comment (j-hui) [inline lib/ClangImporter/SwiftDeclSynthesizer.cpp]: You now only ever push a constant number of cases, so this can be shrunk:

```suggestion
    SmallVector<CaseStmt *, 2> cases;
```

Using a `SmallVector` here is actually unnecessary because you don't even need to allocate, so you could consider just using a fixed-size array, but I'm not sure what `SwitchStmt::create()` expects/is able to take. IMO the cleanest would be to eliminate `cases` altogether and pass `{validCase, defaultCase}` directly, but I'm not sure whether that will or if you'll need to stack-allocate some array first.

**Review by j-hui — APPROVED** [review]
Thanks for the ping @an0 , this looks really great!

I just have a couple of nits that I would still like you to address before merging, but approve of this PR overall.

Feel free to ping me to help you merge if you don't have permissions to do so yourself.

File: lib/ClangImporter/SwiftDeclSynthesizer.cpp (hunk 7 above)
Comment (hnrklssn) [reply lib/ClangImporter/SwiftDeclSynthesizer.cpp]: `SwitchStmt::create()` takes an `ArrayRef`, so `{validCase, defaultCase}` should work

Comment (an0) [reply lib/ClangImporter/SwiftDeclSynthesizer.cpp]: Thanks for the feedback! I've updated the doc comment to reflect the consolidated case structure and eliminated the SmallVector by passing {validCase, defaultCase} directly to SwitchStmt::create().

**Comment by AdamCmiel** [comment]
is this initializer called on the code path of an `@objc func takes(anEnumCase: SomeClosedEnum)` ? What happens if that is called from objc with a value outside of the enumeration? Is it unexpectedly nil on the Swift side? The zero case (probably worse?)? A crash? Can you add a test case for that behavior?

**Comment by an0** [comment]
> is this initializer called on the code path of an `@objc func takes(anEnumCase: SomeClosedEnum)` ? What happens if that is called from objc with a value outside of the enumeration? Is it unexpectedly nil on the Swift side? The zero case (probably worse?)? A crash? Can you add a test case for that behavior?

`init(rawValue:)` is not called if ObjC passes in the enum to a Swift function.

ObjC side passing invalid value is a programmer error and it should crash.

BTW, Clang's `-Wassign-enum` catches `takes(12345);` with `Warning: Integer constant not in range of enumerated type 'enum SomeClosedEnum'`.

Just like any tools, we still can shoot ourselves in the foot if we try hard enough:
`takes((SomeClosedEnum)12345);`
It is intentionally breaking things using unsafe mechanisms. We can even do something similar in Swift by using unsafeBitCast. I won’t blame tooling for not catching it.

File: lib/ClangImporter/SwiftDeclSynthesizer.cpp (hunk 7 above)
Comment (an0) [reply lib/ClangImporter/SwiftDeclSynthesizer.cpp]: > Feel free to ping me to help you merge if you don't have permissions to do so yourself.

I think you are right, I don't see any button to merge it, so I need your help.

Comment (an0) [reply lib/ClangImporter/SwiftDeclSynthesizer.cpp]: > > Feel free to ping me to help you merge if you don't have permissions to do so yourself.
> 
> I think you are right, I don't see any button to merge it, so I need your help.

Ping @j-hui

**Comment by j-hui** [comment]
@swift-ci please test

**Comment by j-hui** [comment]
@AdamCmiel just wanted to double-check that this PR has your approval too before I merge (it LGTM but I want to confirm your concerns were addressed too)

**Comment by AdamCmiel** [comment]
Looks great!

**Comment by an0** [comment]
@j-hui thanks for merging it! Do you have any idea when it will be released?

**Comment by j-hui** [comment]
@an0 my pleasure!

To your question, it depends on what you mean by "release." You should able to try out in a nightly toolchain from swift.org within a few days, but I'm not sure what the timeline will be like for it to land in a stable toolchain.

There's already a release/6.3 branch, which is the upcoming compiler version, but that doesn't include this patch, so it won't be until the compiler version after that.

**Comment by grynspan** [comment]
Does this resolve https://github.com/swiftlang/swift/issues/58272?

**Comment by an0** [comment]
> Does this resolve https://github.com/swiftlang/swift/issues/58272?

Yes. You can mark your report as dup of #85701
