### PR TITLE
[ASTGen]: Assert that the position is within buffer bounds for BridgedSourceLoc

### LINKED ISSUE #68610: Assert that position is within buffer bounds in `BridgedSourceLoc.init`
Currently, we construct a null location if the input position is out of bounds, meaning the position is invalid or the buffer is null/wrong. Neither is ever expected to happen in ASTGen, and if it does, we don’t want it to go unnoticed or cause a less informative failure downstream.

### PR DESCRIPTION
**Pull request by saehejkang**
Addition of an `assert` if the position is within buffer bounds added to ` BridgeSourceLoc.init`.

Resolves #68610

### CODE REVIEW

File: lib/ASTGen/Sources/ASTGen/Bridge.swift [hunk 1]
```diff
@@ -34,6 +34,7 @@ extension BridgedSourceLoc {
   ) {
     if let start = buffer.baseAddress,
       position.utf8Offset >= 0 && position.utf8Offset < buffer.count {
+      assert(position.utf8Offset >= 0 && position.utf8Offset < buffer.count)
```
Comment (AnthonyLatsis) [inline lib/ASTGen/Sources/ASTGen/Bridge.swift:37]: This assertion will never be tripped.

Comment (saehejkang) [reply lib/ASTGen/Sources/ASTGen/Bridge.swift:37]: is this `if-else` statement ever even reachable, because the issue says neither is ever expected? So how would we assert for something in a place that it is never tripped.

Comment (AnthonyLatsis) [reply lib/ASTGen/Sources/ASTGen/Bridge.swift:37]: There's a difference between expectation and reality though, right? We want to assert precisely because we never expect this condition to fail, instead of retuning a null location whenever it happens to fail. In other words, we want this condition to become part of the initializer's contract.

Currently, the assertion is placed along a path where the asserted condition is known to be true, and will never fulfill its purpose.

Comment (saehejkang) [reply lib/ASTGen/Sources/ASTGen/Bridge.swift:37]: so the `init` of `BridgedSourceLoc` becomes

```swift
  init(
    at position: AbsolutePosition,
    in buffer: UnsafeBufferPointer<UInt8>,
    ast: Bool
  ) {
```
And whenever we are declaring any `BridgedSourceLoc` we would need to pass in the `assert`? Which in this case is checking the position bounds?

Comment (AnthonyLatsis) [reply lib/ASTGen/Sources/ASTGen/Bridge.swift:37]: Not quite. What I mean is a plain old assertion inside the `init`. Currently, we construct a null location when the position is out of bounds. Instead, we want to assert that the given position is within bounds right from the start, and not construct a null location at all.

Did the word "contract" mislead you? When we place expectations on a function’s inputs using assertions due to not being able to enforce them at compile time, they become part of the function’s run-time contract. The contract is simply a user agreement, something that one accepts by calling the function, and that may or may not be fully documented. For instance, suppose a function is documented to do something, and to require an integer argument > 1. The developer assumes responsibility for the documented behavior by vending the function, and the user assumes responsibility for satisfying the > 1 requirement by using the function.

Comment (saehejkang) [reply lib/ASTGen/Sources/ASTGen/Bridge.swift:37]: The user, based on the contract, is "agreeing" to pass a position that is already in bounds. The `init` right now is checking for validity of the position with the `if-else`, but we are "expecting" that it will always be set to a valid location and NEVER reach the `else`, which sets it the location to `null`. 

But, in reality we are never 100% that the position will ALWAYS be in bounds, so we are asserting from the get go of `init` and that way it becomes a part of the function's run time contract and errors out?

Comment (AnthonyLatsis) [reply lib/ASTGen/Sources/ASTGen/Bridge.swift:37]: Yep!

@ahoppen Did you suggest an assert rather than a precondition because this is a hot path?

Comment (ahoppen) [reply lib/ASTGen/Sources/ASTGen/Bridge.swift:37]: I said assertion because I didn’t actually think about whether I preferred an assertion or precondition. I just chatted to @bnbarham  and @rintaro and we prefer `precondition` and want to follow the same paradigm as in swift-syntax

https://github.com/apple/swift-syntax/blob/806c4732347d34b645ec8ec357914d6c3e3716ba/Sources/SwiftSyntax/Assert.swift#L13-L23

Comment (saehejkang) [reply lib/ASTGen/Sources/ASTGen/Bridge.swift:37]: The `precondition` will be checking the bounds of the buffer and the location will be set to a `non-null` value if it passes.

```swift
extension BridgedSourceLoc {
  /// Form a source location at the given absolute position in `buffer`.
  init(
    at position: AbsolutePosition,
    in buffer: UnsafeBufferPointer<UInt8>
  ) {
    precondition(position.utf8Offset >= 0 && position.utf8Offset < buffer.count)
    self = SourceLoc_advanced(BridgedSourceLoc(raw: buffer.baseAddress), SwiftInt(position.utf8Offset))
  }
}
```

Comment (ahoppen) [reply lib/ASTGen/Sources/ASTGen/Bridge.swift:37]: That looks good. Can you push your changes?

**Review by ahoppen — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

File: lib/ASTGen/Sources/ASTGen/Bridge.swift [hunk 2]
```diff
@@ -32,12 +32,8 @@ extension BridgedSourceLoc {
...
     in buffer: UnsafeBufferPointer<UInt8>
   ) {
-    if let start = buffer.baseAddress,
-      position.utf8Offset >= 0 && position.utf8Offset < buffer.count {
-      self = SourceLoc_advanced(BridgedSourceLoc(raw: start), SwiftInt(position.utf8Offset))
-    } else {
-      self = nil
-    }
+    precondition(position.utf8Offset >= 0 && position.utf8Offset < buffer.count)
+    self = SourceLoc_advanced(BridgedSourceLoc(raw: buffer.baseAddress), SwiftInt(position.utf8Offset))
```
Comment (AnthonyLatsis) [inline lib/ASTGen/Sources/ASTGen/Bridge.swift:36]: I think we should force-unwrap `buffer.baseAddress`. We used to fall back to an invalid location if it was `nil` and now we're just letting it slip through.

Comment (saehejkang) [reply lib/ASTGen/Sources/ASTGen/Bridge.swift:36]: something like this?

```swift
extension BridgedSourceLoc {
  /// Form a source location at the given absolute position in `buffer`.
  init(
    at position: AbsolutePosition,
    in buffer: UnsafeBufferPointer<UInt8>?
  ) {
    precondition(position.utf8Offset >= 0 && position.utf8Offset < buffer!.count)
    self = SourceLoc_advanced(BridgedSourceLoc(raw: buffer!.baseAddress), SwiftInt(position.utf8Offset))
  }
}
```

Comment (ahoppen) [reply lib/ASTGen/Sources/ASTGen/Bridge.swift:36]: Yes

File: lib/ASTGen/Sources/ASTGen/Bridge.swift [hunk 3]
```diff
@@ -30,14 +30,10 @@ extension BridgedSourceLoc {
   /// Form a source location at the given absolute position in `buffer`.
   init(
     at position: AbsolutePosition,
-    in buffer: UnsafeBufferPointer<UInt8>
+    in buffer: UnsafeBufferPointer<UInt8>?
```
Comment (ahoppen) [inline lib/ASTGen/Sources/ASTGen/Bridge.swift:33]: There’s no reason to change the method signature. All that matters, was unwrapping  the `baseAddress` of `buffer`. Also, instead of copy-pasting code in the comments, just push, that makes it a lot easier to review.

File: lib/ASTGen/Sources/ASTGen/Bridge.swift (hunk 2 above)
Comment (bnbarham) [reply lib/ASTGen/Sources/ASTGen/Bridge.swift]: `buffer.baseAddress` is the optional here, so @AnthonyLatsis just meant `buffer.basAddress!`

File: lib/ASTGen/Sources/ASTGen/Bridge.swift (hunk 3 above)
Comment (saehejkang) [reply lib/ASTGen/Sources/ASTGen/Bridge.swift:33]: > There’s no reason to change the method signature

the method signature needs to be changed because it says I `Cannot force unwrap value of non-optional type`. 

> copy-pasting code in the comments

I usually do this when we are having a discussion about the direction to go. If I am making changes on my own, I push them up. I can see why it makes things easier to review and can start pushing more often.

Comment (bnbarham) [reply lib/ASTGen/Sources/ASTGen/Bridge.swift:33]: Posted after it was already resolved in the other thread but:

> buffer.baseAddress is the optional here, so @AnthonyLatsis just meant buffer.baseAddress!

**Review by ahoppen — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please smoke test
