### PR TITLE
Include extended typealias in index data

### LINKED ISSUE #64594: Index data usr wrong when extending a typealias
With this code:

```swift
// ModuleC
public struct Root<T> {}

// ModuleB
import ModuleC
public typealias Alias = Root<Int>

// ModuleA
import ModuleB
extension Alias {
    func empty() {}
}
```

The index data produced when building this code incorrectly references that `extension Alias` points to `ModuleC` instead of `ModuleB`. This is easiest to visualize with [indexutil-annotate](https://github.com/lyft/swift-index-store/tree/main/Sources/indexutil-annotate):

```swift
/*
       module=ModuleB=usr is c:@M@ModuleB
       v  */
import ModuleB

/*
          struct=Root=usr is s:7ModuleC4RootV
          extension.swiftExtensionOfStruct=Root=usr is s:e:s:7ModuleC4RootV0A1ASiRszlE5emptyyyF
          v  */
extension Alias {
    /*
         instanceMethod=empty()=usr is s:7ModuleC4RootV0A1ASiRszlE5emptyyyF
         v  */
    func empty() {}
}
```

Interestingly if you remove the `func empty() {}` you get what I would expect to always get:

```swift
/*
       module=ModuleB=usr is c:@M@ModuleB
       v  */
import ModuleB

/*
          typealias=Alias=usr is s:7ModuleB5Aliasa
          v  */
extension Alias {}
```

Note that in the first example we see no usrs containing `ModuleC` at all (outside of the import itself), but in the second example we see the alias correctly has the `ModuleB` definition.

**Steps to reproduce**

Using this project: [reproextension.zip](https://github.com/apple/swift/files/11057050/reproextension.zip) and [`indexutil-annotate`](https://github.com/lyft/swift-index-store/tree/main/Sources/indexutil-annotate):

1. `swift build`
2. `indexutil-annotate .build/debug/index/store/ Sources/ModuleA/ModuleA.swift`

You can also inspect the record naively with `strings` to see there are no other string references to `ModuleB`:

```
% strings $(find .build/debug/index/store/v5/records -name "ModuleA.swift*")
IDXR
ModuleBc:@M@ModuleB
Roots:7ModuleC4RootVL
Roots:e:s:7ModuleC4RootV0A1ASiRszlE5emptyyyF
empty()s:7ModuleC4RootV0A1ASiRszlE5emptyyyF
```

**Expected behavior**

The index should have a reference to ModuleB, as it directly depends on it, but it does not, making it appear that the import for ModuleB can be removed.

**Environment**
- Swift compiler version info swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
- Xcode version info Xcode 14.2 Build version 14C18

I also tested with Swift @ 1b13b598bfdb3fad418dc86fab94f90e4f114c5e

### PR DESCRIPTION
**Pull request by keith**
Previously only the type underlying the typealias was included in the index data. Now the extension of a typealias includes 2 entries, 1 for the underlying type and one for the typealias definition.

Fixes https://github.com/apple/swift/issues/64594

### CODE REVIEW

**Comment by keith** [comment]
@swift-ci please test

**Comment by keith** [comment]
I'm actually not sure if including the underlying type in the index data makes the most sense here, judging by https://github.com/apple/swift/commit/bd5f5d80e41978d6b614f67e8f1ace62ab9a535a it might have just been a side effect of a refactor. I just wasn't sure if it would be safe to remove that case

File: lib/Index/Index.cpp [hunk 1]
```diff
@@ -1504,6 +1504,13 @@ bool IndexSwiftASTWalker::reportExtension(ExtensionDecl *D) {
   if (!startEntity(D, Info, /*IsRef=*/false))
     return false;
 
+  if (auto *DR = dyn_cast_or_null<DeclRefTypeRepr>(D->getExtendedTypeRepr()))
```
Comment (keith) [inline lib/Index/Index.cpp:1507]: I assume there's a better way to do this that I hope someone can advise me on

Comment (bnbarham) [reply lib/Index/Index.cpp:1507]: Rather than `getNominalType` above, could we grab `getExtendedType` and then use `reportRelatedTypeRef` instead of `reportRelatedRef` which would then also handle adding the implicit reference to the underlying NTD?

Comment (keith) [reply lib/Index/Index.cpp]: Nice! I updated to do this but I don't think I could entirely remove the `getNominalType` call since other functions require that? Am I missing something there?

File: lib/Index/Index.cpp [hunk 2]
```diff
@@ -1386,6 +1386,7 @@ bool IndexSwiftASTWalker::reportRelatedTypeRef(const TypeLoc &Ty, SymbolRoleSet
     if (auto *VD = declRefTR->getBoundDecl()) {
       if (auto *TAD = dyn_cast<TypeAliasDecl>(VD)) {
         IndexSymbol Info;
+        Info.roles |= Relations;
```
Comment (keith) [inline lib/Index/Index.cpp:1389]: This feels like it might be a big change but otherwise the typealias was never included as the passed relation, so the index entry was just a reference, but never more specific like it's the base of the type etc

**Comment by keith** [comment]
@swift-ci please test

File: lib/Index/Index.cpp (hunk 2 above)
Comment (bnbarham) [reply lib/Index/Index.cpp:1389]: Hmmm. I don't feel super strongly about this, but it does feel pretty odd to me. Given:
```
struct A {}
typealias SomeAlias = A
extension SomeAlias {}
```

This would add a `RelationExtendedBy` on `SomeAlias` (and on the implicit reference `A`). That feels a little odd to me. Did you need it to be more specific?

File: lib/Index/Index.cpp (hunk 1 above)
Comment (bnbarham) [reply lib/Index/Index.cpp]: Not missing anything, I just didn't notice it being used elsewhere when I was looking at it :).

File: lib/Index/Index.cpp (hunk 2 above)
Comment (keith) [reply lib/Index/Index.cpp:1389]: I think that example is actually correct? In that case it looks like this:

```swift
/*
       constructor=init()=s:3foo1AVACycfc=definition, implicit, childOf
       struct=A=s:3foo1AV=definition
       v  */
struct A {}
/*
          typealias=SomeAlias=s:3foo9SomeAliasa=definition
          |           struct=A=s:3foo1AV=reference
          v           v  */
typealias SomeAlias = A
/*
          typealias=SomeAlias=s:3foo9SomeAliasa=reference, extendedBy
          struct=A=s:3foo1AV=reference, implicit, extendedBy
          extension.swiftExtensionOfStruct=A=s:e:s:3foo1AVAAyyF=definition
          v  */
extension SomeAlias {
    /*
         instanceMethod=foo()=s:3foo1AVAAyyF=definition, childOf
         v  */
    func foo() {}
}
```

And since you can technically call `foo()` on an `A` it seems fair that it is implicitly extended by? As in because this compiles:

```swift
struct A {}
typealias SomeAlias = A
extension SomeAlias {
    func foo() {}
}

let a = A()
a.foo()
```

Comment (keith) [reply lib/Index/Index.cpp:1389]: Oh sorry, yea you mean the other way around, the typealias being `extendedBy`. That one is a bit weirder I agree. Conceptually it does seem to me like we are extending the typealias, but I guess practically speaking that's not really happening. I think the baseOf case is more clear, especially if you wanted to try to build a graph of these to trace things back. This isn't a hugely core part of this change so we could drop it if you want.

Comment (bnbarham) [reply lib/Index/Index.cpp:1389]: My preference would be that `A` gets an implicit `extendedBy` and `SomeAlias` just gets a reference, especially if you don't actually have a use case in mind where you need `SomeAlias` to be `extendedBy` at the moment.

**Comment by keith** [comment]
@swift-ci please test

File: lib/Index/Index.cpp (hunk 2 above)
Comment (keith) [reply lib/Index/Index.cpp]: sounds good, done

**Comment by keith** [comment]
@swift-ci please test Windows Platform

File: test/Index/roles.swift [hunk 3]
```diff
@@ -499,3 +499,18 @@ protocol WithPrimary<Assoc> {
...
+typealias Alias = Root // CHECK: [[@LINE]]:11 | type-alias/Swift | Alias | [[Alias_USR:.*]] | Def | rel: 0
+
+extension Alias {
+  // CHECK: [[@LINE-1]]:11 | type-alias/Swift | Alias | [[Alias_USR:.*]] | Ref | rel: 0
+  // CHECK: [[@LINE-2]]:11 | struct/Swift | Root | [[Root_USR:.*]] | Ref,Impl,RelExt | rel: 1
+  func empty() {}
+}
+
+extension Root {
+  // CHECK: [[@LINE-1]]:11 | struct/Swift | Root | [[Root_USR:.*]] | Ref,RelExt | rel: 1
```
Comment (bnbarham) [inline test/Index/roles.swift:514]: I'd hope we have a test for this already, suppose there's no harm in an extra one though 😅

**Review by bnbarham — APPROVED** [review]
LGTM. I'd prefer the commits to be collapsed unless you have a reason you'd prefer not to.

File: test/Index/roles.swift (hunk 3 above)
Comment (keith) [reply test/Index/roles.swift:514]: hrm i'll drop it actually though, I think there was a point in having it in an earlier change

**Comment by keith** [comment]
Yep I was planning on squashing and merging but I will do it manually

File: test/Index/roles.swift [hunk 4]
```diff
@@ -499,3 +499,18 @@ protocol WithPrimary<Assoc> {
...
 // CHECK-NEXT: RelChild | protocol/Swift | WithPrimary | {{.*}}
 }
+
+struct Root {} // CHECK: [[@LINE]]:8 | struct/Swift | Root | [[Root_USR:.*]] | Def | rel: 0
+
+typealias Alias = Root // CHECK: [[@LINE]]:11 | type-alias/Swift | Alias | [[Alias_USR:.*]] | Def | rel: 0
+
+extension Alias {
+  // CHECK: [[@LINE-1]]:11 | type-alias/Swift | Alias | [[Alias_USR:.*]] | Ref | rel: 0
+  // CHECK: [[@LINE-2]]:11 | struct/Swift | Root | [[Root_USR:.*]] | Ref,Impl,RelExt | rel: 1
```
Comment (keith) [inline test/Index/roles.swift:509]: just realized there's a bug here too, this is re-assigning that value from above, but it should be validating against it, fixing now

**Comment by keith** [comment]
@swift-ci please test and merge
