### PR TITLE
[Sema] Move anonymous closure argument check from parser to semantic analysis

### LINKED ISSUE #54030: [SR-11619] Spurious error "anonymous closure argument not contained in a closure" in #if false
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-11619      |
   |Radar             | None         |
   |Original Reporter | @DougGregor      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, StarterBug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: fce0a8071c3d74595e44fbbd42aa3fa0

  </details>

**Issue Description:**

This code currently produces an error, but shouldn't:

``` java
#if false
if $0 { } // error: anonymous closure argument not contained in a closure
#endif
```

### PR DESCRIPTION
**Pull request by yyoungbash**
Resolves https://github.com/swiftlang/swift/issues/54030.

### CODE REVIEW

**Review by slavapestov — APPROVED** [review]

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
Does ASTGen emit this diagnostic? If so it needs to be removed there as well.

File: test/Sema/issue-54030.swift [hunk 1]
```diff
@@ -0,0 +1,9 @@
+// RUN: %target-typecheck-verify-swift
```
Comment (slavapestov) [inline test/Sema/issue-54030.swift]: It might be better to put this test in expr/closure and give it a better name, or merge it with one of the existing test files.

**Comment by slavapestov** [comment]
Looks like some existing tests fail:
```
11:52:54  Failed Tests (2):
11:52:54    Swift(linux-x86_64) :: Parse/dollar_identifier.swift
11:52:54    Swift(linux-x86_64) :: expr/closure/closures.swift
```
Please run the test suite locally and take a look.

**Comment by yyoungbash** [comment]
> Does ASTGen emit this diagnostic? If so it needs to be removed there as well.

It produces `fatalError()` here [Expr.swift](https://github.com/swiftlang/swift/blob/d7ae15565d28ba1ad14f64954d5b316d647c78f1/lib/ASTGen/Sources/ASTGen/Exprs.swift#L568)

> Please run the test suite locally and take a look.

Sure, I'll update the PR tomorrow.

**Comment by yyoungbash** [comment]
@slavapestov All tests passing now. Could you please run the ci?

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by yyoungbash** [comment]
I've raised a pr in https://github.com/swiftlang/llvm-project/pull/12040 addressing the the failure. once it's merged the ci should pass.

**Comment by slavapestov** [comment]
https://github.com/swiftlang/llvm-project/pull/12040
@swift-ci Please smoke test

**Comment by yyoungbash** [comment]
@slavapestov  macos timed out. Could you please retrigger ? Also check https://github.com/swiftlang/llvm-project/pull/12040

**Comment by yyoungbash** [comment]
@slavapestov ping

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by yyoungbash** [comment]
@MaxDesiatov could you please run CI with https://github.com/swiftlang/llvm-project/pull/12040?

**Comment by jamieQ** [comment]
https://github.com/swiftlang/llvm-project/pull/12040
@swift-ci Please smoke test
