### PR TITLE
[Caching] Allow prefix mapping for generated bridging header

### LINKED ISSUE #84088: [Caching] Swift caching with prefix mapping doesn't work when having a bridging header
### Description

Thread: https://forums.swift.org/t/about-swift-shared-cache-across-machines/

Reported prefix mapping failed to remap chained bridging header into a canonical location so there can't be a cache hit when source directory is moved.

### Reproduction

Test project:
https://github.com/Coder-Star/cache_test

Build from two different locations and different source location can't cache hit all the tasks.

### Expected behavior

All cache hit.

### Environment

Xcode 26 beta 2

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by cachemeifyoucan**
To allow prefix mapping of the bridging header to achieve cache hit when source files are located in different location, the generated chained bridging header should not include absolute paths of the headers. Fix the problem by concat the chained bridging header together.

Fixes: https://github.com/swiftlang/swift/issues/84088

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
@swift-ci please smoke test

File: lib/DependencyScan/ModuleDependencyScanner.cpp [hunk 1]
```diff
@@ -1665,56 +1657,89 @@ llvm::Error ModuleDependencyScanner::performBridgingHeaderChaining(
...
   }
 
-  if (!hasBridgingHeader)
-    return llvm::Error::success();
+  // Handle bridging header in main module.
+  auto mainModuleDeps = cache.findKnownDependency(rootModuleID);
+  auto *mainModule = mainModuleDeps.getAsSwiftSourceModule();
+  assert(mainModule && "expect main module to be a swift source module");
+  std::unique_ptr<llvm::MemoryBuffer> sourceBuffer;
+  bool needChainedHeader = !sourceBuf.empty();
```
Comment (artemcm) [inline lib/DependencyScan/ModuleDependencyScanner.cpp]: This threw me off because `sourceBuf` and way too close to `sourceBuffer` declared on the line above and I was confused how this was expected to work.

File: lib/DependencyScan/ModuleDependencyScanner.cpp [hunk 2]
```diff
@@ -1665,56 +1657,89 @@ llvm::Error ModuleDependencyScanner::performBridgingHeaderChaining(
...
+    if (auto srcBuf = FS->getBufferForFile(
+            *mainModule->textualModuleDetails.bridgingHeaderFile))
+      sourceBuffer = std::move(*srcBuf);
+    else
+      return llvm::errorCodeToError(srcBuf.getError());
+  } else {
+    // There are bridging header needed to be chained. Append the bridging
+    // header from main module if needed and create use a new source buffer.
+    if (mainModule->textualModuleDetails.bridgingHeaderFile) {
+      auto srcBuf = FS->getBufferForFile(
```
Comment (artemcm) [inline lib/DependencyScan/ModuleDependencyScanner.cpp:1709]: There's `sourceBuf`, `sourceBuffer` and `srcBuf` in one scope here.

File: lib/DependencyScan/ModuleDependencyScanner.cpp [hunk 3]
```diff
@@ -1774,9 +1800,22 @@ llvm::Error ModuleDependencyScanner::performBridgingHeaderChaining(
         }
         mainModuleDeps.updateBridgingHeaderCommandLine(
             bridgingHeaderCommandLine);
+        // Fixup headerFileInputs to include bridging header and not include
+        // generated bridging header.
```
Comment (artemcm) [inline lib/DependencyScan/ModuleDependencyScanner.cpp]: Could you please add a one-sentence explanation as to why.

**Review by artemcm — APPROVED** [review]

**Comment by cachemeifyoucan** [comment]
@swift-ci please smoke test

**Comment by cachemeifyoucan** [comment]
https://github.com/swiftlang/swift-docc/pull/1298
@swift-ci test Windows platform

**Comment by cachemeifyoucan** [comment]
@swift-ci test Windows platform
