### PR TITLE
[CSOptimizer] Score candidate matches that require easure lower for o…

### LINKED ISSUE #88193: Source break between Swift 6.2.4 and 6.3
### Description

discussed on https://forums.swift.org/t/source-break-between-swift-6-2-4-and-6-3/85658 

there is a source break in the Swift 6.3 release compiler, with respect to Swift 6.2.4.

in all versions of Swift since Swift 5, an operator overload on a type `T` with signature 
`(Self, Self) -> Whatever` 
would always be preferred over an operator with signature 
`(Self, any T) -> Whatever`.

that meant that a program like this

```swift
extension Error where Self: Equatable {
    private func equals(_ other: any Error) -> Bool {
        (other as? Self).map { $0 == self } ?? false
    }
}
extension Error {
    static func == (lhs: Self, rhs: any Error) -> Bool {
        if let lhs: any Error & Equatable = lhs as? any Error & Equatable {
            return lhs.equals(rhs)
        } else {
            return false
        }
    }
}

struct BarbieError: Equatable, Error {}

let a: any Error = BarbieError.init()
let b: any Error = BarbieError.init()

print(a == b)
```

was well-formed and would dispatch from `(Self, any T) -> Whatever` down to `(Self, Self) -> Whatever`.

in Swift 6.3, the overload resolution precedence is reversed, `(Self, any T) -> Whatever` will be preferred over `(Self, Self) -> Whatever`. that causes the example program above to fall into infinite recursion, and crash.

an LLM-assisted search surfaced an issue reported by @Frizlab about a month ago.

https://forums.swift.org/t/source-breaking-change-in-swift-6-3/85047

that bug was blamed on literals in default arguments, but in this example, there are no literals involved.

### Reproduction

see above

### Expected behavior

see above

### Environment

$ swift --version
Swift version 6.3 (swift-6.3-RELEASE)
Target: x86_64-unknown-linux-gnu

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by xedin**
…perators

This change restores pre-6.3 operator overload selection behavior.

The same is done for cases when candidate matches all of the requirements placed on the generic parameter and optional injections because operators historically favored exact/subtype matches in concrete overloads above all else.

Resolves: https://github.com/swiftlang/swift/issues/88193
Resolves: rdar://173728495

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
Source compat failures are unrelated and happening on main as well.

File: lib/Sema/CSOptimizer.cpp [hunk 1]
```diff
@@ -1032,8 +1032,11 @@ scoreCandidateMatch(ConstraintSystem &cs,
 
   // Conversion from a concrete type to its existential value.
   if (paramType->isExistentialType()) {
-    if (isSubtypeOfExistentialType(candidateType, paramType))
-      return 100;
+    if (isSubtypeOfExistentialType(candidateType, paramType)) {
+      // Operators always prefer exact and subtype matches. Erasure should
+      // shouldn't be scored higher than a match on a generic parameter.
+      return choice->isOperator() ? 90 : 100;
```
Comment (hamishknight) [inline lib/Sema/CSOptimizer.cpp:1038]: We have this logic for `isOperator() ? 90 : 100` in a few other places in this function, would it be worth factoring it out? i.e could be `return subtypeMatch(/*preferExactForOperator*/ true)`

**Review by hamishknight — APPROVED** [review]
I would like @slavapestov to also take a look, but this looks reasonable to me

File: lib/Sema/CSOptimizer.cpp (hunk 1 above)
Comment (xedin) [reply lib/Sema/CSOptimizer.cpp:1038]: Yeah, maybe it's time to normalize the representation of these numbers...

Comment (xedin) [reply lib/Sema/CSOptimizer.cpp:1038]: I'll look into that separately.

**Review by slavapestov — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform
