### PR TITLE
[Distributed] Map into context computed property result type for SerReq checking

### LINKED ISSUE #75466: Distributed actors: Incorrect error for associated type in protocol
### Description

Trying to build protocols for distributed actors and getting error for associatedtype

### Reproduction

```swift
import Distributed
import DistributedCluster

protocol Recipient: DistributedActor where ActorSystem == ClusterSystem {
  associatedtype Info: Sendable & Codable
  distributed var info: Info { get async } // Result type 'Self.Info' of distributed property 'info' does not conform to serialization requirement 'Codable'
}
```

### Expected behavior

Getter should work properly, changing to concrete type or `distributed func getInfo() async throws -> Info` works.

### Environment

Xcode 16 Beta 4 (16A5211f)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ktoso**
We were doing the right thing for functions but didn't for computed properties, and thus the type checking serialization req would fail for computed properties.

resolves https://github.com/swiftlang/swift/issues/75466 
resolves rdar://132467762

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please smoke test

File: lib/Sema/TypeCheckDistributed.cpp [hunk 1]
```diff
@@ -420,7 +420,10 @@ static bool checkDistributedTargetResultType(
   if (auto func = dyn_cast<FuncDecl>(valueDecl)) {
     resultType = func->mapTypeIntoContext(func->getResultInterfaceType());
   } else if (auto var = dyn_cast<VarDecl>(valueDecl)) {
-    resultType = var->getInterfaceType();
+    // Distributed computed properties are always getters,
+    // so get the get accessor for mapping the type into context:
+    auto getter = var->getAccessor(swift::AccessorKind::Get);
+    resultType = getter->mapTypeIntoContext(var->getInterfaceType());
```
Comment (xedin) [inline lib/Sema/TypeCheckDistributed.cpp:426]: AccessorDecls inherits from `FuncDecl`, you can do something like before retrieving the result type:
```
if (auto *var = dyn_cast<VarDecl>(valueDecl)) {
  valueDecl = var->getAccessor(swift::AccessorKind::Get);
}
```

And the mapping would be handled by `FuncDecl` branch.

Comment (ktoso) [reply lib/Sema/TypeCheckDistributed.cpp:426]: Nice, thanks! Will do
