### PR TITLE
[CXX-Interop] Fix NS_OPTION related label transformations and assertion failures

### LINKED ISSUE #63671: Method UIControl.addTarget(_:action:for:) imported incorrectly when C++ interop is enabled.
**Description**
The method `UIControl.addTarget(_:action:for:)` is imported as `UIControl.addTarget(_:action:forControlEvents:)` when C++ interop is enabled.

**Steps to reproduce**

Use the following lit test. The build configuration needs to have iOS targets enabled for this to work.

```
// RUN: %target-swift-frontend -enable-experimental-cxx-interop -typecheck %s

// REQUIRES: OS=ios

import UIKit

public class Foo : NSObject {
    @objc
    public func callMe() {}

    public func checkMe() {
        let control = UIControl()
        control.addTarget(self, action: #selector(callMe), for: [.touchDown])
    }
}
```

The test will fail with the following:

```
.../swift-source/swift/test/Interop/Cxx/objc-correctness/control-event-omit-needless-words.swift:13:26: error: incorrect argument label in call (have '_:action:for:', expected '_:action:forControlEvents:')
        control.addTarget(self, action: #selector(callMe), for: [.touchDown])
                         ^                                 ~~~
                                                           forControlEvents
```

**Expected behavior**

The test should pass. `UIControl.addTarget(_:action:for:)` is the documented and expected API for the Objective-C method.

**Environment**

Using a recent `main`.

- Swift compiler version info: Apple Swift version 5.9-dev (LLVM 50ed2bf09779f5f, Swift 55c1b6591e2bb0e) / Target: x86_64-apple-macosx13.0
- Xcode version info: Xcode 14.2 / Build version 14C18
- Deployment target:  arm64-apple-ios11.0

/cc @plotfi

### PR DESCRIPTION
**Pull request by NuriAmari**
This patch resolves https://github.com/apple/swift/issues/63671. 

The issue turned out to be two issues, and I've included a commit for each issue. The commit messages provide a more detailed explanation, but in short the issues were:

- We were assuming enums are always imported as `NominalTypeDecl`s, which isn't the case
- The logic for "trimming" of parameter labels based on NS_OPTION parameter types needed adjusting

### CODE REVIEW

File: test/Interop/Cxx/enum/c-enums-NS_OPTIONS-typecheck-name-differs-between-versions.swift [hunk 1]
```diff
@@ -0,0 +1,9 @@
+// RUN: %target-swift-frontend -I %S/Inputs -enable-experimental-cxx-interop -typecheck %s
+// REQUIRES: objc_interop
+
+import CenumsNSOptions
+
+let foo = CFunctionReturningNSOption()
```
Comment (NuriAmari) [inline test/Interop/Cxx/enum/c-enums-NS_OPTIONS-typecheck-name-differs-between-versions.swift:6]: These parameters hit invalid cast assertions prior to this patch.

File: lib/ClangImporter/ImportDecl.cpp [hunk 2]
```diff
@@ -5756,7 +5756,8 @@ SwiftDeclConverter::getImplicitProperty(ImportedName importedName,
         assert(clangEnum.value()->getIntegerType()->getCanonicalTypeInternal() ==
                typedefType->getCanonicalTypeInternal());
         if (auto swiftEnum = Impl.importDecl(*clangEnum, Impl.CurrentVersion)) {
-          importedType = {cast<NominalTypeDecl>(swiftEnum)->getDeclaredType(), false};
```
Comment (NuriAmari) [inline lib/ClangImporter/ImportDecl.cpp:5759]: Under the right conditions, there are `TypeAliasDecls`, not `NominalTypeDecl`s.

**Comment by NuriAmari** [comment]
@swift-ci Please test

**Comment by NuriAmari** [comment]
@swift-ci Please test source compatibility

File: lib/ClangImporter/ImportDecl.cpp (hunk 2 above)
Comment (NuriAmari) [reply lib/ClangImporter/ImportDecl.cpp:5759]: Looked around a bit, if this were Objective-C, and we didn't need to play this find the anonymous tag decl for this typedef game, we are calling `getDeclaredInterfaceType`: https://github.com/apple/swift/blob/main/lib/ClangImporter/ImportType.cpp#L997. Unless something breaks, that is convincing enough for me.

**Comment by NuriAmari** [comment]
@swift-ci Please test

File: lib/ClangImporter/ImportDecl.cpp (hunk 2 above)
Comment (plotfi) [reply lib/ClangImporter/ImportDecl.cpp:5759]: Do we have any evidence to suggest that we should do `cast<NominalTypeDecl>(swiftEnum)->getDeclaredType()` for C/ObjC interop and `cast<TypeDecl>(swiftEnum)->getDeclaredInterfaceType()` for C++-Interop? I think it'd be best to keep things uniform between th two but Just wondering what would work best for either case.

Comment (NuriAmari) [reply lib/ClangImporter/ImportDecl.cpp:5759]: I don't think there is any reason for them to be different. When I said "if this were Objective-C", I didn't really mean as a consequence of the Swift compiler behaving differently with cxx-interop enabled. Since NS_OPTION is defined differently in C++-mode, we have to go from the backing typedef, to the anonymous enum, import that, then get its type. If we had the enum in the first place (as we would if NS_OPTION in C++ wasn't so weird), we'd return `getDeclaredInterfaceType` at the line I linked, so I think that is the appropriate thing to do.

As an aside, the different between the two methods seems to be related to generics, and to my knowledge, C/Objective-C/C++ enums can't be generic, so I can't imagine why they'd be imported as such. I don't think `getDeclaredType` was chosen for any particular reason, but I think @zoecarver wrote it, so I'll let him chime in if he sees fit 🙂

**Review by zoecarver — APPROVED** [review]
Looks good. Thanks!

**Comment by plotfi** [comment]
LGTM
