### PR TITLE
[SILGen]: Emit ignored loads of uninhabited lvalues to address DI edge cases

### LINKED ISSUE #74478: Constants of type Never used in switch statements do not trigger error for use of uninitialized constant, leading to runtime crash
### Description

When a constant is declared with type `Never` and subsequently used as the subject of a `switch` statement, the compiler fails to diagnose the use of an uninitialized constant, leading to a runtime crash.

### Reproduction

```swift
let x: Never
switch x { }
```

I will provide the crash message shortly; at the moment, I am not at my computer.

### Expected behavior

The compiler should produce an error.

### Environment

I believe it is 5.10.1, but I am not sure as I am not at my computer. I downloaded the release about a week ago. I will report the version as soon as I am back at my computer.

I was running Swift in an Ubuntu 24.04 container. Swift was installed to `/opt/swift`.

### Additional information

I was informed this is not intentional in [this thread on the forum](https://forums.swift.org/t/why-is-this-not-an-error/72537).

### PR DESCRIPTION
**Pull request by jamieQ**
Previously we would crash (at runtime) on this pattern:

```swift
let x: Never
switch x {}
```

This appears to be due to the fact that the switch over the uninhabited value did not result in any instructions DI considers a use being produced. This change adds special handling of this case so that we now emit a load of the value so DI correctly diagnoses the use before init.

Resolves: https://github.com/swiftlang/swift/issues/74478

### CODE REVIEW

**Comment by jamieQ** [comment]
@swift-ci smoke test macos

**Comment by jamieQ** [comment]
@swift-ci please test source compatibility

**Comment by jamieQ** [comment]
@swift-ci please test

File: lib/SILGen/SILGenExpr.cpp [hunk 1]
```diff
@@ -7628,6 +7628,19 @@ void SILGenFunction::emitIgnoredExpr(Expr *E) {
...
+    if (LE->getType()->isStructurallyUninhabited()) {
+      // If the lvalue is structurally uninhabited, we emit the load so that
+      // DI will see any uses before initialization. It should not be possible
+      // to ever really load such a value, so this should result in some sort
+      // of downstream error.
+      //
+      // Failure to do this in the past resulted in this bug:
+      // https://github.com/swiftlang/swift/issues/74478.
+
+      emitLoadOfLValue(E, std::move(lv), SGFContext::AllowImmediatePlusZero);
```
Comment (jamieQ) [inline lib/SILGen/SILGenExpr.cpp:7721]: could someone verify if it matters what SGFContext value is used here? i assume this case should always result in a downstream error so i'm inclined to think it doesn't...

**Comment by jamieQ** [comment]
@swift-ci please clean test macos

**Comment by jamieQ** [comment]
any takers to consider this edge case? @eeckstein @jckarter @kavon

**Comment by jamieQ** [comment]
@eeckstein @jckarter @kavon i'd appreciate your feedback on this

**Review by eeckstein — APPROVED** [review]
lgtm

**Comment by jamieQ** [comment]
@swift-ci please test

**Comment by jamieQ** [comment]
@swift-ci please test windows

**Comment by jamieQ** [comment]
@swift-ci test

**Comment by jamieQ** [comment]
@swift-ci test linux

**Comment by jamieQ** [comment]
@swift-ci test macos

**Comment by jamieQ** [comment]
@swift-ci smoke test linux

**Comment by jamieQ** [comment]
@swift-ci smoke test macos

**Comment by jamieQ** [comment]
validation test failures look unrelated to me, so going to merge this
