### PR TITLE
TypeCheckType: Fix existential `any` migration diagnostics for extra-modular protocols

### LINKED ISSUE #65034: Enabling upcoming feature `ExistentialAny` does not work for standard library protocols.
**Description**

Enabling upcoming feature `ExistentialAny` does not work for standard library protocols.

For example, it should produce a compile error, considering `Decoder` is a bare protocol. However, the compiler does not produce any error or warning, even though for other non-standard library protocols it produces errors and warnings correctly.
```
init(from decoder: Decoder) throws { /* ... */ }
```

**Steps to reproduce**

1. `swift repl -enable-upcoming-feature ExistentialAny`
2. put following;
```swift
protocol P {}
extension Int: P {}
```
3. put following:
```swift
let value: P = 42
```
It produces an error
```
expression failed to parse:
error: repl.swift:5:12: error: use of protocol 'P' as a type must be written 'any P'
let value: P = 42
           ^
           any P
```
4. put following;
```swift
let value: Codable = 42
```
It works!

**Expected behavior**
`Codable` should also produce a compile error, but it doesn't.

**Environment**
- Swift compiler version info 
  ```
  swiftc -version
  swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
  Target: x86_64-apple-macosx13.0
  ```
- Xcode version info 
   ```
   Xcode 14.3
   Build version 14E222b
   ```
- Deployment target: N/A

As I checked, it seems `any P` check is not working for standard library protocols without associated types including `Codable`, `Decoder`, `Encoder`, `CustomStringConvertible`, `CustomDebugStringConvertible`, `ExpressibleBy*Literal`, and so on.

Forum thread: https://forums.swift.org/t/any-p-check-doesnt-work-for-standard-library-protocols/64276

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
There are two issues:
* The evaluation of `ExistentialRequiresAnyRequest` is dependent on whether the `ExistentialAny` feature is enabled in the current compiler invocation, but the evaluation is bypassed for deserialized protocols because the result of the request is part of the serialized record. This made `existentialRequiresAny()` independent of the feature state for deserialized protocols (#65034).
* The evaluation of `ExistentialRequiresAnyRequest` must not depend on the feature state, or else is will persist in module files and override the feature state for protocols originating in those modules. In other words, the feature must not be enforced on protocols originating in a different module just because that module was compiled with the feature enabled.

Resolves #65034
___
IMO there is no reason not to accept this into 5.9, but I would also vote to take it into 5.8 because the issue affects the new migration experience for a pretty impactful upcoming feature.

### CODE REVIEW

File: include/swift/AST/Decl.h [hunk 1]
```diff
@@ -4874,8 +4874,14 @@ class ProtocolDecl final : public NominalTypeDecl {
...
-  /// with \c any. \c any is required if any of the members contain
-  /// an associated type, or if \c Self appears in non-covariant position.
+  /// with \c any. \c any is required if one of the following conditions is met
+  /// for this protocol or an inherited protocol:
+  /// - The protocol has an associated type requirement.
+  /// - `Self` appears in non-covariant position in the type signature of a
+  ///   value requirement.
+  ///
+  /// @Note This method does not take the state of language features into
+  /// account.
```
Comment (hborla) [inline include/swift/AST/Decl.h:4884]: You could also pass in the usage context into `existentialRequiresAny` so the method itself accounts for language feature state, but the `ExistentialRequiresAny` request does not. Thoughts?

Comment (AnthonyLatsis) [reply include/swift/AST/Decl.h:4884]: I was going to but that is what the serializer calls to obtain the evaluation result. I think we should rename the request to something like `HasSelfOrAssociatedTypeRequirements` and pair it with a corresponding method to use in serialization so that `existentialRequiresAny` could account for language feature state.

Comment (hborla) [reply include/swift/AST/Decl.h:4884]: 👍 that sounds like a good approach to me (and we don't need to do that as part of this PR)

**Review by hborla — APPROVED** [review]
Thank you!

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by hborla** [comment]
```
[...]
forward_trailing_closure_errors.swift -swift-version 6
--
Exit Code: 1

Command Output (stderr):
--
/Users/ec2-user/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/swift/test/expr/postfix/call/forward_trailing_closure_errors.swift:23:14: error: unexpected error produced: use of protocol 'Error' as a type must be written 'any Error'
  onError: ((Error) -> Void)? = nil,
             ^
```

Hah. That's true!

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test
