### PR TITLE
[Macros] Don't visit macro-generated extensions in `visitAuxiliaryDecls`.

### LINKED ISSUE #66916: `@Observable` Macro causes compilation error when in an `extension` of a view
**Description**

The `@Observable` macro only works on view models that are _not_ within extensions. For example this works:
```
struct MyView: View {
  ...
}

extension MyView {
  final class MyViewModel: ObservableObject {
    ...
  }
} 
```

**but this does not:**
```
extension MyView {
  @Observable final class MyViewModel {
    ...
  }
} 
```

**Steps to reproduce**

1. Create a simple view with a basic view model using the `@Observable` macro.
2. Wrap the view model in an extension of the view; this should cause the error.

**Expected behavior**
Successful compilation.

**Environment**
- Swift compiler version info: swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
  
- Xcode 15.0 Beta 
- Deployment target: iOS 17.0 Beta

### PR DESCRIPTION
**Pull request by hborla**
Macro-generated extensions are hoisted to file scope, because extensions are not valid in nested scopes. Callers of `visitAuxiliaryDecls` assume that the auxiliary decls are in the same decl context as the original, which is clearly not the case for extensions, and it leads to issues like visiting extension at the wrong time during SILGen. The extensions are already added exposed via `getTopLevelDecls()`, so we don't need to visit them as auxiliary decls.

Resolves: https://github.com/apple/swift/issues/66916, rdar://111000256

### CODE REVIEW

**Comment by hborla** [comment]
@swift-ci please smoke test

File: lib/Sema/TypeCheckMacros.cpp [hunk 1]
```diff
@@ -1446,6 +1446,16 @@ swift::expandConformances(CustomAttr *attr, MacroDecl *macro,
...
+
+    // Most other macro-generated declarations are visited and type-checked
+    // through calling 'visitAuxiliaryDecls' on the original declaration the
+    // macro is attached to. We don't do this for macro-generated extensions,
+    // because the extension is not a peer of the original declaration. Instead
+    // of requiring all callers of 'visitAuxiliarDecls' to understsand the
+    // hoisting behavior of macro-generated extensions, we simply expose the
+    // extension to 'getTopLevelDecls()' and type check the extension eagerly
+    // here.
+    TypeChecker::typeCheckDecl(extension);
```
Comment (DougGregor) [inline lib/Sema/TypeCheckMacros.cpp:1458]: Could we instead visit these at the end of TypeCheckDeclPrimary's visitation? Doing a complete check of the extension seems unnecessary here.

(Also, you have typos "visitAuxiliarDecls" and "understsand").

Comment (hborla) [reply lib/Sema/TypeCheckMacros.cpp:1458]: I suppose it's better to visit expanded extensions in TypeCheckDeclPrimary as opposed to visiting the top-level decls of `SF->getSynthesizedFile()` at the end of `TypeCheckSourceFileRequest::evaluate` because the former approach will definitely invoke the request if it hasn't already happened?

Comment (DougGregor) [reply lib/Sema/TypeCheckMacros.cpp]: I hadn't thought of `TypeCheckSourceFileRequest::evaluate`. Visiting the top-level decls of the synthesized file there should work.
