### PR TITLE
FP Parsing: Fix over-eager underflow check

### LINKED ISSUE #86462: Parsing `Float32` and `Float64` regressed on `main` snapshots on Linux
### Description

_No response_

### Reproduction

```
> container run --rm -it swiftlang/swift:nightly-6.3-noble /usr/bin/swift -e 'print(Float32("0x0.00000100000000001p-126")!)'
1e-45
> container run --rm -it swiftlang/swift:nightly-main-noble /usr/bin/swift -e 'print(Float32("0x0.00000100000000001p-126")!)'
0.0
> container run --rm -it swiftlang/swift:nightly-6.3-noble  /usr/bin/swift -e 'print(Float64("+0x0.000000000000080000000001p-1022")!)'
5e-324
> container run --rm -it swiftlang/swift:nightly-main-noble /usr/bin/swift -e 'print(Float64("+0x0.000000000000080000000001p-1022")!)'
0.0
```

### Expected behavior

Expected `Float32` and `Float64` parsing to work on `main` in the same way it works in 6.3 development snapshots.

### Environment

Reproducible only in Linux toolchains.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tbkka**
An early check for underflow was a bit too aggressive, resulting in values that would otherwise round up to the smallest subnormal failing to go through the regular rounding logic.

Resolves #86462
Resolves rdar://167942063

### CODE REVIEW

**Comment by tbkka** [comment]
@swift-ci Please test

File: stdlib/public/core/FloatingPointFromString.swift [hunk 1]
```diff
@@ -593,7 +593,7 @@ fileprivate func hexFloat(
     return .infinity(sign: sign) // Overflow
   }
 
-  if binaryExponent < targetFormat.minBinaryExponent - targetFormat.significandBits + 1 {
+  if binaryExponent < targetFormat.minBinaryExponent - targetFormat.significandBits {
```
Comment (tbkka) [inline stdlib/public/core/FloatingPointFromString.swift:596]: "If this value is so tiny that it _OBVIOUSLY_ rounds to zero, ...."

This check ensures that the full rounding logic below never has to consider ridiculous values like `0x1p-9999999999999` which might cause integer overflow.  But it was off by one, which caught values close to 1/2 of the smallest subnormal.  Such values need the full rounding analysis to determine whether they round down to zero or up to the smallest subnormal.

**Review by MaxDesiatov — APPROVED** [review]
Thanks!

**Review by kateinoigakukun — APPROVED** [review]

File: stdlib/public/core/FloatingPointFromString.swift (hunk 1 above)
Comment (tbkka) [reply stdlib/public/core/FloatingPointFromString.swift:596]: Hmm....  Actually, I think it would suffice to use a hardcoded limit:
```
if binaryExponent < -16385 - 112
```
(`-16385 - 112` is large enough to work correctly for Float80 and Float128).  That would avoid some arithmetic (thus be a tad faster) and still sufficient for the purpose here.

I'll keep that in mind for some future performance-tuning of this code.

**Comment by MaxDesiatov** [comment]
@swift-ci test macos

**Comment by MaxDesiatov** [comment]
@swift-ci test macos

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test macos

**Review by stephentyrone — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci test macos

**Comment by MaxDesiatov** [comment]
test failure in SwiftPM is unrelated
@swift-ci test macos

**Comment by MaxDesiatov** [comment]
macOS failure in SwiftPM again seems unrelated: `error: Exited with unexpected signal code 11`
@swift-ci test macos

**Comment by MaxDesiatov** [comment]
@swift-ci test macos

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test macos
