### PR TITLE
[SILGen]: fix a bug in isolated default argument handling

### LINKED ISSUE #84647: Compiler crash involving isolated default arguments and default tuple arguments
### Description

if a _static_ function contains an isolated default parameter, and is followed by a tuple-typed defaulted parameter, followed by _another_ default parameter, the compiler crashes when attempting to SILGen the function call that uses the default parameters.

### Reproduction

```swift
@MainActor
func isolatedDefaultArg<G>(_ g: G) -> G { g }

enum E {
    @MainActor
    static func crash(
        _ rvalue: Int,
        iso: Int = isolatedDefaultArg(1),
        tup: (Int, Int) =  (2, 3),
        def: Int = 3
    ) {}
}

@MainActor
func noCrash(
    _ rvalue: Int,
    iso: Int = isolatedDefaultArg(1),
    tup: (Int, Int) =  (2, 3),
    def: Int = 3
) {}

func fail() async {
    await E.crash(0) // 💥
    await noCrash(0) // ✅
}
```

### Stack dump

```text
/cefs/5a/5afd274eb51c5c731b7266ae_swift-nightly/usr/bin/swift-frontend -frontend -emit-sil -primary-file <source> -target x86_64-unknown-linux-gnu -disable-objc-interop -no-color-diagnostics -Xcc -fno-color-diagnostics -g -debug-info-format=dwarf -dwarf-version=4 -swift-version 6 -empty-abi-descriptor -enable-anonymous-context-mangled-names -file-compilation-dir /app -Xllvm --x86-asm-syntax=intel -no-auto-bridging-header-chaining -module-name output -in-process-plugin-server-path /cefs/5a/5afd274eb51c5c731b7266ae_swift-nightly/usr/lib/swift/host/libSwiftInProcPluginServer.so -plugin-path /cefs/5a/5afd274eb51c5c731b7266ae_swift-nightly/usr/lib/swift/host/plugins -plugin-path /cefs/5a/5afd274eb51c5c731b7266ae_swift-nightly/usr/local/lib/swift/host/plugins -o /app/output.s
Swift version 6.3-dev (LLVM 984f3dccb13e621, Swift 2a9d858583dc912)
Target: x86_64-unknown-linux-gnu
swift-frontend: /home/build-user/swift/lib/SILGen/SILGenApply.cpp:3210: void emitDelayedArguments(SILGenFunction &, MutableArrayRef<DelayedArgument>, MutableArrayRef<SmallVector<ManagedValue, 4>>): Assertion `!siteArgs[argIndex] && "overwriting an existing arg during delayed isolated " "argument emission"' failed.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /cefs/5a/5afd274eb51c5c731b7266ae_swift-nightly/usr/bin/swift-frontend -frontend -emit-sil -primary-file <source> -target x86_64-unknown-linux-gnu -disable-objc-interop -no-color-diagnostics -Xcc -fno-color-diagnostics -g -debug-info-format=dwarf -dwarf-version=4 -swift-version 6 -empty-abi-descriptor -enable-anonymous-context-mangled-names -file-compilation-dir /app -Xllvm --x86-asm-syntax=intel -no-auto-bridging-header-chaining -module-name output -in-process-plugin-server-path /cefs/5a/5afd274eb51c5c731b7266ae_swift-nightly/usr/lib/swift/host/libSwiftInProcPluginServer.so -plugin-path /cefs/5a/5afd274eb51c5c731b7266ae_swift-nightly/usr/lib/swift/host/plugins -plugin-path /cefs/5a/5afd274eb51c5c731b7266ae_swift-nightly/usr/local/lib/swift/host/plugins -o /app/output.s
1.	Swift version 6.3-dev (LLVM 984f3dccb13e621, Swift 2a9d858583dc912)
2.	Compiling with the current language version
3.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for file "<source>")
4.	While silgen emitFunction SIL function "@$s6output4failyyYaF".
 for 'fail()' (at <source>:20:1)
 #0 0x000062268c9e6168 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/cefs/5a/5afd274eb51c5c731b7266ae_swift-nightly/usr/bin/swift-frontend+0x8c7e168)
 #1 0x000062268c9e3c8e llvm::sys::RunSignalHandlers() (/cefs/5a/5afd274eb51c5c731b7266ae_swift-nightly/usr/bin/swift-frontend+0x8c7bc8e)
 #2 0x000062268c9e6801 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #3 0x000077d8f9e42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x000077d8f9e969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x000077d8f9e42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x000077d8f9e287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x000077d8f9e2871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x000077d8f9e39e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x000062268567b5aa emitDelayedArguments(swift::Lowering::SILGenFunction&, llvm::MutableArrayRef<(anonymous namespace)::DelayedArgument>, llvm::MutableArrayRef<llvm::SmallVector<swift::Lowering::ManagedValue, 4u>>) SILGenApply.cpp:0:0
#10 0x000062268569dd66 (anonymous namespace)::CallEmission::emitArgumentsForNormalApply(swift::Lowering::AbstractionPattern, swift::CanTypeWrapper<swift::SILFunctionType>, llvm::ArrayRef<swift::LifetimeDependenceInfo>, swift::ForeignInfo const&, llvm::SmallVectorImpl<swift::Lowering::ManagedValue>&, std::optional<swift::SILLocation>&) SILGenApply.cpp:0:0
#11 0x000062268568067a (anonymous namespace)::CallEmission::apply(swift::Lowering::SGFContext) SILGenApply.cpp:0:0
#12 0x000062268567db82 swift::Lowering::SILGenFunction::emitApplyExpr(swift::ApplyExpr*, swift::Lowering::SGFContext) crtstuff.c:0:0
#13 0x0000622685586034 swift::ASTVisitor<(anonymous namespace)::RValueEmitter, swift::Lowering::RValue, void, void, void, void, void, swift::Lowering::SGFContext>::visit(swift::Expr*, swift::Lowering::SGFContext) SILGenExpr.cpp:0:0
#14 0x0000622685579e46 swift::Lowering::SILGenFunction::emitIgnoredExpr(swift::Expr*) crtstuff.c:0:0
#15 0x000062268563589a swift::ASTVisitor<(anonymous namespace)::StmtEmitter, void, void, void, void, void, void>::visit(swift::Stmt*) SILGenStmt.cpp:0:0
#16 0x0000622685633f5d swift::Lowering::SILGenFunction::emitStmt(swift::Stmt*) crtstuff.c:0:0
#17 0x00006226855ac41a swift::Lowering::SILGenFunction::emitFunction(swift::FuncDecl*) crtstuff.c:0:0
#18 0x000062268551a888 swift::Lowering::SILGenModule::emitFunctionDefinition(swift::SILDeclRef, swift::SILFunction*) crtstuff.c:0:0
#19 0x000062268551befe swift::Lowering::SILGenModule::emitOrDelayFunction(swift::SILDeclRef) crtstuff.c:0:0
#20 0x0000622685518dcc swift::Lowering::SILGenModule::emitFunction(swift::FuncDecl*) crtstuff.c:0:0
#21 0x000062268551f1e3 swift::Lowering::SILGenModule::emitSourceFile(swift::SourceFile*) crtstuff.c:0:0
#22 0x000062268551f934 swift::ASTLoweringRequest::evaluate(swift::Evaluator&, swift::ASTLoweringDescriptor) const (/cefs/5a/5afd274eb51c5c731b7266ae_swift-nightly/usr/bin/swift-frontend+0x17b7934)
#23 0x0000622685633856 swift::SimpleRequest<swift::ASTLoweringRequest, std::unique_ptr<swift::SILModule, std::default_delete<swift::SILModule>> (swift::ASTLoweringDescriptor), (swift::RequestFlags)17>::evaluateRequest(swift::ASTLoweringRequest const&, swift::Evaluator&) crtstuff.c:0:0
#24 0x00006226855249d3 swift::ASTLoweringRequest::OutputType swift::Evaluator::getResultUncached<swift::ASTLoweringRequest, swift::ASTLoweringRequest::OutputType swift::evaluateOrFatal<swift::ASTLoweringRequest>(swift::Evaluator&, swift::ASTLoweringRequest)::'lambda'()>(swift::ASTLoweringRequest const&, swift::ASTLoweringRequest::OutputType swift::evaluateOrFatal<swift::ASTLoweringRequest>(swift::Evaluator&, swift::ASTLoweringRequest)::'lambda'()) crtstuff.c:0:0
#25 0x00006226855202ef swift::performASTLowering(swift::FileUnit&, swift::Lowering::TypeConverter&, swift::SILOptions const&, swift::IRGenOptions const*) (/cefs/5a/5afd274eb51c5c731b7266ae_swift-nightly/usr/bin/swift-frontend+0x17b82ef)
#26 0x0000622684cd719f swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) (/cefs/5a/5afd274eb51c5c731b7266ae_swift-nightly/usr/bin/swift-frontend+0xf6f19f)
#27 0x0000622684ced7ea withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) FrontendTool.cpp:0:0
#28 0x0000622684cdc754 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) FrontendTool.cpp:0:0
#29 0x0000622684cd9421 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) (/cefs/5a/5afd274eb51c5c731b7266ae_swift-nightly/usr/bin/swift-frontend+0xf71421)
#30 0x0000622684a39fcc swift::mainEntry(int, char const**) (/cefs/5a/5afd274eb51c5c731b7266ae_swift-nightly/usr/bin/swift-frontend+0xcd1fcc)
#31 0x000077d8f9e29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#32 0x000077d8f9e29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#33 0x0000622684a39015 _start (/cefs/5a/5afd274eb51c5c731b7266ae_swift-nightly/usr/bin/swift-frontend+0xcd1015)

*** Signal 6: Backtracing from 0x77d8f9f1e88d... done ***

*** Program crashed: Aborted at 0x0000280000000001 ***

Platform: x86_64 Linux (Ubuntu 22.04.5 LTS)

Thread 0 "swift-frontend" crashed:

  0  0x000077d8f9f1e88d <unknown> in libc.so.6
...


Registers:

rax 0x0000000000000000  0
rdx 0x0000000000000006  6
rcx 0x000077d8f9f1e88d  48 3d 01 f0 ff ff 73 01 c3 48 8b 0d 73 b5 0f 00  H=·ðÿÿs·ÃH··sµ··
rbx 0x0000000000000006  6
rsi 0x0000000000000001  1
rdi 0x0000000000000001  1
rbp 0x0000000000000001  1
rsp 0x000062269435b5a8  2b 68 9e 8c 26 62 00 00 30 b8 35 94 26 62 00 00  +h··&b··0¸5·&b··
 r8 0x000062269435b830  06 00 00 00 00 00 00 00 fa ff ff ff 00 00 00 00  ········úÿÿÿ····
 r9 0x000062269435b830  06 00 00 00 00 00 00 00 fa ff ff ff 00 00 00 00  ········úÿÿÿ····
r10 0x000062269435b830  06 00 00 00 00 00 00 00 fa ff ff ff 00 00 00 00  ········úÿÿÿ····
r11 0x0000000000000246  582
r12 0x0000000000000000  0
r13 0x0000000000000000  0
r14 0x0000000000000000  0
r15 0x000062269435b5b8  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ················
rip 0x000077d8f9f1e88d  48 3d 01 f0 ff ff 73 01 c3 48 8b 0d 73 b5 0f 00  H=·ðÿÿs·ÃH··sµ··

rflags 0x0000000000000246  ZF PF

cs 0x0033  fs 0x0000  gs 0x0000


Images (26 omitted):

0x000077d8f9e00000–0x000077d8f9fbc341 d5197096f709801829b118af1b7cf6631efa2dcd libc.so.6 /lib/x86_64-linux-gnu/libc.so.6

Backtrace took 0.00s

Program terminated with signal: SIGSEGV
Compiler returned: 139
```

### Expected behavior

should not crash

### Environment

Swift version 6.3-dev (LLVM 984f3dccb13e621, Swift 2a9d858583dc912)
Target: x86_64-unknown-linux-gnu

### Additional information

discovered when investigating a similar (or the same) issue involved with some potential changes involved in this forum thread: https://forums.swift.org/t/thoughts-on-fixing-a-sil-verification-error-and-or-bad-codegen-involving-default-arguments-implicitly-opened-existentials/82409

godbolt: https://swift.godbolt.org/z/4ExvM885r

### PR DESCRIPTION
**Pull request by jamieQ**
Changes in https://github.com/swiftlang/swift/pull/81370 addressed a number of issues with isolated default argument handling. However, there seemed to still be a problem when dealing with isolated default arguments of instance/static methods under the following conditions:

- The method contained an isolated default parameter
- The method contained a defaulted parameter that expanded to 0 or >1 values
- Said parameter was followed by another defaulted parameter

The attempted fix here was to adjust the isolated default argument iteration bookkeeping.

resolves: https://github.com/swiftlang/swift/issues/84647

### CODE REVIEW

**Comment by jamieQ** [comment]
@swift-ci please smoke test

**Comment by jamieQ** [comment]
@rjmccall if you get a chance to take a look at this proposed fix, i'd appreciate your insights on:

1. if the proposed solution seems appropriate
2. anything else you think would be valuable to add to the test cases (currently they just ensure the previous crasher/assertion failure no longer occurs)

File: test/SILGen/isolated_default_arguments.swift [hunk 1]
```diff
@@ -161,3 +161,66 @@ func useCallerIsolatedDefaultArg() async {
 // CHECK:         // function_ref default argument 0 of
 // CHECK-NEXT:    [[GEN:%.*]] = function_ref @$s4test24callerIsolatedDefaultArg1xySi_tYaFfA_ :
 // CHECK-NEXT:    [[ARG:%.*]] = apply [[GEN]]()
+
+// The following tests failed due to a book-keeping error when processing delayed
+// isolated arguments in methods with:
+//
+//  - a `self` parameter
+//  - delayed arguments that expanded to zero or greater than one value
+//  - a subsequent delayed argument
```
Comment (jamieQ) [inline test/SILGen/isolated_default_arguments.swift:170]: should probably say 'default' rather than 'delayed'

**Comment by jamieQ** [comment]
ping @rjmccall / @kavon / @jckarter

File: lib/SILGen/SILGenApply.cpp [hunk 2]
```diff
@@ -3203,6 +3202,7 @@ static void emitDelayedArguments(SILGenFunction &SGF,
       // Otherwise, reset the current index adjustment.
       } else {
         indexAdjustment = 0;
+        indexAdjustmentSite = site;
```
Comment (kavon) [inline lib/SILGen/SILGenApply.cpp:3205]: Based on a cursory look at this bit of code, it seems suspicious to me that we'd only update `indexAdjustmentSite` in this else branch. We were updating the `indexAdjustment` below in this loop unconditionally, but seemingly didn't update the `indexAdjustmentSite` at all, prior to this PR. Why is that?

Comment (jamieQ) [reply lib/SILGen/SILGenApply.cpp:3205]: i assume that was an error/oversight as not updating it causes the added tests to hit assertion failures when they overwrite prior default arguments. IIUC the 'site args' stuff is perhaps a vestige from curried function call syntax. this is what Slava informed me of [here](https://forums.swift.org/t/thoughts-on-fixing-a-sil-verification-error-and-or-bad-codegen-involving-default-arguments-implicitly-opened-existentials/82409/6):

> SILGen has some vestigial support for the old curried function call syntax that was removed in Swift 3. We still use it to represent the `self` parameter, so a method has type `(Self) -> (Args...) -> Result` in the AST, but in SIL it's `(Args..., Self) -> Result`. There are two "call sites" for a single "call", basically. But now it only ever comes up in this case.

so now i think there are only ever at most 2 'levels' of 'site args'. most of the existing test cases i saw for this isolated default args stuff appeared to use free functions and not instance methods (static or otherwise), so i'm not sure they exercised this case.

**Comment by jamieQ** [comment]
@rjmccall / @kavon / @jckarter – any thoughts on this proposed fix?

**Comment by slavapestov** [comment]
@swift-ci Please test
