### PR TITLE
[SILGen]Check if baseType is DynamicSelfType

### LINKED ISSUE #80669: Crash when using `Self` in KeyPath expression
### Description

The program crashes with `Fatal error: could not demangle keypath type from '�`.

### Reproduction

```swift
public func type<Root, Value>(at keyPath: KeyPath<Root, Value>) -> Value.Type {
    return Value.self
}

extension Int {
    static func bar() {
        print("Hello")
    }
}

class Foo {
    var int = 10
    
    static func staticFunc() {
        type(at: \Self.int).bar()
    }
}

Foo.staticFunc() // crashes
```

```swift
public func type<Root, Value>(at keyPath: KeyPath<Root, Value>) -> Value.Type {
    return Value.self
}

extension Int {
    static func bar() {
        print("Hello")
    }
}

class Foo {
    var int = 10
    
    static func staticFunc() {
        type(at: \Foo.int).bar()
    }
}

Foo.staticFunc() // Prints `Hello` correctly
```

### Stack dump

```text
#0	0x00000001adb1c95c in _swift_runtime_on_report ()
#1	0x00000001adbf49c8 in _swift_stdlib_reportFatalErrorInFile ()
#2	0x00000001ad7bc080 in closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> () in Swift._assertionFailure(_: Swift.StaticString, _: Swift.String, file: Swift.StaticString, line: Swift.UInt, flags: Swift.UInt32) -> Swift.Never ()
#3	0x00000001ad7bb1f8 in Swift._assertionFailure(_: Swift.StaticString, _: Swift.String, file: Swift.StaticString, line: Swift.UInt, flags: Swift.UInt32) -> Swift.Never ()
#4	0x00000001ad8ed61c in Swift._resolveKeyPathGenericArgReference(_: Swift.UnsafeRawPointer, genericEnvironment: Swift.Optional<Swift.UnsafeRawPointer>, arguments: Swift.Optional<Swift.UnsafeRawPointer>) -> Swift.UnsafeRawPointer ()
#5	0x00000001ad8ed9cc in generic specialization <Swift.GetKeyPathClassAndInstanceSizeFromPattern> of Swift._walkKeyPathPattern<τ_0_0 where τ_0_0: Swift.KeyPathPatternVisitor>(_: Swift.UnsafeRawPointer, walker: inout τ_0_0) -> () ()
#6	0x00000001ad8ece30 in Swift._getKeyPathClassAndInstanceSizeFromPattern(Swift.UnsafeRawPointer, Swift.UnsafeRawPointer) -> (keyPathClass: Swift.AnyKeyPath.Type, rootType: Any.Type, size: Swift.Int, alignmentMask: Swift.Int) ()
#7	0x00000001ad8ecc04 in Swift._swift_getKeyPath(pattern: Swift.UnsafeMutableRawPointer, arguments: Swift.UnsafeRawPointer) -> Swift.UnsafeRawPointer ()
```

### Expected behavior

No crash should happen

### Environment

Swift compiler in toolchain shipped with `Xcode 16.3 (16E140)`

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by stzn**
Resolves https://github.com/swiftlang/swift/issues/80669
I think the issue mentioned above has been resolved by this, but it’s unrelated. I will create a separate one for it.  

The compiler crashed when compiling the following code:

```swift
func type<Root, Value>(at keyPath: KeyPath<Root, Value>) -> Value.Type {
    return Value.self
}

class Foo {
    var other = Foo()

    static func staticFunc() {
        type(at: \Self.other).bar()
    }

    static func bar() {
        print("Hello")
    }
}
```

The crash log was as follows:

```
SIL verification failed: can't upcast to same type: UI->getType() != UI->getOperand()->getType()
Verifying instruction:
     %4 = load [take] %2 : $*Foo                  // user: %5
->   %5 = upcast %4 : $Foo to $Foo                // users: %11, %6
     %6 = begin_borrow %5 : $Foo                  // users: %9, %8, %7
     destroy_value %5 : $Foo                      // id: %11
In function:
// key path getter for Foo.other : Self
sil shared [thunk] [ossa] @$s4main3FooC5otherACvpACXDTK : $@convention(keypath_accessor_getter) (@in_guaranteed Foo) -> @out Foo {
// %0                                             // user: %10
// %1                                             // user: %3
bb0(%0 : $*Foo, %1 : $*Foo):
  %2 = alloc_stack $Foo                           // users: %12, %4, %3
  copy_addr %1 to [init] %2                       // id: %3
  %4 = load [take] %2                             // user: %5
  %5 = upcast %4 to $Foo                          // users: %11, %6
  %6 = begin_borrow %5                            // users: %9, %8, %7
  %7 = class_method %6, #Foo.other!getter : (Foo) -> () -> Foo, $@convention(method) (@guaranteed Foo) -> @owned Foo // user: %8
  %8 = apply %7(%6) : $@convention(method) (@guaranteed Foo) -> @owned Foo // user: %10
  end_borrow %6                                   // id: %9
  store %8 to [init] %0                           // id: %10
  destroy_value %5                                // id: %11
  dealloc_stack %2                                // id: %12
  %13 = tuple ()                                  // user: %14
  return %13                                      // id: %14
} // end sil function '$s4main3FooC5otherACvpACXDTK'
Stack dump:
0.      Program arguments: /usr/bin/swift-frontend -frontend -interpret - -disable-objc-interop -color-diagnostics -enable-bare-slash-regex -empty-abi-descriptor -resource-dir /usr/lib/swift -no-auto-bridging-header-chaining -module-name main -in-process-plugin-server-path /usr/lib/swift/host/libSwiftInProcPluginServer.so -plugin-path /usr/lib/swift/host/plugins -plugin-path /usr/local/lib/swift/host/plugins
1.      Swift version 6.2-dev (LLVM a3e32cdaae72f3d, Swift fa8609703528715)
2.      Compiling with effective version 5.10
3.      While evaluating request ASTLoweringRequest(Lowering AST to SIL for module main)
4.      While verifying SIL function "@$s4main3FooC5otherACvpACXDTK".
 for <<debugloc at "<compiler-generated>":0:0>>
...
```

The cause appears to be that when using `\Self` in a key path, the `baseType` is `DynamicSelfType`. This prevents retrieving the `baseClass` using `getClassOrBoundGenericClass`, as seen here:
https://github.com/swiftlang/swift/blob/main/lib/SILGen/SILGenExpr.cpp#L3402

Therefore, a check was added to determine if `baseType` is `DynamicSelfType`.

### CODE REVIEW

File: lib/SILGen/SILGenExpr.cpp [hunk 1]
```diff
@@ -3399,7 +3399,11 @@ static ManagedValue emitKeyPathRValueBase(SILGenFunction &subSGF,
   
   // Upcast a class instance to the property's declared type if necessary.
   if (auto propertyClass = storage->getDeclContext()->getSelfClassDecl()) {
-    if (baseType->getClassOrBoundGenericClass() != propertyClass) {
+    auto baseClass = baseType->getClassOrBoundGenericClass();
+    if (auto dynamicSelfType = baseType->getAs<DynamicSelfType>()) {
+      baseClass = dynamicSelfType->getSelfType()->getClassOrBoundGenericClass();
```
Comment (slavapestov) [inline lib/SILGen/SILGenExpr.cpp:3404]: Instead of calling getClassOrBoundGenericClass() twice, how about we unwrap the DynamicSelfType first:

```
if (auto selfType = baseType->getAs<DynamicSelfType>()) {
  baseType = selfType->getSelfType();
baseClass = baseType->getClassOrBoundGenericClass();
ASSERT(baseClass != nullptr);
```

The assert means that if this kind of bug comes up again, we get a better crash report than we otherwise would from a segfault.

Comment (stzn) [reply lib/SILGen/SILGenExpr.cpp:3404]: @slavapestov 

Thank you for checking. I tried the below code, but the assertion failed in [`subclass_generics`](https://github.com/swiftlang/swift/blob/f31c89a73e3f14e8f5e7ad1b92dd434ef12654b1/test/SILGen/keypaths.swift#L510).

```
if (auto selfType = baseType->getAs<DynamicSelfType>())
      baseType = selfType->getSelfType()->getCanonicalType(); // Need getCanonicalType() since baseType is CanType 
auto baseClass = baseType->getClassOrBoundGenericClass();
ASSERT(baseClass != nullptr);
```

Am I misunderstanding something?

Comment (stzn) [reply lib/SILGen/SILGenExpr.cpp]: @slavapestov 
As far as I confirmed, `baseClass` still could be nil when `baseType` is `ArchetypeType`.
Please correct me if I'm wrong. Thank you.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
Oops, dropped the ball on this one. Let's merge it if the tests pass.
