### PR TITLE
[CS] Map caught error type into context

### LINKED ISSUE #77295: Typed-throws invalid diagnostic
### Reproduction

```swift
extension Optional {
  public func unwrapped<E: Swift.Error>(orThrow error: @autoclosure () -> E) throws(E) -> Wrapped {
    switch self {
    case .none:
      throw error()
    case .some(let wrapped):
      wrapped
    }
  }
}
```

### Expected behavior

Compiles

### Actual behavior
```
/tmp/test.swift:5:13: error: thrown expression type 'E' cannot be converted to error type 'E'
 3 |     switch self {
 4 |     case .none:
 5 |       throw error()
   |             `- error: thrown expression type 'E' cannot be converted to error type 'E'
 6 |     case .some(let wrapped):
 7 |       wrapped
```

### Environment

```
swift-driver version: 1.115 Apple Swift version 6.0.2 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
Target: arm64-apple-macosx15.0
```

### PR DESCRIPTION
**Pull request by hamishknight**
Factor out `ConstraintSystem::getExplicitCaughtErrorType` from  `getCaughtErrorType`. Then use this for the contextual type for a `throw` syntactic element.

rdar://139000351
Resolves #77295

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]
Thanks!

**Comment by hamishknight** [comment]
@swift-ci please test Linux

**Comment by hamishknight** [comment]
@swift-ci please test macOS

File: lib/Sema/CSSyntacticElement.cpp [hunk 1]
```diff
@@ -969,7 +969,7 @@ class SyntacticElementConstraintGenerator
     auto throwLoc = throwStmt->getThrowLoc();
     Type errorType;
     if (auto catchNode = ASTScope::lookupCatchNode(module, throwLoc))
-      errorType = catchNode.getExplicitCaughtType(cs.getASTContext());
+      errorType = cs.getExplicitCaughtErrorType(catchNode);
```
Comment (xedin) [inline lib/Sema/CSSyntacticElement.cpp:972]: My only note here is [use of DC](https://github.com/swiftlang/swift/pull/80248/files#diff-d57f6f2d466f1f207cdf2dbd0396a1dbb2caba7b6828ebdb9954948f0ac2b499R520) in existing code. Maybe we should propagate `dc` down explicitly to avoid problems in the future because `DC` in ConstraintSystem during solving could be difference from DC during constraint generation unfortunately...

Comment (hamishknight) [reply lib/Sema/CSSyntacticElement.cpp:972]: Yup, fortunately in this case being in a closure doesn't affect the result of mapping into context, but yeah I agree we ought to be passing the DeclContext down
