### PR TITLE
[AutoDiff] Handle materializing adjoints with non-differentiable fields

### LINKED ISSUE #66522: [Autodiff]: Failure to synthesize conformance to `AdditiveArithmetic` in some cases.
**Description**
The following code fails to build in Debug mode. The error message is:
```
Assertion failed: (!confRef.isInvalid() && "Missing conformance to `AdditiveArithmetic`"), function emitZeroIntoBuffer, file TangentBuilder.cpp, line 42.
```

**Steps to reproduce**
Paste the following code into a new project and build.

```
import _Differentiation
public struct P<Value> {
    public typealias TangentVector = Self
    public let name = ""
    var value: Value
}
extension P: Equatable, AdditiveArithmetic where Value: AdditiveArithmetic {
    public static var zero: Self {fatalError()}
    public static func + (lhs: Self, rhs: Self) -> Self {fatalError()}
    public static func - (lhs: Self, rhs: Self) -> Self {fatalError()}
}
public extension P {
    @differentiable(reverse where Value: Differentiable, Value.TangentVector == Value, Value: AdditiveArithmetic) func a() -> Value {self.value}
    @differentiable(reverse where Value: Differentiable, Value.TangentVector == Value, Value: AdditiveArithmetic) static internal func t(_ data: Self) -> Value{data.value}
}
extension P: Differentiable where Value:  Differentiable, Value.TangentVector == Value, Value: AdditiveArithmetic {}
@differentiable(reverse) internal func z(_ data: P<Double>) -> Double {
    data.value
    //data.a()
    //P<Double>.z(data)
}

```

**Expected behavior**
The code should compile successfully. 

**Environment**
- Swift compiler version info: Toolchains 2022-10-09a and 2023-05-31a exhibit this issue.
- Xcode version info: 14.2
- Deployment target: M1

**Additional context**
- Removing `public let name = ""` causes the build to succeed.
- Returning the value in the function called `z` using `data.a()` or `P<Double>.z(data)` causes the build to succeed.

Stack trace:
```
1.	Apple Swift version 5.9-dev (LLVM fd15f782007e262, Swift 65bb599048dbd75)
2.	Compiling with the current language version
3.	While evaluating request ExecuteSILPipelineRequest(Run pipelines { Mandatory Diagnostic Passes + Enabling Optimization Passes } on SIL for a)
4.	While running pass #172 SILModuleTransform "Differentiation".
5.	While processing // differentiability witness for z(_:)
sil_differentiability_witness [serialized] [reverse] [parameters 0] [results 0] @$s1a1zySdAA1PVySdGF : $@convention(thin) (@guaranteed P<Double>) -> Double {
}

 on SIL function "@$s1a1zySdAA1PVySdGF".
 for 'z(_:)' (at /Users/user/a/a/main.swift:17:35)
6.	While generating VJP for SIL function "@$s1a1zySdAA1PVySdGF".
 for 'z(_:)' (at /Users/user/a/a/main.swift:17:35)
7.	While generating pullback for SIL function "@$s1a1zySdAA1PVySdGF".
 for 'z(_:)' (at /Users/user/a/a/main.swift:17:35)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x000000010924c69c llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x000000010924ba40 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x000000010924ccdc SignalHandler(int) + 304
3  libsystem_platform.dylib 0x0000000197f0ea24 _sigtramp + 56
4  libsystem_pthread.dylib  0x0000000197edfc28 pthread_kill + 288
5  libsystem_c.dylib        0x0000000197dedae8 abort + 180
6  libsystem_c.dylib        0x0000000197dece44 err + 0
7  swift-frontend           0x000000010939a700 swift::autodiff::TangentBuilder::emitZeroIntoBuffer(swift::SILLocation, swift::SILValue, swift::IsInitialization_t) (.cold.3) + 0
8  swift-frontend           0x0000000104c3311c swift::autodiff::TangentBuilder::emitZeroIntoBuffer(swift::SILLocation, swift::SILValue, swift::IsInitialization_t) + 996
9  swift-frontend           0x0000000104c33248 swift::autodiff::TangentBuilder::emitZero(swift::SILLocation, swift::CanType) + 264
10 swift-frontend           0x0000000104c25e14 swift::autodiff::PullbackCloner::Implementation::materializeAdjointDirect(swift::autodiff::AdjointValue, swift::SILLocation) + 348
11 swift-frontend           0x0000000104c25e7c swift::autodiff::PullbackCloner::Implementation::materializeAdjointDirect(swift::autodiff::AdjointValue, swift::SILLocation) + 452
12 swift-frontend           0x0000000104c23e80 swift::autodiff::PullbackCloner::Implementation::run()::$_1::operator()(unsigned int) const + 124
13 swift-frontend           0x0000000104c20388 swift::autodiff::PullbackCloner::Implementation::run() + 6628
14 swift-frontend           0x0000000104c1e96c swift::autodiff::PullbackCloner::run() + 24
15 swift-frontend           0x0000000104c3b81c swift::autodiff::VJPCloner::Implementation::run() + 1368
16 swift-frontend           0x0000000104c3bee0 swift::autodiff::VJPCloner::run() + 24
17 swift-frontend           0x0000000104d6ffd4 (anonymous namespace)::DifferentiationTransformer::canonicalizeDifferentiabilityWitness(swift::SILDifferentiabilityWitness*, swift::autodiff::DifferentiationInvoker, swift::IsSerialized_t) + 5616
18 swift-frontend           0x0000000104d6e0a4 (anonymous namespace)::Differentiation::run() + 1032
19 swift-frontend           0x0000000104df1a34 swift::SILPassManager::runModulePass(unsigned int) + 980
20 swift-frontend           0x0000000104df784c swift::SILPassManager::execute() + 624
21 swift-frontend           0x0000000104dee9dc swift::SILPassManager::executePassPipelinePlan(swift::SILPassPipelinePlan const&) + 68
22 swift-frontend           0x0000000104dee960 swift::ExecuteSILPipelineRequest::evaluate(swift::Evaluator&, swift::SILPipelineExecutionDescriptor) const + 68
23 swift-frontend           0x0000000104e2ce8c swift::SimpleRequest<swift::ExecuteSILPipelineRequest, std::__1::tuple<> (swift::SILPipelineExecutionDescriptor), (swift::RequestFlags)1>::evaluateRequest(swift::ExecuteSILPipelineRequest const&, swift::Evaluator&) + 28
24 swift-frontend           0x0000000104e1683c llvm::Expected<swift::ExecuteSILPipelineRequest::OutputType> swift::Evaluator::getResultUncached<swift::ExecuteSILPipelineRequest>(swift::ExecuteSILPipelineRequest const&) + 252
25 swift-frontend           0x0000000104deebd0 swift::executePassPipelinePlan(swift::SILModule*, swift::SILPassPipelinePlan const&, bool, swift::irgen::IRGenModule*) + 84
26 swift-frontend           0x0000000104e188e0 swift::runSILDiagnosticPasses(swift::SILModule&) + 192
27 swift-frontend           0x0000000104734f9c swift::CompilerInstance::performSILProcessing(swift::SILModule*) + 68
28 swift-frontend           0x0000000104599078 performCompileStepsPostSILGen(swift::CompilerInstance&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*) + 788
29 swift-frontend           0x0000000104598798 swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 568
30 swift-frontend           0x00000001045a7988 withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 160
31 swift-frontend           0x000000010459b278 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 724
32 swift-frontend           0x000000010459a20c swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2456
33 swift-frontend           0x00000001043e4940 swift::mainEntry(int, char const**) + 2144
34 dyld                     0x0000000197b87f28 start + 2236
```

### PR DESCRIPTION
**Pull request by jkshtj**
This PR fixes a compiler crasher in AutoDiff. 

The compiler used to crash while generating a pullback for differentiable functions that take a differentiable input, whose tangent vector contains non-differentiable fields.

Changes in this PR fix the issue by specializing adjoint materialization logic for user-defined tangent vectors containing non-differentiable fields.

Fixes #66522

### CODE REVIEW

**Comment by jkshtj** [comment]
@asl @BradLarson could one of you invoke swift-ci tests?

File: test/AutoDiff/compiler_crashers_fixed/issue-66522-pullback-generation-when-tangentvector-of-input-contains-nondifferentiable-fields.swift [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+// 
+// SO WHAT? 
+// It feels like a bit of an edge case that for a user-defined tangent 
+// vector, such as that for `P`, we cannot have a function mapping 
+// individual member fields to `P`.
+//
+// NOW WHAT?
+// Is this edge case something that we need to handle?
+// 
+// @differentiable(reverse)
```
Comment (jkshtj) [inline test/AutoDiff/compiler_crashers_fixed/issue-66522-pullback-generation-when-tangentvector-of-input-contains-nondifferentiable-fields.swift:64]: @rxwei Could you please take a look at the comments on this commented-out differentiable function? 

I may have discovered an edge-case and I wanted to confirm whether or not it's something we need to handle and/or fix.

**Comment by asl** [comment]
I am confused. I think the discussion was that we need to fix adjoint generation for `struct_extract` instruction. Are there other usecases besides `struct_extract` that should be covered?

What is the test coverage for newly added code?

**Comment by asl** [comment]
@swift-ci please test

**Comment by jkshtj** [comment]
> I am confused. I thought the discussion was that we need to fix adjoint generation for `struct_extract` instruction.

I think I may have misunderstood how to go about fixing the issue. Are you suggesting that we never add non-differentiable fields to the adjoint for `struct_extract`?

**Comment by jkshtj** [comment]
> Are there other usecases besides `struct_extract` that should be covered?

If we do make the fix in the adjoint generation code, then I believe we'd have to at least do the same for `tuple_extract`. There may be other instructions as well, but I'd need to take a closer look.

**Comment by jkshtj** [comment]
> What is the test coverage for newly added code?

In unit tests none. 

In the end to end tests, I added a tests for the path where we need to materialize an adjoint with non-differentiable fields. I should perhaps also have added a test for materializing normal adjoints with all differentiable fields.

**Comment by asl** [comment]
> I think I may have misunderstood how to go about fixing the issue. Are you suggesting that we never add non-differentiable fields to the adjoint for `struct_extract`?

There are multiple questions that need to be answered:

1. Are there any other instructions that are affected here. Besides `struct_extract`? For example, you've added handling of adjoint buffers in addition to values. Are there any testcases for this code?

2. Next, the current adjoint generation for `struct_extract` is essentially:
```
  ///   Original: y = struct_extract x, #field
  ///    Adjoint: adj[x] += struct (0, ..., #field': adj[y], ..., 0)
  ///                                       ^~~~~~~
  ///                     field in tangent space corresponding to #field
```

So, instead of materalizing that bunch of zeros, why we simply cannot do the following:
```
adj[x].field += adj[y]
```

After all, we know that things should conform to `AdditiveArithmetic` and therefore `a += 0` should be equal to `a`.

**Comment by asl** [comment]
> In unit tests, none.

Please ensure that all codepaths are covered by tests.

**Comment by jkshtj** [comment]
>     1. Are there any other instructions that are affected here. Besides `struct_extract`? For example, you've added handling of adjoint buffers in addition to values. Are there any testcases for this code?

Since the adjoint materialization code is shared by all instructions, we shouldn't need to handle things separately for different instructions. As for the handling of adjoint buffer handling, it looks like that code isn't actually called anywhere.

**Comment by jkshtj** [comment]
>     2. Next, the current adjoint generation for `struct_extract` is essentially:
> 
> 
> ```
>   ///   Original: y = struct_extract x, #field
>   ///    Adjoint: adj[x] += struct (0, ..., #field': adj[y], ..., 0)
>   ///                                       ^~~~~~~
>   ///                     field in tangent space corresponding to #field
> ```
> 
> So, instead of materalizing that bunch of zeros, why we simply cannot do the following:
> 
> ```
> adj[x].field += adj[y]
> ```
> 
> After all, we know that things should conform to `AdditiveArithmetic` and therefore `a += 0` should be equal to `a`.

Ah, indeed this is what I tried to do first and I ran into an issue with `TangentBuilder`'s `emitInPlaceAdd` method, which takes the lhs as a buffer. This was causing SIL verification failures for '+='-ing trivial types such as `Double`, with the following error message - 
```
SIL verification failed: operand of 'apply' doesn't match function input type
  $Double
  $*Double
Verifying instruction:
   %0 = argument of bb0 : $Double                 // user: %8
     %5 = struct_element_addr %1 : $*P<Double>, #P.value // user: %8
     %6 = witness_method $Double, #AdditiveArithmetic."+=" : <Self where Self : AdditiveArithmetic> (Self.Type) -> (inout Self, Self) -> () : $@convention(witness_method: AdditiveArithmetic) <τ_0_0 where τ_0_0 : AdditiveArithmetic> (@inout τ_0_0, @in_guaranteed τ_0_0, @thick τ_0_0.Type) -> () // user: %8
     %7 = metatype $@thick Double.Type            // user: %8
->   %8 = apply %6<Double>(%5, %0, %7) : $@convention(witness_method: AdditiveArithmetic) <τ_0_0 where τ_0_0 : AdditiveArithmetic> (@inout τ_0_0, @in_guaranteed τ_0_0, @thick τ_0_0.Type) -> ()
```

It looks like I may have misinterpreted the meaning of the error, however. And I think I simply needed to change the type of the input arguments. 

I can definitely try this out.

**Comment by jkshtj** [comment]
> > In unit tests, none.
> 
> Please ensure that all codepaths are covered by tests.

Would you know of an existing unit test that tests auto diff code? I wasn't quite sure how I can setup `PullbackCloner` for unit testing.

**Comment by asl** [comment]
> > ```
> > 1. Are there any other instructions that are affected here. Besides `struct_extract`? For example, you've added handling of adjoint buffers in addition to values. Are there any testcases for this code?
> > ```
> 
> Since the adjoint materialization code is shared by all instructions, we shouldn't need to handle things separately for different instructions. As for the handling of adjoint buffer handling, it looks like that code isn't actually called anywhere.

Allright, but what are those "different instruction"? Besides `tuple_extract`? Looks like you're adding whole bunch of generic code without any tests just to fix one particular corner case. Differential paths are known to have less-than-optimal test coverage and this usually cause all kinds of issues when the code is actually called in some obscure case. So we try to improve the test coverage, not to reduce it.

**Comment by asl** [comment]
> Would you know of an existing unit test that tests auto diff code? I wasn't quite sure how I can setup `PullbackCloner` for unit testing.

`test/AutoDiff` contain the tests for different aspects of autodiff code.

**Comment by asl** [comment]
> This was causing SIL verification failures for '+='-ing trivial types such as `Double`, with the following error message -

The `lhs` is a struct somewhere. So you should be able to take the address of its field and pass to `+=` method.

**Comment by jkshtj** [comment]
> > Would you know of an existing unit test that tests auto diff code? I wasn't quite sure how I can setup `PullbackCloner` for unit testing.
> 
> `test/AutoDiff` contain the tests for different aspects of autodiff code.

Oh, I think I was mistaking unit tests for the ones that occur in the [unittests](https://github.com/apple/swift/tree/main/unittests) directory in the Swift repo.

**Comment by jkshtj** [comment]
> > This was causing SIL verification failures for '+='-ing trivial types such as `Double`, with the following error message -
> 
> The `lhs` is a struct somewhere. So you should be able to take the address of its field and pass to `+=` method. However, in your particular case it was rhs that caused the assertion as the argument is passed indirect.

Yeah it was the right one. I was a little bit surprised because I was thinking that only the left one needs to be taken as a pointer (or by reference). But I'm guessing this more generalized SIL definition exists to accomodate for different types that may want to conform to AdditiveArithmetic?

**Comment by jkshtj** [comment]
> > > ```
> > > 1. Are there any other instructions that are affected here. Besides `struct_extract`? For example, you've added handling of adjoint buffers in addition to values. Are there any testcases for this code?
> > > ```
> > 
> > 
> > Since the adjoint materialization code is shared by all instructions, we shouldn't need to handle things separately for different instructions. As for the handling of adjoint buffer handling, it looks like that code isn't actually called anywhere.
> 
> Allright, but what are those "different instruction"? Besides `tuple_extract`? Looks like you're adding whole bunch of generic code without any tests just to fix one particular corner case. Differential paths are known to have less-than-optimal test coverage and this usually cause all kinds of issues when the code is actually called in some obscure case. So we try to improve the test coverage, not to reduce it.

I see the point. Indeed, I missed a number of tests that could be added with this change. I was thinking we can start by covering pullbacks for instructions listed [here](https://github.com/apple/swift/blob/main/docs/DifferentiableProgrammingImplementation.md#derivative-code-generation-details). 

Can you think of any others that I should also test?

**Comment by jkshtj** [comment]
>     2. Next, the current adjoint generation for `struct_extract` is essentially:
> 
> 
> ```
>   ///   Original: y = struct_extract x, #field
>   ///    Adjoint: adj[x] += struct (0, ..., #field': adj[y], ..., 0)
>   ///                                       ^~~~~~~
>   ///                     field in tangent space corresponding to #field
> ```
> 
> So, instead of materalizing that bunch of zeros, why we simply cannot do the following:
> 
> ```
> adj[x].field += adj[y]
> ```
> 
> After all, we know that things should conform to `AdditiveArithmetic` and therefore `a += 0` should be equal to `a`.

@asl I've incorporated this feedback about adjoint materialization and am creating a new PR revision for some early feedback. 

I'm still working on adding test coverage but am struggling a bit to understand what exactly the tests should be doing. I'll post my questions about tests in another comment shortly.

**Comment by jkshtj** [comment]
@rxwei Could you also please take a look at the approach and comment whether it makes sense and whether I am making changes at the right place?

**Comment by asl** [comment]
> @asl I've incorporated this feedback about adjoint materialization and am creating a new PR revision for some early feedback.

Have you forgotten to push your new changes?

**Comment by jkshtj** [comment]
> > @asl I've incorporated this feedback about adjoint materialization and am creating a new PR revision for some early feedback.
> 
> Have you forgotten to push your new changes?

I don't think so. I amended the existing commit, however, instead of creating a new one.

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 2]
```diff
@@ -376,38 +481,114 @@ class PullbackCloner::Implementation final
...
+        materializeAggregateAdjointInDirect(val, destAddress, loc);
       }
       break;
     }
     /// If adjoint value is concrete, it is already materialized. Store it in
     /// the destination address.
     case AdjointValueKind::Concrete:
       auto concreteVal = val.getConcreteValue();
-      builder.emitStoreValueOperation(loc, concreteVal, destAddress,
+      // `val` needs to be an owned value for storing it into `destAddress`,
```
Comment (asl) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp:495]: Do we have testcase for this?

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 3]
```diff
@@ -362,6 +380,93 @@ class PullbackCloner::Implementation final
...
+              tupTy->getElementType(fieldIndex)->getCanonicalType());
+          auto lhsAdjEltBuf =
+              builder
+                  .createTupleElementAddr(loc, resultAlloc, fieldIndex, eltTy)
+                  ->getResult(0);
+          auto rhsAdjEltBuf =
+              builder.createAllocStack(loc, adjField.getType())->getResult(0);
+          materializeAdjointIndirect(adjField, rhsAdjEltBuf, loc);
+
+          // lhsAdjEltBuf += rhsAdjEltBuf
```
Comment (asl) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp:408]: I think it's up to the caller to decide what to do with adjoint value. Can you fold these two into adjoint generation of `tuple_extract` and `struct_extract` correspondingly?

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp (hunk 2 above)
Comment (jkshtj) [reply lib/SILOptimizer/Differentiation/PullbackCloner.cpp:495]: I do, locally. Haven't pushed it yet.

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp (hunk 3 above)
Comment (asl) [reply lib/SILOptimizer/Differentiation/PullbackCloner.cpp:408]: To be explicit. What I'm suggesting:

For `y = struct_extract x, #field` the adjoint generation would be:
 1. You take adjoint of 'x'
 1. You take adjoint of 'y'
 1. You take address of #field in x'
 1. You do x'.#field += y'

File: test/AutoDiff/SILOptimizer/pullback_generation.swift [hunk 4]
```diff
@@ -0,0 +1,129 @@
...
+    var a: Float
+    var b: Double
+}
+
+@differentiable(reverse)
+func f1(v: PiecewiseMaterializable) -> Float {
+    v.a
+}
+
+// CHECK-LABEL: [ORIG]  %2 = struct_extract %0 : $PiecewiseMaterializable, #PiecewiseMaterializable.a // user: %3
```
Comment (asl) [inline test/AutoDiff/SILOptimizer/pullback_generation.swift:23]: Maybe it will make sense to check the generated SIL and not the debug output? After all, you can do `-Xllvm -sil-print-after=differentiation`

File: test/AutoDiff/compiler_crashers_fixed/issue-66522-pullback-generation-when-tangentvector-of-input-contains-nondifferentiable-fields.swift [hunk 5]
```diff
@@ -0,0 +1,67 @@
+// RUN: %target-swift-frontend -emit-sil -O %s
```
Comment (asl) [inline test/AutoDiff/compiler_crashers_fixed/issue-66522-pullback-generation-when-tangentvector-of-input-contains-nondifferentiable-fields.swift:1]: should we XFAIL it then?

File: test/AutoDiff/SILOptimizer/pullback_generation.sil [hunk 6]
```diff
@@ -0,0 +1,155 @@
...
+}
+
+sil hidden [ossa] @$function_with_struct_extract_1 : $@convention(thin) (@guaranteed Y) -> @owned X {
+bb0(%0 : @guaranteed $Y):
+  %1 = struct_extract %0 : $Y, #Y.a               
+  %2 = copy_value %1 : $X                         
+  return %2 : $X                                  
+}
+
+// CHECK-LABEL: [ORIG]  %1 = struct_extract %0 : $Y, #Y.a               // user: %2
```
Comment (asl) [inline test/AutoDiff/SILOptimizer/pullback_generation.sil:60]: I would rather do `CHECK-LABEL` for function name + see comment below

File: test/AutoDiff/compiler_crashers_fixed/issue-66522-pullback-generation-when-tangentvector-of-input-contains-nondifferentiable-fields.swift (hunk 5 above)
Comment (jkshtj) [reply test/AutoDiff/compiler_crashers_fixed/issue-66522-pullback-generation-when-tangentvector-of-input-contains-nondifferentiable-fields.swift:1]: Ah, why? This does not cause a crash anymore.

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 7]
```diff
@@ -1168,22 +1168,35 @@ class PullbackCloner::Implementation final
         break;
       case AdjointValueKind::Concrete:
       case AdjointValueKind::Aggregate: {
```
[the remark this answers is not in the document]
Comment (asl) [reply lib/SILOptimizer/Differentiation/PullbackCloner.cpp:1170]: Right. Please do.

File: test/AutoDiff/compiler_crashers_fixed/issue-66522-pullback-generation-when-tangentvector-of-input-contains-nondifferentiable-fields.swift (hunk 5 above)
Comment (asl) [reply test/AutoDiff/compiler_crashers_fixed/issue-66522-pullback-generation-when-tangentvector-of-input-contains-nondifferentiable-fields.swift:1]: Does the comment at line 35 apply to the whole testcase? Or just the commented out lines?

File: test/AutoDiff/SILOptimizer/pullback_generation.swift (hunk 4 above)
Comment (jkshtj) [reply test/AutoDiff/SILOptimizer/pullback_generation.swift:23]: Yeah sure.

File: test/AutoDiff/SILOptimizer/pullback_generation.sil (hunk 6 above)
Comment (jkshtj) [reply test/AutoDiff/SILOptimizer/pullback_generation.sil:60]: Will change this to use the actual SIL after the differentiation pass instead.

File: test/AutoDiff/compiler_crashers_fixed/issue-66522-pullback-generation-when-tangentvector-of-input-contains-nondifferentiable-fields.swift (hunk 5 above)
Comment (jkshtj) [reply test/AutoDiff/compiler_crashers_fixed/issue-66522-pullback-generation-when-tangentvector-of-input-contains-nondifferentiable-fields.swift:1]: Just the commented out lines. Sorry, if that wasn't clear. 

I wanted to get Richard's comments on what seems like an edge case when using custom tangent vectors. But I can perhaps decouple it from this PR and handle it separately.

Comment (asl) [reply test/AutoDiff/compiler_crashers_fixed/issue-66522-pullback-generation-when-tangentvector-of-input-contains-nondifferentiable-fields.swift:1]: +1

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 8]
```diff
@@ -1162,28 +1162,41 @@ class PullbackCloner::Implementation final
...
-            auto fieldTy = field->getType().subst(substMap);
-            auto fieldSILTy = getTypeLowering(fieldTy).getLoweredType();
-            assert(fieldSILTy.isObject());
-            eltVals.push_back(makeZeroAdjointValue(fieldSILTy));
-          }
-        }
-        addAdjointValue(bb, sei->getOperand(),
-                        makeAggregateAdjointValue(tangentVectorSILTy, eltVals),
-                        loc);
+        llvm_unreachable("Adjoint value kind of the input to `struct_extract` "
```
Comment (rxwei) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp:1198]: With this, you are now forcing all `struct_extract` to materialize the adjoint. To me it seems unnecessary and may lead to performance issues for common cases where there is no non-differentiable fields of a `TangentVector`.

Can we use a type-driven approach instead?  It is still fine to create an `Aggregate` adjoint value or use the `struct` instruction, so long as the following conditions are met:
1. `TangentVector` is defined in the same compilation unit of differentiation.
2. All of `TangentVector`’s stored properties have a same-name differentiable property in the original type.

Or better, you could create a new `AdjointValueKind` called `AddElement`.  When the above conditions aren't met, just create a `AddElement(adj[x], #field, adj[y])` adjoint value. This way the whole thing can be kept symbolic and won't be materialized unless it's absolutely necessary.

Comment (jkshtj) [reply lib/SILOptimizer/Differentiation/PullbackCloner.cpp:1198]: Thanks for reviewing this Richard! I have a follow up question.

> With this, you are now forcing all struct_extract to materialize the adjoint. To me it seems unnecessary and may lead to performance issues for common cases where there is no non-differentiable fields of a TangentVector.

Aren't all adjoints eventually going to materialize, before the end of the differentiation pass, given the differentiation pass is run once and atomically(right?) with no other optimization passes run in between that may perform some peephole optimizations?

Comment (rxwei) [reply lib/SILOptimizer/Differentiation/PullbackCloner.cpp:1198]: > Aren't all adjoints eventually going to materialize

No, the purpose of the `AdjointValue` data structure is to prevent eager materialization and try to fold the data structure as much as possible. This is why we have special handling of different `AdjointValueKind`s for most instructions. There's a lot of cases of creating a struct of all zeros but one element, then using just one element from it in subsequent code.

Comment (jkshtj) [reply lib/SILOptimizer/Differentiation/PullbackCloner.cpp:1198]: That makes sense Richard. I also discussed this with Brad, Anton and others and it seems like the right direction, at the moment. Let me make the changes you suggested and get a new revision out.

Comment (jkshtj) [reply lib/SILOptimizer/Differentiation/PullbackCloner.cpp:1198]: @rxwei I was wondering something about this new adjoint kind we need to create. Could it just be a closure that simply returns a `SILValue`? I'm wondering if a new adjoint kind like `AddElement(adj[x], #field, adj[y])` is too specific and perhaps we can create something more general that works for all adjoints that may need some custom materialization logic?

Comment (jkshtj) [reply lib/SILOptimizer/Differentiation/PullbackCloner.cpp:1198]: Another follow-up question. 

Would you be able to comment on what the representation, in the actual implementation of the new adjoint kind you're suggesting (`AddElement(adj[x], #field, adj[y])`), should look like? The 2 I can think of are:
1. Store the original `struct_extract` or `tuple_extract` instruction.
2. Store the adjoints of `x` and `y` and the `VarDecl` for the field in `y = struct_extract x, #field`

Comment (asl) [reply lib/SILOptimizer/Differentiation/PullbackCloner.cpp:1198]: You need to be able to symbolically evaluate the adjoint in case it would be needed for materialization. Note that both `x` and `y` here could also be symbolic adjoints. So, the `2.` looks like a way to go for me.

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 9]
```diff
@@ -2993,13 +3092,60 @@ AdjointValue PullbackCloner::Implementation::accumulateAdjointsDirect(
       }
       return makeAggregateAdjointValue(lhsVal->getType(), newElements);
     }
+    // x + (zeroBase, index, eltToAdd) => (x.0, ..., x.index + eltToAdd, ...,
```
Comment (jkshtj) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp:3095]: @rxwei @asl I looked into adding a unit test (I'm referring to actual unit tests testing C++ classes/functions directly) for this function, but ran into some issues due to the internal state changes in PullbackCloner, that happen during this its call. 

Do you guys see any issues if I create a PullbackCloner constructor initializing minimal state, required for this test?

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 10]
```diff
@@ -400,12 +458,45 @@ class PullbackCloner::Implementation final
...
       builder.emitStoreValueOperation(loc, concreteVal, destAddress,
                                       StoreOwnershipQualifier::Init);
       break;
     }
+    case AdjointValueKind::AddElement: {
+      auto *addElementValue = val.getAddElementValue();
+      auto baseAdjoint = addElementValue->baseAdjoint;
+      auto eltToAdd = addElementValue->eltToAdd;
+
+      builder.emitZeroIntoBuffer(loc, destAddress, IsInitialization);
```
Comment (asl) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp:472]: Shouldn't you do indirect materialization of `baseAdjoint` into `destAddress?

File: include/swift/SILOptimizer/Differentiation/AdjointValue.h [hunk 11]
```diff
@@ -38,10 +40,25 @@ enum AdjointValueKind {
 
   /// A concrete SIL value.
   Concrete,
+
+  /// A special adjoint, made up of 2 adjoints -- a base adjoint and an element
```
Comment (asl) [inline include/swift/SILOptimizer/Differentiation/AdjointValue.h:44]: Do we really need to provide a "clarification" here? This might confuse the reader. What is confusing is `base adjoint` term. It's not quite so. We're essentially using only type (and index there). Also, do we really need to use `Add` here? I think the semantics is essentially `(0, ..., 0, el', 0, ..., 0)`, so the non-trivial combination of zero and aggregate adjoints.

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp (hunk 9 above)
Comment (asl) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp:3095]: why can't you simply call `accumulateAdjoints` on `x` and `base`, and then wrap the result with `AddElement` again? This way you'd evaluate everything symbolically and only materialize the real value (emit addition) when necessary. It will also collapse zeros on fly.

File: include/swift/SILOptimizer/Differentiation/AdjointValue.h (hunk 11 above)
Comment (jkshtj) [reply include/swift/SILOptimizer/Differentiation/AdjointValue.h:44]: Side-stepping the naming suggestions for a second, what I understood about the semantics of this new adjoint kind is -
1. It is a combination (by addition) of 2 adjoints, let's call them LHS and RHS for now. 
2. The LHS will always be a zeroed aggregate adjoint.
3. The RHS will be the adjoint for one of the fields of LHS. 

Symbolically, we have -
```
AddElement(LHS, #field_or_index, RHS) == (materialization) ==> AddElement.#field_or_index += RHS
```
There might be questions/comments about how we're accumulating this new adjoint with others, but I think establishing a common understanding of its semantics first might be helpful 🙂.

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp (hunk 10 above)
Comment (jkshtj) [reply lib/SILOptimizer/Differentiation/PullbackCloner.cpp]: You're right. Changed it.

**Comment by jkshtj** [comment]
@asl or @BradLarson could one of you kick of swift-ci?

**Comment by asl** [comment]
@swift-ci please test

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 12]
```diff
@@ -2994,13 +3093,70 @@ AdjointValue PullbackCloner::Implementation::accumulateAdjointsDirect(
       }
       return makeAggregateAdjointValue(lhsVal->getType(), newElements);
     }
+    // x + (baseAdjoint, index, eltToAdd)
+    // There are 2 possible cases -
```
Comment (asl) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp:3097]: The whole intention of new adjoint kind is to prevent extraneous materialization of adjoints. Here it seems you're materializing them. Also, why do you need these explicit cases? Why can't you simply call `accumulateAdointsDirect(base, rhs)`, wrap result into `AddElement(, eltToAdd)` and return it? All that zero folding, etc. will be already handled for you.

File: include/swift/SILOptimizer/Differentiation/AdjointValue.h [hunk 13]
```diff
@@ -38,10 +40,17 @@ enum AdjointValueKind {
...
+  /// adjoint to add to it. This case exists to avoid eager materialization of
+  /// `Aggregate` and `Zero` adjoints upon addition.
```
Comment (asl) [inline include/swift/SILOptimizer/Differentiation/AdjointValue.h:46]: Can the base be `AddElement` as well?

Comment (jkshtj) [reply include/swift/SILOptimizer/Differentiation/AdjointValue.h]: Updated in the latest revision.

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp (hunk 12 above)
Comment (jkshtj) [reply lib/SILOptimizer/Differentiation/PullbackCloner.cpp]: I see the issue here and I see what you were saying earlier. I was trying to constrain AddElement adjoint's base adjoint for no reason, it seems. It looks like it can be anything, which should truly let us defer materialization until `materializationAdjoint` is called.

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp (hunk 9 above)
Comment (jkshtj) [reply lib/SILOptimizer/Differentiation/PullbackCloner.cpp]: Fixed in the latest revision.

**Comment by jkshtj** [comment]
@BradLarson @asl could one of you kick off swift-ci please?

**Comment by asl** [comment]
@swift-ci please test

File: lib/SILOptimizer/Differentiation/AdjointValue.cpp [hunk 14]
```diff
@@ -0,0 +1,71 @@
...
+      s << addElementValue->getFieldDecl()->getNameStr();
+    }
+    s << "), ";
+
+    eltToAdd.print(s);
+
+    s << "]";
+    break;
+  }
+}
```
Comment (rxwei) [inline lib/SILOptimizer/Differentiation/AdjointValue.cpp:71]: Nit: Add a new line at the end like other files?

**Review by rxwei — APPROVED** [review]

File: lib/SILOptimizer/Differentiation/AdjointValue.cpp [hunk 15]
```diff
@@ -0,0 +1,71 @@
+//===--- AdjointValue.cpp - Helper class for differentiation ----*- C++
+//-*---===//
```
Comment (asl) [inline lib/SILOptimizer/Differentiation/AdjointValue.cpp:2]: Extra newline?

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 16]
```diff
@@ -400,12 +422,59 @@ class PullbackCloner::Implementation final
...
+    case AdjointValueKind::AddElement: {
+      auto baseAdjoint = val;
+
+      // Current adjoint may be made up of layers of `AddElement` adjoints.
+      // We can iteratively gather the list of elements to add instead of making
+      // recursive calls to `materializeAdjointIndirect`.
+      SmallVector<AddElementValue *, 4> addEltAdjValues;
+
+      do {
+        auto addElementValue = baseAdjoint.getAddElementValue();
```
Comment (asl) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp:440]: Maybe add some assertions here? After all, all these adoints must be either tuple-type or struct-like.

**Review by asl — APPROVED** [review]
Thanks! This variant seems to provide the intended functionality. See small comments here and there

**Comment by jkshtj** [comment]
@rxwei @asl Thanks a lot for reviewing this PR so far.

I have fixed the nits. Could you please take a look?

**Comment by asl** [comment]
> @rxwei @asl Thanks a lot for reviewing this PR so far!
> 
> I have fixed the nits. Could you please take a look?

See new comment.

**Comment by jkshtj** [comment]
> See new comment. 
Did you forget to publish the comment 😅?

> Also, will you please squash the commits?
Sure.

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 17]
```diff
@@ -430,6 +430,8 @@ class PullbackCloner::Implementation final
     }
     case AdjointValueKind::AddElement: {
       auto baseAdjoint = val;
+      assert(baseAdjoint.getType().is<TupleType>() ||
```
Comment (asl) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp:433]: This is not what should be checked here. This assertion is enforced during `AddElement` construction. Here you need to ensure that all nested adjoints are of the same kind: either all tuples or all structs, but not the mixture.

Comment (jkshtj) [reply lib/SILOptimizer/Differentiation/PullbackCloner.cpp:433]: I see. Sorry I sent out that last revision in haste. Fixed in the latest revision and squashed commits.

File: lib/SILOptimizer/Differentiation/PullbackCloner.cpp [hunk 18]
```diff
@@ -400,12 +422,61 @@ class PullbackCloner::Implementation final
...
+      // We can iteratively gather the list of elements to add instead of making
+      // recursive calls to `materializeAdjointIndirect`.
+      SmallVector<AddElementValue *, 4> addEltAdjValues;
+
+      do {
+        auto addElementValue = baseAdjoint.getAddElementValue();
+        addEltAdjValues.push_back(addElementValue);
+        baseAdjoint = addElementValue->baseAdjoint;
+        assert(baseAdjointType == baseAdjoint.getType());
+      } while (baseAdjoint.getKind() == AdjointValueKind::AddElement);
```
Comment (asl) [inline lib/SILOptimizer/Differentiation/PullbackCloner.cpp:445]: Do we have tests for this loop, btw? Maybe I'm missing something, but all loops are doing single struct/tuple extract?

Comment (jkshtj) [reply lib/SILOptimizer/Differentiation/PullbackCloner.cpp:445]: Not explicit tests but the other tests I have added do use this code path -- I needed to fix new test failures after making these changes. But I think it's a good idea to add explicit tests for this.

Comment (jkshtj) [reply lib/SILOptimizer/Differentiation/PullbackCloner.cpp:445]: @asl I have added tests exercising the nested add element adjoint materialization path.

**Review by asl — APPROVED** [review]
Thanks!

**Comment by asl** [comment]
@swift-ci please test

**Comment by jkshtj** [comment]
@asl Had to make some changes after I discovered some small bugs while compiling and running internal test suite. I have added tests for these cases as well.

**Review by asl — APPROVED** [review]
Makes sense, thanks!

**Comment by asl** [comment]
@swift-ci please test

**Comment by jkshtj** [comment]
@asl looks like the "Swift Test Linux Platform" failed due to some network issues. Can we restart them?

**Comment by BradLarson** [comment]
@swift-ci Please test Linux platform

**Comment by asl** [comment]
@swift-ci please test linux

**Comment by jkshtj** [comment]
Huh I see the following error due to which the Linux tests failed -

> ERROR: Error fetching remote repo 'origin'

Seems like something may be up with the Linux build hosts?

**Comment by asl** [comment]
@shahmishal Is CI down?
