### PR TITLE
Avoid loading serialized extensions for nominals in SourceFile

### LINKED ISSUE #86285: Extension on deeply nested generic ~Copyable type fails with type resolution error
# Extension on deeply nested generic `~Copyable` type fails with type resolution error

## Description

An empty extension on a deeply nested generic `~Copyable` type fails to compile when declared in the **same file** as the type definition. Moving the extension to a separate file works around the issue.

The compiler produces a cascade of errors starting with incorrect namespace resolution (`Binary.Binary` instead of `Binary`).

## Reproduction

The bug occurs in a real codebase but could not be minimally reproduced in a standalone package. To reproduce:

```bash
git clone https://github.com/swift-standards/swift-standards
cd swift-standards

# Uncomment the extension
sed -i '' 's|//extension Binary.Cursor.Set.Reader {}|extension Binary.Cursor.Set.Reader {}|' Sources/Binary/Binary.Cursor.swift

# Build
swift build --target Binary
```

Alternatively, see: https://github.com/coenttb/swift-nested-copyable-extension-bug

## Expected behavior

The empty extension should compile:

```swift
extension Binary.Cursor.Set.Reader {}
```

## Actual behavior

Compilation fails with:

```
error: 'Mutable' is not a member type of enum 'Binary.Binary'
   public struct Cursor<Storage: Binary.Mutable>: ~Copyable {
                                         `- error: 'Mutable' is not a member type of enum 'Binary.Binary'
```

Note the erroneous `Binary.Binary` - the compiler doubles the namespace during type resolution.

This triggers a cascade of ~50 additional errors as the entire type hierarchy becomes unresolvable.

## Key observations

| Scenario | Result |
|----------|--------|
| Extension in same file | ❌ Fails |
| Extension in different file | ✅ Works |
| Empty extension body | ❌ Fails |
| Sibling extension (`Binary.Cursor.Move.Reader`) | ✅ Works |
| Methods defined inline in struct | ✅ Works |

## Type structure

```swift
public enum Binary {
    public protocol Contiguous: ~Copyable {
        associatedtype Space
        associatedtype Scalar: FixedWidthInteger & Sendable = Int
    }
    public protocol Mutable: Binary.Contiguous {}

    public typealias Position<Scalar, Space> = Coordinate.X<Space>.Value<Scalar>

    public struct Cursor<Storage: Binary.Mutable>: ~Copyable { ... }
}

extension Binary.Cursor {
    public struct Set: ~Copyable { ... }
}

extension Binary.Cursor.Set {
    public struct Reader: ~Copyable { ... }
}

// This fails:
extension Binary.Cursor.Set.Reader {}
```

## Environment

- **Swift version:** 6.2.3 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
- **Platform:** macOS 26.0 (arm64-apple-macosx26.0)
- **swift-driver version:** 1.127.14.1

## Workaround

Define methods inline in the struct definition instead of using separate extensions.

### PR DESCRIPTION
**Pull request by hamishknight**
Looking up serialized extensions for a nested nominal type requires computing its mangled name, which may kick semantic requests. Ensure we don't do this for nominals in parsed SourceFiles such that we don't end up kicking this during extension binding.

Resolves #86285

### CODE REVIEW

File: test/decl/ext/extension_binding_multiple_nested.swift [hunk 1]
```diff
@@ -0,0 +1,19 @@
+// RUN: %target-typecheck-verify-swift
+// https://github.com/swiftlang/swift/issues/86285
+
+enum A {}
+
+extension A {
+  struct B<T: A.P> {}
+}
+extension A.B {
+  struct Set {}
```
Comment (slavapestov) [inline test/decl/ext/extension_binding_multiple_nested.swift]: I was about to post the same fix, but then I noticed that this nested type has to be named `Set` or some other stdlib type. If I give it a made-up name, the bug no longer occurs. Were you able to figure out why?

Comment (hamishknight) [reply test/decl/ext/extension_binding_multiple_nested.swift]: Ah sorry, didn't mean to collide with your fix. `Set` is necessary since we first check the name in `Core->ExtensionDecls`, so the serialized module needs to have an extension for a same-named nominal. Actually the test case can be reduced a bit further to:

```swift
enum A {}

extension A {
  struct Set<T: A.P> {}
}
extension A.Set {
  struct X {}
}
extension A.Set.X {}

extension A {
  protocol P {}
}
```

Comment (slavapestov) [reply test/decl/ext/extension_binding_multiple_nested.swift]: > Ah sorry, didn't mean to collide with your fix. 

No worries!

> Set is necessary since we first check the name in Core->ExtensionDecls, so the serialized module needs to have an extension for a same-named nominal. 

Ah, thanks, I missed that part. That makes sense.

File: test/decl/ext/extension_binding_multiple_nested.swift [hunk 2]
```diff
@@ -0,0 +1,19 @@
+// RUN: %target-typecheck-verify-swift
+// https://github.com/swiftlang/swift/issues/86285
```
Comment (slavapestov) [inline test/decl/ext/extension_binding_multiple_nested.swift]: FWIW, you might want to move this to test/decl/ext/ alongside the existing extension binding tests like ordering.swift

File: lib/Serialization/SerializedModuleLoader.cpp [hunk 3]
```diff
@@ -1723,6 +1723,14 @@ bool MemoryBufferSerializedModuleLoader::unregisterMemoryBuffer(
 
 void SerializedModuleLoaderBase::loadExtensions(NominalTypeDecl *nominal,
                                                 unsigned previousGeneration) {
+  // Nominals in parsed SourceFiles can't have extensions provided by imported
+  // serialized modules. This is necessary to avoid triggering semantic requests
+  // from extension binding since looking up extensions may need to compute the
+  // mangled name.
+  auto *SF = nominal->getParentSourceFile();
+  if (SF && SF->Kind != SourceFileKind::Interface)
```
Comment (hamishknight) [inline lib/Serialization/SerializedModuleLoader.cpp]: Actually I don't think this should be conditional on `Interface`

File: test/decl/ext/extension_binding_multiple_nested.swift (hunk 2 above)
Comment (hamishknight) [reply test/decl/ext/extension_binding_multiple_nested.swift]: Heh, I saw `test/Sema/extension_binding_multi.swift`, I guess I can move that too

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by slavapestov** [comment]
You should cherry pick this to 6.3 when its ready, since I believe it's a regression from the noncopyable work (prior to that, ASTMangler didn't call getGenericSignature() on nominal type decls AFAIK).

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@slavapestov I'm actually able to reproduce this at least as far back as 4.0, looks like mangling the extension context calls `isEquivalentToExtendedContext` which computes the generic signature. The other minimized variant works up until 6.0 by the looks of things

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test macOS

**Comment by hamishknight** [comment]
@swift-ci please smoke test macOS

**Review by xymus — APPROVED** [review]

**Comment by hamishknight** [comment]
@swift-ci please test macOS
