### PR TITLE
Fix invalid warning for enum cases named self

### LINKED ISSUE #57970: [SR-15691] Invalid warning: 'self' refers to the method 'Foo.self'
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15691      |
   |Radar             | None         |
   |Original Reporter | @keith      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 92266992a8216159c3017c1eaba44660

  </details>

**Issue Description:**

With this code and Swift 5.5, it compiled fine:

``` none
enum Foo {
    case `self`

    init() {
        self = .self
    }
}
```

With the 2021-12-23 main snapshot (org.swift.50202112231a) compiling gives an seemingly impossible to silence warning, here are the variations I tried:

``` none
enum Foo {
    case `self`

    init() {
        // This option produces:
        // /tmp/qux.swift:5:17: warning: 'self' refers to the method 'Foo.self', which may be unexpected
        //         self = .self
        //                 ^
        // /tmp/qux.swift:5:17: note: use 'Foo.self' to silence this warning
        //         self = .self
        //                 ^
        //                 Foo.
        self = .self

        // This option fails to compile
        // /tmp/qux.swift:15:16: error: cannot assign value of type 'Foo.Type' to type 'Foo'
        //         self = Foo.self
        //                ^~~~~~~~
        // self = Foo.self

        // This option produces:
        // /tmp/qux.swift:22:20: warning: 'self' refers to the method 'Foo.self', which may be unexpected
        //         self = Foo.`self`
        //                    ^
        // /tmp/qux.swift:22:20: note: use 'Foo.self' to silence this warning
        //         self = Foo.`self`
        //                    ^
        //                    Foo.
        self = Foo.`self`
    }
}
```

I believe this might have been introduced as the fix for <https://bugs.swift.org/browse/SR-4559> here <https://github.com/apple/swift/commit/7e0a7f322aedd93ae7359884f7c8b4e6884f63d9>

cc jackmarch (JIRA User)

### PR DESCRIPTION
**Pull request by keith**
https://github.com/apple/swift/pull/37992/ introduced a warning when you
were likely to confuse `self` with `TypeName.self`, this also applied to
enum cases that were named `self`, these cases should not be easily
confused at call sites since their use requires prefixing them with a
`.`. There was also no way to avoid this warning since other syntax such
as `TypeName.self`, which produces the enum type instead, or
`` TypeName.`self` `` which produced the same warning again.

Fixes #57970

### CODE REVIEW

**Comment by keith** [comment]
cc @xedin @jackgmarch since you all worked on the original

**Comment by keith** [comment]
@swift-ci please test

File: lib/Sema/MiscDiagnostics.cpp [hunk 1]
```diff
@@ -4748,19 +4748,20 @@ static void diagUnqualifiedAccessToMethodNamedSelf(const Expr *E,
           if (auto typeContext = DC->getInnermostTypeContext()) {
             // self() is not easily confusable
             if (!isa<CallExpr>(Parent.getAsExpr())) {
-
               auto baseType = typeContext->getDeclaredInterfaceType();
-              auto baseTypeString = baseType.getString();
+              if (baseType->getEnumOrBoundGenericEnum() == nullptr) {
```
Comment (xedin) [inline lib/Sema/MiscDiagnostics.cpp:4752]: Nit: Can use ! instead of == nullptr here

**Review by xedin — APPROVED** [review]
Thank you, looks good!

File: lib/Sema/MiscDiagnostics.cpp (hunk 1 above)
Comment (keith) [reply lib/Sema/MiscDiagnostics.cpp]: sg done

**Comment by keith** [comment]
@swift-ci please test

**Comment by keith** [comment]
Hoping to cherry pick this into 5.6 in https://github.com/apple/swift/pull/41529
