### PR TITLE
[IRGen][DebugInfo] split method declaration and definition.

### LINKED ISSUE #53940: [SR-11539] llvm-link: dsymutil prints warning: could not find referenced DIE
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-11539      |
   |Radar             | rdar://problem/55802700         |
   |Original Reporter | jholajter (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963470-0c37c6a1-4fff-45f7-90ca-5a9bfb85e9f4.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 4         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | @JDevlieghere      |
   |Priority          | Medium      |

   

   md5: f5a1284ed6017ecdbfbe081809c954a1

  </details>

**Issue Description:**

When using `llvm-link` to link multiple bitcode files from swift source, the following warning is seen when using `dsymutil`:

 

``` java
warning: could not find referenced DIE
note: while processing /private/tmp/gulps/llvm-linked-bitcode.bc.o
```

 

This is very similar to the problem reported in https://bugs.swift.org/browse/SR-5935 which has been marked as resolved.

 

In the attached `llvm-link-dsymutil-repro.zip`, if the "17.bc" and "24.bc" are linked together using `llvm-link`, `dsymutil` outputs warnings as seen in the attached "repro-output.txt"

 

The "repro.sh" script can be used to reproduce the issue. However because of the limits in the attachment size, I could not include the dependent Frameworks. I can send those via another mechanism upon request. Alternatively, they can be obtained by building the open source Gulps application found at <https://github.com/FancyPixel/gulps>

 

The artifacts in the attachments were generated using Xcode 11.1 GM.

### PR DESCRIPTION
**Pull request by dianqk**
When the function is a method, we only want a `DW_AT_declaration`
there, because LLVM LTO can't unify type definitions when a child DIE is a
full subprogram definition. Now the subprogram definition gets added at the
CU level with a specification link back to the abstract declaration.

Both GCC and Clang write debuginfo this way for C++ class methods. [Now Rust is too](https://github.com/rust-lang/rust/pull/111167).

Related discussions:
- [[Verifier] definition subprograms cannot be nested within DICompositeType when enabling ODR.](https://reviews.llvm.org/D152095)
- https://github.com/llvm/llvm-project/issues/61932
- https://github.com/rust-lang/rust/pull/111167

Fixes #53940.

### CODE REVIEW

**Comment by DianQK** [comment]
@swift-ci please test

File: test/DebugInfo/method.swift [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+func a_function() {}
+
+// CHECK: distinct !DISubprogram(name: "static_method",
+// CHECK-SAME: declaration:
+// CHECK: distinct !DISubprogram(name: "method",
+// CHECK-SAME: declaration:
+// CHECK: distinct !DISubprogram(name: "static_method",
+// CHECK-SAME: declaration:
+// CHECK: distinct !DISubprogram(name: "method",
+// CHECK-SAME: declaration:
```
Comment (adrian-prantl) [inline test/DebugInfo/method.swift:23]: Could you also add a CHECK testing that the declaration is indeed for the same method and that the parent type (e.g., Foo) lists the declaration, not the definition?

**Review by adrian-prantl — APPROVED** [review]

**Comment by DianQK** [comment]
@adrian-prantl  Could you help me invoke `swift-ci` and merge changes? This is my first pull request.

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by DianQK** [comment]
After adding the parameter `--param backtracing`, I can reproduce the `test/Backtracing/Crash.swift` error. Trying to solve it.

**Comment by DianQK** [comment]
After this PR, a DWARF in the following format may be generated:
```
0x00000d58:       DW_TAG_subprogram
                    DW_AT_linkage_name	("$s8CrashOpt0A0V5$mainyyFZ")
                    DW_AT_name	("$main")
                    DW_AT_type	(0x00000f65 "$sytD")
                    DW_AT_declaration	(true)
                    DW_AT_external	(true)
                    DW_AT_APPLE_optimized	(true)
...
0x00000d9d:         DW_TAG_inlined_subroutine
                      DW_AT_abstract_origin	(0x000011d2 "$s8CrashOpt0A0V5$mainyyFZ")
                      DW_AT_ranges	(0x00000210
                         [0x00000000000011e0, 0x00000000000012f3)
                         [0x00000000000012fb, 0x0000000000001307))
                      DW_AT_call_file	("/home/dianqk/Projects/swift-project/swift/test/Backtracing/Crash.swift")
                      DW_AT_call_line	(0)
...
0x000011d2:   DW_TAG_subprogram
                DW_AT_specification	(0x00000d58 "$s8CrashOpt0A0V5$mainyyFZ")
                DW_AT_inline	(DW_INL_inlined)
```
I put [b00d1520f89bb7df1d2a3eeee57cae7682755634](https://github.com/apple/swift/pull/67077/commits/b00d1520f89bb7df1d2a3eeee57cae7682755634) to this PR to show on CI that this did work.

Opening a new PR should be a better option. #67592

**Comment by DianQK** [comment]
I also tried to solve the failure of `lang/swift/async/stepping/step-in/task-switch/TestSwiftTaskSwitch.py` on macOS.
The https://github.com/apple/llvm-project/pull/7114 is a change that can pass the test case. But I have no lldb related knowledge.
This might be something to ask @kastiglione to take a look at, thanks.

**Comment by al45tair** [comment]
I've reviewed the backtracing change in #67592. TL/DR: It looks fine, though I think I'd like it to check the tag to make sure the `DW_AT_specification` is pointing at the kind of thing we expect.

**Review by al45tair — APPROVED** [review]
Seems reasonable to me, modulo my comment about checking the tag.

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by DianQK** [comment]
I figured out why the `TestSwiftTaskSwitch.py` test case was failing. I tried to submit the patch https://reviews.llvm.org/D157184.

**Comment by DianQK** [comment]
Rebase and update code comments.

**Review by adrian-prantl — APPROVED** [review]

**Comment by felipepiovezan** [comment]
@swift-ci test
