### PR TITLE
[Concurrency] Fix `SendableMetatype` conformance failures to behave l…

### LINKED ISSUE #81739: `@preconcurrnecy` doesn't downgrade `SendableMetatype` error
### Description

We need a way to stage in the required change of `SendableMetatype` without breaking existing clients similar to how we were able to do this with `Sendable`.

### Reproduction

The following code produces an error even though `@preconcurrency` is added to the method in an attempt to downgrade the error:

```swift
// Module A
public protocol GlobalLookup {
  static func lookupByName(_ name: String) -> Self?
}
public func hasNamed<T: GlobalLookup & SendableMetatype>(_: T.Type, name: String) async -> Bool {
   return await Task.detached {
     return T.lookupByName(name) != nil
   }.value
}

// Module B
func bar<T: GlobalLookup>(t: T.Type) async {
    _ = await hasNamed(t.self, name: "p") // error: Global function 'hasNamed(_:name:)' requires that 'T' conform to 'SendableMetatype'
}
```

### Expected behavior

I expect that `@preconcurrency` downgrades this to an error

### Environment

Latest swift nightly and 6.2 snapshot

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by xedin**
…ike `Sendable` ones

No warnings with minimal checking, warnings with `strict-concurrency=complete` and if declaration is `@preconcurrency` until next major swift version.

Resolves: rdar://151911135
Resolves: https://github.com/swiftlang/swift/issues/81739

### CODE REVIEW

File: lib/Sema/TypeCheckConcurrency.cpp [hunk 1]
```diff
@@ -764,18 +764,29 @@ static void addSendableFixIt(
...
     auto fixItLoc = genericArgument->getInherited().getEndLoc();
-    diag.fixItInsertAfter(fixItLoc, " & Sendable");
+    diag.fixItInsertAfter(fixItLoc, " & " + protocolName);
   }
 }
+/// Add Fix-It text for the given generic param declaration type to adopt
+/// Sendable.
+static void addSendableFixIt(const GenericTypeParamDecl *genericArgument,
+                             InFlightDiagnostic &diag) {
+  addProtocolFixIt(genericArgument, diag, "Sendable");
```
Comment (ktoso) [inline lib/Sema/TypeCheckConcurrency.cpp]: minor nit, is it worth doing `getProtocolName(KnownProtocolKind::Sendable)` ?

File: include/swift/AST/DiagnosticsSema.def [hunk 2]
```diff
@@ -5943,6 +5943,8 @@ ERROR(concurrent_value_inherit,none,
       (bool, DeclName))
 ERROR(non_sendable_type,none,
       "type %0 does not conform to the 'Sendable' protocol", (Type))
+ERROR(non_sendable_metatype_type,none,
```
Comment (DougGregor) [inline include/swift/AST/DiagnosticsSema.def]: Can you put this diagnostic in the new SendableMetatypes group?

**Review by DougGregor — APPROVED** [review]
Fantastic, thank you!

**Review by ktoso — APPROVED** [review]

File: lib/Sema/TypeCheckConcurrency.cpp (hunk 1 above)
Comment (xedin) [reply lib/Sema/TypeCheckConcurrency.cpp]: Oh, good idea!

File: include/swift/AST/DiagnosticsSema.def (hunk 2 above)
Comment (xedin) [reply include/swift/AST/DiagnosticsSema.def]: Sure!

Comment (xedin) [reply include/swift/AST/DiagnosticsSema.def]: ✅

File: lib/Sema/TypeCheckConcurrency.cpp (hunk 1 above)
Comment (xedin) [reply lib/Sema/TypeCheckConcurrency.cpp]: ✅

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please clean test Linux platform

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Comment by xedin** [comment]
@swift-ci please smoke test
