### PR TITLE
Correctly handle multiple semantic results for autodiff subset differential thunks

### LINKED ISSUE #84365: [AutoDiff] Invalid subset parameter / result thunk is generated for the differential
### Description

Consider the code attached. Compiling it yields a SIL verification assertion:

```log
Begin Error in Function: '$sSa16_DifferentiationAA14DifferentiableRzlE0B4ViewVySf_GA3EIeggooo_TJSdSpSSSrSP'
Error! Found a leaked owned value that was never consumed.
Value: (%3, %4, **%5**) = destructure_tuple %2 : $(Array<Float>.DifferentiableView, Array<Float>.DifferentiableView, Array<Float>.DifferentiableView)

End Error in Function: '$sSa16_DifferentiationAA14DifferentiableRzlE0B4ViewVySf_GA3EIeggooo_TJSdSpSSSrSP'
Found ownership error?!
```

And indeed, it seems that subset thunks generated for differentials for functions with multiple semantics results are quite broken. They do not support semantic result parameters as well (inouts). And it seems that they work solely due to the typo there :)

### Reproduction

```swift
import _Differentiation

@differentiable(reverse,wrt: logits)
public func softSolveForwardWithQ(logits: [Float]) -> ([Float], [Float]) {
    return ([Float](repeating: 0, count: 0), [])
}

@derivative(of: softSolveForwardWithQ, wrt: logits)
public func vjpSoftSolveForwardWithQ(logits: [Float]) -> (value: ([Float], [Float]), pullback: ([Float].TangentVector, [Float].TangentVector) -> [Float].TangentVector) {
    let n = logits.count
    let q = [Float](repeating: 0, count: 0)
    let y = [Float](repeating: 0, count: 0)

    return (
        value: (y, q),
        pullback: { _, _ in 
            return Array<Float>.DifferentiableView([Float](repeating: 0, count: n))
        }
    )
}

@differentiable(reverse,wrt: logits)
public func forwardPredict(logits: [Float]) -> ([Float], [Float], [Float]) {
    let (y, q) = softSolveForwardWithQ(logits: logits)
    return (y, q, [0.0])
}

@derivative(of: forwardPredict, wrt: logits)
public func vjpForwardPredict(logits: [Float]) -> (
    value: ([Float], [Float], [Float]),
    pullback: ([Float].TangentVector, [Float].TangentVector, [Float].TangentVector) -> [Float].TangentVector
) {
    let (valYQ, pb) = vjpSoftSolveForwardWithQ(logits: logits)
    let (y, q) = valYQ
    return ((y, q, [0.0]), { upY, upQ, _ in pb(upY, upQ) }) 
}

@differentiable(reverse,wrt: logits)
public func crossEntropyFromForwardPredict(logits: [Float]) -> Float {
    let (_, q, _) = forwardPredict(logits: logits)
    return q[0] + 1e-8
}
```

### Stack dump

```text
<unknown>:0: error: fatal error encountered during compilation; please submit a bug report (https://swift.org/contributing/#reporting-bugs)
<unknown>:0: note: triggering standard assertion failure routine
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /cefs/3f/3faf439a4df03eff2fc60bff_swift-nightly/usr/bin/swift-frontend -frontend -emit-sil -primary-file <source> -target x86_64-unknown-linux-gnu -disable-objc-interop -no-color-diagnostics -Xcc -fno-color-diagnostics -g -debug-info-format=dwarf -dwarf-version=4 -empty-abi-descriptor -enable-anonymous-context-mangled-names -file-compilation-dir /app -Xllvm --x86-asm-syntax=intel -no-auto-bridging-header-chaining -module-name output -in-process-plugin-server-path /cefs/3f/3faf439a4df03eff2fc60bff_swift-nightly/usr/lib/swift/host/libSwiftInProcPluginServer.so -plugin-path /cefs/3f/3faf439a4df03eff2fc60bff_swift-nightly/usr/lib/swift/host/plugins -plugin-path /cefs/3f/3faf439a4df03eff2fc60bff_swift-nightly/usr/local/lib/swift/host/plugins -o /app/output.s
1.	Swift version 6.3-dev (LLVM 73f0f4667f22bd1, Swift c987ea9c8e684c2)
2.	Compiling with effective version 5.10
3.	While verifying SIL function "@$sSa16_DifferentiationAA14DifferentiableRzlE0B4ViewVySf_GA3EIeggooo_TJSdSpSSSrSP".
 for expression at [<source>:40:21 - line:40:21] RangeText=""
 #0 0x00005605bfb8f0e8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/cefs/3f/3faf439a4df03eff2fc60bff_swift-nightly/usr/bin/swift-frontend+0x8c610e8)
 #1 0x00005605bfb8cc0e llvm::sys::RunSignalHandlers() (/cefs/3f/3faf439a4df03eff2fc60bff_swift-nightly/usr/bin/swift-frontend+0x8c5ec0e)
 #2 0x00005605bfb8f781 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #3 0x00007638b3442520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007638b34969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007638b3442476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007638b34287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00005605b8204a48 swift::DiagnosticHelper::Implementation::diagnoseFatalError(char const*, bool) crtstuff.c:0:0
 #8 0x00005605bfae26f9 llvm::report_fatal_error(llvm::Twine const&, bool) (/cefs/3f/3faf439a4df03eff2fc60bff_swift-nightly/usr/bin/swift-frontend+0x8bb46f9)
 #9 0x00005605bfae25e6 (/cefs/3f/3faf439a4df03eff2fc60bff_swift-nightly/usr/bin/swift-frontend+0x8bb45e6)
#10 0x00005605b8c5d664 swift::LinearLifetimeChecker::ErrorBuilder::handleError(llvm::function_ref<void ()>&&, bool) const crtstuff.c:0:0
#11 0x00005605b8c5c4fb swift::SILValueOwnershipChecker::checkValueWithoutLifetimeEndingUses(llvm::ArrayRef<swift::Operand*>, llvm::ArrayRef<swift::Operand*>) (/cefs/3f/3faf439a4df03eff2fc60bff_swift-nightly/usr/bin/swift-frontend+0x1d2e4fb)
#12 0x00005605b8c5a494 swift::SILValueOwnershipChecker::checkUses() (/cefs/3f/3faf439a4df03eff2fc60bff_swift-nightly/usr/bin/swift-frontend+0x1d2c494)
#13 0x00005605b8c5a0f0 swift::SILValueOwnershipChecker::check() (/cefs/3f/3faf439a4df03eff2fc60bff_swift-nightly/usr/bin/swift-frontend+0x1d2c0f0)
#14 0x00005605b8c5cd84 verifySILValueHelper(swift::SILFunction const*, swift::SILValue, swift::LinearLifetimeChecker::ErrorBuilder&, swift::DeadEndBlocks*, swift::GuaranteedPhiVerifier&) SILOwnershipVerifier.cpp:0:0
#15 0x00005605b8c5cc0b swift::SILValue::verifyOwnership(swift::DeadEndBlocks*) const (/cefs/3f/3faf439a4df03eff2fc60bff_swift-nightly/usr/bin/swift-frontend+0x1d2ec0b)
#16 0x00005605b8c8d4b5 (anonymous namespace)::SILVerifier::checkValueBaseOwnership(swift::ValueBase*) SILVerifier.cpp:0:0
#17 0x00005605b8c905e4 (anonymous namespace)::SILVerifier::visitSILInstruction(swift::SILInstruction*) SILVerifier.cpp:0:0
#18 0x00005605b8c762c7 swift::SILVisitorBase<(anonymous namespace)::SILVerifier, void>::visitSILBasicBlock(swift::SILBasicBlock*) SILVerifier.cpp:0:0
#19 0x00005605b8c6a2df (anonymous namespace)::SILVerifier::visitSILBasicBlock(swift::SILBasicBlock*) SILVerifier.cpp:0:0
#20 0x00005605b8c684bb (anonymous namespace)::SILVerifier::visitSILFunction(swift::SILFunction*) SILVerifier.cpp:0:0
#21 0x00005605b8c5fe88 swift::SILFunction::verify(swift::CalleeCache*, bool, bool, bool) const (/cefs/3f/3faf439a4df03eff2fc60bff_swift-nightly/usr/bin/swift-frontend+0x1d31e88)
#22 0x00005605b8c63c38 swift::SILModule::verify(swift::CalleeCache*, bool, bool) const (/cefs/3f/3faf439a4df03eff2fc60bff_swift-nightly/usr/bin/swift-frontend+0x1d35c38)
#23 0x00005605b8c63aef swift::SILModule::verify(bool, bool) const (/cefs/3f/3faf439a4df03eff2fc60bff_swift-nightly/usr/bin/swift-frontend+0x1d35aef)
#24 0x00005605b82133d4 swift::CompilerInstance::performSILProcessing(swift::SILModule*) (/cefs/3f/3faf439a4df03eff2fc60bff_swift-nightly/usr/bin/swift-frontend+0x12e53d4)
#25 0x00005605b7e98927 performCompileStepsPostSILGen(swift::CompilerInstance&, std::unique_ptr<swift::SILModule, std::default_delete<swift::SILModule>>, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*) FrontendTool.cpp:0:0
#26 0x00005605b7e97730 swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) (/cefs/3f/3faf439a4df03eff2fc60bff_swift-nightly/usr/bin/swift-frontend+0xf69730)
#27 0x00005605b7eadcca withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) FrontendTool.cpp:0:0
#28 0x00005605b7e9cca4 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) FrontendTool.cpp:0:0
#29 0x00005605b7e99971 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) (/cefs/3f/3faf439a4df03eff2fc60bff_swift-nightly/usr/bin/swift-frontend+0xf6b971)
#30 0x00005605b7bfef80 swift::mainEntry(int, char const**) (/cefs/3f/3faf439a4df03eff2fc60bff_swift-nightly/usr/bin/swift-frontend+0xcd0f80)
#31 0x00007638b3429d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#32 0x00007638b3429e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#33 0x00005605b7bfdfd5 _start (/cefs/3f/3faf439a4df03eff2fc60bff_swift-nightly/usr/bin/swift-frontend+0xccffd5)
```

### Expected behavior

Correct subset thunk is created

### Environment

Swift version 6.3-dev (LLVM d804f1f0258914f, Swift f244c8f5b40959c)
Target: arm64-apple-macosx15.0
Build config: +assertions

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by asl**
Fixes https://github.com/swiftlang/swift/issues/84365

### CODE REVIEW

**Comment by asl** [comment]
Apparently, the original code contained a typo (and some kind of kludge for inouts) that made it work for the majority of "simple" cases (e.g. single result passed direct or indirect, or inout), but it failed miserably when we had 3 proper results (as in the testcase).

**Comment by asl** [comment]
@swift-ci Please test

**Comment by asl** [comment]
Tagging @JaapWijnen

File: test/AutoDiff/compiler_crashers_fixed/issue-84365-autodiff-subset-thunks-differential.swift [hunk 1]
```diff
@@ -0,0 +1,49 @@
+// RUN: %target-swift-frontend -emit-sil -verify %s
+
+// https://github.com/swiftlang/swift/issues/84365
+// Ensure autodiff subset thunks for differential correctly
+// handle multiple semantic results and release unwanted
+// result values
+
+import _Differentiation
+
+@differentiable(reverse,wrt: logits)
```
Comment (kovdan01) [inline test/AutoDiff/compiler_crashers_fixed/issue-84365-autodiff-subset-thunks-differential.swift:10]: Nit
```suggestion
@differentiable(reverse, wrt: logits)
```

File: test/AutoDiff/compiler_crashers_fixed/issue-84365-autodiff-subset-thunks-differential.swift [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+
+    return (
+        value: (y, q),
+        pullback: { _, _ in 
+            return Array<Float>.DifferentiableView([Float](repeating: 0, count: n))
+        }
+    )
+}
+
+@differentiable(reverse,wrt: logits)
```
Comment (kovdan01) [inline test/AutoDiff/compiler_crashers_fixed/issue-84365-autodiff-subset-thunks-differential.swift:29]: Nit
```suggestion
@differentiable(reverse, wrt: logits)
```

File: test/AutoDiff/compiler_crashers_fixed/issue-84365-autodiff-subset-thunks-differential.swift [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+public func vjpForwardPredict(logits: [Float]) -> (
+    value: ([Float], [Float], [Float]),
+    pullback: ([Float].TangentVector, [Float].TangentVector, [Float].TangentVector) -> [Float].TangentVector
+) {
+    let (valYQ, pb) = vjpSoftSolveForwardWithQ(logits: logits)
+    let (y, q) = valYQ
+    return ((y, q, [0.0]), { upY, upQ, _ in pb(upY, upQ) }) 
+}
+
+@differentiable(reverse,wrt: logits)
```
Comment (kovdan01) [inline test/AutoDiff/compiler_crashers_fixed/issue-84365-autodiff-subset-thunks-differential.swift:45]: Nit
```suggestion
@differentiable(reverse, wrt: logits)
```

**Review by kovdan01 — APPROVED** [review]
LGTM, thanks!

**Comment by asl** [comment]
@swift-ci please test linux

**Comment by asl** [comment]
@swift-ci please test linux
