### PR TITLE
Sema: Change behavior of implied 'Sendable' conformance

### LINKED ISSUE #71544: Wrong compiler error regarding conditional conformances that involve Sendable
### Description

Hello,

The Swift 5.10 compiler (Xcode version 15.3 beta 2 (15E5188j)) produces a compiler error that I believe is unexpected when it compiles code that involves conditional conformances and the `Sendable` protocol.

### Reproduction

```swift
protocol A: Sendable { }
protocol B: Sendable { }
struct S<T> { }
extension S: A where T: A { }
extension S: B where T: B { } // ❌ 'B' requires that 'T' conform to 'A'
```

### Expected behavior

There is no compiler error.

---

Another way to look at the issue is to split the sample code into library code, and user code:

```swift
// Library code
public protocol A: Sendable { }
public protocol B: Sendable { }

// User code
struct S<T> { }
extension S: A where T: A { }
extension S: B where T: B { } // ❌ 'B' requires that 'T' conform to 'A'
```

In a previous version on the library, the protocols `A` and `B` did not conform to Sendable, and user code did compile smoothly:

```swift
// Previous version on the library did not involve Sendable:
public protocol A { }
public protocol B { }

// User code
struct S<T> { }
extension S: A where T: A { } // ✅
extension S: B where T: B { } // ✅
```

The error only appears when the library adds Sendable requirements. I was asked in the [Swift forums](https://forums.swift.org/t/is-adding-a-sendable-requirement-a-breaking-change/69957/7) to open an issue every time I see that adding a `Sendable` requirement could break user code, so here it is 😊 Indeed, the user can not fix those errors without adding possibly wrong conditions: this is a breaking change.

The reader has recognised in the reduced sample code the classic pattern in which a `RawRepresentable` type is augmented with conditional conformances (see an [example of this pattern](https://github.com/pointfreeco/swift-tagged/blob/e4955955e17abc8765a79f3e4f1e56864cc4f2b5/Sources/Tagged/Tagged.swift#L38)). The bug looks severe to me, because this pattern is quite frequent.

---

For the record, my "real" setup is a little it more complex that the reduced case exposed above. It exhibits some more weird compiler behaviors:

```swift
public protocol A: Sendable { }
public protocol B: Sendable { }
public protocol C: Sendable { }
public protocol D: A & B & C { }
public protocol E: C { }

struct S<T> { }
extension S: A where T: A { } // ✅
extension S: B where T: B { } // ❌ 'B' requires that 'T' conform to 'A'
extension S: C where T: C { } // ❌ 'C' requires that 'T' conform to 'A'
extension S: D where T: D { } // ✅
extension S: E where T: E { } // ✅
```

"Fixing" the first error by adding a condition does not remove the second error (that's somewhat expected, at least the compiler is consistently erroneous):

```swift
extension S: A where T: A { }     // ✅
extension S: B where T: B & A { } // ✅ "fixed"
extension S: C where T: C { }     // ❌ 'C' requires that 'T' conform to 'A'
extension S: D where T: D { }     // ✅
extension S: E where T: E { }     // ✅
```

But "fixing" the second error by adding a condition creates an error at another place 😅 :

```swift
extension S: A where T: A { }     // ✅
extension S: B where T: B { }     // ❌ 'B' requires that 'T' conform to 'A'
extension S: C where T: C & A { } // ✅ "fixed"
extension S: D where T: D { }     // ✅
extension S: E where T: E { }     // ❌ 'E' requires that 'T' conform to 'A'
```

I hope those examples are good food for regression tests.

### Environment

Swift 5.10 (Xcode version 15.3 beta 2 (15E5188j))

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by slavapestov**
Today, this gives you a conditional conformance to `Sendable` in Swift 5 and 6 language mode:

```
protocol P: Sendable {}
struct G<T> {}
extension G: P where T: P {}
// implied: extension G: Sendable where T: P {}
```

Change this so that in Swift 5 mode, the implied conformance is unconditional:

```
extension G: P where T: P {}
// implied: extension G: Sendable {}
```

And ban it outright in Swift 6 mode:

```
extension G: P where T: P {}  // error
```

Fixes rdar://95695543.
Fixes rdar://122754849.
Fixes https://github.com/swiftlang/swift/issues/71544.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by xedin — APPROVED** [review]

File: lib/Sema/TypeCheckProtocol.cpp [hunk 1]
```diff
@@ -2415,8 +2415,16 @@ checkIndividualConformance(NormalProtocolConformance *conformance) {
       ComplainLoc, diag::unchecked_conformance_not_special, ProtoType);
   }
 
+  bool allowImpliedConditionalConformance = false;
+  if (Proto->isSpecificProtocol(KnownProtocolKind::Sendable)) {
+    if (Context.LangOpts.StrictConcurrencyLevel != StrictConcurrency::Complete)
```
Comment (DougGregor) [inline lib/Sema/TypeCheckProtocol.cpp:2420]: Should this be checking for Swift 6 instead, so we don't change Swift 5 code that enabled strict checking?
