### PR TITLE
Issue-60730: Addressing the situation where we were saying that (any …

### LINKED ISSUE #60730: Improve error message for type mismatch between `any P` and `(any P)?`
If you try to pass a value of type `(any P)?` to an argument of type `any P`, Swift should produce an error telling you to unwrap the optional. Instead, it tells you that `(any P)?` doesn’t conform to `P`, which is confusing, and the user probably meant to unwrap the argument anyway.

```swift
protocol P {}

struct S: P {}

func takesP(_: any P) {}

func passOptional(value: (any P)?) {
  takesP(value) // error: Argument type '(any P)?' does not conform to expected type 'P'

  takesP(value ?? S()) // okay
  takesP(value!) // okay
}
```

The constraint system currently applies the `MissingConformance` fix when solving for  the `takesP(value)` expression. Instead, it should identify that the wrapped type of the argument matches the parameter type, and apply the `ForceOptional` fix.

This is also tracked by rdar://94037733

### PR DESCRIPTION
**Pull request by dfperry5**
…P)? does not conform to P, instead we should offer the Force Optional error messaging

Addressing Issue-60730 (https://github.com/apple/swift/issues/60730). In this scenario, we were showing the error message `error: Argument type '(any P)?' does not conform to expected type 'P'` to the user. In the case outlined in the issue, a more informative message would be displayed if we applied the `ForceOptional` fix, which is exactly what this PR does.

Resolves: https://github.com/apple/swift/issues/60730

### CODE REVIEW

**Review by LucianoPAlmeida — COMMENTED** [review]
@dfperry5 Thanks for the contribution!
A couple of tips:
* Take a look at the [How do I format my changes section](https://github.com/apple/swift/blob/main/docs/HowToGuides/FAQ.md#how-do-i-format-my-changes) to make sure the new introduced changes nicely formatted.
* We also need to add test cases: See [Running test section](https://github.com/apple/swift/blob/main/docs/HowToGuides/GettingStarted.md#running-tests). That will help you to run the tests locally using lit and make sure that things are working as expected. 

If you have any question, don't hesitate to ask.
Hope that helps :)

File: lib/Sema/CSSimplify.cpp [hunk 1]
```diff
@@ -3635,9 +3635,20 @@ ConstraintSystem::matchExistentialTypes(Type type1, Type type2,
...
-            if (recordFix(fix, /*impact=*/2))
+            auto impact = 2;
+            if (type1 -> isOptional()) {
+              auto unwrappedType = type1 -> getOptionalObjectType();
+              auto matchTypeResult = matchTypes(unwrappedType, type2, ConstraintKind::Conversion, subflags, locator);
+              if (matchTypeResult.isSuccess()) {
+                // Impact here is a 1 because there is only one failure before
+                // we need to force type1 to be
+                impact = 1;
+                fix = ForceOptional::create(*this, type1, proto, getConstraintLocator(locator));
```
[the remark this answers is not in the document]
Comment (dfperry5) [reply lib/Sema/CSSimplify.cpp:3646]: This makes sense to me! I'll give it a shot!

File: lib/Sema/CSSimplify.cpp [hunk 2]
```diff
@@ -3635,9 +3635,20 @@ ConstraintSystem::matchExistentialTypes(Type type1, Type type2,
             // This would make sure that arguments with incorrect
             // conformances are not prioritized over general argument
             // mismatches.
-            if (recordFix(fix, /*impact=*/2))
+            auto impact = 2;
+            if (type1 -> isOptional()) {
+              auto unwrappedType = type1 -> getOptionalObjectType();
```
[the remark this answers is not in the document]
Comment (dfperry5) [reply lib/Sema/CSSimplify.cpp:3640]: Hmm. I don't know why we wouldn't want to go deeper.

Do you know a better way of doing that than building while loop or recursive function?

[the remark this answers is not in the document]
Comment (LucianoPAlmeida) [reply lib/Sema/CSSimplify.cpp:3640]: Take a look into `lookThroughAllOptionalTypes` method :)

[the remark this answers is not in the document]
Comment (dfperry5) [reply lib/Sema/CSSimplify.cpp:3640]: Thank you!

File: lib/Sema/CSSimplify.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (dfperry5) [reply lib/Sema/CSSimplify.cpp]: I believe I updated this! If you have time to take a look, I still need to write tests :)

File: lib/Sema/CSSimplify.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (dfperry5) [reply lib/Sema/CSSimplify.cpp]: I updated this! Will try to write a test to validate these different scenarios.

File: lib/Sema/CSSimplify.cpp [hunk 3]
```diff
@@ -3626,18 +3626,34 @@ ConstraintSystem::matchExistentialTypes(Type type1, Type type2,
...
             //
             // This would make sure that arguments with incorrect
             // conformances are not prioritized over general argument
             // mismatches.
-            if (recordFix(fix, /*impact=*/2))
+            unsigned impact;
+            if (type1->isOptional()) {
+              auto unwrappedType = type1->lookThroughAllOptionalTypes();
+              auto matchTypeResult =
+                  matchTypes(unwrappedType, type2, ConstraintKind::Conversion,
```
Comment (xedin) [inline lib/Sema/CSSimplify.cpp:3640]: New condition is incorrect because this is happening during check that verifies that existential type represented by `type1` satisfies all protocol requirements of existential type `type2`, we cannot simply try to convert there to determine whether unwrap works or not, we need to re-run `simplifyConformsToConstraint`  (with added `TMF_ApplyingFix` flag) on unwrapped type to figure that out.

File: lib/Sema/CSSimplify.cpp [hunk 4]
```diff
@@ -3626,18 +3626,34 @@ ConstraintSystem::matchExistentialTypes(Type type1, Type type2,
...
+                             subflags, locator);
+              if (matchTypeResult.isSuccess()) {
+                // Impact here is a 1 because there is only one failure before
+                // we need to force type1 to be
+                impact = 1;
+                fix = ForceOptional::create(*this, type1, proto,
+                                            getConstraintLocator(locator));
```
Comment (xedin) [inline lib/Sema/CSSimplify.cpp:3647]: To simplify this code you can `recordFix` directly here with return and add a `break` right after, that way you won't need to use `ConstraintFix *` and impact variables.

**Review by xedin — CHANGES_REQUESTED** [review]

File: lib/Sema/CSSimplify.cpp (hunk 3 above)
Comment (dfperry5) [reply lib/Sema/CSSimplify.cpp]: I tried this - can you take a look and see if its what you meant?

File: lib/Sema/CSSimplify.cpp [hunk 5]
```diff
@@ -3626,33 +3626,36 @@ ConstraintSystem::matchExistentialTypes(Type type1, Type type2,
...
+              if (result == SolutionKind::Solved) {
+                auto matchTypeResult =
+                    matchTypes(unwrappedType, type2, ConstraintKind::Conversion,
+                               subflags, locator);
+                if (matchTypeResult.isSuccess()) {
+                  // Impact here is a 1 because there is only one failure before
+                  // we need to force type1 to be
+                  auto fix = ForceOptional::create(
+                      *this, type1, proto, getConstraintLocator(locator));
+                  if (recordFix(fix, /*impact=*/1))
```
Comment (LucianoPAlmeida) [inline lib/Sema/CSSimplify.cpp:3650]: Nit: One is already the default for `recordFix` so we don't need to pass it. Also we probably don't need the comment above as well.

File: lib/Sema/CSSimplify.cpp [hunk 6]
```diff
@@ -3626,33 +3626,36 @@ ConstraintSystem::matchExistentialTypes(Type type1, Type type2,
...
-                impact = 1;
-                fix = ForceOptional::create(*this, type1, proto,
-                                            getConstraintLocator(locator));
+              auto result = simplifyConformsToConstraint(
+                  unwrappedType, type2, ConstraintKind::ConformsTo,
+                  getConstraintLocator(locator),
+                  TypeMatchFlags::TMF_ApplyingFix);
+              if (result == SolutionKind::Solved) {
+                auto matchTypeResult =
+                    matchTypes(unwrappedType, type2, ConstraintKind::Conversion,
```
Comment (LucianoPAlmeida) [inline lib/Sema/CSSimplify.cpp:3643]: I guess we don't need the `matchTypes` since we are checking through `simplifyConformsToConstraint`

File: lib/Sema/CSSimplify.cpp (hunk 4 above)
Comment (dfperry5) [reply lib/Sema/CSSimplify.cpp]: With this approach - I am seeing both errors returned --> 

/Users/dylanperry/dev/ios/open-source/Swift/Test Files/Test.swift:8:10: error: argument type 'any P' does not conform to expected type 'P'
  takesP(value) // error: Argument type '(any P)?' does not conform to expected type 'P'
         ^
               as P
/Users/dylanperry/dev/ios/open-source/Swift/Test Files/Test.swift:8:10: error: value of optional type '(any P)?' must be unwrapped to a value of type 'any P'
  takesP(value) // error: Argument type '(any P)?' does not conform to expected type 'P'
         ^
/Users/dylanperry/dev/ios/open-source/Swift/Test Files/Test.swift:8:10: note: coalesce using '??' to provide a default when the optional value contains 'nil'
  takesP(value) // error: Argument type '(any P)?' does not conform to expected type 'P'
         ^
               ?? <#default value#>
/Users/dylanperry/dev/ios/open-source/Swift/Test Files/Test.swift:8:10: note: force-unwrap using '!' to abort execution if the optional value contains 'nil'
  takesP(value) // error: Argument type '(any P)?' does not conform to expected type 'P'
         ^
              !

File: lib/Sema/CSSimplify.cpp [hunk 7]
```diff
@@ -3626,18 +3626,37 @@ ConstraintSystem::matchExistentialTypes(Type type1, Type type2,
...
             //
             // This would make sure that arguments with incorrect
             // conformances are not prioritized over general argument
             // mismatches.
+            if (type1->isOptional()) {
+              auto unwrappedType = type1->lookThroughAllOptionalTypes();
+              auto result = simplifyConformsToConstraint(
+                  unwrappedType, type2, ConstraintKind::ConformsTo,
+                  getConstraintLocator(locator),
+                  TypeMatchFlags::TMF_ApplyingFix);
```
Comment (LucianoPAlmeida) [inline lib/Sema/CSSimplify.cpp:3640]: I believe the reason you are seeing the extra diagnostic is this is not the correct way to call `simplifyConformsToConstraint`. You can try it like this:
```suggestion
              auto result = simplifyConformsToConstraint(unwrappedType, protoDecl, kind, locator,
                                                         subflags | TMF_ApplyingFix);
```

File: lib/Sema/CSSimplify.cpp (hunk 4 above)
Comment (LucianoPAlmeida) [reply lib/Sema/CSSimplify.cpp]: Added a comment about that bellow. This is cause the way we are calling `simplifyConformsToConstraint` we should pass the type and protocol declaration. See the bellow comment =]

File: lib/Sema/CSSimplify.cpp (hunk 3 above)
Comment (LucianoPAlmeida) [reply lib/Sema/CSSimplify.cpp]: I think Pavel meant something like 
```cpp
auto proto = protoDecl->getDeclaredInterfaceType();
if (type1->isOptional()) {
  auto unwrappedType = type1->lookThroughAllOptionalTypes();
  auto result = simplifyConformsToConstraint(
      unwrappedType, protoDecl, kind, locator,
      subflags | TMF_ApplyingFix);
  if (result == SolutionKind::Solved) {
    auto fix = ForceOptional::create(*this, type1, proto,
                                     getConstraintLocator(locator));
    if (recordFix(fix))
      return getTypeMatchFailure(locator);
    break;
  }
}
auto fix = AllowArgumentMismatch::create(
    *this, type1, proto, getConstraintLocator(anchor, path));
// Impact is 2 here because there are two failures
// 1 - missing conformance and 2 - incorrect argument type.
//
// This would make sure that arguments with incorrect
// conformances are not prioritized over general argument
// mismatches.
if (recordFix(fix, /*impact=*/2))
  return getTypeMatchFailure(locator);

break;
```

File: lib/Sema/CSSimplify.cpp (hunk 6 above)
Comment (xedin) [reply lib/Sema/CSSimplify.cpp:3643]: Yes, we don't, if the check was successful then the type1 is resolved enough.

File: lib/Sema/CSSimplify.cpp (hunk 7 above)
Comment (xedin) [reply lib/Sema/CSSimplify.cpp:3640]: Yes, that is correct.

File: lib/Sema/CSSimplify.cpp (hunk 5 above)
Comment (xedin) [reply lib/Sema/CSSimplify.cpp:3650]: Besides that result could be three different things - solved, failed, unsolved. It's possible that the type here would be `$T?` where `$T` is a type variable, so we actually need to check that and delay a decision until optional is fully resolved.

Comment (LucianoPAlmeida) [reply lib/Sema/CSSimplify.cpp:3650]: @xedin Is that possible in this code path? I mean, this is at the error path for the first call to [`simplifyConformsToConstraint`](https://github.com/apple/swift/blob/a1fe5001f09256a2241a4f0f324388ca5014b576/lib/Sema/CSSimplify.cpp#L3602) so if existential is not resolved yet, it would never reach diagnostic logic anyways(first call would return unsolved). So I think we don't need to check that here because that would never be the case.

Comment (xedin) [reply lib/Sema/CSSimplify.cpp:3650]: I was thinking about the case involving primary associated types where the conformance is conditional on such a type that is not yet resolved...

Comment (LucianoPAlmeida) [reply lib/Sema/CSSimplify.cpp:3650]: Ah I see, but still not sure how we are going to end up at this code path with unresolved variables. Do you have an example?

File: lib/Sema/CSSimplify.cpp (hunk 6 above)
Comment (xedin) [reply lib/Sema/CSSimplify.cpp:3643]: I don't, we can just make it an assert for now I guess.

File: lib/Sema/CSSimplify.cpp (hunk 7 above)
Comment (dfperry5) [reply lib/Sema/CSSimplify.cpp]: Thank you!
 I think I addressed this!

File: lib/Sema/CSSimplify.cpp (hunk 4 above)
Comment (dfperry5) [reply lib/Sema/CSSimplify.cpp]: @LucianoPAlmeida  Thank you! I am still learning -- appreciate the patience :)

File: lib/Sema/CSSimplify.cpp [hunk 8]
```diff
@@ -3626,18 +3626,29 @@ ConstraintSystem::matchExistentialTypes(Type type1, Type type2,
...
-
             // Impact is 2 here because there are two failures
             // 1 - missing conformance and 2 - incorrect argument type.
             //
             // This would make sure that arguments with incorrect
             // conformances are not prioritized over general argument
             // mismatches.
+            if (type1->isOptional()) {
+              auto unwrappedType = type1->lookThroughAllOptionalTypes();
+              auto result = simplifyConformsToConstraint(
```
Comment (xedin) [inline lib/Sema/CSSimplify.cpp:3637]: This looks good to me! All we need is a test in test/Constraints/optional.swift

Comment (dfperry5) [reply lib/Sema/CSSimplify.cpp:3637]: I will get on that this afternoon / this weekend!

Comment (dfperry5) [reply lib/Sema/CSSimplify.cpp:3638]: @xedin  - just pushed test up.

File: test/Constraints/optional.swift [hunk 9]
```diff
@@ -565,3 +565,18 @@ func testFunctionContainerMethodCall(container: FunctionContainer?) {
   // expected-note@-3 {{coalesce}}
   // expected-note@-4 {{force-unwrap}}
 }
+
+// Test for Issue: 60730 (https://github.com/apple/swift/issues/60730)
+// Rdar: rdar://94037733
+func issue60730Test() {
```
Comment (xedin) [inline test/Constraints/optional.swift:571]: A couple of suggestions here:
1. Let's adjust the comment so that it just mentions links, they are self-evident.
2. Don't have to add a function, `do { }` could be used instead to outline the scope.

File: test/Constraints/optional.swift [hunk 10]
```diff
@@ -565,3 +565,18 @@ func testFunctionContainerMethodCall(container: FunctionContainer?) {
...
+  struct S: P {}
+  func takesP(_: any P) {}
+  func passOptional(value: (any P)?) {
+    takesP(value)
+    // Add full error message
+    // Don't include the error message yet - run it and see the test fail first, and go from there.
```
Comment (xedin) [inline test/Constraints/optional.swift:577]: Is this outdated?

Comment (dfperry5) [reply test/Constraints/optional.swift]: Sorry! So embarrassing leaving the comments in there! Late night PR's :/

File: test/Constraints/optional.swift (hunk 9 above)
Comment (dfperry5) [reply test/Constraints/optional.swift]: Done

File: test/Constraints/optional.swift (hunk 10 above)
Comment (xedin) [reply test/Constraints/optional.swift]: No need to apologize, just making sure it's ready for review is all.

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

File: test/Constraints/optional.swift [hunk 11]
```diff
@@ -565,3 +565,16 @@ func testFunctionContainerMethodCall(container: FunctionContainer?) {
...
+
+// Test for https://github.com/apple/swift/issues/60730
+// rdar://94037733
+do {
+  struct S: P {}
+  func takesP(_: any P) {}
+  func passOptional(value: (any P)?) {
+    takesP(value)
+    // expected-error@-1 {{value of optional type '(any P)?' must be unwrapped to a value of type 'any P'}}
+    // expected-note@-3 {{coalesce using '??' to provide a default when the optional value contains 'nil'}}
```
Comment (xedin) [inline test/Constraints/optional.swift:577]: @dfperry5 This has to be `-2` and the next one `-3` :)

**Comment by xedin** [comment]
@swift-ci please test

File: test/Constraints/optional.swift [hunk 12]
```diff
@@ -565,3 +565,16 @@ func testFunctionContainerMethodCall(container: FunctionContainer?) {
...
+// rdar://94037733
+do {
+  struct S: P {}
+  func takesP(_: any P) {}
+  func passOptional(value: (any P)?) {
+    takesP(value)
+    // expected-error@-1 {{value of optional type '(any P)?' must be unwrapped to a value of type 'any P'}}
+    // expected-note@-2 {{coalesce using '??' to provide a default when the optional value contains 'nil'}}
+    // expected-note@-3 {{force-unwrap using '!' to abort execution if the optional value contains 'nil'}}
+  }
```
Comment (xedin) [inline test/Constraints/optional.swift:579]: @dfperry5 Could you please add one more test-case that tests the opposite scenario where argument does not conform to `P` to make sure that we don't suggest the unwrap? it could be i.e. `(any BinaryInteger)?`) or any stdlib protocol so you don't have to declare anything new.

Comment (LucianoPAlmeida) [reply test/Constraints/optional.swift:579]: @xedin since we are here, I also think would make sense a test case with more than one layer of optional like `(any P)??`

Comment (dfperry5) [reply test/Constraints/optional.swift:579]: @xedin  / @LucianoPAlmeida  -- added these tests.

One thing - wondering if I made a mistake somewhere, for the optional layers, the error message is: 

" error: value of optional type '(any P)??' must be unwrapped to a value of type '(any P)?' "

Is that right? I was wondering if it should be:

" error: value of optional type '(any P)??' must be unwrapped to a value of type 'any P' "

File: test/Constraints/optional.swift [hunk 13]
```diff
@@ -565,3 +565,26 @@ func testFunctionContainerMethodCall(container: FunctionContainer?) {
...
+  func passLayersOfOptional(value: (any P)??) {
+    takesP(value)
+    // expected-error@-1 {{value of optional type '(any P)??' must be unwrapped to a value of type '(any P)?}}
```
Comment (xedin) [inline test/Constraints/optional.swift:582]: Hm, this is not great... Could you please leave a `FIXME(diagnostics):` here to to record multiple ForceUnwrap fixes based on number of optionals we need to unwrap?

Comment (dfperry5) [reply test/Constraints/optional.swift:582]: Where do I add the "FIXME"? As a comment above the takesP() call?

Comment (xedin) [reply test/Constraints/optional.swift:582]: Yes, that's good enough.

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

**Comment by dfperry5** [comment]
@LucianoPAlmeida  / @xedin  - not sure if this is a dumb question but when I look at the failure above for MacOS --> (https://ci.swift.org/job/swift-PR-macos-smoke-test/3584/consoleFull#-1537259845d6fdb6cb-f376-4f2e-8bce-d31c7304698b) -- the only error I'm seeing is: 

UNSUPPORTED: lldb-api :: lang/swift/backwards_compatibility/simple/TestSwiftBackwardsCompatibilitySimple.py (368 of 369)
TIMEOUT: lldb-api :: lang/swift/late_dylib/TestSwiftLateDylib.py (369 of 369)
******************** TEST 'lldb-api :: lang/swift/late_dylib/TestSwiftLateDylib.py' FAILED ********************

and

Exit Code: -9
Timeout: Reached timeout of 600 seconds


Any idea on how I can fix that? Looked at it a little today and feeling stumped!

**Comment by xedin** [comment]
It’s just a flaky test.

**Comment by xedin** [comment]
@swift-ci please test macOS platform

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test macOS platform

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test macOS platform

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test macOS platform

**Comment by LucianoPAlmeida** [comment]
Looks like I'm not able to kick it again ... not sure why 😆

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test macOS platform

**Comment by xedin** [comment]
Let’s give it time :)
