### PR TITLE
[cxx-interop] Prohibit weak references to foreign reference types

### LINKED ISSUE #83080: Assigning a non-nil value to a weak SWIFT_SHARED_REFERENCE variable crashes at runtime
### Description

_No response_

### Reproduction

```c++
struct SharedRef {
    static inline SharedRef*_Nonnull makeSharedRef() SWIFT_RETURNS_RETAINED {
        return new SharedRef();
    }
    
private:
    SharedRef() : _refCount(1) {}
    
    SharedRef(const SharedRef& other) = delete;
    SharedRef& operator=(const SharedRef& other) = delete;
    friend inline void retainSharedRef(SharedRef*_Nonnull x) {
        x->_refCount += 1;
    }
    friend inline void releaseSharedRef(SharedRef*_Nonnull x) {
        x->_refCount -= 1;
        if (x->_refCount == 0) {
            delete x;
        }
    }
    
    int _refCount;
} SWIFT_SHARED_REFERENCE(retainSharedRef, releaseSharedRef);
```
```swift
func foo() {
    weak var x: SharedRef?
    
    let y: SharedRef = SharedRef.makeSharedRef()
    x = y // runtime crash!
}

foo()
```

### Stack dump

```text
(lldb) bt
* thread #1, stop reason = EXC_BAD_ACCESS (code=1, address=0x20)
    frame #0: 0x00000001921143c8 libswiftCore.dylib`swift::WeakReference::unknownAssign(void*) + 72
    frame #1: 0x0000000192114370 libswiftCore.dylib`swift_unknownObjectWeakAssign + 24
  * frame #2: 0x0000000100000ca4 WeakFRTCrash`foo() at main.swift:16:7
    frame #3: 0x0000000100000bbc WeakFRTCrash`main at main.swift:19:1
    frame #4: 0x0000000180532b4c dyld`start + 6000
```

### Expected behavior

I expected the runtime crash would not occur. (Using `weak` or `unowned` with `SWIFT_SHARED_REFERENCE` should probably be a compiler error, since I don't think there's a way for the Swift runtime to weakly hold C++ reference types, so this code should probably not compile at all.)

### Environment

swift-driver version: 1.120.5 Apple Swift version 6.1 (swiftlang-6.1.0.110.21 clang-1700.0.13.3)
Target: arm64-apple-macosx15.0

### Additional information

rdar://124040825

### PR DESCRIPTION
**Pull request by egorzhdan**
This fixes a runtime crash when a `weak` reference to a C++ foreign reference type is used.

Instead of a runtime crash, Swift would now emit a compiler error saying that `weak` keyword is incompatible with foreign reference types.

rdar://124040825 / resolves https://github.com/swiftlang/swift/issues/83080

### CODE REVIEW

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

File: test/Interop/Cxx/foreign-reference/weak-reference-typechecker.swift [hunk 1]
```diff
@@ -0,0 +1,11 @@
+// RUN: %target-typecheck-verify-swift -cxx-interoperability-mode=default -I %S/Inputs -disable-availability-checking
+
+import POD
+
+struct HasWeakReference {
+  weak var x: Empty? // expected-error {{'Empty' is incompatible with 'weak' references}}
```
Comment (j-hui) [inline test/Interop/Cxx/foreign-reference/weak-reference-typechecker.swift]: Nit: I think this error message could be a little clearer about it being incompatible because _FRTs_ cannot be `weak`. But that can also be punted to a follow-up patch.

**Review by j-hui — APPROVED** [review]

File: include/swift/AST/Decl.h [hunk 2]
```diff
@@ -721,9 +721,9 @@ class alignas(1 << DeclAlignInBits) Decl : public ASTAllocated<Decl>, public Swi
     HasMissingVTableEntries : 1,
     ComputedHasMissingVTableEntries : 1,
 
-    /// Whether instances of this class are incompatible
-    /// with weak and unowned references.
+    /// Whether instances of this class are incompatible with weak references.
     IsIncompatibleWithWeakReferences : 1,
+    IsIncompatibleWithUnownedReferences : 1,
```
Comment (Xazax-hun) [inline include/swift/AST/Decl.h]: Why do we need a new bit? Is `ClassDecl::isForeignReferenceType()` insufficient to tell if something is compatible or not?

Comment (egorzhdan) [reply include/swift/AST/Decl.h]: Great point! Let's use `isForeignReferenceType` instead.

File: test/Interop/Cxx/foreign-reference/weak-reference-typechecker.swift (hunk 1 above)
Comment (egorzhdan) [reply test/Interop/Cxx/foreign-reference/weak-reference-typechecker.swift]: Makes sense, changed the diagnostic.

**Comment by egorzhdan** [comment]
@swift-ci please smoke test

**Review by hnrklssn — APPROVED** [review]

**Review by Xazax-hun — APPROVED** [review]
LG, thanks!
