### PR TITLE
[AST] Move generic parameter logic for accessor decl from parser to GenericParamListRequest

### LINKED ISSUE #61387: compiler crash: Functions in generic context must have an interface type
reproduced on `DEVELOPMENT-SNAPSHOT-2022-09-27-a`:

```swift 
struct S 
{
    static 
    func x(_ s:some StringProtocol) -> String 
    {
        .init(s)
    }
    static
    subscript(s:some StringProtocol) -> String 
    {
        Self.x(s)
    }
}
```

```
$ swiftc test8.swift 
error: compile command failed due to signal 6 (use -v to see invocation)
Functions in generic context must have an interface type
(accessor_decl range=[test8.swift:10:5 - line:12:5] 'anonname=0xbef4aa0' interface type=' (S.Type) -> (some StringProtocol) -> String' access=internal captures=(<generic> ) type get_for=subscript(_:)
  (parameter "self")
  (parameter_list range=[test8.swift:9:14 - line:9:36]
    (parameter "s" type='some StringProtocol' interface type='some StringProtocol'))
  (call_expr type='String' location=test8.swift:11:14 range=[test8.swift:11:9 - line:11:17] nothrow
    (dot_syntax_call_expr type='(some StringProtocol) -> String' location=test8.swift:11:14 range=[test8.swift:11:9 - line:11:14] nothrow
      (declref_expr type='(S.Type) -> (some StringProtocol) -> String' location=test8.swift:11:14 range=[test8.swift:11:14 - line:11:14] decl=test8.(file).S.x@test8.swift:4:10 [with (substitution_map generic_signature= (substitution some StringProtocol -> some StringProtocol))] function_ref=single)
      (argument_list implicit
        (argument
          (type_expr type='S.Type' location=test8.swift:11:9 range=[test8.swift:11:9 - line:11:9] typerepr='S'))))
    (argument_list
      (argument
        (declref_expr type='some StringProtocol' location=test8.swift:11:16 range=[test8.swift:11:16 - line:11:16] decl=test8.(file).S.<anonymous>.s@test8.swift:9:15 function_ref=unapplied)))))
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
Stack dump:
0.      Program arguments: /home/ec2-user/.swiftenv/versions/DEVELOPMENT-SNAPSHOT-2022-09-27-a/usr/bin/swift-frontend -frontend -c -primary-file test8.swift -target x86_64-unknown-linux-gnu -disable-objc-interop -color-diagnostics -new-driver-path /home/ec2-user/.swiftenv/versions/DEVELOPMENT-SNAPSHOT-2022-09-27-a/usr/bin/swift-driver -empty-abi-descriptor -resource-dir /home/ec2-user/.swiftenv/versions/DEVELOPMENT-SNAPSHOT-2022-09-27-a/usr/lib/swift -module-name test8 -o /tmp/TemporaryDirectory.nrsWjH/test8-1.o
1.      Swift version 5.8-dev (LLVM ed4d811c2897d77, Swift 8491f52d478aca6)
2.      Compiling with the current language version
3.      While walking into decl 'S' (at test8.swift:1:1)
4.      While walking into 'S' (at test8.swift:1:1)
5.      While verifying AccessorDecl getter for subscript(_:) (at test8.swift:9:5)
6.      While verifying FuncDecl getter for subscript(_:) (at test8.swift:9:5)
7.      While verifying AbstractFunctionDecl getter for subscript(_:) (at test8.swift:9:5)
```

does not crash if the subscript is desugared to the `where`-based syntax.

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
`AbstractFunctionDecl::isGenericContext` being based on `getGenericParams()` which is `nullptr` in this case for `AccessorDecl` because `createOpaqueParameterGenericParams` was not be able to create the implicit generic param list correctly because it was looking to itself but in fact it should look through subscript(storage) signature instead. 

This refectors generic parameters logic for accessor declaration to be a copy of the storage at `GenericParamListRequest ` instead of parse time. See Slava's comment bellow.

Resolves #61387

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

File: lib/AST/NameLookup.cpp [hunk 1]
```diff
@@ -2845,6 +2845,11 @@ createOpaqueParameterGenericParams(GenericContext *genericContext, GenericParamL
   if (!value)
     return { };
 
+  // Consider storage signature opaque parameters for accessor declaration.
```
Comment (slavapestov) [inline lib/AST/NameLookup.cpp:2848]: I wonder if we can refactor things a bit and move the logic into GenericParamListRequest::evaluate().

Take a look at how the parser handles parsed generic parameter lists of subscripts today: they're cloned at parse time when the AccessorDecl is constructed, in createAccessorFunc() in ParseDecl.cpp:

```
  auto *D = AccessorDecl::create(P->Context,
                                 /*FIXME FuncLoc=*/DeclLoc,
                                 AccessorKeywordLoc,
                                 Kind, storage,
                                 StaticLoc, StaticSpellingKind::None,
                                 asyncLoc.isValid(), asyncLoc,
                                 throwsLoc.isValid(), throwsLoc,
                                 (GenericParams
                                  ? GenericParams->clone(P->CurDeclContext)
                                  : nullptr),
                                 ValueArg, Type(),
                                 P->CurDeclContext);
```

Instead, we could probably do this in GenericParamListRequest::evaluate(), and clone subscriptDecl->getGenericParamList() there instead. This would simplify some of the parser logic that threads the GenericParamList through parseGetSet().

Moving semantic analysis like that out of the parser will help simplify the ASTGen pass that we'll use once we migrate to the new swift-syntax parser.

Comment (LucianoPAlmeida) [reply lib/AST/NameLookup.cpp:2848]: It makes total sense @slavapestov! I'll give that a try

Comment (LucianoPAlmeida) [reply lib/AST/NameLookup.cpp:2848]: Actually should this be in this PR, or could be a follow-up?

Comment (slavapestov) [reply lib/AST/NameLookup.cpp:2848]: If you don't mind, I think in this PR is best since it will involve undoing the above change anyway.

Comment (LucianoPAlmeida) [reply lib/AST/NameLookup.cpp:2848]: No problem :)

Comment (AnthonyLatsis) [reply lib/AST/NameLookup.cpp:2848]: Agree with Slava here, an accessor should not have a parsed generic parameter list.

**Comment by LucianoPAlmeida** [comment]
@slavapestov I think changes are ready for a re-review. Let me know if this aligns with what you were thinking

**Review by slavapestov — APPROVED** [review]
Excellent!
