### PR TITLE
SuspendingClock on Windows does not suspend

### LINKED ISSUE #63224: SuspendingClock on Windows does not suspend
**Description**
On Windows, the implementation of `SuspendingClock` is the same as the implementation of `ContinuousClock`. Both use `QueryPerformanceCounter()` which tracks time while sleeping—that is, it is continuous, not suspending.

**Steps to reproduce**
On Windows, create a `SuspendingClock` instance and get the current instant. Sleep the computer for a long time. Wake it and get the current instant again. Note that the long sleep is accounted for.

**Expected behavior**
The suspending clock should not account for the time spent sleeping.

**Environment**
- Swift compiler version info 
- Xcode version info 
- Deployment target:

### PR DESCRIPTION
**Pull request by grynspan**
This PR replaces the implementation of `SuspendingClock` on Windows with one that uses `QueryUnbiasedInterruptTimePrecise()`, which _does_ suspend.

I also updated `swift_get_clock_res()` to produce accurate values on Windows instead of a hard-coded 1µs resolution.

Raymond Chen gives a little bit of info about the various timer APIs [here](https://devblogs.microsoft.com/oldnewthing/20170921-00/?p=97057).

Resolves #63224.

### CODE REVIEW

**Comment by grynspan** [comment]
@swift-ci please test

**Review by compnerd — APPROVED** [review]
Thanks for fixing this!  I think that the commit message could be better (the issue helped me understand the change).

File: stdlib/public/Concurrency/Clock.cpp [hunk 1]
```diff
@@ -132,8 +124,10 @@ switch (clock_id) {
       *seconds = continuous.tv_sec;
       *nanoseconds = continuous.tv_nsec;
 #elif defined(_WIN32)
+      LARGE_INTEGER freq;
+      QueryPerformanceFrequency(&freq);
       *seconds = 0;
-      *nanoseconds = 1000;
+      *nanoseconds = 1000000000 / freq.QuadPart;
```
Comment (grynspan) [inline stdlib/public/Concurrency/Clock.cpp:130]: `QueryPerformanceFrequency()` never reports zero post-Windows XP. If we're concerned about that, we can check.

File: stdlib/public/Concurrency/Clock.cpp [hunk 2]
```diff
@@ -159,7 +153,7 @@ switch (clock_id) {
       *nanoseconds = suspending.tv_nsec;
 #elif defined(_WIN32)
       *seconds = 0;
-      *nanoseconds = 1000;
+      *nanoseconds = 100;
```
Comment (grynspan) [inline stdlib/public/Concurrency/Clock.cpp:156]: `QueryUnbiasedInterruptTimePrecise()` has a unit of 100ns, so its highest possible resolution is 100ns. Neat.

**Comment by grynspan** [comment]
@swift-ci please test

**Comment by grynspan** [comment]
@swift-ci please test

File: stdlib/public/Concurrency/Clock.cpp [hunk 3]
```diff
@@ -52,14 +54,14 @@ void swift_get_time(
...
-      } else {
-        *nanoseconds = 
-            (count.QuadPart % freq.QuadPart) * (1000000000.0 / freq.QuadPart);
-      }
+      // Divide count (number of ticks) by frequency (number of ticks per
+      // second) to get the counter in seconds. We also need to multiply the
+      // count by 1,000,000,000 to get nanosecond resolution. By multiplying
+      // first, we maintain high precision. The resulting value is the tick
+      // count in nanoseconds.
+      long long ns = (count.QuadPart * 1000000000) / freq.QuadPart;
```
Comment (al45tair) [inline stdlib/public/Concurrency/Clock.cpp:62]: Couldn't `count.QuadPart * 1000000000` overflow? I think the previous code might have been the way it was in order to avoid that problem?

File: stdlib/public/Concurrency/Clock.cpp [hunk 4]
```diff
@@ -87,18 +89,33 @@ void swift_get_time(
...
-      LARGE_INTEGER count;
-      QueryPerformanceCounter(&count);
-      *seconds = count.QuadPart / freq.QuadPart;
-      if (freq.QuadPart < 1000000000) {
-        *nanoseconds = 
-            ((count.QuadPart % freq.QuadPart) * 1000000000) / freq.QuadPart;
+      // QueryUnbiasedInterruptTimePrecise() was added in Windows 10 and is, as
+      // the name suggests, more precise than QueryUnbiasedInterruptTime().
+      // However, despite being declared in Windows' headers, we must look it up
+      // dynamically at runtime.
```
Comment (al45tair) [inline stdlib/public/Concurrency/Clock.cpp:95]: I assume this is because we don't have Windows 10 as a minimum target? (That is, `_WIN32_WINNT` would need to be defined to something else?)

Perhaps the comment should say _why_ it needs to be dynamically looked-up.

**Review by al45tair — COMMENTED** [review]
Not sure about the change to the division; could you check that, please.

File: stdlib/public/Concurrency/Clock.cpp (hunk 4 above)
Comment (grynspan) [reply stdlib/public/Concurrency/Clock.cpp:95]: Exactly. I'll edit the comment to make the connection to Windows 10 clearer.

File: stdlib/public/Concurrency/Clock.cpp (hunk 3 above)
Comment (grynspan) [reply stdlib/public/Concurrency/Clock.cpp:62]: `count.QuadPart` is a 64-bit value and the frequency is CPU-bound (clock can't go brrr if CPU doesn't go brrr.) The counter is a 64-bit value and, unless my math is way off, would only overflow if the system had years of uptime.

However, that's a bit handwavey—we could approach this problem in a couple of different ways:

1. Instead of using `QueryPerformanceCounter()`, use `QueryInterruptTimePrecise()` and get a value in units of 100ns, which will overflow after about 58,455 years, but which is slower to call than `QueryPerformanceCounter()`.
2. Use 128-bit multiplication and division to get the nanosecond count. Windows has various bits of 128-bit math API we could use here. I don't know what sort of performance overhead this API has, but it's arithmetic so I'd hope not _too_ bad.

File: stdlib/public/Concurrency/Clock.cpp (hunk 4 above)
Comment (grynspan) [reply stdlib/public/Concurrency/Clock.cpp:95]: I tried at desk, and from what I can see, even on Windows 10 this symbol is not exported normally. I don't need to change `_WIN32_WINNT`, the symbol is _declared_, but it's not available at link time. It is available when dynamically looking it up using `GetProcAddress()`, and it's fully documented on MSDN. I'll note the issue in the comment.

Comment (al45tair) [reply stdlib/public/Concurrency/Clock.cpp:95]: If it's not available at link time, it might just be that we don't link against the relevant `.lib` file?

Comment (grynspan) [reply stdlib/public/Concurrency/Clock.cpp:95]: Ah, I'm not crazy! swift-corelibs-dispatch has the same problem. See [this](https://github.com/apple/swift-corelibs-libdispatch/pull/498) PR from that repo.

File: stdlib/public/Concurrency/Clock.cpp (hunk 3 above)
Comment (grynspan) [reply stdlib/public/Concurrency/Clock.cpp]: I used 128-bit math.

**Comment by grynspan** [comment]
@swift-ci please test

File: stdlib/public/Concurrency/Clock.cpp [hunk 5]
```diff
@@ -52,14 +56,16 @@ void swift_get_time(
...
-            (count.QuadPart % freq.QuadPart) * (1000000000.0 / freq.QuadPart);
-      }
+      // Divide count (number of ticks) by frequency (number of ticks per
+      // second) to get the counter in seconds. We also need to multiply the
+      // count by 1,000,000,000 to get nanosecond resolution. By multiplying
+      // first, we maintain high precision. The resulting value is the tick
+      // count in nanoseconds. Use 128-bit math to avoid overflowing.
+      DWORD64 hi = 0;
+      DWORD64 lo = _umul128(count.QuadPart, 1'000'000'000, &hi);
+      DWORD64 ns = _udiv128(hi, lo, freq.QuadPart, nullptr);
```
Comment (grynspan) [inline stdlib/public/Concurrency/Clock.cpp:66]: `_udiv128()` generates a GPF if the result can't fit in a 64-bit integer, but if that happens that means the computer's been up for more than 2^64 nanoseconds… that's 584 years. If anybody runs into that problem, please let my great-great-great-great-great-great-great-great-great-great-great-great-great-great-great-great-great-great-great-great-great-great-great-great-great-great-grandkid know.

**Comment by grynspan** [comment]
@swift-ci please test windows

**Comment by grynspan** [comment]
@swift-ci please test windows

**Comment by grynspan** [comment]
@swift-ci please test

**Comment by grynspan** [comment]
@swift-ci please test

**Comment by grynspan** [comment]
@swift-ci please test linux

File: stdlib/public/Concurrency/Clock.cpp [hunk 6]
```diff
@@ -52,14 +56,15 @@ void swift_get_time(
...
-      }
+      // Divide count (number of ticks) by frequency (number of ticks per
+      // second) to get the counter in seconds. We also need to multiply the
+      // count by 1,000,000,000 to get nanosecond resolution. By multiplying
+      // first, we maintain high precision. The resulting value is the tick
+      // count in nanoseconds. Use 128-bit math to avoid overflowing.
+      auto quadPart = static_cast<unsigned __int128>(count.QuadPart);
+      auto ns = (quadPart * 1'000'000'000) / freq.QuadPart;
+      *seconds = ns / 1'000'000'000;
+      *nanoseconds = ns % 1'000'000'000;
```
Comment (al45tair) [inline stdlib/public/Concurrency/Clock.cpp:67]: Nice :-)

**Review by al45tair — APPROVED** [review]
LGTM

File: stdlib/public/Concurrency/Clock.cpp (hunk 6 above)
Comment (grynspan) [reply stdlib/public/Concurrency/Clock.cpp:67]: Yeah, the "which compiler builds this file?" part tripped me up!

File: stdlib/public/Concurrency/Clock.cpp [hunk 7]
```diff
@@ -132,8 +154,10 @@ switch (clock_id) {
       *seconds = continuous.tv_sec;
       *nanoseconds = continuous.tv_nsec;
 #elif defined(_WIN32)
+      LARGE_INTEGER freq;
+      QueryPerformanceFrequency(&freq);
       *seconds = 0;
-      *nanoseconds = 1000;
+      *nanoseconds = 1'000'000'000 / freq.QuadPart;
```
[the remark this answers is not in the document]
Comment (grynspan) [reply stdlib/public/Concurrency/Clock.cpp:160]: That would imply the tick duration was less than one nanosecond. It's conceivable that future hardware could support that, but the finest resolution `swift_get_clock_res()` can represent is one nanosecond, so we'd need to refactor this entire function anyway, presumably to support returning attoseconds.)

**Comment by grynspan** [comment]
@swift-ci please test

**Review by phausler — APPROVED** [review]
This looks great to me, the cleanup for non-windows platforms looks correct (and definitely cleaner). 

Thanks for taking this on!

**Comment by grynspan** [comment]
> This looks great to me, the cleanup for non-windows platforms looks correct (and definitely cleaner).
> 
> Thanks for taking this on!

Always happy to help! (**Danger:** I might noodle on this code a bit more in the future if I see ways to improve it further.)

**Comment by grynspan** [comment]
@swift-ci please test

**Comment by grynspan** [comment]
@swift-ci please test windows

**Comment by grynspan** [comment]
@swift-ci please test windows

**Comment by grynspan** [comment]
The reported Windows failure is not related to this PR.

**Comment by grynspan** [comment]
@swift-ci please test windows
