### PR TITLE
Fix some major SILGen bugs with pack handling:

### LINKED ISSUE #80995: Regression from Swift 6.0 -> 6.1 regarding protocols and variadic generics
### Description

Code that does not crash in 6.0 crashes in 6.1 swift-6.1-DEVELOPMENT-SNAPSHOT-2025-03-25-a

### Reproduction

In 6.0, the following code compiles fine. In 6.1, it crashes due to an assertion. Commenting out the `encode` method makes it not crash and correctly fail to compile due to missing protocol requirement.

```swift
public protocol Schema<Value>: Sendable {

  associatedtype Value

  func encode(_ value: Value, to encoder: Encoder<Self>) throws

}

public struct Encoder<Schema> {
}

private struct TupleSchema<each ElementSchema: Schema>: Schema {

  typealias Value = (repeat (each ElementSchema).Value)

  func encode(_ value: Value, to encoder: Encoder<Self>) throws {

  }

}

```

### Stack dump

```text
> /usr/bin/swift build --build-tests -Xswiftc -diagnostic-style=llvm

[1/1] Planning build
Building for debugging...
error: emit-module command failed due to signal 6 (use -v to see invocation)
error: compile command failed due to signal 6 (use -v to see invocation)
swift-frontend: /home/build-user/swift/lib/SILGen/ManagedValue.h:319: SILValue swift::Lowering::ManagedValue::getLValueAddress() const: Assertion `isLValue() && "This isn't an lvalue"' failed.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.      Program arguments: /usr/bin/swift-frontend -frontend -emit-module -experimental-skip-non-inlinable-function-bodies-without-types /workspaces/SadTuple/Sources/SadTuple/SadTuple.swift -target aarch64-unknown-linux-gnu -Xllvm -aarch64-use-tbi -disable-objc-interop -I /workspaces/SadTuple/.build/aarch64-unknown-linux-gnu/debug/Modules -color-diagnostics -enable-testing -g -debug-info-format=dwarf -dwarf-version=4 -module-cache-path /workspaces/SadTuple/.build/aarch64-unknown-linux-gnu/debug/ModuleCache -swift-version 6 -Onone -diagnostic-style=llvm -D SWIFT_PACKAGE -D DEBUG -empty-abi-descriptor -resource-dir /usr/lib/swift -enable-anonymous-context-mangled-names -file-compilation-dir /workspaces/SadTuple -Xcc -fPIC -Xcc -g -Xcc -fno-omit-frame-pointer -module-name SadTuple -package-name sadtuple -in-process-plugin-server-path /usr/lib/swift/host/libSwiftInProcPluginServer.so -plugin-path /usr/lib/swift/host/plugins -plugin-path /usr/local/lib/swift/host/plugins -emit-module-doc-path /workspaces/SadTuple/.build/aarch64-unknown-linux-gnu/debug/Modules/SadTuple.swiftdoc -emit-module-source-info-path /workspaces/SadTuple/.build/aarch64-unknown-linux-gnu/debug/Modules/SadTuple.swiftsourceinfo -emit-dependencies-path /workspaces/SadTuple/.build/aarch64-unknown-linux-gnu/debug/SadTuple.build/SadTuple.emit-module.d -parse-as-library -o /workspaces/SadTuple/.build/aarch64-unknown-linux-gnu/debug/Modules/SadTuple.swiftmodule
1.      Swift version 6.1-dev (LLVM 83bb915697f5992, Swift 1e211b4d3227ecc)
2.      Compiling with the current language version
3.      While evaluating request ASTLoweringRequest(Lowering AST to SIL for module SadTuple)
4.      While generating SIL witness table protocol conformance TupleSchema<repeat each ElementSchema>: Schema at 'TupleSchema' (at /workspaces/SadTuple/Sources/SadTuple/SadTuple.swift:12:9)
5.      While generating protocol witness thunk SIL function "@$s8SadTuple0B6Schema33_B7CE4000642428A090CBF82EDA9BAD5FLLVyxxQp_QPGAA0C0A2aFP6encode_2toy5ValueQz_AA7EncoderVyxGtKFTW".
 for 'encode(_:to:)' (at /workspaces/SadTuple/Sources/SadTuple/SadTuple.swift:16:3)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend  0x0000aaaae806908c
1  swift-frontend  0x0000aaaae8066ee0
2  swift-frontend  0x0000aaaae80697a0
3  linux-vdso.so.1 0x0000ffff907137a0 __kernel_rt_sigreturn + 0
4  libc.so.6       0x0000ffff8eccf1f0
5  libc.so.6       0x0000ffff8ec8a67c raise + 28
6  libc.so.6       0x0000ffff8ec77130 abort + 228
7  libc.so.6       0x0000ffff8ec83fd4
8  libc.so.6       0x0000ffff8ec8404c
9  swift-frontend  0x0000aaaae19643dc
10 swift-frontend  0x0000aaaae1961744
11 swift-frontend  0x0000aaaae1969288
12 swift-frontend  0x0000aaaae195a154
13 swift-frontend  0x0000aaaae195cbd4
14 swift-frontend  0x0000aaaae198eee0
15 swift-frontend  0x0000aaaae19918c0
16 swift-frontend  0x0000aaaae1991104
17 swift-frontend  0x0000aaaae1990a4c
18 swift-frontend  0x0000aaaae198dce0
19 swift-frontend  0x0000aaaae19900ac
20 swift-frontend  0x0000aaaae198fa8c
21 swift-frontend  0x0000aaaae189877c
22 swift-frontend  0x0000aaaae1898d44
23 swift-frontend  0x0000aaaae197b8b8
24 swift-frontend  0x0000aaaae189df18
25 swift-frontend  0x0000aaaae189922c
26 swift-frontend  0x0000aaaae116dea0
27 swift-frontend  0x0000aaaae117b2d8
28 swift-frontend  0x0000aaaae11703c4
29 swift-frontend  0x0000aaaae116f7d4
30 swift-frontend  0x0000aaaae0f56838
31 libc.so.6       0x0000ffff8ec773fc
32 libc.so.6       0x0000ffff8ec774cc __libc_start_main + 152
33 swift-frontend  0x0000aaaae0f55a30
```

### Expected behavior

Does not crash

### Environment

swift-6.1-DEVELOPMENT-SNAPSHOT-2025-03-25-a

### Additional information

Likely having assertions enabled is a culprit here, but the assertion shouldn't be tripping since this is valid code

### LINKED ISSUE #81002: Variadic generics crash when parameter pack is used in a closure's arguments
### Description

A function which takes as an argument a closure whose arguments are a parameter pack equated to a concrete value will reliably cause the compiler to crash (**crash**, not assert).

### Reproduction

Reduced test case:
```swift
public protocol EnumSchemaCodable<Value>: Sendable {

  associatedtype Value

  func encode(_ value: Value, to encoder: some Encoder<Self>)

}

public protocol Encoder<Schema> {

  associatedtype Schema: EnumSchemaCodable

  func encode<each AssociatedValue>(
    _ encode: (
      repeat each AssociatedValue
    ) -> Void
  ) where (repeat each AssociatedValue) == Schema.Value

}

private struct Foo: EnumSchemaCodable {

  typealias Value = (String, Int)

  func encode(_ value: Value, to encoder: some Encoder<Self>) {
    // Commenting this out will fix the crash
    encoder.encode(
      { (first, second) in
      }
    )
  }

}

```

### Stack dump

```text
Building for debugging...
error: compile command failed due to signal 11 (use -v to see invocation)
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.      Program arguments: /Volumes/Shared/Developer/Xcode/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /Volumes/Shared/Developer/Projects/SadTuple/Sources/SadTuple/SadTuple.swift -emit-dependencies-path /Volumes/Shared/Developer/Projects/SadTuple/.build/arm64-apple-macosx/debug/SadTuple.build/SadTuple.d -emit-reference-dependencies-path /Volumes/Shared/Developer/Projects/SadTuple/.build/arm64-apple-macosx/debug/SadTuple.build/SadTuple.swiftdeps -target arm64-apple-macosx14.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -stack-check -sdk /Volumes/Shared/Developer/Xcode/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk -I /Volumes/Shared/Developer/Projects/SadTuple/.build/arm64-apple-macosx/debug/Modules -I /Volumes/Shared/Developer/Xcode/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F /Volumes/Shared/Developer/Xcode/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -color-diagnostics -enable-testing -g -debug-info-format=dwarf -dwarf-version=4 -module-cache-path /Volumes/Shared/Developer/Projects/SadTuple/.build/arm64-apple-macosx/debug/ModuleCache -swift-version 6 -Onone -D SWIFT_PACKAGE -D DEBUG -new-driver-path /Volumes/Shared/Developer/Xcode/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-driver -empty-abi-descriptor -resource-dir /Volumes/Shared/Developer/Xcode/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -file-compilation-dir /Volumes/Shared/Developer/Projects/SadTuple -Xcc -isysroot -Xcc /Volumes/Shared/Developer/Xcode/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk -Xcc -F -Xcc /Volumes/Shared/Developer/Xcode/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -Xcc -fPIC -Xcc -g -module-name SadTuple -package-name sadtuple -disable-clang-spi -target-sdk-version 15.2 -target-sdk-name macosx15.2 -external-plugin-path /Volumes/Shared/Developer/Xcode/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins#/Volumes/Shared/Developer/Xcode/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Volumes/Shared/Developer/Xcode/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins#/Volumes/Shared/Developer/Xcode/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -plugin-path /Volumes/Shared/Developer/Xcode/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Volumes/Shared/Developer/Xcode/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/lib/swift/host/plugins -parse-as-library -o /Volumes/Shared/Developer/Projects/SadTuple/.build/arm64-apple-macosx/debug/SadTuple.build/SadTuple.swift.o -index-store-path /Volumes/Shared/Developer/Projects/SadTuple/.build/arm64-apple-macosx/debug/index/store -index-system-modules
1.      Apple Swift version 6.0.3 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
2.      Compiling with the current language version
3.      While evaluating request ASTLoweringRequest(Lowering AST to SIL for file "/Volumes/Shared/Developer/Projects/SadTuple/Sources/SadTuple/SadTuple.swift")
4.      While silgen emitFunction SIL function "@$s8SadTuple3Foo33_B7CE4000642428A090CBF82EDA9BAD5FLLV6encode_2toySS_Sit_xtAA7EncoderRzAD6SchemaRtzlF".
 for 'encode(_:to:)' (at /Volumes/Shared/Developer/Projects/SadTuple/Sources/SadTuple/SadTuple.swift:25:3)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000109c16a9c llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x0000000109c14cf0 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x0000000109c17068 SignalHandler(int) + 292
3  libsystem_platform.dylib 0x0000000193e7ede4 _sigtramp + 56
4  swift-frontend           0x0000000104de6da4 (anonymous namespace)::SubstFunctionTypePatternVisitor::handlePackExpansion(swift::Lowering::AbstractionPattern, swift::CanType) + 264
5  swift-frontend           0x0000000104de6da4 (anonymous namespace)::SubstFunctionTypePatternVisitor::handlePackExpansion(swift::Lowering::AbstractionPattern, swift::CanType) + 264
6  swift-frontend           0x0000000104de6bc8 void llvm::function_ref<void (swift::Lowering::FunctionParamGenerator&)>::callback_fn<(anonymous namespace)::SubstFunctionTypePatternVisitor::handleUnabstractedFunctionType(swift::CanTypeWrapper<swift::AnyFunctionType>, swift::Lowering::AbstractionPattern, swift::CanType, swift::Lowering::AbstractionPattern)::'lambda'(swift::Lowering::FunctionParamGenerator&)>(long, swift::Lowering::FunctionParamGenerator&) + 348
7  swift-frontend           0x0000000104de3d74 swift::Lowering::AbstractionPattern::forEachFunctionParam(swift::ArrayRefView<swift::AnyFunctionType::Param, swift::AnyFunctionType::CanParam, swift::AnyFunctionType::CanParam::getFromParam(swift::AnyFunctionType::Param const&), true>, bool, llvm::function_ref<void (swift::Lowering::FunctionParamGenerator&)>) const + 208
8  swift-frontend           0x0000000104de604c (anonymous namespace)::SubstFunctionTypePatternVisitor::handleUnabstractedFunctionType(swift::CanTypeWrapper<swift::AnyFunctionType>, swift::Lowering::AbstractionPattern, swift::CanType, swift::Lowering::AbstractionPattern) + 136
9  swift-frontend           0x0000000104de5bfc swift::Lowering::AbstractionPattern::getSubstFunctionTypePattern(swift::CanTypeWrapper<swift::AnyFunctionType>, swift::Lowering::TypeConverter&, swift::Lowering::AbstractionPattern, swift::CanType, bool&) const + 236
10 swift-frontend           0x0000000104e2fe60 getSILFunctionType(swift::Lowering::TypeConverter&, swift::TypeExpansionContext, swift::Lowering::AbstractionPattern, swift::CanTypeWrapper<swift::AnyFunctionType>, swift::SILExtInfoBuilder, (anonymous namespace)::Conventions const&, swift::ForeignInfo const&, std::__1::optional<swift::SILDeclRef>, std::__1::optional<swift::SILDeclRef>, std::__1::optional<swift::SubstitutionMap>, swift::ProtocolConformanceRef) + 1368
11 swift-frontend           0x0000000104e268f0 getNativeSILFunctionType(swift::Lowering::TypeConverter&, swift::TypeExpansionContext, swift::Lowering::AbstractionPattern, swift::CanTypeWrapper<swift::AnyFunctionType>, swift::SILExtInfoBuilder, std::__1::optional<swift::SILDeclRef>, std::__1::optional<swift::SILDeclRef>, std::__1::optional<swift::SubstitutionMap>, swift::ProtocolConformanceRef) + 596
12 swift-frontend           0x0000000104e2a2fc getUncachedSILFunctionTypeForConstant(swift::Lowering::TypeConverter&, swift::TypeExpansionContext, swift::SILDeclRef, swift::Lowering::TypeConverter::LoweredFormalTypes) + 1352
13 swift-frontend           0x0000000104e2ae84 swift::Lowering::TypeConverter::getConstantInfo(swift::TypeExpansionContext, swift::SILDeclRef) + 192
14 swift-frontend           0x0000000104e20644 swift::SILFunctionBuilder::getOrCreateFunction(swift::SILLocation, swift::SILDeclRef, swift::ForDefinition_t, llvm::function_ref<swift::SILFunction* (swift::SILLocation, swift::SILDeclRef)>, swift::ProfileCounter) + 132
15 swift-frontend           0x0000000104fd7c94 swift::Lowering::SILGenModule::getFunction(swift::SILDeclRef, swift::ForDefinition_t) + 440
16 swift-frontend           0x0000000104fe36a0 void llvm::function_ref<void ()>::callback_fn<swift::Lowering::SILGenModule::emitClosure(swift::AbstractClosureExpr*, swift::Lowering::FunctionTypeInfo const&)::$_0>(long) + 92
17 swift-frontend           0x0000000104fdc810 swift::Lowering::SILGenModule::emitClosure(swift::AbstractClosureExpr*, swift::Lowering::FunctionTypeInfo const&) + 280
18 swift-frontend           0x000000010508376c (anonymous namespace)::RValueEmitter::visitAbstractClosureExpr(swift::AbstractClosureExpr*, swift::Lowering::SGFContext) + 1984
19 swift-frontend           0x000000010505f58c swift::Lowering::SILGenFunction::emitRValueAsSingleValue(swift::Expr*, swift::Lowering::SGFContext) + 40
20 swift-frontend           0x000000010503f234 swift::Lowering::SILGenFunction::emitConvertedRValue(swift::SILLocation, swift::Lowering::Conversion const&, swift::Lowering::SGFContext, llvm::function_ref<swift::Lowering::ManagedValue (swift::Lowering::SILGenFunction&, swift::SILLocation, swift::Lowering::SGFContext)>) + 316
21 swift-frontend           0x0000000104fbee74 swift::Lowering::ArgumentSource::getConverted(swift::Lowering::SILGenFunction&, swift::Lowering::Conversion const&, swift::Lowering::SGFContext) && + 136
22 swift-frontend           0x0000000104ffe25c (anonymous namespace)::ArgEmitter::emit(swift::Lowering::ArgumentSource&&, swift::Lowering::AbstractionPattern, std::__1::optional<swift::AnyFunctionType::Param>) + 5528
23 swift-frontend           0x0000000104fec0f0 (anonymous namespace)::ArgEmitter::emitSingleArg(swift::Lowering::ArgumentSource&&, swift::Lowering::AbstractionPattern, std::__1::optional<swift::AnyFunctionType::Param>) + 216
24 swift-frontend           0x0000000104ffc9ac (anonymous namespace)::ArgEmitter::emitPreparedArgs(swift::Lowering::PreparedArguments&&, swift::Lowering::AbstractionPattern) + 256
25 swift-frontend           0x0000000105008878 (anonymous namespace)::CallSite::emit(swift::Lowering::SILGenFunction&, swift::Lowering::AbstractionPattern, swift::CanTypeWrapper<swift::SILFunctionType>, (anonymous namespace)::ParamLowering&, llvm::SmallVectorImpl<swift::Lowering::ManagedValue>&, llvm::SmallVectorImpl<(anonymous namespace)::DelayedArgument>&, swift::ForeignInfo const&) && + 664
26 swift-frontend           0x0000000105008298 (anonymous namespace)::CallEmission::emitArgumentsForNormalApply(swift::Lowering::AbstractionPattern, swift::CanTypeWrapper<swift::SILFunctionType>, swift::ForeignInfo const&, llvm::SmallVectorImpl<swift::Lowering::ManagedValue>&, std::__1::optional<swift::SILLocation>&) + 1000
27 swift-frontend           0x0000000104ff0e7c (anonymous namespace)::CallEmission::apply(swift::Lowering::SGFContext) + 2028
28 swift-frontend           0x0000000104fef408 swift::Lowering::SILGenFunction::emitApplyExpr(swift::ApplyExpr*, swift::Lowering::SGFContext) + 3116
29 swift-frontend           0x000000010505fc74 swift::Lowering::SILGenFunction::emitIgnoredExpr(swift::Expr*) + 888
30 swift-frontend           0x0000000105117274 swift::ASTVisitor<(anonymous namespace)::StmtEmitter, void, void, void, void, void, void>::visit(swift::Stmt*) + 5512
31 swift-frontend           0x000000010508efc8 swift::Lowering::SILGenFunction::emitFunction(swift::FuncDecl*) + 492
32 swift-frontend           0x0000000104fdab1c swift::Lowering::SILGenModule::emitFunctionDefinition(swift::SILDeclRef, swift::SILFunction*) + 8420
33 swift-frontend           0x0000000104fdb3bc swift::Lowering::SILGenModule::emitOrDelayFunction(swift::SILDeclRef) + 216
34 swift-frontend           0x0000000104fd89ec swift::Lowering::SILGenModule::emitFunction(swift::FuncDecl*) + 364
35 swift-frontend           0x000000010512ec8c (anonymous namespace)::SILGenType::visitFuncDecl(swift::FuncDecl*) + 32
36 swift-frontend           0x000000010512b234 (anonymous namespace)::SILGenType::emitType() + 424
37 swift-frontend           0x0000000104fd8624 swift::ASTVisitor<swift::Lowering::SILGenModule, void, void, void, void, void, void>::visit(swift::Decl*) + 104
38 swift-frontend           0x0000000104fdf038 swift::ASTLoweringRequest::evaluate(swift::Evaluator&, swift::ASTLoweringDescriptor) const + 1804
39 swift-frontend           0x000000010511592c swift::SimpleRequest<swift::ASTLoweringRequest, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>> (swift::ASTLoweringDescriptor), (swift::RequestFlags)9>::evaluateRequest(swift::ASTLoweringRequest const&, swift::Evaluator&) + 196
40 swift-frontend           0x0000000104fe3f14 swift::ASTLoweringRequest::OutputType swift::Evaluator::getResultUncached<swift::ASTLoweringRequest, swift::ASTLoweringRequest::OutputType swift::evaluateOrFatal<swift::ASTLoweringRequest>(swift::Evaluator&, swift::ASTLoweringRequest)::'lambda'()>(swift::ASTLoweringRequest const&, swift::ASTLoweringRequest::OutputType swift::evaluateOrFatal<swift::ASTLoweringRequest>(swift::Evaluator&, swift::ASTLoweringRequest)::'lambda'()) + 528
41 swift-frontend           0x00000001045bdb90 swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 920
42 swift-frontend           0x00000001045c0e88 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 1684
43 swift-frontend           0x00000001045bfbb4 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 3572
44 swift-frontend           0x0000000104546a5c swift::mainEntry(int, char const**) + 3680
45 dyld                     0x0000000193ac8274 start + 2840
```

### Expected behavior

This does not crash

### Environment

swift-driver version: 1.115.1 Apple Swift version 6.0.3 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
Target: arm64-apple-macosx15.0

### Additional information

_No response_

### LINKED ISSUE #81600: Compiler crash when conforming to protocol with a method using parameter pack with generic type
### Description

If parameter of `foo` is `repeat each T` the compiler doesn't crash. When using `repeat Foo<each T>` it crashes.

Note that if I remove the conformance declaration it works as well.

### Reproduction

```swift
struct Foo<T> { }

protocol Bar {
    func foo<each T>(
        _ foos: repeat Foo<each T>
    )
}

struct BarImpl: Bar {
    func foo<each T>(
        _ foos: repeat Foo<each T>
    ) {
        
    }
}
```

### Stack dump

```text
Assertion failed: (canForwardOutput == (outputElt.isInContext() || outputElt.isPlusOneOrTrivial(*this)) && "transformation produced a value of the wrong ownership"), function operator(), file SILGenPack.cpp, line 1122.
Stack dump:
0.	Program arguments: ${HOME}/Library/Developer/Toolchains/swift-6.1-RELEASE.xctoolchain/usr/bin/swift-frontend -frontend -interpret Reproducer.swift -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk -color-diagnostics -swift-version 6 -empty-abi-descriptor -resource-dir ${HOME}/Library/Developer/Toolchains/swift-6.1-RELEASE.xctoolchain/usr/lib/swift -module-name Reproducer -in-process-plugin-server-path ${HOME}/Library/Developer/Toolchains/swift-6.1-RELEASE.xctoolchain/usr/lib/swift/host/libSwiftInProcPluginServer.dylib -plugin-path ${HOME}/Library/Developer/Toolchains/swift-6.1-RELEASE.xctoolchain/usr/lib/swift/host/plugins -plugin-path ${HOME}/Library/Developer/Toolchains/swift-6.1-RELEASE.xctoolchain/usr/local/lib/swift/host/plugins -target-sdk-version 15.4 -target-sdk-name macosx15.4 -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server
1.	Apple Swift version 6.1 (swift-6.1-RELEASE)
2.	Compiling with the current language version
3.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for module Reproducer)
4.	While generating SIL witness table protocol conformance BarImpl: Bar at 'BarImpl' (at Reproducer.swift:9:1)
5.	While generating protocol witness thunk SIL function "@$s10Reproducer7BarImplVAA0B0A2aDP3fooyyAA3FooVyqd__Gqd__QpRvd__lFTW".
 for 'foo(_:)' (at Reproducer.swift:10:5)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000109dcb884 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x0000000109dc9fb0 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x0000000109dcbec8 SignalHandler(int) + 292
3  libsystem_platform.dylib 0x000000018f268624 _sigtramp + 56
4  libsystem_pthread.dylib  0x000000018f22e88c pthread_kill + 296
5  libsystem_c.dylib        0x000000018f137c60 abort + 124
6  libsystem_c.dylib        0x000000018f136eec err + 0
7  swift-frontend           0x0000000109e809d4 swift::Lowering::SILGenFunction::emitSwitchStmt(swift::SwitchStmt*) (.cold.3) + 0
8  swift-frontend           0x00000001051483e0 void llvm::function_ref<void (swift::SILValue, swift::SILValue, swift::SILValue)>::callback_fn<swift::Lowering::SILGenFunction::emitPackTransform(swift::SILLocation, swift::Lowering::ManagedValue, swift::CanTypeWrapper<swift::PackType>, unsigned int, swift::SILValue, swift::CanTypeWrapper<swift::PackType>, unsigned int, bool, bool, llvm::function_ref<swift::Lowering::ManagedValue (swift::Lowering::ManagedValue, swift::SILType, swift::Lowering::SGFContext)>)::$_0>(long, swift::SILValue, swift::SILValue, swift::SILValue) + 1188
9  swift-frontend           0x0000000105144230 swift::Lowering::SILGenFunction::emitDynamicPackLoop(swift::SILLocation, swift::CanTypeWrapper<swift::PackType>, unsigned int, swift::SILValue, swift::SILValue, swift::GenericEnvironment*, bool, llvm::function_ref<void (swift::SILValue, swift::SILValue, swift::SILValue)>, swift::SILBasicBlock*) + 1676
10 swift-frontend           0x00000001051457f4 swift::Lowering::SILGenFunction::emitPackTransform(swift::SILLocation, swift::Lowering::ManagedValue, swift::CanTypeWrapper<swift::PackType>, unsigned int, swift::SILValue, swift::CanTypeWrapper<swift::PackType>, unsigned int, bool, bool, llvm::function_ref<swift::Lowering::ManagedValue (swift::Lowering::ManagedValue, swift::SILType, swift::Lowering::SGFContext)>) + 808
11 swift-frontend           0x000000010515ed98 (anonymous namespace)::TranslateArguments::process(swift::Lowering::AbstractionPattern, swift::ArrayRefView<swift::AnyFunctionType::Param, swift::AnyFunctionType::CanParam, swift::AnyFunctionType::CanParam::getFromParam(swift::AnyFunctionType::Param const&), true>, swift::Lowering::AbstractionPattern, swift::ArrayRefView<swift::AnyFunctionType::Param, swift::AnyFunctionType::CanParam, swift::AnyFunctionType::CanParam::getFromParam(swift::AnyFunctionType::Param const&), true>, bool) + 1820
12 swift-frontend           0x00000001051617f8 swift::Lowering::SILGenFunction::emitProtocolWitness(swift::Lowering::AbstractionPattern, swift::CanTypeWrapper<swift::AnyFunctionType>, swift::SILDeclRef, swift::SubstitutionMap, swift::SILDeclRef, swift::SubstitutionMap, swift::Lowering::IsFreeFunctionWitness_t, bool, bool, std::__1::optional<swift::ActorIsolation>) + 2700
13 swift-frontend           0x000000010518b1f4 swift::Lowering::SILGenModule::emitProtocolWitness(swift::ProtocolConformanceRef, swift::SILLinkage, swift::SerializedKind_t, swift::SILDeclRef, swift::SILDeclRef, swift::Lowering::IsFreeFunctionWitness_t, swift::Witness) + 3308
14 swift-frontend           0x000000010518d8fc (anonymous namespace)::SILGenWitnessTable<(anonymous namespace)::SILGenConformance>::addMethodImplementation(swift::SILDeclRef, swift::SILDeclRef, swift::Witness) + 496
15 swift-frontend           0x000000010518d408 (anonymous namespace)::SILGenWitnessTable<(anonymous namespace)::SILGenConformance>::addMethod(swift::SILDeclRef) + 856
16 swift-frontend           0x000000010518ce64 swift::SILWitnessVisitor<(anonymous namespace)::SILGenConformance>::visitProtocolDecl(swift::ProtocolDecl*) + 2148
17 swift-frontend           0x000000010518a398 swift::Lowering::SILGenModule::getWitnessTable(swift::NormalProtocolConformance*) + 324
18 swift-frontend           0x000000010518c2b4 (anonymous namespace)::SILGenType::emitType() + 1568
19 swift-frontend           0x000000010518bc88 swift::Lowering::SILGenModule::visitNominalTypeDecl(swift::NominalTypeDecl*) + 24
20 swift-frontend           0x0000000105084f10 swift::Lowering::SILGenModule::emitSourceFile(swift::SourceFile*) + 176
21 swift-frontend           0x000000010508542c swift::ASTLoweringRequest::evaluate(swift::Evaluator&, swift::ASTLoweringDescriptor) const + 632
22 swift-frontend           0x000000010517a238 swift::SimpleRequest<swift::ASTLoweringRequest, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>> (swift::ASTLoweringDescriptor), (swift::RequestFlags)17>::evaluateRequest(swift::ASTLoweringRequest const&, swift::Evaluator&) + 148
23 swift-frontend           0x0000000105089434 swift::ASTLoweringRequest::OutputType swift::Evaluator::getResultUncached<swift::ASTLoweringRequest, swift::ASTLoweringRequest::OutputType swift::evaluateOrFatal<swift::ASTLoweringRequest>(swift::Evaluator&, swift::ASTLoweringRequest)::'lambda'()>(swift::ASTLoweringRequest const&, swift::ASTLoweringRequest::OutputType swift::evaluateOrFatal<swift::ASTLoweringRequest>(swift::Evaluator&, swift::ASTLoweringRequest)::'lambda'()) + 340
24 swift-frontend           0x0000000105085798 swift::performASTLowering(swift::ModuleDecl*, swift::Lowering::TypeConverter&, swift::SILOptions const&, swift::IRGenOptions const*) + 136
25 swift-frontend           0x0000000104adcd70 swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 1288
26 swift-frontend           0x0000000104ae8b50 withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 164
27 swift-frontend           0x0000000104ade74c performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 716
28 swift-frontend           0x0000000104addf68 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2228
29 swift-frontend           0x00000001048c18f0 swift::mainEntry(int, char const**) + 3064
30 dyld                     0x000000018ee8eb98 start + 6076
```

### Expected behavior

Code should compile without the compiler crashing.

### Environment

Apple Swift version 6.1 (swift-6.1-RELEASE)
Target: arm64-apple-macosx15.0

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by rjmccall**
- Calls to variadic-generic protocol requirements weren't applying substitutions properly, so expansion-sensitive types in the callee signature weren't pairing properly with their expansions in the caller.

- emitPackTransform had an over-destroy if the transformation function actually emitted into the temporary element directly.

- There were some MV ownership assertions that were wrong, which revealed that the corresponding code really didn't handle consuming/ borrowing mismatches properly at all.

- We were completely mishandled consuming packs.

Fixes #81002, fixes #80995, fixes #81600.

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test

File: lib/SILGen/SILGenProlog.cpp [hunk 1]
```diff
@@ -902,6 +902,8 @@ class ArgumentInitHelper {
     ManagedValue argrv = makeArgument(loc, pd);
     if (pd->isInOut()) {
       assert(argrv.getType().isAddress() && "expected inout to be address");
+    } else if (argrv.getType().is<SILPackType>()) {
+      assert(argrv.getType().isAddress() && "expected pack to be address");
```
Comment (slavapestov) [inline lib/SILGen/SILGenProlog.cpp:906]: Consider using ASSERT instead

File: test/SILGen/protocol_packs.swift [hunk 2]
```diff
@@ -0,0 +1,245 @@
+// RUN: %target-swift-emit-silgen -disable-availability-checking -module-name test %s | %FileCheck %s
```
Comment (slavapestov) [inline test/SILGen/protocol_packs.swift]: `-target %target-swift-5.9-abi-triple` is better than `-disable-availability-checking`

**Review by slavapestov — APPROVED** [review]

File: test/SILGen/protocol_packs.swift (hunk 2 above)
Comment (rjmccall) [reply test/SILGen/protocol_packs.swift]: Sure

**Comment by rjmccall** [comment]
@swift-ci Please smoke test

File: lib/SILGen/SILGenProlog.cpp (hunk 1 above)
Comment (rjmccall) [reply lib/SILGen/SILGenProlog.cpp:906]: It's right next to a bunch of other `assert`s, I don't see any reason to do this piecemeal.

**Comment by rjmccall** [comment]
@swift-ci Please clean smoke test macOS

**Comment by rjmccall** [comment]
@swift-ci Please test Windows

**Comment by rjmccall** [comment]
@swift-ci Please test macOS

**Comment by tshortli** [comment]
@swift-ci Please test macOS
