### PR TITLE
Sema: Small fixes for result builder inference

### LINKED ISSUE #76362: Result builder inference behavior does not agree with proposal
### Description

It follows from [SE-0289](https://github.com/swiftlang/swift-evolution/blob/066c7474d4a5ab8c9f04c0a0eee1b519ceb8274b/proposals/0289-result-builders.md#inferring-result-builders-from-protocol-requirements) that result builder attributes in protocols are not hard requirements:

> When a `View`-conforming type defines its `body`, the `@ViewBuilder` attribute is inferred from the protocol requirement it satisfies, implicitly applying the result builder transform. This inference occurs unless:
> * The function or property already has a result builder attribute explicitly written on it, or
> * The body of the function or property getter contains an explicit `return` statement.

However, current behavior is not aligned with the first inference exception.

### Reproduction

```swift
@resultBuilder
enum Builder1 {
  static func buildBlock(_ t: Int) -> Bool {}
}
@resultBuilder
enum Builder2 {
  static func buildBlock(_ t: String) -> Bool {}
}
protocol P {
  @Builder1
  var x: Bool { get }
}
struct Test: P {
  @Builder2
  var x: Bool { "" }
}
```
```
341 | struct Test: P {
342 |   @Builder2
343 |   var x: Bool { "" }
    |                 `- error: cannot convert value of type 'String' to expected argument type 'Int' [cannot_convert_argument_value]
344 | }
345 | 
```

### Expected behavior

Successful compilation.

### Environment

Swift version 6.1-dev (Swift 614e8aa79a84486)

### Additional information

_No response_

### LINKED ISSUE #76746: Result builder inference from protocol requirement does not work when the attribute is attached to getter
### Description

_No response_

### Reproduction

```swift
@resultBuilder
enum Builder<T> {
  static func buildBlock(_ t: T...) -> Bool {true}
}
protocol P {
  var x: Bool { @Builder<Int> get }
}
struct Test: P {
  var x: Bool { 1 }
}
```
```
error: integer literal value '1' cannot be used as a boolean; did you mean 'true'? [integer_used_as_boolean_literal]
  var x: Bool { 1 }
                ^
                true
```

### Expected behavior

Successful compilation.

### Environment

Swift version 6.1-dev (614e8aa79a84486)

### Additional information

_No response_

### LINKED ISSUE #76747: Result builder inference from dynamically replaced decl does not work when the attribute is attached to getter
### Description

_No response_

### Reproduction

```swift
@resultBuilder
enum Builder<T> {
  static func buildBlock(_ t: T...) -> Bool {true}
}
struct Test {
  dynamic var x: Bool { @Builder<Int> get { 1 } }
}
extension Test {
  @_dynamicReplacement(for: x)
  var new_x: Bool { 1 }
}
```
```
/Users/mac/Desktop/test.swift:335:21: error: integer literal value '1' cannot be used as a boolean; did you mean 'true'? [integer_used_as_boolean_literal]
  var new_x: Bool { 1 }
                    ^
                    true
```

### Expected behavior

Successful compilation.

### Environment

Swift version 6.1-dev (614e8aa)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
Fixes #76362, fixes #76746, fixes #76747. 

These are technically source breaking, but the cases in which they break source are quite niche.

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test Linux

File: lib/Sema/TypeCheckRequestFunctions.cpp [hunk 1]
```diff
@@ -201,30 +201,44 @@ AttachedResultBuilderRequest::evaluate(Evaluator &evaluator,
...
+  // inference (e.g. with a return statement).
+  if (!funcDecl->hasBody()) {
+    return Type();
   }
 
+  // Check whether there are any return statements in the function's body.
+  // If there are, the result builder transform will be disabled,
+  // so don't infer a result builder.
+  if (!TypeChecker::findReturnStatements(funcDecl).empty())
+    return Type();
```
Comment (hamishknight) [inline lib/Sema/TypeCheckRequestFunctions.cpp:240]: While here, could change this to use `BraceHasReturnRequest` since that caches the result. Probably also ought to make that request a member on AnyFunctionRef at this point.

Comment (AnthonyLatsis) [reply lib/Sema/TypeCheckRequestFunctions.cpp:240]: Thanks for the idea!

**Review by xedin — APPROVED** [review]
LGTM! I second Hamish's comment about `BraceHasReturnRequest` it would be good to do at least that here.

File: lib/Sema/TypeCheckRequestFunctions.cpp (hunk 1 above)
Comment (AnthonyLatsis) [reply lib/Sema/TypeCheckRequestFunctions.cpp]: > Probably also ought to make that request a member on AnyFunctionRef at this point.

How’s this? I took a slightly different approach.

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test Linux

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test Linux

**Comment by AnthonyLatsis** [comment]
@swift-ci please test source compatibility release

File: lib/Sema/TypeChecker.h [hunk 2]
```diff
@@ -468,8 +468,7 @@ void typeCheckASTNode(ASTNode &node, DeclContext *DC,
 std::optional<BraceStmt *> applyResultBuilderBodyTransform(FuncDecl *func,
                                                            Type builderType);
 
-/// Find the return statements within the body of the given function.
-std::vector<ReturnStmt *> findReturnStatements(AnyFunctionRef fn);
+bool typeCheckClosureBody(ClosureExpr *closure);
```
Comment (hamishknight) [inline lib/Sema/TypeChecker.h:471]: Bad rebase? This function doesn't exist anymore

File: lib/Sema/BuilderTransform.cpp [hunk 3]
```diff
@@ -1126,8 +1124,7 @@ ConstraintSystem::matchResultBuilder(AnyFunctionRef fn, Type builderType,
   // not apply the result builder transform if it contained an explicit return.
   // To maintain source compatibility, we still need to check for HasReturnStmt.
   // https://github.com/apple/swift/issues/64332.
-  if (evaluateOrDefault(getASTContext().evaluator,
-                        BraceHasReturnRequest{fn.getBody()}, false)) {
+  if (fn.getBody()->hasExplicitReturnStmt(getASTContext())) {
```
Comment (hamishknight) [inline lib/Sema/BuilderTransform.cpp:1127]: One advantage of sticking the member on the AnyFunctionRef is you wouldn't have to pass along the ASTContext, but I don't feel too strongly about it

File: lib/Sema/BuilderTransform.cpp [hunk 4]
```diff
@@ -918,13 +918,11 @@ std::optional<BraceStmt *>
 TypeChecker::applyResultBuilderBodyTransform(FuncDecl *func, Type builderType) {
   // First look for any return statements, and bail if we have any.
   auto &ctx = func->getASTContext();
-  if (evaluateOrDefault(ctx.evaluator, BraceHasReturnRequest{func->getBody()},
-                        false)) {
+  if (SmallVector<ReturnStmt *> returnStmts;
+      func->getBody()->getExplicitReturnStmts(ctx, returnStmts),
+      !returnStmts.empty()) {
```
Comment (hamishknight) [inline lib/Sema/BuilderTransform.cpp:923]: Cute, but I would rather just bind `returnStmts` outside the `if`, up to you though

**Review by hamishknight — APPROVED** [review]

File: lib/Sema/BuilderTransform.cpp (hunk 3 above)
Comment (AnthonyLatsis) [reply lib/Sema/BuilderTransform.cpp:1127]: Yeah, that is unfortunate, and storing the context in the `BraceStmt` just for this sounds silly. 

Discoverability was my main concern with declaring it on `AnyFunctionRef`. Would you mind if I add forwarding methods to `AbstractFunctionDecl` and `AbstractClosureExpr` then?

File: lib/Sema/TypeChecker.h (hunk 2 above)
Comment (AnthonyLatsis) [reply lib/Sema/TypeChecker.h:471]: Good catch.

File: lib/Sema/BuilderTransform.cpp (hunk 3 above)
Comment (hamishknight) [reply lib/Sema/BuilderTransform.cpp:1127]: Sure, sounds good to me!

**Comment by AnthonyLatsis** [comment]
@swift-ci please test source compatibility release

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test
