### PR TITLE
[test] Add any_pattern in tuple pattern element extra tests

### LINKED ISSUE #60503: [Sema] Incorrect extra diagnostic for tuple pattern binding with `_` element
**Describe the bug**
For patterns like 
```swift
func f() {
  let (key, _) = settings // expected-error{{cannot find 'settings' in scope}}
  let (_, _) = settings // expected-error{{cannot find 'settings' in scope}}
}
```

Compiler produces an `type of expression is ambiguous without more context`
```
<source>:3:18: error: cannot find 'settings' in scope
  let (key, _) = settings // expected-error{{cannot find 'settings' in scope}}
                 ^~~~~~~~
<source>:3:18: error: type of expression is ambiguous without more context
  let (key, _) = settings // expected-error{{cannot find 'settings' in scope}}
                 ^~~~~~~~
<source>:4:16: error: cannot find 'settings' in scope
  let (_, _) = settings // expected-error{{cannot find 'settings' in scope}}
               ^~~~~~~~
<source>:4:16: error: type of expression is ambiguous without more context
  let (_, _) = settings // expected-error{{cannot find 'settings' in scope}}
               ^~~~~~~~
Compiler returned: 1
```

**Steps To Reproduce**
1. Run the code snippet on main 
2. Or see in Compiler Explorer in https://godbolt.org/z/GnfhaP8Eq
...

**Expected behavior**
The only relevant message is that variable is not on scope. All patterns should be bound to hole.

**Screenshots**

**Environment (please fill out the following information)**
 - OS: [e.g. macOS 11.0]
 - Xcode Version/Tag/Branch: main branch 

**Additional context**

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
AnyPattern in tuple pattern element should be able to be hole in the same way as named patterns. 

Resolves https://github.com/apple/swift/issues/60503.

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

File: lib/Sema/CSGen.cpp [hunk 1]
```diff
@@ -2513,7 +2513,13 @@ namespace {
 
           if (!eltTy)
             return Type();
-
+          
+          // AnyPattern in the context of a tuple binding e.g. (_,_)
+          // should be allowed to bind to a hole to allow them in the context of
+          // pattern bindings like `let (_,_) = notDeclaredVar` to be a hole.
+          if (isa<AnyPattern>(eltPattern)) {
+            CS.recordAnyTypeVarAsPotentialHole(eltTy);
```
Comment (xedin) [inline lib/Sema/CSGen.cpp:2521]: I don't think this is necessary, @LucianoPAlmeida. Examples you have added already work correctly on main because `getTypeForPattern` called on `AnyPattern` would produce a type variable that is marked as a hole.

Could you try without your changes but with very recent main? You should see 3 fixes like this ones:

```
  [fix: ignore invalid AST node] @ locator@0x11f028a00 [Error@<stdin>:3:16]
  [fix: specify type for pattern match] @ locator@0x11f028a98 [AnyPattern@<stdin>:3:8 -> '_' pattern decl]
  [fix: specify type for pattern match] @ locator@0x11f028af0 [AnyPattern@<stdin>:3:11 -> '_' pattern decl]
```

**Review by xedin — CHANGES_REQUESTED** [review]

File: lib/Sema/CSGen.cpp (hunk 1 above)
Comment (LucianoPAlmeida) [reply lib/Sema/CSGen.cpp:2521]: I can check, but while investigating this I have look at it and it was not marked... I think I've updated recently but I'll confirm that todays after work, but at top of my head I don't remember this being marked as hole for anypattern, I'll check today after work, thanks @xedin :)

Comment (LucianoPAlmeida) [reply lib/Sema/CSGen.cpp:2521]: Looks like I miss that completely, was a few days behind main, so before #60203 which not sure how I miss it ... sorry for that.

Comment (xedin) [reply lib/Sema/CSGen.cpp:2521]: No need to apologize! It's been an active development area lately :)

Comment (LucianoPAlmeida) [reply lib/Sema/CSGen.cpp:2521]: Yeah, but after looking to #60203 I also missed some other aspects in the approach, but I got it now. 
Ah, also I'm thinking in reopen this just for test cases, the new ones are slightly different from the ones from #60203 and I still like to move the previous one from `overload.swift` to `patterns.swift` but only if you think it is worth it

Comment (xedin) [reply lib/Sema/CSGen.cpp:2521]: Sure, sounds good to me!

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

**Review by xedin — APPROVED** [review]
