### PR TITLE
Fix two issues related with emission of differentiability witnesses

### LINKED ISSUE #59135: [AutoDiff][SILGen] Did not create differentiability witness for function
**Describe the bug**
When running the following script, the compiler crashes. Use `swiftc file.swift -emit-module` to reproduce this behavior.

**Reproducer**
```swift
import _Differentiation

public struct Tensor: Differentiable & AdditiveArithmetic {
  @inlinable
  func subscriptIndexPath() -> Tensor {
    fatalError()
  }

  @inlinable
  @differentiable(reverse, wrt: self)
  func subscriptRanges() -> Tensor {
    subscriptIndexPath()
  }
  
  @usableFromInline
  @derivative(of: subscriptIndexPath)
  func _vjpSubscriptIndexPath() -> (
    value: Tensor, pullback: (Tensor) -> Tensor
  ) {
    fatalError()
  }
}
```

**Expected behavior**
```
(base) philipturner@M1-Max-MacBook-Pro Desktop % swiftc file.swift -emit-module
error: emit-module command failed due to signal 6 (use -v to see invocation)
Assertion failed: (original->isExternalDeclaration() && "SILGen should create differentiability witnesses for all function " "definitions with explicit differentiable attributes"), function getOrCreateMinimalASTDifferentiabilityWitness, file Common.cpp, line 521.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
Stack dump:
0.	Program arguments: /Library/Developer/Toolchains/swift-5.7-DEVELOPMENT-SNAPSHOT-2022-05-18-a.xctoolchain/usr/bin/swift-frontend -frontend -emit-module -experimental-skip-non-inlinable-function-bodies-without-types file.swift -target arm64-apple-macosx12.0 -Xllvm -aarch64-use-tbi -warn-on-potentially-unavailable-enum-case -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -color-diagnostics -new-driver-path /Library/Developer/Toolchains/swift-5.7-DEVELOPMENT-SNAPSHOT-2022-05-18-a.xctoolchain/usr/bin/swift-driver -empty-abi-descriptor -resource-dir /Library/Developer/Toolchains/swift-5.7-DEVELOPMENT-SNAPSHOT-2022-05-18-a.xctoolchain/usr/lib/swift -module-name file -target-sdk-version 12.3 -emit-module-doc-path file.swiftdoc -emit-module-source-info-path file.swiftsourceinfo -o file.swiftmodule -emit-abi-descriptor-path file.abi.json
1.	Apple Swift version 5.7-dev (LLVM 9fde71b269b42b8, Swift ddc46e1f5bd885d)
2.	Compiling with the current language version
3.	While evaluating request ExecuteSILPipelineRequest(Run pipelines { Mandatory Diagnostic Passes + Enabling Optimization Passes } on SIL for file)
4.	While running pass #110 SILModuleTransform "Differentiation".
5.	While canonicalizing `differentiable_function` SIL node   %3 = differentiable_function [parameters 0] [results 0] %2 : $@convention(method) (Tensor) -> Tensor // user: %4
6.	While ...in SIL function "@$s4file6TensorV15subscriptRangesACyFTJrSpSr".
 for 'subscriptRanges()' (at file.swift:11:3)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x000000010920e01c llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x000000010920d27c llvm::sys::RunSignalHandlers() + 128
2  swift-frontend           0x000000010920e680 SignalHandler(int) + 304
3  libsystem_platform.dylib 0x000000019923f4a4 _sigtramp + 56
4  libsystem_pthread.dylib  0x0000000199227ee0 pthread_kill + 288
5  libsystem_c.dylib        0x0000000199162340 abort + 168
6  libsystem_c.dylib        0x0000000199161754 err + 0
7  swift-frontend           0x00000001093bc808 swift::autodiff::getOrCreateMinimalASTDifferentiabilityWitness(swift::SILModule&, swift::SILFunction*, swift::DifferentiabilityKind, swift::IndexSubset*, swift::IndexSubset*) (.cold.2) + 0
8  swift-frontend           0x000000010538c77c swift::autodiff::getOrCreateMinimalASTDifferentiabilityWitness(swift::SILModule&, swift::SILFunction*, swift::DifferentiabilityKind, swift::IndexSubset*, swift::IndexSubset*) + 724
9  swift-frontend           0x00000001054cff40 (anonymous namespace)::DifferentiationTransformer::promoteToDifferentiableFunction(swift::DifferentiableFunctionInst*, swift::SILBuilder&, swift::SILLocation, swift::autodiff::DifferentiationInvoker) + 1320
10 swift-frontend           0x00000001054cdefc (anonymous namespace)::DifferentiationTransformer::processDifferentiableFunctionInst(swift::DifferentiableFunctionInst*) + 484
11 swift-frontend           0x00000001054cbf88 (anonymous namespace)::Differentiation::run() + 1292
12 swift-frontend           0x000000010553f2fc swift::SILPassManager::runModulePass(unsigned int) + 956
13 swift-frontend           0x000000010554482c swift::SILPassManager::execute() + 624
14 swift-frontend           0x000000010553c3dc swift::SILPassManager::executePassPipelinePlan(swift::SILPassPipelinePlan const&) + 68
15 swift-frontend           0x000000010553c364 swift::ExecuteSILPipelineRequest::evaluate(swift::Evaluator&, swift::SILPipelineExecutionDescriptor) const + 68
16 swift-frontend           0x000000010555c800 swift::SimpleRequest<swift::ExecuteSILPipelineRequest, std::__1::tuple<> (swift::SILPipelineExecutionDescriptor), (swift::RequestFlags)1>::evaluateRequest(swift::ExecuteSILPipelineRequest const&, swift::Evaluator&) + 28
17 swift-frontend           0x00000001055473e8 llvm::Expected<swift::ExecuteSILPipelineRequest::OutputType> swift::Evaluator::getResultUncached<swift::ExecuteSILPipelineRequest>(swift::ExecuteSILPipelineRequest const&) + 252
18 swift-frontend           0x000000010553c5d8 swift::executePassPipelinePlan(swift::SILModule*, swift::SILPassPipelinePlan const&, bool, swift::irgen::IRGenModule*) + 84
19 swift-frontend           0x000000010554aeec swift::runSILDiagnosticPasses(swift::SILModule&) + 92
20 swift-frontend           0x0000000104d8b0d0 swift::CompilerInstance::performSILProcessing(swift::SILModule*) + 72
21 swift-frontend           0x0000000104d2fae8 performCompileStepsPostSILGen(swift::CompilerInstance&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> >, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*) + 716
22 swift-frontend           0x0000000104d2f4ac swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 1028
23 swift-frontend           0x0000000104d3c808 withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 160
24 swift-frontend           0x0000000104d31108 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 3388
25 swift-frontend           0x0000000104c45bc0 swift::mainEntry(int, char const**) + 3764
26 dyld                     0x0000000111b6908c start + 520
```

**Environment (please complete the following information):**
 - OS: macOS 12.4
 - Toolchain: Swift 5.7 Development Snapshot: May 18, 2022 (compiled from the release/5.7 branch)

### PR DESCRIPTION
**Pull request by asl**
1. When differentiable nested function (closure) is specialized by capture promotion pass ensure we generate a differentiability witness for the specialized function as well. Ensure the original witness is removed if the original function becomes dead.
2. Differentiability witnesses for a function could originate either from its `@differentiable` attribute or from explicit `@derivative(of:)` attribute on the derivative. In the latter case the derivative itself might not be emitted, while original function is (e.g. original function is `@inlineable`, but derivative is `@usableFromInline`). Previously both cases were handled only when function body was emitted. As a result we missed witness in the aforementioned case. Ensure the differentiability witness originating from `@derivative(of:)` is emitted even if we're not going to emit body of the derivative.

Fixes #59135

### CODE REVIEW

**Comment by asl** [comment]
Linux build seems to be broken due to unrelated issue:
```log
... lib/libFoundationInternationalization.so  lib/libFoundationEssentials.so  lib/lib_FoundationCollections.a  lib/lib_FoundationCShims.a  lib/lib_FoundationICU.so  /home/build-user/build/buildbot_linux/libdispatch-linux-x86_64/libswiftDispatch.so  /home/build-user/build/buildbot_linux/libdispatch-linux-x86_64/libdispatch.so  /home/build-user/build/buildbot_linux/libdispatch-linux-x86_64/libBlocksRuntime.so  -lgcc  -lgcc_s  -lc  -lgcc  -lgcc_s && :
error: link command failed with exit code 1 (use -v to see invocation)
Sources/plutil/CMakeFiles/plutil.dir/PLUContext_KeyPaths.swift.o:main.swift.o:function $sSS6plutilE19escapedKeyPathSplitSaySSGyF: error: undefined reference to '$sSy12RegexBuilderSs11SubSequenceRtzrlE5split9separator9maxSplits25omittingEmptySubsequencesSaySsGSS_SiSbtF'
```

**Comment by asl** [comment]
@swift-ci please test

**Comment by asl** [comment]
@swift-ci please test

**Comment by asl** [comment]
@swift-ci please test windows platform

**Comment by asl** [comment]
@swift-ci please test windows platform

**Comment by asl** [comment]
@swift-ci please test windows platform

**Comment by JaapWijnen** [comment]
I'm running into this one more often nowadays. Would be great if we could move this PR forward. Is there anything left to do to make the windows tests pass?

**Comment by asl** [comment]
@JaapWijnen windows was just broken on `main` IIRC.

**Comment by asl** [comment]
@swift-ci please test windows platform

**Comment by asl** [comment]
@swift-ci please test

**Comment by asl** [comment]
@swift-ci please test macos platform

**Comment by asl** [comment]
@swift-ci please test macos platform

**Comment by JaapWijnen** [comment]
I'd love to get this merged and perhaps we can still cherry pick this into 6.2? @clackary

File: test/AutoDiff/compiler_crashers_fixed/issue-59135-usableFromInline-VJP.swift [hunk 1]
```diff
@@ -0,0 +1,38 @@
+// RUN: %empty-directory(%t)
+// RUN: %target-swift-emit-sil -Xllvm -debug-only=differentiation -emit-module -module-name M -emit-module-path %t/M.swiftmodule 2>&1 %s | %FileCheck %s
+
+// The original function Tensor.subscriptIndexPath() is not marked as @differentiable. As a result, no explicit differentiable witness is generated for it.
+// However, the witness is generated as a side effect of providing a derivative via  @derivative(of: subscriptIndexPath) on _vjpSubscriptIndexPath.
+// Since _vjpSubscriptIndexPath is not emitted when -emit-module is used, we need to ensure we still generate a wittness.
```
Comment (clackary) [inline test/AutoDiff/compiler_crashers_fixed/issue-59135-usableFromInline-VJP.swift]:
```suggestion
// Since _vjpSubscriptIndexPath is not emitted when -emit-module is used, we need to ensure we still generate a witness.
```
typo

**Comment by asl** [comment]
@eeckstein @jckarter Any objections on this PR?

**Comment by asl** [comment]
@swift-ci please test

**Comment by asl** [comment]
@swift-ci please test

**Comment by asl** [comment]
@swift-ci please test windows platform

**Comment by asl** [comment]
@eeckstein @jckarter ping

**Comment by asl** [comment]
@swift-ci please test

**Comment by asl** [comment]
@eeckstein @jckarter will you please review the changes to optimization passes? The testcase contains the explanation of what's going on.

Thanks!

**Comment by asl** [comment]
@eeckstein @jckarter ping

**Comment by eeckstein** [comment]
Sorry, I'm not the right person to review autodiff changes

**Comment by asl** [comment]
> Sorry, I'm not the right person to review autodiff changes

My main question here is the behavior described in https://github.com/swiftlang/swift/pull/80983/files#diff-3d825843035cff5f5cb637283b50b73988e35a75f65bb402197bcd676924f81fR3 is ok for capture promotion pass.

**Comment by JaapWijnen** [comment]
We're unfortunately hitting #59135 again.
@asl  Are the changes hit by autodiff related code only? Or do these changes also affect other parts? 

Is there anything else we can provide from our side in order to get this approved?

**Comment by asl** [comment]
> @asl Are the changes hit by autodiff related code only? Or do these changes also affect other parts?

There are changes in capture promotion pass which I hoped to receive some approval from @eeckstein

**Comment by JaapWijnen** [comment]
> > @asl Are the changes hit by autodiff related code only? Or do these changes also affect other parts?
> 
> There are changes in capture promotion pass which I hoped to receive some approval from @eeckstein

Just to double check. By that you just mean the 20 lines inside /SilOptimizer/Mandatory right?

**Comment by asl** [comment]
> Just to double check. By that you just mean the 20 lines inside /SilOptimizer/Mandatory right?

Right. Capture promotion and diagnostics for dead functions (+ corresponding boilerplate in SILModule)

File: include/swift/SIL/SILModule.h [hunk 2]
```diff
@@ -600,6 +600,12 @@ class SILModule {
   /// Erase a global SIL variable from the module.
   void eraseGlobalVariable(SILGlobalVariable *G);
 
+  /// Erase a differentiability witness from the module.
+  void eraseDifferentiabilityWittness(SILDifferentiabilityWitness *dw);
```
Comment (kovdan01) [inline include/swift/SIL/SILModule.h]: Typo
```suggestion
  void eraseDifferentiabilityWitness(SILDifferentiabilityWitness *dw);
```

File: include/swift/SIL/SILModule.h [hunk 3]
```diff
@@ -600,6 +600,12 @@ class SILModule {
...
+
+  /// Erase all differentiability witnesses for function f.
+  void eraseAllDifferentiabilityWittnesses(SILFunction *f);
```
Comment (kovdan01) [inline include/swift/SIL/SILModule.h]: Typo
```suggestion
  void eraseAllDifferentiabilityWitnesses(SILFunction *f);
```

File: test/AutoDiff/compiler_crashers_fixed/issue-59135-nested-function-diff-wittness-capture-promotion.swift [hunk 4]
```diff
@@ -0,0 +1,33 @@
...
+struct B: Differentiable{}
+struct X { var j = [Float]()}
+struct W: Differentiable {
+    @noDerivative var z: X
+    var h: B
+}
+func o<T, R>(_ x: T, _ f: @differentiable(reverse) (T) -> R) -> R {f(x)}
+func m<T, R>(_ f: @escaping @differentiable(reverse) (T) -> R) -> @differentiable(reverse) (T) -> R {{ x in o(x, f) }}
+@differentiable(reverse)
+ func s(h: B) -> B {
```
Comment (kovdan01) [inline test/AutoDiff/compiler_crashers_fixed/issue-59135-nested-function-diff-wittness-capture-promotion.swift:24]: Probably non-indended space
```suggestion
func s(h: B) -> B {
```

File: lib/SILGen/SILGen.cpp [hunk 5]
```diff
@@ -1540,6 +1513,36 @@ void SILGenModule::emitAbstractFuncDecl(AbstractFunctionDecl *AFD) {
         SILDeclRef::BackDeploymentKind::Thunk);
     emitBackDeploymentThunk(thunk);
   }
+
+  // Emit differentiability witness for the function referenced in
+  // @derivative(of:) attribute registering current function as VJP / JVP.
+  for (auto *derivAttr : AFD->getAttrs().getAttributes<DerivativeAttr>()) {
+      auto *F = getFunction(SILDeclRef(AFD), NotForDefinition);
```
Comment (kovdan01) [inline lib/SILGen/SILGen.cpp]: Nit: it looks like that the code mostly uses `camelCase`, so it's probably better to name this `f` or `func` or smth instead of `F`

File: lib/SIL/IR/SILModule.cpp [hunk 6]
```diff
@@ -501,6 +501,33 @@ void SILModule::eraseGlobalVariable(SILGlobalVariable *gv) {
   getSILGlobalList().erase(gv);
 }
 
+void SILModule::eraseDifferentiabilityWittness(SILDifferentiabilityWitness *dw) {
+  getSILLoader()->invalidateDifferentiabilityWitness(dw);
+
+  Mangle::ASTMangler mangler(getASTContext());
+  auto *originalFunction = dw->getOriginalFunction();
```
Comment (kovdan01) [inline lib/SIL/IR/SILModule.cpp]: Nit: maybe it's worth to replace this as follows, since we only use `originalFunction` to call `getName()`:
```suggestion
  auto originalFunctionName = dw->getOriginalFunction()->getName();
```

File: lib/SILGen/SILGen.cpp [hunk 7]
```diff
@@ -1540,6 +1513,36 @@ void SILGenModule::emitAbstractFuncDecl(AbstractFunctionDecl *AFD) {
         SILDeclRef::BackDeploymentKind::Thunk);
     emitBackDeploymentThunk(thunk);
   }
+
+  // Emit differentiability witness for the function referenced in
+  // @derivative(of:) attribute registering current function as VJP / JVP.
```
Comment (kovdan01) [inline lib/SILGen/SILGen.cpp:1560]: It might be worth to add a comment (for example, copy it from p.2 of the PR description) explaining why we handle `derivative(of:)` and `differentiable` in different places.

File: test/AutoDiff/compiler_crashers_fixed/issue-59135-usableFromInline-VJP.swift [hunk 8]
```diff
@@ -0,0 +1,38 @@
...
+// Since _vjpSubscriptIndexPath is not emitted when -emit-module is used, we need to ensure we still generate a witness.
+
+import _Differentiation
+
+// CHECK-LABEL: differentiability witness for Tensor.subscriptIndexPath()
+// CHECK: sil_differentiability_witness [serialized] [reverse] [parameters 0] [results 0] @$s1M6TensorV18subscriptIndexPathACyF : $@convention(method) (Tensor) -> Tensor {
+// CHECK:  vjp: @$s1M6TensorV18subscriptIndexPathACyFTJrSpSr : $@convention(method) (Tensor) -> (Tensor, @owned @callee_guaranteed (Tensor) -> Tensor)
+
+// CHECK-LABEL: reverse-mode derivative of Tensor.subscriptIndexPath()
+// CHECK: sil [thunk] [always_inline] [ossa] @$s1M6TensorV18subscriptIndexPathACyFTJrSpSr : $@convention(method) (Tensor) -> (Tensor, @owned @callee_guaranteed (Tensor) -> Tensor) {
```
Comment (kovdan01) [inline test/AutoDiff/compiler_crashers_fixed/issue-59135-usableFromInline-VJP.swift]: On my Linux x86-64 machine and this PR applied on top of recent main branch, I have `[heuristic_always_inline]` instead of `[always_inline]`. If both are considered correct, I guess it's worth adding a regex which would match both

File: lib/SILOptimizer/Mandatory/CapturePromotion.cpp [hunk 9]
```diff
@@ -1473,9 +1473,23 @@ processPartialApplyInst(SILOptFunctionBuilder &funcBuilder,
       funcBuilder, pai, fri, promotableIndices, f->getResilienceExpansion());
   worklist.push_back(clonedFn);
 
+  SILFunction *origFn = fri->getReferencedFunction();
+  for (auto *w : mod.lookUpDifferentiabilityWitnessesForFunction(
```
Comment (kovdan01) [inline lib/SILOptimizer/Mandatory/CapturePromotion.cpp]: Nit
```suggestion
  for (const auto *w : mod.lookUpDifferentiabilityWitnessesForFunction(
```

File: lib/SILOptimizer/Mandatory/CapturePromotion.cpp [hunk 10]
```diff
@@ -1473,9 +1473,23 @@ processPartialApplyInst(SILOptFunctionBuilder &funcBuilder,
...
+         origFn->getName())) {
+    assert(!w->getJVP() && !w->getVJP() && "does not expect custom derivatives here");
```
Comment (kovdan01) [inline lib/SILOptimizer/Mandatory/CapturePromotion.cpp:1481]: It might be worth mentioning that `@derivative(of:` attr cannot be used in local scope, which is the reason why we do not expect custom derivatives here. One might not be aware of such limitations and it might not be clear for them why such assertion always holds.

File: test/AutoDiff/compiler_crashers_fixed/issue-59135-usableFromInline-VJP.swift [hunk 11]
```diff
@@ -0,0 +1,38 @@
+// RUN: %empty-directory(%t)
+// RUN: %target-swift-emit-sil -Xllvm -debug-only=differentiation -emit-module -module-name M -emit-module-path %t/M.swiftmodule 2>&1 %s | %FileCheck %s
```
Comment (kovdan01) [inline test/AutoDiff/compiler_crashers_fixed/issue-59135-usableFromInline-VJP.swift]: Could you please elaborate why in both tests we have debug output enabled? Is this required?

**Review by kovdan01 — COMMENTED** [review]
LGTM, thanks! Please pay attention to the comments in tests. Addressing other nits is optional, but mostly trivial, so I think it would be worth it :)

File: lib/SILGen/SILGen.cpp (hunk 5 above)
Comment (asl) [reply lib/SILGen/SILGen.cpp]: The code was just moved around, so this was the original piece. But anyway, I'll see what could be done

File: test/AutoDiff/compiler_crashers_fixed/issue-59135-usableFromInline-VJP.swift (hunk 8 above)
Comment (asl) [reply test/AutoDiff/compiler_crashers_fixed/issue-59135-usableFromInline-VJP.swift]: Nice catch! Yes, this PR needs a rebase

File: test/AutoDiff/compiler_crashers_fixed/issue-59135-usableFromInline-VJP.swift (hunk 11 above)
Comment (asl) [reply test/AutoDiff/compiler_crashers_fixed/issue-59135-usableFromInline-VJP.swift]: One is indeed just copy & paste. Another one is needed as we're matching post-autodiff SIL not the final one as the SIL will be further simplified by mandatory optimizations

**Comment by asl** [comment]
@swift-ci please test

**Review by kovdan01 — APPROVED** [review]
LGTM, thanks!
