### PR TITLE
[cxx-interop] Fix calling convention for rvalue reference params

### LINKED ISSUE #77894: C++ foreign type's dtor needs to be invoked on moved-from objects
### Description

When passing a type imported from C++ to a consuming Swift function (or a C++ foreign API taking an rvalue reference), the caller is still responsible for destroying the object (calling the dtor) regardless whether the object. 

### Reproduction

```swift
let x = getCppMoveOnlyType()
consumingFunction(x)
```

### Expected behavior

The dtor for `x` is invoked after the last use.

### Environment

swift-driver version: 1.115 Apple Swift version 6.0.2 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
Target: arm64-apple-macosx15.0

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Xazax-hun**
In C++, we always expected to invoke the dtor for moved-from objects. This is not the case for swift. Fortunately, @inCxx calling convention is already expressing that the caller supposed to destroy the object. This fixes the missing dtor calls when calling C++ functions taking rvalue references. Fixes #77894.

rdar://140786022

### CODE REVIEW

**Comment by Xazax-hun** [comment]
@swift-ci please smoke test

**Comment by Xazax-hun** [comment]
@swift-ci please smoke test

**Comment by Xazax-hun** [comment]
@swift-ci please smoke test

**Comment by Xazax-hun** [comment]
@swift-ci please smoke test macOS

**Comment by Xazax-hun** [comment]
@swift-ci please smoke test windows

File: test/Interop/Cxx/reference/rvalue-reference.swift [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+
+import SpecialMembers
+
+func consume(_ x: consuming MoveOnly) {}
+func consume(_ x: consuming Copyable) {}
+
+func main() {
+    let x = MoveOnly()
+// CHECK: MoveOnly 0 created
+// CHECK-OPT: MoveOnly 0 created
```
Comment (j-hui) [inline test/Interop/Cxx/reference/rvalue-reference.swift:14]: Can you document why this `CHECK-OPT` needs to exist? Is it because of potentially optimized temporaries?

If that's the case, I'm wondering whether it might be worth also testing this with `-fno-elide-constructors`, to ensure those temporaries are forcibly created.

File: test/Interop/Cxx/reference/rvalue-reference.swift [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+// RUN: %target-run-simple-swift(-I %S/Inputs/ -Xfrontend -enable-experimental-cxx-interop -O) | %FileCheck -check-prefix=CHECK-OPT %s
+//
+// REQUIRES: executable_test
+
+import SpecialMembers
+
+func consume(_ x: consuming MoveOnly) {}
+func consume(_ x: consuming Copyable) {}
+
+func main() {
```
Comment (j-hui) [inline test/Interop/Cxx/reference/rvalue-reference.swift:11]: nit: can you break this test up into separate functions, and briefly document the expected behavior? It's a bit hard to keep track of which variables are allocated where.

File: test/Interop/Cxx/reference/Inputs/print-special-members.h [hunk 3]
```diff
@@ -0,0 +1,21 @@
...
+    MoveOnly() : id(0) { printf("MoveOnly %d created\n", id); }
+    MoveOnly(const MoveOnly&) = delete;
+    MoveOnly(MoveOnly&& other) : id(other.id + 1) { printf("MoveOnly %d move-created\n", id); }
+    ~MoveOnly() { printf("MoveOnly %d destroyed\n", id); }
+};
+
+struct Copyable {
+    int id;
+    Copyable() : id(0) { printf("Copyable %d created\n", id); }
+    Copyable(const Copyable& other) : id(other.id + 1) { printf("Copyable %d copy-created\n", id); }
```
Comment (j-hui) [inline test/Interop/Cxx/reference/Inputs/print-special-members.h:15]: Is/can this copy constructor invoked when we do something like:

```swift
let c0 = Copyable()
let c1 = Copyable(c0) // or should it be Copyable(other: c0)?
```

File: test/Interop/Cxx/reference/Inputs/module.modulemap [hunk 4]
```diff
@@ -3,6 +3,11 @@ module Reference {
   requires cplusplus
 }
 
+module SpecialMembers {
```
Comment (j-hui) [inline test/Interop/Cxx/reference/Inputs/module.modulemap:6]: nit: why is this module case called `SpecialMembers`/`print-special-members.h`? The theme seems to be about logging copy- and move-constructor calls.

File: test/Interop/Cxx/reference/rvalue-reference.swift (hunk 1 above)
Comment (j-hui) [reply test/Interop/Cxx/reference/rvalue-reference.swift:14]: Oh. I just looked at the `// RUN` directives and realized that `OPT` stands for "optimized" and not "optional". (And I thought that `CHECK-OPT` was built into LLVM-lit, rather than being user-defined.)

Disregard my question about what `CHECK-OPT` means, but I'm still wondering about `-fno-elide-constructors`, and I also wonder if there's a better `check-prefix` like `CHECK-ONONE` vs `CHECK-DASHO` that will make it obvious what is being tested.

File: test/Interop/Cxx/reference/rvalue-reference.swift (hunk 2 above)
Comment (j-hui) [reply test/Interop/Cxx/reference/rvalue-reference.swift:11]: breaking it up into separate functions should also make it clearer which `Copyable` instance is being destroyed at the end.

File: lib/SILOptimizer/Transforms/CopyForwarding.cpp [hunk 5]
```diff
@@ -341,6 +341,7 @@ class AnalyzeForwardUse
     case SILArgumentConvention::Indirect_In:
       return true;
     case SILArgumentConvention::Indirect_In_Guaranteed:
+    case SILArgumentConvention::Indirect_In_CXX:
```
Comment (j-hui) [inline lib/SILOptimizer/Transforms/CopyForwarding.cpp:344]: Just to help me better understand this patch, because I don't see this case being defined in this patch, and the `default` case is `llvm_unreachable`.

Does this mean that the `Indirect_In_Cxx` case was not possible prior to this patch? (I'm guessing it's the additions to `lib/SIL/IR/SILFunctionType.cpp` that make this case possible?)

**Review by j-hui — APPROVED** [review]
I left some questions/suggestions for the test, but LGTM overall

File: lib/SILOptimizer/Transforms/CopyForwarding.cpp (hunk 5 above)
Comment (Xazax-hun) [reply lib/SILOptimizer/Transforms/CopyForwarding.cpp:344]: I hit the unreachable assertion with the test case I added. My suspicion is that it was possible to trigger this even before my patch we just did not run into it with an assertions enabled compiler.

File: test/Interop/Cxx/reference/Inputs/module.modulemap (hunk 4 above)
Comment (Xazax-hun) [reply test/Interop/Cxx/reference/Inputs/module.modulemap:6]: In C++ we call move/copy constructors special member functions: https://en.wikipedia.org/wiki/Special_member_functions

File: test/Interop/Cxx/reference/Inputs/print-special-members.h (hunk 3 above)
Comment (Xazax-hun) [reply test/Interop/Cxx/reference/Inputs/print-special-members.h:15]: No, we do not import the copy constructor as an initializer into Swift. Users cannot invoke them directly.

File: test/Interop/Cxx/reference/rvalue-reference.swift (hunk 2 above)
Comment (Xazax-hun) [reply test/Interop/Cxx/reference/rvalue-reference.swift]: I split it up in 4.

File: test/Interop/Cxx/reference/rvalue-reference.swift (hunk 1 above)
Comment (Xazax-hun) [reply test/Interop/Cxx/reference/rvalue-reference.swift]: Updated the prefixes. `-fno-elide-constructors` is a Clang flag right? Here, the copies are created within Swift, so I would not expect it to make any difference. I think the main differences between optimized and non-optimized code is coming from the optimized version inlining the function defined in Swift so we no longer need some of the copies.

**Comment by Xazax-hun** [comment]
@swift-ci please smoke test
