### PR TITLE
Fix RelBase indexing with composite types

### LINKED ISSUE #56255: [SR-13857] indexstore missing references for superclass / protocol when using composition
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13857      |
   |Radar             | rdar://problem/71447059         |
   |Original Reporter | @keith      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164964011-bef2f852-beb1-403b-baf2-8bdad38e9fa2.gz)

      
<details>
  <summary>Environment</summary>

Xcode 12.2 (12B45b)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Source Tooling    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   md5: 3d2406440cd5302076477f42903a56d5

  </details>

**Issue Description:**

With this code:

```swift
class ZZ1 {}
typealias BaseAlias = ZZ1 & Protocol
protocol Protocol {}

class Subclass: BaseAlias {}
```

The index store produced by building does not contain references from Subclass to ZZ1 as the superclass, or Protocol. This causes Xcode to not display the superclasses / protocol connections in the UI, and also impacts custom tooling built on index store data.

The difference is specifically a few symbols. With this code:

```swift
class ZZ1 {}
typealias BaseAlias = ZZ1 & Protocol
protocol Protocol {}

class Subclass: ZZ1 {}
```

You have this (normalized for display) reference which is missing when building the original snippet: `s:10superclass3ZZ1C baseOf s:10superclass8SubclassC`

If you use this code:

```swift
class ZZ1 {}
typealias BaseAlias = ZZ1
protocol Protocol {}

class Subclass: BaseAlias, Protocol {}
```

You end up with both the reference to the superclass, and a protocol reference: `s:10superclass8ProtocolP baseOf s:10superclass8SubclassC`.

Attached are the screenshots of how this ends up affecting Xcode's UI

### PR DESCRIPTION
**Pull request by keith**
Previously the index data differed when using `Foo, Bar` vs `Foo & Bar`.

Fixes https://github.com/apple/swift/issues/56255

### CODE REVIEW

**Comment by keith** [comment]
@swift-ci please test

File: test/Index/conformances.swift [hunk 1]
```diff
@@ -79,6 +79,12 @@ class SubMultiConf: BaseMultiConf,P2,P1,P3 { // CHECK: [[@LINE]]:7 | class/Swift
   // CHECK-NOT: [[@LINE-13]]:7 | instance-method
 }
 
+class CompositionType: BaseMultiConf & P1 { // CHECK: [[@LINE]]:7 | class/Swift | CompositionType | [[CompositionType_USR:.*]] | Def
```
Comment (bnbarham) [inline test/Index/conformances.swift:82]: Could you also add a test for a typealias? We'll still be missing those relations IIUC, but it seems reasonable to also handle. The relations should be implicit for that case though.

`reportRelatedTypeRef` currently adds a relation for the underlying type of a typealias if it's a nominal type, but not otherwise. We'd need an extra `isImplicit` on `reportRelatedTypeRef`, but seems like we could handle `CompositionTypeRepr` in there rather than on `reportInheritedTypeRefs` - then the `TypeAliasDecl` would just call `reportRelatedTypeRef` again with the underlying type and `isImplicit` set.

**Review by bnbarham — COMMENTED** [review]
Thanks for looking into this Keith :)!

File: test/Index/conformances.swift (hunk 1 above)
Comment (keith) [reply test/Index/conformances.swift:82]: thanks for the pointer, new version here has support for this and tests for it. the gist is what you said with 2 other required changes:

1. I had to pass through the location where the annotation should be, since that would otherwise use the declaration location
2. I handled similar logic in `visitDeclReference` to get the same behavior there, and for recursive typealiases

**Comment by keith** [comment]
@swift-ci please test

File: lib/Index/Index.cpp [hunk 2]
```diff
@@ -1378,20 +1383,37 @@ bool IndexSwiftASTWalker::reportInheritedTypeRefs(ArrayRef<InheritedEntry> Inher
...
+    return true;
+  } else if (auto *declRefTR = dyn_cast_or_null<DeclRefTypeRepr>(Ty.getTypeRepr())) {
+    SourceLoc IdLoc = Loc.value_or(declRefTR->getLoc());
     NominalTypeDecl *NTD = nullptr;
-    bool isImplicit = false;
+    bool isImplicit = Implicit;
     if (auto *VD = declRefTR->getBoundDecl()) {
       if (auto *TAD = dyn_cast<TypeAliasDecl>(VD)) {
         IndexSymbol Info;
+        Info.roles |= Relations;
```
Comment (keith) [inline lib/Index/Index.cpp:1402]: this can be removed depending on the outcome here https://github.com/apple/swift/pull/64999/files#r1172917919 but that would mean the typealias wouldn't be considered the base of anything

**Comment by keith** [comment]
@swift-ci please test

File: lib/Index/Index.cpp (hunk 2 above)
Comment (bnbarham) [reply lib/Index/Index.cpp:1402]: I commented there, but IMO that makes sense to me.

**Review by bnbarham — COMMENTED** [review]
Thanks again Keith!

File: lib/Index/Index.cpp [hunk 3]
```diff
@@ -1378,20 +1383,37 @@ bool IndexSwiftASTWalker::reportInheritedTypeRefs(ArrayRef<InheritedEntry> Inher
   return true;
 }
 
-bool IndexSwiftASTWalker::reportRelatedTypeRef(const TypeLoc &Ty, SymbolRoleSet Relations, Decl *Related) {
-  if (auto *declRefTR = dyn_cast_or_null<DeclRefTypeRepr>(Ty.getTypeRepr())) {
-    SourceLoc IdLoc = declRefTR->getLoc();
+bool IndexSwiftASTWalker::reportRelatedTypeRef(const TypeLoc &Ty, SymbolRoleSet Relations,
+                                               Decl *Related, bool Implicit, const Optional<SourceLoc> Loc) {
```
[the remark this answers is not in the document]
Comment (keith) [reply lib/Index/Index.cpp:1387]: I actually found the need for const when I accidentally typed `Loc = IdLoc` instead of the other way around and it compiled, w/ const it doesn't anymore. Is that a reasonable use of const? Will add docs!

[the remark this answers is not in the document]
Comment (bnbarham) [reply lib/Index/Index.cpp:1387]: I suppose it's one use, I don't often see it being used like that though. Ie. it being on a value rather than a ref was fairly surprising to me.

[the remark this answers is not in the document]
Comment (keith) [reply lib/Index/Index.cpp]: Sounds good, I removed it and added docs!

File: lib/Index/Index.cpp (hunk 2 above)
Comment (keith) [reply lib/Index/Index.cpp]: Sounds good, removed here

**Comment by keith** [comment]
@swift-ci please test

**Comment by keith** [comment]
@swift-ci please test Windows Platform

File: lib/Index/Index.cpp [hunk 4]
```diff
@@ -962,7 +966,18 @@ class IndexSwiftASTWalker : public SourceEntityWalker {
...
+  ///
+  /// NOTE: If the dependent type is a typealias, report the underlying types as well.
+  ///
+  /// \param Ty The type being referenced.
+  /// \param Relations The relationship between the referenced type and the passed Decl.
+  /// \param Related The Decl that is referencing the type.
+  /// \param isImplicit Whether the reference is implicit, such as for a typealias' underlying type.
+  /// \param Loc The location of the reference, otherwise the location of the TypeLoc is used.
+  bool reportRelatedTypeRef(const TypeLoc &Ty, SymbolRoleSet Relations, Decl *Related,
+                            bool isImplicit=false, Optional<SourceLoc> Loc=Optional<SourceLoc>());
```
Comment (bnbarham) [inline lib/Index/Index.cpp:980]:
```suggestion
                            bool isImplicit=false, Optional<SourceLoc> Loc = {});
```
If you realllllllllly want to keep the Optional.

File: lib/Index/Index.cpp [hunk 5]
```diff
@@ -1378,20 +1393,36 @@ bool IndexSwiftASTWalker::reportInheritedTypeRefs(ArrayRef<InheritedEntry> Inher
...
 }
 
-bool IndexSwiftASTWalker::reportRelatedTypeRef(const TypeLoc &Ty, SymbolRoleSet Relations, Decl *Related) {
-  if (auto *declRefTR = dyn_cast_or_null<DeclRefTypeRepr>(Ty.getTypeRepr())) {
-    SourceLoc IdLoc = declRefTR->getLoc();
+bool IndexSwiftASTWalker::reportRelatedTypeRef(const TypeLoc &Ty, SymbolRoleSet Relations,
+                                               Decl *Related, bool Implicit, Optional<SourceLoc> Loc) {
+  if (auto *composite = llvm::dyn_cast_or_null<CompositionTypeRepr>(Ty.getTypeRepr())) {
+    SourceLoc IdLoc = Loc.value_or(composite->getSourceLoc());
+    for (auto *Type : composite->getTypes())
```
Comment (bnbarham) [inline lib/Index/Index.cpp:1400]: I'm all for simple `if... return` without `{}`, but prefer having them around `for`. Not sure what the LLVM style guide says there, not that we *really* follow it anyway 😅

**Review by bnbarham — APPROVED** [review]
Nice 👍

File: lib/Index/Index.cpp (hunk 4 above)
Comment (keith) [reply lib/Index/Index.cpp]: ah sorry i lost the thread on that in the const convo, removed

**Comment by keith** [comment]
@swift-ci please test

File: lib/Index/Index.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (akyrtzi) [reply lib/Index/Index.cpp]: > I actually found the need for const when I accidentally typed Loc = IdLoc instead of the other way around and it compiled, w/ const it doesn't anymore. Is that a reasonable use of const?

Just a side-note, it'd be great if all value parameters in C++ were "const" (like in Swift) or LLVM/Swift coding conventions mandated making them `const` everywhere, but since that is not the case, making one value parameter `const` does seem surprising and "out-of-place" in this codebase.

**Comment by keith** [comment]
@swift-ci please test and merge

**Comment by keith** [comment]
@swift-ci please test and merge

**Comment by keith** [comment]
@swift-ci please test and merge

**Comment by keith** [comment]
https://github.com/apple/swift/pull/65550
