### PR TITLE
Fix missing indexing data when using Self initializer

### LINKED ISSUE #64686: Index data incomplete when using `Self` to initialize a type
With this code:

```swift
// Module0
struct Foo {
    init(bar: String) {}
}

extension Foo {
    static func baz() -> Self {
        Self(bar: "")
    }
}
```

The index data does not correctly tie `Self` or `(bar:` in the extension function to the actual locations. This is easiest to visualize with [indexutil-annotate](https://github.com/lyft/swift-index-store/tree/main/Sources/indexutil-annotate):

```swift
// Module0
/*
       struct=Foo=usr is s:7Module03FooV
       v  */
struct Foo {
    /*
    constructor=init(bar:)=usr is s:7Module03FooV3barACSS_tcfc
    |    parameter=bar=usr is s:7Module03FooV3barACSS_tcfcADL_SSvp
    |    |    struct=String=usr is s:SS
    v    v    v  */
    init(bar: String) {}
}

/*
          struct=Foo=usr is s:7Module03FooV
          extension.swiftExtensionOfStruct=Foo=usr is s:e:s:7Module03FooV3bazACyFZ
          v  */
extension Foo {
    /*
                staticMethod=baz()=usr is s:7Module03FooV3bazACyFZ
                v  */
    static func baz() -> Self {
        Self(bar: "")
    }
}
```

If you replace `Self` with the explicit type `Foo` you get what I would expect:

```swift
// Module0
/*
       struct=Foo=usr is s:7Module03FooV
       v  */
struct Foo {
    /*
    constructor=init(bar:)=usr is s:7Module03FooV3barACSS_tcfc
    |    parameter=bar=usr is s:7Module03FooV3barACSS_tcfcADL_SSvp
    |    |    struct=String=usr is s:SS
    v    v    v  */
    init(bar: String) {}
}

/*
          struct=Foo=usr is s:7Module03FooV
          extension.swiftExtensionOfStruct=Foo=usr is s:e:s:7Module03FooV3bazACyFZ
          v  */
extension Foo {
    /*
                staticMethod=baz()=usr is s:7Module03FooV3bazACyFZ
                v  */
    static func baz() -> Self {
        /*
        struct=Foo=usr is s:7Module03FooV
        constructor=init(bar:)=usr is s:7Module03FooV3barACSS_tcfc
        v  */
        Foo(bar: "")
    }
}
```

**Steps to reproduce**
Using this project: [selfnoindex.zip](https://github.com/apple/swift/files/11093712/selfnoindex.zip) and [`indexutil-annotate`](https://github.com/lyft/swift-index-store/tree/main/Sources/indexutil-annotate):

1. `swift build`
2. `indexutil-annotate .build/debug/index/store/ Sources/Module0/Module0.swift`

**Expected behavior**

The index data should have valid locations for `Self` and the initializer call. This also appears to affect Xcode where you cannot command+click on `Self` to jump to `Foo` (although maybe that's unrelated)

**Environment**
- Swift compiler version info 5.7.2
- Xcode version info 14.2.14C18

### PR DESCRIPTION
**Pull request by keith**
Fixes: https://github.com/apple/swift/issues/64686

### CODE REVIEW

**Comment by keith** [comment]
@swift-ci please test

File: test/Index/index_self.swift [hunk 1]
```diff
@@ -0,0 +1,13 @@
+// RUN: %target-swift-ide-test -print-indexed-symbols -source-filename %s | %FileCheck %s
+
+struct Foo {
+  init() {} // CHECK: [[@LINE]]:3 | constructor/Swift | init() | [[init_USR:.*]] | Def,RelChild | rel: 1
+
+  static func bar() -> Self {
```
Comment (keith) [inline test/Index/index_self.swift:6]: `Self` in this context also isn't indexed yet, I figured that could potentially be done as a follow up. I also thing that one is a bit less important since the type it's referencing will always have another reference in the same file, where the initializer being referenced could be in another file

**Comment by keith** [comment]
> The only thing I'm not sure about this is if there is another time where things could be this same shape

turns out just using the type's name directly is the same shape, so I need to figure out how to narrow it down

**Comment by keith** [comment]
There's actually no difference in the AST (at least via -dump-ast) in that case, so I think I do have to solve this somewhere else

**Comment by keith** [comment]
@swift-ci please test

**Comment by keith** [comment]
@swift-ci please test

**Comment by keith** [comment]
@swift-ci please test macOS Platform

**Review by ahoppen — APPROVED** [review]
Looks reasonable to me.

File: lib/Index/Index.cpp [hunk 2]
```diff
@@ -856,6 +856,8 @@ class IndexSwiftASTWalker : public SourceEntityWalker {
 
     if (Data.isImplicit)
       Info.roles |= (unsigned)SymbolRole::Implicit;
+    if (Data.Kind == SemaReferenceKind::DynamicMemberRef)
+      Info.roles |= (unsigned)SymbolRole::Dynamic;
```
Comment (bnbarham) [inline lib/Index/Index.cpp:860]: It'd be great if this could be handled with `reportIsDynamicRef` instead so that we get the receiver type relations.

File: lib/IDE/Utils.cpp [hunk 3]
```diff
@@ -875,11 +879,15 @@ Expr *swift::ide::getBase(ArrayRef<Expr *> ExprStack) {
   Expr *ParentE = getContainingExpr(ExprStack, 1);
   if (ParentE && isa<FunctionConversionExpr>(ParentE)) {
     ParentE = getContainingExpr(ExprStack, 2);
+  } else if (ParentE && isa<MetatypeConversionExpr>(ParentE)) {
+    ParentE = getContainingExpr(ExprStack, 2);
   }
```
Comment (hamishknight) [inline lib/IDE/Utils.cpp:884]: I would merge these branches and just check for `ImplicitConversionExpr` instead. For completeness, we _probably_ ought to iterate up the stack if we encounter multiple `ImplicitConversionExpr`s, though I can't immediately think of a case where that happens, so I don't think it's crucial.

File: lib/IDE/SourceEntityWalker.cpp [hunk 4]
```diff
@@ -633,6 +633,17 @@ ASTWalker::PreWalkAction SemaAnnotator::walkToTypeReprPre(TypeRepr *T) {
                         ReferenceMetaData(SemaReferenceKind::TypeRef, None));
       return Action::StopIf(!Continue);
     }
+  } else if (auto FT = dyn_cast<FixedTypeRepr>(T)) {
+    ValueDecl *VD = FT->getType()->getAnyGeneric();
+    if (auto DT = FT->getType()->getAs<DynamicSelfType>())
+      VD = DT->getSelfType()->getAnyGeneric();
+
+    if (VD) {
+      auto Data = ReferenceMetaData(SemaReferenceKind::TypeRef, None, /*isImplicit=*/true);
```
Comment (hamishknight) [inline lib/IDE/SourceEntityWalker.cpp:642]: It's a shame that we'll be marking `Self` as implicit here, we ought to fix that in the parser by having it produce a proper TypeRepr instead of the current hack. That being said, we could potentially work around that issue here by checking if the parent `TypeExpr` is implicit or not (the ASTWalker tracks the `Parent` node during its walk).

File: test/Index/roles.swift [hunk 5]
```diff
@@ -336,7 +336,7 @@ extension ExtendMe where Self: Whatever {}
 
 var anInstance = AClass(x: 1)
 // CHECK: [[@LINE-1]]:18 | class/Swift | AClass | s:14swift_ide_test6AClassC | Ref,RelCont | rel: 1
-// CHECK: [[@LINE-2]]:18 | constructor/Swift | init(x:) | s:14swift_ide_test6AClassC1xACSi_tcfc | Ref,Call,RelCont | rel: 1
+// CHECK: [[@LINE-2]]:18 | constructor/Swift | init(x:) | s:14swift_ide_test6AClassC1xACSi_tcfc | Ref,Call,Dyn,RelCont | rel: 1
```
Comment (hamishknight) [inline test/Index/roles.swift:339]: Hmm, that doesn't seem right to me, unless the `init` is marked dynamic, there should be no dynamic dispatch here.

**Review by hamishknight — CHANGES_REQUESTED** [review]
Thanks for fixing this!

File: lib/Index/Index.cpp (hunk 2 above)
Comment (keith) [reply lib/Index/Index.cpp]: we worked on this offline and decided to punt on it since it also marks standard class initializers as dynamic. I will submit a follow up change as an example of how it could work

File: lib/IDE/Utils.cpp [hunk 6]
```diff
@@ -875,11 +879,15 @@ Expr *swift::ide::getBase(ArrayRef<Expr *> ExprStack) {
...
   Expr *Base = nullptr;
 
   if (auto DSE = dyn_cast_or_null<DotSyntaxCallExpr>(ParentE))
     Base = DSE->getBase();
+  else if (auto DSE = dyn_cast_or_null<ConstructorRefCallExpr>(ParentE))
+    Base = DSE->getDirectCallee();
```
[the remark this answers is not in the document]
Comment (keith) [reply lib/IDE/Utils.cpp]: sorry i just reworked this because of other issues hit here

File: lib/IDE/Utils.cpp (hunk 3 above)
Comment (keith) [reply lib/IDE/Utils.cpp]: this one was removed as well

File: test/Index/roles.swift (hunk 5 above)
Comment (keith) [reply test/Index/roles.swift]: yea, this was the core reason we decided to drop this for now

File: lib/IDE/SourceEntityWalker.cpp (hunk 4 above)
Comment (keith) [reply lib/IDE/SourceEntityWalker.cpp:642]: hrm I guess I hadn't felt too bad about `Self` being implicit in this case:

```swift
    /*
    class=Bar=s:3foo3BarC=reference, implicit, containedBy
    constructor=init()=s:3foo3BarCACycfc=reference, call, implicit, calledBy, containedBy
    v  */
    Self()
```

just taking that value literally since `Bar` isn't explicitly written there 🤔

File: lib/IDE/Utils.cpp [hunk 7]
```diff
@@ -853,6 +853,10 @@ bool swift::ide::isBeingCalled(ArrayRef<Expr *> ExprStack) {
       if (CRCE->getBase() == Target)
         return true;
     }
+    if (auto *CRCE = dyn_cast<ConstructorRefCallExpr>(AE->getFn()))
+      if (auto *MCE = dyn_cast<MetatypeConversionExpr>(CRCE->getBase()))
+        if (MCE->getSubExpr() == Target)
+          return true;
```
[the remark this answers is not in the document]
Comment (keith) [reply lib/IDE/Utils.cpp]: the problem is the slight difference in casing `AE->getFn` to `ConstructorRefCallExpr` instead of just `AE`. Good call on using `ImplicitConversionExpr` instead

File: lib/IDE/SourceEntityWalker.cpp (hunk 4 above)
Comment (keith) [reply lib/IDE/SourceEntityWalker.cpp:642]: I wonder if instead we should drop the implicit bit all together for both here? if anything is implicit it feels like it's the type, but the constructor isn't considered implicit in the other case:

```swift
/*
       constructor=init()=s:3foo3BarVACycfc=definition, implicit, childOf
       struct=Bar=s:3foo3BarV=definition
       v  */
struct Bar {
  /*
              staticMethod=foo()=s:3foo3BarVAaCyFZ=definition, childOf
              v  */
  static func foo() -> Self {
    /*
    struct=Bar=s:3foo3BarV=reference, containedBy
    constructor=init()=s:3foo3BarVACycfc=reference, call, calledBy, containedBy
    v  */
    Bar()
  }
  /*
              staticMethod=baz()=s:3foo3BarV3bazACyFZ=definition, childOf
              v  */
  static func baz() -> Self {
    /*
    struct=Bar=s:3foo3BarV=reference, implicit, containedBy
    constructor=init()=s:3foo3BarVACycfc=reference, call, implicit, calledBy, containedBy
    v  */
    Self()
  }
}```

Comment (bnbarham) [reply lib/IDE/SourceEntityWalker.cpp:642]: I've always taken `implicit` to mean "not spelt here". @akyrtzi / @benlangmuir in case I've had that wrong this whole time 😅

Comment (bnbarham) [reply lib/IDE/SourceEntityWalker.cpp:642]: So FWIW the current output for the `init` case is:
```
1:8 | struct/Swift | Foo | s:14swift_ide_test3FooV | Def | rel: 0
1:8 | constructor/Swift | init() | s:14swift_ide_test3FooVACycfc | Def,Impl,RelChild | rel: 1
```
ie. implicit constructor. Whether that's intended or not... I'm not sure. It could certainly just be because the expression is implicit.

Having said that, my impression has always been what I said above - ie. "not spelt here". I'm also not sure what other meaning would be useful in terms of the index data. Generally it seems useful to know whether a reference is explicitly spelt (eg. should participate in a rename) vs a reference that may be known by the compiler, but isn't actually in the source explicitly.

So my preference here would be to keep it as implicit.

File: lib/IDE/Utils.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (hamishknight) [reply lib/IDE/Utils.cpp]: Ah yeah, presumably the issue is the `isImplicit` check above? I think both cases should be able to use `AE->getFn()`, as a `ConstructorRefCallExpr` can only be used as the function of another call (we build an autoclosure for the unapplied case).

File: lib/IDE/Utils.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (hamishknight) [reply lib/IDE/Utils.cpp]: FYI filed https://github.com/apple/swift/issues/65614 for the above example

File: lib/IDE/Utils.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (keith) [reply lib/IDE/Utils.cpp]: nice, done

File: lib/IDE/SourceEntityWalker.cpp (hunk 4 above)
Comment (keith) [reply lib/IDE/SourceEntityWalker.cpp]: I pushed an option here for making the type implicit but the ctor call explicit, but it would be nice to have a cleaner approach if you all have any ideas

Comment (bnbarham) [reply lib/IDE/SourceEntityWalker.cpp]: > @bnbarham That's the index data for the implicit memberwise init decl right? That should definitely be implicit :)

Heh, indeed it was :(. The reference is not implicit:
```
5:7 | constructor/Swift | init() | s:14swift_ide_test3FooVACycfc | Ref,Call,RelCall,RelCont | rel: 1
```

We discussed this offline. We should consider `Self` similar to the typealias case. Ie. the type reference should be implicit, but the constructor should be explicit.

Comment (keith) [reply lib/IDE/SourceEntityWalker.cpp]: sounds good, this PR currently solves that with a new bool, definitely open to better ideas for how to track that

Comment (bnbarham) [reply lib/IDE/SourceEntityWalker.cpp]: None from me unfortunately. Any thoughts @hamishknight?

File: lib/IDE/Utils.cpp [hunk 8]
```diff
@@ -849,9 +849,12 @@ bool swift::ide::isBeingCalled(ArrayRef<Expr *> ExprStack) {
     auto *AE = dyn_cast<ApplyExpr>(E);
     if (!AE || AE->isImplicit())
       continue;
-    if (auto *CRCE = dyn_cast<ConstructorRefCallExpr>(AE)) {
+    if (auto *CRCE = dyn_cast<ConstructorRefCallExpr>(AE->getFn())) {
       if (CRCE->getBase() == Target)
         return true;
+      if (auto *MCE = dyn_cast<ImplicitConversionExpr>(CRCE->getBase()))
+        if (MCE->getSubExpr() == Target)
+          return true;
```
Comment (hamishknight) [inline lib/IDE/Utils.cpp:857]: IMO this would be better written as:

```suggestion
      auto *Base = CRCE->getBase();
      while (auto *ICE = dyn_cast<ImplicitConversionExpr>(Base))
        Base = ICE->getSubExpr();
      if (Base == Target)
        return true;
```

File: lib/IDE/SourceEntityWalker.cpp (hunk 4 above)
Comment (hamishknight) [reply lib/IDE/SourceEntityWalker.cpp]: Yeah I think that's fine for now, I think ideally we'd try and walk the decl ref separately (or mark it explicit as @keith suggested), which I believe should avoid the need for that

**Review by hamishknight — APPROVED** [review]

**Comment by keith** [comment]
@swift-ci please test and merge
