### PR TITLE
[AccessRequests] Allow Init accessor to be `internal`

### LINKED ISSUE #71578: Init Accessors not found by linker when used in another file
### Description

When I try to use an [Init Accessor](https://github.com/apple/swift-evolution/blob/main/proposals/0400-init-accessors.md) in a file different from where they have been defined, my Swift Package stops compiling:

```log
ld: Undefined symbols:
  SwiftBugReport.Angle.radians.init : Swift.Double, referenced from:
      SwiftBugReport.Angle.init(radians: Swift.Double) -> SwiftBugReport.Angle in SwiftBugReport.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Reproduction

Taking example from <https://github.com/apple/swift-evolution/blob/main/proposals/0400-init-accessors.md#proposed-solution>:

```swift
//  File1.swift
import Foundation

public struct Angle {
  public var degrees: Double
  public var radians: Double {
    @storageRestrictions(initializes: degrees)
    init(initialValue)  {
      degrees = initialValue * 180 / .pi
    }

    get { degrees * .pi / 180 }
    set { degrees = newValue * 180 / .pi }
  }

  public init(degrees: Double) {
    self.degrees = degrees
  }
}
```

If we just put `init(radians:)` in another file, `ld` doesn't find `Angle.radians.init : Swift.Double` anymore and the build crashes.

```swift
//  File2.swift
import Foundation

extension Angle {
  public init(radians: Double) {
    self.radians = radians
  }
}
```

### Stack dump

```text
Showing All Messages

Prepare build
note: Removed stale file '/Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Intermediates.noindex/SwiftBugReport.build/Debug-iphoneos/SwiftBugReport.build/Objects-normal/arm64/SwiftBugReport.o'

note: Removed stale file '/Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Intermediates.noindex/SwiftBugReport.build/Debug-iphoneos/SwiftBugReport.build/Objects-normal/arm64/SwiftBugReport.swiftconstvalues'



Removed stale file '/Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Intermediates.noindex/SwiftBugReport.build/Debug-iphoneos/SwiftBugReport.build/Objects-normal/arm64/SwiftBugReport.o'


Removed stale file '/Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Intermediates.noindex/SwiftBugReport.build/Debug-iphoneos/SwiftBugReport.build/Objects-normal/arm64/SwiftBugReport.swiftconstvalues'


ComputeTargetDependencyGraph

note: Building targets in dependency order
note: Target dependency graph (3 targets)
    Target 'SwiftBugReportTests' in project 'SwiftBugReport'
        ➜ Explicit dependency on target 'SwiftBugReport' in project 'SwiftBugReport'
    Target 'SwiftBugReport' in project 'SwiftBugReport'
        ➜ Explicit dependency on target 'SwiftBugReport' in project 'SwiftBugReport'
    Target 'SwiftBugReport' in project 'SwiftBugReport' (no dependencies)

Building targets in dependency order

Target dependency graph (3 targets)

GatherProvisioningInputs

CreateBuildDescription

Build description signature: a61ce25f1e515067416dde88ad559544
Build description path: /Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Intermediates.noindex/XCBuildData/a61ce25f1e515067416dde88ad559544.xcbuilddata

[...]

SwiftDriverJobDiscovery normal arm64 Compiling SwiftBugReportTests.swift (in target 'SwiftBugReportTests' from project 'SwiftBugReport')

SwiftDriver\ Compilation SwiftBugReportTests normal arm64 com.apple.xcode.tools.swift.compiler (in target 'SwiftBugReportTests' from project 'SwiftBugReport')
    cd /Users/xxxx/SwiftBugReport
    builtin-Swift-Compilation -- /Applications/Xcode-15.2.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -module-name SwiftBugReportTests -Onone -enforce-exclusivity\=checked @/Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Intermediates.noindex/SwiftBugReport.build/Debug-iphoneos/SwiftBugReportTests.build/Objects-normal/arm64/SwiftBugReportTests.SwiftFileList -DSWIFT_PACKAGE -DDEBUG -DXcode -sdk /Applications/Xcode-15.2.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk -target arm64-apple-ios12.0 -g -module-cache-path /Users/xxxx/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -Xfrontend -serialize-debugging-options -profile-coverage-mapping -profile-generate -enable-testing -index-store-path /Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Index.noindex/DataStore -swift-version 5 -I /Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Products/Debug-iphoneos -I /Applications/Xcode-15.2.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/lib -F /Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Products/Debug-iphoneos/PackageFrameworks -F /Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Products/Debug-iphoneos -F /Applications/Xcode-15.2.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -F /Applications/Xcode-15.2.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk/Developer/Library/Frameworks -parse-as-library -c -j12 -enable-batch-mode -incremental -Xcc -ivfsstatcache -Xcc /Users/xxxx/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphoneos17.2-21C52-d4853233c81beb1da90379997a312ef0.sdkstatcache -output-file-map /Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Intermediates.noindex/SwiftBugReport.build/Debug-iphoneos/SwiftBugReportTests.build/Objects-normal/arm64/SwiftBugReportTests-OutputFileMap.json -use-frontend-parseable-output -save-temps -no-color-diagnostics -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Intermediates.noindex/SwiftBugReport.build/Debug-iphoneos/SwiftBugReportTests.build/Objects-normal/arm64/SwiftBugReportTests.swiftmodule -validate-clang-modules-once -clang-build-session-file /Users/xxxx/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -Xfrontend -package-name -Xfrontend swiftbugreport -emit-const-values -Xfrontend -const-gather-protocols-file -Xfrontend /Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Intermediates.noindex/SwiftBugReport.build/Debug-iphoneos/SwiftBugReportTests.build/Objects-normal/arm64/SwiftBugReportTests_const_extract_protocols.json -Xcc -I/Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Products/Debug-iphoneos/include -Xcc -I/Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Intermediates.noindex/SwiftBugReport.build/Debug-iphoneos/SwiftBugReportTests.build/DerivedSources-normal/arm64 -Xcc -I/Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Intermediates.noindex/SwiftBugReport.build/Debug-iphoneos/SwiftBugReportTests.build/DerivedSources/arm64 -Xcc -I/Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Intermediates.noindex/SwiftBugReport.build/Debug-iphoneos/SwiftBugReportTests.build/DerivedSources -Xcc -DSWIFT_PACKAGE -Xcc -DDEBUG\=1 -working-directory /Users/xxxx/SwiftBugReport -experimental-emit-module-separately -disable-cmo

WriteAuxiliaryFile /Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Intermediates.noindex/SwiftBugReport.build/Debug-iphoneos/SwiftBugReportTests.build/Objects-normal/arm64/SwiftBugReportTests.LinkFileList (in target 'SwiftBugReportTests' from project 'SwiftBugReport')
    cd /Users/xxxx/SwiftBugReport
    write-file /Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Intermediates.noindex/SwiftBugReport.build/Debug-iphoneos/SwiftBugReportTests.build/Objects-normal/arm64/SwiftBugReportTests.LinkFileList

Ld /Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Products/Debug-iphoneos/SwiftBugReportTests.xctest/SwiftBugReportTests normal (in target 'SwiftBugReportTests' from project 'SwiftBugReport')
    cd /Users/xxxx/SwiftBugReport
    /Applications/Xcode-15.2.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -Xlinker -reproducible -target arm64-apple-ios12.0 -bundle -isysroot /Applications/Xcode-15.2.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk -O0 -L/Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Intermediates.noindex/EagerLinkingTBDs/Debug-iphoneos -L/Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Products/Debug-iphoneos -L/Applications/Xcode-15.2.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/lib -F/Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Intermediates.noindex/EagerLinkingTBDs/Debug-iphoneos -F/Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Products/Debug-iphoneos/PackageFrameworks -F/Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Products/Debug-iphoneos -F/Applications/Xcode-15.2.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -iframework /Applications/Xcode-15.2.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -iframework /Applications/Xcode-15.2.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk/Developer/Library/Frameworks -filelist /Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Intermediates.noindex/SwiftBugReport.build/Debug-iphoneos/SwiftBugReportTests.build/Objects-normal/arm64/SwiftBugReportTests.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker /Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Products/Debug-iphoneos/PackageFrameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/../Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Intermediates.noindex/SwiftBugReport.build/Debug-iphoneos/SwiftBugReportTests.build/Objects-normal/arm64/SwiftBugReportTests_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -debug_variant -fobjc-link-runtime -fprofile-instr-generate -L/Applications/Xcode-15.2.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Intermediates.noindex/SwiftBugReport.build/Debug-iphoneos/SwiftBugReportTests.build/Objects-normal/arm64/SwiftBugReportTests.swiftmodule -Wl,-no_warn_duplicate_libraries -framework XCTest -Xlinker -dependency_info -Xlinker /Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Intermediates.noindex/SwiftBugReport.build/Debug-iphoneos/SwiftBugReportTests.build/Objects-normal/arm64/SwiftBugReportTests_dependency_info.dat -o /Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Products/Debug-iphoneos/SwiftBugReportTests.xctest/SwiftBugReportTests -Xlinker -add_ast_path -Xlinker /Users/xxxx/Library/Developer/Xcode/DerivedData/SwiftBugReport-euwmnzzwnujrvucebxjwtxhzfmjr/Build/Intermediates.noindex/SwiftBugReport.build/Debug-iphoneos/SwiftBugReport.build/Objects-normal/arm64/SwiftBugReport.swiftmodule

ld: Undefined symbols:
  SwiftBugReport.Angle.radians.init : Swift.Double, referenced from:
      SwiftBugReport.Angle.init(radians: Swift.Double) -> SwiftBugReport.Angle in SwiftBugReport.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Undefined symbols:

Linker command failed with exit code 1 (use -v to see invocation)



Build failed    13/02/2024, 11:35    0.7 seconds
```

### Expected behavior

I would expect either to be able to use an Init Accessor in a separate file or receive a comprehensive compiler error message saying along the lines of "This is not possible, Init Accessors can only be used in the file where they have been declared" (if it's a known limitation).

### Environment

```txt
swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: x86_64-apple-macosx14.0
```

### Additional information

- I used a Swift Package, I don't know if it changes anything
- A simple workaround exists: moving the extension back in the same file (which means this crash is non-blocking)

### PR DESCRIPTION
**Pull request by li3zhen1**
- Disallow init accessors in extensions.
- Allow init accessor to be `internal`.

Resolves #71578

### CODE REVIEW

File: lib/SILGen/SILGenLValue.cpp [hunk 1]
```diff
@@ -3930,6 +3946,16 @@ LValue SILGenLValue::visitMemberRefExpr(MemberRefExpr *e,
     }
   }
   
+  // if we are trying to access an init accessor of a property out of the
+  // lexical type context, emit an error.
+  if (strategy.hasAccessor() && strategy.getAccessor() == AccessorKind::Init) {
+    AccessorDecl* initAccessorDecl = var->getOpaqueAccessor(AccessorKind::Init);
+    if (initAccessorDecl && !isInitAccessorAccessible(SGF, initAccessorDecl)) {
```
Comment (xedin) [inline lib/SILGen/SILGenLValue.cpp:3953]: I think this needs to happen during Sema, `Init` based strategy is only produced for immutable things and it should be possible to prevent that from happening, we have a few places were we pretend that property is mutable so the availability check should happen there.

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@li3zhen1 Sorry it took so long! Would you mind fixing the test-case that is failing or should I?

**Comment by xedin** [comment]
@swift-ci please test

File: lib/Parse/ParseDecl.cpp [hunk 2]
```diff
@@ -8497,8 +8497,12 @@ void Parser::ParsedAccessors::classify(Parser &P, AbstractStorageDecl *storage,
   }
 
   if (Init) {
-    if (!storage->getDeclContext()->getSelfNominalTypeDecl() ||
-        isa<SubscriptDecl>(storage)) {
+    if (storage->getDeclContext()->getContextKind() ==
```
Comment (slavapestov) [inline lib/Parse/ParseDecl.cpp:8500]: `if (isa<ExtensionDecl>(storage->getDeclContext())`

File: lib/AST/AccessRequests.cpp [hunk 3]
```diff
@@ -65,8 +65,8 @@ AccessLevelRequest::evaluate(Evaluator &evaluator, ValueDecl *D) const {
       // These are only needed to synthesize the setter.
       return AccessLevel::Private;
     case AccessorKind::Init:
-      // These are only called from designated initializers.
-      return AccessLevel::Private;
+      // These are only called from within the same module.
+      return std::min(storage->getFormalAccess(), AccessLevel::Internal);
```
Comment (slavapestov) [inline lib/AST/AccessRequests.cpp:69]: Why this change?

File: include/swift/AST/DiagnosticsParse.def [hunk 4]
```diff
@@ -2158,6 +2158,10 @@ ERROR(init_accessor_is_not_on_property,none,
       "init accessors could only be associated with properties",
       ())
 
+ERROR(init_accessor_is_not_in_the_primary_declaration,none,
+      "init accessors could only be declared in the primary declaration",
```
Comment (slavapestov) [inline include/swift/AST/DiagnosticsParse.def:2162]: "Cannot be declared inside an extension" maybe?

File: lib/Parse/ParseDecl.cpp [hunk 5]
```diff
@@ -8497,8 +8497,12 @@ void Parser::ParsedAccessors::classify(Parser &P, AbstractStorageDecl *storage,
...
+        DeclContextKind::ExtensionDecl) {
+      P.diagnose(Init->getLoc(),
+                 diag::init_accessor_is_not_in_the_primary_declaration);
+    } else if (!storage->getDeclContext()->getSelfNominalTypeDecl() ||
```
Comment (slavapestov) [inline lib/Parse/ParseDecl.cpp:8504]: `!storage->getDeclContext()->isTypeContext()`

File: lib/AST/AccessRequests.cpp (hunk 3 above)
Comment (xedin) [reply lib/AST/AccessRequests.cpp:69]: The init accessor should be accessible within the module but it's currently impossible to use it across different files in the module.

File: lib/Parse/ParseDecl.cpp (hunk 2 above)
Comment (xedin) [reply lib/Parse/ParseDecl.cpp]: Done

File: include/swift/AST/DiagnosticsParse.def (hunk 4 above)
Comment (xedin) [reply include/swift/AST/DiagnosticsParse.def]: Reworded this, thanks!

File: lib/Parse/ParseDecl.cpp (hunk 5 above)
Comment (xedin) [reply lib/Parse/ParseDecl.cpp]: Done!

**Comment by xedin** [comment]
@swift-ci please test
