### PR TITLE
[ConstraintSystem] Fix crash when diagnosing missing args in KeyPath application

### LINKED ISSUE #85942: Crash in Solution::getFunctionArgApplyInfo() because of missing overload
### Description

Compiler crashes will compiling the attached files

### Reproduction

Compile the attached files with
swiftc *.swift -o aoc

### Stack dump

```text
error: compile command failed due to signal 11 (use -v to see invocation)
main.swift:38:55: error: missing arguments for parameters 'maxSplits', 'omittingEmptySubsequences' in call
36 |         // pattern --> (3) (1,3) (2) (2,3) (0,2) (0,1)
37 |         let buttonsStr = pattern.split(separator: " ")
38 |         let buttons : [[Int]] = buttonsStr.map(\.split(separator: ",").compactMap(Int.init))
   |                                                       `- error: missing arguments for parameters 'maxSplits', 'omittingEmptySubsequences' in call
39 |         print(buttons)
40 |         

Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /Library/Developer/CommandLineTools/usr/bin/swift-frontend -frontend -c data.swift extensions.swift -primary-file main.swift -target arm64-apple-macosx26.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -stack-check -sdk /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -no-color-diagnostics -Xcc -fno-color-diagnostics -new-driver-path /Library/Developer/CommandLineTools/usr/bin/swift-driver -empty-abi-descriptor -no-auto-bridging-header-chaining -module-name main -disable-clang-spi -target-sdk-version 26.1 -target-sdk-name macosx26.1 -external-plugin-path /Library/Developer/Developer/usr/lib/swift/host/plugins#/Library/Developer/Developer/usr/bin/swift-plugin-server -external-plugin-path /Library/Developer/Developer/usr/local/lib/swift/host/plugins#/Library/Developer/Developer/usr/bin/swift-plugin-server -in-process-plugin-server-path /Library/Developer/CommandLineTools/usr/lib/swift/host/libSwiftInProcPluginServer.dylib -plugin-path /Library/Developer/CommandLineTools/usr/lib/swift/host/plugins -plugin-path /Library/Developer/CommandLineTools/usr/local/lib/swift/host/plugins -o /var/folders/y6/brbfc0px01726m2cw70nf5gw0000gn/T/TemporaryDirectory.9QgEuG/main-1.o
1.	Apple Swift version 6.2.1 (swiftlang-6.2.1.4.8 clang-1700.4.4.1)
2.	Compiling with effective version 5.10
3.	While evaluating request TypeCheckPrimaryFileRequest(source_file "main.swift")
4.	While evaluating request TypeCheckFunctionBodyRequest(main.(file).getData(str:)@main.swift:18:6)
5.	While type-checking statement at [main.swift:18:41 - line:44:1] RangeText="{
    var machines : [Machine] = []
    
    for s in str.split(separator: "\n") {
        
        let step1 = s.split(separator: " ")
        let firstInfo = step1[0]

        var g : [Bool] = []
        for i in 1..<(firstInfo.count) {
            g.append(firstInfo[i] == "#")
        }
        
        let endOfButton = s.firstIndex(of: "]")!
        let startJoltage = s.firstIndex(of: "{")!
        let patternRange = s.index(after: endOfButton)..<startJoltage
        let pattern = String(s[patternRange])

        // pattern --> (3) (1,3) (2) (2,3) (0,2) (0,1)
        let buttonsStr = pattern.split(separator: " ")
        let buttons : [[Int]] = buttonsStr.map(\.split(separator: ",").compactMap(Int.init))
        print(buttons)
        
    }
    
    return machines
"
6.	While type-checking statement at [main.swift:21:5 - line:41:5] RangeText="for s in str.split(separator: "\n") {
        
        let step1 = s.split(separator: " ")
        let firstInfo = step1[0]

        var g : [Bool] = []
        for i in 1..<(firstInfo.count) {
            g.append(firstInfo[i] == "#")
        }
        
        let endOfButton = s.firstIndex(of: "]")!
        let startJoltage = s.firstIndex(of: "{")!
        let patternRange = s.index(after: endOfButton)..<startJoltage
        let pattern = String(s[patternRange])

        // pattern --> (3) (1,3) (2) (2,3) (0,2) (0,1)
        let buttonsStr = pattern.split(separator: " ")
        let buttons : [[Int]] = buttonsStr.map(\.split(separator: ",").compactMap(Int.init))
        print(buttons)
        
    "
7.	While type-checking statement at [main.swift:21:41 - line:41:5] RangeText="{
        
        let step1 = s.split(separator: " ")
        let firstInfo = step1[0]

        var g : [Bool] = []
        for i in 1..<(firstInfo.count) {
            g.append(firstInfo[i] == "#")
        }
        
        let endOfButton = s.firstIndex(of: "]")!
        let startJoltage = s.firstIndex(of: "{")!
        let patternRange = s.index(after: endOfButton)..<startJoltage
        let pattern = String(s[patternRange])

        // pattern --> (3) (1,3) (2) (2,3) (0,2) (0,1)
        let buttonsStr = pattern.split(separator: " ")
        let buttons : [[Int]] = buttonsStr.map(\.split(separator: ",").compactMap(Int.init))
        print(buttons)
        
    "
8.	While type-checking declaration 0x9b6fdf5c0 (at main.swift:38:9)
9.	While type-checking expression at [main.swift:38:33 - line:38:92] RangeText="buttonsStr.map(\.split(separator: ",").compactMap(Int.init)"
10.	While type-checking-target starting at main.swift:38:44
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x000000010b3d9eb4 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x000000010b3d7844 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x000000010b3da4e0 SignalHandler(int, __siginfo*, void*) + 344
3  libsystem_platform.dylib 0x0000000188ca3744 _sigtramp + 56
4  swift-frontend           0x00000001063909e0 swift::constraints::Solution::getFunctionArgApplyInfo(swift::constraints::ConstraintLocator*) const + 976
5  swift-frontend           0x00000001063909e0 swift::constraints::Solution::getFunctionArgApplyInfo(swift::constraints::ConstraintLocator*) const + 976
6  swift-frontend           0x00000001063314ac swift::constraints::MissingArgumentsFailure::diagnoseAsError() + 496
7  swift-frontend           0x0000000106306f90 swift::constraints::AddMissingArguments::diagnoseForAmbiguity(llvm::ArrayRef<std::__1::pair<swift::constraints::Solution const*, swift::constraints::ConstraintFix const*>>) const + 188
8  swift-frontend           0x000000010638cb60 swift::constraints::ConstraintSystem::diagnoseAmbiguityWithFixes(llvm::SmallVectorImpl<swift::constraints::Solution>&) + 15928
9  swift-frontend           0x00000001063887f4 swift::constraints::ConstraintSystem::salvage() + 524
10 swift-frontend           0x00000001062d8830 swift::constraints::ConstraintSystem::solve(swift::constraints::SyntacticElementTarget&, swift::FreeTypeVariableBinding) + 1160
11 swift-frontend           0x00000001064f51d0 swift::TypeChecker::typeCheckTarget(swift::constraints::SyntacticElementTarget&, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>, swift::DiagnosticTransaction*) + 704
12 swift-frontend           0x00000001064f4dec swift::TypeChecker::typeCheckExpression(swift::constraints::SyntacticElementTarget&, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>, swift::DiagnosticTransaction*) + 420
13 swift-frontend           0x00000001064f6644 swift::TypeChecker::typeCheckBinding(swift::Pattern*&, swift::Expr*&, swift::DeclContext*, swift::Type, swift::PatternBindingDecl*, unsigned int, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 200
14 swift-frontend           0x00000001064f6860 swift::TypeChecker::typeCheckPatternBinding(swift::PatternBindingDecl*, unsigned int, swift::Type, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 292
15 swift-frontend           0x0000000106556228 (anonymous namespace)::DeclChecker::visit(swift::Decl*) + 5560
16 swift-frontend           0x000000010660d410 (anonymous namespace)::StmtChecker::typeCheckASTNode(swift::ASTNode&) + 1024
17 swift-frontend           0x0000000106613034 swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) + 288
18 swift-frontend           0x0000000106610694 bool (anonymous namespace)::StmtChecker::typeCheckStmt<swift::BraceStmt>(swift::BraceStmt*&) + 312
19 swift-frontend           0x000000010661312c swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) + 536
20 swift-frontend           0x0000000106612ddc bool (anonymous namespace)::StmtChecker::typeCheckStmt<swift::Stmt>(swift::Stmt*&) + 312
21 swift-frontend           0x000000010660d060 (anonymous namespace)::StmtChecker::typeCheckASTNode(swift::ASTNode&) + 80
22 swift-frontend           0x0000000106613034 swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) + 288
23 swift-frontend           0x0000000106610694 bool (anonymous namespace)::StmtChecker::typeCheckStmt<swift::BraceStmt>(swift::BraceStmt*&) + 312
24 swift-frontend           0x000000010660f14c swift::TypeCheckFunctionBodyRequest::evaluate(swift::Evaluator&, swift::AbstractFunctionDecl*) const + 2996
25 swift-frontend           0x0000000106a72a20 swift::TypeCheckFunctionBodyRequest::OutputType swift::Evaluator::getResultUncached<swift::TypeCheckFunctionBodyRequest, swift::TypeCheckFunctionBodyRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckFunctionBodyRequest>(swift::Evaluator&, swift::TypeCheckFunctionBodyRequest, swift::TypeCheckFunctionBodyRequest::OutputType)::'lambda'()>(swift::TypeCheckFunctionBodyRequest const&, swift::TypeCheckFunctionBodyRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckFunctionBodyRequest>(swift::Evaluator&, swift::TypeCheckFunctionBodyRequest, swift::TypeCheckFunctionBodyRequest::OutputType)::'lambda'()) + 688
26 swift-frontend           0x00000001069c2770 swift::AbstractFunctionDecl::getTypecheckedBody() const + 152
27 swift-frontend           0x0000000106666b78 swift::TypeCheckPrimaryFileRequest::evaluate(swift::Evaluator&, swift::SourceFile*) const + 912
28 swift-frontend           0x000000010666da80 swift::TypeCheckPrimaryFileRequest::OutputType swift::Evaluator::getResultUncached<swift::TypeCheckPrimaryFileRequest, swift::TypeCheckPrimaryFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckPrimaryFileRequest>(swift::Evaluator&, swift::TypeCheckPrimaryFileRequest, swift::TypeCheckPrimaryFileRequest::OutputType)::'lambda'()>(swift::TypeCheckPrimaryFileRequest const&, swift::TypeCheckPrimaryFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckPrimaryFileRequest>(swift::Evaluator&, swift::TypeCheckPrimaryFileRequest, swift::TypeCheckPrimaryFileRequest::OutputType)::'lambda'()) + 672
29 swift-frontend           0x0000000105415a0c bool llvm::function_ref<bool (swift::SourceFile&)>::callback_fn<swift::CompilerInstance::performSema()::$_0>(long, swift::SourceFile&) + 156
30 swift-frontend           0x000000010540f094 swift::CompilerInstance::forEachFileToTypeCheck(llvm::function_ref<bool (swift::SourceFile&)>) + 176
31 swift-frontend           0x000000010540ef28 swift::CompilerInstance::performSema() + 120
32 swift-frontend           0x0000000105016154 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 772
33 swift-frontend           0x0000000105015144 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 3580
34 swift-frontend           0x0000000104f96724 swift::mainEntry(int, char const**) + 5412
35 dyld                     0x00000001888d1d54 start + 7184
```

### Expected behavior

Should compile

### Environment

swift-driver version: 1.127.14.1 Apple Swift version 6.2.1 (swiftlang-6.2.1.4.8 clang-1700.4.4.1)
Target: arm64-apple-macosx26.0

### Additional information

[Day_10.zip](https://github.com/user-attachments/files/24071833/Day_10.zip)

### PR DESCRIPTION
**Pull request by AnirudhMathur12**
This patch fixes a compiler crash (Signal 11) where `getFunctionArgApplyInfo` blindly cast an expression to `CallExpr` without verification, and `CSDiagnostics` subsequently dereferenced a null result.

This occurred specifically when using a KeyPath expression (e.g. inside `.map`) that had argument labels missing. The diagnostic logic triggered on the KeyPath node, which is not a `CallExpr`, causing an assertion failure in debug builds and a segfault in release builds.

Resolves: #85942

### CODE REVIEW

File: lib/Sema/CSDiagnostics.cpp [hunk 1]
```diff
@@ -5286,7 +5286,11 @@ bool MissingArgumentsFailure::diagnoseAsError() {
   // foo(bar) // `() -> Void` vs. `(Int) -> Void`
   // ```
   if (locator->isLastElement<LocatorPathElt::ApplyArgToParam>()) {
-    auto info = *(getFunctionArgApplyInfo(locator));
+    auto info_ptr = getFunctionArgApplyInfo(locator);
```
Comment (xedin) [inline lib/Sema/CSDiagnostics.cpp]: I’d expect the fix here would be to adjust `getFunctionArgApplyInfo` to produce a result for key path application instead of null,  because locator points at the argument position.

**Review by xedin — CHANGES_REQUESTED** [review]
Thank you for the contribution! Please see my comment inline.

File: lib/Sema/CSDiagnostics.cpp (hunk 1 above)
Comment (anirudhmathur12) [reply lib/Sema/CSDiagnostics.cpp]: Since `getOverloadChoiceIfAvailable` returned `null` (which is why we reached this `else` block), we don't have a resolved `rawFnType`. Without the function type, I don't believe we can determine the parameter list required to construct `FunctionArgApplyInfo`.

I might be missing a mechanism to derive the function parameters for a `KeyPath` component without a resolved overload, so if there is a way, let me know and I'm happy to update it!

Comment (xedin) [reply lib/Sema/CSDiagnostics.cpp]: `getOverloadChoiceIfAvailable` might not be getting a right locator, the solver did select an overload for this, that’s how the fix about missing arguments got recorded, it’s just a matter of retrieving it properly.

Comment (anirudhmathur12) [reply lib/Sema/CSDiagnostics.cpp]: @xedin You were right! I realized the locator passed in was pointing to the ApplyArgument, but the overload was recorded on the `KeyPathComponent`.

I will update the logic to scan the locator path for the `KeyPathComponent`. Using that, I can now correctly retrieve both the ArgumentList (from the component) and the rawFnType (by looking up the overload on the component's locator).

This fixes the crash while correctly preserving the diagnostic info you wanted.

Also I requested the re-review by mistake.

**Comment by anirudhmathur12** [comment]
@xedin I implemented the logic to scan for the KeyPathComponent and retrieve the overload from there as you suggested.

However, for this specific crash case, getOverloadChoiceIfAvailable returns null even for the correct component locator (likely because the solver failed to record a selected overload for the invalid component).

To handle this, I've adopted a hybrid approach:

In ConstraintSystem.cpp: I kept the logic to look up the component overload, so we get the correct info whenever it is available.

In CSDiagnostics.cpp: I added a null-check for the result. This ensures we fallback gracefully instead of crashing when the solver doesn't have the data.

This fixes the crash while still attempting to retrieve the best possible diagnostic info.

File: lib/Sema/CSDiagnostics.cpp (hunk 1 above)
Comment (anirudhmathur12) [reply lib/Sema/CSDiagnostics.cpp]: @xedin I have implemented your suggestions, please check my latest comment.

File: lib/Sema/ConstraintSystem.cpp [hunk 2]
```diff
@@ -4246,24 +4246,55 @@ Solution::getFunctionArgApplyInfo(ConstraintLocator *locator) const {
...
+          return std::nullopt;
+      }
+
+      assert(!shouldHaveDirectCalleeOverload(call) &&
              "Should we have resolved a callee for this?");
+    } else if (auto *keyPath = getAsExpr<KeyPathExpr>(anchor)) {
+       // FIX for #85942: Handle KeyPath application diagnostics.
+       auto path = locator->getPath();
+
+       for (const auto &elt : path) {
```
Comment (xedin) [inline lib/Sema/ConstraintSystem.cpp]: This is closer but not the approach I had in mind. Take a look at `getCalleeLocator` - it's supposed to produce a locator that would be used to retrieve an overload - in your example, the fix points at `key path component #3` which is an Apply component, and calling `getCalleeLocator` on that locator should produce a locator for component `#2` instead because that's the member that is being apply. I think once you fix that everything should just work.

File: lib/Sema/CSDiagnostics.cpp (hunk 1 above)
Comment (xedin) [reply lib/Sema/CSDiagnostics.cpp]: I left a comment inline about the changes.

File: lib/Sema/ConstraintSystem.cpp (hunk 2 above)
Comment (anirudhmathur12) [reply lib/Sema/ConstraintSystem.cpp]: Hey @xedin! I tried implementing your approach please check the new commit out!

**Comment by anirudhmathur12** [comment]
The crash occurred because `getCalleeLocator` wasn't correctly handling KeyPath Apply components. The fix ensures it returns the right component (the callee) so that diagnostic information can be properly retrieved.

The new Swift parser now produces different (but still helpful) error messages for this case, catching the syntax error earlier than the constraint system.

**Comment by anirudhmathur12** [comment]
Hi @xedin @hborla — just a gentle ping in case this slipped through the cracks.
I’ve addressed the earlier feedback and would appreciate another look when you have time.
Thanks!

**Comment by xedin** [comment]
No problem, I will take a look on Monday (PST).

File: lib/Sema/ConstraintSystem.cpp [hunk 3]
```diff
@@ -4225,14 +4229,25 @@ Solution::getFunctionArgApplyInfo(ConstraintLocator *locator) const {
...
-  // If we were unable to simplify down to the argument expression, we don't
-  // know what this is.
-  if (!argExpr)
-    return std::nullopt;
+  if (!argList) {
+    if (auto *kp = getAsExpr<KeyPathExpr>(anchor)) {
+      if (auto componentElt =
+              argLocator->findLast<LocatorPathElt::KeyPathComponent>()) {
+        auto &component = kp->getComponents()[componentElt->getIndex()];
+        argList = component.getArgs();
```
Comment (xedin) [inline lib/Sema/ConstraintSystem.cpp]: This looks like a workaround, the underlying issue here is that key path component that represents an application didn't register the argument list like normal applies do and this needs to happen during constraint generation (check uses of `recordArgumentList` in there).

Comment (anirudhmathur12) [reply lib/Sema/ConstraintSystem.cpp]: I have tried to address the issue you raised please look at my newest commit.

**Comment by anirudhmathur12** [comment]
Hi @xedin! Thanks for your feedback, I have tried to implement the solution completely from scratch using your advice. I hope this solution is satisfactory, finding it was proving to be really difficult. Thanks for your time.

File: lib/Sema/ConstraintSystem.cpp [hunk 4]
```diff
@@ -760,6 +760,35 @@ ConstraintLocator *ConstraintSystem::getCalleeLocator(
                             getOverloadFor);
   }
 
+  {
+    auto iter = path.rbegin();
+    if (locator->findLast<LocatorPathElt::KeyPathComponent>(iter)) {
```
Comment (xedin) [inline lib/Sema/ConstraintSystem.cpp]: Please explain to me why we need to this instead of simply changing `getCalleeLocator` like the following and no other changes?

```
diff --git a/lib/Sema/ConstraintSystem.cpp b/lib/Sema/ConstraintSystem.cpp
index cbddf562b79..c3d2bc63e32 100644
--- a/lib/Sema/ConstraintSystem.cpp
+++ b/lib/Sema/ConstraintSystem.cpp
@@ -784,7 +784,8 @@ ConstraintLocator *ConstraintSystem::getCalleeLocator(
       break;
     case ComponentKind::UnresolvedApply:
     case ComponentKind::Apply:
-      return getConstraintLocator(anchor, *componentElt);
+      return getConstraintLocator(anchor, LocatorPathElt::KeyPathComponent(
+                                              componentElt->getIndex() - 1));
     case ComponentKind::Invalid:
     case ComponentKind::OptionalForce:
     case ComponentKind::OptionalChain:
```

Comment (anirudhmathur12) [reply lib/Sema/ConstraintSystem.cpp]: I have addressed the requested changes. Thanks for the review.

**Comment by anirudhmathur12** [comment]
Thanks for the review @xedin! I applied your suggestion to getCalleeLocator — hooking into the existing switch with index - 1 is definitely cleaner and safer than my original approach.

However, fixing the locator exposed a latent crash downstream in `getFunctionArgApplyInfo`.

When the constraint system fails to resolve an overload for a `KeyPath` application (as in this test case), `getFunctionArgApplyInfo` falls through to its else block. That block previously assumed the anchor must be a `CallExpr` and performed a blind `castToExpr<CallExpr>(anchor)`.

Since we are now correctly identifying the KeyPathExpr anchor, that cast triggers an assertion failure.

The Fix: I’ve updated `getFunctionArgApplyInfo` to use `getAsExpr<CallExpr>` instead. If the anchor isn't a `CallExpr` (e.g. it's a `KeyPath` application), it now safely returns `nullopt` instead of crashing.

Tests are passing locally with both changes included.

**Comment by xedin** [comment]
> Since we are now correctly identifying the KeyPathExpr anchor, that cast triggers an assertion failure.

Do you have a snippet of code that shows this?

I'm asking because I tried example you checked-in with just that one change to getCalleeLocator and it didn't crash.

**Comment by anirudhmathur12** [comment]
Here you go:
I built with 
```
ninja -C ../build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64 swift-frontend
```

And then ran the test case using

```
./../build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend -typecheck -verify test/Constraints/issue-85942.swift
```

And got this output:
```
Assertion failed: (isa<To>(Val) && "cast<Ty>() argument of incompatible type!"), function cast, file Casting.h, line 578.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.      Program arguments: ./../build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend -typecheck -verify test/Constraints/issue-85942.swift
1.      Swift version 6.3-dev (LLVM 9aac83f07b93962, Swift ec681c75b9b1e76)
2.      Compiling with effective version 5.10
3.      While evaluating request TypeCheckPrimaryFileRequest(source_file "test/Constraints/issue-85942.swift")
4.      While evaluating request TypeCheckFunctionBodyRequest(main.(file).f(buttonsStr:)@test/Constraints/issue-85942.swift:7:6)
5.      While type-checking statement at [test/Constraints/issue-85942.swift:7:33 - line:12:1] RangeText="{
    // expected-error@+3 {{unexpected code '(separator: ",").compactMap(Int.init)' in function call}}
    // expected-error@+2 {{key path cannot refer to instance method 'compactMap'}}
    // expected-error@+1 {{cannot convert value of type '() -> Int' to expected argument type '(ArraySlice<Character>) throws -> Int?'}}
    let _: [[Int]] = buttonsStr.map(\.split(separator: ",").compactMap(Int.init))
"
6.      While type-checking declaration 0xa5540fe90 (at test/Constraints/issue-85942.swift:11:5)
7.      While type-checking expression at [test/Constraints/issue-85942.swift:11:22 - line:11:81] RangeText="buttonsStr.map(\.split(separator: ",").compactMap(Int.init)"
8.      While type-checking-target starting at test/Constraints/issue-85942.swift:11:33
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x000000010a667eac llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x000000010a665f68 llvm::sys::RunSignalHandlers() + 172
2  swift-frontend           0x000000010a668954 SignalHandler(int, __siginfo*, void*) + 300
3  libsystem_platform.dylib 0x0000000190db7744 _sigtramp + 56
4  libsystem_pthread.dylib  0x0000000190dad888 pthread_kill + 296
5  libsystem_c.dylib        0x0000000190cb2850 abort + 124
6  libsystem_c.dylib        0x0000000190cb1a84 err + 0
7  swift-frontend           0x000000010a66a9e4 findSelfIndex(swift::ide::api::SDKNode*) (.cold.1) + 0
8  swift-frontend           0x0000000105e88988 swift::constraints::Solution::getFunctionArgApplyInfo(swift::constraints::ConstraintLocator*) const + 1468
9  swift-frontend           0x0000000105e3dbc4 swift::constraints::MissingArgumentsFailure::diagnoseAsError() + 368
10 swift-frontend           0x0000000105e0e8b4 swift::constraints::AddMissingArguments::diagnose(swift::constraints::Solution const&, bool) const + 120
11 swift-frontend           0x0000000105e84304 swift::constraints::ConstraintSystem::diagnoseAmbiguityWithFixes(llvm::SmallVectorImpl<swift::constraints::Solution>&) + 9432
12 swift-frontend           0x0000000105e81aa4 swift::constraints::ConstraintSystem::salvage() + 432
13 swift-frontend           0x0000000105def5a8 swift::constraints::ConstraintSystem::solve(swift::constraints::SyntacticElementTarget&, swift::FreeTypeVariableBinding) + 240
14 swift-frontend           0x0000000105f90978 swift::TypeChecker::typeCheckTarget(swift::constraints::SyntacticElementTarget&, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>, swift::DiagnosticTransaction*) + 324
15 swift-frontend           0x0000000105f907d8 swift::TypeChecker::typeCheckExpression(swift::constraints::SyntacticElementTarget&, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>, swift::DiagnosticTransaction*) + 196
16 swift-frontend           0x0000000105f91cc0 swift::TypeChecker::typeCheckBinding(swift::Pattern*&, swift::Expr*&, swift::DeclContext*, swift::Type, swift::PatternBindingDecl*, unsigned int, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 112
17 swift-frontend           0x0000000105f91eb4 swift::TypeChecker::typeCheckPatternBinding(swift::PatternBindingDecl*, unsigned int, swift::Type, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 280
18 swift-frontend           0x0000000105fd87d4 (anonymous namespace)::DeclChecker::visit(swift::Decl*) + 2416
19 swift-frontend           0x0000000105fd7e48 swift::TypeChecker::typeCheckDecl(swift::Decl*) + 128
20 swift-frontend           0x000000010606257c swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) + 288
21 swift-frontend           0x0000000106060ea4 bool (anonymous namespace)::StmtChecker::typeCheckStmt<swift::BraceStmt>(swift::BraceStmt*&) + 136
22 swift-frontend           0x00000001060608f8 (anonymous namespace)::StmtChecker::typeCheckBody(swift::BraceStmt*&) + 32
23 swift-frontend           0x00000001060606c4 swift::TypeCheckFunctionBodyRequest::evaluate(swift::Evaluator&, swift::AbstractFunctionDecl*) const + 1028
24 swift-frontend           0x000000010646b6b8 swift::TypeCheckFunctionBodyRequest::OutputType swift::Evaluator::getResultUncached<swift::TypeCheckFunctionBodyRequest, swift::TypeCheckFunctionBodyRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckFunctionBodyRequest>(swift::Evaluator&, swift::TypeCheckFunctionBodyRequest, swift::TypeCheckFunctionBodyRequest::OutputType)::'lambda'()>(swift::TypeCheckFunctionBodyRequest const&, swift::TypeCheckFunctionBodyRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckFunctionBodyRequest>(swift::Evaluator&, swift::TypeCheckFunctionBodyRequest, swift::TypeCheckFunctionBodyRequest::OutputType)::'lambda'())::'lambda'()::operator()() const + 76
25 swift-frontend           0x000000010646b0dc swift::TypeCheckFunctionBodyRequest::OutputType swift::Evaluator::getResultUncached<swift::TypeCheckFunctionBodyRequest, swift::TypeCheckFunctionBodyRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckFunctionBodyRequest>(swift::Evaluator&, swift::TypeCheckFunctionBodyRequest, swift::TypeCheckFunctionBodyRequest::OutputType)::'lambda'()>(swift::TypeCheckFunctionBodyRequest const&, swift::TypeCheckFunctionBodyRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckFunctionBodyRequest>(swift::Evaluator&, swift::TypeCheckFunctionBodyRequest, swift::TypeCheckFunctionBodyRequest::OutputType)::'lambda'()) + 216
26 swift-frontend           0x00000001063e4890 swift::AbstractFunctionDecl::getTypecheckedBody() const + 108
27 swift-frontend           0x000000010651285c swift::SourceFile::typeCheckDelayedFunctions() + 92
28 swift-frontend           0x00000001060ae0e8 swift::TypeCheckPrimaryFileRequest::evaluate(swift::Evaluator&, swift::SourceFile*) const + 348
29 swift-frontend           0x00000001060b1854 swift::TypeCheckPrimaryFileRequest::OutputType swift::Evaluator::getResultUncached<swift::TypeCheckPrimaryFileRequest, swift::TypeCheckPrimaryFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckPrimaryFileRequest>(swift::Evaluator&, swift::TypeCheckPrimaryFileRequest, swift::TypeCheckPrimaryFileRequest::OutputType)::'lambda'()>(swift::TypeCheckPrimaryFileRequest const&, swift::TypeCheckPrimaryFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckPrimaryFileRequest>(swift::Evaluator&, swift::TypeCheckPrimaryFileRequest, swift::TypeCheckPrimaryFileRequest::OutputType)::'lambda'())::'lambda'()::operator()() const + 72
30 swift-frontend           0x00000001060b1284 swift::TypeCheckPrimaryFileRequest::OutputType swift::Evaluator::getResultUncached<swift::TypeCheckPrimaryFileRequest, swift::TypeCheckPrimaryFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckPrimaryFileRequest>(swift::Evaluator&, swift::TypeCheckPrimaryFileRequest, swift::TypeCheckPrimaryFileRequest::OutputType)::'lambda'()>(swift::TypeCheckPrimaryFileRequest const&, swift::TypeCheckPrimaryFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckPrimaryFileRequest>(swift::Evaluator&, swift::TypeCheckPrimaryFileRequest, swift::TypeCheckPrimaryFileRequest::OutputType)::'lambda'()) + 204
31 swift-frontend           0x00000001060adf64 swift::performTypeChecking(swift::SourceFile&) + 76
32 swift-frontend           0x00000001050c8a64 bool llvm::function_ref<bool (swift::SourceFile&)>::callback_fn<swift::CompilerInstance::performSema()::$_0>(long, swift::SourceFile&) + 16
33 swift-frontend           0x00000001050c0988 swift::CompilerInstance::forEachFileToTypeCheck(llvm::function_ref<bool (swift::SourceFile&)>) + 156
34 swift-frontend           0x00000001050c08cc swift::CompilerInstance::performSema() + 144
35 swift-frontend           0x0000000104e79120 withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 60
36 swift-frontend           0x0000000104e6c814 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*, llvm::ArrayRef<char const*>) + 560
37 swift-frontend           0x0000000104e6a3c8 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2440
38 swift-frontend           0x0000000104be8be0 swift::mainEntry(int, char const**) + 3244
39 dyld                     0x00000001909e5d54 start + 7184
[2]    19676 abort      ./../build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend
```

My code was the changes you suggested and nothing else was modified, i.e., identical to the main branch.

**Comment by xedin** [comment]
> When the constraint system fails to resolve an overload for a KeyPath application (as in this test case), getFunctionArgApplyInfo falls through to its else block. 

But we are fixing `getCalleeLocator` to make sure that `getOverloadChoiceIfAvailable` does produce an overload choice, we shouldn't be entering the `else` block there at all.

**Comment by anirudhmathur12** [comment]
You're right @xedin that normally the locator fix should find the overload and return early.

But since this is an invalid code case (`\.split`), the solver actually fails to record an overload, so `getOverloadChoiceIfAvailable` returns `null` and we still fall through to the `else` block.

The crash happens because that else block assumes anything without an overload is a CallExpr. Since it's actually a `KeyPathExpr`, the cast fails. I added the `getAsExpr` check just to handle this failure case without crashing.

That is my understanding, at least. I'm still new to the codebase, so please let me know if I'm misinterpreting.

**Comment by xedin** [comment]
If that was the case they we won't have produced a fix for `split` that deals with argument mismatches.

**Comment by anirudhmathur12** [comment]
Hey @xedin,

That makes complete sense—since the solver produced a `missing argument` fix, it must have successfully identified the overload during the solve phase.

However, I am hitting a hard assertion failure at `castToExpr<CallExpr>(anchor)` inside `getFunctionArgApplyInfo`. This confirms that in this specific lookup context, `getOverloadChoiceIfAvailable` is returning null—perhaps there is a subtle mismatch between the locator reconstructed here and the one stored in the solution.

Because this re-lookup fails, we fall through to the `else` block. The existing code there blindly assumes that 'no overload' means 'this is a standard CallExpr', which isn't true for KeyPaths, causing the crash.

I added the `getAsExpr` check as a defensive measure to handle this specific lookup failure gracefully, rather than letting the compiler abort.

**Comment by xedin** [comment]
I'm not sure what you mean by the assertion. I tried just the change to `getCalleeLocator` and added your test-case to the suite and there are no failures beside one improvement in the diagnostic below:

```
swift/test/expr/unary/keypath/keypath.swift:868:56: error: incorrect message found
  let _: KeyPath<S, Int> = \.add() // expected-error {{failed to produce diagnostic for expression}}
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                       no exact matches in call to instance method 'add'
```

The new test is passing as well and that's why I'm trying to understand what is actually failing for you. As I said before there is not going to be a "missing" or "incorrect" fix if there is no overload and that cast is correct because we'd only expect that for call expressions.

**Comment by anirudhmathur12** [comment]
Are you, by any chance, running a Release build? I am running RelWithDebInfoAssert.

**Comment by xedin** [comment]
I'm also using `RelWithDebInfoAssert` with `-T` to run all the tests. Maybe you need to update-checkout?

**Comment by anirudhmathur12** [comment]
Hey, so I have tried your suggested fix on a fresh clone of the main branch and am getting the same result as you. I think I messed up the build somewhere long ago and have been getting weird behaviors since. 

Pushing the correct fix in a bit.

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
You'd need to fix the test I mentioned above related to key paths and adjust the diagnostic a bit - see https://ci.swift.org/job/swift-PR-Linux/25846/ results.

**Comment by anirudhmathur12** [comment]
Hey @xedin, I fixed the incorrect expected error issue.

**Comment by xedin** [comment]
@AnirudhMathur12 there is one more test in the suite that needs updating, please run tests locally and address it.

**Comment by anirudhmathur12** [comment]
@xedin I just updated keypath.swift to match the new behavior.

The test failures were actually due to the improved diagnostics—the test was expecting the old 'failed to produce diagnostic' fallback error. Since the fix now correctly identifies the issue ('no exact matches') and provides candidate notes,.

**Comment by xedin** [comment]
Yes, I mentioned that in my previous comments.

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

File: test/Constraints/issue-85942.swift [hunk 5]
```diff
@@ -0,0 +1,12 @@
+// expected-error@1 {{new Swift parser generated errors for code that C++ parser accepted}}
+// RUN: %target-typecheck-verify-swift
```
Comment (xedin) [inline test/Constraints/issue-85942.swift]: One more thing - could you please use `// RUN: %target-typecheck-verify-swift -disable-experimental-parser-round-trip` here? It would remove all of this round-trip diagnostics like `new Swift parser generated` and `unexpected code`.

Comment (anirudhmathur12) [reply test/Constraints/issue-85942.swift]: Yeah, I was going to push that update after looking through the Windows console log. Pushing now.

Comment (anirudhmathur12) [reply test/Constraints/issue-85942.swift]: Done.

Comment (xedin) [reply test/Constraints/issue-85942.swift]: It doesn't look like you did.

Comment (anirudhmathur12) [reply test/Constraints/issue-85942.swift]: Do you see it now?

Comment (xedin) [reply test/Constraints/issue-85942.swift]: Yep, now it's pushed.

**Comment by xedin** [comment]
@swift-ci please test
