### PR TITLE
[Completion] Type-check parent closures for local functions

### LINKED ISSUE #77305: Completion doesn't work in nested function in closure
The following doesn't produce any completions:

```swift
func withFoo(_ x: (Int) -> Void) {}

withFoo { foo in
  func bar() {
    foo.#^CC^#
  }
}
```

### PR DESCRIPTION
**Pull request by hamishknight**
Local functions can capture variables from parent closures, so we need to make sure we type-check parent closures when doing completion in a local function. Ideally we ought to be able to be more selective about the elements of the parent closure that we type-check, but that's a more complex change I'm leaving as future work for now.

Resolves #77305

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please SourceKit stress test

**Review by rintaro — APPROVED** [review]
Looks reasonable

**Review by ahoppen — APPROVED** [review]
LGTM

File: lib/Sema/CSApply.cpp [hunk 1]
```diff
@@ -5620,16 +5620,20 @@ namespace {
...
-      auto &eval = cs.getASTContext().evaluator;
-      for (auto *E : MacrosToExpand) {
-        (void)evaluateOrDefault(eval, ExpandMacroExpansionExprRequest{E},
-                                std::nullopt);
+      // If we're doing code completion, avoid doing any further type-checking,
+      // that should instead be handled by TypeCheckASTNodeAtLocRequest.
+      if (!ctx.CompletionCallback) {
+        // Type-check any local decls encountered.
+        for (auto *D : LocalDeclsToTypeCheck)
+          TypeChecker::typeCheckDecl(D);
```
Comment (xedin) [inline lib/Sema/CSApply.cpp:5628]: Maybe we should skip adding them to the local decls and macro lists?

Comment (hamishknight) [reply lib/Sema/CSApply.cpp:5628]: Sure, I don't mind

Comment (hamishknight) [reply lib/Sema/CSApply.cpp:5628]: #77561
