### PR TITLE
[CSOptimizer] Also favor existential metatype candidates in paramType isAny fast path

### LINKED ISSUE #85020: Overload resolution picks wrong initializer for some metatype arguments
### Description

We noticed a regression (or a change in behavior at the very least) when using metatype arguments.

When two initializers differ only by (a) accepting `Any.Type` vs `Any`, and (b) sharing the same external label `(of:)`, calls that pass metatype arguments like `Int.self` or `Any.self` sometimes resolve to the instance-taking overload instead of the metatype-taking overload. This produces unexpected stored types (Int.Type, Any.Protocol) and ends up breaking code that relies on equality checks that should otherwise succeed.

The included reproducer uses `Any` and `Int` examples, which do reproduce the bug. It also includes an example using `String` which does not reproduce the bug, so only happens with some types.

### Reproduction

1. Create a single file `type-resolution-repro.swift` with the following code...
```swift
import Foundation

struct Wrapper {
    struct Store: Equatable, CustomStringConvertible {
        let theType: Any.Type

        // Labeled initializers
        init(of theType: Any.Type) { self.theType = theType }
        init(of instance: Any)     { self.init(of: type(of: instance)) }

        // Unlabeled initializers
        init(_ theType: Any.Type)  { self.theType = theType }
        init(_ instance: Any)      { self.init(type(of: instance)) }

        static func == (lhs: Self, rhs: Self) -> Bool { lhs.theType == rhs.theType }

        var description: String { "Store(\(String(reflecting: theType)))" }
    }

    let store: Store

    init(_ theType: Any.Type) {
        self.store = .init(of: theType)
    }
}

func check<T: Equatable & CustomStringConvertible>(_ a: T, _ b: T, _ label: String) {
    print("\(label): \(a) == \(b)  →  \(a == b ? "✅ true" : "❌ false")")
}

check(Wrapper(Any.self).store, .init(of: Any.self), "Any.self vs .init(of: Any.self) (labeled)")
check(Wrapper(Any.self).store, .init(Any.self),     "Any.self vs .init(Any.self) (unlabeled)")

check(Wrapper(Int.self).store, .init(of: Int.self), "Int.self vs .init(of: Int.self) (labeled)")
check(Wrapper(Int.self).store, .init(Int.self),     "Int.self vs .init(Int.self) (unlabeled)")

check(Wrapper(String.self).store, .init(of: "hello"), "String.self vs .init(of: \"hello\") (labeled)")
check(Wrapper(String.self).store, .init("hello"),     "String.self vs .init(\"hello\") (unlabeled)")
```
2. Run with `swift type-resolution-repro.swift`

### Expected behavior

Actual behavior against Swift 6.2...
```
Any.self vs .init(of: Any.self) (labeled): Store(Any) == Store(Any)  →  ✅ true
Any.self vs .init(Any.self) (unlabeled): Store(Any) == Store(Any)  →  ✅ true
Int.self vs .init(of: Int.self) (labeled): Store(Swift.Int) == Store(Swift.Int)  →  ✅ true
Int.self vs .init(Int.self) (unlabeled): Store(Swift.Int) == Store(Swift.Int)  →  ✅ true
String.self vs .init(of: "hello") (labeled): Store(Swift.String) == Store(Swift.String)  →  ✅ true
String.self vs .init("hello") (unlabeled): Store(Swift.String) == Store(Swift.String)  →  ✅ true
```

The expected behavior against main-snapshots is that it matches the 6.2 behavior.

The actual behavior against nightly main-snapshots...
```
Any.self vs .init(of: Any.self) (labeled): Store(Any) == Store(Any.Protocol)  →  ❌ false
Any.self vs .init(Any.self) (unlabeled): Store(Any) == Store(Any)  →  ✅ true
Int.self vs .init(of: Int.self) (labeled): Store(Swift.Int) == Store(Swift.Int.Type)  →  ❌ false
Int.self vs .init(Int.self) (unlabeled): Store(Swift.Int) == Store(Swift.Int)  →  ✅ true
String.self vs .init(of: "hello") (labeled): Store(Swift.String) == Store(Swift.String)  →  ✅ true
String.self vs .init("hello") (unlabeled): Store(Swift.String) == Store(Swift.String)  →  ✅ true
```

### Environment

This reproduces on macOS and linux.

### Additional information

This seems to be a regression that first landed in the main-snapshot-2025-08-16 nightly toolchain. The latest known-good toolchain was main-snapshot-2025-08-14.

### PR DESCRIPTION
**Pull request by clackary**
Adds a test case and a fix to CSOptimizer, regarding a fast path with `Any` parameters that recently landed (https://github.com/swiftlang/swift/commit/c46f9e4f45d5a7195129bdf72d039a4c3d1dc99b). This change introduced a regression where it would cause `(T.Type) -> (Any)` disjunctions to outrank `(T.Type) -> (Any.Type)`.

Refines the check to also favor existential metatype candidates.

Resolves: https://github.com/swiftlang/swift/issues/85020
Resolves: rdar://163074598

### CODE REVIEW

**Comment by clackary** [comment]
@swift-ci please test

**Comment by clackary** [comment]
@swift-ci please test

File: lib/Sema/CSOptimizer.cpp [hunk 1]
```diff
@@ -1429,11 +1429,13 @@ static void determineBestChoicesInContext(
...
-      // If the parameter is `Any` we assume that all candidates are
-      // convertible to it, which makes it a perfect match. The solver
-      // would then decide whether erasing to an existential is preferable.
-      if (paramType->isAny())
-        return 1;
+      // If the parameter is `Any`, it's generally a perfect match, except
+      // when the candidate is an existential metatype. In that case, it would
+      // cause (T.Type) -> (Any) disjunctions to outrank (T.Type) -> (Any.Type).
+      if (paramType->isAny() &&
+          !candidateType->is<ExistentialMetatypeType>()) {
```
Comment (xedin) [inline lib/Sema/CSOptimizer.cpp]: It sounds like what we want here instead is a rule that matches `Any.Type` and return `1.0` if that matches, this way we'll get both choices favored.

Comment (clackary) [reply lib/Sema/CSOptimizer.cpp]: I like that idea. Something like this? Is there a better way to check for `Any.Type`?
```
if (paramType->isAny() && 
    paramType->is<MetatypeType>() &&
    candidateType->is<ExistentialMetatypeType>()) {
  return 1.0
}
```

Comment (xedin) [reply lib/Sema/CSOptimizer.cpp]: I'd say something like this:

```
diff --git a/lib/Sema/CSOptimizer.cpp b/lib/Sema/CSOptimizer.cpp
index aab3431df14..3b84228d71a 100644
--- a/lib/Sema/CSOptimizer.cpp
+++ b/lib/Sema/CSOptimizer.cpp
@@ -21,6 +21,7 @@
 #include "swift/AST/ExistentialLayout.h"
 #include "swift/AST/Expr.h"
 #include "swift/AST/GenericSignature.h"
+#include "swift/AST/Types.h"
 #include "swift/Basic/Defer.h"
 #include "swift/Basic/OptionSet.h"
 #include "swift/Sema/ConstraintGraph.h"
@@ -1429,11 +1430,22 @@ static void determineBestChoicesInContext(
         }
       }

-      // If the parameter is `Any` we assume that all candidates are
-      // convertible to it, which makes it a perfect match. The solver
-      // would then decide whether erasing to an existential is preferable.
-      if (paramType->isAny())
-        return 1;
+      if (paramType->isAnyExistentialType()) {
+        // If the parameter is `Any` we assume that all candidates are
+        // convertible to it, which makes it a perfect match. The solver
+        // would then decide whether erasing to an existential is preferable.
+        if (paramType->isAny())
+          return 1;
+
+        // If the parameter is `Any.Type` we assume that all metatype
+        // candidates are convertible to it.
+        if (auto *EMT = paramType->getAs<ExistentialMetatypeType>()) {
+          if (EMT->getExistentialInstanceType()->isAny() &&
+              (candidateType->is<ExistentialMetatypeType>() ||
+               candidateType->is<MetatypeType>()))
+            return 1;
+        }
+      }

       // Check if a candidate could be matched to a parameter by
       // an existential opening.
```

File: test/Constraints/issue-85020.swift [hunk 2]
```diff
@@ -0,0 +1,35 @@
+// RUN: %target-run-simple-swift | %FileCheck %s
+
+// https://github.com/swiftlang/swift/issues/85020
+
+struct Store {
+    let theType: Any.Type
+
+    init(of theType: Any.Type) {
```
Comment (xedin) [inline test/Constraints/issue-85020.swift]: Nit: we use 2 space indentation everywhere.

Comment (xedin) [reply test/Constraints/issue-85020.swift]: Also since this is a runtime test it should go to `test/Interpreter`.

**Comment by clackary** [comment]
@swift-ci please test

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
Thank you!

**Comment by xedin** [comment]
Let's cherry-pick this to 6.3 as well.
