### PR TITLE
SILOptimizer: Fix CapturePromotion crash with indirect error result

### LINKED ISSUE #86391: Task typed throws API change triggers crash in CapturePromotion.cpp
### Description

With the changes to the Task API from #86358, a crash has been exposed. I've reduced it down to the following code. However, I'm unable to get it to repro without also applying the API changes. I experimented with doing it in file local extensions, maybe I just missed something.

It may have something to do with the `fileprivate` annotation here. Removing just that from this code results in a successful build.

### Reproduction

```swift
private protocol AnyTask: Sendable {
  func waitForCompletion() async
}

extension Task: AnyTask {
  func waitForCompletion() async {
  }
}

struct PendingTask: Sendable {
  fileprivate let task: any AnyTask
}

public final class AsyncQueue: Sendable {
  public init() {}

  public func asyncThrowing<Success: Sendable>(
    @_inheritActorContext operation: @escaping @Sendable () async throws -> Success
  ) -> Void {
      var dependencies: [PendingTask] = []

      Task {
        for dependency in dependencies {
          await dependency.task.waitForCompletion()
        }

        let result = try await operation()

        return result
    }
  }
}
```

### Stack dump

```text
Assertion failed: (calleeConv.getSILType(cpInfo, builder.getTypeExpansionContext()) == box->getType() && "SILType of parameter info does not match type of parameter"), function processPartialApplyInst, file CapturePromotion.cpp, line 1553.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend -frontend -c -primary-file /Users/matt/Developer/swift-project/swift/test/Concurrency/Runtime/task_creation.swift -target arm64-apple-macosx10.15 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.2.sdk -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -F /Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/lib -module-cache-path /Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/swift-test-results/arm64-apple-macosx13.0/clang-module-cache -swift-version 4 -define-availability "SwiftStdlib 9999:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999" -define-availability "StdlibDeploymentTarget 9999:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999" -define-availability "SwiftStdlib 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2" -define-availability "StdlibDeploymentTarget 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2" -define-availability "SwiftStdlib 5.1:macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0" -define-availability "StdlibDeploymentTarget 5.1:macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0" -define-availability "SwiftStdlib 5.2:macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4" -define-availability "StdlibDeploymentTarget 5.2:macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4" -define-availability "SwiftStdlib 5.3:macOS 11.0, iOS 14.0, watchOS 7.0, tvOS 14.0" -define-availability "StdlibDeploymentTarget 5.3:macOS 11.0, iOS 14.0, watchOS 7.0, tvOS 14.0" -define-availability "SwiftStdlib 5.4:macOS 11.3, iOS 14.5, watchOS 7.4, tvOS 14.5" -define-availability "StdlibDeploymentTarget 5.4:macOS 11.3, iOS 14.5, watchOS 7.4, tvOS 14.5" -define-availability "SwiftStdlib 5.5:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0" -define-availability "StdlibDeploymentTarget 5.5:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0" -define-availability "SwiftStdlib 5.6:macOS 12.3, iOS 15.4, watchOS 8.5, tvOS 15.4" -define-availability "StdlibDeploymentTarget 5.6:macOS 12.3, iOS 15.4, watchOS 8.5, tvOS 15.4" -define-availability "SwiftStdlib 5.7:macOS 13.0, iOS 16.0, watchOS 9.0, tvOS 16.0" -define-availability "StdlibDeploymentTarget 5.7:macOS 13.0, iOS 16.0, watchOS 9.0, tvOS 16.0" -define-availability "SwiftStdlib 5.8:macOS 13.3, iOS 16.4, watchOS 9.4, tvOS 16.4" -define-availability "StdlibDeploymentTarget 5.8:macOS 13.0" -define-availability "SwiftStdlib 5.9:macOS 14.0, iOS 17.0, watchOS 10.0, tvOS 17.0" -define-availability "StdlibDeploymentTarget 5.9:macOS 13.0" -define-availability "SwiftStdlib 5.10:macOS 14.4, iOS 17.4, watchOS 10.4, tvOS 17.4, visionOS 1.1" -define-availability "StdlibDeploymentTarget 5.10:macOS 13.0" -define-availability "SwiftStdlib 6.0:macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0" -define-availability "StdlibDeploymentTarget 6.0:macOS 13.0" -define-availability "SwiftStdlib 6.1:macOS 15.4, iOS 18.4, watchOS 11.4, tvOS 18.4, visionOS 2.4" -define-availability "StdlibDeploymentTarget 6.1:macOS 13.0" -define-availability "SwiftStdlib 6.2:macOS 26.0, iOS 26.0, watchOS 26.0, tvOS 26.0, visionOS 26.0" -define-availability "StdlibDeploymentTarget 6.2:macOS 13.0" -define-availability "SwiftStdlib 6.3:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999, visionOS 9999" -define-availability "StdlibDeploymentTarget 6.3:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999, visionOS 9999" -define-availability "SwiftStdlib 6.4:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999, visionOS 9999" -define-availability "StdlibDeploymentTarget 6.4:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999, visionOS 9999" -define-availability "SwiftCompatibilitySpan 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2, visionOS 1.0" -define-availability "SwiftCompatibilitySpan 6.2:macOS 26.0, iOS 26.0, watchOS 26.0, tvOS 26.0, visionOS 26.0" -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.2.sdk/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.2.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.2.sdk/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.2.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -in-process-plugin-server-path /Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/lib/swift/host/libSwiftInProcPluginServer.dylib -plugin-path /Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/lib/swift/host/plugins -plugin-path /Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/local/lib/swift/host/plugins -target-sdk-version 26.2 -dwarf-version=4 -parse-as-library -module-name main -o /var/folders/ys/r6dvhjxd4xq982fvrx8c7zz40000gn/T/lit-tmp-881h8tt5/task_creation-a17d2f.o
1.	Swift version 6.3-dev (LLVM 1822b0058a71438, Swift 249d3aab6c7cca8)
2.	Compiling with effective version 4.1.50
3.	While evaluating request ExecuteSILPipelineRequest(Run pipelines { Mandatory Diagnostic Passes + Enabling Optimization Passes } on SIL for main)
4.	While running pass #96 SILModuleTransform "CapturePromotion".
 #0 0x000000010618907c llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1060a507c)
 #1 0x0000000106186fdc llvm::sys::RunSignalHandlers() (/Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1060a2fdc)
 #2 0x0000000106189b24 SignalHandler(int, __siginfo*, void*) (/Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1060a5b24)
 #3 0x00000001964bf744 (/usr/lib/system/libsystem_platform.dylib+0x1804e3744)
 #4 0x00000001964b5888 (/usr/lib/system/libsystem_pthread.dylib+0x1804d9888)
 #5 0x00000001963ba850 (/usr/lib/system/libsystem_c.dylib+0x1803de850)
 #6 0x00000001963b9a84 (/usr/lib/system/libsystem_c.dylib+0x1803dda84)
 #7 0x00000001061f0fc8 (anonymous namespace)::CapturePromotionPass::processFunction(swift::SILFunction*, llvm::SmallVectorImpl<swift::SILFunction*>&) (.cold.78) (/Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x10610cfc8)
 #8 0x00000001010642b0 (anonymous namespace)::CapturePromotionPass::processFunction(swift::SILFunction*, llvm::SmallVectorImpl<swift::SILFunction*>&) (/Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x100f802b0)
 #9 0x0000000101061874 (anonymous namespace)::CapturePromotionPass::run() (/Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x100f7d874)
#10 0x000000010115ee1c swift::SILPassManager::runModulePass(unsigned int) (/Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x10107ae1c)
#11 0x0000000101161734 swift::SILPassManager::execute() (/Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x10107d734)
#12 0x000000010115b760 swift::SILPassManager::executePassPipelinePlan(swift::SILPassPipelinePlan const&) (/Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x101077760)
#13 0x000000010115b6fc swift::ExecuteSILPipelineRequest::evaluate(swift::Evaluator&, swift::SILPipelineExecutionDescriptor) const (/Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1010776fc)
#14 0x0000000101177094 swift::SimpleRequest<swift::ExecuteSILPipelineRequest, std::__1::tuple<> (swift::SILPipelineExecutionDescriptor), (swift::RequestFlags)1>::evaluateRequest(swift::ExecuteSILPipelineRequest const&, swift::Evaluator&) (/Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x101093094)
#15 0x000000010116683c swift::ExecuteSILPipelineRequest::OutputType swift::Evaluator::getResultUncached<swift::ExecuteSILPipelineRequest, swift::ExecuteSILPipelineRequest::OutputType swift::evaluateOrFatal<swift::ExecuteSILPipelineRequest>(swift::Evaluator&, swift::ExecuteSILPipelineRequest)::'lambda'()>(swift::ExecuteSILPipelineRequest const&, swift::ExecuteSILPipelineRequest::OutputType swift::evaluateOrFatal<swift::ExecuteSILPipelineRequest>(swift::Evaluator&, swift::ExecuteSILPipelineRequest)::'lambda'())::'lambda'()::operator()() const (/Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x10108283c)
#16 0x00000001011667b0 swift::ExecuteSILPipelineRequest::OutputType swift::Evaluator::getResultUncached<swift::ExecuteSILPipelineRequest, swift::ExecuteSILPipelineRequest::OutputType swift::evaluateOrFatal<swift::ExecuteSILPipelineRequest>(swift::Evaluator&, swift::ExecuteSILPipelineRequest)::'lambda'()>(swift::ExecuteSILPipelineRequest const&, swift::ExecuteSILPipelineRequest::OutputType swift::evaluateOrFatal<swift::ExecuteSILPipelineRequest>(swift::Evaluator&, swift::ExecuteSILPipelineRequest)::'lambda'()) (/Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1010827b0)
#17 0x000000010115b958 swift::executePassPipelinePlan(swift::SILModule*, swift::SILPassPipelinePlan const&, bool, swift::irgen::IRGenModule*) (/Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x101077958)
#18 0x0000000101168108 swift::runSILDiagnosticPasses(swift::SILModule&) (/Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x101084108)
#19 0x00000001006743c0 swift::CompilerInstance::performSILProcessing(swift::SILModule*) (/Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1005903c0)
#20 0x00000001003a1c78 performCompileStepsPostSILGen(swift::CompilerInstance&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*, llvm::ArrayRef<char const*>, llvm::ArrayRef<swift::PrimarySpecificPaths>) (/Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1002bdc78)
#21 0x00000001003a132c swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*, llvm::ArrayRef<char const*>) (/Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1002bd32c)
#22 0x00000001003b190c withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) (/Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1002cd90c)
#23 0x00000001003a4f78 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*, llvm::ArrayRef<char const*>) (/Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1002c0f78)
#24 0x00000001003a2b2c swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) (/Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1002beb2c)
#25 0x000000010011e27c swift::mainEntry(int, char const**) (/Users/matt/Developer/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x10003a27c)
#26 0x00000001960edd54
```

### Expected behavior

This should build without issue

### Environment

Swift version 6.3-dev (LLVM 1822b0058a71438, Swift 249d3aab6c7cca8)
Target: arm64-apple-macosx26.0

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by slavapestov**
- Fixes https://github.com/swiftlang/swift/issues/86391

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Review by ktoso — APPROVED** [review]
Thanks a lot, Slava! LGTM

File: lib/SILOptimizer/Mandatory/CapturePromotion.cpp [hunk 1]
```diff
@@ -1512,7 +1512,8 @@ processPartialApplyInst(SILOptFunctionBuilder &funcBuilder,
   unsigned opNo = 1;
   unsigned opCount = pai->getNumOperands() - pai->getNumTypeDependentOperands();
   SmallVector<SILValue, 16> args;
-  auto numIndirectResults = calleeConv.getNumIndirectSILResults();
+  auto numIndirectResults = (calleeConv.getNumIndirectSILResults() +
+                             calleeConv.getNumIndirectSILErrorResults());
```
Comment (jamieQ) [inline lib/SILOptimizer/Mandatory/CapturePromotion.cpp]: nit (please forgive the lengthy comment...): it may be slightly nicer to replace this with the seemingly-equivalent `getSILArgIndexOfFirstParam()`. as someone unfamiliar with this code, i think it would make the logic a bit clearer, since this value is just being used for relative offset calculation purposes IIUC.
and as an aside... there is this comment i found in the SIL conventions [doc](https://github.com/swiftlang/swift/blob/48bc818f99b6ebc480a65c2de380247ad06c55f3/docs/SIL/SILFunctionConventions.md):

> A common mistake is to directly map the ApplySite's caller-side
arguments onto callee-side SILFunctionArguments. This happens to work
until the same code is exposed to a `partial_apply`. Instead, use the `ApplySite` API for applied argument indices, or use
`ApplySite::getCalleeArgIndexOfFirstAppliedArg()` to translate the
apply's arguments into function convention arguments.

is that callout relevant here?

File: test/SILOptimizer/capture_promotion_typed_throws.swift [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+        return rez
+    }
+}
+
+func doit<Success, Failure: Error>(
+    op: @escaping () throws(Failure) -> Success
+) {}
+
+@_optimize(none)
+func use<T>(_: T) {}
```
Comment (jamieQ) [inline test/SILOptimizer/capture_promotion_typed_throws.swift:26]: @slavapestov (asking here for threading reasons): not directly related to the change, but can you tell if this issue affects release compilers too (e.g. 6.2)? none of the 'nearby' code appeared to have been changed in years, so i would assume it's possible, but also i'm not sure how to verify or if it would result in observable problems (without bisecting or something).

File: lib/SILOptimizer/Mandatory/CapturePromotion.cpp (hunk 1 above)
Comment (slavapestov) [reply lib/SILOptimizer/Mandatory/CapturePromotion.cpp]: Nice catch!

File: test/SILOptimizer/capture_promotion_typed_throws.swift (hunk 2 above)
Comment (slavapestov) [reply test/SILOptimizer/capture_promotion_typed_throws.swift:26]: You're asking if there is a possible miscompile in a noassert build where the assertion is skipped? It's possible. After the assertion, we pass the `cpInfo` down to `releasePartialApplyCapturedArg()`, which calls `shouldDestroyPartialApplyCapturedArg()`, which checks:

```
  if (paramInfo.isIndirectMutating())
    return false;
```

So if you have a situation where the parameter is `inout`, the incorrect indexing might cause us to not take this branch, and return `true` from this function instead. Captures of `inout` parameters appear when you have a non-escaping closure, but I can't immediately think of a test case off the top of my head.

Comment (slavapestov) [reply test/SILOptimizer/capture_promotion_typed_throws.swift:26]: I changed the assert() to ASSERT() on account of this possibility, but only in the main PR. I'll leave it as-is for 6.3.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

File: test/SILOptimizer/capture_promotion_typed_throws.swift (hunk 2 above)
Comment (jamieQ) [reply test/SILOptimizer/capture_promotion_typed_throws.swift:26]: > You're asking if there is a possible miscompile in a noassert build where the assertion is skipped?

yeah, and the slightly more confusing thing to me is that in the repro that did not use a generic return type ([here](https://github.com/swiftlang/swift/issues/86391#issuecomment-3725983186)), the code seemed like it hit an array OOB when indexing into the `calleePInfo` array. however, that doesn't seem to be an issue on the release compilers which seems... surprising.

Comment (slavapestov) [reply test/SILOptimizer/capture_promotion_typed_throws.swift:26]: I forgot to add your second test case but I can confirm that the other repro also compiles with this fix.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

File: test/SILOptimizer/capture_promotion_typed_throws.swift (hunk 2 above)
Comment (jamieQ) [reply test/SILOptimizer/capture_promotion_typed_throws.swift:26]: for posterity, i think i resolved my confusion about why reading off the end of the array didn't seem to cause (immediate, terrible) problems in the release compilers. the next trailing object is the indirect error result, and the type layout between the parameter & result info seemingly is similar enough (the same?) that things 'work out' and don't result in a compiler crash.
