### PR TITLE
Round the initial context size of tasks up to 32 on 64-bit <=5.6 runtimes

### LINKED ISSUE #63420: XCode 14.2/Swift 5.7 memory corruption on Task creation when app is launched on iOS < 16.
**Description**
Task creation in some contexts can lead to corruption of the application's memory. Examples can be seen in the demo application code.

**Steps to reproduce**
1. Download demo application source code: https://github.com/mstyura/Swift-Task-Heap-Curruption-on-iOS-15-and-earlier.
2. Select scheme `TaskCrasher - Release - libgmalloc - use with arm64 simulator`;
3. Run demo app on `arm64` iOS simulator with `iOS 15.4`;

**Expected behavior**
Application is not crashed.

**Actual behavior**
Demo app crashes with `libgmalloc` enabled. Address sanitizer unfortunately unable to catch the issue.

выява

I've actually encountered problem on real production application on iOS device where app  is randomly crashed on memory access to address `0x100000000 + offset` where offset is usually `+0x10`,` +0x20` or `-0x8` in application or system library code.
Also in real application `libmalloc` were capable to detect it was corrupted on some point, but it was unclear who was responsible for corruption.

**Environment**
- Swift compiler version info
```
swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0
```
- Xcode version info
```
Xcode 14.2
Build version 14C18
```
- Deployment target: 
  checked that issue happen on iOS 14 and iOS 13 and iOS 15 as deployment target.

Additional context:
An app that I observed crashing worked fine when built with `XCode 13.4.1` and `Swift 5.6`, but experienced significant, random crashes with "bad access" errors on addresses like `0x100000020` when built with `XCode 14.2` or` XCode 14.1` and `Swift 5.7`. As a result, it's currently not feasible to target iOS versions lower than 16 and use `Swift 5.7` with async functions and Tasks without encountering random crashes.

**UPD**: On demo application issue is only happen when compiled with `-O` (optimize for speed), but not when compiled with `-Osize` (optimize for size) or `-Onone`.

### PR DESCRIPTION
**Pull request by rjmccall**
Fixes issue 63420.

### CODE REVIEW

**Comment by rjmccall** [comment]
@swift-ci Please test

**Review by etcwilde — APPROVED** [review]
Yeah, I think this should work.

File: stdlib/toolchain/Compatibility56/Overrides.cpp [hunk 1]
```diff
@@ -42,6 +42,7 @@ struct ConcurrencyOverrideSection {
 ConcurrencyOverrideSection Swift56ConcurrencyOverrides
 __attribute__((used, section("__DATA,__s_async_hook"))) = {
   .version = 0,
+  .task_create_common = swift56override_swift_task_create_common,
```
Comment (mikeash) [inline stdlib/toolchain/Compatibility56/Overrides.cpp:45]: Since this override doesn't do anything on 32-bit, do we want to move/copy the `#if` here and not override at all in that case?

**Review by mikeash — APPROVED** [review]
One tiny optimization possibility but LGTM.

**Review by DougGregor — APPROVED** [review]

**Comment by rjmccall** [comment]
@swift-ci Please test

File: stdlib/toolchain/Compatibility56/Overrides.cpp (hunk 1 above)
Comment (etcwilde) [reply stdlib/toolchain/Compatibility56/Overrides.cpp:45]: The `#if`should  be around `.task_create_common = swift56override_swift_task_create_common,`, not `future_wait`.

**Review by etcwilde — CHANGES_REQUESTED** [review]
The `#if` should be around `.task_create_common = swift56override_swift_task_create_common,`, not future_wait in `Overrides.cpp`

**Comment by rjmccall** [comment]
@swift-ci Please test

**Comment by rjmccall** [comment]
> The `#if` should be around `.task_create_common = swift56override_swift_task_create_common,`, not future_wait in `Overrides.cpp`

...this is what I get for trying to rush a patch in.

**Comment by rjmccall** [comment]
@swift-ci Please test

**Review by etcwilde — APPROVED** [review]
LGTM
