### PR TITLE
[Distributed] Handle composite type in generic bound in distributed accessor

### LINKED ISSUE #67090: [Distributed] IRGenRequest crash when "Codable & SomeDistActorProtocol" are used and returned from dist runc
rdar://111664985

The attached state of the distributed cluster repo crashes because of this line:

where we add the `Codable` here, since 
```
struct ClusterSingletonRemoteCallInterceptor<Singleton: Codable & ClusterSingleton>: RemoteCallInterceptor {
```

The same happens if we add the Codable here, like this:

```
public protocol ClusterSingleton: Codable, DistributedActor where ActorSystem == ClusterSystem {

// was:
// public protocol ClusterSingleton: DistributedActor where ActorSystem == ClusterSystem {
```

Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -c -filelist /var/folders/hn/c22y4jsn4j74mw23_kpgn88w0000gn/T/TemporaryDirectory.YsFwAT/sources-1 -primary-file /Users/ktoso/code/swift-distributed-actors/Sources/DistributedCluster/Plugins/ClusterSingleton/ClusterSingletonBoss.swift -emit-dependencies-path /Users/ktoso/code/swift-distributed-actors/.build/arm64-apple-macosx/debug/DistributedCluster.build/Plugins/ClusterSingleton/ClusterSingletonBoss.d -emit-reference-dependencies-path /Users/ktoso/code/swift-distributed-actors/.build/arm64-apple-macosx/debug/DistributedCluster.build/Plugins/ClusterSingleton/ClusterSingletonBoss.swiftdeps -target arm64-apple-macosx13.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -stack-check -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -I /Users/ktoso/code/swift-distributed-actors/.build/arm64-apple-macosx/debug -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -color-diagnostics -enable-testing -g -module-cache-path /Users/ktoso/code/swift-distributed-actors/.build/arm64-apple-macosx/debug/ModuleCache -swift-version 5 -Onone -D SWIFT_PACKAGE -D DEBUG -new-driver-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-driver -empty-abi-descriptor -plugin-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/lib/swift/host/plugins -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -fmodule-map-file=/Users/ktoso/code/swift-distributed-actors/.build/arm64-apple-macosx/debug/CBacktrace.build/module.modulemap -Xcc -I -Xcc /Users/ktoso/code/swift-distributed-actors/.build/checkouts/swift-backtrace/Sources/CBacktrace/include -Xcc -fmodule-map-file=/Users/ktoso/code/swift-distributed-actors/.build/arm64-apple-macosx/debug/CNIOLLHTTP.build/module.modulemap -Xcc -I -Xcc /Users/ktoso/code/swift-distributed-actors/.build/checkouts/swift-nio/Sources/CNIOLLHTTP/include -Xcc -fmodule-map-file=/Users/ktoso/code/swift-distributed-actors/.build/arm64-apple-macosx/debug/CNIOBoringSSLShims.build/module.modulemap -Xcc -I -Xcc /Users/ktoso/code/swift-distributed-actors/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSLShims/include -Xcc -fmodule-map-file=/Users/ktoso/code/swift-distributed-actors/.build/arm64-apple-macosx/debug/CNIOBoringSSL.build/module.modulemap -Xcc -I -Xcc /Users/ktoso/code/swift-distributed-actors/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/include -Xcc -fmodule-map-file=/Users/ktoso/code/swift-distributed-actors/.build/arm64-apple-macosx/debug/CNIODarwin.build/module.modulemap -Xcc -I -Xcc /Users/ktoso/code/swift-distributed-actors/.build/checkouts/swift-nio/Sources/CNIODarwin/include -Xcc -fmodule-map-file=/Users/ktoso/code/swift-distributed-actors/.build/checkouts/swift-nio/Sources/CNIOWindows/include/module.modulemap -Xcc -I -Xcc /Users/ktoso/code/swift-distributed-actors/.build/checkouts/swift-nio/Sources/CNIOWindows/include -Xcc -fmodule-map-file=/Users/ktoso/code/swift-distributed-actors/.build/arm64-apple-macosx/debug/CNIOLinux.build/module.modulemap -Xcc -I -Xcc /Users/ktoso/code/swift-distributed-actors/.build/checkouts/swift-nio/Sources/CNIOLinux/include -Xcc -fmodule-map-file=/Users/ktoso/code/swift-distributed-actors/.build/arm64-apple-macosx/debug/CNIOAtomics.build/module.modulemap -Xcc -I -Xcc /Users/ktoso/code/swift-distributed-actors/.build/checkouts/swift-nio/Sources/CNIOAtomics/include -Xcc -fmodule-map-file=/Users/ktoso/code/swift-distributed-actors/.build/checkouts/swift-atomics/Sources/_AtomicsShims/include/module.modulemap -Xcc -I -Xcc /Users/ktoso/code/swift-distributed-actors/.build/checkouts/swift-atomics/Sources/_AtomicsShims/include -Xcc -fmodule-map-file=/Users/ktoso/code/swift-distributed-actors/.build/arm64-apple-macosx/debug/CDistributedActorsMailbox.build/module.modulemap -Xcc -I -Xcc /Users/ktoso/code/swift-distributed-actors/Sources/CDistributedActorsMailbox/include -Xcc -isysroot -Xcc /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -Xcc -F -Xcc /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -Xcc -fPIC -module-name DistributedCluster -disable-clang-spi -target-sdk-version 14.0 -target-sdk-name macosx14.0 -parse-as-library -o /Users/ktoso/code/swift-distributed-actors/.build/arm64-apple-macosx/debug/DistributedCluster.build/Plugins/ClusterSingleton/ClusterSingletonBoss.swift.o -index-store-path /Users/ktoso/code/swift-distributed-actors/.build/arm64-apple-macosx/debug/index/store -index-system-modules
1.	Apple Swift version 5.9 (swiftlang-5.9.0.121 clang-1500.0.35.1)
2.	Compiling with the current language version
3.	Contents of /var/folders/hn/c22y4jsn4j74mw23_kpgn88w0000gn/T/TemporaryDirectory.YsFwAT/sources-1:
---
...
4.	While evaluating request IRGenRequest(IR Generation for file "/Users/ktoso/code/swift-distributed-actors/Sources/DistributedCluster/Plugins/ClusterSingleton/ClusterSingletonBoss.swift")
5.	While emitting IR SIL function "@$s18DistributedCluster0B13SingletonBossC09hasActiveC0xSgyYaKFTE".
 for 'hasActiveSingleton()' (in module 'DistributedCluster')

### PR DESCRIPTION
**Pull request by ktoso**
**Description:** It seems a distributed accessor's emit fails for `DistributedActor & Somethign`, the crash is in `IGM.getTypeInfo(directResultTy);` because the method does not have access to a generic context; The solution is to provide it earlier during emit rather than later as we did before.
**See Also:** Resolves a FIXME in distributed cluster: https://github.com/apple/swift-distributed-actors/pull/1127/files#diff-7da4ba0dfda5902083a859fdf6d209fb5902d4926b6bee24fa7eee420b84b4e3R231
**Risk:** Low, only moves the generic scope a few lines earlier, since we use it there already
**Review @xedin @drexin 
**Testing:** CI testing
**Radar:** rdar://111664985
Resolves: https://github.com/apple/swift/issues/67090

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please test

File: lib/IRGen/GenDistributed.cpp [hunk 1]
```diff
@@ -616,6 +616,8 @@ void DistributedAccessor::emit() {
 
   auto params = IGF.collectParameters();
 
+  GenericContextScope scope(IGM, targetTy->getInvocationGenericSignature());
```
Comment (ktoso) [inline lib/IRGen/GenDistributed.cpp:619]: The fix™ is that this must be made before the IGM `getTypeInfo` call, otherwise the generic context is not available (null) and we crash.

**Review by drexin — APPROVED** [review]
LGTM

**Review by xedin — APPROVED** [review]
