### PR TITLE
[Mangler] Handle local archetypes in `getDeclTypeForMangling`

### LINKED ISSUE #78690: USR mangling doesn't handle local archetypes
The following test case crashes SourceKit:

```swift
func foo<each T>(_ xs: repeat each T) {
  for x in repeat each xs {
    // RUN: %sourcekitd-test -req=cursor -pos=%(line-1):7 %s -- %s
  }
}
```

```
{
  key.request: source.request.cursorinfo,
  key.offset: 2767,
  key.sourcefile: "/Users/hamish/src/swift-test-arena/swift-test-arena/main.swift",
  key.primary_file: "/Users/hamish/src/swift-test-arena/swift-test-arena/main.swift",
  key.compilerargs: [
    "/Users/hamish/src/swift-test-arena/swift-test-arena/main.swift"
  ]
}
Cannot mangle free-standing archetype: (element_archetype_type address=0x11ea0baa0 conforms_to="Swift.(file).Copyable" conforms_to="Swift.(file).Escapable" opened_element_id="7F7D30B0-D452-11EF-BBBD-4A10B34A40AC")
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      While evaluating request USRGenerationRequest(main.(file).foo(_:).x@/Users/hamish/src/swift-test-arena/swift-test-arena/main.swift:168:7)
fish: Job 1, './sourcekitd-test -req=cursor -…' terminated by signal SIGABRT (Abort)
```

```
Swift version 6.2-dev (LLVM bb5a46203470a96, Swift 192bb334093ddfa)
Target: arm64-apple-darwin24.2.0
```

### PR DESCRIPTION
**Pull request by hamishknight**
Element archetypes can occur here when mangling the USR for local variables for e.g SourceKit cursor info, as well as for regular compilation for things like lazy variables.

Update `getDeclTypeForMangling` to map local archetypes out of context, using both the captured generic environments and the archetypes present in the type. More work is needed to support lazy variable though (now it crashes in SILGen).

This patch doesn't handle mangling standalone element archetypes for e.g `printTypeUSR`, ideally we'd fix the clients there to not pass local archetypes.

rdar://145737847

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

File: lib/AST/ASTMangler.cpp [hunk 1]
```diff
@@ -2372,6 +2376,20 @@ void ASTMangler::appendImplFunctionType(SILFunctionType *fn,
...
+void ASTMangler::appendElementArchetype(ElementArchetypeType *archetype,
+                                        GenericSignature sig,
+                                        const ValueDecl *forDecl) {
+  ASSERT(forDecl && "Can currently only mangle element archetypes for a Decl");
+  CaptureInfo captureInfo;
+  if (auto fn = AnyFunctionRef::fromDeclContext(forDecl->getDeclContext()))
+    captureInfo = fn->getCaptureInfo();
+
+  auto interfaceTy = mapLocalArchetypesOutOfContext(
+      archetype, sig, captureInfo.getGenericEnvironments());
```
Comment (slavapestov) [inline lib/AST/ASTMangler.cpp:2388]: Why not just call mapLocalArchetypesOutOfContext() before calling into the mangler?

**Review by slavapestov — CHANGES_REQUESTED** [review]

**Comment by slavapestov** [comment]
I'm afraid this is not the correct fix. It sounds like there is an issue with `lazy` variables, and something separate with CursorInfo.

**Comment by slavapestov** [comment]
For `lazy` vars it appears you need to change `appendAccessorEntity()` to do the same thing as `appendClosureComponents()` when the accessor in question is a local function.

File: lib/AST/ASTMangler.cpp (hunk 1 above)
Comment (hamishknight) [reply lib/AST/ASTMangler.cpp:2388]: Not sure if this is what you're asking for, but could move this to `getDeclTypeForMangling` instead? I don't really have any strong opinions one way or the other

**Comment by hamishknight** [comment]
> It sounds like there is an issue with `lazy` variables, and something separate with CursorInfo

It's the same underlying issue; we can't mangle a decl with an interface type that contains a local archetype

> Neither of these should require anything resembling a complete rethink of local archetypes to resolve.

Right, I was referring to handling standalone local archetypes for e.g `printTypeUSR`

> For `lazy` vars it appears you need to change `appendAccessorEntity()` to do the same thing as `appendClosureComponents()` when the accessor in question is a local function.

Is there any advantage to doing this over handling it generally for any decl?

**Comment by hamishknight** [comment]
@swift-ci please test

File: lib/AST/ASTMangler.cpp (hunk 1 above)
Comment (hamishknight) [reply lib/AST/ASTMangler.cpp]: Updated to move into `getDeclTypeForMangling`, how does this look @slavapestov?

**Comment by hamishknight** [comment]
@swift-ci please test Windows

File: lib/AST/LocalArchetypeRequirementCollector.cpp [hunk 2]
```diff
@@ -183,13 +183,29 @@ Type MapLocalArchetypesOutOfContext::getInterfaceType(
     ++depth;
   }
 
+  // If the environment we have is not for a capture, this must be a generic
+  // environment local to the parent function. For element archetypes, the depth
+  // we have is relative to the parent signature, so we can compute the correct
+  // depth by offsetting it by the number of parent captured environments.
```
Comment (slavapestov) [inline lib/AST/LocalArchetypeRequirementCollector.cpp:189]: This might not be correct if you have multiple nested `for` loops over packs. What causes us to end up in this code path?

Comment (hamishknight) [reply lib/AST/LocalArchetypeRequirementCollector.cpp:189]: This handles e.g:

```swift
func foo<each T>(_ xs: repeat each T) {
  for x in repeat each xs {}
}
```

There is no captured environment for `x`, it's local to the function itself. Multiple nested should be fine since we track the parent generic signature in the statement checker, let me update the test case

**Comment by hamishknight** [comment]
@swift-ci please test

File: lib/AST/LocalArchetypeRequirementCollector.cpp (hunk 2 above)
Comment (hamishknight) [reply lib/AST/LocalArchetypeRequirementCollector.cpp:189]: Oh hrm, looks like it doesn't work in a closure 🤔 Seems like we don't pass down the innermost element environment

Comment (hamishknight) [reply lib/AST/LocalArchetypeRequirementCollector.cpp:189]: That isn't really an issue with this patch though, this crashes on main:

```swift
func foo<each T>(xs: repeat each T) {
  _ = {
    for x in repeat each xs {
      for y in repeat each xs {
        return (x, y)
      }
    }
  }
}
```

**Comment by hamishknight** [comment]
@swift-ci please test

File: lib/AST/ASTMangler.cpp [hunk 3]
```diff
@@ -4016,6 +4016,43 @@ static bool isMethodDecl(const Decl *decl) {
...
+  CaptureInfo captureInfo;
+  auto *innerDC = decl->getInnermostDeclContext();
+  auto genericSig = innerDC->getGenericSignatureOfContext();
+  if (auto fn = AnyFunctionRef::fromDeclContext(innerDC))
+    captureInfo = fn->getCaptureInfo();
+
+  // Record any captured generic environments we have.
+  llvm::SmallSetVector<GenericEnvironment *, 4> capturedEnvs;
+  for (auto *genericEnv : captureInfo.getGenericEnvironments())
+    capturedEnvs.insert(genericEnv);
```
Comment (hamishknight) [inline lib/AST/ASTMangler.cpp:4041]: In principle I think we could purely rely on gathering them from the type, but I don't think there's any harm in doing this and it's more consistent with the closure logic. I don't feel strongly about it though.

**Comment by hamishknight** [comment]
@slavapestov How does this look?

**Review by slavapestov — APPROVED** [review]
