### PR TITLE
[CSDiagnostics] Add diagnostics for holes in generic parameter packs

### LINKED ISSUE #69432: Passing nil to a parameter pack fails to produce diagnostic for expression
**Description**
Passing nil to a parameter pack fails to produce diagnostic for expression. This of course is invalid code but a good diagnostic would be nice to have.

**Steps to reproduce**
```swift
func foo<each T>(_ bar: repeat each T) { }

foo(nil) // Failed to produce diagnostic for expression; please submit a bug report
```

**Expected behavior**
Build error with appropriate diagnostic.

**Environment**
- Swift compiler version info
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1) 
Target: arm64-apple-macosx14.0
- Xcode version info
Xcode 15.0.1
Build version 15A507
- Deployment target:
macOS 14.0

### PR DESCRIPTION
**Pull request by li3zhen1**
Removed `TVO_CanBindToHole` flag in `ConstraintSystem::openGenericParameter` when generic parameter is parameter pack, so that passing `nil` to generic parameter pack produces fix correctly.

Resolves #69432 .

### Before

```swift
func foo<each T>(_ bar: repeat each T) { }

foo(nil) // Failed to produce diagnostic for expression; please submit a bug report
```

### After

```swift
func foo<each T>(_ bar: repeat each T) { }

foo(1, "hello", 2) // OK

foo(nil) // error: 'nil' requires a contextual type

foo(1, nil) // error: 'nil' requires a contextual type
```

Diagnostic messages:
```
/Projects/SwiftPlayground/Sources/main.swift:5:5: error: 'nil' requires a contextual type
foo(nil)
    ^
/Projects/SwiftPlayground/Sources/main.swift:7:8: error: 'nil' requires a contextual type
foo(1, nil)
```

### CODE REVIEW

File: lib/Sema/ConstraintSystem.cpp [hunk 1]
```diff
@@ -2022,7 +2022,7 @@ TypeVariableType *ConstraintSystem::openGenericParameter(
   if (parameter->isParameterPack())
     options |= TVO_CanBindToPack;
 
-  if (shouldAttemptFixes())
+  else if (shouldAttemptFixes())
     options |= TVO_CanBindToHole;
```
Comment (xedin) [inline lib/Sema/ConstraintSystem.cpp:2026]: Let's do this slightly differently so it a bit more readable:

```
if (shouldAttemptFixes())
    options |= TVO_CanBindToHole;

  if (parameter->isParameterPack()) {
    options |= TVO_CanBindToPack;
    options -= TVO_CanBindToHole;
  }
```

**Comment by xedin** [comment]
One more thing - please add test-cases from description to `test/Constraints/variadic_generic_functions.swift` and we’d be good to go!

File: lib/Sema/ConstraintSystem.cpp (hunk 1 above)
Comment (li3zhen1) [reply lib/Sema/ConstraintSystem.cpp:2023]: Hi! Just pushed the suggested version. But I found this is not fixed:

```swift
struct S<each T> {
    init(_ values: repeat each T) {}
}

let _ = S.init(1, nil) // OK, Correct diagnosis: 'nil' requires a contextual type
let _ = S.init(1, nil) // OK, Correct diagnosis: 'nil' requires a contextual type
let _ = S(1, nil) // OK, Correct diagnosis: 'nil' requires a contextual type
let _ = S(nil) // ❌
```

Any idea on this?

```
Assertion failed: (!fixed->is<TypeVariableType>() && "Cannot bind to type variable; merge equivalence classes instead"), function bindTypeVariable, file ConstraintGraph.cpp, line 605.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend /Users/lizhen/Projects/SwiftPlayground/Sources/main.swift -typecheck
1.	Swift version 5.11-dev (LLVM c4000d8995e87b5, Swift 6fdfd7ea81a5c12)
2.	Compiling with the current language version
3.	While evaluating request TypeCheckSourceFileRequest(source_file "/Users/lizhen/Projects/SwiftPlayground/Sources/main.swift")
4.	While type-checking statement at [/Users/lizhen/Projects/SwiftPlayground/Sources/main.swift:8:1 - line:8:14] RangeText="let a = A(nil"
5.	While type-checking declaration 0x13d19b8f8 (at /Users/lizhen/Projects/SwiftPlayground/Sources/main.swift:8:1)
6.	While evaluating request PatternBindingEntryRequest((unknown decl), 0)
7.	While type-checking expression at [/Users/lizhen/Projects/SwiftPlayground/Sources/main.swift:8:9 - line:8:14] RangeText="A(nil"
8.	While type-checking-target starting at /Users/lizhen/Projects/SwiftPlayground/Sources/main.swift:8:9
 #0 0x000000010832ea38 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x105536a38)
 #1 0x000000010832d228 llvm::sys::RunSignalHandlers() (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x105535228)
 #2 0x000000010832f080 SignalHandler(int) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x105537080)
 #3 0x0000000184755a24 (/usr/lib/system/libsystem_platform.dylib+0x18046da24)
 #4 0x0000000184725cc0 (/usr/lib/system/libsystem_pthread.dylib+0x18043dcc0)
 #5 0x0000000184631a40 (/usr/lib/system/libsystem_c.dylib+0x180349a40)
 #6 0x0000000184630d30 (/usr/lib/system/libsystem_c.dylib+0x180348d30)
 #7 0x0000000108711b98 swift::constraints::ConstraintGraph::bindTypeVariable(swift::TypeVariableType*, swift::Type) (.cold.4) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x105919b98)
 #8 0x00000001040defc8 swift::constraints::ConstraintGraph::bindTypeVariable(swift::TypeVariableType*, swift::Type) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1012e6fc8)
 #9 0x00000001040f126c swift::constraints::ConstraintSystem::assignFixedType(swift::TypeVariableType*, swift::Type, bool, bool) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1012f926c)
#10 0x0000000104030ef0 swift::constraints::ConstraintSystem::matchTypesBindTypeVar(swift::TypeVariableType*, swift::Type, swift::constraints::ConstraintKind, swift::optionset::OptionSet<swift::constraints::ConstraintSystem::TypeMatchFlags, unsigned int>, swift::constraints::ConstraintLocatorBuilder, llvm::function_ref<swift::constraints::ConstraintSystem::TypeMatchResult ()>) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x101238ef0)
#11 0x000000010402669c swift::constraints::ConstraintSystem::matchTypes(swift::Type, swift::Type, swift::constraints::ConstraintKind, swift::optionset::OptionSet<swift::constraints::ConstraintSystem::TypeMatchFlags, unsigned int>, swift::constraints::ConstraintLocatorBuilder) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x10122e69c)
#12 0x0000000104050484 swift::constraints::ConstraintSystem::simplifyConstraint(swift::constraints::Constraint const&) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x101258484)
#13 0x0000000104064f74 swift::constraints::ConstraintSystem::simplify() (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x10126cf74)
#14 0x0000000103fee970 swift::constraints::TypeVariableBinding::attempt(swift::constraints::ConstraintSystem&) const (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1011f6970)
#15 0x000000010407b2fc swift::constraints::BindingStep<swift::constraints::TypeVarBindingProducer>::take(bool) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1012832fc)
#16 0x0000000104067090 swift::constraints::ConstraintSystem::solveImpl(llvm::SmallVectorImpl<swift::constraints::Solution>&) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x10126f090)
#17 0x00000001040ff3b0 swift::constraints::ConstraintSystem::salvage() (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1013073b0)
#18 0x0000000104068610 swift::constraints::ConstraintSystem::solve(swift::constraints::SyntacticElementTarget&, swift::FreeTypeVariableBinding) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x101270610)
#19 0x00000001041e3c7c swift::TypeChecker::typeCheckTarget(swift::constraints::SyntacticElementTarget&, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1013ebc7c)
#20 0x00000001041e3afc swift::TypeChecker::typeCheckExpression(swift::constraints::SyntacticElementTarget&, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1013ebafc)
#21 0x00000001041e4bf8 swift::TypeChecker::typeCheckBinding(swift::Pattern*&, swift::Expr*&, swift::DeclContext*, swift::Type, swift::PatternBindingDecl*, unsigned int, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1013ecbf8)
#22 0x00000001041e4e2c swift::TypeChecker::typeCheckPatternBinding(swift::PatternBindingDecl*, unsigned int, swift::Type, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1013ece2c)
#23 0x00000001042b2c3c swift::PatternBindingEntryRequest::evaluate(swift::Evaluator&, swift::PatternBindingDecl*, unsigned int) const (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1014bac3c)
#24 0x00000001046a8ef4 swift::PatternBindingEntryRequest::OutputType swift::Evaluator::getResultUncached<swift::PatternBindingEntryRequest, swift::PatternBindingEntryRequest::OutputType swift::evaluateOrDefault<swift::PatternBindingEntryRequest>(swift::Evaluator&, swift::PatternBindingEntryRequest, swift::PatternBindingEntryRequest::OutputType)::'lambda'()>(swift::PatternBindingEntryRequest const&, swift::PatternBindingEntryRequest::OutputType swift::evaluateOrDefault<swift::PatternBindingEntryRequest>(swift::Evaluator&, swift::PatternBindingEntryRequest, swift::PatternBindingEntryRequest::OutputType)::'lambda'()) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1018b0ef4)
#25 0x000000010467767c swift::PatternBindingDecl::getCheckedPatternBindingEntry(unsigned int) const (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x10187f67c)
#26 0x0000000104229044 (anonymous namespace)::DeclChecker::visit(swift::Decl*) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x101431044)
#27 0x0000000104228bac swift::TypeChecker::typeCheckDecl(swift::Decl*) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x101430bac)
#28 0x00000001042aa44c swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1014b244c)
#29 0x00000001042a8a90 bool (anonymous namespace)::StmtChecker::typeCheckStmt<swift::BraceStmt>(swift::BraceStmt*&) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1014b0a90)
#30 0x00000001042a8b40 swift::TypeChecker::typeCheckTopLevelCodeDecl(swift::TopLevelCodeDecl*) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1014b0b40)
#31 0x00000001042e4df4 swift::TypeCheckSourceFileRequest::evaluate(swift::Evaluator&, swift::SourceFile*) const (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1014ecdf4)
#32 0x00000001042e6860 swift::TypeCheckSourceFileRequest::OutputType swift::Evaluator::getResultUncached<swift::TypeCheckSourceFileRequest, swift::TypeCheckSourceFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckSourceFileRequest>(swift::Evaluator&, swift::TypeCheckSourceFileRequest, swift::TypeCheckSourceFileRequest::OutputType)::'lambda'()>(swift::TypeCheckSourceFileRequest const&, swift::TypeCheckSourceFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckSourceFileRequest>(swift::Evaluator&, swift::TypeCheckSourceFileRequest, swift::TypeCheckSourceFileRequest::OutputType)::'lambda'()) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1014ee860)
#33 0x00000001042e4cf0 swift::performTypeChecking(swift::SourceFile&) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1014eccf0)
#34 0x0000000103224414 bool llvm::function_ref<bool (swift::SourceFile&)>::callback_fn<swift::CompilerInstance::performSema()::$_7>(long, swift::SourceFile&) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x10042c414)
#35 0x000000010321e1b0 swift::CompilerInstance::forEachFileToTypeCheck(llvm::function_ref<bool (swift::SourceFile&)>) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1004261b0)
#36 0x000000010321e0f4 swift::CompilerInstance::performSema() (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1004260f4)
#37 0x0000000102ffef60 withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x100206f60)
#38 0x0000000102ff08e8 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1001f88e8)
#39 0x0000000102fef944 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1001f7944)
#40 0x0000000102e2b0d4 swift::mainEntry(int, char const**) (/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend+0x1000330d4)
#41 0x00000001843a50e0
```

Comment (xedin) [reply lib/Sema/ConstraintSystem.cpp:2023]: This looks like a bigger issue where the solver is trying to bind type variables together, most likely inference problem. I think we can land this change and fix `S(nil)` in a separate PR.

Comment (xedin) [reply lib/Sema/ConstraintSystem.cpp:2023]: I will take a look at the `-debug-constraints` and give you some pointers on Monday.

Comment (li3zhen1) [reply lib/Sema/ConstraintSystem.cpp:2023]: Thanks! Shall I remove `S(nil)` from test cases?

Comment (xedin) [reply lib/Sema/ConstraintSystem.cpp:2023]: Leave the improved ones but not `S(nil)` we still want to make sure that these don’t regress :)

Comment (li3zhen1) [reply lib/Sema/ConstraintSystem.cpp:2023]: Okay. But sorry that I've already broke the test with this PR 🥲. I'll try to look into this.

```swift
Command Output (stderr):
--
/Users/lizhen/Projects/swift-projects/swift/test/Constraints/variadic_generic_functions.swift:35:68: error: incorrect message found
  multipleParameters(xs: "", 5.0, ys: 5.0, "") // expected-error {{conflicting arguments to generic parameter 'each T' ('Pack{Double, String}' vs. 'Pack{String, String}' vs. 'Pack{String, Double}' vs. 'Pack{Double, Double}')}}
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                   conflicting arguments to generic parameter 'each T' ('Pack{Double, Double}' vs. 'Pack{Double, String}' vs. 'Pack{String, Double}' vs. 'Pack{String, String}')
/Users/lizhen/Projects/swift-projects/swift/test/Constraints/variadic_generic_functions.swift:75:60: error: expected note not produced
  func foo<each T>(_: repeat each T = bar().element) {} // expected-note {{in call to function 'foo'}}
                                                       ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/Users/lizhen/Projects/swift-projects/swift/test/Constraints/variadic_generic_functions.swift:77:6: error: expected error not produced
  // expected-error@-2 {{value pack expansion can only appear inside a function argument list, tuple element, or as the expression of a for-in loop}}
~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/lizhen/Projects/swift-projects/swift/test/Constraints/variadic_generic_functions.swift:78:26: error: incorrect message found
  // expected-error@-3 {{generic parameter 'each T' could not be inferred}}
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                         type of expression is ambiguous without a type annotation

--

********************
********************
Failed Tests (1):
  Swift(macosx-arm64) :: Constraints/variadic_generic_functions.swift
```

Comment (li3zhen1) [reply lib/Sema/ConstraintSystem.cpp:2023]: Hi, I think I fixed this issue this approach:

> Other way of approaching this would be in TypeVariableBinding::fixForHole to check whether TypeVar's locator ends with PackElement and if so either:
> a. Create and record a new fix that is going to produce a diagnostic similar to type of pack expansion 'each T' cannot be inferred'.

It passes all the test under `test/Constraints` (Crash of `S(nil)` remains still)

**Comment by xedin** [comment]
@li3zhen1 So I've been looking at the the constraint system state with these problematic cases and I'm thinking that we should just produce a tailored fixed for each pack element that cannot be inferred with diagnostic like 'cannot infer pack element #<number> from context` and a tailored version of that when it's converted to `nil` (that shouldn't be hard to detect because the locator for `pack element` is going to have ApplyArgToParam in the path for these cases). 

It seems reasonable to let pack element to be bound to a hole and propagate that to the `nil` type variable instead of other way around because we don't want to attempt binding `nil` directly until absolutely necessary.

File: lib/Sema/CSBindings.cpp [hunk 2]
```diff
@@ -2551,12 +2551,27 @@ TypeVariableBinding::fixForHole(ConstraintSystem &cs) const {
...
+
+      SourceRange range;
+      ConstraintLocator* eltDstLocator = simplifyLocator(cs, dstLocator, range);
+
+      // `nil` appears as an element of generic pack params, let's record a
+      // specify contextual type for nil fix.
+      if (isExpr<NilLiteralExpr>(eltDstLocator->getAnchor())) {
+        ConstraintFix *fix =
+          SpecifyContextualTypeForNil::create(cs, eltDstLocator);
+        return std::make_pair(fix, /*impact=*/(unsigned)10);
```
Comment (li3zhen1) [inline lib/Sema/CSBindings.cpp:2569]: I tested this with your fix from #71756 , everything should be good now:

```swift
/Users/lizhen/Projects/swift-debug/generic_pack.swift:5:19: error: 'nil' requires a contextual type
_ = foo(value: 1, nil)
                  ^
/Users/lizhen/Projects/swift-debug/generic_pack.swift:11:34: error: 'nil' requires a contextual type
bar(1, 5, "Hello", foo(value: 1, nil), u: 3, w: 4, 8, nil)
                                 ^
/Users/lizhen/Projects/swift-debug/generic_pack.swift:11:55: error: 'nil' requires a contextual type
bar(1, 5, "Hello", foo(value: 1, nil), u: 3, w: 4, 8, nil)
                                                      ^
/Users/lizhen/Projects/swift-debug/generic_pack.swift:19:7: error: 'nil' requires a contextual type
_ = S(nil)
      ^
/Users/lizhen/Projects/swift-debug/generic_pack.swift:20:12: error: 'nil' requires a contextual type
_ = S.init(nil)
           ^
/Users/lizhen/Projects/swift-debug/generic_pack.swift:22:10: error: 'nil' requires a contextual type
_ = S(1, nil)
         ^
/Users/lizhen/Projects/swift-debug/generic_pack.swift:23:15: error: 'nil' requires a contextual type
_ = S.init(2, nil)
              ^
```

File: lib/Sema/CSBindings.cpp [hunk 3]
```diff
@@ -2551,12 +2551,27 @@ TypeVariableBinding::fixForHole(ConstraintSystem &cs) const {
...
+      }
+
+      // The hole in a generic pack parameter can not be inferred
+      ConstraintFix *fix = SpecifyTypeForPlaceholder::create(cs, eltDstLocator);
```
Comment (li3zhen1) [inline lib/Sema/CSBindings.cpp:2573]: I couldn't think of an example that triggers `cannot infer pack element # from context`, could you name some?

File: lib/Sema/ConstraintSystem.cpp [hunk 4]
```diff
@@ -5886,9 +5887,28 @@ void constraints::simplifyLocator(ASTNode &anchor,
...
       if (auto *args = anchorExpr->getArgs()) {
-        if (elt->getArgIdx() < args->size()) {
+        if (hasEltPack) {
+          if (elt->getArgIdx() + eltPackIdx < args->size()) {
+            anchor = args->getExpr(elt->getArgIdx() + eltPackIdx);
+            path = path.slice(3);
+            continue;
+          }
+        }
+        else if (elt->getArgIdx() < args->size()) {
```
Comment (li3zhen1) [inline lib/Sema/ConstraintSystem.cpp:5911]: This offset of pack element is originally added to avoid casting a generic pack like `1, 2, nil` into an expression when calling `SpecifyContextualTypeForNil::diagnoseAsError()`. But since I'm using `simplifyConstriant` in `fixForFole` now, the expression being diagnosed is already narrowed down to `nil`. should I still keep this?

File: lib/Sema/CSBindings.cpp (hunk 3 above)
Comment (xedin) [reply lib/Sema/CSBindings.cpp:2573]: What I was trying to say in my previous comment is that I think we need to add a new ConstraintFix and a new diagnostic to accompany it and record it in `TypeVariableBinding::fixForHole` when the dstLocator ends with `PackElement`.

**Comment by li3zhen1** [comment]
> @li3zhen1 So I've been looking at the the constraint system state with these problematic cases and I'm thinking that we should just produce a tailored fixed for each pack element that cannot be inferred with diagnostic like 'cannot infer pack element # from context`and a tailored version of that when it's converted to`nil`(that shouldn't be hard to detect because the locator for`pack element` is going to have ApplyArgToParam in the path for these cases).
> 
> It seems reasonable to let pack element to be bound to a hole and propagate that to the `nil` type variable instead of other way around because we don't want to attempt binding `nil` directly until absolutely necessary.

How about this?

Screenshot 2024-02-22 at 11 36 37

**Comment by xedin** [comment]
Sorry, I'm trying to decide how I keep about all of the locators manipulation that is going on here.

File: lib/Sema/CSDiagnostics.cpp [hunk 5]
```diff
@@ -8187,6 +8187,50 @@ bool UnableToInferClosureReturnType::diagnoseAsError() {
...
+    }
+    else {
+      // unable to infer the type of an element of generic pack params
+      emitDiagnostic(diag::could_not_infer_pack_element, packElementElt->getIndex());
+    }
+
+    // emit callee side diagnostics
+    auto applyExpr = castToExpr<ApplyExpr>(locator->getAnchor());
+    if (auto* Fn = applyExpr->getFn()) {
+      if (const auto DeclRef = Fn->getReferencedDecl()) {
```
Comment (xedin) [inline lib/Sema/CSDiagnostics.cpp:8218]: This would only work for non-overloaded cases like you have with`bar` in all other cases you'd have to retrieve the overload selected for a given solution using `FailureDiagnostic::getOverloadChoice(ConstraintLocator *)`, it would be good to add a few test-cases with overloads too!

File: lib/Sema/CSDiagnostics.cpp [hunk 6]
```diff
@@ -8187,6 +8187,50 @@ bool UnableToInferClosureReturnType::diagnoseAsError() {
   return true;
 }
 
+bool UnableToInferGenericPackElementType::diagnoseAsError() {
+
+  const auto* locator = getLocator();
+  auto path = locator->getPath();
+
+  if (path.size() > 1) {
```
Comment (xedin) [inline lib/Sema/CSDiagnostics.cpp:8195]: The way everything is setup today I don't think you need any of this checking in the `path`. The fix is always going to be with locator that ends on `PackElement` and `simplifyLocator` changes take care of resolving `anchor` correctly, so I think this whole method could be simplified down to:

```c++
auto *locator = getLocator();
auto *elementLoc = locator->castLastElementTo<LocatorPathElt::PackElement>();
if (isExpr<NilLiteralExpr>(getAnchor())) {
  emitDiagnostic(diag::unresolved_nil_literal);
} else {
  // unable to infer the type of an element of generic pack params
  emitDiagnostic(diag::could_not_infer_pack_element, elementLoc->getIndex());
}

if (auto *applyExpr = getAsExpr<ApplyExpr>(locator->getAnchor())) {
   // use getCalleeLocator + getOverloadChoice to find overload and note
}

return true;
```

File: lib/Sema/ConstraintSystem.cpp [hunk 7]
```diff
@@ -5881,9 +5881,28 @@ void constraints::simplifyLocator(ASTNode &anchor,
...
```
Comment (xedin) [inline lib/Sema/ConstraintSystem.cpp:5905]: Nit: this needs `clang-format`

File: lib/Sema/ConstraintSystem.cpp [hunk 8]
```diff
@@ -5881,9 +5881,28 @@ void constraints::simplifyLocator(ASTNode &anchor,
       if (!elt)
         break;
 
+      // If the 3rd element is an PackElement, add the index of pack element within 
+      // packs to locate the correct element.
+      bool hasEltPack = false;
+      unsigned eltPackIdx = 0;
+      if (path.size() > 2) {
+        auto eltPack = path[2].getAs<LocatorPathElt::PackElement>();
```
[the remark this answers is not in the document]
Comment (li3zhen1) [reply lib/Sema/ConstraintSystem.cpp:5889]: I was thinking about `ApplyArguments -> ApplyArgToParam -> PackElement`. Did I get something wrong?

This a `-debug-constraints` result:

```swift
func foo<each T>(_ v: repeat each T) {}
_ = foo(nil)
```

```
---Solution---
Fixed score: [component: applied fix(s), value: 1] [component: hole(s), value: 1]
Type variables:
  $T0 as () @ locator@0x141018e00 [DiscardAssignment@/Users/lizhen/Projects/swift-debug/generic_pack.swift:4:1]
  $T1 as (<<placeholder for $T8>>) -> () @ locator@0x141018e68 [DeclRef@/Users/lizhen/Projects/swift-debug/generic_pack.swift:4:5]
  $T2 as Pack{<<placeholder for $T8>>} @ locator@0x141018eb0 [DeclRef@/Users/lizhen/Projects/swift-debug/generic_pack.swift:4:5 → generic parameter 'each T']
  $T3 as <<placeholder for $T8>> @ locator@0x141018fc8 [DeclRef@/Users/lizhen/Projects/swift-debug/generic_pack.swift:4:5 → pack expansion type (/* shape: $T2 */ repeat $T2)]
  $T4 as <<placeholder for $T8>> @ locator@0x141019120 [NilLiteral@/Users/lizhen/Projects/swift-debug/generic_pack.swift:4:9]
  $T5 as () @ locator@0x1410191f0 [Call@/Users/lizhen/Projects/swift-debug/generic_pack.swift:4:5 → function result]
  $T6 as () @ locator@0x141018e00 [DiscardAssignment@/Users/lizhen/Projects/swift-debug/generic_pack.swift:4:1]
  $T8 as <<placeholder for $T8>> @ locator@0x1410195b0 [Call@/Users/lizhen/Projects/swift-debug/generic_pack.swift:4:5 → apply argument → comparing call argument #0 to parameter #0 → pack element #0]

Overload choices:
  locator@0x141018e68 [DeclRef@/Users/lizhen/Projects/swift-debug/generic_pack.swift:4:5] with generic_pack.(file).foo@/Users/lizhen/Projects/swift-debug/generic_pack.swift:3:6 as foo: ($T3) -> ()
Trailing closure matching:
  locator@0x1410192b8 [Call@/Users/lizhen/Projects/swift-debug/generic_pack.swift:4:5 → apply argument]: forward
Opened types:
  locator@0x141018e68 [DeclRef@/Users/lizhen/Projects/swift-debug/generic_pack.swift:4:5] opens 'each T' (each τ_0_0) -> Pack{<<hole>>} [from $T2]
Defaulted constraints: locator@0x1410195b0 [Call@/Users/lizhen/Projects/swift-debug/generic_pack.swift:4:5 → apply argument → comparing call argument #0 to parameter #0 → pack element #0]
Fixes:
  [fix: specify pack element type] @ locator@0x1410195b0 [Call@/Users/lizhen/Projects/swift-debug/generic_pack.swift:4:5 → apply argument → comparing call argument #0 to parameter #0 → pack element #0]
/Users/lizhen/Projects/swift-debug/generic_pack.swift:4:9: error: 'nil' requires a contextual type
_ = foo(nil)
        ^
/Users/lizhen/Projects/swift-debug/generic_pack.swift:3:20: note: in inferring pack element #1 of 'v'
func foo<each T>(_ v: repeat each T) {}
                   ^
```

[the remark this answers is not in the document]
Comment (xedin) [reply lib/Sema/ConstraintSystem.cpp:5889]: I see, there is a different situation when `PackElement` is produced while matching to pack expansions but I guess that comes later, okay makes sense!

File: lib/Sema/CSDiagnostics.cpp (hunk 6 above)
Comment (li3zhen1) [reply lib/Sema/CSDiagnostics.cpp:8195]:
```swift
func patternInstantiationTupleTest1<each T>() -> (repeat Array<each T>) {}

func patternInstantiationConcreteInvalid() {
  let _: Set<Int> = patternInstantiationTupleTest1()
  // expected-error@-1 {{cannot convert value of type '(repeat Array<_>)' to specified type 'Set<Int>'}}

  let _: (Array<Int>, Set<String>) = patternInstantiationTupleTest1() // expected-error {{'(repeat Array<Int, _>)' is not convertible to '(Array<Int>, Set<String>)', tuples have a different number of elements}}
}
```

Seems like this case in `swift/test/Constraints/pack_expansion_types.swift` unintentionally hits `diag::could_not_infer_pack_element` branch without the guarding conditions.

```
Fixes:
  [fix: ignore specified contextual type] @ locator@0x1339e7800 [Call@/Users/lizhen/Projects/swift-debug/boldly.swift:4:21 → contextual type]
  [fix: specify pack element type] @ locator@0x1339e7a68 [Call@/Users/lizhen/Projects/swift-debug/boldly.swift:4:21 → contextual type → tuple type '(/* shape: $T1 */ repeat Array<$T1>)' → tuple type '(_: Set<Int>)' → tuple element #0 → pack element #0]
(failed constraint (/* shape: Pack{<<unresolvedtype>>} */ repeat Array<Pack{<<unresolvedtype>>}>) conv Set<Int> @ locator@0x134015400 [])
(increasing 'user conversion' score by 1 @ locator@0x134015400 [])
(failed constraint (/* shape: Pack{<<unresolvedtype>>} */ repeat Array<Pack{<<unresolvedtype>>}>) bridging conv Set<Int> @ locator@0x134015400 [])
/Users/lizhen/Projects/swift-debug/boldly.swift:4:21: error: cannot convert value of type '(repeat Array<_>)' to specified type 'Set<Int>'
  let _: Set<Int> = patternInstantiationTupleTest1()
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/lizhen/Projects/swift-debug/boldly.swift:4:21: error: could not infer pack element #0 from context
  let _: Set<Int> = patternInstantiationTupleTest1()
                    ^
```

Guess I should add some guards like this?

```swift
  const auto applyArgToParamElt = (path.end() - 2)->getAs<LocatorPathElt::ApplyArgToParam>();
  const auto packElementElt = (path.end() - 1)->getAs<LocatorPathElt::PackElement>();
  if (!applyArgToParamElt || !packElementElt) {
    return false;
  }
```

Comment (xedin) [reply lib/Sema/CSDiagnostics.cpp:8195]: I think that's okay, the conversion fails and the element cannot be inferred because of that. For that particular case we could detect that it's mismatch between collections and propagate the element type down to avoid the second diagnostic.

File: lib/Sema/CSDiagnostics.cpp
Comment (li3zhen1) [inline lib/Sema/CSDiagnostics.cpp:1]: Changed to 0-based indexing since I found other sema diagnostics are doing so.

File: lib/Sema/CSDiagnostics.cpp [hunk 9]
```diff
@@ -8199,6 +8199,47 @@ bool UnableToInferClosureReturnType::diagnoseAsError() {
...
+bool UnableToInferGenericPackElementType::diagnoseAsError() {
+  auto *locator = getLocator();
+  auto path = locator->getPath();
+
+  const auto applyArgToParamElt =
+      (path.end() - 2)->getAs<LocatorPathElt::ApplyArgToParam>();
+  const auto packElementElt =
+      (path.end() - 1)->getAs<LocatorPathElt::PackElement>();
+  if (!applyArgToParamElt || !packElementElt) {
+    return false;
```
Comment (xedin) [inline lib/Sema/CSDiagnostics.cpp:8211]: We shouldn't produce a fix in this case because this would just result in a fallback diagnostic this looks like more of an assert to me

Comment (xedin) [reply lib/Sema/CSDiagnostics.cpp:8211]: Just so we are on the same page here - you don't have to do it in this PR. This would have to be detected during fixing of the conversion mismatch that's when we have both Set and Array types, we can have a special case in repairFailures for collections

Comment (li3zhen1) [reply lib/Sema/CSDiagnostics.cpp:8211]: Okay, I'll try to look into this. Just one more question – is this supposed to be a generic type mismatch or the specific case for collections? 

This could also invoke the same diagnostics with the same path:

```swift

struct S<T> {
    init() {}
}

struct S2<T> {
    init() {}
}

func patternInstantiationTupleTest1<each T>() -> (repeat S<each T>) {}

func patternInstantiationConcreteInvalid() {
  let _: S2<Int> = patternInstantiationTupleTest1()
  let _: (S<Int>, S2<String>) = patternInstantiationTupleTest1()
}
```

Comment (xedin) [reply lib/Sema/CSDiagnostics.cpp:8211]: Hm, maybe it's okay to forward generic arguments upon mismatches in general if the number of expected arguments on the other side matches, so if both types are BoundGenericTypes with the same number of arguments

**Comment by xedin** [comment]
@li3zhen1 We are getting pretty close. I think all we need is to address a few remaining comments and add a few more test-cases that test newly add diagnostic.

**Comment by li3zhen1** [comment]
@xedin Sorry for the delay. I'm still trying to learn how `repairFailure` works here. Could you give more hint about this? like do I try avoid the unexpected `fixForHole` call or just silence the hole's diagnostics?

**Comment by xedin** [comment]
No rush! Regarding repairFailures, there is a simpler problem you can look at which doesn't involve variadic generics:

```
```

**Comment by xedin** [comment]
The failure to convert `Array` to `Set` here is "fixed"  via IgnoreContextualType fix - `(attempting fix [fix: ignore specified contextual type] @ locator@0x14b13f320 [Call@<stdin>:5:19 → contextual type])`

This block of code is `repairFailures` that deals with `ContextualType` locator could detect that both types are `BoundGenericType`s with the same number of arguments and use `matchTypes` (like we do in other places there) to match them, that would mean that `Int` from `Set` is propagated to type variable that opens `T` of `Array` and would avoid `generic parameter 'T' could not be inferred` failure.

**Comment by xedin** [comment]
But as I mentioned before, you don't have to fix it in this PR - you can just adjust the changed diagnostics, we'll take a look what changed and whether it makes sense.

**Comment by li3zhen1** [comment]
> We shouldn't produce a fix in this case because this would just result in a fallback diagnostic this looks like more of an assert to me

So does this mean that I should move the condition `applyArguments -> applyArgToParam -> PackElements` to `fixForHole`?

**Comment by xedin** [comment]
In general if there is a case that cannot be diagnosed, it shouldn't produce a fix just to fail a diagnostic.  If we detect that a type variable represents a pack element it shouldn't matter what path it uses because it can always fallback to newly added "cannot infer pack element ..." diagnostic right? In the diagnostic we could check for presence of `ApplyArguments` or `ArgToParam` etc. and produce tailored diagnostic messages but the fallback is always there.

**Comment by li3zhen1** [comment]
If I understand correctly, I need to either: 
- fix the unexpected `<placeholder>` first
- or add the fallback diagnostic, and allow that case to emit this `cannot infer pack element ...`
Right?

**Comment by xedin** [comment]
Not really, I think check for PackElement can be turned into an assert and check for apply arguments could be removed completely for the diagnostic.

**Comment by li3zhen1** [comment]
I see. Below is the result accordingly. Guess I can't pass the test without removing that placeholder?

```
/Users/lizhen/Projects/swift-projects/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend /Users/lizhen/Projects/swift-debug/generic_mismatch.swift -typecheck
/Users/lizhen/Projects/swift-debug/generic_mismatch.swift:9:21: error: cannot convert value of type '(repeat Array<_>)' to specified type 'Set<Int>'
 7 │ func patternInstantiationConcreteInvalid() {
 8 │
 9 │   let _: Set<Int> = patternInstantiationTupleTest1()
   │                     ╰─ error: cannot convert value of type '(repeat Array<_>)' to specified type 'Set<Int>'
10 │
11 │ }

/Users/lizhen/Projects/swift-debug/generic_mismatch.swift:9:21: error: could not infer pack element #0 from context
 7 │ func patternInstantiationConcreteInvalid() {
 8 │
 9 │   let _: Set<Int> = patternInstantiationTupleTest1()
   │                     ╰─ error: could not infer pack element #0 from context 
                              ❌  this is not expected in test case.
10 │
11 │ }
```

```cpp
bool UnableToInferGenericPackElementType::diagnoseAsError() {
  auto *locator = getLocator();
  auto path = locator->getPath();

  const auto packElementElt = (path.end() - 1)->getAs<LocatorPathElt::PackElement>();

  if (isExpr<NilLiteralExpr>(getAnchor())) {
    emitDiagnostic(diag::unresolved_nil_literal);
  } else {
    // ❌ generic mismatch hits here:
    emitDiagnostic(diag::could_not_infer_pack_element,
                   packElementElt->getIndex());
  }

  if (isExpr<ApplyExpr>(locator->getAnchor())) {
    // emit callee side diagnostics
    if (auto *calleeLocator = getSolution().getCalleeLocator(locator)) {
      if (const auto choice = getOverloadChoiceIfAvailable(calleeLocator)) {
        if (auto *decl = choice->choice.getDeclOrNull()) {
          const auto applyArgToParamElt =
              (path.end() - 2)->getAs<LocatorPathElt::ApplyArgToParam>();
          if (auto paramDecl =
                  getParameterAt(decl, applyArgToParamElt->getParamIdx())) {
            emitDiagnosticAt(
                paramDecl->getLoc(), diag::note_in_opening_pack_element,
                packElementElt->getIndex(), paramDecl->getNameStr());
          }
        }
      }
    }
  }

  return true;
}
```

File: lib/Sema/CSDiagnostics.cpp [hunk 10]
```diff
@@ -8202,20 +8202,17 @@ bool UnableToInferClosureReturnType::diagnoseAsError() {
...
 
   if (isExpr<NilLiteralExpr>(getAnchor())) {
     // `nil` appears as an element of generic pack params, let's record a
     // specify contextual type for nil fix.
     emitDiagnostic(diag::unresolved_nil_literal);
   } else {
+    if (llvm::any_of(getSolution().Fixes, [&locator](const ConstraintFix *fix) {
+          return fix->getLocator() == locator;
+        }))
+      return false;
```
Comment (li3zhen1) [inline lib/Sema/CSDiagnostics.cpp:8215]: Does this make sense?

Comment (xedin) [reply lib/Sema/CSDiagnostics.cpp:8215]: I'm not sure what are you trying to archive here, this would always return `false` because locator for diagnostic comes from the fix. What I was saying in my previous comment is that we need

```
auto packElementElt = locator->getLastElementAs<PackElement>();
assert(packElementElt);
```

That that's pretty much it.

Comment (li3zhen1) [reply lib/Sema/CSDiagnostics.cpp:8215]:
```swift 
func patternInstantiationTupleTest1<each T>() -> (repeat Array<each T>) {}

func patternInstantiationConcreteInvalid() {
  let _: Set<Int> = patternInstantiationTupleTest1()
  // expected-error@-1 {{cannot convert value of type '(repeat Array<_>)' to specified type 'Set<Int>'}}

  let _: (Array<Int>, Set<String>) = patternInstantiationTupleTest1() // expected-error {{'(repeat Array<Int, _>)' is not convertible to '(Array<Int>, Set<String>)', tuples have a different number of elements}}
}
```
This case produces 2 fix here:
```
```

Comment (xedin) [reply lib/Sema/CSDiagnostics.cpp:8215]: That's fine, let's update the test for now.

Comment (li3zhen1) [reply lib/Sema/CSDiagnostics.cpp:8215]: It passes tests for now. Is there any thing I need to add?

Comment (xedin) [reply lib/Sema/CSDiagnostics.cpp:8217]: I understand that it's passing tests but the code is nevertheless wrong and that statement on top of this comment chain has to be removed and tests updated to add new diagnostic.

Comment (li3zhen1) [reply lib/Sema/CSDiagnostics.cpp]: Updated. Sorry I misunderstood that

File: lib/Sema/CSDiagnostics.cpp [hunk 11]
```diff
@@ -8199,6 +8199,44 @@ bool UnableToInferClosureReturnType::diagnoseAsError() {
   return true;
 }
 
+bool UnableToInferGenericPackElementType::diagnoseAsError() {
+  auto *locator = getLocator();
+  auto path = locator->getPath();
+
+  auto packElementElt = (path.end() - 1)->getAs<LocatorPathElt::PackElement>();
```
Comment (xedin) [inline lib/Sema/CSDiagnostics.cpp:8206]: Nit: We don't actually need to do this arithmetic - use `locator->getLastElementAs<LocatorPathElt::PackElement>()` instead.

File: test/Constraints/variadic_generic_functions.swift [hunk 12]
```diff
@@ -1,4 +1,4 @@
-// RUN: %target-typecheck-verify-swift
+// RUN: %target-typecheck-verify-swift -disable-availability-checking
```
Comment (xedin) [inline test/Constraints/variadic_generic_functions.swift:1]: Why is `-disable-availability-checking` necessary now?

Comment (li3zhen1) [reply test/Constraints/variadic_generic_functions.swift:1]: The struct case emit the following error on my end:
```
/Users/lizhen/Projects/swift-projects/swift/test/Constraints/variadic_generic_functions.swift:107:10: error: unexpected note produced: add @available attribute to enclosing generic struct
  struct Foo<each T> {
         ^
/Users/lizhen/Projects/swift-projects/swift/test/Constraints/variadic_generic_functions.swift:107:14: error: unexpected error produced: parameter packs in generic types are only available in macOS 14.0.0 or newer
  struct Foo<each T> {
             ^
```

Comment (li3zhen1) [reply test/Constraints/variadic_generic_functions.swift]: I removed that flag and placed `struct Foo<each T>` in `test/Constraint/variadic_generic_types.swift` now.

File: lib/Sema/CSDiagnostics.cpp [hunk 13]
```diff
@@ -8199,6 +8199,44 @@ bool UnableToInferClosureReturnType::diagnoseAsError() {
...
+                   packElementElt->getIndex());
+  }
+
+  if (isExpr<ApplyExpr>(locator->getAnchor())) {
+    // emit callee side diagnostics
+    if (auto *calleeLocator = getSolution().getCalleeLocator(locator)) {
+      if (const auto choice = getOverloadChoiceIfAvailable(calleeLocator)) {
+        if (auto *decl = choice->choice.getDeclOrNull()) {
+          const auto applyArgToParamElt =
+              (path.end() - 2)->getAs<LocatorPathElt::ApplyArgToParam>();
```
Comment (xedin) [inline lib/Sema/CSDiagnostics.cpp:8225]: Nit: I think the last thing here - let's use `findFirst<LocatorPathElt::ApplyArgToParam>()` and check that for presence.

Comment (li3zhen1) [reply lib/Sema/CSDiagnostics.cpp]: Updated. Thank you!

**Review by xedin — APPROVED** [review]
Great work, thank you very much!

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Comment by AnthonyLatsis** [comment]
@li3zhen1 Thank you for seeing this through. The next time you wish to take an issue with relatively recent prior activity, please ask the previous volunteers if they are still working on it and mind you taking it. We don’t want good first issues to be a competitive game.

**Comment by li3zhen1** [comment]
> @li3zhen1 Thank you for seeing this through. The next time you wish to take an issue with relatively recent prior activity, please ask the previous volunteers if they are still working on it and mind you taking it. We don’t want good first issues to be a competitive game.

Sorry. I’ll keep this in mind.

**Comment by li3zhen1** [comment]
> The failure to convert `Array` to `Set` here is "fixed" via IgnoreContextualType fix - `(attempting fix [fix: ignore specified contextual type] @ locator@0x14b13f320 [Call@<stdin>:5:19 → contextual type])`
> 
> This block of code is `repairFailures` that deals with `ContextualType` locator could detect that both types are `BoundGenericType`s with the same number of arguments and use `matchTypes` (like we do in other places there) to match them, that would mean that `Int` from `Set` is propagated to type variable that opens `T` of `Array` and would avoid `generic parameter 'T' could not be inferred` failure.

@xedin Did you mean that for this case there should be no **`generic parameter 'T' could not be inferred`**? I tried swift 5.9 and the main branch and they are all emitting two errors including this. Is this a desired behavior? If so, I feel like it's reasonable to emit 2 errors in the generic pack element case as well.
