### PR TITLE
RequirementMachine: Leave behind conflicting requirements in the minimized signature

### LINKED ISSUE #61031: Compiler crash when using same-type constraint on invalid unparameterized generic type
**Describe the bug**

Consider

```swift
public struct Wrapped<Values>: Sequence where Values: Sequence {
    public var values: Values

    public func makeIterator() -> Values.Iterator {
        values.makeIterator()
    }
}

extension Wrapped where Values == Array {
    public init(repeating value: Element, count: Int) {
        values = Array(repeating: value, count: count)
    }
}
```

This (invalid) program, while emitting an error, will crash the compiler:

```
error: compile command failed due to signal 6 (use -v to see invocation)
crash.swift:9:35: error: reference to generic type 'Array' requires arguments in <...>
extension Wrapped where Values == Array {
                                  ^
                                       <Any>
Swift.Array:1:23: note: generic type 'Array' declared here
@frozen public struct Array<Element> : _DestructorSafeContainer {
                      ^
Invalid type parameter in getReducedType()
Original type: (τ_0_0.Element, Int) -> Wrapped<τ_0_0>
Simplified term: τ_0_0.[Sequence:Element]
Longest valid prefix: τ_0_0
Prefix type: τ_0_0

Requirement machine for <τ_0_0>
Rewrite system: {
}
}
Property map: {
}
Conformance paths: {
}
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
Stack dump:
0.	Program arguments: /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2022-08-29-a.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file property-wrapper-crash.swift -target arm64-apple-macosx12.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -new-driver-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2022-08-29-a.xctoolchain/usr/bin/swift-driver -empty-abi-descriptor -resource-dir /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2022-08-29-a.xctoolchain/usr/lib/swift -module-name main -o /var/folders/k2/hxsy4q4x32x_m8_3qj04sdv80000gn/T/TemporaryDirectory.8aFhqN/property-wrapper-crash-1.o
1.	Apple Swift version 5.8-dev (LLVM 03bd949eeee4761, Swift 2c40a850df6f409)
2.	Compiling with the current language version
3.	While evaluating request TypeCheckSourceFileRequest(source_file "property-wrapper-crash.swift")
4.	While type-checking extension of Wrapped (at property-wrapper-crash.swift:9:1)
5.	While type-checking 'init(repeating:count:)' (at property-wrapper-crash.swift:10:12)
6.	While evaluating request CheckRedeclarationRequest(main.(file).Wrapped extension.init(repeating:count:)@property-wrapper-crash.swift:10:12)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000108ed378c llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x0000000108ed2a10 llvm::sys::RunSignalHandlers() + 128
2  swift-frontend           0x0000000108ed3dcc SignalHandler(int) + 304
3  libsystem_platform.dylib 0x000000018d1c34a4 _sigtramp + 56
4  libsystem_pthread.dylib  0x000000018d1abee0 pthread_kill + 288
5  libsystem_c.dylib        0x000000018d0e6340 abort + 168
6  swift-frontend           0x0000000105982b3c substPrefixType(swift::Type, unsigned int, swift::Type, swift::GenericSignature) + 0
7  swift-frontend           0x00000001059e34d8 swift::Type::transformWithPosition(swift::TypePosition, llvm::function_ref<llvm::Optional<swift::Type> (swift::TypeBase*, swift::TypePosition)>) const + 112
8  swift-frontend           0x00000001059e4604 swift::Type::transformWithPosition(swift::TypePosition, llvm::function_ref<llvm::Optional<swift::Type> (swift::TypeBase*, swift::TypePosition)>) const + 4508
9  swift-frontend           0x00000001059e5cd4 swift::Type::transformRec(llvm::function_ref<llvm::Optional<swift::Type> (swift::TypeBase*)>) const + 36
10 swift-frontend           0x0000000105980b38 swift::rewriting::RequirementMachine::getReducedType(swift::Type, swift::ArrayRefView<swift::Type, swift::GenericTypeParamType*, swift::GenericTypeParamType* swift::staticCastHelper<swift::GenericTypeParamType>(swift::Type const&), true>) const + 56
11 swift-frontend           0x00000001058d9204 swift::GenericSignatureImpl::getReducedType(swift::Type) const + 188
12 swift-frontend           0x00000001059d86ac swift::TypeBase::computeCanonicalType() + 2236
13 swift-frontend           0x00000001059d8eac swift::TypeBase::getMinimalCanonicalType(swift::DeclContext const*) const + 40
14 swift-frontend           0x00000001057a9d38 swift::ValueDecl::getOverloadSignatureType() const + 900
15 swift-frontend           0x0000000105370650 swift::CheckRedeclarationRequest::evaluate(swift::Evaluator&, swift::ValueDecl*) const + 672
16 swift-frontend           0x000000010538420c llvm::Expected<swift::CheckRedeclarationRequest::OutputType> swift::Evaluator::getResultUncached<swift::CheckRedeclarationRequest>(swift::CheckRedeclarationRequest const&) + 400
17 swift-frontend           0x0000000105383fac llvm::Expected<swift::CheckRedeclarationRequest::OutputType> swift::Evaluator::getResultCached<swift::CheckRedeclarationRequest, (void*)0>(swift::CheckRedeclarationRequest const&) + 160
18 swift-frontend           0x00000001053794b4 swift::CheckRedeclarationRequest::OutputType swift::evaluateOrDefault<swift::CheckRedeclarationRequest>(swift::Evaluator&, swift::CheckRedeclarationRequest, swift::CheckRedeclarationRequest::OutputType) + 44
19 swift-frontend           0x0000000105373580 (anonymous namespace)::DeclChecker::visit(swift::Decl*) + 296
20 swift-frontend           0x00000001053785ac swift::ASTVisitor<(anonymous namespace)::DeclChecker, void, void, void, void, void, void>::visit(swift::Decl*) + 7044
21 swift-frontend           0x0000000105373538 (anonymous namespace)::DeclChecker::visit(swift::Decl*) + 224
22 swift-frontend           0x0000000105373444 swift::TypeChecker::typeCheckDecl(swift::Decl*, bool) + 116
23 swift-frontend           0x0000000105424268 swift::TypeCheckSourceFileRequest::evaluate(swift::Evaluator&, swift::SourceFile*) const + 176
24 swift-frontend           0x00000001054263d0 llvm::Expected<swift::TypeCheckSourceFileRequest::OutputType> swift::Evaluator::getResultUncached<swift::TypeCheckSourceFileRequest>(swift::TypeCheckSourceFileRequest const&) + 400
25 swift-frontend           0x0000000105426170 llvm::Expected<swift::TypeCheckSourceFileRequest::OutputType> swift::Evaluator::getResultCached<swift::TypeCheckSourceFileRequest, (void*)0>(swift::TypeCheckSourceFileRequest const&) + 124
26 swift-frontend           0x00000001054240ac swift::TypeCheckSourceFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckSourceFileRequest>(swift::Evaluator&, swift::TypeCheckSourceFileRequest, swift::TypeCheckSourceFileRequest::OutputType) + 44
27 swift-frontend           0x000000010471044c bool llvm::function_ref<bool (swift::SourceFile&)>::callback_fn<swift::CompilerInstance::performSema()::$_7>(long, swift::SourceFile&) + 16
28 swift-frontend           0x000000010470c940 swift::CompilerInstance::forEachFileToTypeCheck(llvm::function_ref<bool (swift::SourceFile&)>) + 76
29 swift-frontend           0x000000010470c8d4 swift::CompilerInstance::performSema() + 76
30 swift-frontend           0x00000001046bdc90 withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 60
31 swift-frontend           0x00000001046b0e2c swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 3256
32 swift-frontend           0x000000010451f9f0 swift::mainEntry(int, char const**) + 3136
33 dyld                     0x0000000111b7d08c start + 520
```

Changing `... == Array` to  `... == [Element]` will still crash Swift 5.6.1, but successfully errors on the latest trunk toolchain:

```
crash.swift:9:19: error: same-type constraint 'Values' == 'Array<Values.Element>' is recursive
extension Wrapped where Values == [Element] {
                  ^
```

**Steps To Reproduce**

1. Use the `Swift Development Snapshot 2022-08-29` (`Apple Swift version 5.8-dev (LLVM 03bd949eeee4761, Swift 2c40a850df6f409`)
2. Compile the program

**Expected behavior**

The compiler should only emit an error message, not crash.

**Environment (please fill out the following information)**
 - OS: `macOS 12.5.1 arm64`
 - Xcode Version/Tag/Branch: `13.4.1` with `Swift Development Snapshot 2022-08-29`

### LINKED ISSUE #63997: swiftc crash: constrain protocol extension P where Self == J<A>
Environment:
- `swift-DEVELOPMENT-SNAPSHOT-2023-02-28-a.xctoolchain`
- macOS 13.2.1 (22D68)

Source code:

```swift
protocol P {
    associatedtype A
}

struct J<A> { }

extension P where Self == J<A> {
    static func just(_: A) { }
}
```

Compiler invocation:

```
/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2023-02-28-a.xctoolchain/usr/bin/swiftc -c t.swift
```

Crash report:

```
t.swift:7:13: error: no type for 'Self' can satisfy both 'Self == J<Self.A>' and 'Self : P'
extension P where Self == J<A> {
            ^
t.swift:7:13: error: same-type constraint 'Self' == 'J<Self.A>' is recursive
extension P where Self == J<A> {
            ^
Invalid type parameter in getReducedType()
Original type: (τ_0_0.A) -> ()
Simplified term: τ_0_0.[P:A]
Longest valid prefix: τ_0_0
Prefix type: τ_0_0

Requirement machine for <τ_0_0>
Rewrite system: {
}
}
Property map: {
}
Conformance paths: {
}
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2023-02-28-a.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file t.swift -target arm64-apple-macosx13.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -color-diagnostics -new-driver-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2023-02-28-a.xctoolchain/usr/bin/swift-driver -empty-abi-descriptor -plugin-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2023-02-28-a.xctoolchain/usr/lib/swift/host/plugins -resource-dir /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2023-02-28-a.xctoolchain/usr/lib/swift -module-name t -o t.o
1.	Apple Swift version 5.9-dev (LLVM 84aca0981812b32, Swift 8a930ca7c7f84d3)
2.	Compiling with the current language version
3.	While evaluating request TypeCheckSourceFileRequest(source_file "t.swift")
4.	While type-checking extension of P (at t.swift:7:1)
5.	While type-checking 'just(_:)' (at t.swift:8:5)
6.	While evaluating request CheckRedeclarationRequest(t.(file).P extension.just@t.swift:8:17, t.(file).P@t.swift:1:10)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000104c9d51c llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x0000000104c9c7a0 llvm::sys::RunSignalHandlers() + 128
2  swift-frontend           0x0000000104c9db5c SignalHandler(int) + 304
3  libsystem_platform.dylib 0x0000000192af82a4 _sigtramp + 56
4  libsystem_pthread.dylib  0x0000000192ac9cec pthread_kill + 288
5  libsystem_c.dylib        0x0000000192a022c8 abort + 180
6  swift-frontend           0x000000010180a460 substPrefixType(swift::Type, unsigned int, swift::Type, swift::GenericSignature) + 0
7  swift-frontend           0x0000000101875188 swift::Type::transformWithPosition(swift::TypePosition, llvm::function_ref<llvm::Optional<swift::Type> (swift::TypeBase*, swift::TypePosition)>) const + 112
8  swift-frontend           0x0000000101876258 swift::Type::transformWithPosition(swift::TypePosition, llvm::function_ref<llvm::Optional<swift::Type> (swift::TypeBase*, swift::TypePosition)>) const + 4416
9  swift-frontend           0x000000010187788c swift::Type::transformRec(llvm::function_ref<llvm::Optional<swift::Type> (swift::TypeBase*)>) const + 36
10 swift-frontend           0x00000001018081d0 swift::rewriting::RequirementMachine::getReducedType(swift::Type, swift::ArrayRefView<swift::Type, swift::GenericTypeParamType*, swift::GenericTypeParamType* swift::staticCastHelper<swift::GenericTypeParamType>(swift::Type const&), true>) const + 56
11 swift-frontend           0x000000010175396c swift::GenericSignatureImpl::getReducedType(swift::Type) const + 188
12 swift-frontend           0x0000000101869eac swift::TypeBase::computeCanonicalType() + 2228
13 swift-frontend           0x000000010186a6b0 swift::TypeBase::getMinimalCanonicalType(swift::DeclContext const*) const + 40
14 swift-frontend           0x0000000101601e30 swift::ValueDecl::getOverloadSignatureType() const + 408
15 swift-frontend           0x00000001012e6144 swift::CheckRedeclarationRequest::evaluate(swift::Evaluator&, swift::ValueDecl*, swift::NominalTypeDecl*) const + 672
16 swift-frontend           0x00000001012fb334 llvm::Expected<swift::CheckRedeclarationRequest::OutputType> swift::Evaluator::getResultUncached<swift::CheckRedeclarationRequest>(swift::CheckRedeclarationRequest const&) + 400
17 swift-frontend           0x00000001012fb0d4 llvm::Expected<swift::CheckRedeclarationRequest::OutputType> swift::Evaluator::getResultCached<swift::CheckRedeclarationRequest, (void*)0>(swift::CheckRedeclarationRequest const&) + 160
18 swift-frontend           0x00000001012f0268 swift::CheckRedeclarationRequest::OutputType swift::evaluateOrDefault<swift::CheckRedeclarationRequest>(swift::Evaluator&, swift::CheckRedeclarationRequest, swift::CheckRedeclarationRequest::OutputType) + 44
19 swift-frontend           0x00000001012e92e8 (anonymous namespace)::DeclChecker::visit(swift::Decl*) + 376
20 swift-frontend           0x00000001012ef154 swift::ASTVisitor<(anonymous namespace)::DeclChecker, void, void, void, void, void, void>::visit(swift::Decl*) + 8164
21 swift-frontend           0x00000001012e9278 (anonymous namespace)::DeclChecker::visit(swift::Decl*) + 264
22 swift-frontend           0x00000001012e915c swift::TypeChecker::typeCheckDecl(swift::Decl*, bool) + 116
23 swift-frontend           0x00000001013b30f0 swift::TypeCheckSourceFileRequest::evaluate(swift::Evaluator&, swift::SourceFile*) const + 164
24 swift-frontend           0x00000001013b53fc llvm::Expected<swift::TypeCheckSourceFileRequest::OutputType> swift::Evaluator::getResultUncached<swift::TypeCheckSourceFileRequest>(swift::TypeCheckSourceFileRequest const&) + 400
25 swift-frontend           0x00000001013b519c llvm::Expected<swift::TypeCheckSourceFileRequest::OutputType> swift::Evaluator::getResultCached<swift::TypeCheckSourceFileRequest, (void*)0>(swift::TypeCheckSourceFileRequest const&) + 124
26 swift-frontend           0x00000001013b2f40 swift::TypeCheckSourceFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckSourceFileRequest>(swift::Evaluator&, swift::TypeCheckSourceFileRequest, swift::TypeCheckSourceFileRequest::OutputType) + 44
27 swift-frontend           0x00000001004a0410 bool llvm::function_ref<bool (swift::SourceFile&)>::callback_fn<swift::CompilerInstance::performSema()::$_7>(long, swift::SourceFile&) + 16
28 swift-frontend           0x000000010049bc1c swift::CompilerInstance::forEachFileToTypeCheck(llvm::function_ref<bool (swift::SourceFile&)>) + 76
29 swift-frontend           0x000000010049bbb0 swift::CompilerInstance::performSema() + 76
30 swift-frontend           0x000000010033a4c4 withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 60
31 swift-frontend           0x000000010032d1f8 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 3240
32 swift-frontend           0x000000010018527c swift::mainEntry(int, char const**) + 3304
33 dyld                     0x000000019279fe50 start + 2544
zsh: abort       -c t.swift
```

### PR DESCRIPTION
**Pull request by slavapestov**
Requirement lowering only expects that it won't see two requirements
of the same kind (except for conformance requirements). So only mark
those as conflicting.

This addresses a crash-on-invalid and improves diagnostics for
move-only generics, because a conflict won't drop the copyability
of a generic parameter and expose a move-only-naive user to
confusing error messages.

Fixes https://github.com/apple/swift/issues/61031.
Fixes https://github.com/apple/swift/issues/63997.
Fixes rdar://problem/111991454.

### CODE REVIEW

File: validation-test/compiler_crashers_2_fixed/issue61031.swift [hunk 1]
```diff
@@ -0,0 +1,16 @@
+// RUN: %target-typecheck-verify-swift
```
Comment (AnthonyLatsis) [inline validation-test/compiler_crashers_2_fixed/issue61031.swift:1]: Do you mind sticking to the `issue-*` format for file names? This is the one I'm planning to use once I start renaming all the `sr*` files.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

File: test/IDE/complete_where_clause.swift [hunk 2]
```diff
@@ -234,8 +234,11 @@ extension WithAssoc where T.#^EXT_ASSOC_MEMBER_1^#
 // EXT_ASSOC_MEMBER-DAG: Decl[AssociatedType]/CurrNominal:   Q;
 // EXT_ASSOC_MEMBER-DAG: Keyword/None:                       Type[#Self.T.Type#];
 
+// This is kind of funny because we parse it as 'Int == T', so completing 'T'
+// shows members of 'Int'.
 extension WithAssoc where Int == T.#^EXT_ASSOC_MEMBER_2^# 
-// Same as EXT_ASSOC_MEMBER
+// EXT_ASSOC_MEMBER_2: Begin completions, {{.*}} items
+// EXT_ASSOC_MEMBER_2: Keyword/None:                           Type[#Int.Type#];
```
Comment (ahoppen) [inline test/IDE/complete_where_clause.swift:241]: This is a regression. Do you know how it used to get parsed or why the behavior might have changed?
