### PR TITLE
[AST/SIL] Expand SIL function type isolation to include `nonisolated(nonsending)`

### LINKED ISSUE #86083: [concurrency]: nonisolated(nonsending) can unexpectedly lose actor isolation
### Description

in the following example, for some reason the isolation assertions fail at runtime when it does not seem like they should.

### Reproduction

```swift
actor MyActor {
    func test(_ closure: nonisolated(nonsending) () async -> Void) async {
        // uncommenting this somehow fixes the assertion failure
        // self.assertIsolated()
        await closure()
    }
}

nonisolated func test() async {
    let a = MyActor()

    await a.test {
        let iso = #isolation
        print(iso as Any)       // Optional(output.MyActor)
        assert(iso === a)       // ✅
        iso!.assertIsolated()   // 💥
        a.assertIsolated()      // 💥
    }
}

await test()
```

### Expected behavior

the isolation assertions should pass

### Environment

Swift version 6.3-dev (LLVM cff341857efbfc7, Swift 956dc0c1a258891)
Target: x86_64-unknown-linux-gnu

### Additional information

godbolt: https://swift.godbolt.org/z/qPE9dxMq9
similar issue discussed here: https://github.com/swiftlang/swift/pull/84206

### PR DESCRIPTION
**Pull request by xedin**
- Explanation:

  The primary driver for this change is the `OptimizeHopToExecutor` pass because it has to check whether a call is a suspension point or not and the most convenient way to rule out `nonisolated(nonsending)` would be to check a callee but since the `nonisolated(nonsending)` isolation wasn't represented before it had to go through actor isolation which is not always easier to figure out from SIL. This means that some hops were optimized away even though they shouldn't have been.

  The change includes the following:

   - Adding `nonisolated(nonsending)` to SILFunctionType;
   - Expanding mangling to support that (uses `N` to represent the new isolation);
   - Serialization of SILFunctionTypeLayout records has been expanded to store "isolation" instead of just "erased" bit;
   - `getSILFunctionType` is updated to start producing lowering with `nonisolated(nonsending)` isolation;
   - `FullyApplySite::isCallerIsolationInheriting` is updated to check callee instead of reaching of the isolation;

- Resolves: https://github.com/swiftlang/swift/issues/86083, rdar://169998321

- Risk: Low to Medium. This is a representation change so it carries some risk of interactions with optimizations beyond specialization.

- Testing: Added new test-cases to the suite, updated existing tests.

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test

File: lib/AST/ASTContext.cpp [hunk 1]
```diff
@@ -5627,6 +5627,16 @@ CanSILFunctionType SILFunctionType::get(
   assert(!ext.isPseudogeneric() || genericSig ||
          coroutineKind != SILCoroutineKind::None);
 
+  // Make sure that the invariant that `nonisolated(nonsending)` function
+  // always has an implicit leading parameter is maintained.
```
Comment (jamieQ) [inline lib/AST/ASTContext.cpp:5631]: Not sure if it should be done in this PR, but do you think the verifier should enforce that the actor isolation and implicit leading parameters correspond in the expected way? Something like `<is_nonisolated_nonsending_isolation>` <-> `<has_implicit_leading_isolated_param>`? Or are there expected cases in which that does not hold?

File: lib/Demangling/Remangler.cpp [hunk 2]
```diff
@@ -2135,6 +2142,9 @@ ManglingError Remangler::mangleImplFunctionType(Node *node, unsigned depth) {
       case Node::Kind::ImplErasedIsolation:
         Buffer << 'A';
         break;
+      case Node::Kind::ImplNonisolatedNonsendingIsolation:
+        Buffer << 'N';
```
Comment (jamieQ) [inline lib/Demangling/Remangler.cpp:2146]: Just out of curiosity, how are the letters for this encoding chosen?

**Review by jamieQ — COMMENTED** [review]
A couple general interest questions for you if you have a moment @xedin:

1. Why is this approach preferable over a narrower fix to just address the issue in the executor hop optimization pass?
2. I assume the answer is "no", but is this expected to resolve the other apparent issue with that pass described in https://github.com/swiftlang/swift/issues/88259?

File: lib/AST/ASTContext.cpp (hunk 1 above)
Comment (xedin) [reply lib/AST/ASTContext.cpp:5631]: Yeah, I need to think about that some more that’s why I put an assert here for now.

File: lib/Demangling/Remangler.cpp (hunk 2 above)
Comment (xedin) [reply lib/Demangling/Remangler.cpp:2146]: To minimize possibility of clashes but really arbitrarily, I used the first letter of the attribute and checked where else we use it.

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Comment by xedin** [comment]
@jamieQ the reason why I did it this way is because there is no reliable way to make it narrow, we should track the isolation.

File: include/swift/AST/ASTMangler.h [hunk 3]
```diff
@@ -84,6 +84,14 @@ class ASTMangler : public Mangler {
   /// If enabled, inverses will not be mangled into generic signatures.
   bool AllowInverses = true;
 
+  /// If enabled, nonisolated(nonsending) can be encoded in the mangled name.
+  /// Suppressing type attributes this way is generally questionable ---
+  /// for example, it does not interact properly with substitutions ---
+  /// and should only be done in situations where it is just going to be
+  /// interpreted as a type and the exact string value does not play
+  /// a critical role.
+  bool AllowNonisolatedNonsending = true;
```
Comment (rjmccall) [inline include/swift/AST/ASTMangler.h]: Is this necessary? I don't think the mangling of impl-function-type is supposed to show up in the "real" ABI — we only have this mangling in order to distinguish internal details like reabstraction thunks from each other, and they shouldn't ever be demangled by the runtime. We do always want to make sure that reabstraction thunks are distinguished by this isolation because it's an important ABI difference (although the implicit parameter will already accomplish that to a degree). And I wouldn't want someone to see this flag and think that it controls the mangling of *normal* function types — and of course we absolutely need to always mangle this isolation into normal function types because of its major impact on the ABI.

**Review by rjmccall — CHANGES_REQUESTED** [review]
Generally looks good, except I don't think we want the mangling suppression flag.

File: include/swift/AST/ASTMangler.h (hunk 3 above)
Comment (xedin) [reply include/swift/AST/ASTMangler.h]: I see, I modeled this on `@isolated(any)` but I understand your point and will remove it.

Comment (xedin) [reply include/swift/AST/ASTMangler.h]: ✅

**Comment by xedin** [comment]
@swift-ci please test

File: lib/Demangling/NodePrinter.cpp [hunk 4]
```diff
@@ -2892,6 +2893,9 @@ NodePointer NodePrinter::print(NodePointer Node, unsigned depth,
   case Node::Kind::ImplEscaping:
     Printer << "@escaping";
     return nullptr;
+  case Node::Kind::ImplNonisolatedNonsendingIsolation:
+    Printer << "nonisolated(nonsending)";
```
Comment (rjmccall) [inline lib/Demangling/NodePrinter.cpp]: This is not how it's actually spelled in SIL, right?

Comment (xedin) [reply lib/Demangling/NodePrinter.cpp]: Oh, good catch! I forgot to update it for `@caller_isolated`.

**Review by rjmccall — APPROVED** [review]
Approving because the patch seems overall fine, but I think we probably want to fix the printer.

File: lib/Demangling/NodePrinter.cpp (hunk 4 above)
Comment (xedin) [reply lib/Demangling/NodePrinter.cpp]: ✅

**Comment by xedin** [comment]
@swift-ci please test

**Review by hborla — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform
