### PR TITLE
[Parse] Handle underscored integer in #sourceLocation line directive

### LINKED ISSUE #55049: [SR-12605] #sourceLocation doesn't allow underscores in line numbers
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12605      |
   |Radar             | rdar://problem/62202395         |
   |Original Reporter | @beccadax      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Near-master, 15 April 2019

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Parser, StarterBug        |
   |Assignee          | matthewspear (JIRA)      |
   |Priority          | Medium      |

   

   md5: 41076a6957823a7ff8a7fce6be55225d

  </details>

**Issue Description:**

``` none
  1> #sourceLocation(file: "a.swift", line: 1_000)
error: /var/folders/mw/1rhv6fn96gb8swwkt8zycwph0000gn/T/repl1-101710..swift:2:40: error: expected starting line number for #sourceLocation directive
#sourceLocation(file: "a.swift", line: 1_000)
                                       ^
  1> #sourceLocation(file: "a.swift", line: 1000)
  2> 1_000
$R0: Int = 1000
  3>  
```

Underscore separators in `#sourceLocation` directives probably ought to be supported.

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Strip underscores when parsing line directive integers.

Resolves https://github.com/apple/swift/issues/55049.

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

File: lib/Parse/ParseDecl.cpp [hunk 1]
```diff
@@ -5778,7 +5778,8 @@ ParserStatus Parser::parseLineDirective(bool isLine) {
         diagnose(Tok, diag::expected_line_directive_number);
         return makeParserError();
       }
-      if (Tok.getText().getAsInteger(0, StartLine)) {
+      auto text = copyAndStripUnderscores(Tok.getText());
```
Comment (rintaro) [inline lib/Parse/ParseDecl.cpp:5781]: Could you limit this to only strings containing `_`?
```suggestion
      auto text = Tok.getText();
      if (text.contains('_'))
        text = copyAndStripUnderscores(text);
```
Because `copyAndStripUnderscores` unconditionally copies the string to `ASTContext`, which is unnecessary for this case.

Comment (LucianoPAlmeida) [reply lib/Parse/ParseDecl.cpp]: Makes sense, just fixed

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please test

File: lib/Parse/ParseExpr.cpp [hunk 2]
```diff
@@ -1009,6 +1009,10 @@ StringRef Parser::copyAndStripUnderscores(StringRef orig) {
   return StringRef(start, p - start);
 }
 
+StringRef Parser::copyAndStripUnderscoresIfNeeded(StringRef text) {
+  return text.contains('_') ? copyAndStripUnderscores(text) : text;
+}
```
Comment (rintaro) [inline lib/Parse/ParseExpr.cpp:1014]: Sorry, this is confusing. The main purpose of `copyAndStripUnderscores()` is copying the literal string to `ASTContext` for later stages getting the literal value from it. Stripping underscores is a secondary "while you are here" thing.

However this new function is all about stripping underscores. We don't want to copy it to `ASTContext` if possible, and the copied string just "leaks." So I don't think we should use similar name for this.

If you want to factor out it to a function, could you do like:
```cpp
StringRef stripUnderscoresIfNeeded(StringRef str, SmallVectorImpl<char> &buf) {
  if (!str.contains('_')) return str;
  buf.clear();
  llvm::copy_if(str, std::back_inserter(buf), [](char c){ return c != '_'; });
  return StringRef(buffer.data(), buffer.size());
}
```
And use a temporary buffer like
```cpp
SmallString<16> scratch;
auto text = stripUnderscoresIfNeeded(Tok.getText(), scratch);
```
Otherwise, I don't think it's worth to make a function for this.

**Comment by rintaro** [comment]
@swift-ci Please test

**Review by rintaro — APPROVED** [review]
Thank you!
