### PR TITLE
[Sema] Track implicit tuple expr use for closure empty return to improve diagnostic location

### LINKED ISSUE #59716: Swift 5.7 compiler error lacks file name or line number when block doesn't have the right return type
**Describe the bug**

The following code should (and does) fail to compile, but the error message is a lot less helpful under swift 5.7

```
["foo"].map { s in
    if s == "1" { return }
    return s.isEmpty
}.filter { $0 }
```

**To Reproduce**

Compiled with swift5.7, the error message doesn't list a file name or line number, so it's almost impossible to find the bug.

```
$ swift ~/Desktop/error.swift 
<unknown>:0: error: cannot convert return expression of type '()' to return type 'Bool'
```

**Expected behavior**

Compiled with swift5.6, the error message is much more useful.

```
$ swift5.6 ~/Desktop/error.swift 
/Users/tominsam/Desktop/error.swift:2:19: error: non-void function should return a value
    if s == "1" { return }
                  ^
```

**Environment (please complete the following information):**
 - OS: macOS 12.4 (M1)
 - swift 5.7 from xcode 14b2 (14A5229c)
 - swift 5.6 from xcode 13.4 (13F17a)

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
The problem here is the anchor expr in which the fix is recorded is an implicit  empty tuple expression which means no valid source location.

This PR track the return statement associated with an implicit tuple expression used to type check empty return as `Void` in closure to be able to produce diagnostics with better source location. Couldn't think in another approach for this, the information is somewhat tracked in `solutionApplicationTargets` but not really accessible and it didn't felt correct to rely on it for this in specific, so this seemed like a simpler way to improve this.  

Fixes #59716

### CODE REVIEW

**Review by xedin — CHANGES_REQUESTED** [review]
Here is a simpler alternative - add a `SourceLoc` parameter to `getVoidExpr` and use location of `ReturnStmt` there, that way even though `()` is implicit it would still have a valid source range so the diagnostic would be in the right place.

**Comment by LucianoPAlmeida** [comment]
> Here is a simpler alternative - add a `SourceLoc` parameter to `getVoidExpr` and use location of `ReturnStmt` there, that way even though `()` is implicit it would still have a valid source range so the diagnostic would be in the right place.

Thanks @xedin!
Just adjusted :)

**Review by xedin — APPROVED** [review]
Great, thank you!

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test

File: lib/Sema/CSClosure.cpp [hunk 1]
```diff
@@ -885,11 +885,13 @@ class SyntacticElementConstraintGenerator
...
       // which is also useful if contextual turns out to be e.g. `Void?`.
-      resultExpr = getVoidExpr(cs.getASTContext());
+      // Also, attach return stmt source location so if there is a contextual
+      // mismatch we can produce a diagnostic in a valid source location.
+      resultExpr = getVoidExpr(cs.getASTContext(), returnStmt->getEndLoc());
     }
 
     SolutionApplicationTarget target(resultExpr, context.getAsDeclContext(),
-                                     CTP_ReturnStmt, resultType,
+                                     CTP_ClosureResult, resultType,
```
Comment (xedin) [inline lib/Sema/CSClosure.cpp:894]: @LucianoPAlmeida I have been testing my AST transform for result builders and apparently this change actually breaks opaque result type opening - ConstraintSystem::openOpaqueType only accepts `CTP_ReturnStmt` for opening. I think we should change locators back and modify diagnostics instead to detect that CTP_ReturnStmt comes from the closure body. Would you like to work on that or should I?

Comment (LucianoPAlmeida) [reply lib/Sema/CSClosure.cpp:894]: Ah sorry for that. I thought CPT use was most for diagnostics, I can work on it. First I'll revert this just to umbrela things and try to adjust that separately :)

Comment (LucianoPAlmeida) [reply lib/Sema/CSClosure.cpp:894]: Do you have a repro? I thought it would be something like this:
```swift
func f() -> some BinaryInteger {
  return ["foo"].map { s in
       if s == "1" { return } // expected-error{{cannot convert value of type '()' to closure result type 'Bool'}}
       return s.count
  }
}
```
Just want to add a regression test

Comment (xedin) [reply lib/Sema/CSClosure.cpp:894]: So I tried to work it out and unfortunately it doesn't seem possible without my changes because `SyntacticElementConstraintGenerator` only handles closures at the moment but with my changes it would be able to handle accessors (mutate their bodies to apply result builder and what's where that issue happens). Note: it's okay to use `CTP_ClosureResult` if "context" is a closure but `CTP_ReturnStmt` should be used in all other cases.

You can build https://github.com/apple/swift/pull/60065 locally and test the following snippet with the feature enabled (`-enable-experimental-feature ResultBuilderASTTransform`) to reproduce:

```
import SwiftUI

struct EqualWitdthHStack : Layout {
  func sizeThatFits(proposal: ProposedViewSize, subviews: Self.Subviews, cache: inout Self.Cache) -> CGSize { fatalError() }
  func placeSubviews(in bounds: CGRect, proposal: ProposedViewSize, subviews: Self.Subviews, cache: inout ()) {}
}

struct MyView : View {
  var body : some View {
    EqualWitdthHStack {
      EmptyView()
    }
  }
}
```

Type-checking of that with `ReturnStmt` target set to use `CTP_ClosureResult` would result in `error: cannot convert value of type 'some View' (result of 'Self.callAsFunction') to closure result type 'some View' (type of 'MyView.body')`

Comment (LucianoPAlmeida) [reply lib/Sema/CSClosure.cpp:894]: @xedin Quick question about the approach you mentioned here

>  I think we should change locators back and modify diagnostics instead to detect that CTP_ReturnStmt comes from the closure body

What do you mean by changing locators back? Track this information via locator?

Comment (LucianoPAlmeida) [reply lib/Sema/CSClosure.cpp:894]: Oh I forgot about this one, this week has been busy. But I'll probably wait for that PR to land before work on this

Comment (LucianoPAlmeida) [reply lib/Sema/CSClosure.cpp:894]: Hey @xedin, trying to introduce this test snippet but it looks like failing with `cannot find type 'Layout' in scope`. I don't know much about SwiftUI so is that a type a `SwiftUI` type added in a specific version? Do I have to have a specific version of OS with that type to run that locally? 
Just not sure about what am I missing 😅

Comment (LucianoPAlmeida) [reply lib/Sema/CSClosure.cpp:894]: Ah actually never mind, I just found that some of the types in the snippet are really `macOS 13.0+` so now everything makes sense again =]
Do you have a repro snippet that doesn't need those?
