### PR TITLE
[Concurrency] Avoid inserting handler record in already cancelled task.

### LINKED ISSUE #80161: onCancel callback of the withTaskCancellationHandler() is called more than once.
### Description

The documentation doesn't clearly state that the `onCancel` can be called more than once.
We observed sometimes it happens and not clear is it bug or not.
Minimized reproducing test is available on [github](https://github.com/ordo-one/external-reproducers/tree/main/swift/task-cancellation)

### Reproduction

```
git clone https://github.com/ordo-one/external-reproducers
cd external-reproducers/swift/task-cancellation
swift Sources/Main.swift 
```

Sometimes test fails:
```
task-cancellation % swift Sources/Main.swift 
Main/Main.swift:39: Precondition failed: cancelled more than once, iteration: 234607
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend             0x000000010a1c6a9c llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend             0x000000010a1c4cf0 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend             0x000000010a1c7068 SignalHandler(int) + 292
3  libsystem_platform.dylib   0x000000018b436de4 _sigtramp + 56
4  libswiftCore.dylib         0x000000019c1d90a4 $ss17_assertionFailure__4file4line5flagss5NeverOs12StaticStringV_SSAHSus6UInt32VtF + 268
5  libswiftCore.dylib         0x00000001108709ac $ss17_assertionFailure__4file4line5flagss5NeverOs12StaticStringV_SSAHSus6UInt32VtF + 18446744071367653908
6  libswift_Concurrency.dylib 0x000000026bcd427c swift::runJobInEstablishedExecutorContext(swift::Job*) + 252
7  libswift_Concurrency.dylib 0x000000026bcd57a4 swift_job_runImpl(swift::Job*, swift::SerialExecutorRef) + 144
8  libdispatch.dylib          0x000000018b25f4cc _dispatch_root_queue_drain + 392
9  libdispatch.dylib          0x000000018b25fcd8 _dispatch_worker_thread2 + 156
10 libsystem_pthread.dylib    0x000000018b3fc39c _pthread_wqthread + 228
11 libsystem_pthread.dylib    0x000000018b3fb0f0 start_wqthread + 8
zsh: trace trap  swift Sources/Main.swift
```

### Expected behavior

`precondition` check at line [39](https://github.com/ordo-one/external-reproducers/blob/main/swift/task-cancellation/Sources/Main.swift#L39) always success

### Environment

```
task-cancellation % swiftc -version 
swift-driver version: 1.115.1 Apple Swift version 6.0.3 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
Target: arm64-apple-macosx15.0
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ktoso**
This avoids the potential to race with the triggering coming from task_cancel, because we first set the cancelled flag, and only THEN take the lock and iterate over the inserted records. Because of this we could: T1 flip the cancelled bit; T2 observes that, and triggers "immediately" during installing the handler record. T1 then proceeds to lock records and trigger it again, causing a double trigger of the cancellation handler.

resolves https://github.com/swiftlang/swift/issues/80161 
resolves rdar://147493150

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
@swift-ci please smoke test

File: stdlib/public/Concurrency/Task.cpp [hunk 1]
```diff
@@ -1758,27 +1758,45 @@ swift_task_addCancellationHandlerImpl(
...
     CancellationNotificationStatusRecord *record) {
-  removeStatusRecordFromSelf(record);
-  swift_task_dealloc(record);
+  if (!record) {
+    // seems we never added the record but have run it immediately,
+    // so we make no attempts to remove it.
+    return;
+  }
+
+  if (auto poppedRecord =
```
Comment (ktoso) [inline stdlib/public/Concurrency/Task.cpp:1795]: The way the remove and add are paired is such that the record should always be at the top here, so this removal should be exactly that record on the top.

**Comment by ktoso** [comment]
Failure was TestSwiftActorUnprioritisedJobs.py which seems to be flaky, see also https://github.com/swiftlang/llvm-project/pull/10404 trying to fix it

**Comment by ktoso** [comment]
@swift-ci please smoke test macOS

File: stdlib/public/Concurrency/TaskPrivate.h [hunk 2]
```diff
@@ -244,6 +244,16 @@ void removeStatusRecordWhere(
...
 
+/// Remove and return a status record of the given type. This function removes a
+/// singlw record, and leaves subsequent records as-is if there are any.
+/// Returns `nullptr` if there are no matching records.
+///
+/// NOTE: When using this function with new record types, make sure to provide
+/// an explicit instantiation in TaskStatus.cpp.
+template <typename TaskStatusRecordT>
+SWIFT_CC(swift)
+TaskStatusRecordT* popStatusRecordOfType(AsyncTask *task);
```
Comment (mikeash) [inline stdlib/public/Concurrency/TaskPrivate.h:255]: We may want to move the templated parts of the implementation into the header to avoid annoying link issues.

File: stdlib/public/Concurrency/Task.cpp (hunk 1 above)
Comment (ktoso) [reply stdlib/public/Concurrency/Task.cpp:1795]: I’ll add that

File: stdlib/public/Concurrency/TaskPrivate.h (hunk 2 above)
Comment (ktoso) [reply stdlib/public/Concurrency/TaskPrivate.h:255]: I did try that but we don’t have the types fully declared there hmmm, I can try again. I’ll share the error

Comment (mikeash) [reply stdlib/public/Concurrency/TaskPrivate.h:255]: It's fine to leave it if C++ objects too strenuously to my idea.

Comment (ktoso) [reply stdlib/public/Concurrency/TaskPrivate.h:255]: Yeah it's a bit painful, we'd need complete type declarations for a bunch of stuff:

```
/Users/ktoso/code/swift-project/swift/stdlib/public/Concurrency/TaskPrivate.h:255:27: warning: extra qualification on member 'popStatusRecordOfType' [-Wextra-qualification]
  255 | TaskStatusRecordT* swift::popStatusRecordOfType(AsyncTask *task) {
      |                           ^
/Users/ktoso/code/swift-project/swift/stdlib/public/Concurrency/TaskPrivate.h:255:27: error: out-of-line definition of 'popStatusRecordOfType' does not match any declaration in namespace 'swift'
  255 | TaskStatusRecordT* swift::popStatusRecordOfType(AsyncTask *task) {
      |                           ^~~~~~~~~~~~~~~~~~~~~
/Users/ktoso/code/swift-project/swift/stdlib/public/Concurrency/TaskPrivate.h:258:54: error: variable has incomplete type 'ActiveTaskStatus'
  258 |   removeStatusRecordWhere(task, [&](ActiveTaskStatus s, TaskStatusRecord *r) {
      |                                                      ^
/Users/ktoso/code/swift-project/swift/stdlib/public/Concurrency/TaskPrivate.h:58:7: note: forward declaration of 'swift::ActiveTaskStatus'
   58 | class ActiveTaskStatus;
      |       ^
```

File: stdlib/public/Concurrency/Task.cpp (hunk 1 above)
Comment (ktoso) [reply stdlib/public/Concurrency/Task.cpp:1795]: Adding here https://github.com/swiftlang/swift/pull/80522

File: stdlib/public/Concurrency/TaskPrivate.h (hunk 2 above)
Comment (mikeash) [reply stdlib/public/Concurrency/TaskPrivate.h:255]: We could have a small templatized implementation in the header that just retrieves the kind of the type being requested, then calls into a real non-templatized implementation which looks for that kind. But we can save that for when we actually need it.

File: test/Concurrency/Runtime/cancellation_handler_only_once.swift [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+        $0.cancelled += 1
+        return $0.continuation.take()
+      }
+      continuation?.resume()
+    }
+  }
+
+  // This task cancel is racing with installing the cancellation handler,
+  // and we may either hit the cancellation handler:
+  // - after this cancel was issued, and therefore the handler runs immediately
```
Comment (macguru) [inline test/Concurrency/Runtime/cancellation_handler_only_once.swift:46]: I just accidentally dropped by here and noticed that the comment seems clipped and is missing the second case. Probably not worth bothering, but wanted to bring it up.
