### PR TITLE
[Concurrency] allow isolated on dynamic self types

### LINKED ISSUE #70924: `Self` shorthand does not work with `isolated` parameters
### Description

using the `Self` shorthand with an `isolated` parameter results in `error: 'isolated' parameter has non-actor type 'Self'`. 

### Reproduction

```diff
actor A 
{
    init() {}
}
extension A 
{
    nonisolated
    func f() async
    {
-       await { (self:isolated A) in } (self)
+       await { (self:isolated Self) in } (self)
    }
}
```

### Expected behavior

as actors do not allow inheritance, `Self` should be equivalent to spelling out the full type name

### Environment

```
$ swiftc --version
Swift version 5.9.2 (swift-5.9.2-RELEASE)
Target: x86_64-unknown-linux-gnu
```

### Additional information

forum thread: https://forums.swift.org/t/isolated-parameter-has-non-actor-type-self/69440/2

### PR DESCRIPTION
**Pull request by ktoso**
`isolated` typechecking missed the handling of `DynamicSelfType` and wrongly prevented using `Self` with `isolated`.

This patch fixes the behavior and adds tests for the specific case.

Resolves #70924
Resolves rdar://121022467

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please smoke test

File: test/Concurrency/isolated_parameters.swift [hunk 1]
```diff
@@ -395,3 +395,18 @@ nonisolated func callFromNonisolated(ns: NotSendable) async {
...
+actor A2 {
+}
+extension A2 {
+  nonisolated func f() async {
+    await { (self: isolated Self) in }(self)
+  }
+}
+
+@MainActor class MA2 {}
+extension MA2 {
```
Comment (ktoso) [inline test/Concurrency/isolated_parameters.swift:408]: missed handling this case

Comment (ktoso) [reply test/Concurrency/isolated_parameters.swift]: Seems this would not work even with a concrete MA, so skipping from this patch

**Comment by ktoso** [comment]
@swift-ci please smoke test
