### PR TITLE
[Backtracing][Linux] Replace regex with ProcMapsScanner.

### LINKED ISSUE #66457: Building `stdlib/public/Backtracing/Backtrace.swift` fails
**Description**

Command:
```
utils/build-script --skip-build-benchmarks --skip-ios --skip-watchos --skip-tvos --swift-darwin-supported-archs="$(uname -m)" --release-debuginfo --sccache --swift-disable-dead-stripping --skip-early-swift-driver --bootstrapping=off
```

Error:
```
/Users/mac/Desktop/swift-project/swift/stdlib/public/Backtracing/Backtrace.swift:479:21: error: expected a macro identifier for a pound literal expression
    let mapRegex = #/
                    ^
/Users/mac/Desktop/swift-project/swift/stdlib/public/Backtracing/Backtrace.swift:479:21: error: consecutive statements on a line must be separated by ';'
    let mapRegex = #/
                    ^
                    ;
/Users/mac/Desktop/swift-project/swift/stdlib/public/Backtracing/Backtrace.swift:479:21: error: operator with postfix spacing cannot start a subexpression
    let mapRegex = #/
                    ^
/Users/mac/Desktop/swift-project/swift/stdlib/public/Backtracing/Backtrace.swift:480:49: error: consecutive statements on a line must be separated by ';'
    ^(?<start>[A-Fa-f0-9]+)-(?<end>[A-Fa-f0-9]+)\s+
                                                ^
                                                ;
/Users/mac/Desktop/swift-project/swift/stdlib/public/Backtracing/Backtrace.swift:481:22: error: expected ',' separator
    (?<perms>[-rwxsp]{4})\s+
                     ^
                     ,
/Users/mac/Desktop/swift-project/swift/stdlib/public/Backtracing/Backtrace.swift:481:26: error: consecutive statements on a line must be separated by ';'
    (?<perms>[-rwxsp]{4})\s+
                         ^
                         ;
/Users/mac/Desktop/swift-project/swift/stdlib/public/Backtracing/Backtrace.swift:482:28: error: consecutive statements on a line must be separated by ';'
    (?<offset>[A-Fa-f0-9]+)\s+
                           ^
                           ;
/Users/mac/Desktop/swift-project/swift/stdlib/public/Backtracing/Backtrace.swift:483:27: error: consecutive statements on a line must be separated by ';'
    (?<major>[A-Fa-f0-9]+):(?<minor>[A-Fa-f0-9]+)\s+
                          ^
                          ;
/Users/mac/Desktop/swift-project/swift/stdlib/public/Backtracing/Backtrace.swift:483:27: error: expected expression
    (?<major>[A-Fa-f0-9]+):(?<minor>[A-Fa-f0-9]+)\s+
                          ^

```

**Environment**
- Swift version 5.9-dev (LLVM d638e0929fa87b0, Swift 23e2f345b51ca0c)

### PR DESCRIPTION
**Pull request by al45tair**
We were using a regular expression to scan `/proc/<pid>/maps`, but we shouldn't really do that because it breaks non-bootstrapped builds.

rdar://110452324
Resolves #66457

### CODE REVIEW

**Comment by al45tair** [comment]
@swift-ci Please smoke test

File: stdlib/public/Backtracing/ProcMapsScanner.swift [hunk 1]
```diff
@@ -0,0 +1,256 @@
...
+    }
+
+    func isHex(_ ch: UInt8) -> Bool {
+      return ch >= UInt8(ascii: "A") && ch <= UInt8(ascii: "F")
+        || ch >= UInt8(ascii: "a") && ch <= UInt8(ascii: "f")
+        || ch >= UInt8(ascii: "0") && ch <= UInt8(ascii: "9")
+    }
+
+    func isWhitespace(_ ch: UInt8) -> Bool {
+      return ch == 32 || ch == 9
```
Comment (mikeash) [inline stdlib/public/Backtracing/ProcMapsScanner.swift:102]: Using `UInt8(ascii:)` here would save people from looking up what ASCII 9 is, and be more consistent with the rest.

**Review by mikeash — APPROVED** [review]
This is an excellent example of the power of regex.

File: stdlib/public/Backtracing/ProcMapsScanner.swift (hunk 1 above)
Comment (al45tair) [reply stdlib/public/Backtracing/ProcMapsScanner.swift:102]: :-) I'm probably showing my age there; I'll change to using `UInt8(ascii:)` for all of them.

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Comment by al45tair** [comment]
> Using UInt8(ascii:) here would save people from looking up what ASCII 9 is

What? You mean someone _doesn't_ know what ASCII 9 is? :-D

I sometimes forget I grew up in a world of 8-bit micros and dot matrix printers, so ended up just knowing lots of ASCII control codes.

**Review by gottesmm — APPROVED** [review]

**Comment by al45tair** [comment]
This resolves #66457.
