### PR TITLE
Sema: Don't coerce subexpression of 'try' to rvalue

### LINKED ISSUE #85034: Compiler crash when writing "try" keyword before instance variable in closure
### Description

Xcode fails to compile with an error
```
Command SwiftCompile failed with a nonzero exit code
```
I assume this is a compiler crash; I'd appreciate if anyone can confirm this. In Console.app I have crash reports for both swift-frontend and SourceKitService: do any of them, or both, signal a compiler crash? The stack dump below is from the latest SourceKitService crash report.

### Reproduction

```swift
let asd = Asd()
let _ = Dictionary(uniqueKeysWithValues: [0].map({ ($0, try asd.asd )}))

class Asd {
    var asd = 0
}

```

### Stack dump

```text
0     sourcekitdInProc              	       0x11ae7127c swift::constraints::ConstraintSystem::coerceToRValue(swift::Expr*) + 4
1     sourcekitdInProc              	       0x11ae779c0 (anonymous namespace)::ExprRewriter::coerceToType(swift::Expr*, swift::Type, swift::constraints::ConstraintLocatorBuilder) + 6932
2     sourcekitdInProc              	       0x11ae768b8 (anonymous namespace)::ExprRewriter::coerceToType(swift::Expr*, swift::Type, swift::constraints::ConstraintLocatorBuilder) + 2572
-------- RECURSION LEVEL 12173
3     sourcekitdInProc              	       0x11ae768b8 (anonymous namespace)::ExprRewriter::coerceToType(swift::Expr*, swift::Type, swift::constraints::ConstraintLocatorBuilder) + 2572
-------- RECURSION LEVEL 12172
4     sourcekitdInProc              	       0x11ae768b8 (anonymous namespace)::ExprRewriter::coerceToType(swift::Expr*, swift::Type, swift::constraints::ConstraintLocatorBuilder) + 2572
-------- RECURSION LEVEL 12171
--------
-------- ELIDED 12167 LEVELS OF RECURSION THROUGH 0x11ae768b8 (anonymous namespace)::ExprRewriter::coerceToType(swift::Expr*, swift::Type, swift::constraints::ConstraintLocatorBuilder) + 2572
--------
12172 sourcekitdInProc              	       0x11ae768b8 (anonymous namespace)::ExprRewriter::coerceToType(swift::Expr*, swift::Type, swift::constraints::ConstraintLocatorBuilder) + 2572
-------- RECURSION LEVEL 3
12173 sourcekitdInProc              	       0x11ae768b8 (anonymous namespace)::ExprRewriter::coerceToType(swift::Expr*, swift::Type, swift::constraints::ConstraintLocatorBuilder) + 2572
-------- RECURSION LEVEL 2
12174 sourcekitdInProc              	       0x11ae768b8 (anonymous namespace)::ExprRewriter::coerceToType(swift::Expr*, swift::Type, swift::constraints::ConstraintLocatorBuilder) + 2572
-------- RECURSION LEVEL 1
12175 sourcekitdInProc              	       0x11ae74a3c (anonymous namespace)::ExprWalker::rewriteTarget(swift::constraints::SyntacticElementTarget) + 7400
12176 sourcekitdInProc              	       0x11aec6314 (anonymous namespace)::SyntacticElementSolutionApplication::visitReturnStmt(swift::ReturnStmt*) + 1108
12177 sourcekitdInProc              	       0x11aec5d04 swift::ASTVisitor<(anonymous namespace)::SyntacticElementSolutionApplication, void, swift::ASTNode, void, void, void, void>::visit(swift::Stmt*) + 5200
12178 sourcekitdInProc              	       0x11aec2bbc swift::constraints::ConstraintSystem::applySolution(swift::AnyFunctionRef, swift::constraints::SyntacticElementTargetRewriter&) + 2664
12179 sourcekitdInProc              	       0x11ae791e0 (anonymous namespace)::ExprWalker::walkToExprPre(swift::Expr*) + 80
12180 sourcekitdInProc              	       0x11b6de0d4 (anonymous namespace)::Traversal::visit(swift::ArgumentList*) + 220
12181 sourcekitdInProc              	       0x11b6daa80 (anonymous namespace)::Traversal::visitApplyExpr(swift::ApplyExpr*) + 196
12182 sourcekitdInProc              	       0x11b6d8060 (anonymous namespace)::Traversal::visit(swift::Expr*) + 84
12183 sourcekitdInProc              	       0x11b6de0fc (anonymous namespace)::Traversal::visit(swift::ArgumentList*) + 260
12184 sourcekitdInProc              	       0x11b6daa80 (anonymous namespace)::Traversal::visitApplyExpr(swift::ApplyExpr*) + 196
12185 sourcekitdInProc              	       0x11b6d8060 (anonymous namespace)::Traversal::visit(swift::Expr*) + 84
12186 sourcekitdInProc              	       0x11ae73378 (anonymous namespace)::ExprWalker::rewriteTarget(swift::constraints::SyntacticElementTarget) + 1572
12187 sourcekitdInProc              	       0x11ae72c58 swift::constraints::ConstraintSystem::applySolution(swift::constraints::Solution&, swift::constraints::SyntacticElementTarget) + 6560
12188 sourcekitdInProc              	       0x11b169244 swift::TypeChecker::typeCheckTarget(swift::constraints::SyntacticElementTarget&, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>, swift::DiagnosticTransaction*) + 792
12189 sourcekitdInProc              	       0x11b168e08 swift::TypeChecker::typeCheckExpression(swift::constraints::SyntacticElementTarget&, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>, swift::DiagnosticTransaction*) + 420
12190 sourcekitdInProc              	       0x11b16a660 swift::TypeChecker::typeCheckBinding(swift::Pattern*&, swift::Expr*&, swift::DeclContext*, swift::Type, swift::PatternBindingDecl*, unsigned int, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 200
12191 sourcekitdInProc              	       0x11b16a87c swift::TypeChecker::typeCheckPatternBinding(swift::PatternBindingDecl*, unsigned int, swift::Type, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 292
12192 sourcekitdInProc              	       0x11b2894b8 swift::PatternBindingEntryRequest::evaluate(swift::Evaluator&, swift::PatternBindingDecl*, unsigned int) const + 3760
12193 sourcekitdInProc              	       0x11b7b08c4 swift::PatternBindingEntryRequest::OutputType swift::Evaluator::getResultUncached<swift::PatternBindingEntryRequest, swift::PatternBindingEntryRequest::OutputType swift::evaluateOrDefault<swift::PatternBindingEntryRequest>(swift::Evaluator&, swift::PatternBindingEntryRequest, swift::PatternBindingEntryRequest::OutputType)::'lambda'()>(swift::PatternBindingEntryRequest const&, swift::PatternBindingEntryRequest::OutputType swift::evaluateOrDefault<swift::PatternBindingEntryRequest>(swift::Evaluator&, swift::PatternBindingEntryRequest, swift::PatternBindingEntryRequest::OutputType)::'lambda'()) + 676
12194 sourcekitdInProc              	       0x11b770a48 swift::PatternBindingDecl::getCheckedPatternBindingEntry(unsigned int) const + 140
12195 sourcekitdInProc              	       0x11b1c5e3c (anonymous namespace)::DeclChecker::visit(swift::Decl*) + 1656
12196 sourcekitdInProc              	       0x11b279508 (anonymous namespace)::StmtChecker::typeCheckASTNode(swift::ASTNode&) + 1024
12197 sourcekitdInProc              	       0x11b27f12c swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) + 288
12198 sourcekitdInProc              	       0x11b27c78c bool (anonymous namespace)::StmtChecker::typeCheckStmt<swift::BraceStmt>(swift::BraceStmt*&) + 312
12199 sourcekitdInProc              	       0x11b27c94c swift::TypeChecker::typeCheckTopLevelCodeDecl(swift::TopLevelCodeDecl*) + 120
12200 sourcekitdInProc              	       0x11b2cf660 swift::TypeCheckPrimaryFileRequest::evaluate(swift::Evaluator&, swift::SourceFile*) const + 696
12201 sourcekitdInProc              	       0x11b2d6640 swift::TypeCheckPrimaryFileRequest::OutputType swift::Evaluator::getResultUncached<swift::TypeCheckPrimaryFileRequest, swift::TypeCheckPrimaryFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckPrimaryFileRequest>(swift::Evaluator&, swift::TypeCheckPrimaryFileRequest, swift::TypeCheckPrimaryFileRequest::OutputType)::'lambda'()>(swift::TypeCheckPrimaryFileRequest const&, swift::TypeCheckPrimaryFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckPrimaryFileRequest>(swift::Evaluator&, swift::TypeCheckPrimaryFileRequest, swift::TypeCheckPrimaryFileRequest::OutputType)::'lambda'()) + 672
12202 sourcekitdInProc              	       0x119fca544 bool llvm::function_ref<bool (swift::SourceFile&)>::callback_fn<swift::CompilerInstance::performSema()::$_0>(long, swift::SourceFile&) + 156
12203 sourcekitdInProc              	       0x119fc4330 swift::CompilerInstance::forEachFileToTypeCheck(llvm::function_ref<bool (swift::SourceFile&)>) + 176
12204 sourcekitdInProc              	       0x119fc41c4 swift::CompilerInstance::performSema() + 120
12205 sourcekitdInProc              	       0x119cfb880 void SourceKit::WorkQueue::DispatchData::callAndDelete<(anonymous namespace)::ASTBuildOperation::schedule(SourceKit::WorkQueue)::$_0>(void*) + 3204
12206 libdispatch.dylib             	       0x190082ac4 _dispatch_client_callout + 16
12207 libdispatch.dylib             	       0x19006dc34 _dispatch_block_invoke_direct + 284
12208 sourcekitdInProc              	       0x11f143a6c executeBlock(void*) + 28
12209 sourcekitdInProc              	       0x11f143a9c void* llvm::thread::ThreadProxy<std::__1::tuple<void (*)(void*), void*>>(void*) + 24
12210 libsystem_pthread.dylib       	       0x190224c08 _pthread_start + 136
12211 libsystem_pthread.dylib       	       0x19021fba8 thread_start + 8
```

### Expected behavior

A meaningful error message.

### Environment

swift-driver version: 1.127.14.1 Apple Swift version 6.2 (swiftlang-6.2.0.19.9 clang-1700.3.19.1)
Target: arm64-apple-macosx26.0

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by slavapestov**
Undo the change in 8ab8b2e3e9107f32ea13efd38e270ff3b45d324a, which was an incorrect fix for some other bug which has since been fixed properly.

If this becomes an rvalue even though the type of the surrounding expression is an lvalue, we can end up with infinite recursion in coerceToType(), as demonstrated by the test case.

Fixes https://github.com/swiftlang/swift/issues/85034.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

File: lib/Sema/TypeCheckStmt.cpp [hunk 1]
```diff
@@ -1702,6 +1702,11 @@ class StmtChecker : public StmtVisitor<StmtChecker, Stmt*> {
     // Type-check the subject expression.
     Expr *subjectExpr = switchStmt->getSubjectExpr();
     auto resultTy = TypeChecker::typeCheckExpression(subjectExpr, DC);
+
+    // FIXME: What's happening here?
+    if (!resultTy)
```
Comment (slavapestov) [inline lib/Sema/TypeCheckStmt.cpp]: @hamishknight What does it mean when this is null? It's the only place that it happens. (And it's from a code completion test: `IDE/complete_stmt_controlling_expr.swift`)

Comment (hamishknight) [reply lib/Sema/TypeCheckStmt.cpp]: Null here means type-checking the subject expr failed (or we did a completion in it). I don't think we want to completely bail out here though, e.g we should still update the node on the SwitchStmt and continue to type-check the case bodies.

Comment (hamishknight) [reply lib/Sema/TypeCheckStmt.cpp]: I assume we're only hitting this for completion since when type-checking for completion we don't do CSApply so will leave the expression un-type-checked

File: lib/Sema/CSApply.cpp [hunk 2]
```diff
@@ -3753,21 +3753,7 @@ namespace {
...
-
-        if (!subExpr)
-          return nullptr;
-      }
-
-      cs.setType(expr, cs.getType(subExpr));
-      expr->setSubExpr(subExpr);
-
+      cs.setType(expr, cs.getType(expr->getSubExpr()));
       return expr;
```
Comment (hamishknight) [inline lib/Sema/CSApply.cpp]:
```suggestion
  return simplifyExprType(expr);
```

**Review by hamishknight — COMMENTED** [review]
I think this also needs CSGen changes to work correctly, e.g we don't want to produce an lvalue here:

```swift
var x = 0
(try! x) += 1
```

If we see that the sub-expression can bind to an lvalue I think we need to produce a fresh type variable that isn't `TVO_CanBindToLValue` and add an `Equal` constraint

**Comment by slavapestov** [comment]
@hamishknight Actually it looks like the `try!` part of the change was somewhat correct so I'm changing `visitAnyTryExpr()` to `visitForceTryExpr()`, and adding a `visitTryExpr()` that doesn't load the lvalue.

Indeed, the original test case only passed `-typecheck` so it wasn't even triggering the crash it was meant to fix, which only occurs in SILGen.

File: lib/Sema/TypeCheckStmt.cpp (hunk 1 above)
Comment (slavapestov) [reply lib/Sema/TypeCheckStmt.cpp]: Ah, got it.

**Comment by hamishknight** [comment]
@slavapestov I suspect the updated code will still crash for the newly added test case if you change `try` to `try!`, the issue here seems to fundamentally be the fact that we're mismatching the types produced by the solution and the types being assigned in CSApply. As such I suspect this will probably need fixing in CSGen

**Comment by slavapestov** [comment]
Indeed you're right, I'll see about fixing CSGen for `ForceTryExpr`. That should eliminate the need to load the rvalue here.

**Comment by slavapestov** [comment]
@hamishknight Thank you for the detailed review, that was really helpful!

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test source compatibility

**Comment by slavapestov** [comment]
@hamishknight It looks like for `try!` we still have to load the rvalue because the subexpression's type might be an lvalue. But now we get consistent types and it doesn't crash.

File: lib/Sema/CSGen.cpp [hunk 3]
```diff
@@ -2060,10 +2060,20 @@ namespace {
...
       return CS.getType(expr->getSubExpr());
     }
 
+    Type visitForceTryExpr(AnyTryExpr *expr) {
+      auto valueTy = CS.createTypeVariable(CS.getConstraintLocator(expr),
+                                           TVO_PrefersSubtypeBinding |
+                                               TVO_CanBindToNoEscape);
+      CS.addConstraint(ConstraintKind::Equal, valueTy,
+                       CS.getType(expr->getSubExpr()),
+                       CS.getConstraintLocator(expr));
```
Comment (xedin) [inline lib/Sema/CSGen.cpp:2073]: @hamishknight this makes me wonder - instead of trying to load a sub-expr of a try, maybe we should be instead make sure that each element of the tuple expression is r-value which would in turn make sure that `try` is loaded as well...

Comment (slavapestov) [reply lib/Sema/CSGen.cpp:2073]: we should probably disallow tuple types that contain lvalues, or at least a mix of rvalues and lvalues, but that's a bigger change...

Comment (slavapestov) [reply lib/Sema/CSGen.cpp:2073]: I see the following is rejected, so I'm wondering if its possible for lvalue to appear inside a tuple type in any case where the entire tuple isn't an lvalue:
```
func f() {
  var x = 0

  g(&(x, "hi").0)
}

func g(_: inout Int) {}
```

Comment (slavapestov) [reply lib/Sema/CSGen.cpp:2073]: Certainly `(x, y) = (y, x)` and so on is fine, but that can be modeled as `@lvalue (Int, Int)` instead of `(@lvalue Int, @lvalue Int)`.

Comment (xedin) [reply lib/Sema/CSGen.cpp:2073]: Yeah, if I try `(0, x.x)` I see that the member reference is loaded. I haven't actually tested, but based on the discussion, it sounds like the "type mismatch" in the example is related to the fact that the type of a tuple element is l-value but in tuple expression when the actual expression has been loaded already by the logic in `visitAnyTryExpr`, in this case I'd say that CSGen should make sure that the elements are r-values and that would allow us to remove some of the loading for CSApply that handles this kind of transform post-factum...

**Review by hamishknight — COMMENTED** [review]
Thanks! LGTM

File: lib/Sema/CSGen.cpp (hunk 3 above)
Comment (hamishknight) [reply lib/Sema/CSGen.cpp:2073]: > this makes me wonder - instead of trying to load a sub-expr of a try, maybe we should be instead make sure that each element of the tuple expression is r-value which would in turn make sure that try is loaded as well...

I don't think this is specific to tuples, I think you'd run into similar issues for things like `(try! x)`, if `x` is an lvalue and we don't enforce that the type of the `try!` is an rvalue in CSGen then the ParenExpr is going to have an lvalue type in the solution which CSApply will happily assign and we'll crash even if we have coerced `x` to an rvalue.

It agree it would be nice if we could stop modeling tuple elements as lvalues though, maybe at some point in the future we could even stop modeling lvalues at all in the constraint system :)

Comment (xedin) [reply lib/Sema/CSGen.cpp:2073]: > I don't think this is specific to tuples

@hamishknight Isn't the problem with infinite `coerceToType` is specific to tuple elements? I brought it up because I think we should be enforcing this higher up if the assessment in my previous comment is correct. It seems like the fundamental issue here is that we end up with a type that contains  l-value(s) i.e. `(Int, @lvalue Int)` coming out of CSGen but then later we coerce each element type to r-value (that's what I noticed with `(0, x.x)`) in CSApply somewhere, regardless of whether r-value is necessary for a `try!` or not this shouldn't have produced a solution in my opinion and we don't actually know in what other cases we might be in the same situation were we'd need to use a non-lvalue type variable for some other expression.
