### PR TITLE
Fixes throwing super.init() diagnostics

### LINKED ISSUE #56650: [SR-14291] Compiler doesn't tell where the error occurs.
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14291      |
   |Radar             | rdar://problem/74876041         |
   |Original Reporter | @YOCKOW      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)  
Target: x86_64-apple-darwin20.3.0

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI        |
   |Assignee          | None      |
   |Priority          | Medium      |

   md5: 9a5fd6b71ce55da5783b9975045cb234

  </details>

**Issue Description:**

Try to compile the following code:

``` swift
class C {
  init() throws {}
}

class D: C {
  let i: Int
  init(i: Int) {
    self.i = i
  }
}
```

The compiler views error like  
`<unknown>:0: error: call can throw, but it is not marked with 'try' and the error is not handled`.

`D` seems to call `super.init` implicitly, but the error message doesn't imply it.

### PR DESCRIPTION
**Pull request by Visckmart**
### Problem

If we have a class with a throwing initializer and a subclass that implements an initializer and doesn't call the `super.init` explicitly, like this:
```swift
class ThrowingInitClass {
    init() throws {}
}

class ExampleSubclass: ThrowingInitClass {
    let exampleVariable: Int
    
    init(exampleParameter: Int) {
        self.exampleVariable = exampleParameter
    }
}
```
The compiler doesn't behave appropriately, as can be seen here:
`<unknown>:0: error: call can throw, but it is not marked with 'try' and the error is not handled.`

Note: This is not a problem if the subclass's initializer is also a throwing initializer (like `init(exampleParameter: Int) throws`). It compiles without errors or warnings.

### Solution Context

If we were to replace the `throws` on the previous block of code with `async`, we would hit the situation described on this excerpt from [
The Swift Programming Language (5.9) > Initialization > Initializer Inheritance and Overriding](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/initialization/#Initializer-Inheritance-and-Overriding):
>If a subclass initializer performs no customization in phase 2 of the initialization process, and the superclass has a synchronous, zero-argument designated initializer, you can omit a call to super.init() after assigning values to all of the subclass’s stored properties. **If the superclass’s initializer is asynchronous, you need to write await super.init() explicitly**.

As the related diagnostic in that case is:
`missing call to superclass's initializer; 'super.init' is 'async' and requires an explicit call`

### Implemented Solution

The solution I implemented mirrors the `async` approach to improve the diagnostic for the throwing case:
`missing call to superclass's initializer; 'super.init' is a throwing initializer and requires an explicit call`

This error only shows when the `super.init` is throwing while the subclass's initializer is not. If both are throwing, the current behavior (synthesizing what is probably something like `try super.init()`) should still work.

### Improvements Considered

1. I considered ending the error message with `"[...] requires an explicit call or that this initializer becomes a throwing initializer"` but I think it would be too long.

2. I also considered adding a fix-it for writing `throws` on the initializer, which would enable the synthetization to work. But I think that doing this would imply that this is the ideal solution on most cases, and it's not clear to me that this is true.

3. I also considered adding a fix-it for writing the `try super.init()` statement explicitly, which would then result on the `Errors thrown from here are not handled` error. But although I think this could be useful, I'm not confident on how to thoroughly test an implementation like that, so I decided to not go that deep for now.

4. I think we should clarify this situation on the paragraph I cited from the documentation and I plan on exploring if there are ways to do that if this pull request is approved.

Fixes #56650.

### CODE REVIEW

File: lib/Sema/TypeCheckStmt.cpp [hunk 1]
```diff
@@ -2221,6 +2221,13 @@ static bool checkSuperInit(ConstructorDecl *fromCtor,
       fromCtor->diagnose(diag::availability_unavailable_implicit_init,
                          ctor, superclassDecl->getName());
     }
+    
+    // Not allowed to implicitly generate a super.init() call if it's
+    // a throwing initializer while the one being typechecked is not.
+    if ((fromCtor->hasThrows() == false) && ctor->hasThrows()) {
```
Comment (slavapestov) [inline lib/Sema/TypeCheckStmt.cpp:2227]: Stylistically we prefer `!x` over `x == false`

**Review by slavapestov — APPROVED** [review]
Nice fix!

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by AnthonyLatsis** [comment]
> 1. I considered ending the error message with `"[...] requires an explicit call or that this initializer becomes a throwing initializer"` but I think it would be too long.

I think this is reasonable despite the length, because the `async` case is different in that an explicit call is always necessary, even if the current initializer is also `async`. How about `missing call to superclass's initializer; 'super.init' is a throwing initializer and requires an explicit call because the subclass initializer is not throwing`?

**Review by AnthonyLatsis — COMMENTED** [review]
Can you add some tests? Probably makes the most sense to write these next to where the `async` case is tested, but not if the file is dedicated to `async` diagnostics only.

File: lib/Sema/TypeCheckStmt.cpp (hunk 1 above)
Comment (Visckmart) [reply lib/Sema/TypeCheckStmt.cpp]: Improved!

File: include/swift/AST/DiagnosticsSema.def [hunk 2]
```diff
@@ -4698,6 +4698,18 @@ ERROR(return_init_non_nil,none,
...
+
+ERROR(implicit_throws_super_init_rethrowing,none,
+      "missing call to superclass's initializer; "
+      "'super.init' requires an explicit call because it's a throwing initializer "
+      "while the subclass's initializer can only rethrow errors from its parameters",
+      ())
+
 ERROR(implicit_async_super_init,none,
       "missing call to superclass's initializer; "
       "'super.init' is 'async' and requires an explicit call",
```
Comment (AnthonyLatsis) [inline include/swift/AST/DiagnosticsSema.def:4715]: We want diagnostics that belong to the same family to be consistent and recognizable. In this case, we want the `throws` error to ring a bell with a programmer that once already encountered the `async` error, so I believe the wording in all three of these must be aligned. Should we agree on the new wording, I suggest basing the current changes on a commit that updates the `async` error.

File: lib/Sema/TypeCheckStmt.cpp [hunk 3]
```diff
@@ -2229,7 +2229,23 @@ static bool checkSuperInit(ConstructorDecl *fromCtor,
       fromCtor->diagnose(diag::availability_unavailable_implicit_init,
                          ctor, superclassDecl->getName());
     }
-
+    
+    // Only allowed to synthesize a throwing super.init() call if the init being
+    // checked is also throwing.
+    if (ctor->hasThrows()) {
+      // Diagnose on nonthrowing initializer
+      if (!fromCtor->hasThrows()) {
```
Comment (AnthonyLatsis) [inline lib/Sema/TypeCheckStmt.cpp:2237]: Ugh, the name of this method and associated doc comment is so misleading. We should really rename it to `hasThrowsOrRethrows` or `isThrowingOrRethrowing`.

File: include/swift/AST/DiagnosticsSema.def (hunk 2 above)
Comment (Visckmart) [reply include/swift/AST/DiagnosticsSema.def:4715]: I completely agree with your reasoning about keeping them consistent and recognizable. With that in mind I believe we should revert the words I had moved back to their original position and arrive even closer to your suggestion. Something I would consider, though, is replacing "subclass's initializer" with "this initializer". What do you think about doing this? To me, it makes it easier to understand what is being referred on the sentence. If we agree on that we will have:

**For reference, the `async` case**
`missing call to superclass's initializer; 'super.init' is 'async' and requires an explicit call`

**On the nonthrowing case**
`missing call to superclass's initializer; 'super.init' is a throwing initializer and requires an explicit call since this initializer is nonthrowing`

**On the `rethrows` case**
`missing call to superclass's initializer; 'super.init' is a throwing initializer and requires an explicit call since this initializer can only rethrow errors from its parameters`

Comment (AnthonyLatsis) [reply include/swift/AST/DiagnosticsSema.def:4715]: On `rethrows errors from its parameters`: Although I perfectly understand the point of this interpretation colloquially, I have doubts about whether it is technically accurate enough for a diagnostic, and und  to put it that way. I’m more inclined to describe rethrowing as either "can only rethrow errors thrown by a call t
* `'super.init' is a throwing initializer and requires either an explicit call or that this initializer be throwing too`

Comment (Visckmart) [reply include/swift/AST/DiagnosticsSema.def:4715]: Merging them can be good as it also forces us to write a more succinct message. To me, the ending could be a bit more formal, though. Like the following:
`'super.init' is a throwing initializer and requires either an explicit call or that this initializer is also marked as throwing`

Note that the terminology we're using now could be a bit confusing to beginners if they mark the initializer with `rethrows` because they might think "If it's marked as rethrowing, it's obviously marked as throwing too!". To try to mitigate this interpretation I used the word "also" on "[...] or that this initializer is **also** marked as throwing". Other than that I think this is something we might have to deal with, and the documentation should be there to clarify.

What do you think?

---

No worries! I didn't feel discouraged by your comment at all. And I'm still not completely against my original idea of moving the "requires an explicit call" earlier in the sentence. Your comment just made me wonder if I had a good enough reason to propose a change to the async diagnostic and to expand the scope of discussion of this PR. My conclusion was that I didn't, so I preferred making the new diagnostics conform to the writing of the existing one.

Comment (AnthonyLatsis) [reply include/swift/AST/DiagnosticsSema.def:4715]: > Other than that I think this is something we might have to deal with, and the documentation should be there to clarify.
>
> What do you think?

Agreed. The book defines a throwing function specifically as a function with the `throws` specifier, so I reckon a "go read the book" overtone is well grounded. We may as well go a step further and say `also marked as 'throws'`.

___
> No worries! I didn't feel discouraged by your comment at all. And I'm still not completely against my original idea of moving the "requires an explicit call" earlier in the sentence.

Good to know we’re on the same page. And you’re welcome to revisit this in a future PR!

File: test/Parse/super.swift [hunk 4]
```diff
@@ -98,3 +98,26 @@ class Closures : B {
     g()
   }
 }
+
+class ThrowingInitSuperclass {
+  init() throws { }
+}
```
Comment (AnthonyLatsis) [inline test/Parse/super.swift:104]: Since these are semantic analysis, not parsing, tests, let’s move them to the Sema folder. A new file is fine; no sign of an existing corner dedicated to this feature in Sema.

Comment (Visckmart) [reply test/Parse/super.swift]: Done! Would you mind reviewing carefully the file header and it's name? I tried my best, but I'm not sure the command on the first line is the ideal one.

File: include/swift/AST/DiagnosticsSema.def (hunk 2 above)
Comment (Visckmart) [reply include/swift/AST/DiagnosticsSema.def]: This was actually the version I almost suggested instead of my previous one! Hahah Done.

> And you’re welcome to revisit this in a future PR!
Awesome!

**Comment by AnthonyLatsis** [comment]
@slavapestov Do you mind giving this another round of review? We’ve updated the error message.

File: lib/Sema/TypeCheckStmt.cpp [hunk 5]
```diff
@@ -2245,7 +2245,17 @@ static bool checkSuperInit(ConstructorDecl *fromCtor,
       fromCtor->diagnose(diag::availability_unavailable_implicit_init,
                          ctor, superclassDecl->getName());
     }
-
+    
+    // Only allowed to synthesize a throwing super.init() call if the init being
+    // checked is also throwing.
+    if (ctor->hasThrows()) {
+      // Diagnose on nonthrowing or rethrowing initializer
```
[the remark this answers is not in the document]
Comment (Visckmart) [reply lib/Sema/TypeCheckStmt.cpp]: Done! Hahah

**Comment by Visckmart** [comment]
@slavapestov ping

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test Linux

File: include/swift/AST/DiagnosticsSema.def [hunk 6]
```diff
@@ -4807,6 +4807,12 @@ ERROR(return_init_non_nil,none,
       "'nil' is the only return value permitted in an initializer",
       ())
 
+ERROR(implicit_throws_super_init,none,
+      "missing call to superclass's initializer; "
```
Comment (AnthonyLatsis) [inline include/swift/AST/DiagnosticsSema.def:4811]: Hmm... I wonder if developers would find the second clause more coherent if the first one mentioned that the call cannot be synthesized. For example: 

`call to superclass's initializer is missing and cannot be synthesized; 'super.init' is a throwing initializer and requires either an explicit call or that this initializer is also marked as 'throws'`.

vs.

`missing call to superclass's initializer; 'super.init' is a throwing initializer and requires either an explicit call or that this initializer is also marked as 'throws'`

Longer, yes, but I’m not a fan of this "brevity beats clarity" policy we appear to be expected to follow for Swift diagnostics.

File: include/swift/AST/DiagnosticsSema.def [hunk 7]
```diff
@@ -4807,6 +4807,12 @@ ERROR(return_init_non_nil,none,
...
+      "'super.init' is a throwing initializer and requires either an explicit "
```
Comment (AnthonyLatsis) [inline include/swift/AST/DiagnosticsSema.def:4812]: Maybe worth clarifying that we are referring to `super.init()`, not just any `super.init`?

**Review by AnthonyLatsis — APPROVED** [review]
Comments are optional.

File: include/swift/AST/DiagnosticsSema.def (hunk 6 above)
Comment (AnthonyLatsis) [reply include/swift/AST/DiagnosticsSema.def:4811]: cc @hborla

Comment (Visckmart) [reply include/swift/AST/DiagnosticsSema.def:4811]: I agree the first one makes it clearer but will wait a bit to see if someone with more experience than me has something to say about the "brevity beats clarity" tradeoff.

File: include/swift/AST/DiagnosticsSema.def (hunk 7 above)
Comment (Visckmart) [reply include/swift/AST/DiagnosticsSema.def:4812]: Yeah, totally!

File: include/swift/AST/DiagnosticsSema.def (hunk 6 above)
Comment (AnthonyLatsis) [reply include/swift/AST/DiagnosticsSema.def:4811]: > I believe we would have to change this on the async version of them too.

Yeah, fair enough. Better save this for another PR.

**Comment by AnthonyLatsis** [comment]
@slavapestov @xedin @hborla Reminder 🙇🏼‍♂️. We settled on a slightly different error message after the initial approval.

File: test/Sema/throwing_super_init.swift [hunk 8]
```diff
@@ -0,0 +1,24 @@
...
+// initializer is not a throwing initializer.
+class NonThrowingInitClass: ThrowingInitSuperclass {
+  init(simpleArgument: Int) { } // expected-error {{missing call to superclass's initializer; 'super.init' is a throwing initializer and requires either an explicit call or that this initializer is also marked as 'throws'}}
+}
+
+// Implicitly calling the super.init IS NOT possible here because the
+// initializer is a rethrowing initializer, which means it can only
+// rethrow errors from its parameters.
+class RethrowingInitClass: ThrowingInitSuperclass {
+  init(throwingArgument: () throws -> Void) rethrows { } // expected-error {{missing call to superclass's initializer; 'super.init' is a throwing initializer and requires either an explicit call or that this initializer is also marked as 'throws'}}
```
Comment (xedin) [inline test/Sema/throwing_super_init.swift:23]: Can we actually suggest an explicit call in this case or only viable option is to change `rethrows` to `throws`?

Comment (xedin) [reply test/Sema/throwing_super_init.swift:23]: Is the only way to make it work in both cases:

```
do {
  try super.init()
} catch {
   fatalError(...)
}
```

Or something similar?

Comment (Visckmart) [reply test/Sema/throwing_super_init.swift:23]: > Can we actually suggest an explicit call in this case or only viable option is to change `rethrows` to `throws`?

By "suggest" do you mean adding a fixit? Because the diagnostic message already suggests an explicit call, or am I missing something?

> Is the only way to make it work in both cases:
> 
> ```
> do {
>   try super.init()
> } catch {
>    fatalError(...)
> }
> ```
> 
> Or something similar?

I believe this is a possible solution, yeah, but I can think of two alternatives: disabling the error propagation via `try!` and making use of a failable initializer, enabling a `return nil` on the catch block.

Comment (xedin) [reply test/Sema/throwing_super_init.swift:23]: I was asking whether saying that "explicit" call is viable here from the developer perspective, I guess with `try!` failable initializer and `do { } catch { ... }` there are options.

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
Thank you!

File: test/Sema/throwing_super_init.swift (hunk 8 above)
Comment (AnthonyLatsis) [reply test/Sema/throwing_super_init.swift:23]: > Can we actually suggest an explicit call in this case or only viable option is to change `rethrows` to `throws`?

The intended takeaway from this error message is that in order to proceed in the given direction you either have to rethink the `rethrows` or explicitly call `super.init()` *in a way the compiler would be happy about*.
