### PR TITLE
[Diagnostics] Increase impact for missed property diagnostic

### LINKED ISSUE #83885: Bad diagnostic for error inside closure
### Description

A compilation error inside a closure results in a misleading diagnostic.

### Reproduction

```swift
func example(ptr: UnsafeRawPointer) {
    let regions: [UnsafeRawBufferPointer] = []
    let matchingRegion = regions.first { region in
        let ptr = UInt(bitPattern: ptr)
        return ptr >= UInt(bitPattern: region.baseAddress!)
            && ptr < (UInt(bitPattern: region.baseAddress!) 
                      + UInt(region.bogusProperty))
    } // `bogusProperty` doesn't exist on UnsafeRawBufferPointer
}
```

See https://swift.godbolt.org/z/oTcq6McaE

The error message is:
```
<source>:3:34: error: cannot call value of non-function type 'UnsafeRawBufferPointer?'
 1 | func example(ptr: UnsafeRawPointer) {
 2 |     let regions: [UnsafeRawBufferPointer] = []
 3 |     let matchingRegion = regions.first { region in
   |                                  `- error: cannot call value of non-function type 'UnsafeRawBufferPointer?'
 4 |         let ptr = UInt(bitPattern: ptr)
 5 |         return ptr >= UInt(bitPattern: region.baseAddress!)
Compiler returned: 1
```

### Expected behavior

The error should be that `bogusProperty` isn't a known property of `UnsafeRawBufferPointer`.

### Environment

Swift version 6.2-dev (LLVM 29f45403943bdc7, Swift 299f17395c7cb19)
swift-DEVELOPMENT-SNAPSHOT-2025-08-18-a (actually 6.3-dev)

### Additional information

Note that using an inline closure rather than a trailing closure does not help.

same result:
```swift
func example(ptr: UnsafeRawPointer) {
    let regions: [UnsafeRawBufferPointer] = []
    let matchingRegion = regions.first(where: { region in
        let ptr = UInt(bitPattern: ptr)
        return ptr >= UInt(bitPattern: region.baseAddress!)
            && ptr < (UInt(bitPattern: region.baseAddress!) 
                      + UInt(region.bogusProperty))
      } // `bogusProperty` doesn't exist on UnsafeRawBufferPointer
    )
}
```

Credit to Noah Gregory https://swift-open-source.slack.com/archives/C04MRUD6VH8/p1755800748691209

### PR DESCRIPTION
**Pull request by kathygray-pl**
Impact for an unknown property access was frequently higher than other options on ambiguous selections, by 3 to 5 points, causing fix selections that were farther away and frequently noted to be in accurate. This commit lowers the impact to be in a similar range to other fixes and this causes property accesses to be selected more proprotionaly.

In the existing test suite, this changed the diagnostic only in the case of protocol composition, which was also discovered to be a flawed binding lookup.

Tests added for the property lookup, tests updated for protocol composition (Including correcting a likely error in a test specification)

Fixes: rdar://148350982
Fixes: https://github.com/swiftlang/swift/issues/83885

### CODE REVIEW

File: lib/Sema/CSRanking.cpp [hunk 1]
```diff
@@ -174,7 +174,8 @@ bool ConstraintSystem::worseThanBestSolution() const {
 
   if (isDebugMode()) {
     llvm::errs().indent(solverState->getCurrentIndent())
-        << "(solution is worse than the best solution)\n";
+        << "(solution " << CurrentScore << " is worse than the best solution "
+        << solverState->BestScore <<")\n";
```
Comment (hamishknight) [inline lib/Sema/CSRanking.cpp:178]: Thank you for adding this :)

File: test/Constraints/static_members_on_protocol_in_generic_context.swift [hunk 2]
```diff
@@ -175,14 +175,14 @@ test_combo(.genericFn(42)) // expected-error {{global function 'test_combo' requ
 
 /* Invalid result types */
 
-extension P { // expected-note 13 {{missing same-type requirement on 'Self'}} {{12-12= where Self == <#Type#>}}
+extension P { // expected-note 8 {{missing same-type requirement on 'Self'}} {{12-12= where Self == <#Type#>}}
   static func generic<T>(_: T) -> T { fatalError() }
-  static func genericWithReqs<T: Collection, Q>(_: T) -> Q where T.Element == Q { // expected-note 3 {{required by static method 'genericWithReqs' where 'T' = '()'}}
+  static func genericWithReqs<T: Collection & Q>(_: T) -> Q where T.Element == Q { // expected-note 4 {{required by static method 'genericWithReqs' where 'T' = '()'}} expected-note 5 {{where 'T' = '[any Q]'}}
```
Comment (hamishknight) [inline test/Constraints/static_members_on_protocol_in_generic_context.swift]: I definitely agree the previous definition didn't make much sense, though I'm not entirely convinced that this is what was intended either since the generic signature now cannot be satisfied at all since `[any Q]` does not conform to `Q`. I think it would probably make more sense to drop `Q` entirely and make this:

```swift
static func genericWithReqs<T: Collection>(_: T) -> T.Element
```

Maybe we could add a conformance requirement on `T.Element` if we still want the generic signature to have a requirement for the element. What do you think?

File: test/Constraints/static_members_on_protocol_in_generic_context.swift [hunk 3]
```diff
@@ -243,30 +249,47 @@ test(.generic(42).other)
...
-// expected-note@-2 {{only concrete types such as structs, enums and classes can conform to protocols}}
+// expected-error@-2 {{type '()' cannot conform to 'Q'}}
 // expected-error@-3 {{contextual member reference to static method 'genericWithReqs' requires 'Self' constraint in the protocol extension}}
+// expected-note@-4 2 {{only concrete types such as structs, enums and classes can conform to protocols}}
 
 test_combo(.doesntExist) // expected-error {{reference to member 'doesntExist' cannot be resolved without a contextual type}}
 test_combo(.doesnt.exist()) // expected-error {{reference to member 'doesnt' cannot be resolved without a contextual type}}
 test_combo(.invalidProp)
 // expected-error@-1 {{contextual member reference to static property 'invalidProp' requires 'Self' constraint in the protocol extension}}
+test_combo(.invalidProp.doesntExist) //FIXME Should be reporting that Int has no doesntExist if P&Q lookup fixed
```
Comment (hamishknight) [inline test/Constraints/static_members_on_protocol_in_generic_context.swift]: Minor nit, this allows it to be highlighted in Xcode:

```suggestion
test_combo(.invalidProp.doesntExist) // FIXME: Should be reporting that Int has no doesntExist if P&Q lookup fixed
```

Same goes for the others below

File: test/Constraints/static_members_on_protocol_in_generic_context.swift [hunk 4]
```diff
@@ -243,30 +249,47 @@ test(.generic(42).other)
...
+// expected-error@-1{{type 'Q' has no member 'invalidProp'}}
 test_combo(.invalidMethod())
-// expected-error@-1 {{contextual member reference to static method 'invalidMethod()' requires 'Self' constraint in the protocol extension}}
+// expected-error@-1 {{failed to produce diagnostic for expression}}
```
Comment (hamishknight) [inline test/Constraints/static_members_on_protocol_in_generic_context.swift]: Could you also add a FIXME for these "failed to produce diagnostic" cases?

Comment (hamishknight) [reply test/Constraints/static_members_on_protocol_in_generic_context.swift]: Actually I took a quick look at this and it seems like we're recording a duplicate `AllowInvalidStaticMemberRefOnProtocolMetatype` fix, once when looking up the member, and once when solving the conformance constraint for the base, I wonder if we could fix by doing:

```diff
--- a/lib/Sema/CSSimplify.cpp
+++ b/lib/Sema/CSSimplify.cpp
@@ -9247,6 +9247,8 @@
       if (isExpr<UnresolvedMemberExpr>(anchor) &&
           req->is<LocatorPathElt::TypeParameterRequirement>()) {
         auto *memberLoc = getConstraintLocator(anchor, path.front());
+        if (hasFixFor(memberLoc))
+          return SolutionKind::Solved;

         auto signature = path[path.size() - 2]
                              .castTo<LocatorPathElt::OpenedGeneric>()
```

In fact the logic following this new check seems like it might just be dead, we might be able to just remove it

File: lib/Sema/CSSimplify.cpp [hunk 5]
```diff
@@ -11646,9 +11645,9 @@ ConstraintSystem::SolutionKind ConstraintSystem::simplifyMemberConstraint(
         }
 
         // Increasing the impact for missing member in any argument position so
-        // it doesn't affect situations where there are another fixes involved.
+        // it doesn't significantly pull away from situations with options.
```
Comment (xedin) [inline lib/Sema/CSSimplify.cpp]: This is somewhat obscure, what are you trying to say here?

File: lib/Sema/CSSimplify.cpp [hunk 6]
```diff
@@ -15650,6 +15649,12 @@ bool ConstraintSystem::recordFix(ConstraintFix *fix, unsigned impact,
   if (auto impactScoreKind = fix->impact())
     increaseScore(*impactScoreKind, fix->getLocator(), impact);
 
+  if (isDebugMode()) {
+    auto &log = llvm::errs();
+    log.indent(solverState ? solverState->getCurrentIndent() : 0)
+      << "(fix has score " << impact << ")\n";
```
Comment (xedin) [inline lib/Sema/CSSimplify.cpp]: I think this is duplicate information because `increaseScore` already prints this with more information.

**Comment by xedin** [comment]
@kathygray-pl I believe this might also fix https://github.com/swiftlang/swift/issues/79474

**Comment by kathygray-pl** [comment]
@swift-ci please test

**Comment by kathygray-pl** [comment]
@swift-ci please test source compatibility

**Comment by kathygray-pl** [comment]
@swift-ci please test

**Comment by kathygray-pl** [comment]
@swift-ci please test

**Comment by kathygray-pl** [comment]
@swift-ci please test

File: validation-test/Sema/SwiftUI/rdar84580119.swift [hunk 7]
```diff
@@ -14,8 +14,9 @@ extension EnvironmentValues {
   var myHorizontalAlignment: AlignmentID? {
     get { fatalError() }
     set { self[\.MyHorizontalAlignmentEnvironmentKey.self] = newValue }
-    // expected-error@-1 {{subscript 'subscript(_:)' requires that 'any AlignmentID' be a class type}}
-    // expected-error@-2 {{cannot infer key path type from context; consider explicitly specifying a root type}}
+    // FIXME: error lost {{subscript 'subscript(_:)' requires that 'any AlignmentID' be a class type}}
```
Comment (hamishknight) [inline validation-test/Sema/SwiftUI/rdar84580119.swift]: I don't actually think we want that diagnostic anyway, it was because we picked a subscript overload that expected a metatype argument and was read-only, so it seems pretty unlikely that's what was expected here

File: validation-test/Sema/SwiftUI/too_complex_source_location.swift [hunk 8]
```diff
@@ -25,8 +25,9 @@ struct ContentView: View {
             VStack {
                 Picker(selection: $selection) {
                     ForEach(["a", "b", "c"], id: \.self) {
-                        Text($0)  // expected-error {{reasonable time}}
-                            .foregroundStyl(.red) // Typo is here
+                        Text($0)  // Formerly ran out of time
+                            .foregroundStyl(.red) // expected-error {{value of type 'Text' has no member 'foregroundStyl'; did you mean 'foregroundStyle'}}
```
Comment (hamishknight) [inline validation-test/Sema/SwiftUI/too_complex_source_location.swift]: Nice!

File: test/Constraints/static_members_on_protocol_in_generic_context.swift [hunk 9]
```diff
@@ -243,30 +247,38 @@ test(.generic(42).other)
...
-test_combo(.genericWithReqs([42]))
-// expected-error@-1 {{contextual member reference to static method 'genericWithReqs' requires 'Self' constraint in the protocol extension}}
+// expected-error@-1{{contextual member reference to static method 'generic' requires 'Self' constraint in the protocol extension}}
+test_combo(.generic(S()))
+// expected-error@-1{{contextual member reference to static method 'generic' requires 'Self' constraint in the protocol extension}}
+test_combo(.generic(G<Int>()))
+//expected-error@-1 {{contextual member reference to static method 'generic' requires 'Self' constraint in the protocol extension}}
+test_combo(.genericWithReqs([S()]))
+// expected-error@-1{{contextual member reference to static method 'genericWithReqs' requires 'Self' constraint in the protocol extension}}
+test_combo(.genericWithReqs([42])) //FIXME: Requires protocol conformance fix for expected two messages below
```
Comment (hamishknight) [inline test/Constraints/static_members_on_protocol_in_generic_context.swift:276]: Just to double check, by protocol conformance fix you mean #85951?

**Review by hamishknight — APPROVED** [review]
Thanks! LGTM

**Comment by hamishknight** [comment]
Could you also add a test case for #83885?

File: test/Constraints/static_members_on_protocol_in_generic_context.swift (hunk 9 above)
Comment (kathygray-pl) [reply test/Constraints/static_members_on_protocol_in_generic_context.swift:276]: Yes, I should add the PR number now that it exists

**Comment by kathygray-pl** [comment]
> @kathygray-pl I believe this might also fix #79474

I've checked and it sadly doesn't

**Comment by kathygray-pl** [comment]
@swift-ci please test

**Comment by kathygray-pl** [comment]
@swift-ci please test

**Comment by kathygray-pl** [comment]
@swift-ci please test
