### PR TITLE
[Sema]Skip Sendable conformance check when `sending` are added to parameters or return types of an actor-isolated function

### LINKED ISSUE #76710: Despite the sending return, I cannot satisfy protocol with a sending return
### Description

I thought for sure this was going to work, but somewhat similar to https://github.com/swiftlang/swift/issues/76677, it doesn't look like the `sending` is being taken into account here. The Sendability of the return type should not matter in this case, should it?

### Reproduction

```swift
final class DataModel {
	let name: String

	init(name: String) {
		self.name = name
	}
}

protocol DataStoring {
	func loadModel() async -> sending DataModel
}

@MainActor
final class DataStore: DataStoring {
	func loadModel() async -> sending DataModel {
	// error: non-sendable type 'DataModel' returned by main actor-isolated instance method 'loadModel()' satisfying protocol requirement cannot cross actor boundary
		DataModel(name: "foo")
	}
}
```

### Expected behavior

I'd expect this to compile without error.

### Environment

Apple Swift version 6.0.2-dev (LLVM 43d73cb0cc589f7, Swift aaa632cea622394)
Target: arm64-apple-macosx14.0

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by stzn**
Resolves #76710 

Previously, we encountered errors and notes when using a non-Sendable type with `sending` for parameters or return types of an actor-isolated function, as shown below:

```swift
class NonSendable { var value = 0 } // note: class 'NonSendable' does not conform to the 'Sendable' protocol

protocol P {
    func bar(a: sending NonSendable) async -> sending NonSendable
}

@MainActor
class PImpl: P {
    // error: non-sendable type 'NonSendable' cannot be returned from main actor-isolated implementation to caller of protocol requirement 'bar(a:)'
    // error: non-sendable parameter type 'NonSendable' cannot be sent from caller of protocol requirement 'bar(a:)' into main actor-isolated implementation
    func bar(a: sending NonSendable) async -> sending NonSendable { a }
}
```

Based on the issue described, this functionality should work without any errors. To resolve the issue, we need to bypass the Sendable conformance check for non-Sendable types when `sending` keywords is added to function's parameters or return types.

--

Even if the conformance check is skipped, invalid scenarios will still be validated at the SIL stage to ensure correctness.

For example:

When running `-emit-sil -swift-version 6`, a potential data race error is still detected.

```swift
func test() async {
    var nonSendable = NonSendable()
    let p = PImpl()

    // error: sending 'nonSendable' risks causing data races
    // note: 'nonSendable' used after being passed as a 'sending' parameter; Later uses could race 
    _ = await p.bar(a: nonSendable)

    // note: access can happen concurrently 
    nonSendable.value = 1 
}
```

### CODE REVIEW

File: test/Sema/issue-76710.swift [hunk 1]
```diff
@@ -0,0 +1,52 @@
+// RUN: %target-typecheck-verify-swift -swift-version 6
+
+// https://github.com/swiftlang/swift/issues/76710
+
+class NonSendableKlass1 {}
+
+protocol P1 {
+    func bar(_ a: sending NonSendableKlass1) async -> sending NonSendableKlass1
```
Comment (azarovalex) [inline test/Sema/issue-76710.swift:8]: nit
```suggestion
  func bar(_ a: sending NonSendableKlass1) async -> sending NonSendableKlass1
```

File: lib/Sema/TypeCheckConcurrency.cpp [hunk 2]
```diff
@@ -1166,6 +1166,9 @@ bool swift::diagnoseNonSendableTypesInReference(
     if (funcCheckOptions.contains(FunctionCheckKind::Params)) {
       // only check params if funcCheckKind specifies so
       for (auto param : *function->getParameters()) {
+        if (param->isSending())
+          return true;
```
Comment (azarovalex) [inline lib/Sema/TypeCheckConcurrency.cpp:1170]: Here you are skipping sendability validation on all other parameters if at least one of them is marked as `sending`, which seems incorrect, we should check sendability of all arguments.
Also this function is supposed to return `true` if there are any errors being produced, which is not what happens in our case.
It seems like instead of instead of bailing out early from this function we should keep checking other arguments but skip `diagnoseNonSendableTypes` check below if the argument is marked as `sending`.

Could you also consider adding a test for a case where first argument is marked with `sending` but a second argument isn't?

Comment (stzn) [reply lib/Sema/TypeCheckConcurrency.cpp:1170]: Thank you for the review.

> we should check sendability of all arguments.

I think that's right. Let me check it again.

Also, I might be misunderstanding this comment, but are you talking about `type->hasError()` in `diagnoseSingleNonSendableType`? If so, I think I overlooked it and we need to check `type->hasError()` and return `false` if there is any error.

```
static bool diagnoseSingleNonSendableType(
    Type type, SendableCheckContext fromContext,
    Type inDerivedConformance, SourceLoc loc,
    llvm::function_ref<bool(Type, DiagnosticBehavior)> diagnose) {
  if (type->hasError())
    return false;
```

Comment (stzn) [reply lib/Sema/TypeCheckConcurrency.cpp]: I fixed it in https://github.com/swiftlang/swift/pull/78601/commits/f63350561e7f04bfc9fdcd8497d8dae124749051. Please check it when you have time. Thank you!

**Comment by omochi** [comment]
@swift-ci please smoke test

File: lib/Sema/TypeCheckConcurrency.cpp [hunk 3]
```diff
@@ -1181,6 +1185,10 @@ bool swift::diagnoseNonSendableTypesInReference(
       if (funcCheckOptions.contains(FunctionCheckKind::Results)) {
         // only check results if funcCheckKind specifies so
         Type resultType = func->getResultInterfaceType().subst(subs);
+
+        if (func->hasSendingResult() && !resultType->hasError())
```
Comment (azarovalex) [inline lib/Sema/TypeCheckConcurrency.cpp:1189]: I don't think we should bail out early if result is sending, there are a lot of other checks further down in this function that should still pass. Also the return value can't be `true` here, since `true` means that an error was emitted, in our case though there is no error.

Comment (stzn) [reply lib/Sema/TypeCheckConcurrency.cpp:1189]: Thank you.

> Also the return value can't be true here,
It was my misunderstanding🤦🏻‍♂️ Let me fix it.

> We probably shouldn't bail out early if the result is markin with sending, there are a lot of other checks further down in this function that should still pass.

How about checking diag.ID like the below?

```
if (diag.ID == diag::non_sendable_result_in_witness.ID &&
            func->hasSendingResult() && !resultType->hasError())
    return false;
```

non_sendable_result_in_witness.ID is “non-sendable type %0 cannot be returned from %2 implementation to caller of protocol requirement %1”.

Comment (stzn) [reply lib/Sema/TypeCheckConcurrency.cpp:1189]: @azarovalex 

Hi, what do you think about https://github.com/swiftlang/swift/pull/78601#discussion_r1919488417 ?

**Review by xedin — COMMENTED** [review]
`subscript` declarations can have `sending` on parameters/result:

```
struct S {
    subscript(_: sending Int) -> Bool { true }
}
```

I think it should be possible to unify some of the logic in this function because i.e. `getParameters()` and `getIndices()` both produce `ParameterList *` and for results the logic is pretty much the same except to exactly how the type has been retrieved.

**Comment by stzn** [comment]
@xedin 

Thank you very much for the advice. I combined the function and subscript checks into one.
I have a question. I tried reproducing the issue with the subscript, but I encountered a different error as shown below.

```swift

class NonSendable {}

protocol P {
    subscript(_: sending NonSendable) -> Bool { get }
}

@MainActor
class C: P {
    // Main actor-isolated subscript 'subscript(_:)' cannot be used to satisfy nonisolated protocol requirement
    subscript(_: sending NonSendable) -> Bool { true } // If add `nonisolated`, the error is solved
}
```

I tried more patterns, but all of them successfully built.
Is there a way to reproduce the issue with subscripts? I’d like to add tests for it.

File: lib/Sema/TypeCheckConcurrency.cpp [hunk 4]
```diff
@@ -1160,32 +1160,48 @@ bool swift::diagnoseNonSendableTypesInReference(
...
       }
     }
 
-    // Check the result type of a function.
-    if (auto func = dyn_cast<FuncDecl>(function)) {
+    // Check the result type of a function or subscript.
+    if (auto func = dyn_cast<FuncDecl>(decl)) {
       if (funcCheckOptions.contains(FunctionCheckKind::Results)) {
         // only check results if funcCheckKind specifies so
         Type resultType = func->getResultInterfaceType().subst(subs);
```
Comment (stzn) [inline lib/Sema/TypeCheckConcurrency.cpp:1195]: That's incorrect. I'll correct it.

**Comment by stzn** [comment]
I’m currently looking into several potential issues related to subscripts that use the 
`sending` keyword.

### 1

An assertion failure occurs during SIL generation (see https://github.com/swiftlang/swift/blob/main/lib/AST/ASTPrinter.cpp#L3816). It appears that 
`ParameterTypeFlags` is not set the `sending` flag. The issue occurs when printing the subscript getter in `SILWitnessTable`.

```
sil_witness_table hidden S: P module main {
  method #P.subscript!getter: <Self where Self : P> (Self) -> (Assertion failed: (flags.isSending() && "Only valid when sending is enabled"), function printParameterFlags, file ASTPrinter.cpp, line 3759.
```

Steps to reproduce:

Run the following: swift -frontend -emit-sil -swift-version 6

```swift
protocol P {
    subscript(_: sending NonSendable) -> Bool { get }
}

struct S: P {
    subscript(_: sending NonSendable) -> Bool { true }
}
```

### 2

The `SubscriptDecl` does not have a `HasSending` field, so retrieving sending information relies on the 
`SendingTypeExpr`. I am uncertain whether this is the correct approach.

### 3

The `sending` keyword is not printed because the AST printer does not handle it (see https://github.com/swiftlang/swift/blob/main/lib/AST/ASTPrinter.cpp#L4408).

For example, given the following code:

```swift
struct S5 {
    subscript(_: Bool) -> sending NonSendable { NonSendable() }
}
```

The output is:

```
struct S5 {
  subscript(_: Bool) -> NonSendable { get }
  init()
}
```

In this case, the `sending` keyword is omitted. I am unsure if this behavior is intentional.

**Comment by stzn** [comment]
I made a mistake with the branch. I'll correct it.

**Comment by stzn** [comment]
I think I can find all of my answers in [the comment](https://github.com/swiftlang/swift/pull/78601#issuecomment-2619917546).

So, I’d like to proceed with this PR again.

What do I need to modify more to fix [the original issue](https://github.com/swiftlang/swift/issues/76710)?

**Comment by stzn** [comment]
@xedin

I fixed related issues in other PRs: https://github.com/swiftlang/swift/pull/79042 and https://github.com/swiftlang/swift/pull/79560. I've also confirmed this fix still works on `swift-DEVELOPMENT-SNAPSHOT-2025-04-03-a`.

Could you take a look at this PR again?

**Comment by xedin** [comment]
Sure, I'll add it to my queue for Monday!

File: lib/Sema/TypeCheckConcurrency.cpp [hunk 5]
```diff
@@ -1168,34 +1168,58 @@ bool swift::diagnoseNonSendableTypesInReference(
...
+        decl = func;
+      } else if (auto subscript = dyn_cast<SubscriptDecl>(decl)) {
+        resultType = subscript->getElementInterfaceType().subst(subs);
+        hasSendingResult = isa<SendingTypeRepr>(subscript->getResultTypeRepr());
+      }
+      if (!resultType) {
+        return false;
+      }
+      auto diag = getSendableResultDiag(refKind);
+      if (diag.ID == diag::non_sendable_result_in_witness.ID &&
```
Comment (xedin) [inline lib/Sema/TypeCheckConcurrency.cpp:1214]: I don't think using diagnostic id as a conditional here is a good idea and what does that only apply to witnesses?

File: lib/Sema/TypeCheckConcurrency.cpp [hunk 6]
```diff
@@ -1168,34 +1168,58 @@ bool swift::diagnoseNonSendableTypesInReference(
...
+      if (auto function = dyn_cast<AbstractFunctionDecl>(decl)) {
+        paramList = function->getParameters();
+      } else if (auto subscript = dyn_cast<SubscriptDecl>(decl)) {
+        paramList = subscript->getIndices();
+      }
+
+      // Check params of this function or subscript override for sendability
+      for (auto param : *paramList) {
         Type paramType = param->getInterfaceType().subst(subs);
+        if (param->isSending() && !paramType->hasError()) {
```
Comment (xedin) [inline lib/Sema/TypeCheckConcurrency.cpp:1187]: Should this check instead be a part of `diagnoseNonSendableTypes`? We do pass a declaration there, it could be declaration of the parameter instead of the whole function. This might make it easier to diagnose result types properly as well.

Comment (stzn) [reply lib/Sema/TypeCheckConcurrency.cpp]: Thank you for checking.

I moved the check into a new method `diagnoseNonSendableTypesWithSendingCheck`. https://github.com/swiftlang/swift/pull/78601/commits/765f8acf7bd13df51db6887721f395aff8ef4b87

How about this?

Comment (xedin) [reply lib/Sema/TypeCheckConcurrency.cpp]: Yes, that looks great, thank you!

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

File: lib/Sema/TypeCheckConcurrency.h [hunk 7]
```diff
@@ -436,6 +437,38 @@ namespace detail {
...
+      return false;
+    }
+  }
+  if (auto *func = dyn_cast<FuncDecl>(decl)) {
+    if (func->hasSendingResult())
+      return false;
+  }
+  if (auto *subscript = dyn_cast<SubscriptDecl>(decl)) {
+    if (auto resultTypeRepr = subscript->getResultTypeRepr())
+      if (isa<SendingTypeRepr>(resultTypeRepr))
```
Comment (xedin) [inline lib/Sema/TypeCheckConcurrency.h:463]: You can simplify this down to `isa_and_nonnull<SendingTypeRepr>(subscript->getResultTypeRepr())`

**Comment by xedin** [comment]
@swift-ci please test

File: lib/Sema/TypeCheckConcurrency.h (hunk 7 above)
Comment (stzn) [reply lib/Sema/TypeCheckConcurrency.h]: @xedin 
Thank you! I fixed it.
https://github.com/swiftlang/swift/pull/78601/commits/55e8d5579ffa2873d240daaf4558a345f02fad1c

**Comment by omochi** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility debug

**Comment by xedin** [comment]
@swift-ci please test source compatibility debug

**Comment by xedin** [comment]
We had a PR with some diagnostic messages land recently, let's re-run smoke test macOS just in case and land this.

**Comment by xedin** [comment]
@swift-ci please smoke test macOS platform

**Comment by xedin** [comment]
@swift-ci please test source compatibility debug
