### PR TITLE
[SR-15231] #sourceLocation doesn't recognize CRLF line endings #57553

### LINKED ISSUE #57553: [SR-15231] #sourceLocation doesn't recognize CRLF line endings
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15231      |
   |Radar             | None         |
   |Original Reporter | luiz (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

compnerd.org Swift version 5.5 (swift-5.5-RELEASE)  
Target: x86_64-unknown-windows-msvc

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug, Parser        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: dd11ee2dd4b9697e5789194705a8281b

  </details>

**Issue Description:**

It seems that \#sourceLocation rejects any trailing characters after the closing ')' except for line breaks, but on Windows or other machines which default to CRLF, it incorrectly identifies the carriage-return before the line feed as an extraneous character.

Steps to reproduce:

1\. Create a standalone .swift file  
2. In an editor that supports changing line ending modes, write the following dummy code:

``` swift
#sourceLocation(file: "test.swift", line: 1)
#sourceLocation()
```

3\. Verify that in LF line ending mode swift compiles the file successfully.  
4. Change line endings to be CRLF  
5. Re-compile file

Expected:

File compile with no issues.

Actual result:

File compiles with errors:

``` java
test.swift:1:44: error: extra tokens at the end of #sourceLocation directive
#sourceLocation(file: "test.swift", line: 1)
                                           ^
test.swift:3:1: error: parameterless closing #sourceLocation() directive without prior opening #sourceLocation(file:,line:) directive
```

### PR DESCRIPTION
**Pull request by grynspan**
This fix allows for the presence of a single `\r` character before `\n` in a line containing a `#sourceLocation` directive.

Resolves #57553.

### CODE REVIEW

**Comment by grynspan** [comment]
@swift-ci please test

**Review by compnerd — APPROVED** [review]
Thanks for fixing this!

**Review by rintaro — APPROVED** [review]

**Comment by grynspan** [comment]
@swift-ci please test macOS

**Comment by grynspan** [comment]
@swift-ci please test

File: lib/Parse/ParseDecl.cpp [hunk 1]
```diff
@@ -5950,6 +5950,9 @@ ParserStatus Parser::parseLineDirective(bool isLine) {
   // line.
   while (*LastTokTextEnd == ' ' || *LastTokTextEnd == '\t')
     ++LastTokTextEnd;
+  if (*LastTokTextEnd == '\r') {
```
Comment (al45tair) [inline lib/Parse/ParseDecl.cpp:5953]: IMO this code should read
```
  while (*LastTokTextEnd == ' ' || *LastTokTextEnd == '\t')
    ++LastTokTextEnd;

  SourceLoc nextLineStartLoc;
  switch (*LastTokTextEnd++) {
  case '\r':
    if (*LastTokTextEnd == '\n')
      ++LastTokTextEnd;
    LLVM_FALLTHROUGH;
  case '\n':
    nextLineStartLoc = Lexer::getSourceLoc(LastTokTextEnd);
    break;
  default:
    diagnose(Tok.getLoc(), diag::extra_tokens_line_directive);
    return makeParserError();
  }
```

That better matches what we do in the lexer (namely, we generally regard `\r`, `\r\n` and `\n` as line endings; there are probably some omissions, but those are bugs IMO).

File: test/Parse/line-directive-crlf.swift.gyb.swift [hunk 2]
```diff
@@ -0,0 +1,10 @@
+// RUN: %empty-directory(%t)
+// RUN: %gyb %t/line-directive-crlf.swift
+// RUN: %target-typecheck-verify-swift
+// RUN: not %target-swift-frontend -c %t/line-directive-crlf.swift 2>&1 | %FileCheck %t/line-directive-crlf.swift
+
+// https://github.com/apple/swift/issues/57553
+func I57553() {
+% print("#sourceLocation(file: \"issue-57553.swift\", line: 12345)\r\n")
+% print("#sourceLocation()\r\n")
+}
```
Comment (al45tair) [inline test/Parse/line-directive-crlf.swift.gyb.swift:10]: Rather than just testing `\r\n`, could we please test `\r`, `\r\n` and `\n` here? All of them should work, IMO.

**Review by al45tair — CHANGES_REQUESTED** [review]

**Comment by grynspan** [comment]
@swift-ci please test

**Comment by grynspan** [comment]
@swift-ci please test

**Review by al45tair — APPROVED** [review]

**Comment by grynspan** [comment]
@swift-ci please test macOS
