### PR TITLE
[cxx-interop] Emit type metadata for foreign types more often

### LINKED ISSUE #75593: Interop: Compiler and C++ Bridging header disagree on ABI of `Optional<CxxValueType>`
### Description

When writing a swift function that returns a small optional C++ value type, the swift compiler seems to generates code to
- assume that the calling scope's return slot has space for the type + a bool (?)
- construct the C++ type by calling its constructor
- return the `Optional<CxxValueType>` in a register.

On the other hand, the generated bridging header from -emit-clang-header-path seems to think the type will be returned as a heap allocated allocated objective-c type (?) with a type metadata and everything that goes along with that.

### Reproduction

The reproduction for this requires a few files:
- a C++ type
- a swift function to return `CxxType?` from that function
- a C++ function that calls the swift function

I've created a project here that can reproduce the issue https://github.com/ADKaster/swift-shlib-cxx-exe with 
```
cmake -B build -GNinja && cmake --build build
```

The most important files are below:

Color.h
```c++
#pragma once

#include <stdint.h>

class Color
{
public:
    Color() = default;
    explicit Color(uint32_t rep) : m_rep(rep) { }

    static bool fromString(Color&, char const*);

private: 
    uint32_t m_rep { 0 };
};
```

Color.cpp
```c++
#include "Color.h"

#include <swift/bridging>
#include <shlib-Swift.h>

bool Color::fromString(Color& color, char const* str)
{
    if (auto c = SwiftShlib::colorFromString(str)) {
        color = c.get();
        return true;
    }
    return false;
}

```

Color.swift
```swift
import shlib

public func colorFromString(_ str: String) -> shlib.Color?
{
    if (str == "red") {
        return Color(1234)
    }
    return nil
}
```

Building with `-DCMAKE_BUILD_TYPE=Debug`, this produces the following linker error:

```
[1/2] Linking Swift shared library shlib/libshlib.so
FAILED: shlib/libshlib.so 
: && /home/andrew/swift/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swiftc -j 32 -num-threads 32 -emit-library -Onone -g  -Xlinker --no-allow-shlib-undefined -Xlinker --no-undefined /home/andrew/swift/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/lib/swift/linux/x86_64/swiftrt.o -use-ld=lld  -Xlinker -soname -Xlinker libshlib.so -o shlib/libshlib.so shlib/CMakeFiles/shlib.dir/Color.cpp.o shlib/CMakeFiles/shlib.dir/Color.swift.o -L /home/andrew/swift/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/lib/swift/linux   -L /home/andrew/swift/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/lib/swift/linux/x86_64   -L /usr/lib/gcc/x86_64-linux-gnu/12 -lstdc++  -lm  -lgcc_s  -lgcc  -lc  -lgcc_s  -lgcc && :
error: link command failed with exit code 1 (use -v to see invocation)
ld.lld: error: undefined symbol: $sSo5ColorVMa
>>> referenced by shlib-Swift.h:5765 (shlib/include/shlib-Swift.h:5765)
>>>               /home/andrew/ladybird-org/testing/swift-tests/swift-shlib-cxx-exe/build/shlib/CMakeFiles/shlib.dir/Color.cpp.o:(swift::TypeMetadataTrait<Color>::getTypeMetadata())
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

with `-DCMAKE_BUILD_TYPE=Release`, the error is a bit different and less helpful:

```
error: link command failed with exit code 1 (use -v to see invocation)
ld.lld: error: undefined symbol: $sSo5ColorVMa
>>> referenced by Color.cpp
>>>               /home/andrew/ladybird-org/testing/swift-tests/swift-shlib-cxx-exe/build/shlib/CMakeFiles/shlib.dir/Color.cpp.o:(Color::fromString(Color&, char const*))
>>> referenced by Color.cpp
>>>               /home/andrew/ladybird-org/testing/swift-tests/swift-shlib-cxx-exe/build/shlib/CMakeFiles/shlib.dir/Color.cpp.o:(Color::fromString(Color&, char const*))
>>> referenced by Color.cpp
>>>               /home/andrew/ladybird-org/testing/swift-tests/swift-shlib-cxx-exe/build/shlib/CMakeFiles/shlib.dir/Color.cpp.o:(Color::fromString(Color&, char const*))
>>> referenced 1 more times
```

### Expected behavior

The program should link successfully. getTypeMetadata should not be called when the swift compiler does not actually emit type metadata.

### Environment

$ /home/andrew/swift/build/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swiftc  -version
Swift version 6.0-dev (LLVM 3427f33b53c666b, Swift 225809e3f8e9c7b)
Target: x86_64-unknown-linux-gnu

Also tested with:

$ swiftc -version
swift-driver version: 1.111.2 Apple Swift version 6.0 (swiftlang-6.0.0.5.15 clang-1600.0.22.6)
Target: arm64-apple-macosx14.0

### Additional information

https://forums.swift.org/t/cxxinterop-swift-function-returning-optional-c-type-in-shlib-doesnt-generate-metadata/73423

### PR DESCRIPTION
**Pull request by Xazax-hun**
Metadata for foreign types are emitted lazily, when SILGen generates a reference to it. Unfortunately, C++ reverse interop can also introduce references to such metadata in the generated header when types are used as generic arguments. This adds a type visitor to make note of the type metadata use for those generic arguments in public APIs when C++ interop is enabled. Fixes #75593

rdar://132925256

### CODE REVIEW

**Comment by Xazax-hun** [comment]
@swift-ci please smoke test

File: lib/IRGen/IRGenSIL.cpp [hunk 1]
```diff
@@ -2472,6 +2476,76 @@ static void emitDynamicSelfMetadata(IRGenSILFunction &IGF) {
   IGF.setDynamicSelfMetadata(selfTy, isExact, value, selfKind);
 }
 
+namespace {
+// Notes the use of foreign types in generic arguments for C++ interop.
+class NoteUseOfForeignTypeMetadata
```
Comment (slavapestov) [inline lib/IRGen/IRGenSIL.cpp:2481]: Why not use Type::walk() to recursively visit everything instead of manually destructuring types like this?

File: lib/IRGen/IRGenSIL.cpp [hunk 2]
```diff
@@ -2472,6 +2476,76 @@ static void emitDynamicSelfMetadata(IRGenSILFunction &IGF) {
...
+    for (auto type : TT->getElementTypes())
+      TypeVisitor::visit(type, isInGenericArgument);
+  }
+
+  void visitSugarType(SugarType *sugarTy, bool isInGenericArgument) {
+    TypeVisitor::visit(sugarTy->getSinglyDesugaredType(), isInGenericArgument);
+  }
+
+  void visitClassType(ClassType *CT, bool isInGenericArgument) {
+    noteUseOfTypeMetadata(CT->getDecl(), isInGenericArgument);
```
Comment (slavapestov) [inline lib/IRGen/IRGenSIL.cpp:2498]: For example, for non-generic nominal types you also have to visit getParent(), which might be generic (`struct G<T> { struct Nested {} }`). If that can't come up in your case, you can add an `ASSERT(!CT->isSpecialized())`

File: lib/IRGen/IRGenSIL.cpp (hunk 1 above)
Comment (Xazax-hun) [reply lib/IRGen/IRGenSIL.cpp:2481]: Oh, I totally missed the existence of that API! Thanks for bringing it to my attention. I'll give this a try tomorrow.

File: lib/IRGen/IRGenSIL.cpp (hunk 2 above)
Comment (Xazax-hun) [reply lib/IRGen/IRGenSIL.cpp:2498]: Would `Type::walk()` also visit the parents?

Comment (slavapestov) [reply lib/IRGen/IRGenSIL.cpp:2498]: Yes, it will visit everything.

**Comment by Xazax-hun** [comment]
@swift-ci please smoke test

File: lib/IRGen/IRGenSIL.cpp (hunk 1 above)
Comment (Xazax-hun) [reply lib/IRGen/IRGenSIL.cpp]: Thanks! I switched to `Type::walk` and it looks much cleaner.

**Comment by Xazax-hun** [comment]
Looks like emitting type metadata for foreing types on Windows is not supported at the moment.

@swift-ci please smoke test

File: lib/IRGen/IRGenSIL.cpp [hunk 3]
```diff
@@ -2472,6 +2476,53 @@ static void emitDynamicSelfMetadata(IRGenSILFunction &IGF) {
   IGF.setDynamicSelfMetadata(selfTy, isExact, value, selfKind);
 }
 
+/// C++ interop might refer to the type metadat in some scenarios.
```
Comment (ADKaster) [inline lib/IRGen/IRGenSIL.cpp:2479]:
```suggestion
/// C++ interop might refer to the type metadata in some scenarios.
```

File: lib/IRGen/IRGenSIL.cpp [hunk 4]
```diff
@@ -2472,6 +2476,53 @@ static void emitDynamicSelfMetadata(IRGenSILFunction &IGF) {
...
+/// This function covers those cases and makes sure metadata is emitted
+/// for the foreing types.
```
Comment (ADKaster) [inline lib/IRGen/IRGenSIL.cpp:2481]:
```suggestion
/// for the foreign types.
```

File: lib/IRGen/IRGenSIL.cpp [hunk 5]
```diff
@@ -2487,6 +2538,12 @@ void IRGenModule::emitSILFunction(SILFunction *f) {
       f->isAvailableExternally())
     return;
 
+  // Type metadata for foreign references is not yet supported on Windows.
```
Comment (ADKaster) [inline lib/IRGen/IRGenSIL.cpp:2541]: Is there/should there be a tracking issue for this feature on Windows in the swiftlang/swift issue tracker?

**Review by ADKaster — COMMENTED** [review]
surface level from me, thanks for looking at my reported issue!

File: lib/IRGen/IRGenSIL.cpp (hunk 5 above)
Comment (Xazax-hun) [reply lib/IRGen/IRGenSIL.cpp:2541]: @egorzhdan do you know if we already track this somewhere?

Comment (egorzhdan) [reply lib/IRGen/IRGenSIL.cpp:2541]: I don't think we have an issue yet, but it would make sense to have one! 🙂

Comment (Xazax-hun) [reply lib/IRGen/IRGenSIL.cpp:2541]: Ok, opened one: https://github.com/swiftlang/swift/issues/76168

**Comment by Xazax-hun** [comment]
@swift-ci please smoke test

**Comment by Xazax-hun** [comment]
@swift-ci please smoke test

File: lib/IRGen/IRGenSIL.cpp [hunk 6]
```diff
@@ -2487,6 +2538,12 @@ void IRGenModule::emitSILFunction(SILFunction *f) {
       f->isAvailableExternally())
     return;
 
+  // Type metadata for foreign references is not yet supported on Windows. Bug #76168.
```
Comment (compnerd) [inline lib/IRGen/IRGenSIL.cpp:2541]: Is there a reason that this is not supported on Windows?

Comment (egorzhdan) [reply lib/IRGen/IRGenSIL.cpp:2541]: My understanding is that on Windows we end up requiring a metadata completion function for C++ foreign reference types. That logic just isn't implemented yet for C++ types.

https://github.com/swiftlang/swift/blob/bd313deae5fef61d7e167a90f5dd39a2dea4b251/lib/IRGen/GenMeta.cpp#L6636-L6639

**Review by egorzhdan — APPROVED** [review]

File: lib/IRGen/IRGenSIL.cpp [hunk 7]
```diff
@@ -2472,6 +2476,53 @@ static void emitDynamicSelfMetadata(IRGenSILFunction &IGF) {
...
+
+  // Notes the use of foreign types in generic arguments for C++ interop.
+  auto processType = [&](CanType type) {
+    struct Walker : TypeWalker {
+      Walker(IRGenerator &IRGen) : IRGen(IRGen) {}
+
+      Action walkToTypePre(Type ty) override {
+        if (auto *BGT = ty->getAs<BoundGenericType>())
+          genericDepth++;
+        else if (auto *nominal = ty->getAs<NominalType>())
```
Comment (DougGregor) [inline lib/IRGen/IRGenSIL.cpp:2495]: I'm not sure I understand the goal of `genericDepth` here. It's going to increase whenever we're walking into a type like `X<Y>`, and suppress the type metadata for both `X` and `Y`. Is that intended?

My expectation based on the comment is that you wanted to emit metadata for any non-generic types encountered along the way. To do that, you could skip the `genericDepth` bit and instead check whether the nominal type declaration has a generic signature where `areAllParamsConcrete()` is false.

Comment (Xazax-hun) [reply lib/IRGen/IRGenSIL.cpp:2495]: My goal is to emit metadata for the foreign type `Y` when it was a generic argument, e.g., in `X<Y>`. 

My understanding is that we visit `X` first, increase the counter, visit `Y` later with the counter set to 1, so we emit metadata for Y. I only wanted to avoid emitting metadata for the outermost types (in this case `X`). 

> My expectation based on the comment is that you wanted to emit metadata for any non-generic types encountered along the way.

Emitting metadata for every non-generic type would emit metadata for `X` (a single non-generic type). But we do not need metadata for that, only for types that are used as generic arguments.

Comment (DougGregor) [reply lib/IRGen/IRGenSIL.cpp:2495]: Okay! I misunderstood the premise. Looks good, then.

**Review by DougGregor — APPROVED** [review]

File: lib/IRGen/IRGenSIL.cpp (hunk 7 above)
Comment (Xazax-hun) [reply lib/IRGen/IRGenSIL.cpp:2495]: Hmm, I think the most probably the most concise way to describe what I wanted to do here is to collect all the generic arguments recursively.

**Comment by Xazax-hun** [comment]
@swift-ci please smoke test

**Comment by Xazax-hun** [comment]
Only rerunning tests because the last completion was a long time ago (to make sure it does not conflict with anything added since then).

**Comment by Xazax-hun** [comment]
@swift-ci please smoke test windows

**Comment by rjmccall** [comment]
This is acceptable as a short-term workaround, but in the long term we don't want to be doing this.  It is an important goal of C++ interop to be able to work with an arbitrary existing Swift module, which means we must not require the module to be emitted in a special way.  Maybe we need some ability to emit a supporting .o when emitting a C++ interop header.
