### PR TITLE
[Serialization][wasm] Preserve wasm import metadata for SIL serialization

### LINKED ISSUE #87320: [WebAssembly] "wasm-ld: import module mismatch for symbol" when using `@_extern(wasm, ...)`
### Description

When adding a decl like this
`@_extern(wasm, module: "BrowserInterop", name: "something")`
in a library, linking will fail in certain conditions with an error like this:

```
wasm-ld: error: import module mismatch for symbol: $e14BrowserInterop31bjs_JSWindow_scrollY_get_extern33_A850048D7CA460B221AE34673489EEABLLySds5Int32VF
>>> defined as env in /Users/simon/dev/elementary-swift/elementary-ui/Examples/Basic/.build/wasm32-unknown-wasip1/release/App.build/AnimationsView.swift.o
>>> defined as BrowserInterop in /Users/simon/dev/elementary-swift/elementary-ui/Examples/Basic/.build/wasm32-unknown-wasip1/release/BrowserInterop.build/BridgeJS.swift.o
```

see this PR: https://github.com/swiftlang/swift/pull/87250

The module name is lost, and two mismatching symbols (one with the correct module, one with default "env") cause an error.

### Reproduction

https://github.com/swiftwasm/JavaScriptKit/issues/657
https://github.com/swiftwasm/JavaScriptKit/pull/628
https://github.com/swiftwasm/JavaScriptKit/pull/631

### Expected behavior

module name is not lost during optimization / compilation, linking works

### Environment

swift-6.2.3-RELEASE_wasm-embedded

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by kateinoigakukun**
Serialize/deserialize wasm import module/name for SIL serialization so inlined decls keep their import names. Otherwise, inlining a function with `@_extern(wasm)` would lose the import name and cause IRGen to emit an import from the default module "env".

Related links: https://github.com/swiftwasm/JavaScriptKit/pull/631 https://github.com/swiftwasm/JavaScriptKit/pull/628

Resolves https://github.com/swiftlang/swift/issues/87320

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
@swift-ci smoke test

**Comment by kateinoigakukun** [comment]
@swift-ci smoke test

**Comment by kateinoigakukun** [comment]
@swift-ci smoke test

**Comment by kateinoigakukun** [comment]
@swift-ci smoke test macOS Platform

**Comment by kateinoigakukun** [comment]
@swift-ci smoke test Windows Platform

**Comment by kateinoigakukun** [comment]
@swift-ci smoke test macOS Platform

**Comment by MaxDesiatov** [comment]
@kateinoigakukun would you mind creating an issue that tracks this at https://github.com/swiftlang/swift/issues? If you plan to cherry-pick this for 6.3 the issue will be required anyway, but also desirable for `main`-only PRs

**Comment by kateinoigakukun** [comment]
Opened a cherry-pick PR against 6.3 https://github.com/swiftlang/swift/pull/87335

File: lib/Serialization/DeserializeSIL.cpp [hunk 1]
```diff
@@ -1084,6 +1086,16 @@ llvm::Expected<SILFunction *> SILDeserializer::readSILFunctionChecked(
       case ExtraStringFlavor::Section:
         fn->setSection(blobData);
         break;
+      case ExtraStringFlavor::WasmImportModule:
+        WasmImportModule = blobData;
+        if (!WasmImportField.empty())
```
Comment (eeckstein) [inline lib/Serialization/DeserializeSIL.cpp]: Can it be that only one of these two attributes is set and the other is empty? Then you wouldn't set the non-empty attribute at all.

Comment (kateinoigakukun) [reply lib/Serialization/DeserializeSIL.cpp]: Good point! Yes, one of them can be empty. Added tests to cover such cases.

**Comment by kateinoigakukun** [comment]
@swift-ci smoke test

**Review by eeckstein — APPROVED** [review]
lgtm

**Review by DougGregor — APPROVED** [review]
