### PR TITLE
Fix missing indexing data with overloaded type

### LINKED ISSUE #64598: Index data incomplete when referencing an ambiguous type name
**Description**

With this code:

```swift
// Module0
public struct Thing {
    public init(string: String) {}
}
// Module1
public struct Thing {}
// Module2
import Module0
import Module1

func foo() {
    _ = Thing(string: "lol")
}
```

The index data for Module3 includes no references at all to `Thing` or the initializer being called. This is easiest to visualize with [indexutil-annotate](https://github.com/lyft/swift-index-store/tree/main/Sources/indexutil-annotate):

```swift
// Module2
/*
       module=Module0=usr is c:@M@Module0
       v  */
import Module0
/*
       module=Module1=usr is c:@M@Module1
       v  */
import Module1

/*
     function=foo()=usr is s:7Module23fooyyF
     v  */
func foo() {
    _ = Thing(string: "lol")
}
```

If I add the explicit module name to the call like this: `_ = Module0.Thing(string: "lol")` we get what appears to be the right data:

```swift
// Module2
/*
       module=Module0=usr is c:@M@Module0
       v  */
import Module0
/*
       module=Module1=usr is c:@M@Module1
       v  */
import Module1

/*
     function=foo()=usr is s:7Module23fooyyF
     v  */
func foo() {
    /*
        module=Module0=usr is c:@M@Module0
        |       struct=Thing=usr is s:7Module05ThingV
        |       constructor=init(string:)=usr is s:7Module05ThingV6stringACSS_tcfc
        v       v  */
    _ = Module0.Thing(string: "lol")
}
```

Also removing the import to `Module1` also gives us the right info:

```swift
// Module2
/*
       module=Module0=usr is c:@M@Module0
       v  */
import Module0

/*
     function=foo()=usr is s:7Module23fooyyF
     v  */
func foo() {
    /*
        struct=Thing=usr is s:7Module05ThingV
        constructor=init(string:)=usr is s:7Module05ThingV6stringACSS_tcfc
        v  */
    _ = Thing(string: "lol")
}
```

**Steps to reproduce**

Using this project [initextension.zip](https://github.com/apple/swift/files/11057383/initextension.zip) and [`indexutil-annotate`](https://github.com/lyft/swift-index-store/tree/main/Sources/indexutil-annotate):

1. `swift build`
2. `indexutil-annotate .build/debug/index/store/ Sources/Module2/Module2.swift`

You can also inspect the record naively with `strings` to see there are no other string references to `Module2`:

```
% strings $(find .build/debug/index/store/v5/records -name "Module2.swift*")
IDXR
Module0c:@M@Module0
Module1c:@M@Module1
foo()s:7Module23fooyyF
```

**Expected behavior**

The specific type should be known because the initializer disambiguates it, and that should be present in the index data.

**Environment**
- Swift compiler version info 5.7.2
- Xcode version info 14.2.14C18

I also tested with Swift @ 1b13b598bfdb3fad418dc86fab94f90e4f114c5e

### PR DESCRIPTION
**Pull request by keith**
When you have a type that's ambiguous because it's defined in 2 imported modules, but you don't have to disambiguate by using the module name, previously no index references were produced. Now most are for the common case, but notably nested type constructors and generics still aren't emitted, partially because of https://github.com/apple/swift/issues/65726

Fixes: https://github.com/apple/swift/issues/64598

### CODE REVIEW

**Comment by keith** [comment]
@swift-ci please test

File: lib/Sema/CSApply.cpp [hunk 1]
```diff
@@ -627,6 +627,7 @@ namespace {
       if (isa<TypeDecl>(decl) && !isa<ModuleDecl>(decl)) {
         auto typeExpr = TypeExpr::createImplicitHack(
             loc.getBaseNameLoc(), adjustedFullType->getMetatypeInstanceType(), ctx);
+        typeExpr->setImplicit(implicit);
```
Comment (xedin) [inline lib/Sema/CSApply.cpp:630]: Could you please elaborate on why this is necessary?

File: include/swift/AST/TypeRepr.h [hunk 2]
```diff
@@ -1145,10 +1145,11 @@ class CompileTimeConstTypeRepr : public SpecifierTypeRepr {
 class FixedTypeRepr : public TypeRepr {
   Type Ty;
   SourceLoc Loc;
+  bool IsSelf;
```
Comment (xedin) [inline include/swift/AST/TypeRepr.h:1148]: Why do we need this flag is this could be established based on `Ty`?

Comment (keith) [reply include/swift/AST/TypeRepr.h:1148]: AFAICT the type being written as Self isn't inspectable anywhere, but in the case of the index that impacts whether or not the reference should be implicit or explicit

File: lib/Sema/CSApply.cpp (hunk 1 above)
Comment (keith) [reply lib/Sema/CSApply.cpp:630]: In this case even though the type is written directly, this codepath creates it implicit in the AST, even though (AFAIUI) it is definitely explicit as it is written in the file (unlike other implicit cases with type inference etc). The thing that I'm wary about with this is I don't know, besides the index, what other implications this has

File: include/swift/AST/TypeRepr.h (hunk 2 above)
Comment (xedin) [reply include/swift/AST/TypeRepr.h:1148]: I wonder whether it would make sense to have a special Repr node for this instead of just a flag?

File: lib/Sema/CSApply.cpp (hunk 1 above)
Comment (xedin) [reply lib/Sema/CSApply.cpp:630]: I understand what you mean regarding the type being provided by the user but if we have to synthesize something we should mark it as `implicit`, having a valid loc here should be all that matters.

Comment (keith) [reply lib/Sema/CSApply.cpp:630]: this is probably just me not knowing about how this works entirely, but what qualifies for us synthesizing something? because i guess in this case the only LOC difference being an `import` to hit the implicit vs explicit case of this makes it seem to me like we're not synthesizing anything major here. Also implicit vs explicit is the only difference in the AST, I guess I assume more would be different if major things are synthesized?

File: include/swift/AST/TypeRepr.h (hunk 2 above)
Comment (keith) [reply include/swift/AST/TypeRepr.h:1148]: If this is the only place where we care about the difference with this maybe not? I guess it would either be this or a subclass of FixedTypeRepr that could be used to determine if they different?

Comment (hamishknight) [reply include/swift/AST/TypeRepr.h:1148]: IMO a new TypeRepr would be best, `Self` is the only user of `FixedTypeRepr` outside of `TypeExpr::createImplicitHack`, and that really ought to be the only user.

**Comment by keith** [comment]
@swift-ci please test

File: lib/Sema/CSApply.cpp (hunk 1 above)
Comment (keith) [reply lib/Sema/CSApply.cpp:630]: do you think this is on the right track or should i look for another solution here?

**Review by slavapestov — COMMENTED** [review]
I'm not sure it makes sense to add a new TypeRepr for `Self`, especially since it appears to only be used in preCheckExpr(). TypeReprs are syntactic constructs and `Self` is not special in any way as far as the syntax is concerned.

Why does indexing look at TypeReprs at all?

**Comment by keith** [comment]
@swift-ci please test linux platform

**Comment by keith** [comment]
Friendly bump

File: lib/Sema/CSApply.cpp (hunk 1 above)
Comment (hamishknight) [reply lib/Sema/CSApply.cpp:630]: IMO this seems reasonable enough to me, if the type was written explicitly by the user, the AST node representing it should be explicit. That being said, I think a better way of doing this would be to use `TypeExpr::createForDecl` if `implicit` is `false`, which will create a proper `SimpleIdentTypeRepr` for it. This nicely matches the logic in `resolveDeclRefExpr`:

https://github.com/apple/swift/blob/0f201443acf3b12975b63a49611dea8131c007df/lib/Sema/PreCheckExpr.cpp#L666-L676

Arguably the implicit case should also use `TypeExpr::createImplicitForDecl` too.

File: lib/IDE/SourceEntityWalker.cpp [hunk 3]
```diff
@@ -634,15 +634,22 @@ ASTWalker::PreWalkAction SemaAnnotator::walkToTypeReprPre(TypeRepr *T) {
       return Action::StopIf(!Continue);
     }
   } else if (auto FT = dyn_cast<FixedTypeRepr>(T)) {
-    ValueDecl *VD = FT->getType()->getAnyGeneric();
-    if (auto DT = FT->getType()->getAs<DynamicSelfType>())
+    if (ValueDecl *VD = FT->getType()->getAnyGeneric()) {
+      auto Data = ReferenceMetaData(SemaReferenceKind::TypeRef, None);
+      auto Continue = passReference(VD, FT->getType(), FT->getLoc(),
+                                    FT->getSourceRange(), Data);
+      return Action::StopIf(!Continue);
```
Comment (hamishknight) [inline lib/IDE/SourceEntityWalker.cpp:641]: Now that SelfTypeRepr has been separated out, this case should only handle implicit cases, so I think it would make sense to set both `isImplicit` and `isImplicitCtorType` to `true` on the `ReferenceMetaData`

**Review by hamishknight — APPROVED** [review]
Modulo the two comments I've left, this LGTM! (sorry for the late review)

File: lib/IDE/SourceEntityWalker.cpp (hunk 3 above)
Comment (keith) [reply lib/IDE/SourceEntityWalker.cpp:641]: setting `isImplicitCtorType` changes this case: https://github.com/apple/swift/pull/65729/files#diff-1563554316b92e9e77632af5f813d4a441724dfd389f42d401ff291ee254557cR34 to be implicit. If it weren't for the ambiguous type it wouldn't be, so I'm not sure it should be here either?

File: lib/Sema/CSApply.cpp (hunk 1 above)
Comment (keith) [reply lib/Sema/CSApply.cpp]: Done! I didn't touch the other branch thought since I'm not sure the full impact of that

File: lib/IDE/SourceEntityWalker.cpp (hunk 3 above)
Comment (keith) [reply lib/IDE/SourceEntityWalker.cpp]: ah good point, done!

**Comment by keith** [comment]
@swift-ci please test

**Review by xedin — APPROVED** [review]
I concur with @hamishknight comments, this looks good to me too!

**Review by hamishknight — APPROVED** [review]
Thanks!
