### PR TITLE
[Sema] Check for already existential type while resolving existential

### LINKED ISSUE #58920: No compiler error and abort trap when trying to create an existential type of another existential type
**Describe the bug**
When creating a type alias that represents an existential type, if you then attempt to create an existential of the type alias, instead of throwing a compile-time error, the compiler abort traps.

**To Reproduce**

```swift
typealias Iterator = any IteratorProtocol
// This causes an abort trap. It should instead throw an error message such as
// "Iterator" is not a protocol type and cannot be specialized with the "any" keyword.
var example: any Iterator = 5
```

**Expected behavior**
I would expect there to be a compile-time error for this incorrect code, such as "Iterator is not a protocol type and cannot be specialized with the any keyword."

**Environment (please complete the following information):**
 - OS: macOS 12.3
 - Xcode Version/Tag/Branch: Xcode 13.3.1 | Swift Toolchain Snapshot 2022-05-04

``

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
In those cases constraint type will be already resolved as `ExistentialType` which seems to make sense to just return it already. 

Fixes https://github.com/apple/swift/issues/58920

### CODE REVIEW

**Review by xedin — APPROVED** [review]

File: lib/Sema/TypeCheckType.cpp [hunk 1]
```diff
@@ -3980,7 +3980,8 @@ TypeResolver::resolveExistentialType(ExistentialTypeRepr *repr,
                                      TypeResolutionOptions options) {
   auto constraintType = resolveType(repr->getConstraint(),
       options.withContext(TypeResolverContext::ExistentialConstraint));
-  if (constraintType->is<ExistentialMetatypeType>())
+  if (constraintType->is<ExistentialMetatypeType>() ||
+      constraintType->is<ExistentialType>())
```
Comment (hborla) [inline lib/Sema/TypeCheckType.cpp:3984]: Hmm I don't think this is the correct fix. Right now, `ExistentialMetatype` is special because it really should be `ExistentialType`, I just haven't done that refactoring yet. In general, it is not  correct to write `any` in front of an `any` type. I think your test case below would compile if you assigned a type that does conform to `IteratorProtocol`, but instead it should report an error with a fix-it to remove `any`.

Comment (xedin) [reply lib/Sema/TypeCheckType.cpp:3984]: Thank you for the explanation!

Comment (LucianoPAlmeida) [reply lib/Sema/TypeCheckType.cpp:3984]: Ah it does make sense, thanks @hborla 
So every `any ProtocolType` is represented as an `ExistentialType`? In this case the type aliasing for an any type is the same as `any any IteratorProtocol` and seems like I miss that. Will make the changes =]

Comment (hborla) [reply lib/Sema/TypeCheckType.cpp:3984]: Yes, that's correct. Thank you!!

**Review by xedin — APPROVED** [review]

File: lib/Sema/TypeCheckType.cpp [hunk 2]
```diff
@@ -3987,6 +3987,14 @@ TypeResolver::resolveExistentialType(ExistentialTypeRepr *repr,
...
 
+  // Diagnose redundant `any` on an already existential type e.g. any (any P)
+  // with a fix-it to remove first any.
+  if (constraintType->is<ExistentialType>()) {
+    diagnose(repr->getLoc(), diag::redundant_any_in_existential, constraintType)
+        .fixItRemove(repr->getAnyLoc());
+    return constraintType;
+  }
+
   if (!constraintType->isExistentialType()) {
```
Comment (hborla) [inline lib/Sema/TypeCheckType.cpp:3998]: Can we instead fix this here by changing this to `(!constraintType->isConstraintType())`? That seems like the obvious fix to me

Comment (hborla) [reply lib/Sema/TypeCheckType.cpp:3998]: `isConstraintType()` return `true` for `ProtocolType`, `ProtocolCompositionType`, and `ParameterizedProtocolType`, but not `ExistentialType`. This also matches the assertion inside `ExistentialType::get`

Comment (LucianoPAlmeida) [reply lib/Sema/TypeCheckType.cpp]: It makes sense, just adjusted!

Comment (xedin) [reply lib/Sema/TypeCheckType.cpp]: Sorry @LucianoPAlmeida , I'm completely useless for this one :)

**Review by hborla — APPROVED** [review]
Thank you!

File: lib/Sema/TypeCheckType.cpp (hunk 2 above)
Comment (LucianoPAlmeida) [reply lib/Sema/TypeCheckType.cpp]: Ah no worries =]

**Comment by LucianoPAlmeida** [comment]
@swift-ci Please smoke test
