### PR TITLE
[cxx-interop] Use the correct access for synthesized setterDecl

### LINKED ISSUE #82637: AbstractStorageDecl's setter access is out of sync with the access actually on the setter
### Description

1. Apple Swift version 6.2-dev (LLVM ac66248b7c45109, Swift 92fd571d0786efe)
2. Compiling with the current language version
3. While verifying VarDecl 'value' (at GermanString/Sources/CGermanString/include/german.h:15:25)

### Reproduction

I can provide access to my private repo with the code on request.

```
#include <stdint.h>
#include <string.h>

typedef union {
  struct {
    uintptr_t __pad1 : 61;
    uintptr_t is_persistent : 1;
    uintptr_t is_transient  : 1;
    uintptr_t is_temporary  : 1;
  };
  struct {
    uintptr_t __pad2 : 61;
    uintptr_t tag : 3;
  };
  const uint8_t * const value; <---- This line is GermanString/Sources/CGermanString/include/german.h:15:25
} tagged_ptr;

typedef struct {
  uint32_t len;
  uint8_t content[12];
} short_string;

typedef struct {
  uint32_t len;
  uint8_t prefix[4];
  tagged_ptr ptr;
} long_string;

typedef union {
  uint32_t len;
  uint64_t data[2];
  short_string short_;
  long_string long_;
} german_string;
```

### Stack dump

```text
#0 0x00000001087e193c (/Users/jason/Library/Developer/Toolchains/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-06-27-a.xctoolchain/usr/bin/swift-frontend+0x1059d593c)
 #1 0x00000001087e0068 (/Users/jason/Library/Developer/Toolchains/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-06-27-a.xctoolchain/usr/bin/swift-frontend+0x1059d4068)
 #2 0x00000001087e1f84 (/Users/jason/Library/Developer/Toolchains/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-06-27-a.xctoolchain/usr/bin/swift-frontend+0x1059d5f84)
 #3 0x000000019fed6704 (/usr/lib/system/libsystem_platform.dylib+0x1804ce704)
 #4 0x000000019fecc88c (/usr/lib/system/libsystem_pthread.dylib+0x1804c488c)
 #5 0x000000019fdd1860 (/usr/lib/system/libsystem_c.dylib+0x1803c9860)
 #6 0x000000010885e1a0 (/Users/jason/Library/Developer/Toolchains/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-06-27-a.xctoolchain/usr/bin/swift-frontend+0x105a521a0)
 #7 0x00000001045c8980 (/Users/jason/Library/Developer/Toolchains/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-06-27-a.xctoolchain/usr/bin/swift-frontend+0x1017bc980)
 #8 0x00000001045c8458 (/Users/jason/Library/Developer/Toolchains/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-06-27-a.xctoolchain/usr/bin/swift-frontend+0x1017bc458)
 #9 0x00000001045bbc78 (/Users/jason/Library/Developer/Toolchains/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-06-27-a.xctoolchain/usr/bin/swift-frontend+0x1017afc78)
#10 0x00000001045c9d1c (/Users/jason/Library/Developer/Toolchains/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-06-27-a.xctoolchain/usr/bin/swift-frontend+0x1017bdd1c)
#11 0x00000001045c9bdc (/Users/jason/Library/Developer/Toolchains/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-06-27-a.xctoolchain/usr/bin/swift-frontend+0x1017bdbdc)
#12 0x00000001045b8f04 (/Users/jason/Library/Developer/Toolchains/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-06-27-a.xctoolchain/usr/bin/swift-frontend+0x1017acf04)
#13 0x0000000104359fd8 (/Users/jason/Library/Developer/Toolchains/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-06-27-a.xctoolchain/usr/bin/swift-frontend+0x10154dfd8)
#14 0x00000001044f541c (/Users/jason/Library/Developer/Toolchains/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-06-27-a.xctoolchain/usr/bin/swift-frontend+0x1016e941c)
#15 0x00000001030a18f8 (/Users/jason/Library/Developer/Toolchains/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-06-27-a.xctoolchain/usr/bin/swift-frontend+0x1002958f8)
#16 0x000000010309e6a0 (/Users/jason/Library/Developer/Toolchains/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-06-27-a.xctoolchain/usr/bin/swift-frontend+0x1002926a0)
#17 0x000000010309de3c (/Users/jason/Library/Developer/Toolchains/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-06-27-a.xctoolchain/usr/bin/swift-frontend+0x100291e3c)
#18 0x0000000102e41d18 (/Users/jason/Library/Developer/Toolchains/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-06-27-a.xctoolchain/usr/bin/swift-frontend+0x100035d18)
#19 0x000000019fb15854
```

### Expected behavior

I expect the code to compile as it did with previous versions of Swift, or at least not crash the compiler.

### Environment

Apple Swift version 6.2-dev (LLVM ac66248b7c45109, Swift 92fd571d0786efe)
Target: arm64-apple-macosx26.0
Build config: +assertions

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by j-hui**
Not setting this correctly can lead to an assertion failure in the AST verifier:

    AbstractStorageDecl's setter access is out of sync with the access actually on the setter

Fixes #82637

rdar://154685710

### CODE REVIEW

**Comment by j-hui** [comment]
@swift-ci please test

File: test/Interop/Cxx/union/anonymous-union-const-member.swift [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+};
+
+//--- main.swift
+import CxxModule
+
+func fooer(_ f: inout Foo) {
+  let _ = f.variable
+  let _ = f.constant
+  f.variable = 42
+  // f.constant = 42 // FIXME: this should not work (but currently does)
```
Comment (j-hui) [inline test/Interop/Cxx/union/anonymous-union-const-member.swift:31]: NOTE: I address this in #83219

Comment (hnrklssn) [reply test/Interop/Cxx/union/anonymous-union-const-member.swift:31]: nit: there's no need to comment out the statement here. Feel free to ignore.

**Review by hnrklssn — APPROVED** [review]

**Review by nkcsgexi — APPROVED** [review]

**Comment by j-hui** [comment]
@swift-ci please test macos platform

**Comment by j-hui** [comment]
@swift-ci please test windows platform

**Review by Xazax-hun — APPROVED** [review]

**Comment by toffaletti** [comment]
Will this make it to 6.2 branch?
