### PR TITLE
[Sema] Fix issue 65330 Unhelpful error when missing contextually requ…

### LINKED ISSUE #65330: Unhelpful error when missing contextually required `as` bridging conversion to `AnyObject` in structural position
```swift
let _: AnyObject = "a" // OK, not much better but at least we get a custom error message and correct fix-it

let _: [AnyObject] = ["a"] // error: type of expression is ambiguous without more context
let _: [String: AnyObject] = ["a": "a"] // error: type of expression is ambiguous without more context
let _: (AnyObject, Void) = ("a", ()) // error: type of expression is ambiguous without more context
```

**Environment**
- Swift version 5.9-dev (LLVM 91080e65df791d6, Swift c1d5118c21da49a)

### PR DESCRIPTION
**Pull request by jreference**
…ired as bridging conversion to AnyObject in structural position. 

Minor formatting change in previous test case `generic-subscript.swift`

I'm not sure if these expressions should be considered to be contextual failures as well but it seemed reasonable. So this code change adds some custom logic in the contextual failure diagnosis for `TupleElement` locators when trying to diagnose `AnyObject` conversion failures.

Resolves #65330

### CODE REVIEW

File: lib/Sema/CSFix.cpp [hunk 1]
```diff
@@ -1934,7 +1934,7 @@ bool AllowNonClassTypeToConvertToAnyObject::diagnose(const Solution &solution,
                                                      bool asNote) const {
   auto *locator = getLocator();
 
-  if (locator->isForContextualType()) {
+  if (locator->isForContextualType() || locator->isForTupleElement()) {
```
Comment (xedin) [inline lib/Sema/CSFix.cpp:1937]: Instead of doing this let's just add a new `FailureDiagnostic` (something like `InvalidNonClassTypeToAnyObjectConversion`) and move `if (locator->isForContextualType()` and `if (locator->isLastElement<LocatorPathElt::ApplyArgToParam>())` to its `::diagnoseAsError()` method, add new custom cases for collections and a fallback to the generic `value of type 'String' expected to be instance of class or class-constrained type`. This way we don't have to add `isForTupleElement()` and assume that it would always have a contextual type.

**Review by xedin — CHANGES_REQUESTED** [review]
Thank you for the contribution!

File: lib/Sema/CSDiagnostics.h [hunk 2]
```diff
@@ -667,6 +667,22 @@ class AssignmentFailure final : public FailureDiagnostic {
   Optional<OverloadChoice> getMemberRef(ConstraintLocator *locator) const;
 };
 
+class NonClassTypeToAnyObjectConversionFailure : public FailureDiagnostic {
```
Comment (xedin) [inline lib/Sema/CSDiagnostics.h:670]: Let's make this `final` and inherit from `ContextualFailure` this was you can just pass lhs, rhs to the constructor and it would resolve them properly (the reason why it's important is that fix could have type variables in the types which needs to be resolved based on the deduced solution), and you can use `ContextualMismatch::diagnoseAs{Error, Note}();` it your diagnose methods.

File: lib/Sema/CSDiagnostics.h [hunk 3]
```diff
@@ -667,6 +667,22 @@ class AssignmentFailure final : public FailureDiagnostic {
...
+  ConstraintLocator *RawLocator;
+
+public:
+  NonClassTypeToAnyObjectConversionFailure(
+      const Solution &solution, Type lhs, Type rhs, ConstraintLocator *locator,
+      FixBehavior fixBehavior = FixBehavior::Error)
+      : FailureDiagnostic(solution, locator, fixBehavior), RawFromType(lhs),
+        RawToType(rhs), RawLocator(locator){};
+
+  virtual bool diagnoseAsError() override;
```
Comment (xedin) [inline lib/Sema/CSDiagnostics.h:681]: No need to mark these methods `virtual`.

File: lib/Sema/CSDiagnostics.h [hunk 4]
```diff
@@ -667,6 +667,22 @@ class AssignmentFailure final : public FailureDiagnostic {
   Optional<OverloadChoice> getMemberRef(ConstraintLocator *locator) const;
 };
 
+class NonClassTypeToAnyObjectConversionFailure : public FailureDiagnostic {
+  Type RawFromType, RawToType;
+  ConstraintLocator *RawLocator;
```
Comment (xedin) [inline lib/Sema/CSDiagnostics.h:672]: `FailureDiagnostic` already saves the locator it got passed in so you don't need to safe it this way.

File: lib/Sema/CSDiagnostics.cpp [hunk 5]
```diff
@@ -3528,6 +3527,66 @@ ContextualFailure::getDiagnosticFor(ContextualTypePurpose context,
...
+  Optional<Diag<Type, Type>> diagnosis;
+  bool forProtocol = RawToType->isConstraintType();
+  auto originalAnchor = getLocator()->getAnchor();
+
+  if (isExpr<ArrayExpr>(originalAnchor)) {
+    diagnosis = forProtocol ? diag::cannot_convert_array_element_protocol
+                            : diag::cannot_convert_array_element;
+  } else if (isExpr<DictionaryExpr>(originalAnchor)) {
+    auto lastElem =
+        RawLocator->getPath().back().castTo<LocatorPathElt::TupleElement>();
```
Comment (xedin) [inline lib/Sema/CSDiagnostics.cpp:3552]: Nit: Use `getLastElementAs<LocatorPathElt::TupleElement>`. We also have `isLastElement` and `castLastElementTo` .

File: lib/Sema/CSDiagnostics.cpp [hunk 6]
```diff
@@ -3528,6 +3527,66 @@ ContextualFailure::getDiagnosticFor(ContextualTypePurpose context,
...
+    return failure.diagnoseAsError();
+  }
+
+  if (RawLocator->isLastElement<LocatorPathElt::ApplyArgToParam>()) {
+    ArgumentMismatchFailure failure(getSolution(), RawFromType, RawToType,
+                                    RawLocator);
+    return failure.diagnoseAsError();
+  }
+
+  Optional<Diag<Type, Type>> diagnosis;
```
Comment (xedin) [inline lib/Sema/CSDiagnostics.cpp:3543]: Nit: we call this simply `diagnostic`

File: lib/Sema/CSDiagnostics.cpp [hunk 7]
```diff
@@ -3528,6 +3527,66 @@ ContextualFailure::getDiagnosticFor(ContextualTypePurpose context,
...
+  bool forProtocol = RawToType->isConstraintType();
+  auto originalAnchor = getLocator()->getAnchor();
```
Comment (xedin) [inline lib/Sema/CSDiagnostics.cpp:3545]: I'm assuming that you was a "raw" anchor, if so then `FailureDiagnostic` already has a facility for that - `getRawAnchor()`.

**Review by xedin — CHANGES_REQUESTED** [review]
Looks much better now! I think after my inline comments are addressed it would be ready to go.

File: lib/Sema/CSDiagnostics.h [hunk 8]
```diff
@@ -804,6 +804,22 @@ class ContextualFailure : public FailureDiagnostic {
...
+class NonClassTypeToAnyObjectConversionFailure final
+    : public ContextualFailure {
+  Type RawFromType, RawToType;
+
+public:
+  NonClassTypeToAnyObjectConversionFailure(
+      const Solution &solution, Type lhs, Type rhs, ConstraintLocator *locator,
+      FixBehavior fixBehavior = FixBehavior::Error)
+      : ContextualFailure(solution, lhs, rhs, locator, fixBehavior),
+        RawFromType(lhs), RawToType(rhs){};
```
Comment (xedin) [inline lib/Sema/CSDiagnostics.h:816]: There is no need for `;` here too. Could you please run `git-clang-format` on your changes (here is how to do it - https://github.com/apple/swift/blob/main/docs/HowToGuides/FAQ.md#how-do-i-format-my-changes).

File: lib/Sema/CSDiagnostics.h [hunk 9]
```diff
@@ -804,6 +804,22 @@ class ContextualFailure : public FailureDiagnostic {
...
 
+class NonClassTypeToAnyObjectConversionFailure final
+    : public ContextualFailure {
+  Type RawFromType, RawToType;
+
+public:
+  NonClassTypeToAnyObjectConversionFailure(
+      const Solution &solution, Type lhs, Type rhs, ConstraintLocator *locator,
+      FixBehavior fixBehavior = FixBehavior::Error)
+      : ContextualFailure(solution, lhs, rhs, locator, fixBehavior),
```
Comment (xedin) [inline lib/Sema/CSDiagnostics.h:815]: This fix behavior is always FixBehavior:Error so I don't think we need to provide that parameter/argument at all here.

**Review by xedin — CHANGES_REQUESTED** [review]

**Comment by xedin** [comment]
Regarding starter bugs I can definitely find you a few, are you interesting in the same general area?

File: lib/Sema/CSDiagnostics.h [hunk 10]
```diff
@@ -804,6 +804,22 @@ class ContextualFailure : public FailureDiagnostic {
   }
 };
 
+class NonClassTypeToAnyObjectConversionFailure final
+    : public ContextualFailure {
+  Type RawFromType, RawToType;
```
[the remark this answers is not in the document]
Comment (xedin) [reply lib/Sema/CSDiagnostics.h]: It's actually better to pass getFromType() and getToType() to `ArgumentMismatchFailure` because it would save at least one simplification :)

File: lib/Sema/CSDiagnostics.h (hunk 8 above)
Comment (xedin) [reply lib/Sema/CSDiagnostics.h]: Oh well, at least we caught it.

File: lib/Sema/CSDiagnostics.h (hunk 10 above)
[the remark this answers is not in the document]
Comment (xedin) [reply lib/Sema/CSDiagnostics.h]: Diagnostics shouldn’t use raw types in general so we are good.

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
Feel free to merge yourself next time if the PR is approved and tests are green! I will leave some more starter bug issues in here on Monday.

**Comment by xedin** [comment]
- Looks like there is some work still that needs to be done for https://github.com/apple/swift/issues/53378 

Example:
```swift
protocol Integer {
}
func foo() -> some Integer {
  let x = 0
  x
}
```

Doesn't produce a fix-it we'd expect.

- https://github.com/apple/swift/issues/57437
- https://github.com/apple/swift/issues/61039
- https://github.com/apple/swift/issues/50745
