### PR TITLE
[Sema]: ban @isolated(any) conversions to synchronous function types

### LINKED ISSUE #80823: @isolated(any) closure can be assigned to non isolated closure property
### Description

The compiler allows to set an `@isolated(any)` closure to a property that is not isolated itself. Shouldn't this throw a compilation error?

```swift
struct Example {
  var getString: @Sendable () -> String

  init(getString: @isolated(any) @escaping @Sendable () -> String) {
    self.getString = getString
  }
}
```

### Reproduction

```swift
struct Example {
  var getString: @Sendable () -> String

  init(getString: @isolated(any) @escaping @Sendable () -> String) {
    self.getString = getString
  }
}

await Task.detached {
  let e = Example { @MainActor in
    MainActor.assertIsolated() // This crashes
    return "Hello, world!"
  }
  print(e.getString())
}.value
```

### Expected behavior

The compiler should not allow `self.getString = getString`, unless `var getString: @Sendable () -> String` is changed to `var getString: @isolated(any) @Sendable () -> String`.

### Environment

swift-driver version: 1.120.5 Apple Swift version 6.1 (swiftlang-6.1.0.110.21 clang-1700.0.13.3)
Target: arm64-apple-macosx15.0

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jamieQ**
currently, function conversions from `@isolated(any)` functions to synchronous, non-`@isolated(any)` functions are permitted, despite this being [expressly stated](https://github.com/swiftlang/swift-evolution/blob/d527bd1b0a5e467db4d450a5c7483835f6a3cdf5/proposals/0431-isolated-any-functions.md#conversions) as an invalid conversion in SE-0431. this change updates the type checking machinery to diagnose such conversions (currently as a warning that will be an error in a future language mode).

resolves https://github.com/swiftlang/swift/issues/80823

relevant forum posts: [one](https://forums.swift.org/t/why-can-i-assign-isolated-any-closure-to-non-isolated-closure/79257) & [two](https://forums.swift.org/t/a-few-isolated-any-function-conversion-questions/79279)

### CODE REVIEW

**Comment by jamieQ** [comment]
@swift-ci please smoke test macos

File: lib/Sema/CSSimplify.cpp [hunk 1]
```diff
@@ -2985,6 +2985,10 @@ ConstraintSystem::matchFunctionIsolations(FunctionType *func1,
     case FunctionTypeIsolation::Kind::Erased:
       return matchIfConversion();
 
+      // TODO: should this be handled here?
```
Comment (slavapestov) [inline lib/Sema/CSSimplify.cpp:2988]: Rejecting invalid conversions in the solver is generally better. For example if you have two overloads and one of the choices involves the invalid conversion, diagnosing the conversion after the solution is applied means the code will fail to type check with an ambiguity.

Comment (jamieQ) [reply lib/Sema/CSSimplify.cpp:2988]: thanks! and just to clarify as i'm not very familiar with this area of the code – this file is part of the (constraint?) 'solver', correct?

i assume i should remove the logic from the actor isolation checker in favor of this then, since presumably there's no reason to duplicate the check in both places – or is there?

Comment (jamieQ) [reply lib/Sema/CSSimplify.cpp:2988]: although... the comment up above does give me some pause (i don't fully grasp what it's trying to communicate):

```
    // Erasing global-actor isolation to non-isolation can admit data
    // races; such violations are diagnosed by the actor isolation checker.
    // We deliberately do not allow actor isolation violations to influence
    // overload resolution to preserve the property that an expression can
    // be re-checked against a different isolation context for isolation
    // violations.
    //
    // This also applies to @isolated(any) because we want to be able to
    // decide that we contextually isolated to the function's dynamic
    // isolation.
```

**Comment by jamieQ** [comment]
@swift-ci please smoke test

File: lib/Sema/CSSimplify.cpp [hunk 2]
```diff
@@ -2943,6 +2943,11 @@ ConstraintSystem::matchFunctionIsolations(FunctionType *func1,
                                           ConstraintLocatorBuilder locator) {
   auto isolation1 = func1->getIsolation(), isolation2 = func2->getIsolation();
 
+  // An @isolated(any) function cannot be converted to a non-@isolated(any)
+  // synchronous function regardless of whether or not it is itself async.
+  if (isolation1.isErased() && !isolation2.isErased() && !func2->isAsync())
```
Comment (jamieQ) [inline lib/Sema/CSSimplify.cpp:2948]: the early exit here presumably means some of the 'score increase' logic that used to occur no longer will. does that seem generally okay?

**Comment by jamieQ** [comment]
note: the current proposal for `Observed` is currently relying on the existing behavior (see [here](https://github.com/swiftlang/swift/pull/79817/files#diff-5331c04d92a773232e57d5cb29954ab33d972b63aee0a1b7527d1a487c1c588fR200-R203)) to be able to synchronously invoke an `@isolated(any)` function

**Comment by jamieQ** [comment]
@swift-ci please smoke test linux

File: lib/Sema/CSSimplify.cpp (hunk 1 above)
Comment (hborla) [reply lib/Sema/CSSimplify.cpp]: > Rejecting invalid conversions in the solver is generally better

I agree as a general principle, but we can't do that in for invalid conversions due to actor isolation, because actor isolation of context is determined after constraint solving, and that's the isolation of non-`Sendable` function types. Maybe this particular invalid conversion could be diagnosed in the constraint system because `@isolated(any)` is always part of the type, but I'm not sure that it's better to do some isolation conversion checking in the solver and the rest in the actor isolation checker.

Comment (hborla) [reply lib/Sema/CSSimplify.cpp]: And yes, like @jamieQ points out, because many invalid conversions due to isolation cannot be prevented in the constraint system, we do not allow isolation to influence overload resolution.

Comment (xedin) [reply lib/Sema/CSSimplify.cpp]: I concur with @hborla here, isolation checking is better suited here because it runs at the point where all of the moving pieces are determined and it would be easier to deal with downgrades.  @jamieQ re: source compatibility I think we aught to downgrade this to a warning until future swift version unless accepting the code with this conversion is completely undesirable.

Comment (jamieQ) [reply lib/Sema/CSSimplify.cpp]: thanks all – per my understanding i should:
- move the diagnostic back into the actor isolation checker (removing it from constraint solving)
- downgrade it to a warning for source compatibility reasons

assuming that's right, i'll move this back to draft status until i can resolve those things.

Comment (xedin) [reply lib/Sema/CSSimplify.cpp]: Yep, I think that's right.

**Comment by jamieQ** [comment]
@swift-ci please smoke test

**Comment by jamieQ** [comment]
@swift-ci please smoke test windows

**Review by hborla — APPROVED** [review]
Thank you!

**Comment by hborla** [comment]
@jamieQ Would you mind cherry picking this fix to `release/6.2`?

**Comment by jamieQ** [comment]
> Would you mind cherry picking this fix to `release/6.2`?

@hborla yep, can do
