### PR TITLE
[Sema] 61733 error message improvement

### LINKED ISSUE #61733: Improve the error message for passing `(any P)?` to `(some P)?`
If you try to pass a value of type `(any P)?` to an argument of type `(some P)?`, the compiler tells you that `any P` cannot conform to `P`, which is confusing and not actionable. With [SE-0375](https://github.com/apple/swift-evolution/blob/main/proposals/0375-opening-existential-optional.md), existential opening/unboxing is supported with optionals, but only if the argument is not an optional because it's possible that the `(any P)?` is `nil` (and thus does not have a dynamic type to bind to `some P`). With SE-0375, the fix is to unwrap the optional or provide a default value. So, the error message should tell you that!

```swift
protocol P {}

struct S: P {}

func takesOptionalP(_: (some P)?) {}

func passOptional(value: (any P)?) {
  takesOptionalP(value) // error: type 'any P' cannot conform to 'P'

  takesOptionalP(value ?? S()) // okay under SE-0375
  takesOptionalP(value!) // okay under SE-0375
}
```

The constraint system currently applies the `MissingConformance` fix when solving for the `takesOptionalP(value)` expression. Instead, it should identify that the wrapped type of the argument matches the parameter type, and apply the `ForceOptional` fix.

### PR DESCRIPTION
**Pull request by aeu**
### Supercedes
[PR86370](https://github.com/swiftlang/swift/pull/86370)
Replaces previous PR on this issue.  Based on reviewer feedback from @xedin the original approach was not correct, so there was no point in preserving any of the commit history.

### Resolves
[Issue 61733](https://github.com/swiftlang/swift/issues/61733)

### Problem Statement
If you try to pass a value of type (any P)? to an argument of type (some P)?, the compiler tells you that any P cannot conform to P, which is confusing and not actionable. With [SE-0375](https://github.com/apple/swift-evolution/blob/main/proposals/0375-opening-existential-optional.md), existential opening/unboxing is supported with optionals, but only if the argument is not an optional because it's possible that the (any P)? is nil (and thus does not have a dynamic type to bind to some P). With [SE-0375](https://swiftlang.github.io/swift-evolution/#?proposal=SE-0375), the fix is to unwrap the optional or provide a default value. So, the error message should tell you that!

#### Reproducer code

````
protocol P {}

struct S: P {}

func takesOptionalP(_: (some P)?) {}

func passOptional(value: (any P)?) {
  takesOptionalP(value) // error: type 'any P' cannot conform to 'P'

  takesOptionalP(value ?? S()) // okay under SE-0375
  takesOptionalP(value!) // okay under SE-0375
}
````
The constraint system currently applies the MissingConformance fix when solving for the takesOptionalP(value) expression. Instead, it should identify that the wrapped type of the argument matches the parameter type, and apply the ForceOptional fix.

### Cause
During constraint solving for takesOptionalP(value), the constraint system records a viable ForceOptional fix at the call site, but during salvage it still applies MissingConformance, producing a misleading protocol conformance diagnostic.

### Changes
+ Adds a check in matchCallArguments() to detect the case where an optional existential is being passed to a generic parameter. If the existential’s layout is valid and non-class-bound, we now record a ForceOptional fix.
+ A regression test was added under test/Constraints/issue-61733.swift.
+ An existing test case was updated (as the output changed and it would not have worked)

## Before
````
$ cat 61733.swift 
protocol P {}
struct S: P {}

func takesOptionalP(_: (some P)?) {}

// Test Case 01
func passOptional(foo: (any P)?) {
    takesOptionalP(foo)
}

$ swiftc 61733.swift 
61733.swift:8:5: error: type 'any P' cannot conform to 'P'
 2 | struct S: P {}
 3 | 
 4 | func takesOptionalP(_: (some P)?) {}
   |      `- note: required by global function 'takesOptionalP' where 'some P' = 'any P'
 5 | 
 6 | // Test Case 01
 7 | func passOptional(foo: (any P)?) {
 8 |     takesOptionalP(foo)
   |     |- error: type 'any P' cannot conform to 'P'
   |     `- note: only concrete types such as structs, enums and classes can conform to protocols
 9 | }
10 | 
````

## After
````
$ cat 61733.swift 
protocol P {}
struct S: P {}

func takesOptionalP(_: (some P)?) {}

// Test Case 01
func passOptional(foo: (any P)?) {
    takesOptionalP(foo)
}

$ swiftc 61733.swift 
61733.swift:8:20: error: value of optional type '(any P)?' must be unwrapped to a value of type 'any P'
 6 | // Test Case 01
 7 | func passOptional(foo: (any P)?) {
 8 |     takesOptionalP(foo)
   |                    |- error: value of optional type '(any P)?' must be unwrapped to a value of type 'any P'
   |                    |- note: coalesce using '??' to provide a default when the optional value contains 'nil'
   |                    `- note: force-unwrap using '!' to abort execution if the optional value contains 'nil'
 9 | }
10 | 
````

### CODE REVIEW

**Comment by xedin** [comment]
Thank you, I will take a look on Monday!

File: lib/Sema/CSSimplify.cpp [hunk 1]
```diff
@@ -1819,28 +1851,68 @@ static ConstraintSystem::TypeMatchResult matchCallArguments(
...
-      if (auto typeVarAndBindingTy = shouldOpenExistentialCallArgument(
-              callee, paramIdx, paramTy, argTy, argExpr, cs)) {
-        // My kingdom for a decent "if let" in C++.
+      auto shouldOpenExistentialArgument =
+      [&]() -> std::optional<std::pair<TypeVariableType *, Type>> {
+
+        Type argTypeForOpening = argTy;
+
+        auto *module = cs.DC ? cs.DC->getParentModule() : nullptr;
+        if (!module || isLanguageRuntimeModule(module)) {
```
Comment (slavapestov) [inline lib/Sema/CSSimplify.cpp]: I don't think the behavior of the type checker should be conditionalized like this. Were you seeing the stdlib fail to build with this change, or does it produce new warnings?

File: lib/Sema/CSSimplify.cpp [hunk 2]
```diff
@@ -1819,28 +1851,68 @@ static ConstraintSystem::TypeMatchResult matchCallArguments(
...
+        //    and arg is Optional whose object is an existential any ... with protocols
+        //    and not class-constrained.
+        if (!cs.shouldAttemptFixes())
+          return std::nullopt;
+
+        if (Type optObject = argTy->getOptionalObjectType()) {
+          Type unwrapped = optObject->lookThroughAllOptionalTypes();
+          if (unwrapped->isAnyExistentialType()) {
+            auto layout = unwrapped->getExistentialLayout();
+            if (!layout.getProtocols().empty() && !layout.requiresClass()) {
```
Comment (slavapestov) [inline lib/Sema/CSSimplify.cpp]: getProtocols().empty() will almost always be false, because any copyable existential includes at least one protocol. What was your intent behind this if statement?

File: lib/Sema/CSSimplify.cpp [hunk 3]
```diff
@@ -1819,28 +1851,68 @@ static ConstraintSystem::TypeMatchResult matchCallArguments(
         }
       }
 
-      // If the argument is an existential type and the parameter is generic,
-      // consider opening the existential type.
-      if (auto typeVarAndBindingTy = shouldOpenExistentialCallArgument(
-              callee, paramIdx, paramTy, argTy, argExpr, cs)) {
-        // My kingdom for a decent "if let" in C++.
+      auto shouldOpenExistentialArgument =
+      [&]() -> std::optional<std::pair<TypeVariableType *, Type>> {
```
Comment (slavapestov) [inline lib/Sema/CSSimplify.cpp]: Indentation

File: lib/Sema/CSSimplify.cpp [hunk 4]
```diff
@@ -1819,28 +1851,68 @@ static ConstraintSystem::TypeMatchResult matchCallArguments(
...
+
+      if (auto typeVarAndBindingTy = shouldOpenExistentialArgument()) {
         TypeVariableType *typeVar;
         Type bindingTy;
         std::tie(typeVar, bindingTy) = *typeVarAndBindingTy;
 
-        ExistentialArchetypeType *openedArchetype;
+        ExistentialArchetypeType *openedArchetype = nullptr;
+
+        argTy = argTy.transformRec([&](TypeBase *t)-> std::optional<Type> {
```
Comment (slavapestov) [inline lib/Sema/CSSimplify.cpp]: This looks like a pure formatting change and deletion of a comment, maybe it's not necessary?

File: lib/Sema/CSSimplify.cpp (hunk 1 above)
Comment (aeu) [reply lib/Sema/CSSimplify.cpp]: That was exactly it, build failures.

File: lib/Sema/CSSimplify.cpp [hunk 5]
```diff
@@ -1819,28 +1851,68 @@ static ConstraintSystem::TypeMatchResult matchCallArguments(
...
-      // consider opening the existential type.
-      if (auto typeVarAndBindingTy = shouldOpenExistentialCallArgument(
-              callee, paramIdx, paramTy, argTy, argExpr, cs)) {
-        // My kingdom for a decent "if let" in C++.
+      auto shouldOpenExistentialArgument =
+      [&]() -> std::optional<std::pair<TypeVariableType *, Type>> {
+
+        Type argTypeForOpening = argTy;
+
+        auto *module = cs.DC ? cs.DC->getParentModule() : nullptr;
```
Comment (slavapestov) [inline lib/Sema/CSSimplify.cpp]: cs.DC is never null because we use the DeclContext for name lookups and so on.

File: lib/Sema/CSSimplify.cpp (hunk 2 above)
Comment (aeu) [reply lib/Sema/CSSimplify.cpp]: You're right, it's pointless as it will never be empty.  I'll remove it.

File: lib/Sema/CSSimplify.cpp (hunk 4 above)
Comment (aeu) [reply lib/Sema/CSSimplify.cpp]: openedArchetype is only conditionally assigned inside the lambda, so I initialized it to avoid pushing an uninitialized value into openedExistentials.

File: lib/Sema/CSSimplify.cpp (hunk 5 above)
Comment (aeu) [reply lib/Sema/CSSimplify.cpp]: You're right, its a pointless safety check.  I'll remove it.

File: lib/Sema/CSSimplify.cpp (hunk 3 above)
Comment (aeu) [reply lib/Sema/CSSimplify.cpp]: Fixed

File: lib/Sema/CSSimplify.cpp (hunk 1 above)
Comment (xedin) [reply lib/Sema/CSSimplify.cpp]: That's what has to be investigated since it shouldn't matter where the type comes from or in what module type-checking happens in this case.

Comment (aeu) [reply lib/Sema/CSSimplify.cpp]: I removed the runtime module bypass and got a clean build.  Looks like the failures were caused by an earlier version of the patch.  Conditional removed and pushed.

File: lib/Sema/CSSimplify.cpp (hunk 4 above)
Comment (aeu) [reply lib/Sema/CSSimplify.cpp]: I put the comment back in as well as re-inserted a space that was triggering a git diff and fixed the indentation

File: lib/Sema/CSSimplify.cpp [hunk 6]
```diff
@@ -1819,28 +1819,69 @@ static ConstraintSystem::TypeMatchResult matchCallArguments(
...
-      if (auto typeVarAndBindingTy = shouldOpenExistentialCallArgument(
-              callee, paramIdx, paramTy, argTy, argExpr, cs)) {
-        // My kingdom for a decent "if let" in C++.
+      auto shouldOpenExistentialArgument =
+        [&]() -> std::optional<std::pair<TypeVariableType *, Type>> {
+
+        Type argTypeForOpening = argTy;
+
+        auto *module = cs.DC->getParentModule();
+        if (!module) {
```
Comment (xedin) [inline lib/Sema/CSSimplify.cpp]: Why is this necessary?

Comment (aeu) [reply lib/Sema/CSSimplify.cpp]: It's not necessary anymore. That was added earlier when I was conditionally bypassing behavior for the standard library module, which is no longer the case.  Removed.

**Comment by aeu** [comment]
HI @xedin & @slavapestov, following up on this to see if you have any additional feedback for me to address.  Thank you.

**Review by xedin — CHANGES_REQUESTED** [review]
Looks reasonable! I'm requesting changes because I'd like to ask you to run clang-format on the changes before we can merge this. Please re-request the review once that's done and we can run the tests and land it if everything goes well.

**Comment by aeu** [comment]
@xedin - clang format done.

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
This change regresses test/PlaygroundTransform/existential.swift

**Comment by aeu** [comment]
@xedin - yes, working on a fix.  Will ping you when I figure it out.

**Comment by aeu** [comment]
ForceOptional recovery was being applied to any Optional<existential> argument, which then triggered when the playground transform passed Any? to a non-optional generic parameter in its logging infrastructure, causing a regression in PlaygroundTransform/existential.swift.

Updated logic to only match cases where the parameter type is also optional, which matches the intended (any P)? → (some P)? scenario and prevents the solver from introducing an invalid unwrap diagnostic.

@xedin - update posted.  This passes on my environment.  I ran the formatter already as well.

**Comment by xedin** [comment]
Hm, this means that `Any` is successfully opened by `shouldOpenExistentialCallArgument`... @AnthonyLatsis is that actually supposed to happen?

**Comment by AnthonyLatsis** [comment]
If `ImplicitOpenExistentials` is enabled and the generic parameter is unconstrained, then yes, I believe so. Though, admittedly, the [proposal](https://github.com/swiftlang/swift-evolution/blob/ca37659831799cfa06622fae600178509874976d/proposals/0352-implicit-open-existentials.md#avoid-opening-when-the-existential-type-satisfies-requirements-in-swift-5) is not *crystal clear* on this matter. Anyhow:

> ```swift
> func acceptsBox<T>(_ value: T) -> Any { [value] }
> 
> func passBox(p: any P) {
>   let result = acceptsBox(p) // currently infers 'T' to be 'any P', returns [any P]
>       // unrestricted existential opening would infer 'T' to be the underlying type of 'p', returns [T]
> }
> ```
> [...] Therefore, in Swift 5, this proposal prevents opening of existential values when the existential types themselves would satisfy the conformance requirements of the corresponding generic parameter [...] Swift 6 will be a major language version change that can incorporate some semantics- and source-breaking changes. In Swift 6, the suppression mechanism described in this section will not apply, so the `passBox` example above would open the value of `p` and bind `T` to that opened existential type  [...]
> ```swift
> func takeError<E: Error>(_ error: E) { }
> 
> func passError(error: any Error) {
>   takeError(error)  // okay without opening: 'E' binds to 'any Error' because 'any Error' conforms to 'Error'
> }
> ```
> This proposal preserves the semantics of the call above by not opening the existential argument in cases where the existential type satisfies the corresponding generic parameter's conformance requirements

I doubt that last rule is meant to apply to `Any`, or else it would evidently contradict the previous rule.

**Comment by xedin** [comment]
@aeu I'd say let's ignore `Any` instead of trying to check whether a parameter is optional or not.

**Comment by aeu** [comment]
Hi @xedin - I incorporated the requested change about ignoring `Any`.   Let me know if this is what you had in mind.

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test source compatibility

**Comment by xedin** [comment]
@swift-ci please test source compatibility debug

**Comment by xedin** [comment]
@swift-ci please test source compatibility debug

**Comment by xedin** [comment]
Looks like there is another regression from this in CI.

**Comment by aeu** [comment]
```15:33:23  /home/build-user/swift-testing/Sources/Testing/ExitTests/ExitTest.CapturedValue.swift:99:18: error: value of optional type '(any Codable & Sendable)?' (aka 'Optional<any Decodable & Encodable & Sendable>') must be unwrapped to a value of type 'any Codable & Sendable' (aka 'any Decodable & Encodable & Sendable')
15:33:23   97 |           assert(newValue is U, "Attempted to set a captured value to an instance of '\(String(describingForTest: T.self))', but an instance of '\(String(describingForTest: U.self))' was expected.")
15:33:23   98 |         }
15:33:23   99 |         validate(newValue, is: type)
15:33:23      |                  |- error: value of optional type '(any Codable & Sendable)?' (aka 'Optional<any Decodable & Encodable & Sendable>') must be unwrapped to a value of type 'any Codable & Sendable' (aka 'any Decodable & Encodable & Sendable')
15:33:23      |                  |- note: coalesce using '??' to provide a default when the optional value contains 'nil'
15:33:23      |                  `- note: force-unwrap using '!' to abort execution if the optional value contains 'nil'
15:33:23  100 | 
15:33:23  101 |         if let newValue {
15:33:23  ninja: build stopped: subcommand failed.
15:33:23  ERROR: command `['env', '/home/build-user/build/cmake-linux-x86_64/bin/cmake', '--build', '/home/build-user/build/buildbot_linux/swifttesting-linux-x86_64', '--config', 'Release', '--', '-j36']` terminated with a non-zero exit status 1, aborting
```

This is the test in question.

[ExitTest.CapturedValue.swift
](https://github.com/swiftlang/swift-testing/blob/main/Sources/Testing/ExitTests/ExitTest.CapturedValue.swift)

```
#if !SWT_NO_EXIT_TESTS
        let type = typeOfWrappedValue

        func validate<T, U>(_ newValue: T, is expectedType: U.Type) {
          assert(newValue is U, "Attempted to set a captured value to an instance of '\(String(describingForTest: T.self))', but an instance of '\(String(describingForTest: U.self))' was expected.")
        }
        validate(newValue, is: type)

        if let newValue {
          _kind = .wrappedValue(newValue)
        } else {
          _kind = .typeOnly(type)
        }
#else
```

Hi @xedin - looking at this, I get the feeling that I need to put back the optional parameter guard.  I'll give that a shot and ping you when I have something to look at.

**Comment by xedin** [comment]
Well, the issue is that we don't always know whether parameter would be optional early on because the type could be inferred from other parameters or a result.

**Comment by aeu** [comment]
Hi @xedin - this should take care of that failed test.  I wasn’t able to reproduce the CI environment locally, could you please kick off CI when you get a chance?

**Comment by hnrklssn** [comment]
@swift-ci please smoke test

**Comment by xedin** [comment]
Sorry I'm still thinking about this. @aeu could you please rebase meanwhile?

**Comment by aeu** [comment]
@xedin - rebase done.

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Comment by aeu** [comment]
@xedin - looks like the Windows test failed.  I can't tell what was the cause though, the more information link gives me a 404.

**Comment by xedin** [comment]
@swift-ci please test Windows platform

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
Sorry it took so long and thank you for working through this, @aeu!

**Comment by aeu** [comment]
No worries @xedin, was a great learning experience.
