### PR TITLE
[SymbolGraphGen] allow SourceKit to print declarations for private stdlib symbols

### LINKED ISSUE #62457: Symbolgraph crashes with Assertion failed: (NumFragments), function ~DeclarationFragmentPrinter, file DeclarationFragmentPrinter.h, line 143.
The following new test case causes an assertion failure in SymboGraph

```swift
// RUN: %sourcekitd-test -req=cursor -req-opts=retrieve_symbol_graph=1 -pos=8:13 %s -- %s

struct AnyError: Swift.Error {
  let error: Swift.Error
}

func test(lhs: AnyError) {
  lhs.error._code
}
```

#### Stack trace

```
Thread 5 Crashed::  Dispatch queue: sourcekit.swift.ConsumeAST
0   libsystem_kernel.dylib        	    0x7ff810dc130e __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff810df8f7b pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff810d42d3f __abort + 139
3   libsystem_c.dylib             	    0x7ff810d42cb4 abort + 138
4   libsystem_c.dylib             	    0x7ff810d41fbe __assert_rtn + 314
5   libsourcekitdInProc.dylib     	       0x1133b5ad3 swift::symbolgraphgen::DeclarationFragmentPrinter::~DeclarationFragmentPrinter() (.cold.1) + 35
6   libsourcekitdInProc.dylib     	       0x1133b204f swift::symbolgraphgen::DeclarationFragmentPrinter::~DeclarationFragmentPrinter() + 111
7   libsourcekitdInProc.dylib     	       0x1133a03ae swift::symbolgraphgen::Symbol::getFragmentInfo(llvm::SmallVectorImpl<swift::symbolgraphgen::FragmentInfo>&) const + 350
8   libsourcekitdInProc.dylib     	       0x1133b6bbc swift::symbolgraphgen::printSymbolGraphForDecl(swift::ValueDecl const*, swift::Type, bool, swift::symbolgraphgen::SymbolGraphOptions const&, llvm::raw_ostream&, llvm::SmallVectorImpl<swift::symbolgraphgen::PathComponent>&, llvm::SmallVectorImpl<swift::symbolgraphgen::FragmentInfo>&) + 684
9   libsourcekitdInProc.dylib     	       0x112496a89 fillSymbolInfo(SourceKit::CursorSymbolInfo&, DeclInfo const&, swift::SourceLoc, bool, SourceKit::SwiftLangSupport&, swift::CompilerInvocation const&, llvm::ArrayRef<llvm::IntrusiveRefCntPtr<SourceKit::ImmutableTextSnapshot> >, llvm::BumpPtrAllocatorImpl<llvm::MallocAllocator, 4096ul, 4096ul, 128ul>&) + 2425
10  libsourcekitdInProc.dylib     	       0x11248edb1 passCursorInfoForDecl(swift::ide::ResolvedValueRefCursorInfo const&, bool, bool, llvm::ArrayRef<SourceKit::RefactoringInfo>, SourceKit::SwiftLangSupport&, swift::CompilerInvocation const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, llvm::ArrayRef<llvm::IntrusiveRefCntPtr<SourceKit::ImmutableTextSnapshot> >, std::__1::function<void (SourceKit::RequestResult<SourceKit::CursorInfoData> const&)>) + 449
11  libsourcekitdInProc.dylib     	       0x11248dc2f resolveCursor(SourceKit::SwiftLangSupport&, llvm::StringRef, unsigned int, unsigned int, bool, bool, llvm::IntrusiveRefCntPtr<SourceKit::SwiftInvocation>, bool, bool, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, void const*, std::__1::function<void (SourceKit::RequestResult<SourceKit::CursorInfoData> const&)>)::CursorInfoConsumer::handlePrimaryAST(llvm::IntrusiveRefCntPtr<SourceKit::ASTUnit>) + 2287
12  libsourcekitdInProc.dylib     	       0x11248551f void SourceKit::WorkQueue::DispatchData::callAndDelete<SourceKit::ASTUnit::Implementation::consumeAsync(std::__1::shared_ptr<SourceKit::SwiftASTConsumer>, llvm::IntrusiveRefCntPtr<SourceKit::ASTUnit>)::$_0>(void*) + 95
13  libdispatch.dylib             	    0x7ff810c79a44 _dispatch_client_callout + 8
14  libdispatch.dylib             	    0x7ff810c7fac4 _dispatch_lane_serial_drain + 694
15  libdispatch.dylib             	    0x7ff810c805b4 _dispatch_lane_invoke + 366
16  libdispatch.dylib             	    0x7ff810c8aad7 _dispatch_workloop_worker_thread + 762
17  libsystem_pthread.dylib       	    0x7ff810df5ce3 _pthread_wqthread + 326
18  libsystem_pthread.dylib       	    0x7ff810df4c67 start_wqthread + 15
```

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
Resolves rdar://103112656
Resolves #62457

When SourceKit gets a cursor symbol graph for an internal stdlib symbol, the declaration fragment printer hits an assertion because it hasn't actually printed anything. This is because the PrintOptions used by the printer sets `SkipPrivateStdlibDecls` and `SkipUnderscoredStdlibProtocols`. This is useful when generating a whole-module symbol graph, but is causing problems for SourceKit. This PR adds an option to SymbolGraphOptions that turns those options off for SourceKit, so that these symbols can get a symbol graph correctly generated.

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

File: test/SourceKit/CursorInfo/issue-62457-symbol-graph-crash.swift [hunk 1]
```diff
@@ -0,0 +1,9 @@
+// RUN: %sourcekitd-test -req=cursor -req-opts=retrieve_symbol_graph=1 -pos=8:13 %s -- %s
```
Comment (ahoppen) [inline test/SourceKit/CursorInfo/issue-62457-symbol-graph-crash.swift:1]: Would it be useful to check the response here as well?

Also, not required, but I find it easier to follow if the `RUN` line is right above the place where you invoke `sourcekitd` test and then uses `-pos=%(line + 1):13`. That also makes it easier to edit the file because adding new lines above the cursor info position doesn’t shift everything around.

**Review by ahoppen — APPROVED** [review]

File: test/SourceKit/CursorInfo/issue-62457-symbol-graph-crash.swift (hunk 1 above)
Comment (ahoppen) [reply test/SourceKit/CursorInfo/issue-62457-symbol-graph-crash.swift:1]: Makes sense to me 👍🏽

File: test/SourceKit/CursorInfo/issue-62457-symbol-graph-crash.swift [hunk 2]
```diff
@@ -0,0 +1,9 @@
...
+
+struct AnyError: Swift.Error {
+  let error: Swift.Error
+}
+
+func test(lhs: AnyError) {
+  lhs.error._code
```
Comment (bnbarham) [inline test/SourceKit/CursorInfo/issue-62457-symbol-graph-crash.swift:8]: Could you add some checks that the symbol graph looks reasonable? Could name the test something like `private-stdlib-symbol-graph.swift`.

**Review by bnbarham — APPROVED** [review]

File: test/SourceKit/CursorInfo/issue-62457-symbol-graph-crash.swift (hunk 2 above)
Comment (bnbarham) [reply test/SourceKit/CursorInfo/issue-62457-symbol-graph-crash.swift:8]: Ah I see Alex beat me to that. I really do think the response is more relevant than the fact it crashed here.

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

File: test/SourceKit/CursorInfo/issue-62457-symbol-graph-crash.swift (hunk 2 above)
Comment (QuietMisdreavus) [reply test/SourceKit/CursorInfo/issue-62457-symbol-graph-crash.swift:7]: I've added some lines to test the declaration fragments, since that's what was crashing SymbolGraphGen.
