### PR TITLE
[cxx-interop] Copy lazily bridged Cocoa strings correctly without hanging

### LINKED ISSUE #69870: Grabbing Mac computer name through C++ Interop hangs
**Description**
I've found that defining a simple function in Swift to grab the name of the local Mac and calling that from C++ can hang if the Mac name contains particular characters.

**Steps to reproduce**
The following steps reproduce the crash for me using XCode 15.0.1 (15A507) on an M1 Max MBP running Sonoma 14.1.1:
- Create a new ‘Command Line Tool’ project named “TestCommand”.
- Create a new C++ file named ‘test’ (with header).  Click ‘Create Bridging Header’ when it asks.
- In TestCommand-Bridging-Header.h, add:
  ```c++
  #include "test.hpp"
  ```
- In test.hpp, add:
  ```c++
  void doTest();
  ```
- In test.cpp, add:
  ```c++
  #include <TestCommand-Swift.h>

  void doTest() {
    printf("Getting Mac name via Swift...\n");
    std::string val = TestCommand::getMacName();
    printf("Got Mac name: %s\n", val.c_str());
  }
  ```
- In main.swift, add:
  ```swift
  // Expose a call for C++ to use.
  public func getMacName() -> String {
    return Host.current().localizedName ?? "Unknown"
  }

  // Call our C++ function that runs the test.
  doTest()
  ```
- Under build settings for the TestCommand target, set C++ and Objective-C Interoperability to “C++/Objective C++”
- You should now be able to build and run the project.
- Now, depending on the name of the Mac (as per System Settings -> General), running should either print the name or hang indefinitely. In my case, if my Mac is named "Eric’s MacBook Pro" I get a hang, but if I remove the apostrophe then the run completes.
- Interestingly, hard-coding the Swift function to return the exact string "Eric’s MacBook Pro" succeeds, whatever that might imply.

**Environment**
- Swift compiler version info: swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)

- Xcode version info: Xcode 15.0.1 Build version 15A507
- Deployment target: macOS Sonoma 14.1.1 (23B81). Also repro'd on Monterey 12.7.1 (21G920)

### PR DESCRIPTION
**Pull request by ludwwwig**
Fixes #69870

### CODE REVIEW

**Review by Xazax-hun — COMMENTED** [review]
Thanks a lot for the contribution! 

Could you add a test that fails before the fix and passes after?

Somewhere in `test/Interop/SwiftToCxx/stdlib` might be a good location for it.

File: lib/PrintAsClang/_SwiftStdlibCxxOverlay.h [hunk 1]
```diff
@@ -70,13 +70,14 @@ static_assert(sizeof(_impl::_impl_String) >= 0,
 SWIFT_INLINE_THUNK String::operator std::string() const {
   auto u = getUtf8();
   std::string result;
-  result.reserve(u.getCount() + 1);
-  using IndexType = decltype(u.getStartIndex());
-  for (auto s = u.getStartIndex().getEncodedOffset(),
-            e = u.getEndIndex().getEncodedOffset();
-       s != e; s = u.indexOffsetBy(IndexType::init(s), 1).getEncodedOffset()) {
```
Comment (hnrklssn) [inline lib/PrintAsClang/_SwiftStdlibCxxOverlay.h:77]: I'm assuming `s` never ends up being equal to `e`. For someone unfamiliar with Cocoa strings, could you elaborate on why that is the case?

**Comment by ludwwwig** [comment]
Hi @Xazax-hun 

Thanks for the quick reply!

I added a very simple test which seems to hang on main. I run

`utils/run-test –lit ../llvm-project/llvm/utils/lit/lit.py 
../build/Ninja-RelWithDebInfoAssert/swift-macosx-$(uname -m)/test-macosx-$(uname -m) 
–filter=“to-nsstring”`

With this patch, the test finishes fine 🎉

Please excuse my affection for the Swedish [letters](https://en.wikipedia.org/wiki/Swedish_alphabet)... I can change the string if anyone has any objections 😁

File: lib/PrintAsClang/_SwiftStdlibCxxOverlay.h (hunk 1 above)
Comment (ludwwwig) [reply lib/PrintAsClang/_SwiftStdlibCxxOverlay.h:77]: I think the easiest way to explain this is to look at my patch, along with some debug prints

```swift
SWIFT_INLINE_THUNK String::operator std::string() const {
  auto u = getUtf8();
  auto size = u.getCount();

  std::string result;
  result.reserve(size);

  auto end_offset = u.getEndIndex().getEncodedOffset();

  printf("end offset = %d\n", end_offset);

  auto idx = u.getStartIndex();

  for (; idx.getEncodedOffset() < end_offset;
        idx = u.indexAfter(idx)) {
    result.push_back(static_cast<char>(u[idx]));
    printf("u[idx] = %c, idx offset = %d\n", u[idx], idx.getEncodedOffset());
  }
  printf("final idx offset = %d\n", idx.getEncodedOffset());

  return result;
}
```

When the Swift::String originates from an NSString containing Unicode chars (👨‍💻👩‍💻), we get
```
end offset = 10
u[idx] = \360, idx offset = 0
u[idx] = \237, idx offset = 0
u[idx] = \221, idx offset = 0
u[idx] = \250, idx offset = 0
u[idx] = \342, idx offset = 2
u[idx] = \200, idx offset = 2
u[idx] = \215, idx offset = 2
u[idx] = \360, idx offset = 3
u[idx] = \237, idx offset = 3
u[idx] = \222, idx offset = 3
u[idx] = \273, idx offset = 3
u[idx] = \360, idx offset = 5
u[idx] = \237, idx offset = 5
u[idx] = \221, idx offset = 5
u[idx] = \251, idx offset = 5
u[idx] = \342, idx offset = 7
u[idx] = \200, idx offset = 7
u[idx] = \215, idx offset = 7
u[idx] = \360, idx offset = 8
u[idx] = \237, idx offset = 8
u[idx] = \222, idx offset = 8
u[idx] = \273, idx offset = 8
final idx offset = 10
```

As can be seen, idx offset does not update correctly.

If we do `string.makeContiguousUTF8()` on the Swift side before the conversion, we instead get

```
end offset = 22
u[idx] = \360, idx offset = 0
u[idx] = \237, idx offset = 1
u[idx] = \221, idx offset = 2
u[idx] = \250, idx offset = 3
u[idx] = \342, idx offset = 4
u[idx] = \200, idx offset = 5
u[idx] = \215, idx offset = 6
u[idx] = \360, idx offset = 7
u[idx] = \237, idx offset = 8
u[idx] = \222, idx offset = 9
u[idx] = \273, idx offset = 10
u[idx] = \360, idx offset = 11
u[idx] = \237, idx offset = 12
u[idx] = \221, idx offset = 13
u[idx] = \251, idx offset = 14
u[idx] = \342, idx offset = 15
u[idx] = \200, idx offset = 16
u[idx] = \215, idx offset = 17
u[idx] = \360, idx offset = 18
u[idx] = \237, idx offset = 19
u[idx] = \222, idx offset = 20
u[idx] = \273, idx offset = 21
final idx offset = 22
```

So basically, we can't rely on the offset for the first case. Using `.indexAfter` however seems to work.

Comment (hnrklssn) [reply lib/PrintAsClang/_SwiftStdlibCxxOverlay.h:77]: I see, it looks like the UTF-8 code units within each unicode code point share the same encoded offset. So when the for-loop eagerly calls `getEncodedOffset()` and then needs to reconstruct the index with `IndexType::init(s)` to advance the loop, it probably constructs the index for the first code unit within that code point. This causes it to jump back to an earlier code unit and looping indefinitely. Thanks for sharing the logs and for your contribution!

**Review by egorzhdan — APPROVED** [review]
Thank you!

**Comment by egorzhdan** [comment]
@swift-ci please test

File: lib/PrintAsClang/_SwiftStdlibCxxOverlay.h [hunk 2]
```diff
@@ -70,13 +70,14 @@ static_assert(sizeof(_impl::_impl_String) >= 0,
 SWIFT_INLINE_THUNK String::operator std::string() const {
   auto u = getUtf8();
   std::string result;
-  result.reserve(u.getCount() + 1);
```
Comment (hnrklssn) [inline lib/PrintAsClang/_SwiftStdlibCxxOverlay.h:73]: Are you sure that reserving the extra byte isn't necessary to avoid reallocation? I think it makes sense, since I believe the null terminator in `std::string` doesn't count as an element in the string, but I want to highlight it so we don't accidentally make a mistake here.

CC @hyp

Comment (egorzhdan) [reply lib/PrintAsClang/_SwiftStdlibCxxOverlay.h:73]: According to https://en.cppreference.com/w/cpp/string/basic_string/capacity.html:

> Note that the null terminator is not an element of the [std::basic_string](https://en.cppreference.com/w/cpp/string/basic_string.html)

So the behavior here looks correct to me.

File: lib/PrintAsClang/_SwiftStdlibCxxOverlay.h (hunk 1 above)
Comment (ludwwwig) [reply lib/PrintAsClang/_SwiftStdlibCxxOverlay.h:77]: No problem! 👍🏻

**Comment by Catfish-Man** [comment]
This sort of confusion is why the `encodedOffset` property of String.Index is deprecated; I'm not familiar with which aspects of the Swift String API are available from this layer of C++ bridging, but perhaps there's a way to structure it that doesn't rely on encodedOffset at all? For example, getting a pointer-length pair out of the String and just initializing directly from that.

**Comment by ludwwwig** [comment]
@Catfish-Man Perhaps something like this could work? I'm building right now...

```swift
SWIFT_INLINE_THUNK String::operator std::string() const {
    auto ptr = getUtf8().baseAddress();
    return std::string(ptr, ptr + u.getCount());
}
```

**Comment by Catfish-Man** [comment]
IFF the String is small (15 or fewer bytes of UTF8) that won't work, because there's no contiguous storage to point to. We use closure-taking accessors to get the pointer out reliably: https://developer.apple.com/documentation/swift/string/withcstring(_:)

**Comment by egorzhdan** [comment]
I don't think we currently expose Swift closures to C++ at the moment, so we might have to keep using the non-closure-taking APIs here.

**Comment by ludwwwig** [comment]
At least this patch solves #69870, albeit not in the most efficient way.

Any clues to what's going on with the Windows test @egorzhdan?

**Comment by hnrklssn** [comment]
hmmm let's try to run that again
@swift-ci please test windows platform

**Comment by ludwwwig** [comment]
@hnrklssn Looks like everything passes. Can we merge this now? 🤔
