### PR TITLE
[Sema] Look through FunctionConversionExpr when finding @discardableResult callee

### LINKED ISSUE #60276: Getting "unused" warning from function annotated with "@discardableResult"
**Describe the bug**

I've started to see unused warnings crop up in Xcode 14 beta 4 for endpoints that are annotated with `@discardableResult`.

**Steps To Reproduce**

It's not always easy to reproduce, but I've specifically gotten them to appear in the following repo/project/file:

1. Clone https://github.com/pointfreeco/swift-composable-architecture
2. Check out `d526b07053d46a740936e50be436f78c7ce7b092`
3. Open **ComposableArchitecture.xcworkspace**
4. Navigate to **[VoiceMemosTests.swift](https://github.com/pointfreeco/swift-composable-architecture/blob/d526b07053d46a740936e50be436f78c7ce7b092/Examples/VoiceMemos/VoiceMemosTests/VoiceMemosTests.swift)**
5. Run tests, allow Xcode to type-check file, etc.
6. Note that lines like [this one](https://github.com/pointfreeco/swift-composable-architecture/blob/d526b07053d46a740936e50be436f78c7ce7b092/Examples/VoiceMemos/VoiceMemosTests/VoiceMemosTests.swift#L239) have the warning:
    > **Warning:** Result of call to function returning 'TestStoreTask' is unused
7. Note that the function returning `TestStoreTask` [is annotated](https://github.com/pointfreeco/swift-composable-architecture/blob/d526b07053d46a740936e50be436f78c7ce7b092/Sources/ComposableArchitecture/TestStore.swift#L504) with `@discardableResult`.

**Expected behavior**
I expect no warning.

**Screenshots**
image

**Environment (please fill out the following information)**
 - OS: macOS 11.0
 - Xcode 14 beta 4

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by theblixguy**
Resolves https://github.com/apple/swift/issues/60276

```swift
@discardableResult @MainActor
func a() async -> Int { 5 }

func b() async {
  await a()
}
```

On 5.7. you get a warning:

```
<source>:3:11: warning: result of call to function returning 'Int' is unused
    await a()
          ^~~
```

When using `@MainActor` the call is wrapped in an implicit `FunctionConversionExpr` and we currently do not look through that to find the callee function, so the code falls through and triggers this warning. 

This is a regression in 5.7, as this warning does not appear in 5.6.

### CODE REVIEW

**Review by xedin — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Comment by LucianoPAlmeida** [comment]
MacOS test is failing on OSes that not support concurrency, I think in this case is just fine to run this with `-disable-availability-checking` at `RUN` line...

**Comment by theblixguy** [comment]
@swift-ci please test

File: test/attr/attr_discardableResult.swift [hunk 1]
```diff
@@ -1,4 +1,4 @@
-// RUN: %target-typecheck-verify-swift -enable-objc-interop
+// RUN: %target-typecheck-verify-swift -enable-objc-interop -disable-availability-checking
```
Comment (xedin) [inline test/attr/attr_discardableResult.swift:1]: Could this be moved to one of the concurrency test files instead?

Comment (theblixguy) [reply test/attr/attr_discardableResult.swift:1]: Yeah I thought about doing it, but the files in there pass this flag anyway so I thought I’d tweak this.

Comment (xedin) [reply test/attr/attr_discardableResult.swift:1]: That's okay is they do but at least it's all going to be grouped together...

Comment (theblixguy) [reply test/attr/attr_discardableResult.swift]: Alright done!

**Comment by theblixguy** [comment]
@swift-ci please test

File: test/attr/attr_discardableResult.swift (hunk 1 above)
Comment (xedin) [reply test/attr/attr_discardableResult.swift]: Thank you!

**Comment by xedin** [comment]
@theblixguy Please do open 5.7 PR for this.

**Comment by flowtoolz** [comment]
It has been merged on August 4, but is still present in the official Xcode 14 release. May I be doing anything wrong? 
Screenshot 2022-09-16 at 12 06 08
