### PR TITLE
[Sema] A couple of fixes for MiscDiagnostics on macro expansions

### LINKED ISSUE #77453: Duplicate statement diagnostics in result builder
The following gives a duplicate diagnostic:

```swift
@resultBuilder
struct Builder {
  static func buildBlock<T>(_ components: T...) -> T {
    components.first!
  }
  static func buildEither<T>(first component: T) -> T {
    component
  }
  static func buildEither<T>(second component: T) -> T {
    component
  }
}

func takesClosure(_ fn: () -> Void) -> Int? { nil }

@Builder
func foo() -> Int {
  if let x = takesClosure {} { // 2x warning: trailing closure in this context is confusable with the body of the statement
    0
  } else {
    1
  }
}
```

### PR DESCRIPTION
**Pull request by hamishknight**
- Delay expanding macros until the end of CSApply to ensure the solution is applied to any parent expression nodes, avoiding a crash for the implicit-self diagnostic logic
- Avoid double-diagnosing macro expansions in MiscDiagnostics, ensuring we only walk expansions in MiscDiagnostics when type-checking the expansion itself

rdar://138997009

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

**Comment by hamishknight** [comment]
Oh fun, looks like we were missing `checkExistentialTypes` on `catch` statements previously, this patch fixes it for closures but not regular statements

**Comment by hamishknight** [comment]
Going to drop the `performStmtDiagnostics` change for now since that's going to be a larger change to fix

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test source compatibility

File: test/Macros/macro_misc_diags.swift [hunk 1]
```diff
@@ -0,0 +1,127 @@
...
+
+struct S2 {
+  #makeBinding({deprecatedFunc()})
+  // CHECK-DIAG: Client.swift:[[@LINE-1]]:17: warning: 'deprecatedFunc()' is deprecated
+  // CHECK-DIAG: @__swiftmacro_6Client0017Clientswift_yEEFcfMX[[@LINE-3]]{{.*}}makeBindingfMf_.swift:2:5: warning: 'deprecatedFunc()' is deprecated
+}
+
+func takesClosure(_ fn: () -> Void) -> Int? { nil }
+
+// FIXME: We should only be diagnosing the expansion here.
```
Comment (hamishknight) [inline test/Macros/macro_misc_diags.swift:97]: Okay it turns out the intention is to diagnose for both the argument and the expansion. I'll remove these FIXMEs, and can fix MiscDiagnostics to consistently visit the arguments in a follow-up

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test macOS

File: lib/Sema/MiscDiagnostics.cpp [hunk 2]
```diff
@@ -1581,7 +1577,9 @@ static void diagRecursivePropertyAccess(const Expr *E, const DeclContext *DC) {
     }
 
     MacroWalking getMacroWalkingBehavior() const override {
-      return MacroWalking::Expansion;
+      // Macro expansions will be walked when they're type-checked, not as
+      // part of the surrounding code.
+      return MacroWalking::None;
```
Comment (xedin) [inline lib/Sema/MiscDiagnostics.cpp:1582]: Could you please separately evaluate whether it would be possible to subtype all of this walkers from `BaseDiagnosticWalker` and remove all of these overrides?

**Review by xedin — APPROVED** [review]

File: lib/Sema/MiscDiagnostics.cpp (hunk 2 above)
Comment (hamishknight) [reply lib/Sema/MiscDiagnostics.cpp:1582]: Heh, I have that exact change in a follow-up PR :)

Comment (xedin) [reply lib/Sema/MiscDiagnostics.cpp:1582]: Perfect! :)
