### PR TITLE
ConformanceChecker: Don't record a type witness for an overridden associated type if...

### LINKED ISSUE #55359: [SR-12913] Associated type inference crash: "Conflicting type witness deductions"
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12913      |
   |Radar             | rdar://problem/63819460         |
   |Original Reporter | @dan-zheng      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

swift-DEVELOPMENT-SNAPSHOT-2020-05-26-a

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, AssociatedTypeInference, CompilerCrash        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 017a8020317d94098be933346fbf2e7d

  </details>

**Issue Description:**

Reproducer not minimized. I tried minimizing it to a single file but wasn't yet successful, sorry.

``` swift
import _Differentiation

protocol DifferentiableCollection: Differentiable & Collection {
  associatedtype TangentVector
}
extension Array: DifferentiableCollection {}
```

``` swift
$ swift crash.swift
Assertion failed: (Conformance->getTypeWitnessUncached(assocType) .getWitnessType() ->isEqual(type) && "Conflicting type witness deductions"), function recordTypeWitness, file /Users/danielzheng/swift-debug/swift/lib/Sema/TypeCheckProtocol.cpp, line 2685.
Stack dump:
...
1.  Swift version 5.3-dev (LLVM 2e4f104624, Swift 50b4fcc97d)
2.  While evaluating request TypeCheckSourceFileRequest(source_file "crash.swift")
3.  While type-checking extension of Array (at crash.swift:6:1)
4.  While type-checking protocol conformance to 'DifferentiableCollection' (at crash.swift:3:1) for type 'Array<Element>'
0  swift                    0x000000010a280808 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 40
1  swift                    0x000000010a27f788 llvm::sys::RunSignalHandlers() + 248
2  swift                    0x000000010a280dfd SignalHandler(int) + 285
3  libsystem_platform.dylib 0x00007fff6d6115fd _sigtramp + 29
4  libsystem_platform.dylib 000000000000000000 _sigtramp + 18446603338681084448
5  libsystem_c.dylib        0x00007fff6d4e7808 abort + 120
6  libsystem_c.dylib        0x00007fff6d4e6ac6 err + 0
7  swift                    0x000000010a692ab3 swift::ConformanceChecker::recordTypeWitness(swift::AssociatedTypeDecl*, swift::Type, swift::TypeDecl*) (.cold.1) + 35
8  swift                    0x0000000106a5b881 swift::ConformanceChecker::recordTypeWitness(swift::AssociatedTypeDecl*, swift::Type, swift::TypeDecl*) + 81
9  swift                    0x0000000106a5c0f0 swift::ConformanceChecker::recordTypeWitness(swift::AssociatedTypeDecl*, swift::Type, swift::TypeDecl*) + 2240
10 swift                    0x0000000106a5f615 swift::ConformanceChecker::resolveTypeWitnessViaLookup(swift::AssociatedTypeDecl*) + 869
11 swift                    0x0000000106a7f5ea swift::AssociatedTypeInference::solve(swift::ConformanceChecker&) + 282
12 swift                    0x0000000106a7fe1f swift::ConformanceChecker::resolveTypeWitnesses() + 271
```

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
...the conformance to the corresponding inherited protocol
- originates in a superclass
- originates in a different module
- and the current conformance have mismatching conditional requirements

This can turn out badly in two ways:
- Foremost, we must not *alter* conformances originating in superclasses
  or other modules. In other cases, we may hit an assertion in an attempt
  to overwrite an already recorded type witness with a different one.
  For example, the recorded type witness may be invalid, whereas the
  other one---valid, and vice versa.
- If the current conformance is more restrictive, this type witness may
  not be a viable candidate for the overridden associated type.

This merely addresses some crashers and a correctness issue, as it happens; we should find a more principled approach to overridden associated types in the future.

Resolves #55359

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
@swift-ci please test source compatibility

File: lib/Sema/TypeCheckProtocol.cpp [hunk 1]
```diff
@@ -3397,6 +3397,24 @@ void ConformanceChecker::recordTypeWitness(AssociatedTypeDecl *assocType,
...
+    // conformance have mismatching conditional requirements. This can turn out
+    // badly in two ways:
+    // - If a type witness for the overridden associated type has already been
+    //   recorded, we may hit an assertion in an attempt to overwrite it
+    //   with a different one. For example, the recorded type witness may be
+    //   invalid, whereas the other one---valid, and vice versa.
+    // - If the current conformance is more restrictive, this type witness may
+    //   not be a viable candidate for the overridden associated type.
+    auto currConformanceSig = DC->getGenericSignatureOfContext();
+    auto overriddenConformanceSig = overriddenRootConformance->getDeclContext()
```
Comment (slavapestov) [inline lib/Sema/TypeCheckProtocol.cpp:3412]: Can this be in a base class with a different generic signature?

Comment (AnthonyLatsis) [reply lib/Sema/TypeCheckProtocol.cpp:3412]: Yeah, good point. Testing several scenarios with classes left me pretty confused. For example, to my knowledge the type witness below ought to just be inherited, but instead we find `Derived.A` and crash in an attempt to overwrite the already-resolved type witness for the "overridden" associated type. Interestingly—and I wonder why, because we were recording type witnesses for overridden associated types all the same—this works with a 5.5.2 compiler.

```swift
protocol P {
  associatedtype A
}
protocol Q: P {
  associatedtype A
}

class Base {}
class Derived: Base {}

extension Base: P {
  typealias A = Bool
}
extension Derived: Q {
  typealias A = Int
}
```

**Comment by AnthonyLatsis** [comment]
@swift-ci please smoke test

**Comment by AnthonyLatsis** [comment]
@swift-ci please test source compatibility

**Comment by AnthonyLatsis** [comment]
@slavapestov ping

**Comment by AnthonyLatsis** [comment]
@slavapestov ping

**Review by slavapestov — APPROVED** [review]

**Comment by AnthonyLatsis** [comment]
@swift-ci please test
