### PR TITLE
[Sema] Compiler should diagnose non-unique raw values without crashing

### LINKED ISSUE #63829: Typechecking crashes when enum contains a duplicated string raw value
```swift
struct A
{
    enum CodingKeys:String
    {
        case a
        case b
        case b
    }
}
```

crashes with

```
sourcekit-lsp: /home/build-user/swift/lib/Sema/TypeCheckDecl.cpp:1340: evaluator::SideEffect swift::EnumRawValuesRequest::evaluate(swift::Evaluator &, swift::EnumDecl *, swift::TypeResolutionStage) const: Assertion `lastExplicitValueElt && "should not be able to have non-unique raw values when " "relying on autoincrement"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	While evaluating request TypeCheckSourceFileRequest(source_file "/swift/swift-mongodb/crash.0.swift")
1.	While type-checking 'A' (at /swift/swift-mongodb/crash.0.swift:1:1)
2.	While type-checking 'CodingKeys' (at /swift/swift-mongodb/crash.0.swift:3:5)
3.	While type-checking 'a' (at /swift/swift-mongodb/crash.0.swift:5:14)
4.	While evaluating request EnumRawValuesRequest(main.(file).A.CodingKeys@/swift/swift-mongodb/crash.0.swift:3:10, interface)
[Error - 3:14:02 AM] Request textDocument/codeAction failed.
```

on `swift-5.8-DEVELOPMENT-SNAPSHOT-2023-02-09-a `. (amazon linux2 nightly docker container)

### PR DESCRIPTION
**Pull request by angela-laar**
Enums with raw type `: String ` use the case name as the raw value if the case is undefined. So two identical case names causes a "raw value for enum case is not unique" error. Additionally, identical case names will always cause a separate redeclaration error regardless of the declared enum raw type. 

```
enum Foo : String {
    case Bar
    case Bar // two errors:  non-unique raw value error and invalid redeclaration of 'Bar'
    case Bar = "FooBar" // one error: invalid redeclaration of 'Bar' because raw value is FooBar instead of Bar
}
```

This second error gets diagnosed in CheckRedeclarationRequest in the DeclVisitor. We could add a special case for this situation to ignore the raw value error and defer diagnosing to the DeclVisitor since fixing that error is most correct. For now, I'll fix the crash and let the compiler diagnose both errors.

Fixes rdar://105761206
Fixes #63829

### CODE REVIEW

**Comment by angela-laar** [comment]
@swift-ci please smoke test

File: test/Parse/enum.swift [hunk 1]
```diff
@@ -364,6 +364,13 @@ enum DuplicateMembers7 : String { // expected-error {{'DuplicateMembers7' declar
   case Foo = "Bar" // expected-error {{invalid redeclaration of 'Foo'}}
 }
 
+enum DuplicateMembers8 : String { // expected-error {{'DuplicateMembers8' declares raw type 'String', but does not conform to RawRepresentable and conformance could not be synthesized}}
+  case Foo // expected-note {{'Foo' previously declared here}}
+  // expected-note@-1 {{raw value previously used here}}
+  case Foo // expected-error {{invalid redeclaration of 'Foo'}}
+  // expected-error@-1 {{raw value for enum case is not unique}}
```
Comment (slavapestov) [inline test/Parse/enum.swift:371]: Can you also test a couple of edge cases?

```
case Foo = "Foo"
case Foo = "Foo"
```
and
```
case Foo
case Bar = "Foo"
```

**Review by slavapestov — APPROVED** [review]
I think having both errors is fine since there really _are_ two errors: you're redeclaring a case with the same name, and the implicit raw value is also a duplicate

File: test/Parse/enum.swift (hunk 1 above)
Comment (angela-laar) [reply test/Parse/enum.swift:371]: the second one is already tested in `enum DuplicateMembers7` !

Comment (angela-laar) [reply test/Parse/enum.swift:371]: I'll add a test for your first suggestion

**Comment by angela-laar** [comment]
@swift-ci please smoke test macOS platform

**Comment by angela-laar** [comment]
@swift-ci please smoke test macOS platform
