### PR TITLE
[Concurrency] Fix how we obtain DA-as-A conformance for cross module

### LINKED ISSUE #73702: Reproducer still crashes with the 05/24 toolchain. Stack trace looks a bit different from the original issue.
This is not a "still" but a new issue / regression in 6.0.

Copying from other issue:

----

              Reproducer still crashes with the 05/24 toolchain. Stack trace looks a bit different from the original issue.

```
4.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for file "/Users/kshitij/workspace/scratch/swift-distributed-actors/Sources/DistributedCluster/Plugins/ClusterSingleton/ClusterSingletonBoss.swift")
5.	While generating SIL witness table protocol conformance Self: Actor at extension of DistributedActor (in module 'Distributed')
6.	While reading from module 'Distributed', builder version '6.0(5.10)/Apple Swift version 6.0-dev (LLVM b66077aefd3be08, Swift 84d36181a762913)', built from swiftinterface, resilient, loaded from '/Users/kshitij/workspace/scratch/swift-distributed-actors/Samples/.build/arm64-apple-macosx/debug/ModuleCache/Distributed-3DIVDCQGHH6N9.swiftmodule'
7.	While finishing conformance for protocol conformance Self: Actor at extension of DistributedActor (in module 'Distributed')
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000105c91600 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x0000000105c8fdcc llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x0000000105c91c48 SignalHandler(int) + 304
3  libsystem_platform.dylib 0x00000001a3286a24 _sigtramp + 56
4  libsystem_pthread.dylib  0x00000001a3257c28 pthread_kill + 288
5  libsystem_c.dylib        0x00000001a3165ae8 abort + 180
6  libsystem_c.dylib        0x00000001a3164e44 err + 0
7  swift-frontend           0x00000001061da454 swift::NormalProtocolConformance::setWitness(swift::ValueDecl*, swift::Witness) const (.cold.7) + 0
8  swift-frontend           0x000000010207f6bc swift::NormalProtocolConformance::setWitness(swift::ValueDecl*, swift::Witness) const + 192
9  swift-frontend           0x0000000101519d34 swift::ModuleFile::finishNormalConformance(swift::NormalProtocolConformance*, unsigned long long) + 3840
10 swift-frontend           0x000000010207da58 swift::NormalProtocolConformance::getWitness(swift::ValueDecl*) const + 88
11 swift-frontend           0x0000000100f3e2c4 (anonymous namespace)::SILGenWitnessTable<(anonymous namespace)::SILGenConformance>::addMethod(swift::SILDeclRef) + 128
12 swift-frontend           0x0000000100f3e1c0 void llvm::function_ref<void (swift::AccessorDecl*)>::callback_fn<swift::SILWitnessVisitor<(anonymous namespace)::SILGenConformance>::visitAbstractStorageDecl(swift::AbstractStorageDecl*)::'lambda'(swift::AccessorDecl*)>(long, swift::AccessorDecl*) + 132
13 swift-frontend           0x0000000101ec0074 swift::AbstractStorageDecl::visitExpectedOpaqueAccessors(llvm::function_ref<void (swift::AccessorKind)>) const + 68
14 swift-frontend           0x0000000101ebfe9c swift::AbstractStorageDecl::visitOpaqueAccessors(llvm::function_ref<void (swift::AccessorDecl*)>) const + 40
15 swift-frontend           0x0000000100f3dee8 swift::SILWitnessVisitor<(anonymous namespace)::SILGenConformance>::visitProtocolDecl(swift::ProtocolDecl*) + 1800
16 swift-frontend           0x0000000100f3b6b0 swift::Lowering::SILGenModule::getWitnessTable(swift::NormalProtocolConformance*) + 324
17 swift-frontend           0x0000000100e42920 swift::ASTLoweringRequest::evaluate(swift::Evaluator&, swift::ASTLoweringDescriptor) const + 2120
18 swift-frontend           0x0000000100f2aecc swift::SimpleRequest<swift::ASTLoweringRequest, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>> (swift::ASTLoweringDescriptor), (swift::RequestFlags)9>::evaluateRequest(swift::ASTLoweringRequest const&, swift::Evaluator&) + 148
19 swift-frontend           0x0000000100e47d3c swift::ASTLoweringRequest::OutputType swift::Evaluator::getResultUncached<swift::ASTLoweringRequest, swift::ASTLoweringRequest::OutputType swift::evaluateOrFatal<swift::ASTLoweringRequest>(swift::Evaluator&, swift::ASTLoweringRequest)::'lambda'()>(swift::ASTLoweringRequest const&, swift::ASTLoweringRequest::OutputType swift::evaluateOrFatal<swift::ASTLoweringRequest>(swift::Evaluator&, swift::ASTLoweringRequest)::'lambda'()) + 340
20 swift-frontend           0x0000000100e42d4c swift::performASTLowering(swift::FileUnit&, swift::Lowering::TypeConverter&, swift::SILOptions const&, swift::IRGenOptions const*) + 96
21 swift-frontend           0x000000010082c22c swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 568
22 swift-frontend           0x000000010083d4cc withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 160
23 swift-frontend           0x000000010082e868 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 708
24 swift-frontend           0x000000010082d7d4 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2368
25 swift-frontend           0x00000001006489cc swift::mainEntry(int, char const**) + 3096
26 dyld                     0x00000001a2efff28 start + 2236
```

_Originally posted by @jkshtj in https://github.com/apple/swift/issues/62898#issuecomment-2093637645_

### PR DESCRIPTION
**Pull request by ktoso**
This reworks how we obtain the conformance of `DistributedActor` to `Actor` as the previous way did not account for cross module situations.

Resolves rdar://127206143
Resolves https://github.com/apple/swift/issues/73702

### CODE REVIEW

File: include/swift/AST/DistributedDecl.h [hunk 1]
```diff
@@ -102,6 +102,29 @@ Type getDistributedActorSystemResultHandlerType(NominalTypeDecl *system);
...
+ProtocolConformanceRef
+getDistributedActorAsActorConformanceRef(ASTContext &C);
+
+/// Find the extension that defines the methods necessary for creating the
+/// the DistributedActor-as-Actor conformance.
+ExtensionDecl *
+findDistributedActorAsActorExtension(
+    ProtocolDecl *distributedActorProto, ModuleDecl *module);
+
+bool isDistributedActorAsLocalActorComputedProperty(VarDecl *var);
```
Comment (ktoso) [inline include/swift/AST/DistributedDecl.h:123]: since used in 2 spots

File: lib/SILGen/SILGenConcurrency.cpp [hunk 2]
```diff
@@ -661,75 +662,29 @@ SILValue SILGenFunction::emitGetCurrentExecutor(SILLocation loc) {
   return ExpectedExecutor;
 }
 
-/// Find the extension on DistributedActor that defines __actorUnownedExecutor.
-static ExtensionDecl *findDistributedActorAsActorExtension(
```
Comment (ktoso) [inline lib/SILGen/SILGenConcurrency.cpp:665]: those all moved to DistributedDecl.cpp

File: lib/SILGen/SILGenConcurrency.cpp [hunk 3]
```diff
@@ -661,75 +662,29 @@ SILValue SILGenFunction::emitGetCurrentExecutor(SILLocation loc) {
...
-                                distributedActorTL, anyActorTL,
-                                ctx.AllocateCopy(conformances),
-                                SGFContext(),
-                                [actorValue](SGFContext) {
-    return actorValue;
-  });
+  return emitExistentialErasure(
+      loc, distributedActorCanType, distributedActorTL, anyActorTL,
+      ctx.AllocateCopy(conformances), SGFContext(),
+      [actorValue](SGFContext) { return actorValue; });
```
Comment (ktoso) [inline lib/SILGen/SILGenConcurrency.cpp:689]: (clang format reformatted those heh)

File: lib/Sema/CodeSynthesisDistributedActor.cpp [hunk 4]
```diff
@@ -1066,3 +1065,30 @@ bool CanSynthesizeDistributedActorCodableConformanceRequest::evaluate(
...
+
+  auto actorProto = ctx.getProtocol(KnownProtocolKind::Actor);
+
+  auto ext = findDistributedActorAsActorExtension(
+      distributedActorProto, swiftModule);
+  if (!ext)
+    return nullptr;
+
+  auto genericParam = GenericTypeParamType::get(/*isParameterPack=*/false,
+                                                /*depth=*/0, /*index=*/0, ctx);
```
Comment (ktoso) [inline lib/Sema/CodeSynthesisDistributedActor.cpp:1083]: This seems to be fine...? I guess so, at least real project also is happy with just inventing a generic type here. If there's better way let me know please @slavapestov @xedin

File: test/Distributed/Inputs/FakeDistributedActorSystems.swift [hunk 5]
```diff
@@ -21,6 +21,13 @@ public distributed actor FakeRoundtripActorSystemDistributedActor {
   public typealias ActorSystem = FakeRoundtripActorSystem
 }
 
+
+@available(SwiftStdlib 5.7, *)
+@_transparent
+public func f<T: DistributedActor>(_ t: isolated T) -> any Actor {
```
Comment (ktoso) [inline test/Distributed/Inputs/FakeDistributedActorSystems.swift:27]: - [ ] TODO: maybe rename this or just move into a "lib.swift" for the test.

File: lib/SILGen/SILGen.h [hunk 6]
```diff
@@ -83,10 +83,6 @@ class LLVM_LIBRARY_VISIBILITY SILGenModule : public ASTVisitor<SILGenModule> {
   /// Set of delayed conformances that have already been forced.
   llvm::DenseSet<NormalProtocolConformance *> forcedConformances;
 
-  /// The conformance for any DistributedActor to the Actor protocol,
-  /// used only by the `distributedActorAsAnyActor` builtin.
-  NormalProtocolConformance *distributedActorAsActorConformance = nullptr;
```
Comment (ktoso) [inline lib/SILGen/SILGen.h:88]: removed the ad hoc cache thingy

**Comment by ktoso** [comment]
@swift-ci please smoke test

File: lib/AST/DistributedDecl.cpp [hunk 7]
```diff
@@ -76,6 +76,86 @@ bool swift::canSynthesizeDistributedActorCodableConformance(NominalTypeDecl *act
...
+
+  auto subs =
+    SubstitutionMap::get(
+      asLocalActor->getDeclContext()->getGenericSignatureOfContext(),
+      MapTypeOutOfContext(),
+      LookUpConformanceInModule(actorProto->getParentModule()));
+
+    return ProtocolConformanceRef(
+        actorProto,
+        C.getSpecializedConformance(distributedActorType,
```
Comment (slavapestov) [inline lib/AST/DistributedDecl.cpp:146]: Does this do anything? What happens if you add

distributedActorAsActorConformance->dump();
C.getSpecializedConformance(…)->dump();

Aren’t both the same?

Comment (ktoso) [reply lib/AST/DistributedDecl.cpp:146]: Thanks for the quick review and note, sorry I got caught up something urgent -- I'll check this as soon as i can

File: lib/AST/DistributedDecl.cpp [hunk 8]
```diff
@@ -76,6 +76,86 @@ bool swift::canSynthesizeDistributedActorCodableConformance(NominalTypeDecl *act
...
+         var->getDeclContext()->getSelfProtocolDecl() &&
+         var->getDeclContext()->getSelfProtocolDecl()->isSpecificProtocol(
+             KnownProtocolKind::DistributedActor);
+}
+
+VarDecl *
+swift::getDistributedActorAsLocalActorComputedProperty(ModuleDecl *module) {
+  auto &C = module->getASTContext();
+  auto DA = C.getDistributedActorDecl();
+  auto extension = findDistributedActorAsActorExtension(DA, module);
```
Comment (DougGregor) [inline lib/AST/DistributedDecl.cpp:108]: Should we bail out here if `!extension`? I know it shouldn't happen with a newer _Concurrency module, but...

File: lib/AST/DistributedDecl.cpp [hunk 9]
```diff
@@ -76,6 +76,86 @@ bool swift::canSynthesizeDistributedActorCodableConformance(NominalTypeDecl *act
...
+  }
+
+  return nullptr;
+}
+
+bool swift::isDistributedActorAsLocalActorComputedProperty(VarDecl *var) {
+  auto &C = var->getASTContext();
+  return var->getName() == C.Id_asLocalActor &&
+         var->getDeclContext()->getSelfProtocolDecl() &&
+         var->getDeclContext()->getSelfProtocolDecl()->isSpecificProtocol(
```
Comment (DougGregor) [inline lib/AST/DistributedDecl.cpp:100]: Am I being paranoid in wanting to check the module, too? Users could have an `asLocalActor` that doesn't have the right signature.

File: lib/AST/DistributedDecl.cpp [hunk 10]
```diff
@@ -76,6 +76,86 @@ bool swift::canSynthesizeDistributedActorCodableConformance(NominalTypeDecl *act
...
+  auto actorProto = C.getProtocol(KnownProtocolKind::Actor);
+  auto distributedActorProto = C.getProtocol(KnownProtocolKind::DistributedActor);
+  Type distributedActorType = C.getDistributedActorType();
+
+  auto distributedActorAsActorConformance =
+      getDistributedActorAsActorConformance(C);
+
+  auto module = C.getStdlibModule();
+  VarDecl *asLocalActor =
+      getDistributedActorAsLocalActorComputedProperty(module);
```
Comment (DougGregor) [inline lib/AST/DistributedDecl.cpp:132]: If this is NULL, should we return an invalid ProtocolConformanceRef, or is that just kicking the can down the road?

File: lib/SILGen/SILGen.h (hunk 6 above)
Comment (DougGregor) [reply lib/SILGen/SILGen.h:88]: thanks (and sorry)

File: lib/Sema/CodeSynthesisDistributedActor.cpp (hunk 4 above)
Comment (DougGregor) [reply lib/Sema/CodeSynthesisDistributedActor.cpp:1083]: This looks fine to me

File: lib/Sema/CodeSynthesisDistributedActor.cpp [hunk 11]
```diff
@@ -1066,3 +1065,30 @@ bool CanSynthesizeDistributedActorCodableConformanceRequest::evaluate(
...
+
+  auto distributedActorAsActorConformance = ctx.getNormalConformance(
+      Type(genericParam), actorProto, SourceLoc(), ext,
+      ProtocolConformanceState::Incomplete, /*isUnchecked=*/false,
+      /*isPreconcurrency=*/false);
+  // NOTE: Normally we "register" a conformance, but here we don't
+  // because we cannot (currently) register them in a protocol,
+  // since they do not have conformance tables.
```
Comment (DougGregor) [inline lib/Sema/CodeSynthesisDistributedActor.cpp:1091]: Yeah, the language doesn't have the feature we snuck in here.

File: lib/Serialization/Deserialization.cpp [hunk 12]
```diff
@@ -1011,6 +1013,29 @@ ProtocolConformanceDeserializer::readNormalProtocolConformance(
       conformingType, proto, SourceLoc(), dc,
       ProtocolConformanceState::Incomplete,
       isUnchecked, isPreconcurrency);
+
+  if (conformance->isConformanceOfProtocol()) {
+    auto &C = dc->getASTContext();
+
+    // Currently this we should only be skipping only be happening for the
```
Comment (DougGregor) [inline lib/Serialization/Deserialization.cpp:1020]: Slightly garbled comment, did you mean this?

```suggestion
    // Currently this should only be happening for the
```

**Review by DougGregor — APPROVED** [review]
Thank you, this looks great (and tricky)

File: lib/AST/DistributedDecl.cpp (hunk 9 above)
Comment (ktoso) [reply lib/AST/DistributedDecl.cpp:100]: Sounds good, yes let's check

File: lib/Serialization/Deserialization.cpp (hunk 12 above)
Comment (ktoso) [reply lib/Serialization/Deserialization.cpp:1020]: yeap, whoops thank you

File: lib/Sema/CodeSynthesisDistributedActor.cpp (hunk 4 above)
Comment (ktoso) [reply lib/Sema/CodeSynthesisDistributedActor.cpp:1083]: thanks!

File: lib/SILGen/SILGen.h (hunk 6 above)
Comment (ktoso) [reply lib/SILGen/SILGen.h:88]: no prob, all's good that ends good 😅

Comment (ktoso) [reply lib/SILGen/SILGen.h:88]: no problem, thank you!

File: lib/AST/DistributedDecl.cpp (hunk 7 above)
Comment (ktoso) [reply lib/AST/DistributedDecl.cpp:146]: So I checked and yes they're different, like so:

```
[DistributedDecl.cpp:144](getDistributedActorAsActorConformanceRef) THE distributedActorAsActorConformance ============
(normal_conformance type="\xCF\x84_0_0" protocol="Actor"
  (assoc_conformance type="Self" proto="AnyActor"
    (abstract_conformance protocol="AnyActor")))
```

```
[DistributedDecl.cpp:146](getDistributedActorAsActorConformanceRef) THE C.getSpecializedConformance(distributedActorType ============
(specialized_conformance type="DistributedActor" protocol="Actor"
  (substitution_map generic_signature=<Self where Self : DistributedActor>
    (substitution Self ->
      (generic_type_param_type depth=0 index=0 decl="Distributed.(file).DistributedActor.Self"))
    (conformance type="Self"
      (abstract_conformance protocol="DistributedActor")))
  (<conditional requirements unable to be computed>)
  (normal_conformance type="\xCF\x84_0_0" protocol="Actor"
    (assoc_conformance type="Self" proto="AnyActor"
      (abstract_conformance protocol="AnyActor"))))
[DistributedDecl.cpp:150](getDistributedActorAsActorConformanceRef)
```

Comment (ktoso) [reply lib/AST/DistributedDecl.cpp:146]: But it seems the project compiles fine if we just return `distributedActorAsActorConformance` directly huh -- should I prefer that then @slavapestov ? I don't know why a specialized_conformance or a normal_conformance might be preferred over another.

File: lib/AST/DistributedDecl.cpp (hunk 8 above)
Comment (ktoso) [reply lib/AST/DistributedDecl.cpp:108]: better safe than sorry, done!

File: lib/AST/DistributedDecl.cpp (hunk 9 above)
Comment (ktoso) [reply lib/AST/DistributedDecl.cpp:100]: Hmmm, we are checking "is specific protocol" so I think that includes module right? Happy to add but not sure if necessary

File: lib/AST/DistributedDecl.cpp (hunk 10 above)
Comment (ktoso) [reply lib/AST/DistributedDecl.cpp:132]: managed to not need this line at all! since returning just the normal_conformance now as @slavapestov suggested above

File: lib/AST/DistributedDecl.cpp (hunk 7 above)
Comment (ktoso) [reply lib/AST/DistributedDecl.cpp:146]: I'll prepare the PR with just returning distributedActorAsActorConformance but would like to understand if for sure that's okey :)

**Comment by ktoso** [comment]
@swift-ci please smoke test

File: lib/AST/DistributedDecl.cpp (hunk 7 above)
Comment (slavapestov) [reply lib/AST/DistributedDecl.cpp]: Yes because this is the identity substitution map:

```
  (substitution_map generic_signature=<Self where Self : DistributedActor>
    (substitution Self ->
      (generic_type_param_type depth=0 index=0 decl="Distributed.(file).DistributedActor.Self"))
    (conformance type="Self"
      (abstract_conformance protocol="DistributedActor")))
```

Comment (ktoso) [reply lib/AST/DistributedDecl.cpp]: Ah I see now, thank you!

**Comment by ktoso** [comment]
Been stuck in mysterious CI adventures here... hope to land soon.

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
@swift-ci please smoke test
