### PR TITLE
Fix indexing constructors with generic parameters

### LINKED ISSUE #54532: [SR-12096] Index missing references to initializers in Result extensions
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12096      |
   |Radar             | rdar://problem/58997223         |
   |Original Reporter | @kastiglione      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963621-4060512a-f4b0-4584-9edf-37bd0d008e29.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 1ee7c9ff01d3a11c55b26c435d413b5a

  </details>

**relates to**:  
* [SR-12047](https://bugs.swift.org/browse/SR-12047) Types referenced with `is Foo` not in index  
* [SR-12102](https://bugs.swift.org/browse/SR-12102) Discrepancy in indexstore for function parameter references  

**Issue Description:**

In a specific case, the index is missing references to initializers added in an `enum` extension. In this case, `Result`.

This example is two parts. First, an extension on `Result` that adds initializers:

``` swift
extension Result {
    public init(value: Success) {
        self = .success(value)
    }

    public init(error: Failure) {
        self = .failure(error)
    }
}
```

The second part is calling these initializers with explicit types:

``` swift
let value = Result<Int, SomeError>(value: 5)
let error = Result<Int, SomeError>(error: .mistake)
```

In this case, the index does not contain a reference to the initializers. This can be seen in Xcode, where searching for references to those initializers produce only the initializers themselves.

This problem only happens when the generic types are explicit. If they're inferred, then the index does correctly include proper references. Compare:

``` swift
let value: Result<Int, SomeError> = Result(value: 5)
let error: Result<Int, SomeError> = Result(error: .mistake)
```

In this case, the index works as expected.

In the problem case, the indexstore record files of the callers does not contain references to the initializer's symbol (USR).

Attached is a sample project, and a couple screenshots showing Xcode can't find references even though they exist in the test target.

### PR DESCRIPTION
**Pull request by keith**
Previously in the case of a constructor like `A<Int>(value: 1)` `Fn->getLoc()` returned the location of `>(value: 1)` while the actual location we're looking for is correctly the start of `A<Int>(value: 1)`. This adjusts the location we're looking up to use the start location of the constructor instead.

Fixes: https://github.com/apple/swift/issues/54532

### CODE REVIEW

**Comment by keith** [comment]
@swift-ci please test

**Review by hamishknight — APPROVED** [review]
Thanks!

**Comment by keith** [comment]
the failure here is actually real, the problem is with nested types it moves the initializer to the parent type, which is wrong 😕

File: test/IDE/annotation.swift [hunk 1]
```diff
@@ -129,7 +129,7 @@ class GenCls<T> {
 }
 
 func test2() {
-  // CHECK: <Class@[[@LINE-19]]:7>GenCls</Class><<iStruct@>Int</iStruct>>()
+  // CHECK: <Ctor@[[@LINE-17]]:3-Class@[[@LINE-19]]:7>GenCls</Ctor><<iStruct@>Int</iStruct>>()
```
Comment (keith) [inline test/IDE/annotation.swift:132]: this was wrong before for the same reason

**Comment by keith** [comment]
fixed that failure with a new way to compute the correct location that seems to work in all cases

**Comment by keith** [comment]
this breaks the `Foo.init` case by putting a reference to the constructor on both `Foo` and `.init`. New test incoming

**Comment by keith** [comment]
pushed a version w/ that new case fixed, and `((A))(value: 1)` 🙃

**Comment by keith** [comment]
@swift-ci please test

**Comment by keith** [comment]
@swift-ci please test

**Comment by keith** [comment]
I hope re-pushing cancels previously running tests 😬

**Comment by hamishknight** [comment]
>  I hope re-pushing cancels previously running tests

It does (or more accurately, triggering the tests again cancels any previous runs) :)

File: lib/IDE/SourceEntityWalker.cpp [hunk 2]
```diff
@@ -815,9 +815,18 @@ passReference(ValueDecl *D, Type Ty, SourceLoc BaseNameLoc, SourceRange Range,
...
     if (!CtorRefs.empty() && BaseNameLoc.isValid()) {
-      Expr *Fn = CtorRefs.back()->getFn();
-      if (Fn->getLoc() == BaseNameLoc) {
-        D = ide::getReferencedDecl(Fn).second.getDecl();
+      ConstructorRefCallExpr *Ctor = CtorRefs.back();
+      SourceLoc CtorLoc = Ctor->getFn()->getLoc();
+      if (auto *TE = dyn_cast<TypeExpr>(Ctor->getBase()))
+        CtorLoc = TE->getTypeRepr()->getWithoutParens()->getLoc();
+
+      bool isImplicit = true;
```
Comment (bnbarham) [inline lib/IDE/SourceEntityWalker.cpp:823]: Should probably default to false?

File: lib/IDE/SourceEntityWalker.cpp [hunk 3]
```diff
@@ -815,9 +815,18 @@ passReference(ValueDecl *D, Type Ty, SourceLoc BaseNameLoc, SourceRange Range,
 
   if (auto *TD = dyn_cast<TypeDecl>(D)) {
     if (!CtorRefs.empty() && BaseNameLoc.isValid()) {
-      Expr *Fn = CtorRefs.back()->getFn();
-      if (Fn->getLoc() == BaseNameLoc) {
-        D = ide::getReferencedDecl(Fn).second.getDecl();
+      ConstructorRefCallExpr *Ctor = CtorRefs.back();
+      SourceLoc CtorLoc = Ctor->getFn()->getLoc();
+      if (auto *TE = dyn_cast<TypeExpr>(Ctor->getBase()))
+        CtorLoc = TE->getTypeRepr()->getWithoutParens()->getLoc();
```
Comment (bnbarham) [inline lib/IDE/SourceEntityWalker.cpp:821]: Seems worth of a comment to me. Without any background it seems pretty odd that we're grabbing the base here.

**Review by bnbarham — COMMENTED** [review]
Thanks Keith!

File: lib/IDE/SourceEntityWalker.cpp (hunk 2 above)
Comment (keith) [reply lib/IDE/SourceEntityWalker.cpp:823]: yea i guess so, done

**Comment by keith** [comment]
@swift-ci please test

**Comment by keith** [comment]
@swift-ci please test

File: lib/IDE/SourceEntityWalker.cpp [hunk 4]
```diff
@@ -815,9 +815,22 @@ passReference(ValueDecl *D, Type Ty, SourceLoc BaseNameLoc, SourceRange Range,
...
     if (!CtorRefs.empty() && BaseNameLoc.isValid()) {
-      Expr *Fn = CtorRefs.back()->getFn();
-      if (Fn->getLoc() == BaseNameLoc) {
-        D = ide::getReferencedDecl(Fn).second.getDecl();
+      ConstructorRefCallExpr *Ctor = CtorRefs.back();
+      SourceLoc CtorLoc = Ctor->getFn()->getLoc();
+      // Get the location of the type, ignoring parens, rather than the start of
+      // the Expr, to match the lookup.
+      if (auto *TE = dyn_cast<TypeExpr>(Ctor->getBase()))
+        CtorLoc = TE->getTypeRepr()->getWithoutParens()->getLoc();
```
Comment (hamishknight) [inline lib/IDE/SourceEntityWalker.cpp:823]: I think there may be some other TypeReprs that this doesn't quite handle correctly e.g `X?(y)`, I believe the location in that case will be on the `?`. That being said, I'm still happy to take this given it's a strict improvement over what we have currently. I've started looking into refactoring this so we can walk the references separately, which should avoid the need to do this.

**Review by hamishknight — APPROVED** [review]

File: lib/IDE/SourceEntityWalker.cpp (hunk 4 above)
Comment (keith) [reply lib/IDE/SourceEntityWalker.cpp:823]: Hrm what's the scenario more specifically? this code:

```swift
protocol P {
    init(value: Int)
}

func foo<T: P>(A: T.Type?) {
    _ = A?(value: 0)
}
```

Forces you to do `A?.init` so it ends up working fine

Comment (hamishknight) [reply lib/IDE/SourceEntityWalker.cpp:823]: I mean like this:

```swift
struct S {}

func foo(_ x: S) {
  _ = S?(x)
}
```

Optional has an init that takes the wrapped value

Comment (keith) [reply lib/IDE/SourceEntityWalker.cpp:823]: ah yep, that case doesn't work you're right, i'll file that example

Comment (keith) [reply lib/IDE/SourceEntityWalker.cpp:823]: [hrm I guess actually the reference there would be one for Optional's initializer not `S`'s? ](https://github.com/apple/swift/issues/65723)

Comment (hamishknight) [reply lib/IDE/SourceEntityWalker.cpp:823]: Thanks!
